### ISSUE TITLE
Questions about glslang memory allocations

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#1004]
Hi, while checking for memory allocations when running glslangValidator, I noticed that InitializeMemoryPools function is called, but FreeGlobalPools function would not be called. Just want to check if it's alright or something to fix.

Also, more generally, can you please give some details about how glslang manages the memory allocation on the heap? I see lots of "new" object allocated but not released, however it looks like it's using its own memory buffer and allocator, then release everything at once at the end? I'm asking because I'm calling glslang from an external program and want to make sure they won't be any conflict.

Thanks,

**Comment by johnkslang** [comment]
Check out #976.

>  it looks like it's using its own memory buffer and allocator, then release everything at once at the end?

Yes. This should work independently (not in conflict) with memory schemes used in other parts of the same process.
