### ISSUE TITLE
Tessellation control shaders targeting #version 450 Multiview issues

### ISSUE THREAD

**Issue by zkellsworth** [KhronosGroup/glslang#1016]
I'm not sure if this belongs here, or with SPIRV-Tools, or if its by design. When creating a tessellation control shader (example shader here: [t.tesc.txt](https://github.com/KhronosGroup/glslang/files/1223365/t.tesc.txt)) that targets #version 450, part of the emitted assembly will include **MemberDecorate 46(gl_PerVertex) 4 BuiltIn ViewportIndex**. This Builtin type isn't present in other target version such as #440. 

Is the #450 supposed to include this built in type when building a tessellation control shader? If so then please feel free to close this, and I will report with SPIRV-Tools. Whats happening is the SPIRV-Tools will complain about this built in type with message **SPIR-V module not valid: Operand 4 of MemberDecorate requires one of these capabilities: MultiViewport**

I'm wondering if its just a catch-22, where SPIRV modules don't support multiviewport, but the #version 450 spec requires it.

**Comment by johnkslang** [comment]
Without extensions, a viewport index can only be emitted by the geometry stage and accepted only into the fragment stage.

I assume yes, but were you using an extension with GLSL that allowed a viewport index to be used in other ways?

When the SPIR-V generator translates that, it should also declare a capability and/or an extension that allows it to have this additional behavior.

**Comment by zkellsworth** [comment]
No glsl extensions, in fact the linked t.tesc.txt is the the shader I'm using that causes the issue. When that is compiled using the glslang compiler MemberDecorate 46(gl_PerVertex) 4 BuiltIn ViewportIndex is emitted as part of the compiled source (when viewed with either spirv-as or glslangvalidator -H). Unless targeting 450 is silently enabling extensions I'm not doing so manually.

**Comment by johnkslang** [comment]
These showed up in version 450 to support some extensions. They are harmless in the AST when supporting validation. However, they should not get passed through to the SPIR-V. Will fix soon.
