### ISSUE TITLE
Invalid SPIR-V is generated

### ISSUE THREAD

**Issue by lmagder** [KhronosGroup/glslang#1018]
Not sure if this is HLSL-related or not but the source language is HLSL.

Compiling the attached code with glslc `glslc.exe -o BRDFMaterialPS.spirv -x hlsl -fentry-point=BRDFMaterialPS -fshader-stage=frag
ment BRDFMaterialPS.preproc`

Results in a module which fails spirv-val and the validation layers with the error `error: 3954: OpStore Pointer <id> '573's type does not match Object <id> '34's type.`. I'm using SDK 1.0.57.0`

Not sure if this is a validation error or a compiler error since at first glance the shader seems to work anyway.
[ReproFiles.zip](https://github.com/KhronosGroup/glslang/files/1236037/ReproFiles.zip)

**Comment by johnkslang** [comment]
We have done existing problems with structure types being created and aliased, but I haven't looked in the zip yet (the raw shader would be better).

**Comment by lmagder** [comment]
I thought it might be a dup with that issue, but I removed structs from the code path and it still reproduces. 😞 

The zip does contain the preprocessed shader source, it was just pretty long so I didn't post it inline.

**Comment by johnkslang** [comment]
Thanks. Looks like a failure to implicitly promote the returned float3 to the return type of float4.  Will look at fixing.

**Comment by johnkslang** [comment]
Turns out this is not valid HLSL: fxc says:

> error X3017: cannot implicitly convert from 'float3' to 'float4'

glslang is not an fxc validator, but I also see you are using layout and constructors that glslang supports but fxc does not, making it hard to use fxc as a validator. So, it is difficult.

This shader contains many `float3` vs. `float4` type mismatches that fxc would reject. I suggest generating the code with better type matching in general, rather than so freely mixing `float3` and `float4`.

**Comment by johnkslang** [comment]
Oh, I will still add a check for this in glslang, it just won't support this shader.

**Comment by lmagder** [comment]
Thanks for looking into it. I think your fix is the right one. This shader is invalid as you say. I actually wasn't testing with FXC, just glslc so I never noticed. My impetus for using HLSL was actually just personal preference over GLSL and not porting.
