### ISSUE TITLE
Error "non-opaque uniform variables need a layout(location=L)" with --auto-map-locations

### ISSUE THREAD

**Issue by rikusalminen** [KhronosGroup/glslang#1019]
The error message "non-opaque uniform variables need a layout(location=L)" is emitted when compiling GLSL shaders without explicit uniform locations even when `--auto-map-locations` is given on glslang command line.

This makes it hard to validate GLSL shaders that need to be compatible with old GL drivers (not using SPIR-V).

I have two questions:
1. Which specification requires layout(location) for non-opaque uniform variables? GL_ARB_gl_spirv? I am unable to find the appropriate specification.
2. What is --auto-map-locations intent? Is it supposed to auto-assign locations for non-opaque uniforms too?

My use case is that I'm running glslangValidator to validate GLSL but not using the resulting SPIR-V blobs because I try to support some older hardware/drivers without the SPIR-v GL extension.

For example, the following valid (but old) GLSL shader (simplest.vert):
```
#version 330

uniform mat4 projection_matrix;

void main() {
    vec4 pos = vec4(gl_VertexID >> 1, gl_VertexID & 1, 0.0, 1.0);
    gl_Position = projection_matrix * pos;
}
```

Will produce the following error:
```
$ glslangValidator --auto-map-locations -G -o simplest.vert.spv simplest.vert
ERROR: simplest.vert:3: 'projection_matrix' : non-opaque uniform variables need a layout(location=L)
ERROR: 1 compilation errors.  No code generated.


ERROR: Linking vertex stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```

This behavior was introduced by commit: 67eb497002d1d9b09831c4d3bb2b510dd148d582  SPV/OpenGL: Require locations on non-opaque uniform variables.

This patch will disable the error when --auto-map-locations is provided on the command line:

```
From 411d61f5a5bb4ccd16428f1378a9857bc624845d Mon Sep 17 00:00:00 2001
From: Riku Salminen <rsalminen@iki.fi>
Date: Mon, 21 Aug 2017 13:20:06 +0300
Subject: [PATCH] SPV/OpenGL: No error with --auto-map-locations

When --auto-map-locations is provided on command line, do not trigger
error "non-opaque uniform variables need a layout(location = L)" in
TParseContext::transparentOpaqueCheck().
---
 glslang/MachineIndependent/ParseHelper.cpp | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/glslang/MachineIndependent/ParseHelper.cpp b/glslang/MachineIndependent/ParseHelper.cpp
index 687c2118..e4c81322 100644
--- a/glslang/MachineIndependent/ParseHelper.cpp
+++ b/glslang/MachineIndependent/ParseHelper.cpp
@@ -2488,7 +2488,9 @@ void TParseContext::transparentOpaqueCheck(const TSourceLoc& loc, const TType& t
         if (spvVersion.vulkan > 0)
             vulkanRemoved(loc, "non-opaque uniforms outside a block");
         // OpenGL wants locations on these
-        if (spvVersion.openGl > 0 && !type.getQualifier().hasLocation())
+        // (unless --auto-map-locations is passed on glslang command line)
+        if (spvVersion.openGl > 0 && !type.getQualifier().hasLocation() &&
+            !intermediate.getAutoMapLocations())
             error(loc, "non-opaque uniform variables need a layout(location=L)", identifier.c_str(), "");
     }
 }
-- 
2.14.1
```

**Comment by johnkslang** [comment]
Answering questions:

1) Yes it should be ARB_gl_spirv that defines this rule. A couple quotes:

>  User-defined interface variables must be decorated with a *Location*

(Though, I could understand that one being taken in the context of input/output.)

> The shaders need to specify explicit locations for all uniform variables.

(Though, that it is in an issue.)

However, there is a general spirit and discussion that all SPIR-V linkage is all done by number (or built-in decoration), not by name.

2) The auto-map-locations was actually intended for input and output variables (cross-stage linkage). Will have to check if it generalizes to uniform variables as well. Having it apply to both may be the best path forward.

**Comment by astillich** [comment]
I ran in this, too. Is there any progress on this? BR
