### ISSUE TITLE
MSVC2012: strtoll not available on this version and earlier

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [KhronosGroup/glslang#1020]
glslang\MachineIndependent\preprocessor\PpTokens.cpp, lines 254, 256, 258, 263, 265, 267 use "strtoll", "atoll" and "strtoull".  These are not available (as I believe) prior to MSVC2013.

Suggestion: replace lines 86..88
```C++
#if (defined(_MSC_VER) && _MSC_VER < 1900 /*vs2015*/)
#define snprintf sprintf_s
#endif
```
with
```C++
#ifdef _MSC_VER
    #if (_MSC_VER < 1900 /*vs2015*/)
        #define snprintf sprintf_s
    #endif
    #if (_MSC_VER < 1800 /*vs2013*/)
        #define strtoll _strtoi64
        #define strtoull _strtoui64
        #define atoll _atoi64
    #endif
#endif
```

**Comment by johnkslang** [comment]
These already exist in Common.h, but protected by `_MSC_VER < 1700` instead of `1800`.  Will fix.
