### ISSUE TITLE
MSVC2012 - isnan/isinf not yet supported

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [KhronosGroup/glslang#1022]
File: \SPIRV\hex_float.h, line 26:
change
```#if defined(_MSC_VER) && _MSC_VER < 1700```
to
```#if defined(_MSC_VER) && _MSC_VER < 1800```

**Comment by johnkslang** [comment]
Not sure I follow yet.  _MSC_VER of 1700 corresponds with Visual Studio 2012, yes?

If so, 2012 is already protected.

**Comment by St0fF-NPL-ToM** [comment]
Yes, 1700 corresponds to MSVC 11 / 2012.  Micro$oft version numbering is far from perfect ;)  I also see a "<=" would have done the same trick, even more correctly ... Thank you for your work!
