### ISSUE TITLE
Add support for GL_ARB_stencil_export via SPV_EXT_stencil_export

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#1023]
Right now, glslang accepts shaders which use the GL_ARB_stencil_export extension and happily just drops the built-in on the floor.  We need real support that actually passes the built-in through.

**Comment by amdrexu** [comment]
I will add it once the SPIR-V header is updated. So please wait for a few days.

**Comment by amdrexu** [comment]
Handled in this: https://github.com/KhronosGroup/glslang/pull/1025
