### ISSUE TITLE
HLSL: Clarification on determining if descriptor is SRV or UAV

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1038]
Currently, there isn't an easy way to determine RW state for an OpVariable whose type type is decorated with Buffer or BufferBlock. It seems that some users have written code to walk the Load/Store ops all the way through the function calls to determine R and RW state.  The logic for this approach is complex and possibly error prone.

#u is the only resource type that is writable and we know this from the HLSL source level. Is it possible to add a NonWritable decoration to the other resource types so reflection parsers can easily determine which resources are UAVs?

I understand that there isn't a clean mapping between HLSL and GLSL on this since buffer (VK_DESCRIPTOR_TYPE_STORAGE_BUFFER) is ambiguous. The other relevant descriptor types do inherently have an R/RW state.

**Comment by johnkslang** [comment]
> Currently, there isn't an easy way to determine RW state for an OpVariable whose type type is decorated with Buffer or BufferBlock. It seems that some users have written code to walk the Load/Store ops all the way through the function calls to determine R and RW state.

If it is **Block** (not **BufferBlock**, not **StorageBuffer**), it is not writable, by the definition SPIR-V.

Agreed that, if not already being done, those that are **BufferBlock** or **StorageBuffer** and not writable should have a **NonWritable** decoration. Is that missing?

> #u is the only resource type that is writable and we know this from the HLSL source level. Is it possible to add a NonWritable decoration to the other resource types so reflection parsers can easily determine which resources are UAVs?

SPIR-V should not add any **NonWritable** decorations to anything that is already defined to be not writable. It is already built in they are not writable.

Do we know more specifically what bug is being corrected by analysis? (E.g., some I mentioned above could be.)

The only thing I can imagine to gain from complex analysis, both at the source and SPIR-V level, is that if something was declared as writable, but then never written to, it could get turned into something non writable, but I'm unclear that would be important, or possibly even if it is correct to do so.

**Comment by LoopDawg** [comment]
Possibly related: #795.  There was quite a bit of discussion there around pinning down storage classes and qualifiers for various HLSL types.

**Comment by chaoticbob** [comment]
Updated ticket title to make more sense. 

Sorry, my initial comments might have been a bit over paranoid. After writing test shaders to explore the matter a bit more, it looks there may be complete formulations for detecting R/RW state. So this may be a non-issue. 

Can @johnkslang or @LoopDawg  sanity check the formulation below:

```RWBuffer``` and ```RWTexture``` translates the following, respectively:
````
 %9 = OpTypeFloat 32
%10 = OpTypeImage %9 Buffer 0 0 0 2 Rgba32f
%13 = OpTypeImage %9 2D 0 0 0 2 Rgba32f
````
The **2** for the ```Sampled``` operand indicates that this is a UAV. Would a **1** and **0** indicate that it's a UAV?

```StructuredBuffer``` translates to ```OpTypeStruct``` that's decorated with both ```BufferBlock``` and ````NonWritable```. Easy to determine this is a SRV.

```RWStructuredBuffer``` translate to ```OpTypeStruct``` that's decorated with only ```BufferBlock```. Easy to determine that it's a UAV.

The other remaining ```Texture```, ```Buffer```, and ```StructuredBuffer``` related types are SRV and UAV depending on which category they fall in.

Is this right?

**Comment by chaoticbob** [comment]
I've tested pretty much every variation I can think of for the this and there's always a path to determine the resource type. Albeit sometimes, it takes a little work.

Closing issue.
