### ISSUE TITLE
HLSL: Buffer<float3> and Buffer<float4> translates to OpTypeImage with Rgba32f

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1040]
Simple question about ```Buffer<float3>``` and ```Buffer<float4>``` and their ```RWBuffer``` counterparts: Both of these seem to translate to something like:
````
%72 = OpTypeImage %12 Buffer 0 0 0 2 Rgba32f
````

My expectation was that ```Buffer<float3>``` would translate to:
````
%72 = OpTypeImage %12 Buffer 0 0 0 2 Rgb32f
````
...since ```Buffer<float>``` and ```Buffer<float2>``` translate to ```R32f``` and ```Rg32f```, respectively. 

Is this the wrong expectation to have?

Test shader:
````
Buffer<float>       roBuf1 : register(t0);
Buffer<float2>      roBuf2 : register(t1);
Buffer<float3>      roBuf3 : register(t2);
Buffer<float4>      roBuf4 : register(t3);
RWBuffer<float>     rwBuf1 : register(u4);
RWBuffer<float2>    rwBuf2 : register(u5);
RWBuffer<float3>    rwBuf3 : register(u6);
RWBuffer<float4>    rwBuf4 : register(u7);
[numthreads(1,1,1)]
void CS(uint slot : SV_GroupID) {
}
````

**Comment by LoopDawg** [comment]
Hmm, I'm not sure there is such a thing, at least if I'm grokking the spec properly.  [Table 3.11](https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.html#Image_Format) lists the possible image formats.  For 32 bits per component, there are 1, 2, and 4 component formats.

The decision about how to map the Buffer's template type is being made in HlslParseContext::getLayoutFromTxType().  It intentionally files float3/float4 into the same bucket.

**Comment by chaoticbob** [comment]
Got it. I checked the Vulkan spec and the base requirement for 3 component float is that it supports vertex buffers. My AMD card does report that i can be used as storage and uniform texel buffer. I'll write a test to see if it does the right thing.

**Comment by arcady-lunarg** [comment]
Closing as it seems the question was answered.
