### ISSUE TITLE
TInputScanner incorrectly initializes its TSourceLoc array "loc"

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [KhronosGroup/glslang#1043]
see `MachineIndependent/Scan.h`@54: only the first TSourceLoc gets its `TSourceLoc.string = -stringBias`.  All further ones stay unchanged at "0".
That is not an issue for glslang itself, but if you were to add functionality like I do, I need to distinguish if the preprocessor currently is parsing from the main source string.  Thus I would look at the `TSourceLoc.string` of a TPpToken, if it's positive, I already passed the preamble.

My solution would be:
add Include/Common.h@225:
`    void init( int stringNum ) { name = nullptr; string = stringNum; line = 0; column = 0; }`
change MachineIndependent/Scan.h@61
`            loc[i].init( i - stringBias );`
remove MachineIndependent/Scan.h@67

Regarding "add Include/Common.h@225": in a complex project like this I rather add a function, than change an existing one, just to make sure my change doesn't break anything else.

**Comment by johnkslang** [comment]
Hopefully no one is depending on existing string number behavior of 0.

I did approximately as you suggested. (Note it is potentially more clear to explicitly set it after calling init().)

I can't test your intention. Next time you might want to just submit a PR that does what you want.

**Comment by St0fF-NPL-ToM** [comment]
I'm sorry, I have zero experience using GIT.  I know this sounds weird, but that's how it is.  I'm using glslang for company-internal tooling, so actually I should have created a fork.  But even that's out of my reach for the moment, as I'm on a very tight schedule.
The things I added are:
- named defines (i.e. lines like `"#define SOME_NAMED_DEFINE"`)
  - record identifiers in such definitions
  - record the identifiers that are tested using some `#ifdef`-constructs
So actually I'm just using glslang for pre-introspection of shaders.  And I must say you did a great job!
