### ISSUE TITLE
Can't set emitted entry point name for GLSL shaders

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1045]
For HLSL compilation, we can use 
     -e foo --source-entrypoint bar ....
to set HLSL function "bar" as an entry point and set its entry point name to "foo".

It would be useful to extend -e to set the entry point for GLSL shaders as well.  This would make it easier to compile modules and later combine them, while avoiding entry point name clashes.

**Comment by johnkslang** [comment]
Deducing that the support you need is `-e <new-name> --source-entrypoint main`, for valid GLSL shaders, yes?
