### ISSUE TITLE
HLSL: Crash in TSymbol::getAsVariable() during parsing simple HLSL shader code

### ISSUE THREAD

**Issue by Andreyogld3d** [KhronosGroup/glslang#1060]
Hi!
i'm using modified version of util function GLSLtoSPV from Vulkan SDK(Samples\API-Samples\utils\util.cpp).
```
bool GLSLtoSPV(const VkShaderStageFlagBits shader_type, const char *pshader, std::vector<unsigned int> &spirv) {
...
    EShMessages messages = (EShMessages)(EShMsgSpvRules | EShMsgVulkanRules | EShMsgReadHlsl);
...
}
```
During parsing of the following shader:
```
const char* hlslVertexShader =
		"struct PSOutput {"
			"float4 pos : SV_POSITION;"
			"float4 color : COLOR0;"
		"};"
		"PSOutput vsMain(in float4 pos : SV_POSITION, in float4 color : COLOR0) {"
			"PSOutput output;"
			"output.pos = pos;"
			"output.color = color;"
			"return output";
		"}";
```
i have access violation in glslang\glslang\MachineIndependent\SymbolTable.h line 373:

`symbol.getAsVariable()->setAnonId(anonId++);`

Visual Studio Debug Output:

```
Exception thrown: read access violation.
glslang::TSymbol::getAsVariable[virtual](...) returned nullptr.
```
Others GLSL shaders are created correctly.
What i do wrong?
I can attach simple test project with precompiled library(SPIRV.lib glslang.lib HLSL.lib SPVRemapper.lib OSDependent.lib`OGLCompiler.lib) if it is required.

**Comment by johnkslang** [comment]
You go through a `setAnonId` path if you are making a structure/block that has no instance name. The `variable()` should have the type of the structure. This includes the `this` for methods that might be inside a struct, so that the methods access to the members. I don't know if you are trying to change structure member function support.

**Comment by Andreyogld3d** [comment]
Hi johnkslang!
>  I don't know if you are trying to change structure member function support.
1) I use precompiled library from glslang project.
2) I use funtion from Vulkan SDK with some modification(EShMsgReadHlsl for glslang::TShader::parse)

Ok, i attached simple project with test code.
[GLSLangTest Visual Studio 2015 test project](https://www.dropbox.com/s/bxjsau2nxbmdt0m/GLSLangTest.zip?dl=0)

**Comment by johnkslang** [comment]
Use TShader::setEntryPoint to say what the SPIR-V entry-point will be. If nothing else is done, this name will also be looked for in the shader source as the source-code entry-point name.

Use TShader::setSourceEntryPoint to say the source-code entry-point name is not the same as the final entry-point name given in TShader::setEntryPoint. The given name will become the entry point, renamed to the name given in TShader::setEntryPoint for the SPIR-V.

**Comment by Andreyogld3d** [comment]
Thanks **johnkslang**, but crash still may exist.

**Comment by johnkslang** [comment]
Yes, I see now; I did not realize this connection. I have fixed it now, thanks.

**Comment by Andreyogld3d** [comment]
**johnkslang** , Thanks, now i have no crash.
