### ISSUE TITLE
Sparse binding sets not properly validated against implementation limits?

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/glslang#1065]
The following shader:

```
#version 450

layout (location = 0) in vec4 pos;
layout (location = 1) in vec4 col;
layout (location = 2) in vec2 uv;

layout (binding = 3328, set = 0) uniform sampler sampler0;
layout (binding = 3200, set = 0) uniform texture2D texture0;

layout (location = 0) out vec4 out_col;

void main()
{
    out_col = col * texture(sampler2D(texture0, sampler0), uv);
}
```

Fails during compilation with the following error:

```
$ glslangValidator -V broken.frag
broken.frag
ERROR: broken.frag:7: 'binding' : sampler binding not less than gl_MaxCombinedTextureImageUnits
ERROR: 1 compilation errors.  No code generated.

ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```

The number of bindings should be within the limits, but it sounds like the compiler is perhaps validating against the binding location numbers instead of the count of bindings. (The expected SPIR-V output can be obtained by removing the explicit binding locations and using the various --shift-* arguments instead.)

**Comment by johnkslang** [comment]
Yes, if bindings can be sparse, I agree with your analysis.

Would like to see if there are differences between OpenGL and Vulkan here.

**Comment by nsubtil** [comment]
The GLSL spec doesn't seem to allow this:

> Valid locations for default-block uniform variable locations are in the range of 0 to the implementation-defined maximum number of uniform locations minus one. Valid locations for subroutine uniforms are in the range of 0 to the implementation-defined per-stage maximum number of subroutine uniform locations minus one.

I'm not sure how this would be validated at compile time in this case, since the implementation is not necessarily known. But in either way, the GLSL spec seems clear that the location indices need to be validated, not just the number of uniforms.

On the other hand, we already seem to rely on a different interpretation here --- the compiler can be tricked into generating the same code with no errors by applying the appropriate offsets in the command line (using `--shift-sampler-binding 3328 --shift-texture-binding 3200` and assigning the uniforms to location 0 in this example).

Given that it looks like we can't do this correctly in the compiler anyway, would it make sense to drop location index validation altogether when compiling for Vulkan?

**Comment by johnkslang** [comment]
We have target-specific validation in glslang. So, we could just check something if it is for OpenGL, and not Vulkan. Note there is also a config file (see usage, .conf) that can specify implementation-dependent limits.

**Comment by johnkslang** [comment]
Is this connected to (or independent of) `sparseBinding`?

**Comment by johnkslang** [comment]
> the compiler can be tricked into generating the same code with no errors by applying the appropriate offsets in the command line (using --shift-sampler-binding 3328 --shift-texture-binding 3200

Yes, but that is conflating validation of shader input with explicit control of generated SPIR-V. Maybe there should be some other checks, or more simply, just combine with a validator that does the right check.

**Comment by johnkslang** [comment]
> Valid locations for default-block uniform variable locations 

That answer is about locations, but the question was about bindings.

Do you have spec language about Vulkan bindings being sparse, so not bounded by this limit, while GLSL is not the case, and how this interacts with Vulkan `sparseBinding`?

**Comment by johnkslang** [comment]
I disabled the test for Vulkan. Let me know if that is incorrect, and if there is a different issue, let's open an issue focused on it.
