### ISSUE TITLE
GLSL to DXIL output?

### ISSUE THREAD

**Issue by capitalknew** [KhronosGroup/glslang#1066]
Hello. I want to ask about support compilation GLSL to DXIL (i.e. DirectX Intermediate Language). I know, sounds crazy, but I think this is possible.

**Comment by johnkslang** [comment]
It would be a different repository, or involve a different repository.  There are tools (SPIRV-cross) that can take glslang SPIR-V and translate to other languages. So, there may be an existing path the finishes in Microsoft's stack to generate DXIL. Reusing glslang as-is makes good sense for parsing the GLSL. However, this is an issue for those repositories, and not this repository.
