### ISSUE TITLE
Constructor not taking precision of its operand

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/glslang#1087]
This issue seems similar to issue #999, but not identical.

Given this code:

```
#version 320 es
layout(location = 0) in mediump vec3 inNormal;
layout(set = 1, binding = 0) uniform Uniforms {
	highp mat4 inMat;
};
layout(location = 0) out highp vec3 Normals;

void main() {
	Normals = normalize(mat3(inMat) * inNormal);
}
```

Glslang is generating SPIR-V with relaxed precision decorations on the `Normalize` and `OpMatrixTimesVector` operations.

We'd expect the mat3 constructor result to take the precision of its operand (highp), and this would propagate to the MatrixTimesVector and the normalize.  But glslang is not propagating highp from the operand of the constructor to its result.

ES 3.2 spec states in section 4.3 Precision Qualifiers:

> For this paragraph, “operation” includes operators, built-in functions, and constructors, and “operand” 
includes function arguments and constructor arguments.  The precision used to internally evaluate an 
operation, and the precision qualification subsequently associated with any resulting intermediate values, must be at least as high as the highest precision qualification of the operands consumed by the operation.

Why does the precision of the mat3 constructor operand not propagate to the result of the mat3 constructor?

**Comment by johnkslang** [comment]
Constructors don't result in a precision. One line before you started quoting:

> Literal constants do not have precision qualifiers. Neither do Boolean variables. Neither do constructors.

For the `*` operator, the left operand (the constructor) has no precision, so by the rule

> In cases where operands do not have a precision qualifier, the precision qualification will come from the other operands.

Hence, the precision of the `mat3(inMat)` is taken from `inNormal`, which is `mediump`, hence in SPIR-V **relaxedPrecision**.

**Comment by stevec611** [comment]
Thank you for the explanation.
