### ISSUE TITLE
Q: how to access a TShader's TIntermediate without linking

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [KhronosGroup/glslang#1088]
Hi!

I need access to the full, unoptimized and unlinked interface of a shader.  I understood the code that far, that after parsing a shader I need to access its TIntermediate and traverse it down into the sequence with op == EOpLinkerObjects.  These Linker Objects can then be examined to acquire the shader's input interface.
As TShader::intermediate is private, and there's no accessor function present, how can I achieve traversal without having to add the shader into a TProgram object and linking it (TProgram provides "`getIntermediate( stage )`", but only after linking, and this operates with the linked TIntermediate)?

Thanks a lot in advance and have a nice weekend!
Stefan

**Comment by johnkslang** [comment]
If you have a valid use for public exposure of the intermediate, it seems a public method should simply be added.  I'll do that. If you need different semantics (or if a const reference is okay), make a PR that tweaks the one I submit.
