### ISSUE TITLE
HLSL: Crash for structure cast of scalar with opaque type mixed in

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1091]
The shader below causes a segfault at https://github.com/KhronosGroup/glslang/blob/master/hlsl/hlslParseHelper.cpp#L2751:
````
struct Params {
  Texture2D tex;
  float     x;
};

float4 main(float4 pos : POSITION) : SV_POSITION
{
  Params params = (Params)0;
  return pos;
}
````

Was expecting to get an error due to the Texture2D object being present. ```membersR``` is null.

**Comment by johnkslang** [comment]
Note that this is not valid HLSL, and writing a validator has been lowest priority, as fxc can be used for that.

However, not opposed to catching all syntax issues, or issues preventing making an AST of some meaning, so will have a look.

**Comment by johnkslang** [comment]
This will now say:

```
ERROR: t.vert:8: 'initializer list' : cannot implicitly initialize opaque members
ERROR: t.vert:8: ' const structure{ temp texture2D tex,  temp float x}' : cannot construct with these arguments
```
