### ISSUE TITLE
HLSL: Mixed type struct flattening + flow control errors

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1092]
The shader below compiles fine in FXC, but produces errors that seem to be related to flattening:
````C
Texture2D tex;

struct Packed {
  Texture2D     tex;
  float3        pos[1];
  float2        uv[1];
  float         x;
  int           n;
};

float4 main(float4 pos : POSITION) : SV_POSITION
{
  Packed packed;
  packed.tex    = tex;
  packed.pos[0] = float3(0, 0, 0);
  packed.uv[0]  = float2(0, 1);
  packed.x      = 1.0;
  packed.n      = 3;

  if (packed.x < 10.0) {
    for (int i = 0; i < 1; ++i) {
      packed.pos[i].xy += packed.uv[i];
    }
  }

  for (int i = 0; i < 1; ++i) {
    if (packed.x < 10.0) {
      packed.pos[i].xy += packed.uv[i];
    }
  }  

  return pos + float4(packed.pos[0], 0);
}
````

Errors:
````
$ glslangValidator -V -D -S vert -e main -o struct_array_elem_assign.spv struct_array_elem_assign.hlsl
struct_array_elem_assign.hlsl
ERROR: struct_array_elem_assign.hlsl:23: 'flattenShadow' : Invalid variable index to flattened array
ERROR: struct_array_elem_assign.hlsl:23: 'swizzle or member' : Expected
ERROR: struct_array_elem_assign.hlsl:23: 'for sub-statement' : Expected
ERROR: struct_array_elem_assign.hlsl:23: 'then statement' : Expected
struct_array_elem_assign.hlsl(23): error at column 20, HLSL parsing failed.
ERROR: 5 compilation errors.  No code generated.
````

Happens in both cases: if/for and for/if.

**Comment by johnkslang** [comment]
We should not need to flatten the array part of this hierarchy. (The flattening in doing more than it needs to.)  Will look at fixing.

**Comment by johnkslang** [comment]
Update: I have a design (cross checked with @LoopDawg too, who did some of this) locally that theoretically does a nice job solving this in general. It is correctly working for the policy of what to flatten. Pending is ensuring assignment between inconsistently flattened types. Should be in a day or two.

**Comment by chaoticbob** [comment]
Excellent news!

**Comment by johnkslang** [comment]
The fix is now present in #1102.

**Comment by chaoticbob** [comment]
Thanks, John and @LoopDawg. 

I tested this against the two test cases I had. The first one compiles through without a problem. The second one (the example from above) produces:
````
WARNING: AST will form illegal SPIR-V; need to transform to legalize
````

I assume this is expected and spirv-opt will legalize?

**Comment by johnkslang** [comment]
Yes, that is the intention.
