### ISSUE TITLE
Generating OpAtomicLoad and OpAtomicStore

### ISSUE THREAD

**Issue by dylanede** [KhronosGroup/glslang#1095]
As far as I can see at the moment, there doesn't seem to be a way to generate these opcodes from GLSL. Is that correct? How are atomic loads and stores from/to shared memory meant to be achieved without these primitives?

**Comment by johnkslang** [comment]
The OpenGL `atomicCounter()` built-in should generate **OpAtomicLoad**. I believe you are right that there is not a GLSL path to generate **OpAtomicStore**.
