### ISSUE TITLE
HLSL test failures using Clang 3.9 Release build

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1101]
This is a leftover issue from #1071 

The original failures:
https://travis-ci.org/KhronosGroup/glslang/jobs/279619092#L4538

[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_attribute_expression_comp, where GetParam() = 16-byte object <78-E0 67-00 00-00 00-00 98-4F 6C-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_forLoop_frag, where GetParam() = 16-byte object <6C-E5 67-00 00-00 00-00 09-E0 67-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_implicitBool_frag, where GetParam() = 16-byte object <61-E8 67-00 00-00 00-00 98-4F 6C-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_loopattr_frag, where GetParam() = 16-byte object <7B-EC 67-00 00-00 00-00 98-4F 6C-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_struct_split_array_geom, where GetParam() = 16-byte object <64-F4 67-00 00-00 00-00 98-4F 6C-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_struct_split_trivial_geom, where GetParam() = 16-byte object <D9-F4 67-00 00-00 00-00 98-4F 6C-00 00-00 00-00>

I have seen the problem again, in the Shaderc build bots which also run Glslang tests:

https://travis-ci.org/google/shaderc/jobs/287198962#L5387 

[  FAILED  ] 6 tests, listed below:
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_attribute_expression_comp, where GetParam() = 16-byte object <CA-CB 75-00 00-00 00-00 72-41 7A-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_forLoop_frag, where GetParam() = 16-byte object <06-D1 75-00 00-00 00-00 5B-CB 75-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_implicitBool_frag, where GetParam() = 16-byte object <FB-D3 75-00 00-00 00-00 72-41 7A-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_loopattr_frag, where GetParam() = 16-byte object <15-D8 75-00 00-00 00-00 72-41 7A-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_struct_split_array_geom, where GetParam() = 16-byte object <FE-DF 75-00 00-00 00-00 72-41 7A-00 00-00 00-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_struct_split_trivial_geom, where GetParam() = 16-byte object <73-E0 75-00 00-00 00-00 72-41 7A-00 00-00 00-00>

Both logs have more detailed diffs for the generated SPIR-V.

The Shaderc bot run shows that the only configuration that fails is Clang on Linux in Release build.  @antiagainst says the default Clang in Travis is Clang 3.9.  He has downgraded Clang to 3.6 in the Glslang Travis config.

But this should be fixed eventually.

I can speculate it might be a number of things.  If I understand correctly, this started showing up around the time of adding HLSL legalization passes. If it happens to be an indeterminate-ordering problem in the SPIRV-Tools optimization passes, then please followup with a SPIRV-Tools bug.

**Comment by arcady-lunarg** [comment]
Closing as clang 3.9 is no longer relevant.
