### ISSUE TITLE
GLSL: SHRT_MIN over -1 constant fold is inconsistent with INT_MIN/LLONG_MIN over -1.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#1130]
`INT_MIN / -1` and `LLONG_MIN / -1` constant fold to `INT_MIN` and `LLONG_MIN` respectively, but since `int16_t` is stored in an `int`, so [when it is assigned `(int) 0x8000`](https://github.com/KhronosGroup/glslang/blob/master/glslang/MachineIndependent/Constant.cpp#L221), it widens to positive int `0x00008000`, rather than `0xffff80000` (`(int) -32768`).

**Comment by xorgy** [comment]
@johnkslang In addition to fixing this as-is, I think it might be a good idea to add proper 16-bit integer constant methods to `TConstUnionArray`, let me know if this is worthwhile and I'll write up an issue for it.

**Comment by johnkslang** [comment]
Perhaps, starting as an issue.

I've only worked closely with the 32-bit semantics (the only semantics in the core specification). 
For the new issue, and also for the current issue, where is the specification language for combining 16-bit literal integers coming from?

(It looks like the authors are treating them as promoting quickly to integer.)

**Comment by xorgy** [comment]
@johnkslang Yeah, I gleaned that they promote to int (though I don't know if they promote even for int16_t-int16_t operations), but in this case it was storing to an `int16_t` with a value greater than `INT_MAX` (as you can see in the test output diff). Definitely worth another look w.r.t. the arithmetic, but storing an int constant greater than INT_MAX to int16_t is a straightforward bug.

**Comment by xorgy** [comment]
I have [a branch which contains a tentative fix for this issue](https://github.com/KhronosGroup/glslang/compare/master...xorgy:const-fold-shrt-min-over-negative-one), but we don't yet know enough (see conversation in #1129 about the same commit as shown in this branch, which was removed from the PR).

**Comment by arcady-lunarg** [comment]
This was fixed by #1129, and the behavior is consistent between integer lengths now.
