### ISSUE TITLE
New toolchain dependency on Python2

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/glslang#1132]
The recently added update_glslang_sources.py requires Python2, which is a new dependency, affecting downstream repositories that use glslang (such as LVL)

Would it be possible to adjust that script to either use Python3, or locally available script languages (i.e. .bat and Bash)?

**Comment by johnkslang** [comment]
I believe @greg-lunarg has done this now, through a63622286f1393e5675a2239286199f14260b46a.
