### ISSUE TITLE
glslangValidator.exe -s should print all fatal errors to stderr

### ISSUE THREAD

**Issue by cleak** [KhronosGroup/glslang#1135]
It seems like glslangValidator.exe -s should still print all fatal errors, rather than some, and they should go out on stderr. There are two parts to this:

1. Not all fatal errors are printed with -s. For example, a bad file path will result in "Error unable to open input file (use -h for usage)" with -s given. However, a valid file path with invalid contents will print nothing with -s.
2. When fatal errors are printed, they should be printed to stderr. In effect, this would make -s "suppress all info and warning messages". Only explicitly requested output will be sent to stdout (such as -i). #1134 should cover most of this.

**Comment by johnkslang** [comment]
> Only explicitly requested output will be sent to stdout (such as -i)

Note that in "validator" mode, incorrect syntax and semantics are "requested output".

**Comment by cleak** [comment]
It seems desirable to output fatal errors for whatever mode -s is working with. In validator mode that would mean syntax and semantic errors aren't fatal. In most other modes that would mean they are fatal. I'm ambivalent as to whether the split behavior and added complexity is worth it with this in mind.

**Comment by johnkslang** [comment]
Today, -s is only about whether the file-name/syntax/semantic errors are reported.  That's it.

All truly fatal errors are still printed independent of -s. Then, the user has the choice to see the syntax/semantic errors or not.  I'm unclear what the ask is for this issue. I can make the usage more clear that is all -s does.

**Comment by johnkslang** [comment]
With fatal errors now going to stderr, and -s clarified to be about the reporting of syntax/semantic errors, closing this. If we need another more specific issue about stderr that's not yet addressed, let's start a new issue.
