### ISSUE TITLE
HLSL: interface matching and gl_PerVertex

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/glslang#1136]
As per the Vulkan spec:

> Any variable decorated with Position must be declared as a four-component vector of 32-bit floating-point values.

For VS/PS, it is easy to handle since the entity annotated with `SV_Position` is of vector type. For HS/DS/GS, we have an additional arrayness over the base type. To make sure we comply with the above requirement (and also the similar ones for `ClipDistance` and `CullDistance`), I think we need to group the generated builtins for `Position`, `ClipDistance`, and `CullDistance` into the `gl_PerVertex` struct, and declare an array of appropriate size of such struct, instead of declaring one stand-alone array for each builtin.

If that is correct, it seems the current implementation, which directly [decorates array variable with `Postion` builtin](https://github.com/KhronosGroup/glslang/blob/715c353a15836e5ae192a64a4cf54e2ce7e8d66a/Test/baseResults/hlsl.clipdistance-4.geom.out#L657), needs to be fixed. Also for the handling for `ClipDistance` and `CullDistance`.

What's more, since builtin interface blocks participate in interface matching, to make sure that we can properly link different stages, I think we also need to generate `gl_PerVertex` struct in VS output.

The above seems to be in accord with how we handles these builtins in GLSL.

cc @ehsannas @chaoticbob

**Comment by johnkslang** [comment]
@antiagainst what you are saying seems correct. Agreed that at minimum, the interfaces should match.

However:
- Matching is generally modulo the extra level of arrayness added on to some interfaces.
- Are we completely sure Vulkan does not support this? Vulkan specifically requires the structure?

**Comment by ehsannas** [comment]
+1. Based on my understanding of the two specs, I also agree with @antiagainst

**Comment by antiagainst** [comment]
> Matching is generally modulo the extra level of arrayness added on to some interfaces.

Yep. Vulkan spec specifically says that:

> Tessellation control shader per-vertex output variables and blocks, and tessellation control, tessellation evaluation, and geometry shader per-vertex input variables and blocks are required to be declared as arrays, with each element representing input or output values for a single vertex of a multi-vertex primitive. For the purposes of interface matching, the outermost array dimension of such variables and blocks is ignored.

> Are we completely sure Vulkan does not support this? Vulkan specifically requires the structure?

Actually I'm not 100% certain about this case. Although there is no direct requirements for `gl_PerVertex` in the Vulkan spec, but my reading of the Vulkan spec suggests that it's illegal to create standalone `Postion`/`ClipDistance`/`CullDistance` in HS/DS/GS with the extra arrayness, based on the reasons listed below. I'd really appreciate everyone's comments on this.

1. The immediate problematic part is the requirements for each [BuitIn](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#interfaces-builtin-variables) in the Vulkan spec. Apart from the `Position` builtin mentioned in the above, for `ClipDistance`, we also have:

> In tessellation control, tessellation evaluation, or geometry shaders, any variable decorated with ClipDistance must not be in a storage class other than Input or Output.

> Any variable decorated with ClipDistance must be declared as an array of 32-bit floating-point values.

There are strict requirements over the type of the `ClipDistance` builtin, like `Position`. So if we create a standalone variable for `ClipDistance` in GS input, it will be array of array of floats, which does not comply with the Vulkan spec. It might be an oversight in the Vulkan spec to not mention we need to ignore the outermost arrayness when handling standalone builtins in HS/DS/GS, but I think that's unlikely since there is directly a sentence in the above mentioning the storage class requirements of `ClipDistance` for all supported shaders, including HS/DS/GS.

2. Besides, for interface matching regarding builtins, Vulkan spec says:

> Built-ins only participate in interface matching if they are declared in such a block. 

So builtins does not participate in interface matching if they are not declared in a builtin interface block, which means the first quote from the Vulkan spec (in this reply) about ignoring outermost arrayness for interface matching may not apply for standalone builtins. Standalone builtins does not enjoy the benefits of ignoring the outermost arrayness, and their is no implicit amendment over the type requirements for standalone `Postion`/`ClipDistance`/`CullDistance`. This further forbids we declare them as standalone variables.

The above is to my best effort. I may have neglected some parts of the Vulkan spec that saying something different, and I'm happy to learn about it. :)

**Comment by antiagainst** [comment]
And if we generate `gl_PerVertex` in one stage, to make sure we can link different stages, we need to generate `gl_PerVertex` in pretty much all vertex processing stages because of the 

> Built-ins only participate in interface matching if they are declared in such a block.

requirement for builtin interface blocks.

**Comment by antiagainst** [comment]
cc @dneto0

**Comment by johnkslang** [comment]
Adding more to my last note: GLSL for #version 140 is also not making a block to hold Position, and none of the HLSL tests make the block, so for HLSL I don't think there is a block in one stage mismatching a non block in another.

**Comment by antiagainst** [comment]
Thanks for the additional information, @johnkslang! Agreed. The current implementation does not have block-vs-non-block mismatching right now. My comment previously was saying that if we make the change to emit `gl_PerVertex`, it could be a matching problem if we don't do it for all vertex processing stages, since Vulkan spec says:

> At an interface between two non-fragment shader stages, the built-in interface block must match exactly, as described above. At an interface involving the fragment shader inputs, the presence or absence of any built-in output does not affect the interface matching.

PS is special regarding builtin interface block matching.

If I get it correctly, `#version 140` [is for](https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions) OpenGL 3.1, which does not have [HS](https://www.khronos.org/opengl/wiki/Tessellation_Control_Shader), [DS](https://www.khronos.org/opengl/wiki/Tessellation_Evaluation_Shader), [GS](https://www.khronos.org/opengl/wiki/Geometry_Shader)? So it does not need the block for solving the extra arrayness?

**Comment by johnkslang** [comment]
I had not yet processed some earlier comments.  Key ones:

> It might be an oversight in the Vulkan spec to not mention we need to ignore the outermost arrayness when handling standalone builtins in HS/DS/GS

Yes, I think so. Everyone thinks in terms of this arrayness stripped before applying rules.

> Built-ins only participate in interface matching if they are declared in such a block.

Note how this current rule actually reinforces the position that loose interface variables are allowed. It does not say they must be in a block, it only says the matching is done when they are in a block.

>  Standalone builtins does not enjoy the benefits of ignoring the outermost arrayness

Yes, they must, there is no alternative. The spec. language needs to be more careful about whether the rules are implicitly assuming that extra arrayness is stripped before the rule applies.

**Comment by johnkslang** [comment]
Is there a glslang bug here? I don't see it yet. I think you possibly found a spec. clarification, though that depends on whether you are reading the spec as if the outer arrayness is removed before appyling the rules, which is what we tend to do. Is it stating that incorrectly?

**Comment by antiagainst** [comment]
Yep, I'm convinced that this is more like a spec clarification problem. Then there are no issues for glslang. I'll file a bug against the Vulkan spec. :)

**Comment by antiagainst** [comment]
Thanks, @johnkslang!
