### ISSUE TITLE
Acquire symbol table

### ISSUE THREAD

**Issue by tim37021** [KhronosGroup/glslang#1137]
HI, I have a plan to write an glsl extension for editor. I would like to have some symbol querying(like figure below) and auto completion functionalities
It seems that symbol table is a private structure in glslang, am I right? Is it possible for now to do that?

![image](https://user-images.githubusercontent.com/5507113/32232043-1580a4f4-be92-11e7-8112-6435d5779b45.png)

**Comment by johnkslang** [comment]
The symbol table is not a stable thing. It grows and shrinks with scope changes, and is not present at all once parsing completes. All type information is in the resulting AST nodes.

There might be many variables named "x". You cannot out of context just go look for "x" in the symbol table. Rather, if you have the right AST node (name will be "x"), that node will know all about the right "x".

**Comment by tim37021** [comment]
I see. Is there any plan to have tool for integration like clang?

**Comment by johnkslang** [comment]
There are some debugger plans, especially when SPIR-V is involved, and compiling with -g gives lots debug names, line numbers, and source code to help. That's about all I know.
