### ISSUE TITLE
HLSL shader fails to compile with "spir instruction terminated too early"

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/glslang#1138]
The following HLSL shader is causing some trouble with glslang:

```
struct VSOut
{
    float4 Pos : SV_POSITION;
};


float4 Func1()
{
    float4 OutputColor = (1,0,0,0);
    return OutputColor;
    float4 OutputColor2 = (0,1,0,0);
    return OutputColor2;
}

float4 BugRepro(VSOut In) : SV_TARGET
{
    return Func1();
}
```

```
nsubtil@bender:~$ glslangValidator -D -V -S frag -e BugRepro -o simple.out simple.hlsl
simple.hlsl
spir instruction terminated too early
```

Adding `-Od` causes the problem to go away. Tested with TOT glslang (commit 715c353a1).

**Comment by johnkslang** [comment]
Doesn't that specifically mean it is an issue with the SPIR-V tools, and not with glslang?

**Comment by johnkslang** [comment]
Maybe because of the early return? There might be some problems with the inliner.

@greg-lunarg ?

**Comment by Dragon31337** [comment]
Yes, It is because of early return; when it's removed the shader compiles just fine. But this is completely valid to have early return.

**Comment by johnkslang** [comment]
Yes, an early return is all these: 
- valid
- is not an issue for glslang proper
- may or may not be root cause, even if removing it makes the problem go away
- if it is the problem, may be something not yet supported by SPIRV-Tools/opt, hence asking them

**Comment by greg-lunarg** [comment]
I will take a look.

Thanks,
Greg


Greg Fischer

Project Manager and Senior Engineer

LunarG, Inc. - 3D Driver Innovations

greg@lunarg.com <alan@lunarg.com>

**Comment by greg-lunarg** [comment]
Bug in remapper which is used to get rid of dead stuff that spirv-opt still doesn't get rid of (but will ultimately).

The bug was caused by a dead function scope variable left by the FE which normally aren't left but might be a result of the weird dead return in this shader which the FE does eliminate.

PR on the way.
