### ISSUE TITLE
HLSL: Please add support for TextureBuffer<T>

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1140]
```TextureBuffer<T>``` is a somewhat obscure feature, it doesn't seem to be well documented. It's just the newer syntax for for ```tbuffer``` in the same way that ```ConstantBuffer<T>``` is the newer syntax for ```cbuffer```. 

Sample shader:
````C

struct Data {
  float4  f;
  int4    i;
};

TextureBuffer<Data> TextureBuffer_var : register(t0);

float4 main(float4 pos : SV_POSITION) : SV_TARGET
{
  return TextureBuffer_var.f;
}
````

DXC test here:
https://github.com/Microsoft/DirectXShaderCompiler/blob/master/tools/clang/test/CodeGenHLSL/bindings1.hlsl#L191

**Comment by LoopDawg** [comment]
Thanks for the example code - I don't seem to have access to a version of fxc which implements this syntax, so I can't experiment locally.  I noted in existing tbuffer implementation, and the above code, that tbuffer members appear at global scope, while members for TextureBuffer appear under the named variable.  I implemented the above syntax under #1143, if you want to have a look @chaoticbob .  I adopted your code above as a test case, and augmented it a little with a tbuffer for scope contrast purposes.

(Oddly, one of the build bot's detail pages claims it passed, yet the master status for that bot still shows it as pending, and has for some time now.  Unclear what's up with that.  Hopefully it'll sort itself out eventually).
