### ISSUE TITLE
HLSL: `unorm float4` is not supported

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1141]
In HLSL, using typed loads/stores on UNORM textures requires using `unorm` qualifier in the shader when declaring the resources:

https://msdn.microsoft.com/en-us/library/windows/desktop/dn903947(v=vs.85).aspx#using_unorm_and_snorm_typed_uav_loads_from_hlsl

This requires a shader like this:

```
Texture3D<unorm float4> ResultIn: register(t0);
RWTexture3D<unorm float4> ResultOut: register(u0);

[numthreads(16, 16, 1)]
void main(uint3 tid: SV_DispatchThreadID)
{
	ResultOut[tid] = ResultIn[tid];
}
```

The shader above currently compiles in fxc but fails to compile in glslang with the following error:

```
test.hlsl:1: error: 'scalar or vector type' : Expected
```

**Comment by johnkslang** [comment]
Do you know what `unorm float4` should translate to?  SPIR-V for shaders has the following choices, some of which include `snorm` in their name,  but not `unorm`:

```
    ImageFormatRgba32f = 1,
    ImageFormatRgba16f = 2,
    ImageFormatR32f = 3,
    ImageFormatRgba8 = 4,
    ImageFormatRgba8Snorm = 5,
    ImageFormatRg32f = 6,
    ImageFormatRg16f = 7,
    ImageFormatR11fG11fB10f = 8,
    ImageFormatR16f = 9,
    ImageFormatRgba16 = 10,
    ImageFormatRgb10A2 = 11,
    ImageFormatRg16 = 12,
    ImageFormatRg8 = 13,
    ImageFormatR16 = 14,
    ImageFormatR8 = 15,
    ImageFormatRgba16Snorm = 16,
    ImageFormatRg16Snorm = 17,
    ImageFormatRg8Snorm = 18,
    ImageFormatR16Snorm = 19,
    ImageFormatR8Snorm = 20,
    ImageFormatRgba32i = 21,
    ImageFormatRgba16i = 22,
    ImageFormatRgba8i = 23,
    ImageFormatR32i = 24,
    ImageFormatRg32i = 25,
    ImageFormatRg16i = 26,
    ImageFormatRg8i = 27,
    ImageFormatR16i = 28,
    ImageFormatR8i = 29,
    ImageFormatRgba32ui = 30,
    ImageFormatRgba16ui = 31,
    ImageFormatRgba8ui = 32,
    ImageFormatR32ui = 33,
    ImageFormatRgb10a2ui = 34,
    ImageFormatRg32ui = 35,
    ImageFormatRg16ui = 36,
    ImageFormatRg8ui = 37,
    ImageFormatR16ui = 38,
    ImageFormatR8ui = 39,
```

Maybe we need to extend SPIR-V?

**Comment by zeux** [comment]
@johnkslang I'm not really sure how this matches SPIRV semantics. From where I stand a good first step would be to just parse & ignore unorm/snorm qualifiers.

FWIW, in D3D11 you're supposed to specify them if the backing format is UNORM; however, this validation is very very new and, from what I've been told, somewhat too excessive in that most hardware doesn't actually need to know this information when compiling the shader.

I don't know how SPIRV read/write textures work - are you supposed to specify a precise format? Some of the formats on your list *are* actually unorm formats, they just use an old (and awkward) GL convention that doesn't indicate that explicitly - for example, ImageFormatR8 is R8_UNORM in D3D and would need `unorm float` in UAV declaration, whereas ImageFormatR8ui is R8_UINT and would need to use `uint` instead.

**Comment by antiagainst** [comment]
According to [HLSL doc](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509646(v=vs.85).aspx),

> In Direct3D 10, the following types are modifiers to the float type.
>    snorm float - IEEE 32-bit signed-normalized float in range -1 to 1 inclusive.
>    unorm float - IEEE 32-bit unsigned-normalized float in range 0 to 1 inclusive.

It seems we can just translate snorm/unorm floats as normal floats?

**Comment by LoopDawg** [comment]
> however, this validation is very very new and, from what I've been told, somewhat too excessive

> It seems we can just translate snorm/unorm floats as normal floats?

Under those theories: #1156 parses and ignores them.  The grammar accepts them as part of the type, *not* part of the UAV template parameter, because it seems that's how it works in HLSL.  For example, this is a valid construct to have hanging around somewhere all by itself:

    unorm float4 uf4;

That will be accepted by #1156.  There is some minimal rejection of things like "unorm int4 ...".
