### ISSUE TITLE
Generate AST nodes and SPIR-V for function declarations

### ISSUE THREAD

**Issue by thatname** [KhronosGroup/glslang#1146]
I want to try the new SPIR-V linker,
but, I found compiling a shader with an external function declaration like this
`#version 450`
`vec4 getColor();`
`out vec4 fragColor;`
`void main()`
`{`	
`	fragColor = getColor();`
`}`
will get this AST 
`0:? Sequence`
`0:4  Function Definition: main( ( global void)`
`0:4    Function Parameters: `
`0:6    Sequence`
`0:6      move second child to first child ( temp highp 4-component vector of float)`
`0:6        'fragColor' ( out highp 4-component vector of float)`
`0:6        Function Call: getColor( ( global highp 4-component vector of float)`
`0:?   Linker Objects`
`0:?     'fragColor' ( out highp 4-component vector of float)`
It seems the glslang does not generate AST for function declarations.
I also tried HLSL, It does not generate neither.

**Comment by johnkslang** [comment]
Graphical shaders are made as a fully linked stage by front ends, per the SPIR-V specification. A partially linked graphical shader is out of spec.  So, glslang takes a set of compilation units needed to make a full stage and makes a single module that is a full stage.

**Comment by thatname** [comment]
@johnkslang OK.
But I still feel graphical shader linking is a very useful feature, since graphical shaders in real applications typically share many long common functions. Huge disk space can be saved if we ship SPIR-V for each module and link them together at run time, instead of shipping fully linked shaders.

**Comment by johnkslang** [comment]
@thatname Agreed. The intent of SPIR-V is to have a single module have one copy of shared functions. The space savings are set up to be just as you say.

A SPIR-V module can have multiple entry points sharing the same functions. This is a different subject than a single entry point for a single stage being linked from multiple incomplete compilation units.

We need SPIR-V tools that can take two SPIR-V modules and merge them together into a single SPIR-V module, to get these savings.

**Comment by antiagainst** [comment]
FYI: SPIRV-Tools right now has a linker or module combiner: 86627f7b3f725d390b6e09078db0f41f10c9d165
