### ISSUE TITLE
HLSL register binding overwrites Vulkan's descriptor binding.

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/glslang#1148]
For this HLSL
```
layout(set=4, binding=1)
RWStructuredBuffer<uint> TestBuffer : register(u23);
```
after compilation I have the following output:
```
OpDecorate %TestBuffer_0 DescriptorSet 4
OpDecorate %TestBuffer_0 Binding 23
```
The expectation is if we provide Vulkan's binding information (set, binding) it should have higher priority than HLSL register binding (that's the reason why we provide Vulkan's layout information - to overwrite default behavior with necessary layout).

**Comment by johnkslang** [comment]
Let's have this discussion in #606.
