### ISSUE TITLE
[HLSL] Presence of GS causes HS failure to compile

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#1153]
The presence of a Geometry Shader seems to confuse the compile for a Hull Shader:
````
$ glslangValidator -V -D -S tesc -e HSMain tesc_fails.hlsl -H
tesc_fails.hlsl

ERROR: tesc_fails.hlsl:82: 'line_strip' : output primitive geometry redefinition
ERROR: tesc_fails.hlsl:82: ')' : Expected
ERROR: tesc_fails.hlsl:82: 'function parameter list' : Expected
tesc_fails.hlsl(82): error at column 43, HLSL parsing failed.
ERROR: 4 compilation errors.  No code generated.
````

Commenting out the Geometry Shader, the Hull Shader compiles without a problem.

Attached as a TXT since GIthub doesn't like HLSL file attachments:
[tesc_fails.hlsl.txt](https://github.com/KhronosGroup/glslang/files/1469177/tesc_fails.hlsl.txt)

**Comment by LoopDawg** [comment]
#1157 has a fix.  I used your attached shader verbatim as a test; if there's something in there you'd rather not have appear in the set of checked in tests, let me know and I'll write a from-scratch test instead.  This was just easier, if you don't mind the inclusion.
