### ISSUE TITLE
HLSL: No PSIZE support

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1154]
PSIZE output of the vertex shader was used in DX9 to indicate the size of rendered points.

In DX11, it was removed and all points have a size of 1, *however*...

In Vulkan (and also Metal which you can translate SPIRV to via SPIRV-Cross) you need to output point size from the vertex shader (gl_PointSize / [[point_size]]) for your points to render correctly. Some desktop Vulkan drivers in absence of gl_PointSize render points with size of 1, but it's undefined behavior - the spec says you *must* specify gl_PointSize for point rendering. As such, as it stands you can not render points in Vulkan using HLSL shaders.

It looks like HLSL backend already has a commented out section that introduces PSIZE support (https://github.com/KhronosGroup/glslang/blob/a9c8cce8e769aac95cd11c13bdf76d407069c347/hlsl/hlslScanContext.cpp#L418) - would it be possible to restore that?

**Comment by antiagainst** [comment]
Maybe another way of conveying this Vulkan-specific information is using attributes like `[[vk::builtin("PointSize")]]`. It is more explicit and consistent since we can also use it to support other Vulkan-specific builtins like `HelperInovcation` instead of relying on specific non-SV semantic strings. (AFAICT, there is no HLSL equivalent of `gl_HelperInvocation`?)

**Comment by zeux** [comment]
We can adapt our shaders to any convention, we've just been using PSIZE since it's what DX9 has (and other shader translation pipelines generally support that since they are assuming DX9 source).

It would be nice to pick something that's compatible with what DXC supports so that HLSL shaders are portable across DXC & glslang - is the `vk::builtin` convention already supported by DXC?

**Comment by johnkslang** [comment]
@antiagainst what connection are you making between PointSize and helperInvocation?

I don't mind something like `[[vk::builtin("PointSize")]]` but is there no standard portable point size? Or, we can't add SV_PointSize for uniformity?

**Comment by antiagainst** [comment]
> What connection are you making between PointSize and helperInvocation?

AFAICT, both `PointSize` and `HelperInvocation` builtins have no corresponding SV semantics. Somebody please definitely correct me if I'm wrong. So to generate SPIR-V for them, we need ways to represent both of them in the source code, preferably a consistent way.

> We can't add SV_PointSize for uniformity?

We can but I think that will make the shader unacceptable by `fxc` or `dxc` anymore. `fxc` will error out on seeing `SV_PointSize`, which is unknown to DirectX. That will forbid the devs from sharing the same shader for both DirectX and Vulkan. Yes, `#ifdef` can somewhat help here, but it's still kinda cumbersome and it is not future proof (more on this later).

We can also use certain non-SV semantics, say `PSIZE` for `PointSize` and `HelperInvocation` for `HelperInvocation`. But it seems quite random and blurs the boundary that only SV semantics can possibly be mapped to BuiltIns. Now devs need to choose non-SV semantic names carefully. The other thing is that we are still mandating certain semantic strings to be used for Vulkan specific stuff. Let's say in the future, DirectX introduces `SV_PointSize` or `SV_HelperInovcation` (I am not aware of DirectX enough to say how likely this is, maybe pure hypothetical, would love to hear feedback on this point) into DirectX, the devs need to use `SV_PointSize` but we are requring `PSIZE` here. Yes, we can update our side to support both `PSIZE` and `SV_PointSize`, but what if both are used in the same shader? Right, we can kinda check the shader profile... But IMHO, that will make the rules non-trivial and it comes as a mental burden for devs.

Based on the above thoughts, my preference is to use `[[vk::builtin("...")]]`. It is explicit, consistent, and future proof. Unfortunately, C++11 attribute syntax is also not recognized by `fxc`, which may require `#ifdef` to share the same shader for both DirectX (using `fxc` as compiler) and Vulkan, but that will be remedied by `dxc`, which will just ignore all unknown C++11 attributes, if targeting DXIL.

Happy to hear your opinions. :)

**Comment by antiagainst** [comment]
cc @dneto0 @ehsannas

**Comment by dneto0** [comment]
I don't have strong opinions on the solution.  My thought are:

- #ifdef ugliness can be hidden behind macros
- I believe Microsoft intends to evolve HLSL to be more like C++.  The C++ attribute syntax can be used for ignorable things.  The namespacing helps.
- Would it be ok to allow the DX9 PSIZE syntax?    That's an incompatibility between targeting DX* and Vulkan, but is that ok because I assume you're accessing a feature no longer in DX*?   Even this could be hidden by #ifdef and macros.

So my weak preferences are:  Permit the old PSIZE syntax. Otherwise the C++ attribute syntax. ???

**Comment by zeux** [comment]
I was somewhat reluctant to suggest SV_PointSize, but after thinking about it a bit this:

> We can but I think that will make the shader unacceptable by fxc or dxc anymore. fxc will error out on seeing SV_PointSize, which is unknown to DirectX. That will forbid the devs from sharing the same shader for both DirectX and Vulkan.

Is actually probably a good thing? :)

It's unfortunate that Vulkan/Metal end up requiring point size output from the shader but since they do, it seems reasonable that you wouldn't want this code to compile on fxc/dxc targeting DXIL because:

- If you want to output point size = 1, you're just wasting a VS output
- If you want to output point size >1, it will not work so it makes sense to fail early

I feel like C++ attribute may be harder to support in glslang unless there's already a precedent for this; in addition, you will need to ifdef it out for fxc anyway.

**Comment by johnkslang** [comment]
Just a side point: 

> I feel like C++ attribute may be harder to support in glslang unless there's already a precedent for this;

glslang has full support now for C++11 style attributes.

I can do any/all of the above, if those who feel strongly agree on some point.

**Comment by johnkslang** [comment]
Any votes for or against about adding one or both these?

- `SV_PointSize`
- `[[vk::builtin("PointSize")]]`

**Comment by antiagainst** [comment]
@johnkslang: Ah, sorry. Was occupied by some bugs yesterday. :)

I think we'll add `[[vk::builtin("PointSize")]]` into DXC at first.

I've no strong opinions towards `PSIZE` support. Slightly feeling that what's deprecated should just RIP maybe. ;-P But would happy to add it to please the devs if that's what they still use a lot.

For `SV_PointSize`, it is a little bit difficult for DXC specifically since that involves plumbing through a new SV semantics. We don't control the frontend parsing, and MS will likely question that. It involves more discussion and work.

**Comment by antiagainst** [comment]
@zeux: Ah, that is reasonable! Hmm, but based on my understanding, I assume it's legal in DirectX PS to ignore some semantics appearing in vertex processing stages? So actually it's OK to declare a stage variable for point size in HLSL VS/HS/DS/GS, share the same HLSL for both DX and VK, and just avoid using that variable in the DX PS case? If that's possible, we can share the same set of shaders at lest for VS/HS/DS/GS then? (Some `#ifdef` needed for sharing PS though.)

**Comment by zeux** [comment]
@antiagainst It's legal to ignore semantics as long as the struct members match by index - that is, you could output `struct { float4 p: SV_Position; float psize: PSIZE; }` from VS and just not access psize in PS. You do need to specify valid semantics - SV_PointSize will fail to compile - and you also do need to match inputs & outputs in terms of index in the struct, so having an output from VS `{ SV_Position, PSIZE, TEXCOORD }` and having an input in PS `{ SV_Position, TEXCOORD }` won't work because stage inputs/outputs aren't matched by name (except for IA -> VS...).

**Comment by antiagainst** [comment]
FYI: https://github.com/Microsoft/DirectXShaderCompiler/pull/805 added support for `[[vk::builtin("PointSize")]]` in DXC.

**Comment by zeux** [comment]
Ok, with this in mind it would probably make sense to implement vk::builtin("PointSize") in glslang as well.

**Comment by johnkslang** [comment]
You can now use `[[vk::builtin("PointSize")]]` in front of 

- the return type from a function
- a parameter
- a struct member
