### ISSUE TITLE
[HLSL] Invalid SPIRV generated when passing a ByteAddressBuffer to a function

### ISSUE THREAD

**Issue by williamallas** [KhronosGroup/glslang#1163]
If you compile the following very simple HLSL shader :
```hlsl
ByteAddressBuffer inBuffer : register(t42);

uint readBuffer(ByteAddressBuffer _buf)
{
	return _buf.Load(0);
}

uint main() : OUTV
{
	return readBuffer(inBuffer);
}
```
with **glslangValidator.exe -D -H test.vert -e main**
I am using the glslangValidator.exe provided by the Vulkan SDK 1.0.65.0.

You get the folowing spirv bytecode :
```spirv
test.vert
// Module Version 10000
// Generated by (magic number): 80002
// Id's are bound by 42

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 33
                              Source HLSL 500
                              Name 4  "main"
                              Name 8  ""
                              MemberName 8 0  "@data"
                              Name 33  "@entryPointOutput"
                              Decorate 7 ArrayStride 4
                              MemberDecorate 8 0 NonWritable
                              MemberDecorate 8 0 Offset 0
                              Decorate 8 BufferBlock
                              Decorate 33(@entryPointOutput) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 0
               7:             TypeRuntimeArray 6(int)
               8:             TypeStruct 7
               9:             TypePointer Function 8(struct)
              17:             TypeInt 32 1
              18:     17(int) Constant 0
              19:     17(int) Constant 2
              21:             TypePointer Function 6(int)
              32:             TypePointer Output 6(int)
33(@entryPointOutput):     32(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
              35:      9(ptr) Variable Function
              39:     17(int) ShiftRightArithmetic 18 19
              40:     21(ptr) AccessChain 35 18 39
              41:      6(int) Load 40
                              Store 33(@entryPointOutput) 41
                              Return
                              FunctionEnd
```

As you see the ByteAddressBuffer "inBuffer" does not appear in the spirv (we should see a DescriptorSet at binding 42). Instead it performs a load on an uninitialized "Variable Function" which leads to nothing good...
Are you aware of this issue ?
If you reference directly the buffer when performing the load, the generated spirv is correct.

**Comment by LoopDawg** [comment]
Not only is the buffer gone, but the whole readBuffer() function is too, as well as the invocation thereof.  That can't be good :).

It appears that if the optimizer is disabled (-Od) then the resulting SPIR-V does contain the expected decorations:

                              Name 27  "inBuffer"
     ...
                              Decorate 27(inBuffer) DescriptorSet 0
                              Decorate 27(inBuffer) Binding 42

I think the optimizer is not at fault though, and disabling it is not likely to produce working code.  I more suspect a missing reference to the globally scoped buffer object causing some things to be DCE'd.

SWAG: something is wrong in SPIR-V generation.  It looks like the AST does reference the object as expected during the function call.

**Comment by johnkslang** [comment]
The AST passes `inBuffer` as the argument to the function call, but the SPIR-V passes a local variable. I'll look into this some more.

**Comment by williamallas** [comment]
Thank you for looking at this ! I will temporarely disable the optimizer.

**Comment by LoopDawg** [comment]
> Thank you for looking at this ! I will temporarely disable the optimizer.

I doubt disabling the optimizer will be sufficient to get proper behavior.  It's a data point about the problem, but by itself (probably) won't be a workaround.

**Comment by johnkslang** [comment]
Right, the original generated code uses a local instead of the global.

**Comment by williamallas** [comment]
Yes, I will continue to load my buffers in-place for the moment until you fix it, thank you !

**Comment by johnkslang** [comment]
This is pretty subtle, but we pass blocks with their buffer qualifier, which is mutually exclusive with in/out qualifiers.  So, currently, independent of this issue, we cannot independently represent buffer-ness and in/out-ness, which means we can't support a function that sets an entire buffer, returning it as an output parameter. (This however work with opaques like textures.)

For this issue, we were partly treating the buffer as something to pass by reference, and something that could be set so had to be copied in/out, except were not doing the copies, because `out` was not part of the qualifier. I'm fixing in the direction of pass-by-reference, hence no copy in/out needed, but that will continue to keep the limitation of not having `out` parameters that are buffers (can't use a function to set a buffer).

**Comment by LoopDawg** [comment]
Cool.  Your change, or possibly something already in place, nicely warns upon "out ByteAddressBuffer buf" assignments to the out parameter ("could not create assignment"), so nobody should get silent misbehavior there.
