### ISSUE TITLE
TSampler: isTexture() function

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#1164]
Is this correct in Types.h ?
bool isTexture()     const { return !sampler && !image; }
Seems a bit weird that a cleared TSampler, having all its variables set to false, would return true to isTexture()

**Comment by johnkslang** [comment]
Seems this is only valid if known to be a texture/image.  That is, there should be some check that a type has basic type EbtSampler before starting to query the details of the TSampler, otherwise it seems ill-defined.

**Comment by johnkslang** [comment]
To be more clear, don't look at this data unless the basic type is EbtSampler.
