### ISSUE TITLE
ES3.1 varying linkage

### ISSUE THREAD

**Issue by absinthe99** [KhronosGroup/glslang#1172]
Does match a variable on the vertex side with layout qualifier and variable with same name on the fragment side without layout.

ES3.2 definition clearly explain doesn't match.
defeinition ES3.1 is same definition or not?

It seems ES3.1 and ES3.2 are different definition of varying matching.

ES3.2 explanation
--------------------
An output variable is considered to match an input variable in the subsequent
shader if:
– the two variables match in name, type, and qualification, and neither has a location qualifier; or
– the two variables are declared with the same location qualifier and match in type and qualification.
---------------------

ES3.1 explanation
--------------------
An output variable is considered to match an input variable in the subsequent
shader if:
- the two variables match in name, type, and qualification; or
– the two variables are declared with the same location qualifier and match in type and qualification
---------------------

**Comment by johnkslang** [comment]
This is apparently a specification question, not a glslang question. I'm transferring to the KhronosGroup/OpenGL-GLSL repository.
