### ISSUE TITLE
HLSL: bool & bool generates BitwiseAnd with integer result type

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1192]
We have an HLSL shader that has the following lines of code:

    bool test0 = ...;
    bool test1 = ...;

    count += (test0 & test1);

count is integer; test0 & test1 are computed via some bool-returning function. It looks like in this case glslang generates a BitwiseAnd op that returns a bool. The validation layers then reject the resulting SPIRV:

    [SC] SPIR-V module not valid: Expected int scalar or vector type as Result Type: BitwiseAnd

From the spec, it seems like BitwiseAnd requires two integer inputs & integer output:

> Result Type must be a scalar or vector of integer type. The type of Operand 1 and Operand 2 must be a scalar or vector of integer type. They must have the same number of components as Result Type. They must have the same component width as Result Type.

So this seems like a code generation bug? (if it's actually a validator bug I'm happy to file a validation issue)

Repro case:

    float4 main(): SV_Position
    {
        bool test0 = 1.f < 2.f;
        bool test1 = 2.f < 1.f;

        int count = 0;
        count += (test0 & test1);

        return float4(count, 0, 0, 0);
    }

Generated SPIRV fragment:

              45:     17(int) Select 14 22 20
              47:     17(int) Select 16 22 20
              48:    11(bool) BitwiseAnd 45 47
              49:     17(int) Select 48 22 20
              51:     17(int) IAdd 20 49

Running this:

    glslangValidator.exe -D test.vert --target-env vulkan1.0 -e main
    spirv-val vert.spv

Produces the aforementioned error.

**Comment by johnkslang** [comment]
Makes sense. A previous fix converted bool operands to ints, but was leaving the original operator result type as bool, instead of the new type.
