### ISSUE TITLE
HLSL: Invalid OpConvertFToU generated for RWByteAddressBuffer.Store4 of uint4

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#1194]
Given the following HLSL fragment shader:

RWByteAddressBuffer sbuf;

float4 main(uint pos : FOO, uint4 input : FOO2, float4 output : FOO3) : SV_Target0
{
    sbuf.Store4(pos, input);

    return output;
}

spirv-val complains about the OpConvertFToU in the resultant SPIR-V. Here is the (unlegalized) SPIR-V for main:

%_main_u1_vu4_vf4_ = OpFunction %v4float None %13
        %pos = OpFunctionParameter %_ptr_Function_uint
      %input = OpFunctionParameter %_ptr_Function_v4uint
     %output = OpFunctionParameter %_ptr_Function_v4float
         %18 = OpLabel
%byteAddrTemp = OpVariable %_ptr_Function_int Function
         %22 = OpLoad %uint %pos
         %24 = OpShiftRightLogical %int %22 %int_2
               OpStore %byteAddrTemp %24
         %30 = OpLoad %int %byteAddrTemp
         %32 = OpAccessChain %_ptr_Function_uint %input %uint_0
         %33 = OpLoad %uint %32
         %34 = OpConvertFToU %uint %33
         %36 = OpAccessChain %_ptr_Uniform_uint %sbuf_0 %int_0 %30
               OpStore %36 %34
         %37 = OpLoad %int %byteAddrTemp
         %39 = OpIAdd %int %37 %int_1
         %41 = OpAccessChain %_ptr_Function_uint %input %uint_1
         %42 = OpLoad %uint %41
         %43 = OpConvertFToU %uint %42
         %44 = OpAccessChain %_ptr_Uniform_uint %sbuf_0 %int_0 %39
               OpStore %44 %43
         %45 = OpLoad %int %byteAddrTemp
         %46 = OpIAdd %int %45 %int_2
         %48 = OpAccessChain %_ptr_Function_uint %input %uint_2
         %49 = OpLoad %uint %48
         %50 = OpConvertFToU %uint %49
         %51 = OpAccessChain %_ptr_Uniform_uint %sbuf_0 %int_0 %46
               OpStore %51 %50
         %52 = OpLoad %int %byteAddrTemp
         %54 = OpIAdd %int %52 %int_3
         %56 = OpAccessChain %_ptr_Function_uint %input %uint_3
         %57 = OpLoad %uint %56
         %58 = OpConvertFToU %uint %57
         %59 = OpAccessChain %_ptr_Uniform_uint %sbuf_0 %int_0 %54
               OpStore %59 %58
         %60 = OpLoad %v4float %output
               OpReturnValue %60
               OpFunctionEnd

Submitted on behalf of @dustin-lunarg

**Comment by jfmarquis** [comment]
#1190 should fix that.

**Comment by johnkslang** [comment]
Indeed, the OpConvertFToU are no longer present.
