### ISSUE TITLE
Variable with 'layout' name causes compilation error in HLSL

### ISSUE THREAD

**Issue by kennyalive** [KhronosGroup/glslang#1201]
Using 'layout' as variable name causes compilation error when trying to compile the following HLSL code. Probably compiler handles it as a qualifier that specifies vulkan resource binding. It would be nice to analyse the context and allow to use 'layout' as variable name if it does not creates ambiguity.

```
float4 test(float f, uint layout)
{
    return float4(f, f, f, f);
}

float test2()
{
    float layout = 2.0;
    return layout;
}

void main()
{
}
```

**Comment by johnkslang** [comment]
Fixed by fd1e8a78a88b4865ad6f9d87db7f68c4a2de827b.
