### ISSUE TITLE
HLSL: ImageFetch is generated with the incorrect result type

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1206]
SPIR-V specification mandates that ImageFetch result type is a 4-component vector of floating-point or integer type. While it appears that the validator binary from 1.0.65 SDK doesn't test for this, SPIRV-Tools latest does.

glslang doesn't generate correct SPIRV in case the source HLSL uses a scalar or a narrow vector type, for example:

```
Texture3D<int> IN: register(t0);
RWTexture3D<int> OUT: register(u1);

[numthreads(8,8,8)]
void main(uint3 tid: SV_DispatchThreadID)
{
	OUT[tid] = IN[tid];
}
```

Note that the type of the texture objects here is `int` - so the assignment is that of a scalar. glslang generates this SPIRV:

             39:     13(int) ImageFetch 37 32 Lod 21
             40:          23 Load 25(OUT)
                             ImageWrite 40 32 39

Which fails to validate with latest SPIRV-Tools with this error message:

    Expected Result Type to be int or float vector type: ImageFetch

Similarly, changing `<int>` to `<int2>` produces a vector result that is too narrow:

             40:   14(ivec2) ImageFetch 38 33 Lod 22
             41:          24 Load 26(OUT)
                             ImageWrite 41 33 40

**Comment by johnkslang** [comment]
You are correct the ImageFetch must return a vec4, so glslang must do conversions between that and the templatized type. @LoopDawg expressed interest in fixing this, but in full generality, it gets pretty complicated, so will likely start with some incremental improvements.

**Comment by LoopDawg** [comment]
>  @LoopDawg expressed interest in fixing this,

Or at least "willingness" :P.   #1250 has a fix.

Per what @johnkslang said about "not fully general", this will not handle cases templatized on structs.  It will work for cases such as the posted example where a simple conversion opcode suffices.  (Structs can still be returned from normal texture intrinsics - this limitation exists only around operator[]).  The sequence above now will produce a vec4 from the ImageFetch, plus a conversion to the template type:

              23:   22(ivec4) ImageFetch 19 20 Lod 21
              24:     15(int) CompositeExtract 23 0
