### ISSUE TITLE
HLSL: Forwarding buffered structs as arguments generates invalid spir-v code

### ISSUE THREAD

**Issue by tafuri** [KhronosGroup/glslang#1210]
Compiling the following shader generates invalid spirv code. glsl-val prints out the following error:
`error: 325: OpStore Pointer <id> '82's type does not match Object <id> '55's type.`

```hlsl
struct Globals
{
    float4 test;
    uint idx;
};

cbuffer GobalConstants
{
    Globals global_constants;
}

float TestFunction2(float s, Globals globals)
{
    return s * globals.test2[globals.idx];
}

float TestFunction(float s, Globals globals)
{
    return TestFunction2(s, globals);
}

RWStructuredBuffer<float> Input;
RWStructuredBuffer<float> Output;

void main()
{
    // Calling TestFunction2 directly generates valid code
    Output[0] = TestFunction(Input[0], global_constants);
}
```

**Comment by greg-lunarg** [comment]
I will check if this is caused or fixed by enabling legalization.

**Comment by greg-lunarg** [comment]
Changed test2 to test. Otherwise:

glslangValidator -V -D -e main f.frag
f.frag
ERROR: f.frag:14: 'test2' : no such field in structure 
ERROR: f.frag:14: 'expression followed by ']'' : Expected 
ERROR: f.frag:14: 'expression' : Expected 
ERROR: f.frag:14: ';' : Expected 
f.frag(14): error at column 29, HLSL parsing failed.
ERROR: 5 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link

**Comment by greg-lunarg** [comment]
It appears that you are not building glslangValidator with spirv-tools. Please search README.md for "legal" and follow those directions. Doing so eliminates the spirv-val error you noted.

I will verify that the resultant SPIR-V is indeed correct before claiming this is fixed.

**Comment by greg-lunarg** [comment]
You should also pull the latest glslang to get the best known good spirv-tools.

**Comment by greg-lunarg** [comment]
Yes, with "legalization" enabled (glslang built with spirv-opt), the resulting code is valid and looks correct.

**Comment by tafuri** [comment]
Sorry for the mistake in the sample shader (globals.test2 should of course be globals.test).
Turned the problem I had was related to legalization. I was compiling the code through shaderc (with the latest glslang source), and aparently the legalization recipe there is not up-to-date. The generated code was valid when adding optimization though.
