### ISSUE TITLE
Implicit XfbStride is not being calculated correctly

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/glslang#1212]
This bug comes from a new OpenGL CTS test here:
https://gerrit.khronos.org/#/c/2008/

The test uses the following GLSL:
```
#version 450

layout (location = 0) in vec4 position;
layout (location = 20) uniform vec4 extPosition;
layout (binding = 5) uniform ComponentsBlock
{
    vec4 c1;
    vec2 c2;
} components;
layout (xfb_buffer = 0, xfb_offset = 16) out gl_PerVertex
{
    vec4 gl_Position;
};

void main()
{
    gl_Position = position + extPosition + components.c1 + vec4(components.c2, 0.0, 0.0);
}
```

Notice that this shader does not specify "xfb_stride", so the GLSL compiler should figure it out automatically based on variables being captured to the buffer. The problem is that the SPIR-V generated has an explicit XfbStride decoration of 0, which is not right.

Eyeballing the glslang code, I suspect the problem is that addXfbBufferOffset() is not called in the case above because there is no xfb_buffer/xfb_offset qualifier on the "gl_Position" variable. Instead addXfbBufferOffset() should have been called when doing redeclareBuiltinBlock() on the "gl_PerVertex" declaration when the XFB layout qualifiers are merged into all the members. So perhaps either during fixBlockXfbOffsets() or after something should go through the redeclared gl_PerVertex block members and call addXfbBufferOffset() on each one to ensure the implicitStride is getting calculated correctly.

**Comment by johnkslang** [comment]
Sounds like a credible analysis. I will have a look.

**Comment by johnkslang** [comment]
FYI, until these recent efforts, XFB was only at validation level of functionality, versus translation level. Typically, for a feature, these basically match, but XFB seems to have bigger gap.

I'll get this part done today.

**Comment by johnkslang** [comment]
Actually, correcting the last post, it's still in the gap of not having implemented XFB for redeclared built-in blocks.  The commit that fixes this adds 3-4 small pieces of missing functionality in this space.

**Comment by pdaniell-nv** [comment]
Thanks for the quick fix. It appears to work well.
