### ISSUE TITLE
HLSL: invalid break statement causes segfault

### ISSUE THREAD

**Issue by tafuri** [KhronosGroup/glslang#1214]
Compiling this invalid shader as HLSL causes a segfault in glslangcompiler instead of an error.

```hlsl
void main() {
    break;
}
```

**Comment by johnkslang** [comment]
Keep in mind that glslang is intended to support valid HLSL shadars, and is not written as as HLSL validator. Catching simple syntax errors, and helping when there is high value is fair game, but it is not a goal of glslang to fully handle incorrect HLSL.

**Comment by tafuri** [comment]
Yes, I am aware of that. So I don't expect the error messages to make any sense, but it should never segfault in my opinion.
