### ISSUE TITLE
Incorrect comment above setEnvInput()

### ISSUE THREAD

**Issue by snipstruis** [KhronosGroup/glslang#1223]
When parsing HLSL files (with the intention of generating SPIR-V) like so:
```
auto const src = 
  "float4 Main() {"   
  "    return float4(1.0, 0.0, 1.0, 1.0);"
  "};";
auto const resource = TBuiltInResource();
auto ast = std::make_unique<glslang::TShader>(stage);
ast->setStrings(&src, 1);
bool parseSuccess = ast->parse(&resource, 110, false, EShMsgDefault);
```
It unfortunately fails with these unhelpful messages:
```
ERROR: 0:1: '' : array size must be a positive integer 
ERROR: 0:1: '' : compilation terminated 
INTERNAL ERROR: Unable to parse built-ins
ERROR: 0:2: '' :  syntax error, unexpected IDENTIFIER
ERROR: 1 compilation errors.  No code generated.'
```
It only works when setting the environment manually like so:
```
auto const src = 
  "float4 Main() {"   
  "    return float4(1.0, 0.0, 1.0, 1.0);"
  "};";
auto const resource = TBuiltInResource();
auto ast = std::make_unique<glslang::TShader>(stage);
ast->setStrings(&src, 1);
ast->setEnvInput(glslang::EShSourceHlsl, stage, glslang::EShClientVulkan, 1);
ast->setEnvClient(glslang::EShClientVulkan, 1);
ast->setEnvTarget(glslang::EshTargetSpv, 1);
bool parseSuccess = ast->parse(&resource, 110, false, EShMsgDefault);
```
This is contrary to the comment above `setEnvInput()` in `glslang/Public/shaderlang.h`  saying:
`// For setting up the environment (initialized in the constructor):`
Which implies that the environment is automatically initialized in the constructor.

It is also not mentioned in the instructions above the `TShader` class:
```
// Make one TShader per shader that you will link into a program.  Then provide
// the shader through setStrings() or setStringsWithLengths(), then call parse(),
// then query the info logs.
// Optionally use setPreamble() to set a special shader string that will be
// processed before all others but won't affect the validity of #version.
//
// N.B.: Does not yet support having the same TShader instance being linked into
// multiple programs.
//
// N.B.: Destruct a linked program *before* destructing the shaders linked into it.
//
```
Which implies, you can call  `parse()` with only setting the strings.

Can the comment be updated?

**Comment by johnkslang** [comment]
`TranslateEnvironment()` should also be setting this up, based on the legacy settings selected in `messages`. For that, if you wanted HLSL for Vulkan, you'd need to set those bits (the type for `messages` includes `EShMsgVulkanRules`, `EShMsgReadHlsl`, etc.). It's not going to know you want that by default.

I'll update the comment a bit.
