### ISSUE TITLE
HLSL: Use of IncrementCounter() generates invalid spir-v instruction arguments

### ISSUE THREAD

**Issue by tafuri** [KhronosGroup/glslang#1225]
Compiling the following compute shader:

```hlsl
RWStructuredBuffer<uint> Out;

[numthreads(1, 1, 1)]
void main()
{
    uint outIndex = Out.IncrementCounter(0);
	Out[outIndex] = 0;
} 
```

Generates the following invalid spir-v instruction (which is detected by spirv-val):
```
%31 = OpAtomicIAdd %uint %30 %uint_1 %uint_0 %int_1
```

The spir-v spec states that 
> The type of _Value_ must be the same as _Result Type_

so the final %int_1 should really be %uint_1

**Comment by johnkslang** [comment]
This was fixed by 5cd155f075fcd3b31b12ad8e670a8c4d1d0c46c7.
