### ISSUE TITLE
Invalid SPIR-V for passing depth texture as function argument

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#1226]
Given the shader depth.frag:

Texture2D                 g_ShadowAtlas        : register( t1 );
SamplerState              g_LinearClampSampler : register( s1 );
SamplerComparisonState    g_ShadowCompSampler  : register( s2 );

//--------------------------------------------------------------------------------------------------
float SampleWithComp( in float2 uv )
{
  return g_ShadowAtlas.SampleCmpLevelZero( g_ShadowCompSampler, uv, 0 ).r;
}

//--------------------------------------------------------------------------------------------------
float SampleLinear( in float2 uv )
{
  return g_ShadowAtlas.SampleLevel( g_LinearClampSampler, uv, 0 ).r;
}

//--------------------------------------------------------------------------------------------------
float Gather( in Texture2D shadow_atlas, in SamplerComparisonState shadow_samp, in float2 uv )
{
  return shadow_atlas.SampleCmpLevelZero( shadow_samp, uv, 0 );
}

//--------------------------------------------------------------------------------------------------
float SomeFunc( in float2 uv )
{
  return Gather( g_ShadowAtlas, g_ShadowCompSampler, uv );
}

//--------------------------------------------------------------------------------------------------
float EntryFunc( in float2 uv : TEXCOORD0 )
{
#if(0)
  // Works
  float result = SomeFunc( uv );
#elif(0)
  // Works
  float result = SampleLinear( uv );
  result += SomeFunc( uv );
#else
  // Fails
  float result = SampleWithComp( uv );
  result += SomeFunc( uv );
#endif

  return result;
}

Compiling with the following command (optimizer disabled):

glslangValidator -V -D -e EntryFunc -Od depth.frag
mv frag.spv depth.frag.spv

Validating with command:

spirv-val depth.frag.spv

Gives the error:

error: 495: OpStore Pointer <id> '59's type does not match Object <id> '60's type.

I believe this is a continuation of issue #1073

**Comment by greg-lunarg** [comment]
FWIW, compiling with the optimizer on:

glslangValidator -V -D -e EntryFunc depth.frag

does *not* generate a validation error. This is because the optimizer does not run validation when called directly from glslang.

Even more interesting, the resulting SPIR-V is valid and correct. This is because the invalidity does not cause the optimizer to generate incorrect/invalid code. Rather, inlining ignores the invalidity issue and eliminates the problem (type mismatch between formal and actual arguments).

So as there is a workaround, this problem is not urgent. But it does highlight the issue that HLSL tolerates an agnostic view toward depth for images, a view which SPIR-V and subsequently IHVs will need to support. In HLSL, the depth of an image is not resolved until execution time when the sampler operation is finally executed. A shader can contain both depth and non-depth samples of the same image, but only one kind (depth or non-depth) can ultimately be executed during a single execution of a shader.

**Comment by johnkslang** [comment]
We are relying on legalization to get this correct.
