### ISSUE TITLE
Array of array of matrix in function argument not parsed correctly

### ISSUE THREAD

**Issue by raunSSNLF** [KhronosGroup/glslang#1229]
glslang is parsing the following incorrectly.

```
vec3 func(in mat3[2] x[3]) {
	mat3 a0 = x[0][0];
        ...
}
```

...where x[0][0] according to the TParseContext::declareVariable is treated as vec3, not a mat3. It looks like YACC incorrectly handles the declaration of x in for arguments of functions.  'x' should be array of arrays of mat3 elements according to 4.1.9 of OpenGL ES v.3.20rev3, while it is parsed as an array of arrays of vec3.

**Comment by johnkslang** [comment]
I see the inner size (on the type) is replaced instead of merged, for parameter declarations.  Will fix now.
