### ISSUE TITLE
Support ARB_shader_clock

### ISSUE THREAD

**Issue by LDeakin** [KhronosGroup/glslang#1230]
The ARB_shader_clock extension does not yet seem to supported.
It would be useful to have this in order to fine-tune the performance of shaders.

**Comment by LDeakin** [comment]
Looks like this was added in the [Vulkan 1.1.124 spec update](https://github.com/KhronosGroup/Vulkan-Docs/commit/22a5a1459fbe8be546079525c4c9d50bfc20b30b)

**Comment by pdaniell-nv** [comment]
VK_KHR_shader_clock is supported in the 436.52/435.27.00 drivers you can find here: https://developer.nvidia.com/vulkan-driver
