### ISSUE TITLE
Swizzle with dynamic produces incorrect SPIR-V output

### ISSUE THREAD

**Issue by raunSSNLF** [KhronosGroup/glslang#1233]
This sequence produces in correct SPIR-V.

```
#version 440

layout (location = 3) in int userVertexID;

vec4 pos = vec4(0.6, 0.6, 0.3, 1.1);

void main () {
    pos.yxwz[userVertexID % 2] = 2.0;
    gl_Position = pos;
}

```

The swizzle with dynamic indexing is producing side-effects instead of just selecting a channel to update.

```
17:     14(int) Load 16(userVertexID)         // load userVertexID
19:     14(int) SMod 17 18                    // userVertexID % 2
21:    7(fvec4) Load 9(pos)                   // Load pos
22:    7(fvec4) VectorShuffle 21 21 1 0 3 2   // pos.yxwz
23:    7(fvec4) VectorInsertDynamic 22 20 19  // pos.yxwz[userVertexID % 2] = 2.0
                Store 9(pos) 23

```

**Comment by johnkslang** [comment]
This is pretty interesting; a bit of a puzzle buried here:

- an l-value swizzle: do the shuffle and store
- an l-value swizzle with a compile-time constant index: reduce to static component store
- an l-value swizzle with a dynamic index: dynamically remap the index to a different index, then a dynamic component store

That very last part does not exist (it currently inappropriately keeps the whole swizzle).

So, need code to do the dynamic remap of the dynamic index.

**Comment by johnkslang** [comment]
I have this fixed locally, mostly using longer access chains. It expands to a few other cases of using longer access chains, instead of intermediate swizzling. So, will finish those off, and also bump up the generator number, because some code patterns will change.
