### ISSUE TITLE
ShaderLang.h:  EShTargetSpv is mis-spelled with a small 's'

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1235]
See https://github.com/KhronosGroup/glslang/blob/master/glslang/Public/ShaderLang.h#L122 

It's spelled as EshTargetSpv which is inconsistent with all other ESh* enum names.

**Comment by dneto0** [comment]
I filed this as an issue because I don't know how you want to handle this.  If use of this API is widespread then changing the name should be done carefully to avoid backward compatibility breaks.  If it's not widespread then I recommend a pure rename (without deprecation period for the old name).

For my part, Shaderc would like to use this API.  But it's ok to break because currently Shaderc's official builds are broken until #1234 is merged. (Shaderc uses top-of-tree SPIRV-Tools which has more aggressive block merging.)

**Comment by johnkslang** [comment]
I handled it by aliasing the enums, so both names work.
