### ISSUE TITLE
Compilation for Vulkan is getting SPIR-V 1.2 binaries, and can't be overridden

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1236]
The update to unified1 SPIR-V headers caused spv::Version from spirv.hpp to be updated to 0x10200, and that's written as the SPIR-V version number in the module header.
That's not valid for any consuming client API (Vulkan 1.0 or OpenGL 4.6).

That would be ok if glslang::TShader::setEnvTarget could override it with something like:
   setEnvTarget(EshTargetSpv, 100)
But that setting does not get passed down into SPIR-V code generation.

This is blocking me from updating Glslang in Shaderc.

**Comment by johnkslang** [comment]
The override/version-setting are now passed all the way through to code generation.

I.e., still keeping the change to use unified1 headers.
