### ISSUE TITLE
HLSL: InterlockedMax and InterlockedMin won't work with 2 arguments anymore

### ISSUE THREAD

**Issue by bioglaze** [KhronosGroup/glslang#1248]
I updated LunarG SDK from 1.0.65.0 to 1.0.68.0 and the following HLSL code stopped working:

```
groupshared uint ldsZMax;
groupshared uint ldsZMin;
...

void CalculateMinMaxDepthInLds( uint3 globalThreadIdx, uint depthBufferSampleIdx )
{
    float viewPosZ = depthTexture.Load( uint3( globalThreadIdx.x, globalThreadIdx.y, 0 ) ).x;

    uint z = asuint( viewPosZ );

    if (viewPosZ != 0.f)
    {
        InterlockedMax( ldsZMax, z );
        InterlockedMin( ldsZMin, z );
    }
}
```

Now I get this error in `vkCreateShaderModule`:

> Vulkan error: [SC], code: 5: SPIR-V module not valid: AtomicSMax: expected Result Type to be int scalar type

The issue doesn't happen when I use the three argument versions of those functions.

**Comment by johnkslang** [comment]
Do you know if this is a validator issue or a glslang issue?

Posting a working example will help me more quickly help figure that out.

**Comment by bioglaze** [comment]
I don't know if it's a validator or glslang issue but I can test soon if it works without validation. AFAIK any HLSL shader that uses InterlockedMax or InterlockedMin with 2 arguments instead of 3 causes the error, so reproducing should be trivial.

**Comment by bioglaze** [comment]
I tested without validation and it seems to work, so could be a validator bug.

**Comment by bioglaze** [comment]
@LoopDawg I'm not seeing this anymore.
