### ISSUE TITLE
HLSL: Ternary if (?:) should likely use OpSelectionMerge Flatten

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1249]
The way fxc works is you can express a condition in a variety of ways:

- if else without any attributes
- if else with [flatten] or [branch]
- ternary if (?:)

For if/else, fxc will generate either a branch or select instruction, depending on whether you use attributes and on command line flags (/Gfp - prefer branches, /Gfa - avoid branches).
For ternary if (?:), fxc never - as far as I can tell - generates a branch.

I can't speak for the entire industry but many shaders I've seen expect this, using ?: when you want to express a select, and `if` with an explicit attribute when you want a branch. Now, generating OpSelect might be hard for glslang because it only works on vector/scalar arguments, so it might make sense to just tag the branch with Flatten and have spirv-opt deal with the rest (spirv-opt has an if-conversion pass that currently can't flatten many kinds of branches, but it could be extended to do so in presence of an explicit attribute).

I'm not sure what approach dxc takes to SPIRV generation for ternary operator, maybe @antiagainst can comment on that.

**Comment by zeux** [comment]
This also holds for &&/|| operators (they don't seem to short-circuit) and for side-effecting expressions, for example this shader:

```
RWTexture1D<float> tex;

int sideeffectingfunc(float value)
{
	tex[0] = value;
	return 1;
}

float4 main(uint id: SV_VertexID): SV_Position
{
	return (id == 0 && tex[id + sideeffectingfunc(1)] > 0.5) ? id + sideeffectingfunc(2) : tex[id + 1];
}
```

With optimizations disabled and codegen set to prefer branches doesn't generate a single branch in fxc.

**Comment by zeux** [comment]
Ah, indeed, the docs (https://msdn.microsoft.com/en-us/library/windows/desktop/bb509631(v=vs.85).aspx) state that

> Unlike short-circuit evaluation of &&, ||, and ?: in C, HLSL expressions never short-circuit an evaluation because they are vector operations. All sides of the expression are always evaluated.

So the correct thing for glslang to do seems to be generate OpSelect, and the simple thing to do is to generate Flatten decorations.

**Comment by johnkslang** [comment]
Glslang should correctly already be handling the short-circuit distinction. 

For the general case, the expressions, then-block, and else-block involved can be large and complex, and have side effects, so it is worth not unconditionally emitting them.

Ternary `?:` will generate OpSelect for very trivial things.

In SPIR-V, the flatten and branch attributes are hints, they don't force anything. Are you suggesting they have semantic meaning?

The final decisions should be up to the driver back end, to decide between OpSelect and control flow.  Although, any offline optimizer might also swap one for the other, possibly based on some settings.

**Comment by zeux** [comment]
I'm not sure I understand what this:

> Glslang should correctly already be handling the short-circuit distinction.

means? Here's an example of a shader that, when compiled with glslang, results in SPIRV where the computation (`+` etc.) is in the conditional control flow, and `OpSelectionMerge` has an attribute `None`:

```
float4 main(float4 uv: TEXCOORD0): SV_Target0
{
	return uv.w < 0.5 ? uv + 1 : 2;
}
```

**Comment by zeux** [comment]
> In SPIR-V, the flatten and branch attributes are hints, they don't force anything. Are you suggesting they have semantic meaning?

I'm suggesting that, while glslang currently incorrectly generates a branch from `?:`, one way of fixing that would be to generate a branch with `Flatten` decoration and rely on SPIRV-Tools to actually flatten it. Currently glslang provides support for emitting the correct decorations for explicit if statements, but HLSL syntax does not provide any way to specify the branch type for '?:' - understandably, because it shouldn't result in a branch in the first place.

**Comment by antiagainst** [comment]
> Now, generating OpSelect might be hard for glslang because it only works on vector/scalar arguments,

+1 to the type support difference between HLSL and SPIR-V. HLSL supports more types in conditional operator than what OpSelect can support.

>  so it might make sense to just tag the branch with Flatten and have spirv-opt deal with the rest (spirv-opt has an if-conversion pass that currently can't flatten many kinds of branches, but it could be extended to do so in presence of an explicit attribute).

IMHO, sometimes it's not easy to optimize control flows into OpSelect instructions, even with `Flatten` properly attached to OpSelectionMerge instructions. For example, selecting two matrices using the conditional operator: OpSelect does not support matrix types; so, if trying to change the control flow into OpSelect, spirv-opt can arguably only decompose the whole matrix into component vectors. That will cause quite some pain in handling following matrix operations.

**Comment by antiagainst** [comment]
@zeux: In DXC, right now if statements are always translated into control flows; and conditional operators are translated into OpSelect instructions, as long as the type is supported by OpSelect. DXC will generate OpSelect for the above example (`uv.w < 0.5 ? uv + 1 : 2`) because the result type is integer.

**Comment by johnkslang** [comment]
It is possible that a branch is cheaper than pulling something in from memory. It is platform specific which is fastest. Glslang generates the OpSelect only when 100% sure it would be cheaper than evaluating the expressions. Unless side effects are required?

I think the main things to consider changing here are:

- OpSelect works on more types, which is already an internally tracked request for SPIR-V
- :? emit the flatten hint

Yes?

**Comment by zeux** [comment]
For HLSL source, the performance aspects are relevant but regardless of what is faster, HLSL spec says that both branches are evaluated - for any side-effecting operations the spec-compliant SPIRV has to evaluate both branches, and then either OpSelect the result or, if OpSelect is impossible to use, use branches to pick the already computed result.

In absence of side effects, you could emit branch or selection and the results should be the same of course; however, the expectation for HLSL is that there's no branch, and it affects performance. 

Performance here doesn't just depend on the platform - it also fundamentally depends on the programmer's expectation about branch divergence, how expensive the computation on each side is, etc. For example, if it's just a texture load & constant on both sides, you'd expect a driver to use selection because it's not certain whether the branch is coherent and both sides are reasonably cheap; but if the texture fetch UV are random, and branch condition is coherent and almost always ends up picking the branch with a constant, it makes more sense to use a branch.

Because of this, you need the programmer to have control - for `if` you'd expect them to annotate the branch with [flatten] if they expect the control flow to be divergent, and [branch] if they expect control flow to be coherent and the rarely picked branch to be expensive. For `?:` due to HLSL spec, the assumption *is* that this maps to OpSelect. If a branch can be faster in a specific shader, the programmer has to use `if` (with or without explicit [branch] attribute as appropriate).

Note that this issue only talks about HLSL source; I'm not sure what semantics GLSL attaches to `?:`.

**Comment by zeux** [comment]
So - it would be nice to extend OpSelect to handle more types but this is really out of the scope of this issue. This issue argues that the current codegen for `?:` doesn't match HLSL spec; the approach that makes the most sense to me is to emit OpSelect when the types allow that, and branch-based selection of unconditionally computed results if not - sounds like that's what DXC is doing.

**Comment by johnkslang** [comment]
Okay, thanks. `flatten` is not allowed to change semantics. If glslang is not always evaluating both sides of something which it is semantically required to unconditionally evaluate, then it needs to do that, independent of use of `flatten`.

So, it helps to focus on the semantics, and not focus on a possible fix through a hint. We have to quite clear the distinction between semantic and hint. A back end is required to respect a front-end's decision about short-circuiting or not, when side effects are present, so a hint cannot reverse in incorrect decision.

**Comment by johnkslang** [comment]
Just reporting my verification here.

GLSL matches C++. From the GLSL spec: 

> The ternary selection operator (?:). It operates on three expressions (exp1 ? exp2 : exp3). This
operator evaluates the first expression, which must result in a scalar Boolean. If the result is true, it
selects to evaluate the second expression, otherwise it selects to evaluate the third expression. Only
one of the second and third expressions is evaluated. 

From HLSL documentation:

> Unlike short-circuit evaluation of &&, ||, and ?: in C, HLSL expressions never short-circuit an evaluation because they are vector operations. All sides of the expression are always evaluated.

**Comment by johnkslang** [comment]
To be clear, the only bug I see is that, for example, HLSL in glslang will only increment one of `x` and `y` in the following:

```
a > 4 ? ++x : ++y // HLSL says to increment both x and y, C and GLSL say the opposite
```

The AST doesn't currently have an operator for selection requiring both sides to be executed.

**Comment by johnkslang** [comment]
#1253 fixes this, adding AST knowledge that both sides of a selection must be executed. This indeed often results in an OpSelect instead of control flow, but the details were somewhat complex.  See the PR.

**Comment by zeux** [comment]
Thank you! This works as expected on our shaders as far as I can tell.
