### ISSUE TITLE
glslangValidator.exe Release detected as Trojan.

### ISSUE THREAD

**Issue by tglewis1993** [KhronosGroup/glslang#1251]
Windows Defender caught glslang-master-windows-x64-Release executable from master-tot as a Trojan. I've attached the warning below.
![viruswarning](https://user-images.githubusercontent.com/15706219/36365763-e10881d0-1542-11e8-87bb-9ec18e9a1702.PNG)

I'm sure this is a false positive and the Debug version doesn't get treated as such, but I thought I'd bring up the issue. Windows 10. 

As I am on a work computer and can't add this as an accepted file, how would you recommend I compile GLSL shaders as SPIR-V?

Thanks.

**Comment by johnkslang** [comment]
Is it better if you build it yourself? Or is using the debug build okay? Is this actually a bug against Windows Defender?

**Comment by tglewis1993** [comment]
Unfortunately I can't test whether this is caught by Windows Defender on any other machine, so it could be a one off as far as I know. I've opted to build it myself, and use the glslang library with the ShaderLang header.

**Comment by tglewis1993** [comment]
Wanted to add building the glslangValidator.exe myself in release did not kick Windows Defender into action.
