### ISSUE TITLE
initializing global aggregates from specialization constants does not work

### ISSUE THREAD

**Issue by raunSSNLF** [KhronosGroup/glslang#1252]
I'm trying to initialize global vectors of bools, and global structs containing bools from a bool specialization constant.  I'm getting parse errors from.

```
layout (constant_id = 10) const bool c1 = true;     // OpSpecConstantTrue
layout (constant_id = 11) const bool c2 = false;    // OpSpecConstantFalse

// init struct from specialization constant
struct struct_type {
        bool a;
        bool b;
    };
const struct_type spec_const_struct = struct_type(c1, c2); // problem
// ERROR: frag_spec_constnat.frag:18: '=' : global const initializers must be constant ' const structure{ global bool a,  global bool b}'
// ERROR: 1 compilation errors.  No code generated.
```
and ...

```
// const array of bool, initialized from bool spec constant
const bool[2] spec_const_array = bool[2](c1, c2); // problem
	// ERROR: frag_spec_constnat.frag:14: 'spec_const_array' : redeclaration of array with size
	// ERROR: frag_spec_constnat.frag:14: '=' : global const initializers must be constant ' const 2-element array of bool'
	// ERROR: 2 compilation errors.  No code generated.
```

Example shader is attached.  File extension renamed to .log to get around extension limitation on attachments.

[frag_spec_constnat .frag.log](https://github.com/KhronosGroup/glslang/files/1741065/frag_spec_constnat.frag.log)

**Comment by johnkslang** [comment]
I believe full aggregation of specialization constants is not yet complete.  Will need to look deeper into this.

**Comment by johnkslang** [comment]
The GL_KHR_vulkan_glsl specification does not directly support this. It says scalars and vectors can be made:

> While SPIR-V specialization constants are only for scalars, a vector can be made by operations on scalars...

But then is silent about aggregates.

**Comment by johnkslang** [comment]
More information.  The white list of allowed operations that can result in a specialization constant does not include structure constructors.  It does not even include floating-point vectors:

>   - int(), uint(), and bool() constructors for type conversions  from any of the following types to any of the following types:
>           * int
>           * uint
>           * bool
>   - vector versions of the above conversion constructors

If this is important functionality, let's file a feature request against GLSL/Vulkan.
