### ISSUE TITLE
Empty uniform buffers can not be parsed by glslang

### ISSUE THREAD

**Issue by snipstruis** [KhronosGroup/glslang#1254]
### Problem
We are auto-generating GLSL files and sometimes they have empty uniform blocks.
We use the GLSLang C++ API to generate SPIR-V from these files.
Unfortunately, the GLSL parser of GLSLang fails to parse empty uniform blocks.

Minimum test program:
```
#version 330
uniform empty{};
void main(){}
```
when compiled with:
```
.\glslangValidator.exe -H -l -e main test.vert
```
produces the following output:
```
test.vert
ERROR: test.vert:2: '' :  syntax error, unexpected RIGHT_BRACE
ERROR: 1 compilation errors.  No code generated.


ERROR: Linking vertex stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```
Inserting a dummy provides a workaround:
```
#version 330
uniform empty{float dummy;};
void main(){}
```
Compiled with:
```
.\glslangValidator.exe -H -l -e main test.vert
```
Works as expected with the following output:
```
test.vert
// Module Version 10000
// Generated by (magic number): 80004
// Id's are bound by 10

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main"
                              Source GLSL 330
                              Name 4  "main"
                              Name 7  "empty"
                              MemberName 7(empty) 0  "dummy"
                              Name 9  ""
                              MemberDecorate 7(empty) 0 Offset 0
                              Decorate 7(empty) Block
                              Decorate 9 DescriptorSet 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
        7(empty):             TypeStruct 6(float)
               8:             TypePointer Uniform 7(empty)
               9:      8(ptr) Variable Uniform
         4(main):           2 Function None 3
               5:             Label
                              Return
                              FunctionEnd
```
### Workaround
Insert dummy variable with long name as not to cause name conflicts.

### Solution
Update the parser so that empty uniforms are correctly parsed.

**Comment by johnkslang** [comment]
Does the specification allow empty uniform blocks? Note the specification does not allow empty structs.

**Comment by snipstruis** [comment]
The spec does not explicitly say it is allowed but it definitly doesn't forbid it. (I did not exhaustively read it but I searched for the word 'empty')
 I think it is implied that it is okay by the quote:
"Note that the default uniform block always exists even if it is empty."
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_uniform_buffer_object.txt

Searching for 'empty' in the glsl spirv spec also turns up nothing.
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gl_spirv.txt

In C, structs are not allowed to be zero in size to ensure different objects have different adresses. If that is also the reason in GLSL then, the reason would not apply to uniform blocks without an instance, since they are per definition unique.

So the answer is: I think its legal? I can't find evidence to suggest it is illegal.

**Comment by snipstruis** [comment]
Nevermind, It is not allowed:
> _interface-block :_
> layout-qualifier_opt interface-qualifier block-name { member-list } instance-name_opt ;
> // Note: Order of qualifiers is not actually fixed; qualifiers can be in any order.

Where member list is defined as follows:

> _member-list :_
> member-declaration
> member-declaration member-list

page 52 of 4.6 spec: https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf
