### ISSUE TITLE
HLSL: Inconsistent handling of float1 and float in layout

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/glslang#1257]
For the following HLSL source code:
```hlsl
struct S {
    float ff1[1];
    float ff2[1];
    float ff3[1];
    float ff4[1];

    float1 f1[1];
    float1 f2[1];
    float1 f3[1];
    float1 f4[1];
};

StructuredBuffer<S> MySBuffer;

float4 main() : SV_Target {
    return MySBuffer[0].ff1[0] + MySBuffer[0].f3[0];
}
```

The layout decorations generated for it right now look like:
```
OpMemberDecorate %S 0 Offset 0
OpMemberDecorate %S 1 Offset 4
OpMemberDecorate %S 2 Offset 8
OpMemberDecorate %S 3 Offset 12
OpMemberDecorate %S 4 Offset 16
OpMemberDecorate %S 5 Offset 32
OpMemberDecorate %S 6 Offset 48
OpMemberDecorate %S 7 Offset 64
```

We are treating `float` and `float1` differently here. But I think they should be treated the same?

**Comment by antiagainst** [comment]
cc @ehsannas @chaoticbob

**Comment by johnkslang** [comment]
Ah, perhaps so.  Sometimes float1 is like a vector, sometimes like a scalar. But, it does seem it should be treated as a scalar for layout purposes. I (or someone) should first check what FXC does.

**Comment by johnkslang** [comment]
Actually, it works right for float1 when it is not an array. I'll fix it for arrays, and this will be okay for arrays of float1 and float2.

For arrays float3, fxc still packs them with no padding, even with a variable index, which seems quite incorrect for Vulkan when considering it makes a variable indexed object, which when dereferenced gives a run-time address for a vec3 that straddles a vec4 boundary. I don't think Vulkan intends to support that, or this needs to become a spec issue.

The Vulkan rules are:

>- A three- or four-component vector, with components of size N, has a base alignment of 4 N.

>- An array has a base alignment equal to the base alignment of its element type...

>Any ArrayStride or MatrixStride decoration must be an integer multiple of the base alignment of the array or matrix from above.

**Comment by antiagainst** [comment]
Agreed.
