### ISSUE TITLE
glslangValidator generates invalid SPIR-V with nested structs

### ISSUE THREAD

**Issue by afd** [KhronosGroup/glslang#1258]
glslangValidator generates what appears to be invalid SPIR-V for the following GLSL fragment shader:

#version 450

precision highp float;

struct U {
 mat2 m;
};
struct T {
 mat2 m;
};
struct S {
 T t;
 U u;
};
void main()
{
  S(T(mat2(1.0)), U(mat2(1.0)));
}

The SPIR-V that gets generated is as follows:

               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource GLSL 450
               OpName %4 "main"
               OpName %9 "T"
               OpMemberName %9 0 "m"
               OpName %10 "U"
               OpMemberName %10 0 "m"
               OpName %11 "S"
               OpMemberName %11 0 "t"
               OpMemberName %11 1 "u"
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeFloat 32
          %7 = OpTypeVector %6 2
          %8 = OpTypeMatrix %7 2
          %9 = OpTypeStruct %8
         %10 = OpTypeStruct %8
         %11 = OpTypeStruct %9 %10
         %12 = OpConstant %6 1
         %13 = OpConstant %6 0
         %14 = OpConstantComposite %7 %12 %13
         %15 = OpConstantComposite %7 %13 %12
         %16 = OpConstantComposite %8 %14 %15
         %17 = OpConstantComposite %9 %16
         %18 = OpConstantComposite %11 %17 %17
          %4 = OpFunction %2 None %3
          %5 = OpLabel
               OpReturn
               OpFunctionEnd

The problem is:

         %18 = OpConstantComposite %11 %17 %17

This has result type %11, which is:

         %11 = OpTypeStruct %9 %10

Now %17 has type %9, so is fine for the first of the two %17 arguments; but the second type %17 is used, type %10 is expected.

spirv-val rejects the resulting SPIR-V:

error: 113: OpConstantComposite Constituent <id> '17' type does not match the Result Type <id> '11's member type.

**Comment by afd** [comment]
I double-checked and this manifests with the latest commit: 57f6a016f05b83f5f67d46e61771e8f69e0374db

**Comment by dneto0** [comment]
I agree with the validator.  :-)

**Comment by johnkslang** [comment]
Agreed. Something optimized type sharing that should not have.

**Comment by johnkslang** [comment]
This is specifically about caching constant structures.

Constants were generally cached by type opcode, but all structures share the
same type opcode (OpTypeStruct), so they need to be cached by type id.
