### ISSUE TITLE
Optimizer recipe: Recommend using AggressiveDCE pass instead of internal DCEInst calls in local single- and multi-store elimination

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1260]
SPIRV-Tools will be removing internal calls DCEInst inside of LocalSingleStoreElimPass and LocalMultiStoreElimPass.    It's faster overall to run a full ADCE pass after those specialized passes.
See https://github.com/KhronosGroup/SPIRV-Tools/pull/1347

cc: @greg-lunarg @s-perron

**Comment by s-perron** [comment]
FYI, I've just merged this change into spir-v tools.  Changes to the set of optimization used may be necessary if you do not use the predefined sets provided.

**Comment by greg-lunarg** [comment]
This is resolved with #1313.
