### ISSUE TITLE
auto-map-locations on input/output only generates location 0

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1261]
Sample vertex shader:
```
#version 310 es

in vec4 m_in0;
in vec4 m_in1;
out vec4 m_out0;
out vec4 m_out1;

void main() {
 m_out0 = m_in0;
 m_out1 = m_in0 + m_in1;
}
```

Compiled with:
glslangValidator -H -V --aml x.vert
produces

```

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 9 11 13 15
                              Source ESSL 310
                              Name 4  "main"
                              Name 9  "m_out0"
                              Name 11  "m_in0"
                              Name 13  "m_out1"
                              Name 15  "m_in1"
                              Decorate 9(m_out0) Location 0
                              Decorate 11(m_in0) Location 0
                              Decorate 13(m_out1) Location 0
                              Decorate 15(m_in1) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
       9(m_out0):      8(ptr) Variable Output
              10:             TypePointer Input 7(fvec4)
       11(m_in0):     10(ptr) Variable Input
      13(m_out1):      8(ptr) Variable Output
       15(m_in1):     10(ptr) Variable Input
         4(main):           2 Function None 3
               5:             Label
              12:    7(fvec4) Load 11(m_in0)
                              Store 9(m_out0) 12
              14:    7(fvec4) Load 11(m_in0)
              16:    7(fvec4) Load 15(m_in1)
              17:    7(fvec4) FAdd 14 16
                              Store 13(m_out1) 17
                              Return
                              FunctionEnd
```

It seems that m_in1 and m_out1 should get something other than Location 0

**Comment by johnkslang** [comment]
In general, this functionality is only useful now for testing existing shaders without editing them.  Though, I thought it would auto increment.

There is no cross-stage support, so it is not very useful yet for real application run-time use.

From the usage:  "...(fragile, not cross stage)".

What specific functionality are you looking for?

**Comment by dneto0** [comment]
I too expected it to increment.  
I found this when writing tests for the Shaderc functionality that exposes --auto-map-locations.

I would think the minimum functionality would be to avoid obvious conflicts. 

Vulkan 14.1.4 bans location conflicts:  "Any two inputs listed as operands on the same OpEntryPoint must not be assigned the same location, either explicitly or implicitly. Any two outputs listed as operands on the same OpEntryPoint must not be assigned the same location, either explicitly or implicitly."

It would be useful to be able to have outputs compiled under Vulkan rules pass Vulkan validation.

> In general, this functionality is only useful now for testing existing shaders without editing them.

I've heard that real users are using this feature to generate *something*, then patching the SPIR-V binary after the fact with numbers that line up across stages.  That sounds a bit gross to me, but people do what they have to do.

**Comment by dneto0** [comment]
I guess this is an instance of Hyrum's Law http://www.hyrumslaw.com/  :-)

**Comment by johnkslang** [comment]
If we need a tool that does cross-stage location assignment, then we should have one. Maybe what  you are describing is such a tool. Glslang auto-incrementing would not remove the need for such a tool. 

Perhaps you don't want to expose this feature in shaderc?

**Comment by dneto0** [comment]
The existence of the feature in Glslang put a little pressure for having the feature in Shaderc.
Someone contributed the feature in Shaderc yesterday.
In any case, I've updated [my tests PR](https://github.com/google/shaderc/pull/427) to only check Location 0.  So there's no time-urgency for this, and I'll track whatever happens here.

**Comment by johnkslang** [comment]
> I guess this is an instance of Hyrum's Law http://www.hyrumslaw.com/ :-)

> I would think the minimum functionality would be to avoid obvious conflicts.

It seems that would make things worse, regarding appearing to deliver something it does not (that is, locations that would work in a pipeline, which they won't because it is not cross stage).

I think that's why I left it more broken, to fool less.

**Comment by johnkslang** [comment]
Something else I should have said:

This is all in the IO remapper, which people override to implement custom functionality. Someone, could, for example, put in a custom hash, if that works for their pipeline. Or, auto-increment, if they declare variables in the same order, or... a variety of techniques.

It is just plumbed in so they can override to what they want.

**Comment by johnkslang** [comment]
Shaderc should expose the feature, to access the user's overriding implementation of the IO remapper.

**Comment by johnkslang** [comment]
From the io mapper, regarding auto-location mapping:

```
        // Placeholder.
        // TODO: It would be nice to flesh this out using 
        // intermediate->computeTypeLocationSize(type), or functions that call it like
        // intermediate->addUsedLocation()
        // These in turn would want the intermediate, which is not available here, but
        // is available in many places,...
```

I can do the work to bring in the needed infrastructure to compute the size, as is needed as a prerequisite to auto-incrementing.

**Comment by dneto0** [comment]
> Shaderc should expose the feature, to access the user's overriding implementation of the IO remapper.

That's a fair suggestion.  

Glslang's TIoMapResolver is tied to Glslang's AST.  That's more than I would like to expose via Shaderc. Manipulating IO bindings seems like functionality that should be exposed in SPIRV-Tools via general-purpose SPIR-V module reflection plus very low level primitives.  But I haven't thought deeply about it.

**Comment by johnkslang** [comment]
Yes, io mapping currently relies on the AST. Maybe it could be factored into two stages, one needs the AST, and one is just the raw SPIR-V level you imagine. 

Current situation was supplied by customers with specific needs to solve their problems. It does not need to be mutually exclusive with the kind of solution you envision.

I see the only reason the "AST"  would be used for auto-location `computeTypeLocationSize()` is to query the stage (not from the AST-proper, but from the containing `TIntermediate`), but that could be side-band information instead.

**Comment by johnkslang** [comment]
So, I changed it to do some location mapping:

- factored `computeTypeLocationSize()` out of needing `TIntermediate` (the "AST") contents
- use `computeTypeLocationSize()` to show how to know how many locations an object needs

However, it still does not do cross stage, or mixed location/no-location analysis.

To do this right, even for one stage, you need a whole resource tracker, hole finder, etc. to handle the mix of declarations using location and not using location.

**Comment by johnkslang** [comment]
New output, for you example, includes

```
                              Decorate 9(m_out0) Location 0
                              Decorate 11(m_in0) Location 0
                              Decorate 13(m_out1) Location 1
                              Decorate 15(m_in1) Location 1
```

But, more generally, it bumps the location to properly account for the size of the object, which depends on a few things.

**Comment by dneto0** [comment]
This solution hits the sweet spot for me.  Thanks
