### ISSUE TITLE
Calling refract with double I and N incorrectly promotes eta to a double

### ISSUE THREAD

**Issue by bpeel** [KhronosGroup/glslang#1279]
The arguments to the refract extended instruction are documented as follows:

> The type of _I_ and _N_ must be a scalar or vector with a floating-point component type.
> 
> The type of _eta_ must be a 16-bit or 32-bit floating-point scalar.
>
> _Result Type_, the type of _I_, and the type of _N_ must all be the same type.

This implies that _I_ and _N_ can be doubles but _eta_ will always be 32- or 16-bit. Indeed the equivalent function in GLSL has a double alternative defined as follows:

```
genDType refract (genDType I,
                  genDType N,
                  float eta)
```

However if you actually try to use this combination of argument types, glslang seems to promote the final argument to a 64-bit value and so generates invalid SPIR-V. For example:

```
#version 430

layout(location = 0) in double I;
layout(location = 2) in double N;
layout(location = 4) in float eta;

void main()
{
        double result = refract(I, N, eta);
        gl_Position.x = float(result);
}
```

This generates the following instructions:

```
         %11 = OpLoad %double %I
         %13 = OpLoad %double %N
         %17 = OpLoad %float %eta
         %18 = OpFConvert %double %17
         %19 = OpExtInst %double %1 Refract %11 %13 %18
```

**Comment by johnkslang** [comment]
Update: Khronos has decided the types should match, not having mixed double and float.
