### ISSUE TITLE
Commit e518772dc caused regression for ES shaders

### ISSUE THREAD

**Issue by alegal-arm** [KhronosGroup/glslang#1281]
Commit e518772dc99015c48c57789d21a243669adba8f0 caused a regression on a VK-GL-CTS shader. The reason for the regression is that OpArrayLength now returns UINT while in the ES length() is signed integer. 

```
#version 310 es
layout(set=0, binding=0, std430) readonly buffer x {
   int xs[];
};
layout(set=0, binding=1, std430) writeonly buffer y {
   int observed_size;
};
layout(local_size_x=1) in;
void main (void) {
   observed_size = xs.length();
}
```

**Comment by alegal-arm** [comment]
%15 = OpArrayLength %int %__0 0
         %17 = OpAccessChain %_ptr_Uniform_int %_ %int_0
               OpStore %17 %15

**Comment by johnkslang** [comment]
Yes, I think the fix was incomplete. It is probably best to revert it to how things have been and give a chance for a more complete fix.

**Comment by johnkslang** [comment]
This was reverted by ac3707921ed313eaba1c206e8113b85fef054c34.
