### ISSUE TITLE
Mixing multi-dimensional array definition syntaxes inside a block/struct fails

### ISSUE THREAD

**Issue by infapi00** [KhronosGroup/glslang#1290]
From the GLSL spec, 4.1.9:

> An array of arrays can be declared as
> vec4 a[3][2]; // size-3 array of size-2 array of vec4
>
> which declares a one-dimensional array of size 3 of one-dimensional arrays of size 2 of vec4s. These
> following declarations do the same thing:
>
> vec4[2] a[3]; // size-3 array of size-2 array of vec4
> vec4[3][2] a; // size-3 array of size-2 array of vec4

Right now the first one (the more common AFAIU) and the last one example are working fine. It fails the second example, what I call "mixing syntaxes" (sorry, I didn't find a better expression).

So for example, the following shader:
> #version 450
> 
> struct S {
>   vec4 [2] x[2];
> };
> 
> layout (location = 3) uniform S s;
> layout (location = 5) out vec4 outColor;
> 
> void main()
> {
>   outColor = s.x[1][1];
> }

Fails with the following error:
> ERROR: /tmp/aoa_test_mix_syntax.frag:12: 'assign' :  cannot convert from ' temp float' to 'layout( location=5) out 4-component vector of float'
> ERROR: /tmp/aoa_test_mix_syntax.frag:12: '' : compilation terminated 
> ERROR: 2 compilation errors.  No code generated.
> 
> 
> SPIR-V is not generated for failed compile or link

And the really similar following shader:

> #version 450
> 
> layout (location = 5) out vec4 outColor;
> layout (binding = 3) uniform block {
>   vec4 [2] x[2];
> } arr;
> 
> void main()
> {
>   outColor = arr.x[1][1];
> }

Fails with the really similar error:
> ERROR: /tmp/aoa_test_mix_syntax.frag:10: 'assign' :  cannot convert from 'layout( column_major std140) temp float' to 'layout( location=5) out 4-component vector of float'
> ERROR: /tmp/aoa_test_mix_syntax.frag:10: '' : compilation terminated 
> ERROR: 2 compilation errors.  No code generated.

**Comment by johnkslang** [comment]
I analyzed this and found a couple problems.

It works correctly for non-struct/block-member declarations, but:
- the code that combines the mixed dimension is not executed for the struct member case
- there is too much type sharing happening when one declaration declares multiple variables, e.g.:

`int[3] a[2], b[4];`

Am working on fixes for this.

**Comment by johnkslang** [comment]
#1312 has a quite thorough fix of this and related issues.  See the second commit for the real change; the first commit is just a test print-result change.

**Comment by infapi00** [comment]
> #1312 has a quite thorough fix of this and related issues. See the second commit for the real change; the first commit is just a test print-result change.

Just tested the branch with the shaders that were failing to me, and now they work fine. Thanks!

Not sure if you were expecting a real review of the commits, as Im not really used to the current glslang codebase.

**Comment by johnkslang** [comment]
Great, thank you reporting your results.
