### ISSUE TITLE
GL_AMD_gpu_shader_half_float is erroneously reported as required if half-float variables are used inside an #ifdef block which is removed at preprocessing time

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/glslang#1295]
Consider the following GLSL source code:

```
#ifdef SOME_DEFINE

   float16_t sth = 1.0hf;

#endif 
```
Let SOME_DEFINE be NOT defined in the shader. Under such assumption, GL_AMD_gpu_shader_half_float should *not* be required. However, glslang doesn't seem to notice that the half-floats are used inside an #ifdef block which gets removed at pre-processing stage and believes the corresponding float16 extension is needed. This leads to an error reported at compilation time, which is incorrect.

**Comment by amdrexu** [comment]
I think this issue is general. When you have such shader, the error is reported mistakenly as well:
```

#version 450 core

#if 0
uint64_t u64 = 45ul;
#endif

void main()
{
    float f = 0.0;
}
```

**Comment by johnkslang** [comment]
Yes, this is interesting. Input must still be tokenized, even under `#if 0`, it is not just blindly skipped over, and should be tokenizable (and comments can comment out the `#endif`).  Arguably,  lexical errors are still real errors.

But, obviously, for glslang, we want to accept the union of all input languages regarding what's lexically legal under `#if 0`, so I will look at doing that.

**Comment by johnkslang** [comment]
Note this means error recovery is a real thing for these cases, not just a testing mode. Need to ensure all errors not reported under `#if 0` are errors that are fully recovered from.

**Comment by amdrexu** [comment]
Yes, this is the root cause. The error check should be skipped or be muted if culprit codes are placed within a dead body delimited by #if 0 or #ifdef XXX or #if defined(XX)

**Comment by johnkslang** [comment]
#1302 fixes it. Most PP errors are appropriate always, so I manually captured the right subset to skip.
