### ISSUE TITLE
Shifts should be allowed for base/shift operands of different bit-width and sign

### ISSUE THREAD

**Issue by infapi00** [KhronosGroup/glslang#1296]
Since commit 66011cb2c22a19c2fc18885d6a9f2a8fee191ce8 the following shader would fail to be converted to SPIR-V under OpenGL semantics (and I assume under Vulkan too):

> #extension GL_ARB_gpu_shader_int64 : require
> writeonly uniform image2D tex;
> layout(local_size_x = 54) in;
> uniform int64_t arg0;
> uniform uint arg1;
> uniform int64_t expected;
> 
> void main()
> {
>   vec4 tmp_color;
>   int64_t result = (arg0 << arg1);
>   tmp_color = result == expected ? vec4(0.0, 1.0, 0.0, 1.0) : vec4(1.0, 0.0, 0.0, 1.0);
>   ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
>   imageStore(tex, coord, tmp_color);
> }

With the following error:

> '<<' :  wrong operand types: no operation '<<' exists that takes a left-hand operand of type 'layout( location=1) uniform int64_t' and a right operand of type 'layout( location=2) uniform uint' (or there is no acceptable conversion)

The mentioned commit changed the checks at TIntermediate::addConversion, forcing base/shift to be of the same sign and same rank. 

But from GLSL spec:

> The shift operators (<<) and (>>). For both operators, the operands must be signed or unsigned
> integers or integer vectors. One operand can be signed while the other is unsigned. In all cases, the
> resulting type will be the same type as the left operand. If the first operand is a scalar, the second
> operand has to be a scalar as well. If the first operand is a vector, the second operand must be a scalar
> or a vector, and the result is computed component-wise. The result is undefined if the right operand is
> negative, or greater than or equal to the number of bits in the left expression's base type.

so base/shift can be of different sign

And from SPIR-V spec:

> The type of each Base and Shift must be a scalar or vector of integer type. Base and Shift must have the same number
> of components. The number of components and bit width of the type of Base must be the same as in Result Type.
> Shift is treated as unsigned. The result is undefined if Shift is greater than the bit width of the components of Base.

it asks Base and Result to be the same bit-width, not Base and Shift operands.

This was found while working on improving ARB_gl_spirv support for the mesa driver. We use glslang to convert GLSL shaders to SPIR-V. After the mentioned commit, a test that was working properly using the generated SPIR-V started to fail as glslang rejected to generate such SPIR-V binary.

**Comment by johnkslang** [comment]
See discussion of this in PR #1297, where I proposed another fix.

**Comment by johnkslang** [comment]
This will now be fixed by #1299.
