### ISSUE TITLE
GlslangToSpv() doesn't apply optimizations unless optimizeForSize is true

### ISSUE THREAD

**Issue by JustSid** [KhronosGroup/glslang#1298]
Basically what the title says, although I'm not sure if this is a bug or not. The problem is in this if:

https://github.com/KhronosGroup/glslang/blob/ac3707921ed313eaba1c206e8113b85fef054c34/SPIRV/GlslangToSpv.cpp#L6714-L6717

So the function only runs if the source used to be HLSL or size optimization is on AND optimizations aren't disabled. Not sure if this is intentional or not, but without it, the resulting SPIR-V is basically verbatim what I passed in via GLSL without any optimization done whatsoever. For example, I would have expected dead code elimination to happen no matter whether I optimize for size or not.

**Comment by johnkslang** [comment]
Typically, glslang is just being a front end, not an optimizer.

SPIR-V Tools at https://github.com/KhronosGroup/SPIRV-Tools has a full suite of tools, including optimizations.

The HLSL translation done by glslang is faithful to the HLSL, which is illegal on today's shader models until some optimization-like transforms are done. So, to "legalize" this HLSL, these were brought into glslang.  The top goal of glslang though is still to produce the faithful-to-source translation.

**Comment by JustSid** [comment]
That's fair, but how come `SpvOptions` allows me to "enable" optimizations in the first place if this is true?

Don't get me wrong, I'm aware that I can just run the optimizer myself on my generated SPIR-V, and that's exactly what I'm doing anyways. What I find weird is that if glslang is *not* supposed to transform my code and stay faithful to it, how come enabling size optimization is running a bunch of transforms that very much change my code? Clearly this is supposed to happen and not just to make SPIR-V compiled from HLSL legal.

Or put differently: If glslang is not supposed to optimize my code, the bug is that a) I can specify that I want optimizations (which becomes a no-op) and b) enabling optimization for size vastly transforms my code to the point where it's hard to figure out what came from where.

Maybe I'm just missing something here though?

**Comment by johnkslang** [comment]
> That's fair, but how come SpvOptions allows me to "enable" optimizations in the first place if this is the case?

To do HLSL legalization.

> ... how come enabling size optimization... Clearly this is supposed to happen and not just to make SPIR-V compiled from HLSL legal.

I think LunarG conflated a bit size and legalization transforms, but mostly just in name, as they are quite similar/overlapping. But the required point is the HLSL legalization, which when came along, benefited greatly by size transforms.

> I can specify that I want optimizations (which becomes a no-op) and b) enabling optimization for size vastly transforms my code to the point where it's hard to figure out what came from where.

It is certainly up to you then whether or not you want to do it.

**Comment by JustSid** [comment]
Okay, so, HLSL legalization requires transforms, I get that part. When I look at the code, I can see that they are automatically enabled if the source language was HLSL. Here is the part that confuses me as consumer of the API:

	glslang::SpvOptions spvOptions;

	spvOptions.generateDebugInfo = true;
	spvOptions.disableOptimizer = false;
	spvOptions.optimizeSize = false;

	glslang::GlslangToSpv(&intermediate, spirv, &logger, &spvOptions);

There is no documentation around this, so naively I assumed that not disabling optimizations and not enabling size optimizations would be something along the lines of passing "-O3" or so. And if I enable size optimizations it'd be something like "-Os".

It turns out that in reality not disabling optimizations and not enabling size optimizations means "-O0" which isn't exactly straightforward.

**Comment by johnkslang** [comment]
So, I agree with the confusion of size, and wish it was handled differently, but I don't think we should take it away now.  (My goal was only for glslang to do legalization.)

Some of the statements above are source-language specific, because the point was supposed to be just legalization for HLSL.  Here's a summary:

- GLSL has no optimizations by default.
- HLSL has transforms required for legalization by default.
- We have `-Od` to disable optimizations, and `-Os` to enable size optimizations.
- We don't have `-O[0..3]` because it's supposed to be just a front end, with legalization.
