### ISSUE TITLE
Migrate `Todo.txt` to individual issues

### ISSUE THREAD

**Issue by fkaa** [KhronosGroup/glslang#13]
Currently a bit messy in my opinion and can be unclear to those not familiar (what does +/- mean? missing features, bugs?). Would be easier to keep up to date and see who's working on what.

**Comment by johnkslang** [comment]
These are now migrated to issues, and the Todo.txt deleted.

**Comment by Sineaggi** [comment]
Then perhaps the README.md should be updated, as it still recerefences Todo.txt

**Comment by johnkslang** [comment]
Good point.  Done.
