### ISSUE TITLE
TES/TCS raises error is gl_PerVertex input arrays size is not set

### ISSUE THREAD

**Issue by infapi00** [KhronosGroup/glslang#1300]
If any tessellation evaluation shader or tessellation control shader tries to re-declare gl_Pertex like this:

> #version 450
> 
> in gl_PerVertex {
> vec4 gl_Position;
> } gl_in[];

glslangValidator raises the following error:
> 'gl_PerVertex' : block already declared with size, can't redeclare as implicitly-sized

But from OpenGL 4.6 spec, section 11.2.3.3, "Tessellation Evaluation Shader Inputs":

> User-defined per-vertex
> input variables have a value for each vertex and thus need to be declared as arrays
> or inside input blocks declared as arrays. Declaring an array size is optional. If
> no size is specified, it will be taken from the implementation-dependent maximum
> patch size ( gl_MaxPatchVertices ). If a size is specified, it must match the
> maximum patch size; otherwise, a compile or link error will occur.

Although that paragraph is related to the user-defined input, the rule about explicit array size seems to be worded in a general way. In the same way, there isn't anything on GLSL spec, section 7.1, Built-ins, pointing to the opposite. This suggest that gl_PerVertex can be declared as implicitly-sized, so such redeclaration allowed.

FWIW, the error is raised at ParseHelper.cpp line 3678.

**Comment by johnkslang** [comment]
> In the same way, there isn't anything on GLSL spec, section 7.1, Built-ins, pointing to the opposite.

But, the tessellation control and evaluation built-in variables are not implicitly sized. The specification says they are declared as 

`gl_in[gl_MaxPatchVertices]`

I think it is reasonable to redeclare them that way as well. It is at minimum a great work around.

However, I see your point, as a later example of declaring uses implicit sizing (which should be okay for the geometry stage). I think this makes it a specification question, as I should not expand glslang functionality here if it is not what drivers implement.
