### ISSUE TITLE
Export GLSL variable types and functions to JSON?

### ISSUE THREAD

**Issue by c0nd3v** [KhronosGroup/glslang#1301]
I was wondering if it is possible to export GLSL variable types and functions to JSON so that I could make an extension to a text editor (such as Atom or Visual Studio Code) that has autocomplete. Thank you.

**Comment by c0nd3v** [comment]
I am very grateful for all of the work KhronosGroup has done, but why is there no standard for editing GLSL shaders? This would be extremely useful.

**Comment by johnkslang** [comment]
I believe there are tools out there that can help, and Khronos is internally looking at a more text-based version of the specification, which will make it easier for a tool to grab the names of all the variables and functions.

Of course, these are already in glslang, and you could indeed use glslang to print them out if you wanted to  (see glslang/MachineIndependent/Initialize.cpp). So, perhaps this is a specification question?  See https://github.com/KhronosGroup/GLSL/issues for issues dealing with the specification.

I'll close this here, as not being a glslang issue.
