### ISSUE TITLE
typo in name of EshTargetClientVersion 

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1304]
The type definition of EshTargetClientVersion  starts with "Es" rather than "ES" like all the other enumerated types.

See https://github.com/KhronosGroup/glslang/blob/master/glslang/Public/ShaderLang.h#L135

**Comment by johnkslang** [comment]
Maybe I need a different font. Hopefully, this will fix it backward compatibly:

```
typedef EshTargetClientVersion EShTargetClientVersion;
```
