### ISSUE TITLE
Crash when creating shader modules out of shaders containing HLSL semantics decoration

### ISSUE THREAD

**Issue by Cry-Mory** [KhronosGroup/glslang#1307]
I have an AMD GPU with driver version 18.3.3 (released on 19-March-2018). I have compiled [AuxGeomTextureVS.hlsl.txt](https://github.com/KhronosGroup/glslang/files/1833780/AuxGeomTextureVS.hlsl.txt) hlsl shader with latest glslang. When I use the resulting spirv (human readable = [AuxGeomTextureVS.h_spv.txt](https://github.com/KhronosGroup/glslang/files/1833782/AuxGeomTextureVS.h_spv.txt) and binary = [AuxGeomTextureVS.spv.txt](https://github.com/KhronosGroup/glslang/files/1833783/AuxGeomTextureVS.spv.txt)) to create shader module in vulkan, it crashes in AMD driver binaries. 

My question is does this feature need to be supported by vendor drivers? Was this feature part of Vulkan 1.1? They have claimed that they are supporting Vulkan 1.1.

**Comment by johnkslang** [comment]
SPV_GOOGLE_hlsl_functionality1 was not part of Vulkan 1.1. It is quite new. You could ask AMD to support it.

But, to broadly help out and avoid all driver issues, SPIRV-Tools is adding strippers for this information (presumably after reflection tools have made use of it). Should be something like `--strip-reflect`, though that may be evolving? @dneto0 more to add?

**Comment by antiagainst** [comment]
Yes, spirv-opt has the support for `--strip-reflect` now: https://github.com/KhronosGroup/SPIRV-Tools/pull/1399.

Besides, if you don't want the complexity of SPIRV-Tools, writing a stand-alone function for doing the stripping is quite easy. I have an example here: https://github.com/antiagainst/spirv-reflect-stripper/blob/master/stripper.cpp

**Comment by Cry-Mory** [comment]
@johnkslang @antiagainst  Thanks for the replies. Stripping the reflections out is a better idea but anyway I will report it to AMD as well.
