### ISSUE TITLE
Control may reach end of non-void function

### ISSUE THREAD

**Issue by ehsannas** [KhronosGroup/glslang#1308]
Some bots compiling ndk-build are getting the following error.

```
../third_party/glslang/SPIRV/SpvBuilder.cpp:865:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
```
It is generated due to this little function here:
https://github.com/KhronosGroup/glslang/blob/master/SPIRV/SpvBuilder.cpp#L851-L865

**Comment by ehsannas** [comment]
cc @antiagainst @dneto0

**Comment by johnkslang** [comment]
I don't see that myself, but it seems pretty obvious what to do. I pushed a fix. If it doesn't work, reopen, but that seems pretty unlikely.
