### ISSUE TITLE
Invalid SPIR-V generated for spv.GeometryShaderPassthrough.geom

### ISSUE THREAD

**Issue by kayru** [KhronosGroup/glslang#1330]
Running `glslangValidator --auto-map-locations -V spv.GeometryShaderPassthrough.geom && spirv-dis geom.spv` produces the following output:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 4
; Bound: 15
; Schema: 0
               OpCapability Geometry
               OpCapability GeometryShaderPassthroughNV
               OpExtension "SPV_NV_geometry_shader_passthrough"
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Geometry %4 "main" %10 %14
               OpExecutionMode %4 Triangles
               OpExecutionMode %4 Invocations 1
error: 45: End of input reached while decoding OpExecutionMode starting at word 42: expected more operands after 3 words.
```
Tested using glslangValidator from latest public Vulkan SDK (1.1.70.1) and custom-built glslang (ed834895ea68aaa4a6d4975be17751a25899acde).

**Comment by kayru** [comment]
This validation error happens in other shaders that use passthrough extension. Despite it, they appear to actually work correctly. So perhaps this is just a validation issue?

**Comment by johnkslang** [comment]
@chaoc @dgkoch The problem here I see from code reading and the regression test in glslang is that 

```
ExecutionMode 4 OutputVertices <???>
```

The `<???>` should be the number of vertices, from `int vertices;` in localIntermediate.h, but it was never set.

I haven't thought through the extension yet, but is it ill defined to issue this instruction in pass-through mode or something? Maybe the two emissions of `ExecutionModeOutputVertices` need guarding, or maybe `vertices` needs a default value that is greater than 0, or ...?

**Comment by chaoc** [comment]
I agree it should be something more graceful. I believe the correct approach should be not having ExecutionMode 4 OutputVertices at all as this is not needed with pass through geometry shader(output = input).
In fact, the GL extension disallow it altogether:

> A compile- or link-time error will be generated if a program contains a
    passthrough geometry shader and: ....declares a geometry shader output primitive vertex count using the output layout qualifier "max_vertices";
 
 I'll go ahead and make a fix by not generating  ExecutionModeOutputVertices under the extension.

**Comment by dgkoch** [comment]
Actually, I had intended for the compiler front-end to figure out the OutputVertices 
See Issue 1 here: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_geometry_shader_passthrough

**Comment by johnkslang** [comment]
Okay, I will implement that right now.

**Comment by johnkslang** [comment]
Is `line_stripo` a typo @dgkoch?  (Issue in your link.)

**Comment by dgkoch** [comment]
Thanks @johnkslang. 
And yes, `line_stripo` is a typo in the Vulkan spec. I'll submit an MR for that.
