### ISSUE TITLE
Codegen with and without AMD_EXTENSIONS

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/glslang#1337]
Sanity check issue/question: Are there tests to confirm that the code generated using both code paths (with the AMD_EXTENSIONS define enabled and without) generate the same SPIR-V (obviously w/o using actual extensions)?

**Comment by johnkslang** [comment]
No, testing of multiple modes of compilation of glslang is not currently done.

We should see that things under if #ifdef are tied to features enabled by an extension. When I code read a vendor's contribution, it is one thing I look for. I agree that is not as good as testing.
