### ISSUE TITLE
[HLSL] Invalid SPIRV code generated if gl_FragData_0_ is used as output parameter.

### ISSUE THREAD

**Issue by bkaradzic** [KhronosGroup/glslang#1344]
With this code glslang will produce SPIR-V that will cause VK runtime to crash inside driver:

`./glslangValidator -D -e main -V test.frag`

```cpp
void main(out float4 gl_FragData_0_ : SV_TARGET0)
{
	gl_FragData_0_ = float4(1.0, 0.0, 0.0, 1.0);
}
```

This works:
```cpp
void main(out float4 xl_FragData_0_ : SV_TARGET0)
{
	xl_FragData_0_ = float4(1.0, 0.0, 0.0, 1.0);
}
```

**Comment by johnkslang** [comment]
The SPIR-V is identical, except for the spelling of the debug name.

No driver should care at all about any spelling of any debug name.

Have you submitted a defect against the driver?

**Comment by bkaradzic** [comment]
> Have you submitted a defect against the driver?

No.

I'll do more tests on Windows and find more info about it (I tested only on Linux with NV, but had similar issue on Windows with different GPUs).

**Comment by bkaradzic** [comment]
Ok tested it with multiple GPU/drivers, and it seems only NV issue (tested with 384.111, and 391.95).

**Comment by pdaniell-nv** [comment]
This issue should be fixed in our next driver release.
