### ISSUE TITLE
Allow *.<stage>.glsl in glslangvalidator input file names

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/glslang#1349]
Using .glsl as an extension is convenient for a couple of reasons:

1) You only have to configure a single extension to be recognized as GLSL by your tools (i.e. syntax highlighting in text editor).

2) .glsl can be used for "header"-style files (i.e. files that are valid GLSL but are only meant to be included from other shaders) without any confusion.

OTOH, having the shader stage in the extension is also very convenient for tools (and humans), given that GLSL doesn't provide any explicit way of specifying the stage on a language level.

It is proposed to make glslangvalidator recognize a double extension in file names, which would contain both the stage AND end in .glsl.

Thus, the recognized extensions would expand to include:

.vert.glsl - for vertex shaders
.tesc.glsl - for tessellation control shaders
.tese.glsl - for tessellation evaluation shaders
.geom.glsl - for geometry shaders
.frag.glsl - for fragment shaders
.comp.glsl - for compute shaders

**Comment by johnkslang** [comment]
Glslang does support whatever convention you want, with  `-S`, in case that changes anything here.

Otherwise, it would be good to have some consensus this is the new naming convention we'd want for automatic deduction of stage.

**Comment by nicebyte** [comment]
> Glslang does support whatever convention you want, with -S, in case that changes anything here.

Yep, I'm familiar with it. It works for manual invocation, but is a bit awkward for automation. Imagine a situation  when you want to a script to invoke the validator on a file. You have two options:

- Just rename your files to use the current convention
- Write code in your tool to determine the stage name out of the filename, and pass that with `-S` to the validator

I think both of those options are not ideal. While the ".<stage>.glsl" convention streamlines that aspect of automation.

**Comment by warp-10** [comment]
Yes, this is much needed. Instead of having to glob for 6 different extensions, just glob for one.

**Comment by nicebyte** [comment]
The PR that implements this has been merged (thanks John!), so I am closing this issue.

**Comment by johnkslang** [comment]
BTW, I also made it do "-D" by default if sees a .hlsl suffix.
