### ISSUE TITLE
GLSLang generating incorrect OpUConvert

### ISSUE THREAD

**Issue by nicokoch** [KhronosGroup/glslang#1360]
As I understand the spec, the OpUConvert and OpSConvert are meant to cast the bitwidth of an integer (for unsigned and signed ints correspondingly).

I have found a case where GLSLang uses OpUConvert to create a signed integer, which is wrong IMO.

Input:
```glsl
#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_ARB_gpu_shader_int64 : enable

layout (location = 0) out int outVal;

void main()
{
    uint64_t temp = 100000;
    outVal = int(temp);
}
```

Output:
```spirv
; SPIR-V
; Version: 1.2
; Generator: glslang
; Bound: 16
OpCapability Shader
OpCapability Int64
%1 = OpExtInstImport "GLSL.std.450"
OpMemoryModel Logical GLSL450
OpEntryPoint Vertex %4 "main" %12
OpSource GLSL 450
OpSourceExtension "GL_ARB_gpu_shader_int64"
OpSourceExtension "GL_ARB_separate_shader_objects"
OpSourceExtension "GL_ARB_shading_language_420pack"
OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
OpSourceExtension "GL_GOOGLE_include_directive"
OpName %4 "main"
OpName %8 "temp"
OpName %12 "outVal"
OpDecorate %12 Location 0
%2 = OpTypeVoid
%3 = OpTypeFunction %2
%6 = OpTypeInt 64 0
%7 = OpTypePointer Function %6
%9 = OpConstant  %6  100000
%10 = OpTypeInt 32 1
%11 = OpTypePointer Output %10
%12 = OpVariable  %11  Output
%4 = OpFunction  %2  None %3
%5 = OpLabel
%8 = OpVariable  %7  Function
OpStore %8 %9
%13 = OpLoad  %6  %8
%14 = OpUConvert  %10  %13
%15 = OpBitcast  %10  %14
OpStore %12 %15
OpReturn
OpFunctionEnd
```

The problematic line is this one: `%14 = OpUConvert  %10  %13`. %13 is a unsigned integer, but %10 is a signed integer type. IMO, the `OpBitcast` must happen before the `OpUConvert`.

The spec for OpUConvert also states: `Result Type must be a scalar of integer type, whose Signedness operand is 0.` This is clearly not the case here.

I have previously found other cases where GLSLang passes in a signed value into `Unsigned Value`, which also shouldn't happen.

**Comment by johnkslang** [comment]
@alegal-arm may be interested in this.

**Comment by johnkslang** [comment]
It looks like a conversion that changes both signedness and width uses OpUConvert to try to do both at the same time.  OpUConvert needs to change the width, while leaving signedness the same.

**Comment by johnkslang** [comment]
@alegal-arm it actually was two steps, a width conversion and a bitcast, but the intermediate type (of the width conversion) was sometimes incorrectly selected.  I change to a simpler method of doing it.
