### ISSUE TITLE
Wrong Uniform Buffer offsets from optimised block

### ISSUE THREAD

**Issue by mattparks** [KhronosGroup/glslang#1361]
Normally when calling `getUniformBufferOffset` for a uniform that is part of a uniform block, the offset is returned correctly. I will use this block as an example as to when it appears incorrect.

```glsl
layout(set = 0, binding = 0) uniform UboScene
{
	mat4 projectionView;
	vec3 cameraPosition;
} scene;
```

When both uniforms inside of the block are used in the shader program both are recognized in the reflection, and `getUniformBufferOffset` returns offsets for both uniforms correctly. However, when projectionView is not used in the shader program I have seen it is not reported in the uniform reflection (that is fine, I expect unused uniforms and attributes not to be reported). However the buffer offsets are still the same for cameraPosition, leading its size to include projectionView in my program.
Shorted this means even when a unused uniform is removed by glslang the offset for that object is still added to other uniforms, this might be intentional, but a api call that gets a real size ofva uniform contained in a block would be nice.

**Comment by johnkslang** [comment]
I don't think we want the layout to be optimization dependent.

That is, it is correct and intentional that the offset of cameraPosition does not change.

Is this a request for a new query that does not yet exist? Or, something that can be done by getting the TType and asking it how big it is?

**Comment by mattparks** [comment]
```

**Comment by mattparks** [comment]
`TIntermediate::getBaseAlignment` works exactly the same as what I described above with `sizeof(float) * program.getUniformTType(i)->computeNumComponents()`, it computes size perfectly for everything up until what I describe next.

```glsl
struct Light
{
	vec4 colour;
	vec3 position;
	float radius;
}

layout(set = 0, binding = 0) uniform UboScene
{
	Light lights[64];
	mat4 projection;
} scene;
```

I am finding the uniform offset with `program.getUniformBufferOffset(i)`, and uniform size is found with `sizeof(float) * program.getUniformTType(i)->computeNumComponents()`:
```
Uniform Blocks:
  - UniformBlock(name 'UboScene', binding 0, size 2112)
    - Uniform(name 'lights', binding -1, offset 0, size 16, glType 35666)
    - Uniform(name 'projection', binding -1, offset 2048, size 64, glType 35676)
```

I would be expecting a size of 2048 for lights, but 16 has been given.

**Comment by johnkslang** [comment]
I see an offset for `projection` of 2048, so something is figuring out the right size for `lights`.

`getBaseAlignment` does not work by calling `computeNumComponents`.

I don't think `computeNumComponents` will give correct layout information, though it would multiply by array size, so I suspect an answer of 16 means the wrong type was used to query it.
