### ISSUE TITLE
Build fails with Visual Studio 2012

### ISSUE THREAD

**Issue by rvkennedy** [KhronosGroup/glslang#137]
As of 20/1/2016, using the Visual Studio 2012 (xp toolset), SpvBuilder fails - this may be due to unsupported C++11 or C++14 features:

    glslang\SPIRV\SpvBuilder.cpp(1807): error C2143: syntax error : missing ')' before '{'         [glslang\build\x64\SPIRV\SPIRV.vcxproj]
    glslang\SPIRV\SpvBuilder.cpp(1807): error C2661: 'std::stack<_Ty>::push' : no overloaded function takes 0 arguments [glslang\build\x64\SPIRV\SPIRV.vcxproj]
    glslang\SPIRV\SpvBuilder.cpp(1807): error C2143: syntax error : missing ';' before '{' [glslang\build\x64\SPIRV\SPIRV.vcxproj]
    glslang\SPIRV\SpvBuilder.cpp(1807): error C2143: syntax error : missing ';' before '}' [glslang\build\x64\SPIRV\SPIRV.vcxproj]
    glslang\SPIRV\SpvBuilder.cpp(1807): error C2059: syntax error : ')' [glslang\build\x64\SPIRV\SPIRV.vcxproj]

**Comment by baldurk** [comment]
I guess this ties into issue #42 which wasn't explicitly resolved but seems to be trending towards fairly modern VS2013 or VS2015 depending on how much C++11 is used. For what it's worth I'm maintaining a branch [here](https://github.com/baldurk/glslang/tree/vs2010) that compiles on VS2010 if you want to cherry pick things to compile locally. At least for now the diff is pretty small.

**Comment by rvkennedy** [comment]
Thanks, I'll switch over to your branch for now, it's preferable to falling behind on glslang at this point. The failing line (1807) is:

    loops.push({makeNewBlock(), makeNewBlock(), makeNewBlock(), makeNewBlock()});

which is a using an brace-enclose initializer list. This issue might also be relevant: http://stackoverflow.com/questions/4299439/c11-vector-push-back-ambiguous

I was  surprised to learn that this brace initialization was a C++11 feature, as VS2012's C++11 support seemed pretty solid. But https://msdn.microsoft.com/en-us/library/hh567368.aspx shows that you need to go to VS2015 to get really comprehensive 11 support, and many 14 features are missing.

**Comment by Marqin** [comment]
^ ignore that in this issue, accidentally put wrong ID in commit
