### ISSUE TITLE
16 bit SSBO access emits 'OpCapability StorageUniform16'

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/glslang#1374]
Same test case as with issue #1373:
```
#version 450
#extension GL_KHX_shader_explicit_arithmetic_types : enable

layout(std430, binding = 3) buffer layoutName
{
	uint16_t ssbo[];
};

void main() 
{
	uint16_t test = ssbo[ 0 ];
}
```

This creates SPIR-V with both OpCapability StorageBuffer16BitAccess & StorageUniform16. I believe  StorageUniform16 should only be required if reads are from a UBO?

**Comment by johnkslang** [comment]
I see these capabilities declared:

```
 Shader
 Int16
 StorageUniformBufferBlock16
 StorageUniform16
```

I assume you mean you only want to see StorageUniformBufferBlock16, and not see StorageUniform16?

**Comment by Novum** [comment]
Correct. Thank you.
