### ISSUE TITLE
HLSL: Missing OpExtension when using SV_RenderTargetArrayIndex in vertex shader

### ISSUE THREAD

**Issue by awefers** [KhronosGroup/glslang#1377]
Hi,

I am using SV_RenderTargetArrayIndex in a HLSL vertex shader which translates in SPIRV to "BuiltIn Layer". I noticed the following validation warning after upgrading from Vulkan SDK 1.0.68 to 1.1.73:

SPIR-V module not valid: Vulkan spec allows BuiltIn Layer to be used only with Fragment or Geometry execution models. ID <0> (OpStore) is referencing ID <92> (OpVariable) which is decorated with BuiltIn Layer in function <4> called with execution model Vertex.

In order to be able to use "BuiltIn Layer" in a vertex shader, either the extension "VK_EXT_shader_viewport_index_layer" or "VK_NV_viewport_array2" need to be enabled. I have enabled those extensions in VkDeviceCreateInfo (and the layered rendering works as expected). However, I noticed that the SPIRV byte code does not include the OpExtension for any of those two extensions, hence the validation warning.

Axel

**Comment by antiagainst** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/issues/1563 is merged now.

**Comment by awefers** [comment]
I double checked with the latest version of glslang and it generates:

OpCapability Shader
OpCapability Geometry
OpCapability ShaderViewportIndexLayerEXT
OpExtension "SPV_EXT_shader_viewport_index_layer"

The extension is set correctly and the validation fix does resolve the issue.
