### ISSUE TITLE
Questions about glsl4.60.5 specs

### ISSUE THREAD

**Issue by brupelo** [KhronosGroup/glslang#1390]
@johnkslang John, hello, nice to meet you. Sorry to ping you here but I've seen you're one of the main authors of [https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf). Hope you don't mind if I ask you some questions regarding that document here, I didn't know where to ask about this tbh.

Thing is, I'm in the middle of the process of creating a python glsl parser out of this document and I've got some questions about the grammar.

Pages (197-199) give a list of tokens used by the EBNF grammar (pages 199-210). I assume mostly of the tokens are just uppercase version of the glsl keywords (1:1 correspondence). So leaving that big set aside I'm trying to figure out the rest of the token set, for instance:

    'ADD_ASSIGN':       '+='
    'AMPERSAND':        '&'
    'AND_ASSIGN':       '&&='
    'AND_OP':           '&&'
    'BANG':             '!'
    'BOOLCONSTANT':     'const bool'
    'CARET':            '^'
    'COLON':            ':'
    'COMMA':            ','
    'DASH':             '-'
    'DEC_OP':           '--'
    'DIV_ASSIGN':       '/='
    'DOT':              '.'
    'DOUBLECONSTANT':   'const double'
    'EQ_OP':            '='
    'EQUAL':            '=='
    'FIELD_SELECTION':  'UNKNOWN'
    'FLOATCONSTANT':    'const float'
    'GE_OP':            'UNKNOWN'
    'HIGH_PRECISION':   'highp'
    'IDENTIFIER':       'UNKNOWN'
    'INC_OP':           '++'
    'INTCONSTANT':      'const int'
    'LE_OP':            'UNKNOWN'
    'LEFT_ANGLE':       '<'
    'LEFT_ASSIGN':      'UNKNOWN'
    'LEFT_BRACE':       '{'
    'LEFT_BRACKET':     '['
    'LEFT_OP':          'UNKNOWN'
    'LEFT_PAREN':       '('
    'LOW_PRECISION':    'lowp'
    'MEDIUM_PRECISION': 'mediump'
    'MOD_ASSIGN':       '%='
    'MUL_ASSIGN':       '*='
    'NE_OP':            'UNKNOWN'
    'OR_ASSIGN':        '||='
    'OR_OP':            '||'
    'PERCENT':          '%'
    'PLUS':             '+'
    'QUESTION':         '?'
    'RIGHT_ANGLE':      '>'
    'RIGHT_ASSIGN':     'UNKNOWN'
    'RIGHT_BRACE':      '}'
    'RIGHT_BRACKET':    ']'
    'RIGHT_OP':         'UNKNOWN'
    'RIGHT_PAREN':      ')'
    'SEMICOLON':        ';'
    'SLASH':            '/'
    'STAR':             '*'
    'SUB_ASSIGN':       '-='
    'TILDE':            '~'
    'TYPE_NAME':        'UNKNOWN'
    'UINTCONSTANT':     'const uint'
    'VERTICAL_BAR':     'UNKNOWN'
    'XOR_ASSIGN':       '^='
    'XOR_OP':           '^'

Could you please review that set and confirm me the pairs are correct? Also, as you can see there are pairs where I've set the value 'UNKNOWN' and that's mainly because I didn't know the meaning of the token in that particular case.

What I don't understand is why you guys didn't wrote about token/terminals in the document. I mean, you write a little bit about it on chapter 3.5 but is still confusing deducing the meaning of a particular token just by reading its name. Right now, writing a parser using the {tokens, EBNF} is proving to be quite tricky :/

Thanks in advance.
Bruno

**Comment by johnkslang** [comment]
BOOLCONSTANT:  like `true` or `false`, the value itself is side data, same for all the following
    DOUBLECONSTANT: like `3.92e+2lf`
    FIELD_SELECTION: like `structure.member`
    FLOATCONSTANT: like `3.14159`
    IDENTIFIER: a name, a variable, etc., in the source code, like `i` or `foo`
    INTCONSTANT: like `42`
    TYPE_NAME: like the second `S` in  `struct S {...}; S foo;`
    UINTCONSTANT: like `42u`

**Comment by brupelo** [comment]
@johnkslang Cool, at this point has become clear to me how the whole set of tokens looks like, btw, what'd be the start rule of the grammar? Asking you cos the python library I'll be using needs to specify a start rule to load the EBNF grammar properly.

Anyway, you can close the ticket after this, at this point my question has been solved ;)

Tyvm.

**Comment by johnkslang** [comment]
This is the start rule:

```
%start translation_unit
...
translation_unit
    : external_declaration
    | translation_unit external_declaration
```
