### ISSUE TITLE
Support for more file extensions in the standalone wrapper

### ISSUE THREAD

**Issue by Strum355** [KhronosGroup/glslang#1392]
Currently, only `.frag` is supported for fragment shaders and `.vert` for vertex shaders in the standalone wrapper. Would it be possible to get other extensions supported such as `.fsh` and `.vsh`? This would save me having to make links for a linter

**Comment by johnkslang** [comment]
Does it help that you can specify stage on the command line?

`glslangValidator -S frag name.fsh`

**Comment by Strum355** [comment]
I'll close this issue as technically the original issue has been resolved.
