### ISSUE TITLE
Implement Language Server Protocol

### ISSUE THREAD

**Issue by PoignardAzur** [KhronosGroup/glslang#1398]
The [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) is a json-based protocol meant to facilitate implementation of languages within multiple IDEs. The idea is that any LSP-compatible IDE can run a process and give diagnostics and other semantic information for any LSP-compatible language.

With that in mind, it would be nice if glslang had a command line option that made it run in LSP mode. Right now I'm developing a plugin for running GLSL diagnostics on Atom and I'm using https://github.com/svenstaro/glsl-language-server as the LSP client, and it works; but it's not the reference GLSL front-end.

**Comment by johnkslang** [comment]
Sounds nice to have.

**Comment by jozefkucia** [comment]
For what i's worth, https://github.com/svenstaro/glsl-language-server appears to use glslang.

**Comment by johnkslang** [comment]
I will leave it up to others to push anything into the glslang project, or not.

**Comment by Trass3r** [comment]
Looks like that project never made it far and is abandoned.
Does anyone know of any other attempts?
