### ISSUE TITLE
[GLSL] 'mod' ambigous signature.

### ISSUE THREAD

**Issue by Duttenheim** [KhronosGroup/glslang#140]
Using the glslang compiler as a validator in an intermediate compiler, getting this error:

**'mod' : ambiguous function signature match: multiple signatures match under implicit type conversion**

From this code:
```c
uint
ConvertFrom2D(uvec2 coord, uint maxX, uint maxY)
{
	return uint(mod(coord.x, maxX) + uint(coord.y / maxY));
}
```

I've also tried this code:
```c
uint
ConvertFrom2D(uvec2 coord, uint maxX, uint maxY)
{
	const uint x = coord.x;
	const uint y = coord.y;
	return uint(mod(x, maxX) + uint(y / maxY));
}
```

But got the same results.

**Comment by johnkslang** [comment]
mod() operates on floating-point types, and both these exist:

   uint -> float
   uint -> double

So, it's ambiguous.

Do you want % instead?  It works on integer types.

**Comment by johnkslang** [comment]
Another point here is something missing is the (from Todo.txt, which needs updated):

- second-generation function-overloading disambiguation algorithm (version 400)

It's possible that would effect this.  I don't know if you're just testing corner cases, or you really want "%" functionality.

**Comment by johnkslang** [comment]
This is now captured by issue #142.

**Comment by Duttenheim** [comment]
Thanks for your help! I think % will solve my issue.

I have a shader library which compiles on hardware, although I do believe it does so because the hardware compilers automatically performs dead code elimination. I'd rather use the reference compiler to validate instead of creating a GL context everytime I perform GLSL code validation.

I got a similar problem when doing using min, with the same error: 
**'min' : ambiguous function signature match: multiple signatures match under implicit type conversion**

```c
void
ShaderMain()
{
	imageStore(tex, ivec2(gl_GlobalInvocationID.xy), vec4(min(gl_LocalInvocationID.x, 255)));
}
```

I assume here because min takes int, int or uint, uint, and it's ambiguous because you can either convert the integer literal to a unsigned, or gl_LocalInvocationID.x to an integer?

To be fair, none of these problems isn't an error on the compilers behalf at all. I just assumed that if it compiled on hardware it would do so with the reference compiler, but I believe being as strict as possible is the best option. 

Thanks for your help!

**Comment by johnkslang** [comment]
Okay, this is now covered by issue #142, closing.
