### ISSUE TITLE
parsing doubles fails for e11 on OSX

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1400]
The test for parsing of floating pointer numbers is failing on OSX.  It looks like the result rounds down to zero.  I don't know if the same problem occurs on Linux.

Here's the relevant part of glslang-gtest output:

```
With diff:
@@ -109,5 +109,5 @@
 0:26          'e11' ( temp double)
 0:26          Constant:
-0:26            9.8813129168249e-324
+0:26            0.000000
 0:27      Sequence
 0:27        move second child to first child ( temp double)
@@ -562,5 +562,5 @@
 0:26          'e11' ( temp double)
 0:26          Constant:
-0:26            9.8813129168249e-324
+0:26            0.000000
 0:27      Sequence
 0:27        move second child to first child ( temp double)

[  FAILED  ] Glsl/CompileToAstTest.FromFile/stringToDouble_vert, where GetParam() = "stringToDouble.vert" (12 ms)
```

**Comment by johnkslang** [comment]
These all get the same results on Travis CI though, which includes OSX?

**Comment by johnkslang** [comment]
BTW, this test is tweaked to find a portable set of numbers. If we have to tweak it to make it more portable, we can. Likely, by remove the number, or finding a slightly bigger one that works.

BTW, this could be a denorm issue.  Normalized numbers only go down to around E-309.

Fundamentally, this space is not portable. The library calls do not have standardized results.

**Comment by dneto0** [comment]
> These all get the same results on Travis CI though, which includes OSX?

Good point.  I dug up additional info.


I'm using an  Intel Core i7 on OSX 10.13.4, compiler version as follows:

My CMakeCache says it is using this compiler:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


The Travis-CI OSX log says:  

-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works

So I guess there is a non-portability between the compiler versions or more likely their libraries.

**Comment by johnkslang** [comment]
I am basically okay with the fix and fixing it, but I find it mildly disturbing that they stopped supporting denorms.  The breadth of denorm support was pretty wide.
