### ISSUE TITLE
 'non-constant initializer' : not supported with this profile: es

### ISSUE THREAD

**Issue by nstavropoulos** [KhronosGroup/glslang#1404]
```
#version 100
#ifdef GL_ES
precision mediump float;
#endif
struct s {
    float f;
    vec3 v;
};

void main()
{
    const vec4 v = (vec4(1,2,3,4), vec4(5,6,7,8));  // 5,6,7,8
    const s s1 = (s(9.0, vec3(10,11,12)), s(13.0, vec3(14,15,16))); // 13,14,15,16
    gl_FragColor = v + vec4(s1.f, s1.v);  // 18, 20, 22, 24
}

```

The above code although it was compiling successfully with commit 198652a6d4ebbc1d6010faf2cdac7a7871fedddc, after commit 461ea09943e0e88ea854ab9e3b42d17d728af2ad (maybe the related code is in a previous commit ) returns error 

" 'non-constant initializer' : not supported with this profile: es"

As far as I understand the rvalues of s1 and v are constants although they seem complex, thus I would expect that it should compile.

**Comment by johnkslang** [comment]
Comma operations do not qualify as constants.

See section 4.3.3 "Constant Expressions:"

> ... the sequence operator ( , ) and the assignment operators ( =, +=, ...) are not included in the
operators that can create a constant expression.

**Comment by nstavropoulos** [comment]
thanks a lot for the knowledge
