### ISSUE TITLE
Wrong SPIRV generation when we have multiple unsized arrays in a block

### ISSUE THREAD

**Issue by hikiko** [KhronosGroup/glslang#1406]
An SSBO can only contain one unsized array at the end of the block. Therefore, the following shader should generate a compile error, but it doesn't:

```
buffer a {
	vec4 k[];
	vec4 s[];
	vec4 a[];
} b;

in vec4 piglit_vertex;
out vec4 c;

void main(void) {
	c = b.a[0];
}
```

In the generated SPIR-V code only the last unsized array has type OpTypeRuntimeArray. The rest seem to be simple arrays of size 1. I think that in this case the compiler should not be able to calculate the arrays size (there's no way to calculate it and find it 1) and it should generate an error instead.

```
%_arr_v4float_uint_1 = OpTypeArray %v4float %uint_1
%_arr_v4float_uint_1_0 = OpTypeArray %v4float %uint_1
%_runtimearr_v4float = OpTypeRuntimeArray %v4float
```

**Comment by johnkslang** [comment]
For desktop, unsized arrays are generally auto-deduced in their size.

It is only when it is the last one in the SSBO that it defaults to being run-time sized rather than being compile-time sized.

The default size for a compile-time sized array is 1.

**Comment by hikiko** [comment]
You are right.

This part of the GLSLang Spec (4.60, section 4.2 Scoping) clarifies this:

> An array implicitly sized in one shader can be explicitly sized by another shader in the same stage. If no shader in a stage has an explicit size for the array, the largest implicit size (one more than the largest index used) in that stage is used. There is no cross-stage array sizing. If there is no static access to an implicitly sized array within the stage declaring it, then the array is given a size of 1, which is relevant when the array is declared within an interface block that is shared with other stages or the application (other unused arrays might be eliminated by the optimizer).

There's a piglit test that checks if a linker error is generated in the case above that confused me (bug).

I think that we could safely close this issue, sorry for the noise. :)
