### ISSUE TITLE
SPVRemapper does not handle OpConstantNull

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#1408]
SPVRemapper.cpp gives the error "unimplemented constant type" for OpConstantNull:

https://github.com/KhronosGroup/glslang/blob/bea08fe02ac5715efe77ce1e559c0c3a208863ab/SPIRV/SPVRemapper.cpp#L223

Our compile pipeline halts when SPVRemapper calls the error callback so this issue is blocking me with one of our latest shaders.  

Is there something SPVRemapper needs to do special to handle OpConstantNull?

**Comment by greg-lunarg** [comment]
I will take a look.

**Comment by greg-lunarg** [comment]
It looks like we are using isConstOp to guard logic assuming OpConstantNull will not be seen. I will look to add additional logic to handle it.

**Comment by danginsburg** [comment]
The attached SPIR-V reproduces the issue.

[test_309.zip](https://github.com/KhronosGroup/glslang/files/2116036/test_309.zip)

**Comment by greg-lunarg** [comment]
I threw in OpConstantSampler while I was in the neighborhood.
