### ISSUE TITLE
Cannot build glslang with Visual Studio 2015

### ISSUE THREAD

**Issue by adamhusar** [KhronosGroup/glslang#1410]
With latest master (commit 5fe506a8ba0ce5629004d593da16db7f3f57c58b), it is not possible to build glslang with Visual Studio compiler (Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86):

```
cmake ..\ -DCMAKE_INSTALL_PREFIX="$(pwd)/install"
cmake --build . --config Debug --target install
```

Build reports this error:

```
(ClCompile target) ->
  E:\src\glslang\glslang\glslang\MachineIndependent\Constant.cpp(333): error C2440: 'type cast': cannot convert from 'glslang::TConstUnion' to 'bool' [E:\src\glslang\glslang\build\glslang\glslang.vcxproj]
  E:\src\glslang\glslang\glslang\MachineIndependent\Constant.cpp(339): error C2440: 'type cast': cannot convert from 'glslang::TConstUnion' to 'bool' [E:\src\glslang\glslang\build\glslang\glslang.vcxproj]
```

This issue is there for almost a month.

It is related to these parts of code:

```
    case EOpLogicalAnd: // this code is written for possible future use, will not get executed currently
        for (int i = 0; i < newComps; i++)
            newConstArray[i] = leftUnionArray[i] && rightUnionArray[i];
        break;

    case EOpLogicalOr: // this code is written for possible future use, will not get executed currently
        for (int i = 0; i < newComps; i++)
            newConstArray[i] = leftUnionArray[i] || rightUnionArray[i];
        break;
```

**Comment by johnkslang** [comment]
There is `operator&&(...)` and `operator||(...)` to handle this, without type cast, so I don't yet understand what is happening.

Also, I am confused that the error messages are 6 lines apart, when the stride of the code is 5 lines: Is it possible you have modified the code?

**Comment by adamhusar** [comment]
This is interesting, with the current latest commit 0b964b3c35774ba4f93711d520a31d01350a626c, I am able to build gslang without problems, although the diff between the commit 5fe506a and this one does not show any relevant changes. 
So, I am closing this issue.  Thanks
