### ISSUE TITLE
[4.0] Implement version 400 function-overloading disambiguation algorithm

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#142]
Currently, only the pre-version 400 function-overloading algorithm is present.  Version 400 and above should be using the second-generation algorithm.

**Comment by johnkslang** [comment]
FYI, this is specified in section 6.1 of GLSL as the following, and I know it is possible to implement this as a two-pass linear algorithm across the set of choices.

> When function calls are resolved, an exact type match for all the arguments is sought. If an exact match is found, all other functions are ignored, and the exact match is used. If no exact match is found, then the implicit conversions in section 4.1.10 “Implicit Conversions” will be applied to find a match. Mismatched types on input parameters (in or inout or default) must have a conversion from the calling
argument type to the formal parameter type. Mismatched types on output parameters (out or inout) must have a conversion from the formal parameter type to the calling argument type.
>
> If implicit conversions can be used to find more than one matching function, a single best-matching
function is sought. To determine a best match, the conversions between calling argument and formal
parameter types are compared for each function argument and pair of matching functions. After these
comparisons are performed, each pair of matching functions are compared. A function declaration A is
considered a better match than function declaration B if
>
> - for at least one function argument, the conversion for that argument in A is better than the
corresponding conversion in B; and
> - there is no function argument for which the conversion in B is better than the corresponding
conversion in A.
>
> If a single function declaration is considered a better match than every other matching function
declaration, it will be used. Otherwise, a compile-time semantic error for an ambiguous overloaded
function call occurs.
>
> To determine whether the conversion for a single argument in one match is better than that for another match, the following rules are applied, in order:
>
> 1. An exact match is better than a match involving any implicit conversion.
> 2. A match involving an implicit conversion from float to double is better than a match involving any other implicit conversion.
> 3. A match involving an implicit conversion from either int or uint to float is better than a match involving an implicit conversion from either int or uint to double.
>
> If none of the rules above apply to a particular pair of conversions, neither conversion is considered better than the other.

**Comment by johnkslang** [comment]
Here is a high-level design for a generic selector, which I believe can be used by both GLSL and HLSL, and probably other more C++-like languages too.

## Generic Selector

This would live in place usable by multiple languages, e.g. `ParseContextBase`, or just on it's own, taking a parse context or symbol table as needed to operate.

### Assumptions

- There is no exact match, so a selection algorithm needs to run.  This is not inside, so a language-specific parser can first look up exact match and then decide what to do in its absence.

### Input

- calling name
- list of calling argument types, and whether they are **in**, **out**, or both
- a predicate function `convertible(A, B)` that says whether or not type A can implicitly convert to type B (it includes the case of what the calling language would consider a matching type with no conversion needed)
- a predicate function `better(A, B1, B2)` that says whether or not a conversion from A -> B2 is considered better than a conversion from A -> B2 

### Output

- best match
- whether there was a tie for the best match (ambiguous overload selection)

### Operation

1. Get the set of signatures having the same function name.
1. Prune this set down to candidates under conversion, where each candidate has
   - the right number of non-optional arguments
   - each argument is true under `convertable(A, B)`, where `A` is the calling type for **in** and `B` is the formal type, and in addition, for **out** `B` is the calling type and `A` is the formal type
1. If there is only one candidate, return it as the best, with no tie
1. Select the first candidate as the "best", and then compare it to the next candidate.  If the next (new) candidate is better, update "best" to be that one. Repeat, with a linear walk through the full list. A new candidate becomes better than the current best if
   - it has a function argument with a `better(...)` conversion than the current best, for all directions needed by **in** and **out**
   - the current best has no argument with a `better(...)` conversion, for either **in** or **out**, than the new candidate
1. Check for ambiguity by comparing the best candidate from the previous step against each other candidate.  If any other candidate has a function argument with a `better(...)` conversion than the best candidate (for either **in** or **out** directions), return with a tie for best.

**Comment by dankbaker** [comment]
I think this will work for HLSL, I suspect the right thing to do will be take the function which has the minimum best of each individual argument rather then the sum of them, but that's just a guess.

I think it's fine for SVSL (Spir-V Shading Language) to issue an ambiguous error in cases where HLSL would have picked one. It's pretty easy to add some explicit casts to fix those cases, and it's probably whacky code anyway.

**Comment by johnkslang** [comment]
@dneto0 Have any (or know where to get some) input on how well this generalizes to C++ rules?

**Comment by dneto0** [comment]
I haven't worked on a C++ front end, but a good reference would be
http://en.cppreference.com/w/cpp/language/overload_resolution

See the section "Best viable function", especially paragraph 2 beginning with "F1 is determined to be a better funtion than F2...".  That rule looks very similar in spirit to the GLSL rules stated above, by checking for one *better* argument and no argument being worse.   So at first blush your algorithm looks like a good framework.

The next place I'd look after that is the C++ standard itself.

**Comment by johnkslang** [comment]
Thanks @dneto0, I analyzed/compared with this result:

- it is the same, once subsetted to what exists in the shading languages
- they call "viable candidate" what I called "candidate", I updated to match this terminology
- for the `better` predicate, got the generalization that conversion can be looked at as multiple steps (e.g., in HLSL, int -> double4 is conversion+promotion+smear) and then a shorter such chain beats a longer chain

Generally, for all languages `better` works as
  * basic-type promotion is better than basic-type conversion
  * shorter chains of promotion/conversion beat longer chains (it's only HLSL though that includes shape changing in the chain)

**Comment by johnkslang** [comment]
> it is the same

Actually, I should say my algorithm would get the correct result for C++, as neither C++ nor GLSL are giving an algorithm, but rather a description of what is correct.  The descriptions are *O(V^2)*, for *V* being number of viable candidates, whereas the algorithm I'm proposing is *O(C)*, for *C* being number of candidates.

**Comment by johnkslang** [comment]
This is implemented for the generic selector and the GLSL #version 400 predicates in https://github.com/KhronosGroup/glslang/tree/overloaded-400 (last commit there) if anyone wants to check it out or comment.  Will pull into master in a few days.

**Comment by johnkslang** [comment]
This is completed with commit fcc0aa3b647f0943cc9d29e1426b968526e94001.
