### ISSUE TITLE
HLSL: CalculateLevelOfDetailUnclamped is unimplemented

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/glslang#1423]
Hi,

currently CalculateLevelOfDetailUnclamped is unimplemented, as it supposedly is not optianable in GLSL/Spir-V. This is not true, textureQueryLod returns a vector of two, the first corresponds to CalculateLevelOfDetail the second to CalculateLevelOfDetailUnclamped. The HLSL method namings are a bit odd but it just means that it does use the range of the base texture as the second result of textureQueryLod would be.
Proof can be found here https://docs.microsoft.com/de-de/windows/desktop/direct3dhlsl/lod--sm4-1---asm-
which is the asm implementation of the HLSL construct.

**Comment by johnkslang** [comment]
Yes, it looks trivial to get that second component, which begs the question why it was not done.

Is it possible it is not biased correctly?  Vulkan has `mipLodBias` : 

> `mipLodBias` is the bias to be added to mipmap LOD (level-of-detail) calculation and bias provided by image sampling functions in SPIR-V, as described in the Level-of-Detail Operation section

**Comment by TiemoJung** [comment]
The documentation of **OpImageQueryLod** states:

> Result Type must be a two-component floating-point type vector.
> The first component of the result will contain the mipmap array layer.
> The second component of the result will contain the implicit level of detail relative to the base level.

So i would guess there is no bias applied to the second component.

**Comment by johnkslang** [comment]
I was looking for a cross check that DX and Vulkan agreed on the semantics. It seems they very likely do; it just also seemed the original author thought something was non trivial, so was trying to guess what that was.

But, if we have confidence on agreement of semantics, I will fix it for that.
