### ISSUE TITLE
HLSL: precise keyword has to propagate to all involved computations

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1425]
Given this shader:

```
cbuffer myObject
{       
    float4x4 wvp;
}
 

struct Vertex
{
    float3 pos : POSITION;
};

struct Interp
{
    precise float4 pos : SV_Position;
};

Interp main(Vertex input) 
{
    Interp r;
    float3 foo = sin(input.pos);
    r.pos = mul(float4(foo, 1), wvp);
	return r;
}
```

glslang emits NoContraction decoration for the matrix multiplication, but not for the sin. fxc and DXC (when targeting DXIL) propagate precise all the way into all expressions that are required to compute the output in this case.

**Comment by johnkslang** [comment]
What is the value of decorating sin() with NoContraction?  What would happen differently?

**Comment by zeux** [comment]
I was testing whether longer computation chains work correctly, and happened to use sin. Further testing tells me they actually do work - if input to matrix multiplication is a mul+add or another multiplication, glslang does insert NoContraction. Since I don't actually care about sin I'll close this :)

I'm not 100% sure about the correct semantics for sin here - in theory, driver compiler can compile sin to an arbitrary set of instructions with an arbitrary precision depending on the shader; I'm not sure if NoContraction prevents that, or if the correct thing to emit here is Invariant. Regardless, NoContraction seems to be sufficient for the practical uses I need.
