### ISSUE TITLE
GroupNonUniformBroadcast vs OpGroupBroadcast

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/glslang#1426]
This example:

```
#version 460
#extension GL_KHR_shader_subgroup_ballot: enable

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main(){
    int global_index_b = subgroupBroadcast(42, 0);
}
```

with `>glslangValidator.exe -V110 -H --target-env vulkan1.1 .\subgroup.comp` produces:

<pre>
// Module Version 10300
// Generated by (magic number): 80007
// Id's are bound by 18

                              Capability Shader
                              Capability GroupNonUniform
                              Capability GroupNonUniformBallot
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main"
                              ExecutionMode 4 LocalSize 128 1 1
                              Source GLSL 460
                              SourceExtension  "GL_KHR_shader_subgroup_ballot"
                              SourceExtension  "GL_KHR_shader_subgroup_basic"
                              Name 4  "main"
                              Name 8  "global_index_b"
                              Decorate 17 BuiltIn WorkgroupSize
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 1
               7:             TypePointer Function 6(int)
               9:      6(int) Constant 42
              10:             TypeInt 32 0
              11:     10(int) Constant 0
              12:     10(int) Constant 3
              14:             TypeVector 10(int) 3
              15:     10(int) Constant 128
              16:     10(int) Constant 1
              17:   14(ivec3) ConstantComposite 15 16 16
         4(main):           2 Function None 3
               5:             Label
8(global_index_b):      7(ptr) Variable Function
              13:      6(int) GroupNonUniformBroadcast 12 9 11
                              Store 8(global_index_b) 13
                              Return
                              FunctionEnd
</pre>

Since there are no tricks there I would expect `OpGroupBroadcast` instead of `OpGroupNonUniformBroadcast`.

**Comment by sheredom** [comment]
`OpGroupBroadcast` is only valid in OpenCL, so the compiler did the right thing here.

**Comment by krOoze** [comment]
Right, apparently Vulkan lacks the specific Cap support.
