### ISSUE TITLE
HLSL: Suboptimal codegen for static const float arrays

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1430]
Given a shader with static const float3 array declared in a function, glslang generates somewhat suboptimal IR.
Specifically, the array is copied out of global constants into a local variable.
Reading from that variable may require spilling it from registers to local memory; this happens on at least one driver this was tested on...

I'm not sure what the expectation here is in terms of work done by glslang frontend vs spirv-opt optimizer. spirv-opt doesn't optimize this copy away, but arguably glslang could emit more efficient code in the first place.

Shader source:

```
float4 main(uint iid: SV_InstanceId): SV_Position
{
    static const float3 uvRoutingA[16] = { float3(0,0,1),  float3(1,0,0), float3(1,0,0), float3(0,0,1),  float3(1,0,0), float3(1,0,0),  float3(1,0,0),        float3(1,0,0),           float3(0,0,1),        float3(0,0,0), /* #10: */ float3(1,0,0), float3(0,1,0), float3(0,1,0), float3(1,0,0), float3(0,1,0),  float3(0,1,0) };

    return float4(uvRoutingA[iid], 1);
}
```

Shader code with SPIRV: http://shader-playground.timjones.io/e7d48ecea60b861dfe8f8abb8dc7f88f

**Comment by zeux** [comment]
In theory spirv-opt should probably be able to eliminate the copy here as a consequence of https://github.com/KhronosGroup/SPIRV-Tools/pull/1421, but this doesn't happen for some reason; cc @s-perron

**Comment by zeux** [comment]
Just to clarify, this came up in SPIRV-Cross->MSL workflow; the current emitted code results in an inline array initializer for the local array, which causes some Metal drivers to spill. http://shader-playground.timjones.io/5944bca2809c69981234d69bb16f6075

**Comment by johnkslang** [comment]
I recall the need for a memory copy is triggered by a *variable* index into the array, which tends to be platform specific, so the normal path `GLSL -> SPIR-V -> driver` was depending on the driver to locate the array in the best place for the target platform.

**Comment by s-perron** [comment]
I don't think there is anything spriv-opt can do for this case.  I agree with @johnkslang.  The best code sequence will probably be platform specific depending on the capabilities of the platform.  Unless people have other ideas, I think this is simplest code that can be generated given the current instructions in spir-v.

**Comment by zeux** [comment]
A workaround for this issue is now available in SPIRV-Cross thanks to @themaister; I don't think it's possible to improve codegen further due to SPIRV restrictions. I feel like SPIRV is pretty clearly insufficient here - yes, the driver should be responsible for placing constant data wherever it belongs best - but SPIRV makes it necessary for the driver to also remove the copy-to-local-variable, instead of just knowing that the array is in constant memory (which is analogous to analysis performed by SPIRV-Cross now). Anyway, fixing SPIRV is out of scope of this issue so I'll close this.
