### ISSUE TITLE
Convert simple uniforms to an implicit uniform block

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/glslang#1433]
I've work on an application with a large shader library that currently uses uniforms (in addition to UBOs) in a large number of places.  While we're working on migrating away from them, it's not happening quickly.  I'd like to be able to transition our shader pipeline to use SPIR-V as the main representation and then use SPIRV-cross to generate per-platform shaders, but I'm blocked from doing so while the shaders contain uniforms.  If glslang was able to convert uniforms to push constants or specialization constants, I could then do work on SPIRV-cross to convert them back to uniforms as necessary depending on the target GLSL version and other command line options.

**Comment by johnkslang** [comment]
SPIRV-cross should handle uniform fine, and of course time has passed.  Is there still a request here to add functionality to glslang?

**Comment by johnkslang** [comment]
Another feature that could possibly be added is to put all default uniforms into a block.  Glslang already does this for HLSL, but not for GLSL (and is missing a specification to do so).

I'm going to turn this into an enhancement request to do this for GLSL, and I think there was another related issue to point it to.

**Comment by arcady-lunarg** [comment]
You can now do this using the [GL_EXT_vulkan_glsl_relaxed](https://github.com/KhronosGroup/GLSL/blob/main/extensions/ext/GL_EXT_vulkan_glsl_relaxed.txt) extension, which is enabled by passing the `-R` option to glslang. This will put all the simple uniforms into an implicit default block.

**Comment by jherico** [comment]
Awesome.  Sadly I no longer work on shaders.
