### ISSUE TITLE
Can't redeclare gl_perVertex (for gl_ClipDistance as a passthrough)

### ISSUE THREAD

**Issue by tfiner** [KhronosGroup/glslang#1441]
Using glslangValidator, version 7.7.2776 and 7.8.2801 I get the following results:

Reproduction:

a.vert:
```
#version 150
out gl_PerVertex {
   vec4 gl_Position;
   float gl_ClipDistance[4];
};
```
b.geom:
```
#version 150
in gl_PerVertex {
   vec4 gl_Position;
   float gl_ClipDistance[4];
} gl_in[];
```

Observation:
The error is:
> 'built-in block redeclaration' : not supported for this version or the enabled extensions

Expectation:
My understanding is that redeclaring the gl_PerVertex is necessary to define the size of gl_ClipDistance, so I think that the code is correct and the compiler's error message is not. Further, the code does actually work on at least one system. ;)

Lastly, I see in the code with the error message that there's a call to profileRequires what looks like versions 320 and 410 of ES? I didn't see that in the documentation for gl_ClipDistance. Shouldn't it be version 130 for the vertex and 150 for the geometry?

**Comment by johnkslang** [comment]
Redeclaring blocks needs GL_ARB_separate_shader_objects or #version 410.

**Comment by tfiner** [comment]
I don't understand, it says on the documentation page for gl_ClipDistance that you need to redeclare it:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_ClipDistance.xhtml

Is there a way to pass through gl_ClipDistance in a geometry shader in 150?

**Comment by johnkslang** [comment]
I don't think you can redeclare blocks in base #version 150.  This might work:

```
out float gl_ClipDistance[4];
```

Or, going to a higher #version, or using extensions.

Do you need #version 150? #version 150 was a complex juncture between blocks, redeclarations, SSO, extensions, and profiles in this space. If it is possible to get away from it, it would probably save time.

**Comment by tfiner** [comment]
I found a workaround, by taking advantage of that other half of that clause "or indexing with integral constant expressions". It isn't ideal, but it works and compiles without warning or errors.

Your suggestion works fine in a vertex shader, but... there's an array for the geometry shader. That's the part that is causing me problems. Yeah I can't bump the version number.

**Comment by HorstBaerbel** [comment]
I have this for a 330 core shader:
```
#version 330 core
const int nrOfClipPlanes = 6;
uniform vec4 clipPlaneEquation[nrOfClipPlanes];
uniform bool clipPlaneEnabled[nrOfClipPlanes];

out gl_PerVertex {
	vec4 gl_Position;
	float gl_ClipDistance[nrOfClipPlanes];
};

void calculateClipDistances(vec4 position) {
	for (int i = 0; i < nrOfClipPlanes; i++) {
		gl_ClipDistance[i] = clipPlaneEnabled[i] ? dot(position, clipPlaneEquation[i]) : 1.0;
	}
}

uniform mat4 modelViewMatrix;
uniform mat4 projectionMatrix;
uniform mat3 normalMatrix;
uniform vec2 scalarRange;
in vec3 vertex0;
in float color0;
in vec3 normal0;
out float colorCoord;
out vec3 normal;
out vec3 vertexPos;
void main() {
	vec4 position = vec4(vertex0, 1.0);
	vec4 worldPos4 = modelViewMatrix * position;
	gl_Position = projectionMatrix * worldPos4;
	vertexPos = vec3(worldPos4) / worldPos4.w;
	colorCoord = (color0 - scalarRange.x) / (scalarRange.y - scalarRange.x);
	normal = normalize(normalMatrix * normal0);
	calculateClipDistances(position);
} 
```
Is the way of redeclaring gl_ClipDistance wrong?

**Comment by johnkslang** [comment]
Going to `#version 410` lets you redeclare blocks.

For `#version 330`, I think you can just say `out float gl_ClipDistance[nrOfClipPlanes];` without a block.

**Comment by HorstBaerbel** [comment]
I forgot to say that this is a vertex shader. The [wiki page](https://www.khronos.org/opengl/wiki/Vertex_Post-Processing) does not state a specific version requirement btw.

**Comment by johnkslang** [comment]
GLSL issues outside of glslang can be raised at https://github.com/KhronosGroup/GLSL.

**Comment by Yusuf-EMU** [comment]
z
