### ISSUE TITLE
GLSL: inconsistency of implicit type cast between signed and unsigned integers

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/glslang#1448]
Most graphics drivers do not allow implicit type casts between signed and unsigned integers for GLSL, such as `uint x = 1` or `int y = 1u`.

glslang seems to be inconsistent with these type checks, since the following code is validated by the `glslangValidator` (build date: July 17, 2018) without any errors:
```glsl
#version 450
layout(location = 0) out vec4 col;
void main() {
    uint a = 1;
    //int  b = a + 2; // ERROR: cannot convert from ' temp uint' to ' temp int'
    int  b = 2;
    uint c = b * 3;
    uint d = b * 3u;
    col = vec4(1, 2, 3, 4);
}
```
Only the commented line makes glslang output the specified error message.

As far as I know, GLSL is very strict with type casts, especially between signed and unsigned integers.

**Comment by godlikepanos** [comment]
That's a very good point and something that was bugging me for a while as well. As an example, Mali drivers always threw errors on such code.

**Comment by johnkslang** [comment]
The rules are different for OpenGL ES and OpenGL (ESSL versus GLSL).

For ESSL: There are no implicit conversions.

For GLSL: The implicit conversions form a DAG:  int -> uint -> float -> double.  The other direction does not work.  (It is far better to have no cycles when doing overloaded function resolution under type conversion.)

Your example is GLSL. I imagine your Mali experience was ESSL.

Glslang implements the different semantics for each of the dozen or so versions of ESSL and GLSL.

**Comment by LukasBanana** [comment]
We are working on an embedded system but it's running **OpenGL 3.30 Core Profile** on an AMD Vega and a customized GNU/Linux.
However, as far as I know the code was also not compiling on my colleague's PC, who is running a Windows 10 machine which also uses OpenGL rather than OpenGL ES.

**Comment by johnkslang** [comment]
Do you mean this compiles without error?

```
uint a = 1;
int  b = a + 2;
```

That code is simply illegal. File a bug against the driver that allows it.

**Comment by LukasBanana** [comment]
Ok, I'll check that. Thanks for your reply.
