### ISSUE TITLE
Propagation of NoContraction to branch conditions

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/glslang#1449]
Given this code:
```
#version 450

layout (location = 0) in float x;
layout (location = 1) in float y;
layout (location = 2) in float z;

precise gl_Position;

void main(void)
{
    gl_Position.xyzw = vec4(0.0);
    gl_Position.x = ((x * y + z) > 0.0) ? 1.0 : 2.0;
}

```
glslang is generating SPIR-V with **NoContraction** decorations on the **OpFMul** and **OpFAdd**.

However, given the similar
```
#version 450

layout (location = 0) in float x;
layout (location = 1) in float y;
layout (location = 2) in float z;

precise gl_Position;

void main(void)
{
    gl_Position.xyzw = vec4(0.0);
    if ((x * y + z) > 0.0) {
        gl_Position.x = 1.0;
    } else {
        gl_Position.x = 2.0;
    }
}
```

there are no **NoContraction** decorations.
Should one expect the **NoContraction** to propagate through to branch conditions?

**Comment by johnkslang** [comment]
No, I don't think this is part of the contract for `precise`, but I can see it is a bit vague in the specification (a question which should be raised in https://github.com/KhronosGroup/GLSL.

Practically speaking, you could declare the condition to be precise:

```
precise float cond = (x * y + z) > 0.0;
if (cond)...
```

**Comment by johnkslang** [comment]
Any action to take here depends on the outcome of https://github.com/KhronosGroup/GLSL/issues/21.

(It is conceivable no change will be taken.)

**Comment by johnkslang** [comment]
Khronos decided the **NoContraction** does not apply to the control flow or conditions. My own test case for this:

```
#version 460

layout(location = 0) in float f;
layout(location = 1) in float g;
layout(location = 2) in flat int a;
layout(location = 3) in flat int b;
layout(location = 4) in flat int c;

layout(location = 0) out precise vec4 r;

void main()
{
    r = vec4(0);
    r.x = ((a * b + c) > 0) ? f + g : f - g;
}
```

Showed **NoContraction** applying to the `+` and `-`, but not the `*`.

I suspect some subtle translations issues here. So, while there is no effort here to start including control flow, I will check out the inconsistencies raised.

**Comment by stevec611** [comment]
Thanks!

**Comment by johnkslang** [comment]
The difference between our examples is explained by my test math being integer and yours being floating point.

The just leaves the fact that glslang is sometimes propagating NoContraction into the condition of a ?:, where Khronos decided that is not necessary. It's okay, but not required.

**Comment by johnkslang** [comment]
The current algorithm for propagating `precise` picks up the RHS of `=`, regardless of operators, so it is over-conservative for some cases. This is likely okay. You cannot count on this (as indicated from the specification aspect) because of transforms to and from `if-else` and `? :`.
