### ISSUE TITLE
What GLES shader version supported?

### ISSUE THREAD

**Issue by minggo** [KhronosGroup/glslang#1458]
I am the maintainer of [cocos2d-x](https://github.com/cocos2d/cocos2d-x), and doing researching about supporting metal on Mac/iPhone. I plan to not modify current shaders, which are written in GLES version 100(i think it is the version), and use `glslang` to convert the shaders to `SPIR-V` then convert metal later.

I met some issues when doing as mentioned above:
```
A03101308207:bin minggo$ ./glslangValidator -H  ./test.vert
./test.vert
ERROR: #version: ES shaders for Vulkan SPIR-V require version 310 or higher
ERROR: ./test.vert:4: 'attribute' : Reserved word.
ERROR: ./test.vert:4: 'attribute' : no longer supported in es profile; removed in version 300
ERROR: ./test.vert:4: '' : compilation terminated
ERROR: 4 compilation errors.  No code generated.
```

It seems should using ES shader version 310 or higher, but i am not sure if mobile devices, especially android devices, support ES shader 310 or not. Is there any way to work around it? Or is there any suggestion to achieve the goal.

Thanks for your time.

**Comment by johnkslang** [comment]
Version 100 is very old; I think devices generally support newer versions. So, changing your shaders to 310 would probably work. If not, perhaps a switch at the beginning of the shaders: Mostly, the versions are backward compatible. You might be able to change the top of the shaders to adapt:

```
#version 310 es
#define attribute in
...
```

These are specification and market questions, versus glslang questions, so I will close for glslang.

**Comment by minggo** [comment]
Thanks for the reply.
