### ISSUE TITLE
glslangValidator with '-Os' option emits "invalid capability operand: 61"

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/glslang#1461]
An identical SPIR-V file is generated either way but the `-Os` option bleats about subgroups (?).

Error:
```
glslangValidator -Os --target-env vulkan1.1 -o foo.spv foo.comp
error: input:0:0:8: Invalid capability operand: 61`
```

OK:

```
glslangValidator  --target-env vulkan1.1 -o foo.spv foo.comp
```

Compute shader attached: [foo.zip](https://github.com/KhronosGroup/glslang/files/2259072/foo.zip)

**Comment by Nielsbishere** [comment]
I'm having the same problem. I'd very much like to keep -Os. This seems related to https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/101 which might not have been fixed for when optimization occurs.

**Comment by johnkslang** [comment]
@alan-baker this sounds like maybe the optimizer wants to validate first, and due to the environment thinks that this is not allowed:

```
OpCapability GroupNonUniform
```

Should we be looking at the interface between glslang and spirv-opt (how environment is set up)?  Or, is this just within spirv-opt itself?

**Comment by Nielsbishere** [comment]
It sounds like it. I'd guess that not all of the settings are carried from glslangValidator to the optimizer. I'm compiling with -G1.3, so it should generate OpenGL SPIRV1.3

**Comment by alan-baker** [comment]
The optimizer does indeed validate prior to optimization, but GroupNonUniform is acceptable in Vulkan 1.1 in the validator. I'd have to look at how glslang is invoking the validator vs the optimizer. It does seem like the environments aren't being propagated correctly.

**Comment by johnkslang** [comment]
Perhaps confusingly, glslang executes

```
spvOptOptions.set_run_validator(false);
```

Before running the optimizer, so perhaps was not setting things up correctly for it get run anyway.

I see where I could make a context, as already done in glslang:

```
spv_context context = spvContextCreate(MapToSpirvToolsEnv(intermediate.getSpv(), logger));
```

But am not sure where to send it next.

**Comment by johnkslang** [comment]
Looks like it should be this:

```
optimizer.SetTargetEnv(MapToSpirvToolsEnv(intermediate.getSpv(), logger));
```

Going that route.
