### ISSUE TITLE
New glslang release

### ISSUE THREAD

**Issue by jljusten** [KhronosGroup/glslang#1463]
RenderDoc 1.1 embeds an unreleased version of glslang:
https://github.com/baldurk/renderdoc/commit/78ba839f1519

Linux distributions prefer to not use embedded code. Therefore, they rely on a separately packaged glslang. But, since a new glslang version is not available, it is not currently possible to package RenderDoc 1.1.

Maybe a more regular release plan could allow external projects like RenderDoc to know what versions they can depend on without causing difficulties for Linux distributions?

cc: @baldurk

**Comment by johnkslang** [comment]
Sounds right. What qualifies as a "release" for this?

**Comment by johnkslang** [comment]
Glslang moved to semantic versioning with #1255. It makes sense to apply that to the tags, and to tag more often. It adapts often to new extensions, releases of Khronos APIs, etc., and should probably tag at all such interesting events.

**Comment by jljusten** [comment]
That sounds good. Do you anticipate any of these 'interesting events' for adding a new glslang release? (To allow Linux distributions to update RenderDoc to 1.1.)

**Comment by jljusten** [comment]
Thanks! I'll take a look at the new release!

**Comment by johnkslang** [comment]
I still need to figure out how to combine bot binaries with manual tagging.

**Comment by jljusten** [comment]
Is there any chance of gpg signing the tarballs? The wiki.debian.org link above described the process. It's not required, of course, but the signature is just something that is nice to verify.

**Comment by johnkslang** [comment]
I signed the latest tag, which seems tractable, but downloading and verifying all the binaries, signing them, and then uploading the signatures is not easy, and it's not clear it is worth it.

Recapping the changes though: there are now up-to-date releases, with signed tags, and based on the semantic versioning of glslang.

**Comment by jljusten** [comment]
> but downloading and verifying all the binaries, signing them, and then uploading the signatures is not easy, and it's not clear it is worth it.

Maybe you could only sign the source .tar.gz? I think some Linux distributions would check that signature, but I don't know that anyone will check the .zip signature.

**Comment by jljusten** [comment]
> I signed the latest tag, which seems tractable

Yeah, no real need to go back to previous releases...

**Comment by johnkslang** [comment]
It would not be too hard to sign the source.tar.gz. Is there a way GitHub can do that though?  GitHub makes that.

**Comment by jljusten** [comment]
> Is there a way GitHub can do that though?

Based on:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

It looks like the github generated tar.gz has to be downloaded so the gpg command can be run:

> gpg --armor --detach-sign mysoftware-0.4.tar.gz

I don't think github has an option to sign it with a github key.

**Comment by johnkslang** [comment]
Yes, I did that for two executables, will start doing it for the tar.gz.
