### ISSUE TITLE
Automatically uploaded binaries, wrong platform

### ISSUE THREAD

**Issue by Shuusui** [KhronosGroup/glslang#1467]
I downloaded the automatically uploaded binaries from https://github.com/KhronosGroup/glslang/releases/tag/master-tot for windows x64 but all the libraries are x86 libraries so I can't access them from my x64 build. I did it by myself with cmake and everything's fine.

**Comment by johnkslang** [comment]
I believe this is fixed by 242c28f21c1dde6408eb8dc83caa4d8222b3aac2. Reopen if not.
