### ISSUE TITLE
entry-point OpModuleProcessed doesn't correspond to cmd line arg

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#1468]
In the code an `OpModuleProcessed` is added for an entry point specified:

https://github.com/KhronosGroup/glslang/blob/81793ad2a327656cb7b3ae85d32d0360829ffc15/glslang/MachineIndependent/localintermediate.h#L259-L261

but `--entry-point` isn't a valid command line argument to glslang. I think it should just be an alias for `-e` and was missed?

**Comment by johnkslang** [comment]
Looks like it is intended to be there, but not finished. Adding it now.
