### ISSUE TITLE
Build instructions unclear

### ISSUE THREAD

**Issue by delner** [KhronosGroup/glslang#1469]
The build instructions included are unclear and are leading to errors. It asks:

> Assume the source directory is $SOURCE_DIR and the build directory is $BUILD_DIR. First ensure the build directory exists, then navigate to it:
> 
> mkdir -p $BUILD_DIR
> cd $BUILD_DIR
>
> For building on Linux:
> 
> cmake -DCMAKE_BUILD_TYPE={Debug|Release|RelWithDebInfo} \
>       -DCMAKE_INSTALL_PREFIX="$(pwd)/install" $SOURCE_DIR

So I set `SOURCE_DIR` to `~/src/vendor/glslang` (which is the cloned repo) and `BUILD_DIR` to `~/src/vendor/glslang-build` (which is an arbitrary empty dir?)

When I `cd $BUILD_DIR` and run the `cmake`, it results in the following error:

```
~/src/vendor/glslang-build$ cmake -DCMAKE_BUILD_TYPE={Debug|Release|RelWithDebInfo}       -DCMAKE_INSTALL_PREFIX="$(pwd)/install" $SOURCE_DIR
CMake Error: The source directory "~/src/vendor/glslang-build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Command 'Release' not found, did you mean:

  command 'release' from deb bikeshed

Try: sudo apt install <deb name>

RelWithDebInfo}: command not found
```

This is weird because I wouldn't think its trying to read the lists from the build dir. If I `cd $SOURCE_DIR` and try again, I get:

```
~/src/vendor/glslang$ cmake -DCMAKE_BUILD_TYPE={Debug|Release|RelWithDebInfo}       -DCMAKE_INSTALL_PREFIX="$(pwd)/install" $SOURCE_DIR

Command 'Release' not found, did you mean:

  command 'release' from deb bikeshed

Try: sudo apt install <deb name>

RelWithDebInfo}: command not found
```

I'm attempting to install on an Ubuntu 18.04 LTS distribution, and I think I have all the dependencies installed. Any suggestions? Something seems off.

**Comment by baldurk** [comment]
When the instructions list `-DCMAKE_BUILD_TYPE={Debug|Release|RelWithDebInfo}` it's meant that you can choose one of those parameters - i.e. `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo`.

Pasting it as-is means the argument is interpreted as just `-DCMAKE_BUILD_TYPE={Debug` and then the output is piped to a program `Release` which doesn't work - the cmake file isn't found because all the arguments after that aren't passed to `cmake`.

**Comment by delner** [comment]
Alright, I'll give it a shot. Sorry I might have missed this: didn't know that convention.

**Comment by johnkslang** [comment]
Thanks Baldur. I'll take a shot at making the instructions work better for copy-paste.

**Comment by delner** [comment]
Thanks guys. Sorry for the newbie question, but I appreciate the clarification.
