### ISSUE TITLE
mat3 opcode in uniform buffer

### ISSUE THREAD

**Issue by torokze** [KhronosGroup/glslang#1473]
Hi,

A vertex shader with the following uniform compiled into spir-v with glslangValidator.exe:
layout (binding = 0) uniform PerFrame
{
    mat4x4 in_ViewMatrix;
    mat4x4 in_ProjectionMatrix;
    mat4x4 in_ViewProjectionMatrix;
    **mat3x3 in_NormalMatrix;**
    vec3 in_LookAt;
    vec3 in_CamPos;
    vec3 in_ViewDir;
};

The decompiled code shows this:
...
               OpName %19 "PerFrame" ; 0x000000cc
               OpMemberName %19 0 "in_ViewMatrix" ; 0x000000e0
               OpMemberName %19 1 "in_ProjectionMatrix" ; 0x000000fc
               OpMemberName %19 2 "in_ViewProjectionMatrix" ; 0x0000011c
               **OpMemberName %19 3 "in_NormalMatrix" ; 0x00000140**
               OpMemberName %19 4 "in_LookAt" ; 0x0000015c
               OpMemberName %19 5 "in_CamPos" ; 0x00000174
               OpMemberName %19 6 "in_ViewDir" ; 0x0000018c
...
OpMemberDecorate %19 0 ColMajor ; 0x000002a8
               OpMemberDecorate %19 0 Offset 0 ; 0x000002b8
               OpMemberDecorate %19 0 MatrixStride 16 ; 0x000002cc
               OpMemberDecorate %19 1 ColMajor ; 0x000002e0
               OpMemberDecorate %19 1 Offset 64 ; 0x000002f0
               OpMemberDecorate %19 1 MatrixStride 16 ; 0x00000304
               OpMemberDecorate %19 2 ColMajor ; 0x00000318
               OpMemberDecorate %19 2 Offset 128 ; 0x00000328
               OpMemberDecorate %19 2 MatrixStride 16 ; 0x0000033c
               **OpMemberDecorate %19 3 ColMajor ; 0x00000350**
               **OpMemberDecorate %19 3 Offset 192 ; 0x00000360**
               **OpMemberDecorate %19 3 MatrixStride 16 ; 0x00000374**
               OpMemberDecorate %19 4 Offset 240 ; 0x00000388
               OpMemberDecorate %19 5 Offset 256 ; 0x0000039c
               OpMemberDecorate %19 6 Offset 272 ; 0x000003b0
...

Them mat3x3 member (in_NormalMatrix) stride is equal to the mat4x4 members (16 vs 9) .
This causes wrong matrix in shader and wrongly aligned members (the ones behind in_NormalMatrix).
All these matrix and vector values out of sync.

I've checked it with VulkanSDK 1.1.77.0 and 1.1.82.0. Both compiles this the same way.

Zoltán

**Comment by johnkslang** [comment]
Yes, a `uniform` buffer is laid out that way, according to the Vulkan specification:

> * A three- or four-component vector, with components of size N, has a base alignment of 4 N.
> * A column-major matrix has a base alignment equal to the base alignment of the matrix column type.
> * Any ArrayStride or MatrixStride decoration must be an integer multiple of the base alignment of the array or matrix from above.

This is because it is likely that is how your hardware will work the fastest.

**Comment by torokze** [comment]
Thanks johnkslang,

I corrected my application code according to:
14.5.4. Offset and Stride Assignment

and now everything is aligned.
