### ISSUE TITLE
MatrixStride is set to 16 for several cases that could be 8

### ISSUE THREAD

**Issue by infapi00** [KhronosGroup/glslang#1475]
We found that for the following cases:
  * mat2x2 column and row major
  * mat2x3 row major
  * mat2x4 row major
  * mat3x2 column major
  * mat4x2 column major

MatrixStride could be 8, but glslangValidator still sets it to 16. I confirmed that it could be 8 by querying GL_UNIFORM_MATRIX_STRIDE using those matrices when using the original GLSL on OpenGL Mesa Intel driver.

Note that from this paragraph from ARB_gl_spirv spec:

>    "7.6.2.spv SPIR-V Uniform Offsets and Strides
> 
>     The SPIR-V decorations *GLSLShared* or *GLSLPacked* must not be used. A
>     variable in the *Uniform* Storage Class decorated as a *Block* must be
>     explicitly laid out using the *Offset*, *ArrayStride*, and *MatrixStride*
>     decorations. If the variable is decorated as a *BufferBlock*, its offsets
>     and strides must not contradict std430 alignment and minimum offset
>     requirements.  Otherwise, its offsets and strides must not contradict
>     std140 alignment and minimum offset requirements."

I understand that MatrixStride==16 would be still valid. But it also lead to need an unnecessary bigger buffer size.

Skimming the code, I guess that this should be handled at TGlslangToSpvTraverser::getMatrixStride (GlslangToSpv.cpp) or at  TIntermediate::getBaseAlignment(linkValidate.cpp), but I didn't have time to check it. FWIW, the latter includes a list of std140 spec-rules for this, and as far as I understand reading them, it should allow MatrixStride as 8 for those cases.

**Comment by johnkslang** [comment]
I just tried a quick test:

t.vert:
```
#version 460

buffer bname {
    mat2x2 m22;
} binst;

void main()
{
}
```

`glslangValidator -G -H t.vert`:

```
               OpMemberDecorate %bname 0 MatrixStride 8
```

Can you post an example that works incorrectly?

**Comment by infapi00** [comment]
>  Can you post an example that works incorrectly?

Yes, sorry, I forgot to mention that this happens with UBOs (so perhaps we would need to tweak the issue title?). So for example:
```
#version 460

layout (binding = 5, column_major) uniform MyBlock
 {
 mat2x2 m;
 };

void main()
{
}
```
```
$ glslangValidator -G -H --spirv-dis /tmp/ubo.vert | grep MatrixStride
               OpMemberDecorate %MyBlock 0 MatrixStride 16
```

And in order to provide more examples. As I mentioned, I tested the same test in OpenGL GLSL. You can find the test here:
https://github.com/Igalia/piglit/blob/apinheiro/matrix-stride-work/tests/spec/arb_gl_spirv/execution/ubo/matrix/mat2x2-column-major.shader_test

That test includes the original GLSL shader, and the SPIR-V generated by glslangvalidator. We are using tests like that to test our ongoing implementation of ARB_gl_spirv for Mesa driver. The idea is that for most tests, the outcome should be the same, so it is good to be able to execute one and the other to compare. At the end of the test, there is an additional check:

`verify program_interface_query GL_UNIFORM_BLOCK ComponentsBlock GL_BUFFER_DATA_SIZE 16`

16 is the size that we get when we run the GLSL shader. We can only get a buffer size of 16 if the Matrix Stride is 8. Additionally, when is the GLSL shader the one used, the program that run the test do a GL_UNIFORM_MATRIX_STRIDE query in order to know how to upload the matrix content. In that case the Matrix Stride is 8.

**Comment by johnkslang** [comment]
I see the comment (from the OpenGL spec) says:

```
    //   4. If the member is an array of scalars or vectors, the base alignment and array
    //      stride are set to match the base alignment of a single array element, according
    //      to rules (1), (2), and (3), and rounded up to the base alignment of a vec4....
```

Does that last phrase clear things up?

**Comment by infapi00** [comment]
> Does that last phrase clear things up?

Yes, clarifies the issue. Thanks.

I have been investigating what was my problem. The problem was that I forgot that the default ubo layout for GLSL is not std140, but shared. But for GL_KHR_vulkan_glsl (so ARB_gl_spirv) the default is std140. As my test suite doesn't have a way to specify that you are running under GL_KHR_vulkan_glsl rules, I was basically comparing shaders using different layouts, getting different buffer sizes, and assuming that the driver was right. So sorry for not checking the spec with more detail first.

So this issue can be closed. Sorry for the noise, and thanks for the clarification.
