### ISSUE TITLE
Does not compile with ENABLE_OPT enabled

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/glslang#1481]
The include file 'message.h' is missing and requested in file 'SPIRV/GlslangToSpv.cpp'.
This prevents compilation of Google's glslc (shaderc).

**Comment by johnkslang** [comment]
This was fixed yesterday, via #1480.

**Comment by johnkslang** [comment]
@dneto0 does this need to propagate through the fork used by shaderc?

**Comment by dneto0** [comment]
> @dneto0 does this need to propagate through the fork used by shaderc?

Yes.  I've just refreshed google/glslang with latest KhronosGroup/glslang
You can close this now. (I can't)

**Comment by dneto0** [comment]
Oh, you already closed.  Yay. :-)
