### ISSUE TITLE
Glslang project should host its own Android.mk build file

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1483]
Different projects want to build Glslang for Android using ndk-build, e.g. Shaderc and Vulkan CTS.  They are each hosting their own Android.mk file to support that.  

Glslang should host its own Android.mk file so that certain things are easier, like adding a new file to Glslang.

I would recommend borrowing heavily from Shaderc's working solution:
https://github.com/google/shaderc/blob/master/third_party/Android.mk 

A bonus step is to have the Glslang bots check this path, by building for at least one Android ABI.

**Comment by sfricke-samsung** [comment]
I think https://github.com/KhronosGroup/glslang/pull/1606 closes this or am I wrong?

**Comment by arcady-lunarg** [comment]
This has indeed been fixed by #1606.
