### ISSUE TITLE
Unnecessary references to SPV_AMD_gpu_shader_int16

### ISSUE THREAD

**Issue by alegal-arm** [KhronosGroup/glslang#1487]
glslang generates unnecessary OpExtension "SPV_AMD_gpu_shader_int16" for the following shader (OpExtension "SPV_KHR_16bit_storage" should be enough here):

```
#version 450
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_shader_8bit_storage : enable
layout(local_size_x = 1) in;

layout(std140, binding = 0) buffer AcBlock { highp uint ac_numPassed; };

layout(std140, binding = 1) buffer Block
{
    uint16_t var[3];
};

bool compare_uint16_t (highp uint a, highp uint b)    { return a == b; }

void main (void)
{
    bool allOk = true;
    allOk = allOk && compare_uint16_t(uint(var[0]), 9u);
    allOk = allOk && compare_uint16_t(uint(var[1]), 5u);
    allOk = allOk && compare_uint16_t(uint(var[2]), 4u);
    if (allOk)
        ac_numPassed++;

    var[0] = uint16_t(9u);
    var[1] = uint16_t(1u);
    var[2] = uint16_t(1u);
}
```
cmd-line

```
./glslangValidator -V
```

**Comment by alegal-arm** [comment]
cc @johnkslang

**Comment by johnkslang** [comment]
I've been looking at this, and am unclear on when it should be triggered. Currently, it is triggered only if the target SPIR-V version is less than 1.3, but still too broadly.

Do we need options to say which subset of extensions are being targeted?

**Comment by johnkslang** [comment]
I am working now to transfer finer grained testing for this extension to the new post-processing detection for extensions/capabilities.

**Comment by johnkslang** [comment]
The use of UConvert could be satisfied by multiple extensions, leaving a potentially complex problem of how to decide. However, for this case, glslang already emits SPV_KHR_16bit_storage, so there is no need to emit the AMD extension. I could see auto-deducing extensions getting quite a bit more complex though.

**Comment by johnkslang** [comment]
BTW, a work around for AMD code too aggressively suggesting AMD extensions is to compile with AMD_EXTENSIONS turned off.
