### ISSUE TITLE
82 tests failed from master branch revision 949344f

### ISSUE THREAD

**Issue by KarenHuang2016** [KhronosGroup/glslang#1488]
We build glslang and run tests on Windows 10 with VS2017. There are 82 tests failed from master branch revision [949344f ](https://github.com/KhronosGroup/glslang/commit/949344f081d5d2aa4db279dbc00469eba42b13f8). Could you please help to take a look? Thank you very much.

Repro steps:
1. git clone https://github.com/KhronosGroup/glslang.git D:\Glslang\src
2. git clone https://github.com/google/googletest.git D:\Glslang\src\External\googletest
3. Open a VS 2017 x86 command prompt and browse to D:\Glslang
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15 2017" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
6. popd
7. msbuild /p:Configuration=Release;Platform=Win32 build_x86\glslang.sln /t:Rebuild /m
8. pushd build_x86\gtests\Release
9. glslangtests.exe

Actual result:
There are 82 tests failed. 
[==========] 1181 tests from 47 test cases ran. (12208 ms total)
[  PASSED  ] 1099 tests.
[  FAILED  ] 82 tests, listed below:
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_attributeC11_frag, where GetParam() = 8-byte object <8C-EB C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_buffer_frag, where GetParam() = 8-byte object <F8-EB C9-00 F8-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_constantbuffer_frag, where GetParam() = 8-byte object <58-EF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_constructimat_frag, where GetParam() = 8-byte object <A8-EF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_coverage_frag, where GetParam() = 8-byte object <C0-EF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_emptystructreturn_frag, where GetParam() = 8-byte object <28-F0 C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_emptystructreturn_vert, where GetParam() = 8-byte object <44-F0 C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_float1_frag, where GetParam() = 8-byte object <B8-F0 C9-00 F8-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_gatherRGBA_offset_dx10_frag, where GetParam() = 8-byte object <94-F2 C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_gatherRGBA_offsetarray_dx10_frag, where GetParam() = 8-byte object <B8-F2 C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_intrinsics_comp, where GetParam() = 8-byte object <B0-F5 C9-00 98-F5 C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_intrinsics_evalfns_frag, where GetParam() = 8-byte object <C8-F5 C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_intrinsics_frag, where GetParam() = 8-byte object <64-F6 C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_namespace_frag, where GetParam() = 8-byte object <20-FA C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_matNx1_frag, where GetParam() = 8-byte object <4C-FA C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_matrixSwizzle_vert, where GetParam() = 8-byte object <74-FA C9-00 44-F5 C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_PointSize_geom, where GetParam() = 8-byte object <34-FC C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplebias_offset_dx10_frag, where GetParam() = 8-byte object <50-FE C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplebias_offsetarray_dx10_frag, where GetParam() = 8-byte object <74-FE C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmp_array_dx10_frag, where GetParam() = 8-byte object <9C-FE C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmp_basic_dx10_frag, where GetParam() = 8-byte object <BC-FE C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmp_offset_dx10_frag, where GetParam() = 8-byte object <FC-FE C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmp_offsetarray_dx10_frag, where GetParam() = 8-byte object <1C-FF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmplevelzero_array_dx10_frag, where GetParam() = 8-byte object <84-FF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmplevelzero_basic_dx10_frag, where GetParam() = 8-byte object <AC-FF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmplevelzero_offset_dx10_frag, where GetParam() = 8-byte object <D4-FF C9-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_samplecmplevelzero_offsetarray_dx10_frag, where GetParam() = 8-byte object <00-00 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_struct_split_assign_frag, where GetParam() = 8-byte object <20-03 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_frag, where GetParam() = 8-byte object <FC-03 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_append_fn_frag, where GetParam() = 8-byte object <34-04 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_atomics_frag, where GetParam() = 8-byte object <58-04 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_byte_frag, where GetParam() = 8-byte object <78-04 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_coherent_frag, where GetParam() = 8-byte object <94-04 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_fn_frag, where GetParam() = 8-byte object <F4-04 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_rw_frag, where GetParam() = 8-byte object <2C-05 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_rwbyte_frag, where GetParam() = 8-byte object <48-05 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_texture_struct_frag, where GetParam() = 8-byte object <FC-05 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_intrinsics_vert, where GetParam() = 8-byte object <44-06 CA-00 14-F7 C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_matType_frag, where GetParam() = 8-byte object <78-06 CA-00 F8-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_matType_bool_frag, where GetParam() = 8-byte object <8C-06 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_matType_int_frag, where GetParam() = 8-byte object <A4-06 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_semantic_geom, where GetParam() = 8-byte object <2C-07 CA-00 E0-EA C9-00>
[  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_tristream_append_geom, where GetParam() = 8-byte object <24-08 CA-00 E0-EA C9-00>
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_130_frag, where GetParam() = "spv.130.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_140_frag, where GetParam() = "spv.140.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_150_geom, where GetParam() = "spv.150.geom"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_400_frag, where GetParam() = "spv.400.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_420_geom, where GetParam() = "spv.420.geom"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_builtInXFB_vert, where GetParam() = "spv.builtInXFB.vert"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_controlFlowAttributes_frag, where GetParam() = "spv.controlFlowAttributes.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_memoryQualifier_frag, where GetParam() = "spv.memoryQualifier.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_newTexture_frag, where GetParam() = "spv.newTexture.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_paramMemory_frag, where GetParam() = "spv.paramMemory.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_sampleMaskOverrideCoverage_frag, where GetParam() = "spv.sampleMaskOverrideCoverage.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_sparseTexture_frag, where GetParam() = "spv.sparseTexture.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_sparseTextureClamp_frag, where GetParam() = "spv.sparseTextureClamp.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_image_frag, where GetParam() = "spv.image.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_AofA_frag, where GetParam() = "spv.AofA.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_queryL_frag, where GetParam() = "spv.queryL.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_separate_frag, where GetParam() = "spv.separate.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_xfb_vert, where GetParam() = "spv.xfb.vert"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_xfb2_vert, where GetParam() = "spv.xfb2.vert"
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_xfb3_vert, where GetParam() = "spv.xfb3.vert"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_int8_frag, where GetParam() = "spv.int8.frag"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_vulkan110_int16_frag, where GetParam() = "spv.vulkan110.int16.frag"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_int32_frag, where GetParam() = "spv.int32.frag"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_explicittypes_frag, where GetParam() = "spv.explicittypes.frag"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_float32_frag, where GetParam() = "spv.float32.frag"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_float64_frag, where GetParam() = "spv.float64.frag"
[  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_subgroupPartitioned_comp, where GetParam() = "spv.subgroupPartitioned.comp"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_float16_frag, where GetParam() = "spv.float16.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_float16Fetch_frag, where GetParam() = "spv.float16Fetch.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_imageLoadStoreLod_frag, where GetParam() = "spv.imageLoadStoreLod.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_int16_frag, where GetParam() = "spv.int16.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_int16_amd_frag, where GetParam() = "spv.int16.amd.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_shaderBallotAMD_comp, where GetParam() = "spv.shaderBallotAMD.comp"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_textureGatherBiasLod_frag, where GetParam() = "spv.textureGatherBiasLod.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_sampleMaskOverrideCoverage_frag, where GetParam() = "spv.sampleMaskOverrideCoverage.frag"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_viewportArray2_tesc, where GetParam() = "spv.viewportArray2.tesc"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_stereoViewRendering_tesc, where GetParam() = "spv.stereoViewRendering.tesc"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_multiviewPerViewAttributes_tesc, where GetParam() = "spv.multiviewPerViewAttributes.tesc"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_atomicInt64_comp, where GetParam() = "spv.atomicInt64.comp"

**Comment by johnkslang** [comment]
Do you run with SPIRV-Tools (from glslang/known_good.json) present and with ENABLE_OPT turned on?

**Comment by KarenHuang2016** [comment]
@johnkslang, thanks for your response. After run with SPIRV-Tools, these 82 tests passed. So close this issue.
