### ISSUE TITLE
Image sampled type doesn't match GLSL image base type.

### ISSUE THREAD

**Issue by curro** [KhronosGroup/glslang#149]
Use of the following image declaration from a CTS test (full GLSL source attached):
   layout (binding = 0, rgba16ui) writeonly uniform highp uimage1D u_image;

is translated into SPIR-V using the following type declaration:
    9:             TypeInt 32 0
[...]
    28:             TypeImage 9(int) 1D nonsampled format:Rgba16ui

The sampled type is incompatible with the specified image format and doesn't match the GLSL input.
[cs.txt](https://github.com/KhronosGroup/glslang/files/105590/cs.txt)

**Comment by johnkslang** [comment]
Is it only the int versus uint aspect of this that is of concern?

(E.g., I believe the type being 32 bits rather than 16 bits is correct.)

**Comment by curro** [comment]
Yeah, that's right.

**Comment by johnkslang** [comment]
Maybe this is just about the debug string `(int)`: The SPIR-V is `TypeInt 32 0` which is an `unsigned int`.  Or, is there another incompatibility?

**Comment by curro** [comment]
Looks like you're right, the actual type is set up correctly, sorry for the noise.
