### ISSUE TITLE
Preprocessor doesn't handle string literals correctly

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#1490]
I think this is a regression since I believe this used to work at some point in the past.

Given a shader snippet like this:

	[[vk::builtin("PointSize")]]
	float PointSize: PSIZE;

and calling glslang's preprocessor like this:

        glslang::TShader shader(EShLangCompute);
        shader.setPreamble(preamble.c_str());
        shader.setStringsWithLengthsAndNames(&sourceString, &sourceLength, &sourceName, 1);

        TBuiltInResource builtinResources = {};

        EShMessages messages = EShMessages(EShMsgReadHlsl | EShMsgOnlyPreprocessor);

        if (!shader.preprocess(&builtinResources, 0, ENoProfile, false, false, messages, &result, includer))
            throw std::runtime_error("Preprocessing failed\n");

Results in this output:

    [[vk :: builtin(PointSize)]]
    float PointSize : PSIZE;

Which can't be parsed by the compiler since the quotes have been removed.

**Comment by johnkslang** [comment]
I will fix this regression.

However, this is not a goal of glslang, to correctly do "-E" style processing; it was a side path someone added because they almost got this functionality for free and was useful for some testing. But, the rigor and tests that this fully works is still missing.

**Comment by zeux** [comment]
Thanks! Noted about the API not being stable/official.

**Comment by johnkslang** [comment]
Wrong issue number, it was #1496.
