### ISSUE TITLE
Why isn't this idiom supported? "layout(local_size_x = gl_SubgroupSize) in;"

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/glslang#1498]
It's not uncommon to write compute shaders with a workgroup size equal to the subgroup size (or some multiple).

However, declaring the workgroup size like this results in a "constant expression required" error:

```
#extension GL_KHR_shader_subgroup_basic : require
...
layout(local_size_x = gl_SubgroupSize) in;
```

Shouldn't gl_SubgroupSize be considered a (weaker) constant even though it's not known until compile time?

I understand how to workaround this issue though...

**Comment by dneto0** [comment]
I think this is essentially the same as https://github.com/KhronosGroup/GLSL/issues/19

**Comment by allanmac** [comment]
Thanks, this is definitely the same issue!

Even when using a specialization constant, it appears describing a workgroup size in terms of subgroups might not be practical if the device has a variable-width subgroup size determined by register pressure (e.g. Intel GEN) and can't be determined until compilation is complete.

It sounds like the idiom I described should be abandoned and compute shaders should remain opaque and sizable only in terms of invocation ids with no expectation on subgroup width.
