### ISSUE TITLE
SelectionMerge is missing when translating loop to SPIR-V token

### ISSUE THREAD

**Issue by amdrexu** [KhronosGroup/glslang#150]
We find recent refactoring work of CFG block leads to this problem:

Please note that  prior to this instruction "BranchConditional 22 15 16", there is no selection merge.

GLSL source:
#version 450

out vec4 outColor;

void main()
{
    float f1 = 0.0f;
    int i = 1;

    while (i < 10)
    {
        f1 += 0.5;
        i++;
    }

    outColor = vec4(f1);
}

SPIR-V token:
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 33

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 30
                              ExecutionMode 4 OriginLowerLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 8  "f1"
                              Name 12  "i"
                              Name 30  "outColor"
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypePointer Function 6(float)
               9:    6(float) Constant 0
              10:             TypeInt 32 1
              11:             TypePointer Function 10(int)
              13:     10(int) Constant 1
              20:     10(int) Constant 10
              21:             TypeBool
              23:    6(float) Constant 1056964608
              28:             TypeVector 6(float) 4
              29:             TypePointer Output 28(fvec4)
    30(outColor):     29(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
           8(f1):      7(ptr) Variable Function
           12(i):     11(ptr) Variable Function
                              Store 8(f1) 9
                              Store 12(i) 13
                              Branch 14
              14:             Label
                              LoopMerge 16 17 None
                              Branch 18
              18:             Label
              19:     10(int) Load 12(i)
              22:    21(bool) SLessThan 19 20
                              BranchConditional 22 15 16
              15:               Label
              24:    6(float)   Load 8(f1)
              25:    6(float)   FAdd 24 23
                                Store 8(f1) 25
              26:     10(int)   Load 12(i)
              27:     10(int)   IAdd 26 13
                                Store 12(i) 27
                                Branch 17
              17:               Label
                                Branch 14
              16:             Label
              31:    6(float) Load 8(f1)
              32:   28(fvec4) CompositeConstruct 31 31 31 31
                              Store 30(outColor) 32
                              Return
                              FunctionEnd

**Comment by ratchetfreak** [comment]
technically that should be an opLoopMerge before the opBranchConditional.

**Comment by amdrexu** [comment]
The OpLoopMerge appear in the front of this shader. The structure is:

loop
    if (cond)
        do something
    else
        break
    endif
endloop

So I think there is a missing "OpSelectionMerge" corresponding to the "endif".

**Comment by johnkslang** [comment]
The `BranchConditional 22 15 16` is a "convergence" to where the loop's merge instruction said to converge to.

Basically, the idea is that when control flow will diverge, you declare the convergence location with a merge instruction.  Branches in diverged control flow that cause the convergence are converging branches, not diverging branches, and don't need a merge declared.  There is no new merge to declare, it **is** the merge of the previously declared merge.

The specification itself does not require all branches to declare a merge point, only diverging branches.  We have in internal action to make this a bit more clear.

**Comment by amdrexu** [comment]
OK. I see. So when the supposed merge instruction is missing for OpBranchConditional, we have to check the nearest merge instruction prior to it and decide possible actions.

**Comment by johnkslang** [comment]
I think a good thing to do is keep a stack of merge points.  When you see a branch to a merge point, you'll then know it is converging the control flow (exiting at the bottom, a break, etc.).  When you a see a merge instruction, it means a new nested one to go on the stack.  I'm simplifying a bit, but that's the general idea.

**Comment by amdrexu** [comment]
Thank you for providing this valuable suggestion :)
