### ISSUE TITLE
Delete #ifdef's from interfaces

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#1502]
Having `#ifdef`'s in interfaces can cause weird problems if the two components are compiled with different `#define`s.

**Comment by johnkslang** [comment]
So, trying this out, there are a couple issues:

- where to draw the line in "interface", as different uses of glslang consume just the SPIR-V, or the types, or the AST, etc.
- the interaction of code in the interface with code outside the interface, as the headers don't include just declarations, but also methods that operate on them

Is the workaround of defining NV_EXTENSIONS and AMD_EXTENSIONS and ENABLE_HLSL sufficient for the moment? Or, is just dealing with resources.h sufficient? Or, is more needed to make things work today? No argument that longer term, the headers should match the libraries, independent of having to get these flags right.

**Comment by johnkslang** [comment]
> ResourceLimits.h

1f60c72c674d6a77043d03843563b4be63e80267 removes the NV_EXTENSIONS.

**Comment by jeffbolznv** [comment]
Unfortunately, a couple more changes are needed. I see a structure mismatch for TProgram (declared in CTS code, used in glslang code) where the mismatch is caused by the two ifdefs in glslang\Public\ShaderLang.h. Once I remove those, I can run some tests.

**Comment by jeffbolznv** [comment]
I made PR https://github.com/KhronosGroup/glslang/pull/1508 for these two ifdefs.

**Comment by johnkslang** [comment]
Accepted the PR. Note, it was a novel thing, to have #ifdef in these two files; a short-lived thing.

I found two more files for which the same could be said, and am also removing from them:

- SPIRV/SpvBuilder.h
- MachineIndependent/ParseHelper.h

The public interface-proper was meant to be in ShaderLang.h. It is clear it expanded into ResourceLimits.h.  The other two files are more internal; but there seem to be many levels at which consumers hook into glslang.
