### ISSUE TITLE
HLSL: glslang can compile hlsl code with invalid HLSL semantic "POSITION"

### ISSUE THREAD

**Issue by Andreyogld3d** [KhronosGroup/glslang#1504]
Hi!,
I try to compile HLSL Shader:
```
struct PS {
    float4 position     : POSITION; // should be SV_POSITION
   	layout(location = 0) float2 uv0          : TEXCOORD0;
   	layout(location = 1) float AlphaRef : TEXCOORD1;
	layout(location = 2) float3 Normal : TEXCOORD2;
	layout(location = 3) float3 LightDir : TEXCOORD3;
};

cbuffer : register(b0) {
	row_major float4x4 ModelViewProjection;
	float4 CameraPosition;
	float4 ObjectPosition;
	float4 time_0_X;
	float4 LightDir;
}

float GetAlphaScale(float curDistSqCam)
{
	const float alphaRefSqDistance = 30000.0f;
	float aRef = alphaRefSqDistance / curDistSqCam;
	aRef = min(aRef, 1.0f);
	return aRef;
}

float3 rotateVector(float3 v, float angle)
{
	float Sin;
	float Cos;
	sincos(angle, Sin, Cos);
	float3 ret;
    ret.x = v.x * Cos - v.z * Sin;
	ret.z = v.x * Sin + v.z * Cos;
	ret.y = v.y;
	return ret;
}

PS vsMain(layout(location = 0) in float4 position : SV_POSITION, layout(location = 2) in float3 Normal : NORMAL, layout(location = 8) in float2 uv0 : TEXCOORD0, layout(location = 9) in float4 v0 : TRANSFORM0)
{
	PS vsOut;
	float4 pos = float4(position.xyz, 1.0f);
	if (0.0f == uv0.y)
	{
		float val = (ObjectPosition.x + ObjectPosition.z);
		float angle = time_0_X.x + val;
		float Sin_ = sin(angle) * pos.y;
		float Cos_ = cos(angle) * pos.y;
		const half k = 0.1;
		pos.x += (Sin_ * k);
		pos.z += (Cos_ * k);
	}
	pos.xyz += v0.xyz;
	vsOut.position = mul(pos, ModelViewProjection);
	vsOut.uv0 = uv0;
	float3 d = pos.xyz - CameraPosition.xyz;
	float curDistSqCam = dot(d, d);
	float AlphaRef = GetAlphaScale(curDistSqCam);
	vsOut.AlphaRef = AlphaRef;
	vsOut.Normal = Normal;
	vsOut.LightDir = -LightDir.xyz;
	return vsOut;
}

```
We have Invalid HLSL semantic "POSITION",  on AMD hardware this is causes of error of Creating of VkPipeline.
Possible decisions:
1) Don't compile shader and produce error report about invalid HLSL semantic
2) Replace POSITION to SV_POSITION

Aloso, I attached hlsl shader
[bushesVS_vk.zip](https://github.com/KhronosGroup/glslang/files/2412831/bushesVS_vk.zip)
Thank ou for HLSL support.

**Comment by johnkslang** [comment]
Glslang is not an HLSL validator, though it is okay to fix problems people run into. The fuller solution is to consider FXC as a validator.  I'm not sure yet which category this is. FXC would have caught it, but glslang doesn't? Or glslang makes bad SPIR-V and the SPIR-V validator doesn't catch it? Or...?

**Comment by Andreyogld3d** [comment]
Hi, @johnkslang

> Or glslang makes bad SPIR-V and the SPIR-V validator doesn't catch it? Or...?
Yes, I vave problem with result SPIR-V form HLSL: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/350

**Comment by johnkslang** [comment]
Both glslang and FXC accept and translate both SV_POSITION and POSITION. For both, if it is SV_POSITION, it is recognized as the special built-in variable for position.  For both, if it is POSITION, it is treated as a non-built-in variable.

It appears it is simply compiling what you asked it to compile, and if you want SV_POSITION, you should specify SV_POSITION.

**Comment by Andreyogld3d** [comment]
Ok, I Think it can be closed
