### ISSUE TITLE
SPIR-V Stream decoration requires GeometryStreams capability

### ISSUE THREAD

**Issue by dekimir** [KhronosGroup/glslang#151]
When the following geometry shader is compiled into SPIR-V, it decorates `out_color` with `Stream 0` but doesn't include `OpCapability GeometryStreams` as required by the SPIR-V spec:

```
#version 450
layout(triangles) in;
layout(triangle_strip, max_vertices = 3) out;
layout(location = 1) out vec4 out_color;
void main() {}
```

Similarly, in more complex shaders one can see `gl_PerVertex` and some nameless variables also decorated with `Stream` without including the requisite capability.

**Comment by johnkslang** [comment]
There are several missing capabilities.  I just added the following, including the one this issue requested:

```
CapabilityGeometryPointSize
CapabilityTessellationPointSize
CapabilityClipDistance
CapabilityCullDistance
CapabilityMultiViewport
CapabilityTransformFeedback
CapabilityGeometryStreams
CapabilityDerivativeControl
CapabilityInterpolationFunction
```

And am opening issue #152 for the remaining ones, which are mostly sampling related.  If this addresses this issue, close.  If this has more to do with not issuing stream 0 or something else, let's change the title or add a new issue.
