### ISSUE TITLE
Missing selection merge for a branch inside a loop

### ISSUE THREAD

**Issue by MaikKlein** [KhronosGroup/glslang#1519]
```
float test(float[2] arr) {
    uint i = 0;
    float sum = 42;
    while(i < arr.length()) {
        sum += 1.0;
        i+=1;
    }
    return sum;
}
```

This produces the following cfg

![](https://camo.githubusercontent.com/9abb2d78fe90cfe03c0ff69d89821bb3676416a3/68747470733a2f2f692e696d6775722e636f6d2f4844484c38446d2e706e67)

Block `25` doesn't have a `OpSelectionMerge` instruction.
The validator is silent and it seems to work, but is this actually correct?

**Comment by johnkslang** [comment]
Not all conditional branches need OpSelectionMerge.  OpSelection merge is for introduction of something if-then-else, where existing converged control flow will split and go two different directions, to later reconverge again at the merge blocks.  The branches that cause that reconvergence are not new introductions of selection constructs.  We are internally working on making this more clear in the specification language.

**Comment by MaikKlein** [comment]
@johnkslang Thanks for the clarification, that makes sense. Is there a place where I can ask questions about SPIR-V if the spec is a bit vague? Maybe I should open issues at https://github.com/KhronosGroup/Vulkan-Docs?

**Comment by johnkslang** [comment]
Yes, you can post at https://github.com/KhronosGroup/SPIRV-Headers.

**Comment by MaikKlein** [comment]
Thanks!
