### ISSUE TITLE
Missing checks for emitting OpCapability for several capabilities

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#152]
The following capabilities still need to be tested for and have `OpCapability` emitted:

```
Float64
ImageCubeArray
SampledCubeArray
SampleRateShading
ImageRect
SampledRect
InputAttachment
SparseResidency
MinLod
Sampled1D
Image1D
SampledCubeArray
SampledBuffer
ImageBuffer
SampledBuffer
ImageMSArray
StorageImageExtendedFormats
ImageQuery
StorageImageReadWithoutFormat
StorageImageWriteWithoutFormat
```

**Comment by yavn** [comment]
Hi, this could be expanded with a few more, e.g. `Float64` and similar.
At least I've noticed when I use doubles (`OpTypeFloat 64`) this capability isn't emitted.

**Comment by johnkslang** [comment]
Int16, Int64, Float16, and Float64 are handled by 3c52207e8aa67548a2aca489e16f1d845de4a8e9.

b0364dcc3e5e110ad8ef9a938a0cbf2dd9003122 picks up

```
SampledBuffer
ImageBuffer
Sampled1D
Image1D
SampledCubeArray
ImageCubeArray
SampledRect
ImageRect
InputAttachment
ImageMSArray
StorageImageMultisample
```

That leaves:

```
SampleRateShading
SparseResidency
MinLod
StorageImageExtendedFormats
ImageQuery
StorageImageReadWithoutFormat
StorageImageWriteWithoutFormat
```

**Comment by johnkslang** [comment]
SampleRateShading, SparseResidency, MinLod, and ImageQuery added by 5e80113939d0e9591f1fa4e4c2dd9a1559d7e1b8.

StorageImageExtendedFormats, StorageImageReadWithoutFormat, and StorageImageWriteWithoutFormat add by 5d0fa9781bb9f17bab14a35b12c192c4fc93f5e2.
