### ISSUE TITLE
NV_geometry_shader_passthrough shaders failing validation

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1521]
The SPIR-V validator added execution mode checks. 
https://github.com/KhronosGroup/SPIRV-Tools/pull/1940 

These new checks are failing for 3 geometry shaders in the Glslang test suite.
Example log at https://source.cloud.google.com/results/invocations/76118169-d154-4097-a7a4-b5b3bf7cf06e/log 

Details are:
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_GeometryShaderPassthrough_geom, where GetParam() = "spv.GeometryShaderPassthrough.geom"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_GeometryShaderPassthrough_geom, where GetParam() = "spv.GeometryShaderPassthrough.geom"
[  FAILED  ] Glsl/CompileVulkanToSpirvTestNV.FromFile/spv_meshTaskShader_task, where GetParam() = "spv.meshTaskShader.task"

The detail on the first one is:

@@ +1,7 @@
 spv.GeometryShaderPassthrough.geom
+error: SPIRV-Tools Validation Errors
+error: Geometry execution model entry points must specify exactly one of OutputPoints, OutputLineStrip or OutputTriangleStrip execution modes.
+  OpEntryPoint Geometry %main \"main\" %_ %__0
+

The first part of the base result in the test suite is:

                              Capability Geometry
                              Capability GeometryShaderPassthroughNV
                              Extension  "SPV_NV_geometry_shader_passthrough"
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Geometry 4  "main" 10 14
                              ExecutionMode 4 Triangles
                              ExecutionMode 4 Invocations 1
                              ExecutionMode 4 OutputVertices 3
                              Source GLSL 450
                              SourceExtension  "GL_NV_geometry_shader_passthrough"

I don't know if code generation is incorrect or if the rule needs to be relaxed for such shaders.

The extension spec does not say the rule should be relaxed.

http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_geometry_shader_passthrough.html 

@johnk and @dgkoch please take a look.

This problem is causing Shader bots to fail because Shaderc uses latest SPIRV-Tools.  Glslang would eventually see this failure when it updates its SPIRV-Tools.

Cc: @Kangz

**Comment by dgkoch** [comment]
This sounds like Issue 1) of the VK_NV_geometry_shader_passthrough spec: 
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_geometry_shader_passthrough

----
1) Should we require or allow a passthrough geometry shader to specify the output layout qualifiers for the output primitive type and maximum vertex count in the SPIR-V?

RESOLVED: Yes they should be required in the SPIR-V. Per GL_NV_geometry_shader_passthrough they are not permitted in the GLSL source shader, but SPIR-V is lower-level. It is straightforward for the GLSL compiler to infer them from the input primitive type and to explicitly emit them in the SPIR-V according to the following table.

Input Layout | Implied Output Layout
-- | --
points | layout(points, max_vertices=1)
lines | layout(line_strip, max_vertices=2)
triangles | layout(triangle_strip, max_vertices=3)
---

I'm guessing glslang is missing the bit that infers the execution mode from the input layout?

**Comment by dgkoch** [comment]
The 3rd error is related to task shaders though: 

 spv.meshTaskShader.task
+error: SPIRV-Tools Validation Errors
+error: Execution mode can only be used with a Kernel, GLCompute or MeshNV execution model.
+  OpExecutionMode %main LocalSize 32 1 1
+

and looking at Tests/spv.meshTaskShader.task it does appear to incorrectly have 
  layout(local_size_x = 32) in;
in it.

**Comment by dneto0** [comment]
> The 3rd error is related to task shaders though:

Right. My foggy brain got it wrong.  So the third issue would be fixed by a deleting that line from the test.

**Comment by dneto0** [comment]
I forked #1522 for the task shader LocalSize problem.  I'm keeping this issue focused on the geometry shader execution mode for outputs.

**Comment by johnkslang** [comment]
Meta thing though, glslang itself sees ~80 validation issues, but just logs them and looks for changes, it doesn't consider them failures on their own, until after deeper investigation about root cause.

**Comment by johnkslang** [comment]
FYI, I'm also having troubles adding layer and viewport index interface changes this week, and am a bit worried about these things in general. We are discussing internally.

**Comment by chaoc** [comment]
Yes, I agree the glslang needs to generate SPIR-V with explicit output primitives that match the input primitives. I'll push a MR for this soon. 

It also looks like we should add a rule in the spirv-validator that on NV_geometry_shader_passthrough checks for the matching of following three:
intput primitives, 
output primitives,
max output vertices. 

I'll create a MR for that to spirv-tools.

**Comment by chaoc** [comment]
This is fixed in https://github.com/KhronosGroup/glslang/pull/1524. Proposing to close.

**Comment by johnkslang** [comment]
@dneto0 can we close now?

**Comment by dneto0** [comment]
Confirmed this is fixed in latest Glslang with latest SPIRV-Tools validator.
