### ISSUE TITLE
NV Task shaders should not have LocalSize execution mode

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1522]
This is forked from #1521 

LocalSize execution mode is not defined for task shaders.  See http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_mesh_shader.html

Two things to fix here:

1.  Remove the local size qualifier from  Tests/spv.meshTaskShader.task i
layout(local_size_x = 32) in;

2. When I do that, the SPIR-V output still has a default LocalSize execution mode in it:

 
```     
                               MemoryModel Logical GLSL450
                               EntryPoint TaskNV 4  \"main\" 11 17 80 101
-                              ExecutionMode 4 LocalSize 32 1 1
+                              ExecutionMode 4 LocalSize 1 1 1
                               Source GLSL 450
```

SPIR-V code generation should not generate that execution mode. 

cc: @dgkoch

**Comment by dgkoch** [comment]
My bad - @sparmarNV pointed out that according to the GLSL spec we do support local_size_* in task shaders.  Looks like there's a bug in the SPIRV spec instead (and I guess that flows into the json grammar and then validator..).

**Comment by nvpbrown** [comment]
Yes, "local_size_x" is legal in task shaders.  It appears that edits the table of new layout qualifiers in Section 4.4 of the GLSL spec got this wrong, and this error ended up propagating to the SPIR-V specification.

A local work group size is required for both mesh and task shaders, though the GLSL specification inherits the same default behavior as in GLSL compute shaders:

> The local_size_x, local_size_y, and local_size_z qualifiers are used to declare a fixed local group
> size by the compute shader in the first, second, and third dimension, respectively. **If a shader does
> not specify a size for one of the dimensions, that dimension will have a size of 1.**

I'm not sure how this "default" work group size requirement translates to the SPIR-V interface -- either the SPIR-V producer must produce a work group size or the consumer needs to have a default size.  I presume mesh/task will want to do exactly what compute shaders did in this area.

**Comment by nvpbrown** [comment]
The GLSL spec fix can be found in the following pull request:

https://github.com/KhronosGroup/GLSL/pull/28

**Comment by johnkslang** [comment]
Closing, as glslang is working correctly. 

I don't think this impacts the JSON grammar, but does impact the validator.

Is there a validator bug open for this? Or, does the SPIR-V extension still need changes?

**Comment by dneto0** [comment]
Rev2 of the extension spec has the fix.  http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/NV/SPV_NV_mesh_shader.html

Needs a corresponding change to SPIRV-Tools validator.
