### ISSUE TITLE
gl_PerVertex block interface gets spurious XfbStride/XfbBuffer if XfbMode is active, even if it is not marked to capture

### ISSUE THREAD

**Issue by infapi00** [KhronosGroup/glslang#1526]
This is similar to issue #1185 but when gl_PerVertex is not re-declared (so added implicitly).

So for this shader:

> #version 450
> #extension GL_ARB_enhanced_layouts: require
> 
> layout(xfb_buffer = 2, xfb_offset = 0) out float x1_out;
> 
> void main() {
>    x1_out = 7.0;
>    gl_Position = vec4(0.0);
> }

And calling glslangValidator as:
> $glslangValidator -G --aml --amb implicit-glPerVertex.vert -o implicit-glPerVertex.vert.spv

The following SPIR-V is generated:

> ; SPIR-V
> ; Version: 1.0
> ; Generator: Khronos Glslang Reference Front End; 7
> ; Bound: 26
> ; Schema: 0
>                OpCapability Shader
>                OpCapability TransformFeedback
>           %1 = OpExtInstImport "GLSL.std.450"
>                OpMemoryModel Logical GLSL450
>                OpEntryPoint Vertex %main "main" %x1_out %_ %gl_VertexID %gl_InstanceID
>                OpExecutionMode %main Xfb
>                OpSource GLSL 450
>                OpSourceExtension "GL_ARB_enhanced_layouts"
>                OpName %main "main"
>                OpName %x1_out "x1_out"
>                OpName %gl_PerVertex "gl_PerVertex"
>                OpMemberName %gl_PerVertex 0 "gl_Position"
>                OpMemberName %gl_PerVertex 1 "gl_PointSize"
>                OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
>                OpMemberName %gl_PerVertex 3 "gl_CullDistance"
>                OpName %_ ""
>                OpName %gl_VertexID "gl_VertexID"
>                OpName %gl_InstanceID "gl_InstanceID"
>                OpDecorate %x1_out Location 0
>                OpDecorate %x1_out XfbBuffer 2
>                OpDecorate %x1_out XfbStride 4
>                OpDecorate %x1_out Offset 0
>                OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
>                OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
>                OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
>                OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
>                OpDecorate %gl_PerVertex Block
>                OpDecorate %_ XfbBuffer 0
>                OpDecorate %_ XfbStride 0
>                OpDecorate %gl_VertexID BuiltIn VertexId
>                OpDecorate %gl_InstanceID BuiltIn InstanceId
>        %void = OpTypeVoid
>           %3 = OpTypeFunction %void
>       %float = OpTypeFloat 32
> %_ptr_Output_float = OpTypePointer Output %float
>      %x1_out = OpVariable %_ptr_Output_float Output
>     %float_7 = OpConstant %float 7
>     %v4float = OpTypeVector %float 4
>        %uint = OpTypeInt 32 0
>      %uint_1 = OpConstant %uint 1
> %_arr_float_uint_1 = OpTypeArray %float %uint_1
> %gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
> %_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
>           %_ = OpVariable %_ptr_Output_gl_PerVertex Output
>         %int = OpTypeInt 32 1
>       %int_0 = OpConstant %int 0
>     %float_0 = OpConstant %float 0
>          %20 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
> %_ptr_Output_v4float = OpTypePointer Output %v4float
> %_ptr_Input_int = OpTypePointer Input %int
> %gl_VertexID = OpVariable %_ptr_Input_int Input
> %gl_InstanceID = OpVariable %_ptr_Input_int Input
>        %main = OpFunction %void None %3
>           %5 = OpLabel
>                OpStore %x1_out %float_7
>          %22 = OpAccessChain %_ptr_Output_v4float %_ %int_0
>                OpStore %22 %20
>                OpReturn
>                OpFunctionEnd

Note that on that one only x1_out gets the Offset, and that there is the xfb buffer/stride decorations without their related Offset.

**Comment by infapi00** [comment]
I have just edited the text. I have realized that the problem is not that the block is missing a Offset, in order to have the three Offset/XfbStride/XfbBuffer, but the problem is that is being set a XfbStride/XfbBuffer, when it shouldn't.

As soon as Xfb is active, those are added when it shouldn't. This started to happen after the fix for issue #1185. Note that one was trying to fix getting all the Xfb values if gl_PerVertex was redeclared and a xfb_offset was assigned. But if gl_PerVertex is implicit, or gl_PerVertex is redeclared but without a xfb_offset, it shouldn't be assigned a xfbbuffer/xfbstride. Even if Xfb Mode is active, as far as I understand the spec, gl_PerVertex should only be marked to be captured if a xfb_offset/buffer/stride is assigned to it explicitly.

**Comment by johnkslang** [comment]
So far, the only design put out for triggering XFB captures as that that happens only when an offset is supplied.  Stride and buffer should be irrelevant if there is no offset.

Maybe that needs to be revisited for Vulkan, and I have not fully understood your issue yet, but it reads somewhat as if XFB stride/buffer/offset should all appear together iff something is being captured. But, that is not how the OpenGL/GLSL design for this works, which is what the current implementation inherits.

**Comment by infapi00** [comment]
> So far, the only design put out for triggering XFB captures  as that that happens only when an offset is supplied.  Stride and  buffer should be irrelevant if there is no offset.

I have just re-checked ARB_gl_spirv spec, and I think that you are right.  Quoting just to have all the info here:

>     outputs specifying both an *XfbBuffer* and an *Offset* are captured, while outputs not specifying
>     both of these are not captured. Values are captured each time the shader
>     writes to such a decorated object."

It points that to be captured it needs both, but it is true that doesn't say that is an error using stride/buffer but no offset. 

> Maybe that needs to be revisited for Vulkan, and I have not fully understood your issue yet,

Basically, I'm working on the ARB_gl_spirv support for the Mesa driver. Recently, with the addition of the xfb vulkan extension, new code was added for xfb and vulkan, and I was trying to reuse part of it. Right now that code asserts if the stride and buffer is provided, but not the offset. Initially I assumed that it was a bug on glslang, but as you pointed, for OpenGL is not really needed. What I think we need to clarify what is the behaviour expected for Vulkan. Reading the new spec, there isn't too much about it. Sincerely, I think that the easier would be just have the same behaviour, and we could just close this issue, or keep it as a enhancement.

**Comment by johnkslang** [comment]
Agreed, and will close this one. If new specification language is created, making glslang incorrect, at that time we can open an issue specific to that new problem.
