### ISSUE TITLE
Setting CMAKE_DEBUG_POSTFIX to "d" breaks all CMake projects included after glslang

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/glslang#1540]
glslang's main CMake file sets global debug postfix to "d":
`set(CMAKE_DEBUG_POSTFIX "d" CACHE STRING "Adds a postfix for debug-built libraries.")`
This affects every single project processed after glslang in an unexpected and undesired way. If glslang wants to use this postfix, the variable should be local to glslang's source subtree and should not be global and visible to other projects.

**Comment by madwax** [comment]
I've been hit by this same problem in the past.  I ended up editing the CMakefiles but the proper way should be I think is add set_target_properties(glslang PROPERTIES DEBUG_POSTFIX "d") to glslang/CMakeLists.txt

**Comment by johnkslang** [comment]
PR #1676 removes it from the cache, which seems sufficient. Sorry for the delay.
