### ISSUE TITLE
Memory leak when compiling trivial shader

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/glslang#1554]
Below is the full source code that reproduces the issue (Windows desktop, MSVC, x64):

```cpp
static const char* SourceCode = 
R"(
Texture2D g_Texture;
SamplerState g_Texture_sampler;

struct PSInput 
{ 
    float4 Pos : SV_POSITION; 
    float2 uv : TEX_COORD; 
};

float4 main(PSInput ps_in) : SV_TARGET
{
    return g_Texture.Sample(g_Texture_sampler, ps_in.uv); 
}
)";

int C_DECL main(int argc, char* argv[])
{
    _CrtSetDbgFlag( _CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF );

    glslang::InitializeProcess();

    EShLanguage ShLang = EShLanguage::EShLangTessControl;
    glslang::TShader Shader(ShLang);
    TBuiltInResource Resources = glslang::DefaultTBuiltInResource;

    EShMessages messages = (EShMessages)(EShMsgSpvRules | EShMsgVulkanRules | EShMsgReadHlsl | EShMsgHlslLegalization);

    Shader.setEnvInput(glslang::EShSourceHlsl, ShLang, glslang::EShClientVulkan, 100);
    Shader.setEnvClient(glslang::EShClientVulkan, glslang::EShTargetVulkan_1_0);
    Shader.setEnvTarget(glslang::EShTargetSpv, glslang::EShTargetSpv_1_0);
    Shader.setHlslIoMapping(true);

    const char* ShaderStrings      [] = {SourceCode};
    Shader.setStrings(ShaderStrings, 1);

    Shader.setAutoMapBindings(true);
    auto ParseResult = Shader.parse(&Resources, 100, false, messages);

    printf("%s", Shader.getInfoLog());

    glslang::FinalizeProcess();
    return 0;
}
```

CRT output:

Detected memory leaks!
Dumping objects ->
{273106} normal block at 0x000002743FA84930, 8 bytes long.
 Data: <j       > 6A 0F 00 00 FF FF FF FF 

The leak goes away if I remove the texture:

```HLSL
float4 main(PSInput ps_in) : SV_TARGET
{
    return float4(1,1,1,1);//g_Texture.Sample(g_Texture_sampler, ps_in.uv); 
}
```

Every shader that uses textures leaks 8 bytes of memory no matter how many textures there are.

**Comment by DiligentGraphics** [comment]
@johnkslang. The source code I posted is the entire program. I don't even initialize Vulkan, so how can it be driver issue?

**Comment by johnkslang** [comment]
Okay, thanks. I would consider a "Vulkan backend" to be in a driver, while glslang is a front end, just wanted clarification.  I know it depends on your perspective what's a front end and what's a back end.

**Comment by DiligentGraphics** [comment]
Sorry about the confusion. Vulkan backend in the linked issue refers to the backend of the rendering engine that uses glslang to compile shaders, but I isolated the issue to just shader compilation.

**Comment by turol** [comment]
Unable to reproduce with Valgrind or ASAN under Linux. Tested against latest master branch. Either this has already been fixed, it's a Windows-only bug or it's a false positive from your tool.

**Comment by johnkslang** [comment]
We just fixed two leaks, and it looked like one could have been this, but I haven't taken the time yet to prove it.

Since it's verified gone, I will close this in a few days, unless someone else says they can reproduce it.

**Comment by DiligentGraphics** [comment]
I will verify it later today

**Comment by DiligentGraphics** [comment]
The issue is not reproducible in 6a9df5f48f0495b0aa05bad2f32f00f4d6fa5e59
