### ISSUE TITLE
Enabling HLSL functionality 1 makes validation layers complain

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/glslang#1555]
When I enable HLSL functionality 1: `Shader.setEnvTargetHlslFunctionality1()`, validation layers start to generate the following error message when creating shader modules:

Vulkan debug message (ERROR) [Validation] Code 5
Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: DecorateStringGOOGLE requires one of the following extensions: SPV_GOOGLE_decorate_string 

I am not sure where exactly this extension needs to be enabled. At least Vulkan Device on my machine with NV GTX970 GPU and recent driver does not list this extension.

**Comment by johnkslang** [comment]
If your driver does not have this functionality, you might need to strip it back out again before handing it to the driver (or not enabling it to begin with). I believe SPIRV-Tools has a stripper for this; @antiagainst do you know the details?

**Comment by antiagainst** [comment]
Yeah, spirv-opt has `--strip-reflect`.

**Comment by DiligentGraphics** [comment]
Thanks. I do need reflection data though for pipeline layout initialization, and I need this extension to initialize vertex input layout. After I strip reflection, do offsets in the bytecode that I obtained from spirv-cross remain valid?

**Comment by johnkslang** [comment]
Yes, stripping should not change any offset, only annotations that the driver might not recognize.

**Comment by DiligentGraphics** [comment]
Thanks for the suggestions, I believe that should work for me!
