### ISSUE TITLE
SPIRV-Tools asserts when specifying -fhlsl_functionality1

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/glslang#1561]
I am compiling simple shader below with [glslangValidator from build 2259](https://ci.appveyor.com/project/Khronoswebmaster/glslang/branch/master/job/gms08umv8wmw384l/artifacts):
```hlsl
struct PSInput 
{ 
    float4 Pos : SV_POSITION; 
    float2 uv : TEX_COORD; 
};

PSInput VSMain(float3 Pos : SV_POSITION,
               float2 uv : TEX_COORD) 
{
    PSInput ps; 
    ps.Pos = float4(Pos,1.0);
    ps.uv = uv;
    return ps;
}
```
When I use the following command line:
`glslangValidator.exe -V -e VSMain cube.vert.hlsl --hlsl-iomap --auto-map-bindings -fhlsl_functionality1`,
it crashes with the following error:
`Assertion failed: false, file C:\projects\glslang\External\spirv-tools\source\opt\aggressive_dead_code_elim_pass.cpp, line 733`
The same shader compiles fine if I don't specify `-fhlsl_functionality1` option

**Comment by johnkslang** [comment]
It looks like SPIRV-Tools is missing the case statement for `SpvOpMemberDecorateStringGOOGLE` in `AggressiveDCEPass::ProcessGlobalValues()`.  @antiagainst can you confirm this is a SPIRV-Tools hole?

**Comment by antiagainst** [comment]
Yep, I think so. + @s-perron

**Comment by s-perron** [comment]
Sure I'll take a look at it.

**Comment by DiligentGraphics** [comment]
@s-perron, @johnkslang I guess in this case it is just the matter of updating SPIRV-Tools as they just fixed it (https://github.com/KhronosGroup/SPIRV-Tools/issues/2019)

**Comment by s-perron** [comment]
The fix for spirv-tools has been merged.  I'll leave this issue open until glslang has been updated.

**Comment by arcady-lunarg** [comment]
Looks like this has been fixed a while ago.
