### ISSUE TITLE
BuiltIn ClipDistance variable needs to be a 32-bit float array. Member #2 of struct ID <10> is not an array.

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/glslang#1568]
I've embedded `glslang` in my Vulkan renderer so users can give me GLSL shaders. You can see the code I'm using to compile GLSL -> SPIR-V at https://github.com/NovaMods/nova-renderer/blob/rewrite/src/loading/shaderpack/shaderpack_loading.cpp#L335

I have a shader - https://github.com/NovaMods/nova-renderer/blob/rewrite/tests/resources/shaderpacks/DefaultShaderpack/shaders/textured_unlit.vert. When I compile that shader I get an error from the Vulkan validation layers:
```
[Validation] [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: According to the Vulkan spec BuiltIn ClipDistance variable needs to be a 32-bit float array. Member #2 of struct ID <10> is not an array.
  OpFunctionEnd
```

I've disassembled my SPIR-V. You can see it at https://pastebin.com/wf9L94yh. I don't know SPIR-V opcodes well enough to really understand it, but it doesn't look like `ClipDistance` is an array in my SPIR-V.

Is there something I'm doing wrong when I compile GLSL -> SPIR-V that is causing `glslang` to emit SPIR-V that's not quite valid?

This issue seems to be related to #325 and #315, but neither issue seems to have any resolution beyond "ClipDistance is hard to handle properly"

**Comment by DethRaid** [comment]
Oh forgot to mention: I'm building from source from commit https://github.com/KhronosGroup/glslang/commit/f0928b3f569c595737f812572b8279fdf0d27b47

**Comment by DethRaid** [comment]
Update: I've talked to a few people and learned that I need to link my shader to a program a la https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/driver/shaders/spirv/spirv_compile.cpp#L182-L202. Doing so doesn't cause the error.

The issue, then, is that `glslang` generated invalid SPIR-V when you try to generate SPIR-V from the intermediate representation of a shader. I'd like to see the intermediate representation of a shader and program have different types, so that the compiler can tell people like me when they're doing something wrong, but barring that I'd like to see some kinda of error message, instead of getting plausable but invalid SPIR-V

**Comment by arcady-lunarg** [comment]
As far as I can tell, having tried to reproduce the issue, the generated SPIR-V now handles ClipDistance correctly, generating it as an array and with no complaints from the SPIR-V validator. Please reopen this if you feel that there is still a problem that needs to be fixed though.
