### ISSUE TITLE
circular build dependency on pch.pch when using Ninja build tool, VS 2017

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1572]
https://source.cloud.google.com/results/invocations/c0c288dd-c2ae-41a9-a9ab-7f4b7daeca38/targets/graphics_shader_compiler%2Fshaderc%2Fwindows%2Fpresubmit_debug_2017/log 

From the log:

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

...

"Build glslang... Mon 11/12/2018 12:19:27.53"
ninja: warning: multiple rules generate pch.pch. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate pch.pch. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: error: dependency cycle: pch.pch -> third_party/glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/pch.cpp.obj -> cmake_order_depends_target_glslang -> third_party/glslang/hlsl/HLSLd.lib -> third_party/glslang/hlsl/CMakeFiles/HLSL.dir/hlslAttributes.cpp.obj -> pch.pch

[ID: 4256416] Build finished after 24 secs, exit value: 1

**Comment by dneto0** [comment]
cc: @jeffbolznv @dj2

**Comment by dj2** [comment]
Also happens on 2015 and 2013.

**Comment by dneto0** [comment]
I expect a patch shortly
