### ISSUE TITLE
OpLines incorrect for HLSL with #lines from multiple files

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#1575]
Execute the following on the files in the attached .zip:

glslangValidator.exe -D -V -e MainPs -g -o foo4.i.frag.spv foo4.i.frag

Notice that while the #line directives indicate that the source came from multiple files, the OpLines specify that all source came from foo4.frag.

[i2.zip](https://github.com/KhronosGroup/glslang/files/2574153/i2.zip)

**Comment by greg-lunarg** [comment]
@johnkslang  I am going to start looking at this.

**Comment by johnkslang** [comment]
Okay, thanks.

Note that each node tracks its location, including string number or compilation unit, but that no work has been done yet to map that through to OpLine support.
