### ISSUE TITLE
Tip of tree release hasn't been built since September

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/glslang#1584]
https://github.com/KhronosGroup/glslang/releases

**Comment by johnkslang** [comment]
As soon as the latest round of changes stabilizes, I will do that.

FYI, the most recent top-of-master build failure is a bot problem, not glslang.

**Comment by johnkslang** [comment]
Ah, I think there is a misunderstanding.

The bots keep reusing the same tag, so the date does not update. The master-tot is regularly updated with changes to master.

**Comment by johnkslang** [comment]
> As soon as the latest round of changes stabilizes, I will do that.

By this, I am referring to identifying and completing one of the stable releases.

**Comment by allanmac** [comment]
Ahhh... I was assuming the tag date was the build date.

**Comment by johnkslang** [comment]
I made a new stable release Nov. 15 and added dates to the names of the releases to reduce confusion with the tag-reuse date.
