### ISSUE TITLE
Incorrect use of SampleImplicitLod in non-fragment shader

### ISSUE THREAD

**Issue by amdrexu** [KhronosGroup/glslang#159]
If we use such statement in non-fragment shader, the texture() call will be translated to SampleImplicitLod.

texel = texture(samp1D, 1.0);

However, in SPIR-V spec, there are limitations of the use of SampleImplicitLod:

This instruction is only valid in the Fragment Execution Model.

So I wonder if we should use SampleExplicitLod with lod=0 for such texture() call when we detect the shader stage is not fragment shader.

**Comment by johnkslang** [comment]
Yes, fragment-shader only instructions should not be generated for non-fragment shaders. From the GLSL specification:  "...automatic level of detail is computed only for fragment shaders. Other shaders operate as though the base level of detail were computed as zero..." For SPIR-V, the front end should either translate to a non-lod form or an lod form taking 0 as the lod.

**Comment by amdrexu** [comment]
Thank you for your clarification. I will fix this issue later on.

**Comment by johnkslang** [comment]
This seems mainstream enough for a quicker fix.  Done with 019f08fcd8dc787a6b49a20a65fc4c890f822bcb.
