### ISSUE TITLE
No compiler error thrown when a non-constant ID is passed to subgroupBroadcast

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#1591]
From the GL_KHR_shader_subgroup spec:

    The function subgroupBroadcast() returns the <value> from the invocation
    whose <gl_SubgroupInvocationID> is equal to <id>.  <id> must be an integral
    constant expression.

However, putting in a non-constant expression works fine in GLSLang.  Incidentally, it also works fine in our driver so I could easily see shader authors (apparently myself included) mistaking `subgroupBroadcast` for `subgroupShuffle` and a compile error would significantly help.

**Comment by johnkslang** [comment]
I did not write this area, but the tests themselves don't use a constant, and are based on `gl_SubgroupInvocatioID`, which is `in`, not `const`, so I wonder if really the spec. is wrong instead.

@sheredom, do you know?

**Comment by johnkslang** [comment]
The fix, if it should be fixed, is shown in https://github.com/KhronosGroup/glslang/tree/subgroupBroadcast-const-id.

**Comment by sheredom** [comment]
So the way I wrote the spec it should be an integral constant expression.

Does your fix work for specialisation constants too?

**Comment by johnkslang** [comment]
> So the way I wrote the spec it should be an integral constant expression.

Right. But, the tests heavily rely on non-constants and would have to be rewritten, hence questioning what's appropriate, especially if the test pattern is a realistic one.

> Does your fix work for specialisation constants too?

That should work as it does generally, meaning yes, where specialization constants are a subclass of constants.

**Comment by sheredom** [comment]
Honestly I can't remember now why we required it to be an integral constant expression.

For what its worth HLSL only requires their equivalent WaveReadLaneAt to be uniform https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/wavereadlaneat

And on our implementation we only actually require it to be a uniform value.

**Comment by johnkslang** [comment]
The tests are written exclusively in terms of an `in`, so are not uniform. The `id` is:

`(gl_SubgroupInvocationID + gl_SubgroupSize) % 4`

**Comment by sheredom** [comment]
Right, so that should never have been valid for subgroupBroadcast - that is the differentiation between subgroupBroadcast and subgroupShuffle -> shuffle allows a fully dynamic id.

**Comment by johnkslang** [comment]
Okay, I will change the tests to use a constant.

**Comment by johnkslang** [comment]
Can you sign off on #1592?

**Comment by allanmac** [comment]
Broadcasting the last lane results in an error (using today's ToT glslang):

`subgroupBroadcast(value,gl_SubgroupSize - 1)`
`>>> ERROR: ... : 'id' : argument must be compile-time constant`

**Comment by jekstrand** [comment]
@allanmac, that's correct.  You really want to use `subgroupShuffle` in that case or use a specialization constant that you fill in from the physical device properties.

Also, be careful doing that as you don't know that the last lane is actually active.  Even in compute shaders, there is no guarantee that all lanes are active.

**Comment by johnkslang** [comment]
gl_SubgroupSize is not a constant. See https://github.com/KhronosGroup/GLSL/issues/19.

**Comment by allanmac** [comment]
Not being able to broadcast the final lane is unfortunate since a "prefix sum followed by a broadcast" is an very common compute idiom.  

It's creating more work for the developer to have to define what is essentially subgroupBroadcastLast().

**Comment by johnkslang** [comment]
These points should be made in https://github.com/KhronosGroup/GLSL/issues/19.
