### ISSUE TITLE
Missing glslang/pch.pch

### ISSUE THREAD

**Issue by mattparks** [KhronosGroup/glslang#1600]
After https://github.com/KhronosGroup/glslang/commit/0392544b7adddb20f9e14de078994c960f928e54 building with Microsoft Visual Studio 2017 results in this error:
```
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\c1xx : fatal error C1083: Cannot open source file: '(default)/Libraries/glslang/glslang/pch.pch': No such file or directory
```
I have glslang added as a submodule in a Libraries directory and added using add_subdirectory to the project.

**Comment by jeffbolznv** [comment]
IMO we should disable PCH for the Ninja build. I had to do that for other projects (spirv-tools and Vulkan CTS) for various reasons, one of which also had to do with the complexity of choosing the "right" directory for the PCH.
