### ISSUE TITLE
OpArrayLength generated with wrong result type.

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/glslang#1601]
With https://github.com/KhronosGroup/SPIRV-Tools/pull/2117, spirv-tools add check to validate OpArrayLength instructions.  One of the checks is that the result is an unsigned 32-bit integer.  This seems to cause failures for a few glslang test cases:

> [  FAILED  ] 6 tests, listed below:
> [  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_frag, where GetParam() = 16-byte object <2F-33 8B-00 00-00 00-00 35-19 91-00 00-00 00-00>
> [  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_byte_frag, where GetParam() = 16-byte object <64-33 8B-00 00-00 00-00 35-19 91-00 00-00 00-00>
> [  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_coherent_frag, where GetParam() = 16-byte object <A0-21 8B-00 00-00 00-00 35-19 91-00 00-00 00-00>
> [  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_rw_frag, where GetParam() = 16-byte object <D3-33 8B-00 00-00 00-00 35-19 91-00 00-00 00-00>
> [  FAILED  ] ToSpirv/HlslCompileTest.FromFile/hlsl_structbuffer_rwbyte_frag, where GetParam() = 16-byte object <ED-33 8B-00 00-00 00-00 35-19 91-00 00-00 00-00>
> [  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_310_comp, where GetParam() = "spv.310.comp"

The errors all seem to have the same message:

```
 error: SPIRV-Tools Validation Errors
-error: OpStore Pointer <id> '14[size]'s type does not match Object <id> '20's type.
-  OpStore %size %20
+error: The Result Type of OpArrayLength <id> '20' must be OpTypeInt with width 32 and signedness 0.
+  %20 = OpArrayLength %int %sbuf_0 0
```

I'm not sure exactly where the OpArrayLength is generated, but it is not correct.

**Comment by johnkslang** [comment]
GLSL defines array length as an int, so glslang needs to convert to match SPIR-V's unsigned type.  I'll have a look.

**Comment by arcady-lunarg** [comment]
Looks like OpArrayLength now uses the correct result type and bitcasts are inserted to make the signedness match on loads/stores.
