### ISSUE TITLE
Token concatenation (##) bug with token starting with digit

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/glslang#1605]
Here's a small example:

```
#version 450 core

#define TYPE_PREFIX image
#define TYPE_SUFFIX 1D

#define MAKE_TYPE_HELPER(type, suffix) type##suffix
#define MAKE_TYPE(type, suffix) MAKE_TYPE_HELPER(type, suffix)

#define RESOURCE_TYPE MAKE_TYPE(TYPE_PREFIX, TYPE_SUFFIX)

layout (set = 0, binding = 0, IMAGE_FORMAT) uniform writeonly RESOURCE_TYPE dest;

void main()
{
	imageStore(dest, 0, vec4(0));
}
```

The preprocessor output from glslang_validator (-E) is (some empty lines removed):

```
#version 450 core

layout(set = 0, binding = 0, IMAGE_FORMAT)uniform writeonly image1 D dest;

void main()
{
 imageStore(dest, 0, vec4(0));
}
```

As you can see, the intended `image1D` has turned into `image1 D` causing a compile error.

**Comment by johnkslang** [comment]
I was laying the groundwork to fix this in #1700, but it actually seems pretty ill-defined now.

Token pasting pastes together two "preprocessor tokens", where preprocessor tokens are things like literal numbers, identifier-like things, punctuation, etc. It pastes the one just before ## to the one just after ##.

"1D" is two preprocessor tokens: "1" and "D", so, at least from a portability perspective, I think you are expecting non-standard CPP behavior for ## to go past the "1" and also add the "D".

I am looking at special casing this: if the next preprocessor taken had no intervening space, keep pasting.  However, that would require, in the general case, retokenizing everything again.  In the following, where would you stop?

```
#define TYPE_SUFFIX 1D;++a
```

Currently, the pasting stops after the "1". It certainly seems wrong to include it all, but why keep the "1D" together, and, say, not the "1D;" together, when pasting?

**Comment by ShabbyX** [comment]
I think the issue is that you consider `1D` to be two tokens. To me, `1D` is one token for the same reason that `1u` or `1.0f` is one token. The fact that `D` is not a valid suffix is not something the preprocessor should be aware of (it's a semantic error, not even a parse error (let alone a lexer or preprocessor error)).

If you write this code in C:

    int x = 1abcd;

This is what you get with both `gcc` and `clang`:

    .....: error: invalid suffix "abcd" on integer constant
         int x = 1abcd;
 
Which means they both take `1abcd` as one token.

**Comment by johnkslang** [comment]
Yes, glslang does extra literal semantic processing while preprocessing. I can look next at the consequences of changing that to be more standard. That might be a more difficult path though than continuing to apply the ## into consecutive non-spaced tokens.
