### ISSUE TITLE
ToSpirv/HlslCompileTest.FromFile/hlsl_layout_frag generates PushConstant with BufferBlock decoration

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#1609]
Found via https://github.com/KhronosGroup/SPIRV-Tools/pull/2140. The validator started checking the rules for PushConstants in the Vulkan specification section 14.5.1. The test generates a variable for tbufname2 in the PushConstant storage class, but annotates the struct with the BufferBlock decoration (perhaps because it is also used as the type of a SSBO).

There are some other failures due to a formatting fix in a validation error that result from that change.

**Comment by johnkslang** [comment]
Is this a GLSL -> SPIR-V bug?  I can't tell. Do you have a shader you can share that translates to bad SPIR-V?

**Comment by alan-baker** [comment]
The glslang test mentioned in  title exercises this. It is HLSL -> SPIR-V.
```
layout(set=3,binding=5) tbuffer tbufName {
    layout(offset = 16) float4 v1;
};

layout(push_constant) tbuffer tbufName2 {
    float4 v5;
};

layout(constant_id=17) const int specConst = 10;

tbuffer tbufName2 : layout(set=4,binding=7) {
    layout(offset = 16) float4 v1PostLayout;
};

float4 PixelShaderFunction(float4 input) : COLOR0
{
    float4 layout = 2.0;
    return input + v1 + v5 + v1PostLayout * layout;
}
```

**Comment by johnkslang** [comment]
Okay, that's the file Test/hlsl.layout.frag.

Glslang does not provide an HLSL validator.

I'm not yet clear if the input is reasonable. We do have some ~80 validation failures, which still are semi-valid regression tests for glslang internal functionality. I don't know yet if this one should be taken as input to the user to modify their shader, or if it is really something glslang needs to deal with.

(That is, it is somewhat reasonable for the tests to use abusive forms of HLSL to test something. It is only valid HLSL workloads that should not trigger validation errors.)

**Comment by arcady-lunarg** [comment]
This code no longer causes SPIR-V validation failures. Closing this issue.
