### ISSUE TITLE
Vulkan memory model scope test fails validation

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#1610]
The test Glsl/CompileVulkanToSpirvTest.FromFile/spv_memoryScopeSemantics_comp fails validation using SPIRV-Tools (https://github.com/KhronosGroup/SPIRV-Tools/pull/2149)

```
 spv.memoryScopeSemantics.comp
+error: SPIRV-Tools Validation Errors
+error: Load: in Vulkan 1.0 environment Memory Scope is limited to Device, Workgroup and Invocation
+  %89 = OpLoad %uint %88 Volatile|MakePointerVisibleKHR|NonPrivatePointerKHR %uint_3
```

According to Appendix A of the Vulkan spec, this is error correct (though it omits QueueFamilyKHR as permissible in the text it does accept it).

This test should probably be targeting Vulkan 1.1. The SPV_KHR_vulkan_memory_model extension lists SPIR-V 1.3 as a required version.

@jeffbolznv should all the memory model tests generate SPIR-V 1.3?

**Comment by jeffbolznv** [comment]
Yeah, I think this means we just need to move that test into the CompileVulkan1_1ToSpirvTest batch?
