### ISSUE TITLE
Composite specialization constants need to be implemented.

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#163]
Scalar bool/int/float specialization constants are basically, working, as is gl_WorkgroupSize, but general case composites of these are not yet implemented.

Most likely, first, there is a front-end feature needed to track how a composite's subset is specialized, and then second, there should be a general translation of that to SPIR-V in the function createSpvSpecConstant().

**Comment by dneto0** [comment]
Here's a concrete example that I think illustrates what should compile, and how.

```
#version 450

layout(constant_id = 200) const float myfloat = 1.25;
layout(constant_id = 201) const int myint = 14;

struct structtype {
  float f;
  int i;
};

// This should have an initializer that is an OpSpecConstantComposite
const structtype outer_struct_var = { myfloat, myint };

// This should have an initializer that is an OpSpecConstantComposite
// (Similar to scVec example in https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt)
const vec2 myvec = vec2(myfloat, myfloat);

void main() { }

void outer_composite() {
  const float f = outer_struct_var.f;
  const float i = outer_struct_var.i;
}

void inner_composite() {
  // This should have an initializer that is an OpSpecConstantComposite
  const structtype inner_struct_var = { myfloat, myint };
}
```

Glslang errors out with the following:
ERROR: 0:12: 'const' : non-matching or non-convertible constant type for const initializer 
ERROR: 0:16: 'const' : non-matching or non-convertible constant type for const initializer 
ERROR: 0:27: 'const' : non-matching or non-convertible constant type for const initializer

**Comment by Qining** [comment]
Here is a simpler case in which 'SpecConstant' gets involved, but not yet supported.

Current `TIntermConstUnion`'s `ConstantUnionArray` doesn't support symbol-like elements, which are required so that we can have SpecConstants in the initializer list.

```
#version 450

layout(constant_id = 200) const float myfloat = 1.25;
layout(constant_id = 201) const int myint = 14;

const int myint2 = myint;

void main(){}
```

Hi @johnkslang, are you working on this or similar issues? We do have one issue filed in CTS repo, I wonder how is the progress.

Thanks,

**Comment by johnkslang** [comment]
Yes, I was going to look into this late this week.  I see you already started, will try sorting through that crossed with what I was doing.  I had commented some on design intent, which I think you may have seen.

**Comment by johnkslang** [comment]
These examples now work.
