### ISSUE TITLE
VS2013 build fails on Constant.cpp because cstdint types are not defined

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1630]
E.g.:

C:\PROGRA~2\MICROS~2.0\VC\bin\amd64\cl.exe   /nologo /TP -DAMD_EXTENSIONS -DENABLE_HLSL -DENABLE_OPT=1 -DGLSLANG_OSINCLUDE_WIN32 -DNV_EXTENSIONS -I..\third_party\glslang\glslang\.. /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MT /Zi /O2 /Ob1 /DNDEBUG   -w /showIncludes /Fothird_party\glslang\glslang\CMakeFiles\glslang.dir\MachineIndependent\Constant.cpp.obj /Fdthird_party\glslang\glslang\CMakeFiles\glslang.dir\ /FS -c T:\src\github\shaderc\third_party\glslang\glslang\MachineIndependent\Constant.cpp
cl : Command line warning D9025 : overriding '/W3' with '/w'
T:\src\github\shaderc\third_party\glslang\glslang\MachineIndependent\Constant.cpp(762) : error C2061: syntax error : identifier 'int8_t'
...

From Shaderc build log https://source.cloud.google.com/results/invocations/b003a8f9-7cb6-4f47-b993-a6b9c656f4ba/log

**Comment by johnkslang** [comment]
Note that if the recent casts added (e.g., `int8_t`) had actually used the types of the function parameters they were being cast to (e.g., `char`), this problem would not have happened, and `char` is accepted everywhere (when deciding these types in the past, `int8_t` was less portable in practice; maybe it's better today).

**Comment by johnkslang** [comment]
These types don't even match the function parameter types.

I look, and it is far less work to make glslang consistently use the same types in the direction of `char`, `short`, and `int`, ... than to go the other (possibly less portable, from past experience) direction of `int8_t`, `int16_t`, ....

So, I'd do the work to make it consistent.

I sincerely wish C++ really did have explicit-sized types, and would like glslang to move to those. But, not by having one block of code being inconsistent with all the rest, before C++ really has true types here. This is flaw is quite visible with literals and with error messages, even ignoring portability issues.
