### ISSUE TITLE
Invalid structured CFG generated from switch statement

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#1635]
[files.zip](https://github.com/KhronosGroup/glslang/files/2703328/files.zip)

Originally filed against SPIRV-Tools, https://github.com/KhronosGroup/SPIRV-Tools/issues/2213.

Shader source looks like:
```
void main()
{
 switch(_GLF_SWITCH(0))
  {
   case 0:
   if((gl_FragCoord.y < 0.0))
    {
     break;
    }
  }
}
```

The break from case 0 in the source is problematic because it is embedded within another selection.
![cfg](https://user-images.githubusercontent.com/33432579/50351055-fe8f5c80-050e-11e9-839c-272327d8bdcc.png)

The edge from 22 -> 9 is invalid.

**Comment by johnkslang** [comment]
Khronos has agreed this is a legal CFG, and future specifications should make this more clear.
