### ISSUE TITLE
MSYS2/MinGW, GCC: suggest parentheses for sameStructType

### ISSUE THREAD

**Issue by LigH-de** [KhronosGroup/glslang#1650]
Trying to compile [google/shaderc](https://github.com/google/shaderc) (which uses spirv-tools) in [MABS](https://github.com/jb-alvarado/media-autobuild_suite).

Default for GCC in MSYS2/MinGW is treating warnings as errors. This causes an error for an ambiguous boolean sequence:

```[10/28] Building CXX object libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o
FAILED: libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o 
E:\MABS\msys64\mingw32\bin\c++.exe  -DNV_EXTENSIONS -I../libshaderc_util/include -I../third_party/glslang -I../third_party/glslang/glslang/.. -I../third_party/glslang/SPIRV/.. -I../third_party/glslang/SPIRV/../External -I../third_party/spirv-tools/include -I../third_party/spirv-headers/include -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG   -Wall -Werror -fvisibility=hidden -std=c++11 -std=gnu++11 -MD -MT libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o -MF libshaderc_util\CMakeFiles\shaderc_util.dir\src\compiler.cc.o.d -o libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o -c ../libshaderc_util/src/compiler.cc
In file included from E:/MABS/build/shaderc-git/third_party/glslang/glslang/Include/intermediate.h:56:0,
                 from ../third_party/glslang/SPIRV/../glslang/MachineIndependent/localintermediate.h:42,
                 from ../third_party/glslang/SPIRV/SpvTools.h:47,
                 from ../third_party/glslang/SPIRV/GlslangToSpv.h:42,
                 from ../libshaderc_util/src/compiler.cc:29:
E:/MABS/build/shaderc-git/third_party/glslang/glslang/Include/Types.h: In member function 'bool glslang::TType::sameStructType(const glslang::TType&) const':
E:/MABS/build/shaderc-git/third_party/glslang/glslang/Include/Types.h:2006:44: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]
             isStruct() && right.isStruct() && structure == right.structure)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
```

**Comment by johnkslang** [comment]
>  an error for an ambiguous boolean sequence:

`&&` versus `||` is totally unambiguous, completely defined, and 100% portable. It works like 'and' and 'or' in English, as well as being just like * and + with numbers. So, it is a mistake on the toolchain's part if it claims this is a compile-time error regarding ambiguity. I wish the toolchain would be fixed as well.

Of course, we can work around this and add the parenthesis.

**Comment by johnkslang** [comment]
`&&` versus `==` is even more clear, and I doubt there is any warning/error about it.  This is about the `||` from the previous line. It was already recently fixed, so I will close this.

Side note: All this stuff is totally explicit and portable and clear from day 1 of C, from C`s original table of precedence order.  It does get more non-intuitive for `&` versus `==` versus `<<` and other more obscure things.

I don't mind making the code clearer with parentheses. There 100s of equivalent issues with C/C++ where a convention to make intent clearer helps. It just seems broken to me that of all those this one is the error.
