### ISSUE TITLE
CMake bug breaks cross compiled builds with pthreads

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/glslang#1651]
Following on from #1624 the build is now running into a CMake issue [1] that prevents cross-compilation. I suggest that we work around it by falling back to the old method of linking pthreads when cross compiling.

[1] https://gitlab.kitware.com/cmake/cmake/issues/16920

**Comment by johnkslang** [comment]
I merged the PR, trusting it closes this. If not, reopen.
