### ISSUE TITLE
Fix double log2()? Best to stay integer, at minimum use a cast to avoid warning.

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#1653]
See: https://github.com/KhronosGroup/glslang/blob/dfaaf75a31daacce212f11c7b1a9eca0c996a25c/glslang/MachineIndependent/ParseHelper.cpp#L5065

It wants an integer log2 of an integer, but the std function returns a double.

Is there an alternative that stays in the integer domain? (Obviously, a cast could be added, but I don't think doing `double` arithmetic is needed to begin with.)

@jeffbolznv

**Comment by ratchetfreak** [comment]
C++20 has [std::log2pl](https://en.cppreference.com/w/cpp/numeric/log2p1)

otherwise I believe you'll need to implement it yourself using a [bit-twiddle formula](https://graphics.stanford.edu/~seander/bithacks.html#IntegerLogObvious) or an intrinsic.

**Comment by jeffbolznv** [comment]
std::log2 should return an exact answer for power of two input, and this is off the fast path, so IMO we should just add a cast if needed to silence any compiler warnings.
