### ISSUE TITLE
Incorrect gl_PrimitiveIndicesNV[] size

### ISSUE THREAD

**Issue by flisgd** [KhronosGroup/glslang#1659]
According to GLSL_NV_mesh_shader specification: 

The intrinsically declared array gl_PrimitiveIndicesNV[] will be sized according to the primitive type and "max_primitives" declarations, where the size is:
    * the value of "max_primitives" if "points" is declared
    * two times the value of "max_primitives" if "lines" is declared, or
    * three times the value of "max_primitives" if "triangles" is declared.

The following shader causes compilation error:

#version 450
#extension GL_NV_mesh_shader : require
layout(local_size_x=4) in;
layout(max_vertices=4, max_primitives=2, triangles) out;
void main() {
    vec4 triangleData[] = {  vec4(-1.0f, -1.0f, 0.0f, 1.0f), vec4(-1.0f, 1.0f, 0.0f, 1.0f), vec4( 1.0f, 1.0f, 0.0f, 1.0f), vec4( 1.0f, -1.0f, 0.0f,	1.0f) };
    gl_PrimitiveCountNV = 2;
    uint localInvocation = gl_LocalInvocationID.x;
    gl_MeshVerticesNV[localInvocation].gl_Position = triangleData[localInvocation];
	if (localInvocation == 0) {
		//first triangle
		gl_PrimitiveIndicesNV[0]= 0;
		gl_PrimitiveIndicesNV[1]= 1;
		gl_PrimitiveIndicesNV[2]= 2;
		//second triangle
		gl_PrimitiveIndicesNV[3]= 0;
		gl_PrimitiveIndicesNV[4]= 2;  // <---------- ERROR
	}
}

> ERROR: 0:20: 
'
[
'
 :  array index out of range 
'
4
'
ERROR: 0:20: 
'
'
 : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

**Comment by johnkslang** [comment]
@dgkoch any input on this?

**Comment by dgkoch** [comment]
Seems like a glslang bug. I agree with the spec interpretation. 

@sparmarNV is going to take a look.

**Comment by sparmarNV** [comment]
Here is the PR which should correctly resize gl_PrimitiveIndicesNV to "max_primitives x <geometrySize>":
https://github.com/KhronosGroup/glslang/pull/1697

**Comment by sparmarNV** [comment]
@flisgd - the fix has been merged into master. Feel free to verify and close this issue. Thanks.
