### ISSUE TITLE
Cache for builtin symbol tables not sensitive to spv or vulkan parameters

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#166]
In ShaderLang.cpp, the function
```
void SetupBuiltinSymbolTable(int version, EProfile profile, int spv, int vulkan)
```
sets up symbol tables for builtin functions.  It remembers which symbol tables it has set up, based on version and profile, and returns early if the tables have already been created.  This can save a lot of time when doing repeated compiles.
However, this scheme is insensitive to the spv or vulkan settings.  So if you're not careful, you can get invalid symbol tables when switching between spv and not-spv, or vulkan and not-vulkan.

We worked around this in Shaderc, but that workaround is fragile.  The real fix is to make the caching scheme in SetupBuiltinSymbolTable sensitive to the spv and vulkan parameters.

**Comment by johnkslang** [comment]
Yes, if a single instance of glslang will be used for multiple API's, then we need to include the vulkan version as part of the cached key.

First, need to formalize better what the vulkan and spv versions are, so there can be a formal mapping between them and the cache key.  E.g., do they look like 100, 110, etc.?

**Comment by dneto0** [comment]
I believe this has already been fixed, via
 - b901ade058 which consolidated the "spv" and "vulkan" parameters into  an SpvVersion struct parameter to SetupBuiltinSymbolTable, and then
 - 10119719 to make the builtin table cache sensitive to SpvVersion
Thanks!

**Comment by johnkslang** [comment]
Agreed.  I failed to see the connection to this issue when fixing it.
