### ISSUE TITLE
input/output mismatch of HLSL vertex shader and geometry shader

### ISSUE THREAD

**Issue by zhaijialong** [KhronosGroup/glslang#1660]
The following vertex and geometry shader works well on D3D, but generated some validation errors for Vulkan.

```
struct VS_STAR_INPUT
{
	float4 iPos : POSITION0;
	float4 iColor : COLOR0;
};

struct VS_STAR_OUTPUT
{
	float4 oPos : POSITION0;
	float4 oColor : COLOR0;
	float2 oSize : TEXCOORD1;
};

VS_STAR_OUTPUT vs_main_star(VS_STAR_INPUT input)
{
	VS_STAR_OUTPUT output;
	output.oPos = input.iPos;
	output.oColor = float4(1.0, 1.0, 1.0, 1.0);
	output.oSize = float2(1.0, 1.0);
	
	return output;
}

struct GS_STAR_OUTPUT
{
	float4 oPos : SV_POSITION;
	float2 oTex	: TEXCOORD0;
	float4 oColor : COLOR0;
};

[maxvertexcount (4)]
void gs_main_star(point VS_STAR_OUTPUT In[1], inout TriangleStream<GS_STAR_OUTPUT> triStream)
{
	for(int v = 0; v < 4; v ++)
	{   
		GS_STAR_OUTPUT Out;
	
		Out.oPos = In[0].oPos * In[0].oSize.x;
		Out.oTex = float2(1.0, 1.0);
		Out.oColor = In[0].oColor;
	
		triStream.Append(Out);
	}
	triStream.RestartStrip();
}
```

```
Type mismatch on location 0.0: 'ptr to output vec4 of float32' vs 'ptr to input arr[1] of struct of (vec4 of float32, vec4 of float32, vec2 of float32)'
vertex shader writes to output location 1.0 which is not consumed by geometry shader
vertex shader writes to output location 2.0 which is not consumed by geometry shader
```

Looks like the generated spir-v of geometry shader doesn't flatten the input struct, so the vertex shader has 3 output, but geometry shader only have 1 input.

**Comment by zhaijialong** [comment]
@johnkslang I can confirm the problem also exists for VS-HS combine, as #1197 reported. 
So currently the TS and GS of HLSL are not ready to use?
I think these bugs should have a high priority, really hope you can fix them soon, thank you so much !

**Comment by dfranx** [comment]
@johnkslang is there an update to this issue? ETA? Or at least some function to manually flatten the input struct in the geometry shader?

I am facing the same issue. The output of the vertex shader is flattened normally while the input of geometry shader is a non-flattened structure.

**Comment by danginsburg** [comment]
Also hitting this on all our HLSL VS/GS combos: 

```
VK ERROR : VALIDATION - Message Id Number: 0 | Message Id Name: UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch
	Type mismatch on location 0.0: 'ptr to output vec3 of float32' vs 'ptr to input arr[3] of struct of (vec3 of float32, vec3 of float32, vec3 of float32, vec3 of float32, vec3 of float32, vec2 of float32, vec4 of float32, uint32)'

	Objects - 1
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 5AC22F0000007E14, Name "vr_hud_panel.vfx_vs"
```

I can provide examples if needed.

**Comment by greg-lunarg** [comment]
Dxc is splitting out all of the members of the input struct, not just the builtins. It is also array-ing all members, both non-builtins as well as builtins.

Is there a reason not to split out all members? I seem to recall that @LoopDawg had made a conscious effort to not split out non-builtins, but I don't remember why.

I am going to pursue adding this policy to glslang unless someone can think of a reason not to.

**Comment by greg-lunarg** [comment]
There are a number of related issues from this time period, some containing comments by @LoopDawg. I will review all that before writing any code.
