### ISSUE TITLE
__fastcall causing warnings on x86_64 builds

### ISSUE THREAD

**Issue by jamesdolan** [KhronosGroup/glslang#1665]
ShaderLang.h is throwing warnings on x86_64 builds for the `ShFinalize()` function due to fastcall being ignored on non-x86 builds with GCC 8.2.0.

Since it's the only function to specify the calling convention and it seems unnecessary to specify fastcall for that function, can it just be removed?

**Comment by johnkslang** [comment]
These are out-of-date now. I'll remove them.
