### ISSUE TITLE
In Vulkan mode the default execution mode should be OriginUpperLeft

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/glslang#167]
Appendix `A.3` of the Vulkan specs says:

> The OriginLowerLeft execution mode must not be used; fragment entry points must declare OriginUpperLeft. 

But when you compile a shader that doesn't specify an origin it is set to `OriginLowerLeft` by default, even with the `-V` flag.

**Comment by johnkslang** [comment]
Is that true even after the KHR_vulkan_glsl push?  That should have made the default for GLSL be origin_upper_left.

(Though, it wouldn't have to; not making that the GLSL default would just mean you have to explicitly say origin_upper_left in your GLSL to get valid Vulkan SPIR-V.  OpenGL, for example, might keep the GLSL default the other way.)

**Comment by Aatch** [comment]
Looks like there's an `OriginUpperLeft` for fragment entry points now.
