### ISSUE TITLE
Assertion failed: (nIndex != OS_INVALID_TLS_INDEX), function OS_GetTLSValue

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/glslang#1670]
I see a crash in `OS_GetTLSValue`, line 148: 

`Assertion failed: (nIndex != OS_INVALID_TLS_INDEX), function OS_GetTLSValue, file glslang/glslang/OSDependent/Unix/ossource.cpp, line 148.`

Stack trace:

```
#0	0x00007fff7467db66 in __pthread_kill ()
#1	0x0000000104e0d0f0 in pthread_kill ()
#2	0x00007fff745d91ae in abort ()
#3	0x00007fff745a11ac in __assert_rtn ()
#4	0x0000000100dad962 in glslang::OS_GetTLSValue(void*) at git/DiligentEngine/DiligentCore/External/glslang/glslang/OSDependent/Unix/ossource.cpp:148
#5	0x0000000100c5ace0 in glslang::GetThreadPoolAllocator() at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/PoolAlloc.cpp:49
#6	0x0000000100cac071 in glslang::TBuiltIns::operator new(unsigned long) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/Initialize.h:84
#7	0x000000010327dde8 in (anonymous namespace)::CreateBuiltInParseables(TInfoSink&, glslang::EShSource) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/ShaderLang.cpp:87
#8	0x000000010327cecc in (anonymous namespace)::InitializeSymbolTables(TInfoSink&, glslang::TSymbolTable**, glslang::TSymbolTable**, int, EProfile, glslang::SpvVersion const&, glslang::EShSource) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/ShaderLang.cpp:307
#9	0x000000010327a95c in (anonymous namespace)::SetupBuiltinSymbolTable(int, EProfile, glslang::SpvVersion const&, glslang::EShSource) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/ShaderLang.cpp:442
#10	0x00000001032772ed in bool (anonymous namespace)::ProcessDeferred<(anonymous namespace)::DoFullParse>(TCompiler*, char const* const*, int, int const*, char const* const*, char const*, EShOptimizationLevel, TBuiltInResource const*, int, EProfile, bool, bool, EShMessages, glslang::TIntermediate&, (anonymous namespace)::DoFullParse&, bool, glslang::TShader::Includer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, glslang::TEnvironment const*) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/ShaderLang.cpp:888
#11	0x000000010326c927 in (anonymous namespace)::CompileDeferred(TCompiler*, char const* const*, int, int const*, char const* const*, char const*, EShOptimizationLevel, TBuiltInResource const*, int, EProfile, bool, bool, EShMessages, glslang::TIntermediate&, glslang::TShader::Includer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, glslang::TEnvironment*) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/ShaderLang.cpp:1251
#12	0x000000010326ea10 in glslang::TShader::parse(TBuiltInResource const*, int, EProfile, bool, bool, EShMessages, glslang::TShader::Includer&) at git/DiligentEngine/DiligentCore/External/glslang/glslang/MachineIndependent/ShaderLang.cpp:1797
#13	0x0000000102cc2361 in glslang::TShader::parse(TBuiltInResource const*, int, EProfile, bool, bool, EShMessages) at git/DiligentEngine/DiligentCore/Graphics/GLSLTools/../../External/glslang/SPIRV/../glslang/MachineIndependent/../Public/ShaderLang.h:543
#14	0x0000000102cc19a2 in glslang::TShader::parse(TBuiltInResource const*, int, bool, EShMessages) at git/DiligentEngine/DiligentCore/Graphics/GLSLTools/../../External/glslang/SPIRV/../glslang/MachineIndependent/../Public/ShaderLang.h:549
#15	0x0000000102cb859e in Diligent::CompileShaderInternal(glslang::TShader&, EShMessages, glslang::TShader::Includer*, char const*, unsigned long, Diligent::IDataBlob**) at git/DiligentEngine/DiligentCore/Graphics/GLSLTools/src/SPIRVUtils.cpp:328
```

The issue only happens on Mac and only when glslang runs in a shared library. Before crash, the control enters the same function few times, all without leaving `TShader::Parse` and `nIndex` is valid. But then it is null.

**Comment by TheMostDiligent** [comment]
@johnkslang 
This issue is still reproducible and is now a blocker for our project: glslang can't be distributed in a dylib on Mac. Maybe you can suggest what to look at and give an idea of why this may be happening?

**Comment by TheMostDiligent** [comment]
I am trying to debug the problem and I noticed that the address of the global variable `PoolIndex` changes when the flow enters the `GetThreadPoolAllocator` function for the third time. I don't know under what circumstances an address of the global variable can change, but maybe you can suggest?

**Comment by TheMostDiligent** [comment]
The issue with address change gave a good hint to what was happening: glslang was linked into the shared library and into the main application as well, but since the symbols are not hidden, they were leaking into the global scope, and the linker was randomly using functions from different implementations. Enforcing hidden visibility fixed the problem.

Currently, glslang uses [hidden visibility](https://github.com/KhronosGroup/glslang/blob/3ce148638bdc3807316e358dee4a5c9583189ae7/CMakeLists.txt#L298) only when building as shared library. However, when it is built as a static library and linked into a shared, the symbols leak out. I don't think there is a reason to not always set visibility to hidden.

**Comment by GrapixLeGrand** [comment]
Hello,

Could you specify how you fixed the issue? I ran into the same. I'm compiling Glslang as a shared library in my project and it seems that the visibility is set to hidden on the glslang target but I also get exactly the same error as you.

Thanks in advance and best regards,
Quentin

**Comment by TheMostDiligent** [comment]
> Could you specify how you fixed the issue?

https://github.com/KhronosGroup/glslang/issues/1670#issuecomment-732360137

**Comment by GrapixLeGrand** [comment]
Thanks a lot for the quick response! In fact, My problem was simply due to the fact that I forgot to call `ShInitialize` before compiling the shader. This also led to the PoolIndex being null. 
Thanks and best regards.
Quentin

**Comment by abbaswasim** [comment]
I am having the same issue when built as shared library although there is [this]( https://github.com/KhronosGroup/glslang/blob/3ce148638bdc3807316e358dee4a5c9583189ae7/CMakeLists.txt#L298) fix which still doesn't help.

My use case is linking Glslang with a framework that is linked into an application and I am getting the assertion. If I force link it statically instead with the framework then I don't have the issue.

**Comment by TheMostDiligent** [comment]
@abbaswasim I have always had hard times trying to make `-fvisibility=hidden` work as expected.

**Comment by arcady-lunarg** [comment]
In the case of building a static library, the concept of hidden visibility doesn't really exist. If a shared library includes glslang as a static library dependency, it's up to the shared library to control the visibility of glslang's symbols. This problem can also be solved by building a shared library version of glslang, in which case it won't be linked multiple times and you wouldn't have symbol collisions. The experience of building and using glslang as a shared library has been rather less than optimal in the past, but there is work ongoing to fix that, including merging everything into a single library file and hiding symbols that aren't meant to be public.

**Comment by TheMostDiligent** [comment]
@arcady-lunarg this problem does not reproduce for us anymore, so this issue can be closed now.
