### ISSUE TITLE
how to compile a shader with old version? [glsl][question]

### ISSUE THREAD

**Issue by raytracinger** [KhronosGroup/glslang#1673]
Hi all,

I am compiling a shader with old version, command> "glslangValidator  shader.frag  -G --aml"
, but the the compiler report the issue: 
"ERROR: #version: Desktop shaders for OpenGL SPIR-V require version 330 or higher",
I wonder is the glslang able to compile the shader with the version lower than 330 ?  

Thanks

#version 130
in vec4 Color;
in vec4 texColor0;
in vec4 texColor1;
out vec4 FragColor;

void main()
{
    FragColor = Color + texColor0 + texColor1;
}

**Comment by johnkslang** [comment]
That reflects the required minimum `#version 140` from the GL_KHR_vulkan_glsl specification.

Could you change 130 -> 140?
