### ISSUE TITLE
Error on #include for glslangValidator inside shader file

### ISSUE THREAD

**Issue by Hersir88** [KhronosGroup/glslang#1691]
Hi I have two glsl files next to each other `test.vert` and `utils.vert`.

I added include statement inside `test.vert`.
```
#extension GL_GOOGLE_include_directive : enable
#include "utils.vert"
```

But get error all the time:
```
'#include' : Could not process include directive for header name: utils.vert
```

I am missing something or this is not supported ?

Thank you

**Comment by johnkslang** [comment]
For the command line, try including `-l` to say you are linking a full stage. I think that's the only path in the standalone executable that sets up #include.

**Comment by Hersir88** [comment]
@johnkslang thanks this helped now includes work as expected.

Some side question is it possible in command line to enable `GL_GOOGLE_include_directive` so its not needed to write in every file ?

**Comment by johnkslang** [comment]
I it could be added, but...

As a reference validator for the Khronos standard, it is not supposed to perform non-normatively. A command-line option like "--I-know-it-is-not-normative-include-anyway" could work, but then your code would not be portable to other front ends that obey that standard.  If it's just for SPIR-V generation it's more understandable, but for normal OpenGL use, there are a large number of front ends, and glslangValidator is supposed to give errors on non-normative use.

**Comment by Hersir88** [comment]
I use glslang only for validation purpose and do include replace with manual script, but ok I can manually copy file, add that line and then pass that temp file to glslang, as well. Will close this as main problem was answered.

**Comment by alecazam** [comment]
I agree with the ability to force include this.  Otherwise, ths extension has to now be inserted into every .frag/.vert/.comp file that we have.  We can't just add the extension to our Shader.h header, since that would need include support.  We're trying to move between gslangValidator and glslc, and this breaks our codegen.

**Comment by greg-lunarg** [comment]
I haven't read this whole thread yet, but FWIW, I think shaderc has recently picked up the latest glslang, and my fix should be in there, so maybe glslc will now work as you hoped?

**Comment by alecazam** [comment]
I did pull the latest binary of glslc off the main page.  There are many revs of glslang, but glslc appears to point to one over a year old.

 glslc --version
shaderc v2020.1-dev v2020.0-15-gb4a735c
spirv-tools v2020.3 v2020.3
glslang 8.13.3743-39-gd39b8afc <- this is from April 20, 2020

Target: SPIR-V 1.0
alecthatgame.co@Ale

**Comment by greg-lunarg** [comment]
It appears you will need to do a rebuild to get the latest glslang, which is 11.4.0.

Or the next SDK, due in about a week, will have the latest glslc.

**Comment by xzores** [comment]
Was this solved?

**Comment by ncesario-lunarg** [comment]
@xzores can you share some more details (glslang version, shader sources, etc.)? Trying this out locally seems to work fine on recent versions of glslang (>= 12.3.1).

**Comment by xzores** [comment]
I have taken my glslValidator.exe file from the vulkan SDK version 1.3.268.0.
The code I try to run is : 
```
#version 450 core
#extension GL_GOOGLE_include_directive : enable
#include "something.glsl"

layout (location = 0) in vec2 inPos;
layout (location = 1) in vec2 inUV;

layout (location = 0) out vec2 outUV;

out gl_PerVertex 
{
    vec4 gl_Position;   
};

void main(void)
{
	gl_Position = vec4(inPos, 0.0, 1.0);
	outUV = inUV;
}
```


And the error is : '#include' : `Could not process include directive for header name: something.glsl `

**Comment by ncesario-lunarg** [comment]
@xzores Can you share how you're invoking glslang? Running `glslangValidator.exe` on Windows from the 1.3.268.0 SDK I get the expected results. e.g.,

something.glsl:
```glsl
float foo() {
    return 0.0;
}
```

```pwsh
glslang.exe -V -o vert.spv -S vert .\vert.glsl
```

With
```pwsh
> glslang.exe --version
Glslang Version: 11:13.1.1
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 13.1.1
GLSL Version: 4.60 glslang Khronos. 13.1.1
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 11
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```

**Comment by xzores** [comment]
I followed this tutorial https://www.youtube.com/watch?v=NQ-g6v7GtoI&t

**Comment by Ralith** [comment]
> Some side question is it possible in command line to enable GL_GOOGLE_include_directive so its not needed to write in every file ?

In case anyone else, like me, comes here from Google with this question: yes, this is possible. Pass `-P"#extension GL_ARB_shading_language_include : enable​"` on the command line.

**Comment by arcady-lunarg** [comment]
Yes, the `-P` option is designed for exactly this, it can be used to inject e.g. an extension declaration that will be treated as appearing right after the `#version` line and before everything else in the program.
