### ISSUE TITLE
Support texelFetch with cubemaps

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/glslang#1710]
Cubemaps are really texture2d arrays. A view whose type is `VK_IMAGE_VIEW_TYPE_CUBE[_ARRAY]` will be bound to a `texture2DCube[Array]` on which you cannot use `texelFetch`. For the same texture, a view of type `VK_IMAGE_VIEW_TYPE_2D_ARRAY` (bound to `texture2DArray`) can be used with `texelFetch` perfectly fine.

Clearly, there is no hardware limitation in fetching texels from a cubemap texture (as it can be done if viewed as a 2d array). Could we please allow `texelFetch` to take cubemaps too (and treat it the same way it does a 2d array)?

The issue is that cubemap(array)s are currently the only types where you can't use the same view to do both the usual sampling and `texelFetch`, creating an unnecessary need for an extra view (of type 2d array) for `texelFetch`.

This issue is observed in ANGLE, implementing `glTexImage2D` with a shader that performs texel-by-texel copies and given a cube face target.

**Comment by ShabbyX** [comment]
Friendly ping. Any input on this?

**Comment by johnkslang** [comment]
Isn't this a change to language semantics, and needs either a specification change or an extension to be written?

**Comment by ShabbyX** [comment]
Probably an extension / future spec change? It's less of a semantic "change" and more of a new function that was previously not defined. Assuming the definition would be formally written up when necessary, do you see any issue with GLSL supporting `texelFetch` with cubes / cube arrays?

**Comment by johnkslang** [comment]
Yes, new built-in functions need either an extension (so other implementers know how to implement them), or a command-line option that makes it clear it's a tool mode that is out of spec.  Otherwise, glslang stops working as a validator and portability checker.
