### ISSUE TITLE
Possible preprocessor issues with empty token concatenation

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/glslang#1721]
Imagine the following code:
```
#define MACRO(tokenA, tokenB, tokenC) tokenA##tokenB##tokenC
#define MACRO2(filled, none) MACRO(filled, C, none)

#define NONE()
MACRO2(A, NONE())
```

In gcc's and clang's preprocessor the outpout is `AC`. glslang in the other hand outputs `ACtokenC`.

A slight twist of the above:
```
#define MACRO(tokenA, tokenB, tokenC) tokenA##tokenB##tokenC
#define MACRO2(filled, none) MACRO(none, filled, C)

#define NONE()
MACRO2(A, NONE())
```

In gcc's and clang's preprocessor the outpout is `AC` once again. glslang in the other hand throws some errors:
```
ERROR: pp_test.frag:5: '##' : unexpected location 
ERROR: pp_test.frag:5: '##' : unexpected location
```
The following also fails on glslang:
```
#define MACRO(tokenA, tokenB, tokenC) tokenA##tokenB##tokenC
#define MACRO2(filled, none) MACRO(none, filled, C)

MACRO2(A, )
```

I'm not sure which behavior is correct but maybe you can verify. Thank you.

**Comment by johnkslang** [comment]
So, the C++ specification (normative for GLSL preprocessing) says

> If (before argument substitution) any argument consists of no preprocessing tokens, the behavior is undefined.

So, generally, for portability, you'd want to set things up without using arguments that have to tokens in them.

Now, if you want to identify a specific behavior that HLSL does define and is important to use, I could look and see whether that is difficult to support or not.

**Comment by godlikepanos** [comment]
> If (before argument substitution) any argument consists of no preprocessing tokens, the behavior is undefined.

I'm using GLSL so the spec quote and the explanation covers me.

DXC seems to have the same behavior as GCC and clang (as expected) but I don't care. If anyone does maybe they can reopen the ticket.

Closing for now. Thank you!
