### ISSUE TITLE
Invalid spir-v when passing array item to function

### ISSUE THREAD

**Issue by fjhenigman** [KhronosGroup/glslang#1725]
A recent change to the validator (https://github.com/KhronosGroup/SPIRV-Tools/commit/117a1fd11f11e9bef9faa563c3d5156cc6ab529c) makes it reject passing an AccessChain in a FunctionCall, which is what glslang does with this:

#version 310 es
precision mediump float;

layout(set = 0, binding = 0) uniform mediump sampler uSampler;
layout(set = 0, binding = 1) uniform mediump texture2D uTexture[4];
layout(location = 0) out vec4 FragColor;
layout(location = 0) in vec2 vTex;

vec4 func(mediump sampler samp, mediump texture2D tex, vec2 uv) {
    return texture(sampler2D(tex, samp), uv);
}

void main() {
    FragColor = func(uSampler, uTexture[1], vTex);
}

**Comment by johnkslang** [comment]
This is a necessary code pattern, and likely an over-aggressive check. If based on SPIR-V spec. language, we probably instead need an issue against SPIR-V instead.

**Comment by johnkslang** [comment]
This rule in SPIR-V:

> Any pointer operand to an OpFunctionCall must be a memory object declaration.

Did not exist until a few months ago. It got added as part of clarifying pass-by-reference rules, and appears too strong.

I am closing this one and opening one in Khronos for the SPIR-V rule.
