### ISSUE TITLE
Not checking that the constructor for combining image & sampler is called at the point of the texture lookup

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/glslang#1729]
According to GL_KHR_vulkan_glsl:

> Constructors can then be used to combine a sampler and a texture at the point of making a texture lookup call
> texture(sampler2D(t, s), ...);

So the following shader should be invalid: 

```
#version 450 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(set = 0, binding = 1) uniform texture3D u_noiseTex;
layout(set = 0, binding = 2) uniform sampler u_linearAnyRepeatSampler;

sampler3D combineImageSampler(texture3D tex, sampler sampl)
{
	return sampler3D(tex, sampl);
}

void main()
{
	vec3 uv = vec3(0);
	vec4 col = textureLod(combineImageSampler(u_noiseTex, u_linearAnyRepeatSampler), uv, 0.0);
}
```

Unfortunately glslang outputs SPIR-V without complaining. But this SPIR-V will cause:
- The validator to crash
- RADV driver to crash
- nVidia's driver to output garbage 

Maybe glslang should be checking this part of the extension.

**Comment by johnkslang** [comment]
Agreed.

**Comment by arcady-lunarg** [comment]
As of #3444, the shader in question no longer compiles and instead produces an error. There have also been other minor improvements with SPIR-V generation around combining textures and samplers.
