### ISSUE TITLE
HLSL: in/out missmatch (vertex -> hull)

### ISSUE THREAD

**Issue by piluve** [KhronosGroup/glslang#1732]
Hi, 
I'm having some trouble with some HLSL shaders:

```
#define NUM_PATCHES 3
#define MAX_TESSELLATION  32.0

struct VertexInput
{
	float4 Pos : POSITION;
	float4 Nrm : NORMAL;
};

VertexInput VSMain(VertexInput vin)
{
    return vin;
}

struct HullConstantOutput
{
	float edges[NUM_PATCHES]: SV_TessFactor;
	float inside : SV_InsideTessFactor;
};

HullConstantOutput HSConstants(InputPatch<VertexInput, NUM_PATCHES> patch)
{
	float tessAmount = 1.0;

	HullConstantOutput o;
	o.edges[0] = 1.0 + tessAmount;
	o.edges[1] = 1.0 + tessAmount;
	o.edges[2] = 1.0 + tessAmount;
	o.inside = 1.0 + tessAmount;
	return o;
}

[domain("tri")]
[partitioning("fractional_odd")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(NUM_PATCHES)]
[patchconstantfunc("HSConstants")]
[maxtessfactor(MAX_TESSELLATION)]
VertexInput HSMain(InputPatch<VertexInput, NUM_PATCHES> patch, uint pointID : SV_OutputControlPointID)
{
	return patch[pointID];
}
```

Vulkan is not reporting any errors when I call : vkCreateGraphicsPipelines(...). However, nothing is rendering. I took a renderdoc capture and I can see the following:

**Vertex shader:**
```
#version 450

layout(location = 0) in vec4 _121;
layout(location = 1) in vec4 _126;
layout(location = 2) in vec4 _130;
layout(location = 3) in vec4 _134;
layout(location = 10) out vec4 _142;
layout(location = 11) out vec4 _145;
layout(location = 8) out vec4 _148;
layout(location = 12) out vec4 _151;

void main()
{
    _142 = _121;
    _145 = _126;
    _148 = _130;
    _151 = _134;
}
```

**Hull shader:** (note that only 1 input is declared, location = 10).
```
#version 450
layout(vertices = 3) out;

struct _58
{
    vec4 _m0;
    vec4 _m1;
    vec4 _m2;
    vec4 _m3;
};

layout(location = 10) in _58 _559[];
layout(location = 0) out _58 _566[3];

void main()
{
    _58 _568[3] = _559;
    _566[gl_InvocationID] = _568[gl_InvocationID];
    barrier();
    if (int(gl_InvocationID) == 0)
    {
        float _1234 = 1.0 + clamp(1.0, 0.0, 32.0);
        gl_TessLevelOuter[0] = _1234;
        gl_TessLevelOuter[1] = _1234;
        gl_TessLevelOuter[2] = _1234;
        gl_TessLevelInner[0] = _1234;
    }
}
```

I was wondering if this behaviour is expected/correct. Any help will be appreciated (I tested with the latest code from master 18/03/2019).

Thanks!
Nacho.

**Comment by piluve** [comment]
I updated the test HLSL code to be more like the real code I'm testing this with. I just noticed that glslang is producing a validation warning:
**_attribute does not apply to entry point_**

Here is this code in [Shader Playground](http://shader-playground.timjones.io/ed13711178c5fe7642bc995027a50b24)

Maybe re-using the VertexInput struct is messing with the compilation of this shader. Any suggestions? 

Thanks a lot.

**Comment by piluve** [comment]
Another test: [Shader Playground](http://shader-playground.timjones.io/1b8bd6afbe9cddbfdeae4e88606222b0),  in this case, instead of using the same struct {}; I created a new one without semantics (vtx -> control). No validation errors this time, however, the vertex outputs 2 vectors but the control inputs the struct [].

**Comment by piluve** [comment]
I created this repro code ([shader-playground](http://shader-playground.timjones.io/b5f988dbe2a20002f44d601099933b98)).

What I'm seeing is that the vertex shaders splits the outputs:

```
layout(location = 0) out vec4 _entryPointOutput_Pos;
layout(location = 1) out vec4 _entryPointOutput_Nrm;
```

And then, the tessellation stages accept an unbound array:

```
struct VertexInput
{
    vec4 Pos;
    vec4 Nrm;
};
layout(location = 0) in VertexInput _patch[];
```

**Comment by piluve** [comment]
I downloaded the [Vulkan samples](https://github.com/SaschaWillems/Vulkan) and tested this behaviour and apparently works fine. I guess that the shader knows the right offsets and it does not matter if one output is split and the input is a struct (as long as the order and initial location are the same).

**Comment by johnkslang** [comment]
Ah, thanks. I could not yet tell if that's all it was.

HLSL, in general, allows type mismatches like this, just lining things up in order.

**Comment by piluve** [comment]
> Ah, thanks. I could not yet tell if that's all it was.
> 
> HLSL, in general, allows type mismatches like this, just lining things up in order.

No problem. My last post wasn't too clear perhaps, I found a solution but I was hopping someone would confirm my results :)
