### ISSUE TITLE
glslangvalidator fails to compile ray tracing shaders with subgroup builtin variables

### ISSUE THREAD

**Issue by Max1412** [KhronosGroup/glslang#1735]
The following shader file:

```
#version 460
#extension GL_NV_ray_tracing : require
#extension GL_KHR_shader_subgroup_basic : require

void main()
{
    uint test = gl_SubgroupInvocationID;
}
```
fails to compile with glslangvalidator when treated as a ray generation shader (named as `shadername.rgen`), while compiling just fine when treated as, e.g., a fragment shader (`shadername.frag`). with the following error:
```
ERROR: shadername.rgen:7: 'gl_SubgroupInvocationID' : undeclared identifier
```
Meanwhile, the ray generation shader stage is supported by NVIDIA (reported by `VkPhysicalDeviceSubgroupProperties::supportedStages`) and ray generation shaders containing subgroup functions like `subgroupBarrier()` are compiling just fine.
It seems like the builtin variables for subgroups which are supposed to be available in all
shader stages, `gl_SubgroupSize` and `gl_SubgroupInvocationID` are missing in the ray tracing shader stages.

**Comment by johnkslang** [comment]
@dgkoch, any input in this?

**Comment by dgkoch** [comment]
Per the linked issue they should be supported, just haven't gotten around to updating the spec yet.

**Comment by dgkoch** [comment]
@Max1412 PR #1782 should fix this for you, if you want to try it out. 

Note that there are gotchas to using subgroups in ray tracing shaders though -- notably that any of the new builtin ray tracing functions can result in shader invocations being repacked, so the results of subgroup operations are only valid until a potential repacking point is encountered (in program execution order).
