### ISSUE TITLE
glslangValidator with --auto-map-bindings behaviour changed?

### ISSUE THREAD

**Issue by jhonnyking** [KhronosGroup/glslang#1736]
Hi! I'm using two versions of glslangValidator that seem to yield different results when using --auto-map-bindings:

Version A: 7.10.2904
Version B: 7.11.3113

With version A, uniforms that are not used in the final output of the shader won't get a "binding" entry in the reflection output from spirv-cross whereas version B will yield the binding unit 0. This is a bit annoying since I'm using the binding values from the reflection data to setup descriptors in our Vulkan renderer, and if unused uniforms gets zero as binding unit then there's no way of knowing which of those units that are valid.

test.frag:
```
#version 140

in mediump vec2 var_texcoord0;

uniform lowp sampler2D tex0;
uniform lowp sampler2D tex_not_used;
uniform UBO0 { lowp vec4 tint; };
uniform UBO1 { lowp vec4 tint_not_used; };

void main()
{
    lowp vec4 color = texture(tex0, var_texcoord0.xy) * tint;
    gl_FragColor    = vec4(color.rgb,1.0);
}
```

Running the tools:
glslangValidator  --auto-map-bindings --auto-map-locations  -V test.frag
spirv-cross test.spv --reflect

Reflection result from A:
```
...
"textures" : [
        {
            "type" : "sampler2D",
            "name" : "tex0",
            "set" : 0,
            "binding" : 0
        },
        {
            "type" : "sampler2D",
            "name" : "tex_not_used",
            "set" : 0
        }
    ],
    "ubos" : [
        {
            "type" : "_20",
            "name" : "UBO0",
            "block_size" : 16,
            "set" : 0,
            "binding" : 1
        },
        {
            "type" : "_40",
            "name" : "UBO1",
            "block_size" : 16,
            "set" : 0
        }
    ]
```

Reflection result from B:
```
"textures" : [
        {
            "type" : "sampler2D",
            "name" : "tex0",
            "set" : 0,
            "binding" : 0
        },
        {
            "type" : "sampler2D",
            "name" : "tex_not_used",
            "set" : 0,
            "binding" : 0
        }
    ],
    "ubos" : [
        {
            "type" : "_20",
            "name" : "UBO0",
            "block_size" : 16,
            "set" : 0,
            "binding" : 1
        },
        {
            "type" : "_40",
            "name" : "UBO1",
            "block_size" : 16,
            "set" : 0,
            "binding" : 0
        }
    ]
```

Any reason why this behaviour has changed between the two versions? I would like for our shader pipeline to use the latest toolset, but I would rather have the behaviour from A instead of B.

Thanks!

**Comment by johnkslang** [comment]
It should be okay for an unused resource to alias a binding number. Were you using the lack of a binding to discover what was unused?

This was introduced, intentionally, by #1625, which says:

> The newest SPIRV-Tools checks the Vulkan rule that all resources must have a set and binding decoration...

That implies you were relying on illegal SPIR-V, but maybe there is another way to get what you want.

**Comment by jhonnyking** [comment]
Thanks for the reply! 

Yes exactly, our render api is built around OpenGL where that information is available via glGetUniformLocation and there's a bunch of functionality that relies on it. User shaders are written in glsl 120 for best mobile/web compliance so we can't use the optimisation flags for the SPIR-V compilation since I need the original uniform string names for the uniform update. 

But yeah as you say, maybe there's a way around this but for now I can only invalidate shaders with duplicate bindings and let users know so they can remove unused uniforms..

**Comment by nitronoid** [comment]
Hi, sorry to revive this old thread but I'm having a closely related issue.
The tool I'm working on is feeding ESSL through and producing SPIRV, with the intention to patch any blocks which haven't been given explicit bindings by generating them ourselves. This becomes difficult with the changes in the PR you referenced as a binding of 0 is perfectly valid and offers no way of knowing that this uniform wasn't given an explicit binding.

I'm wondering if you have any suggestions on how I could work around this problem? Currently I have subclassed `TGlslIoMapper` to modify the binding values when not explicitly provided to a sentinel value which we check for later, i.e.
```
if (!qualifier.hasBinding()) qualifier.layoutBinding = sentinel;
```
But this feels like a hack and may be fragile.

Perhaps instead of just setting the binding to zero, these uniforms could also be tracked by the shader so we can at least tell where default values have been assigned?

Please let me know if I should create a new issue for this, thanks.

**Comment by johnkslang** [comment]
There are quite a few options to control assigned bindings, like `--shift-ssbo-binding` that might do what you want.  If not, it would make sense to open a new issue to track this request.

**Comment by nitronoid** [comment]
Thank you for your response, I have opened a new issue here #2218
