### ISSUE TITLE
Type mismatch on location error when compiling HLSL geometry shader

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/glslang#1737]
Hello!
I am seeing the following Vulkan validation layer error when creating PSO with geometry shader compiled from HLSL:

```
Diligent Engine: ERROR: Vulkan debug message (validation): UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch
                 Type mismatch on location 0.0: 'ptr to output vec3 of float32' vs 'ptr to input arr[1] of struct of (vec3 of float32)'
                 Object[0] (shader module): Handle 0x2b19, Name: '000002B2212936F0'
```

Vertex shader:
```hlsl
struct VSIn
{
	uint uiVertexId : SV_VertexID;
};

struct VSOutput
{
	float4 f4Position : SV_Position;
	float3 f3Color	: COLOR;
};

void main(VSIn In,
          out VSOutput Out)
{
    float4 Positions[2];
    Positions[0] = float4(-0.4,0.3,0.0,1.0);
    Positions[1] = float4(-0.35,0.25,0.0,1.0);
    float3 Color[2];
    Color[0] = float3(1.0,0.0,0.0);
    Color[1] = float3(0.0,1.0,0.0);
	Out.f4Position = Positions[In.uiVertexId];
    Out.f3Color = Color[In.uiVertexId];
}
```

Geometry shader:
```hlsl
struct VSOutput
{
	float4 f4Position : SV_Position;
	float3 f3Color	: COLOR;
};

struct GSOut
{
    VSOutput VSOut;
};


[maxvertexcount(6)]
void main(point VSOutput In[1], 
          inout TriangleStream<GSOut> triStream )
{
    float2 Offsets[3];
    Offsets[0] = float2(-0.05, -0.05);
    Offsets[1] = float2(+0.05, -0.05);
    Offsets[2] = float2( 0.0, 0.0);
    for(int i=0; i<3; i++)
    {
        GSOut Out;
        Out.VSOut = In[0];
        Out.VSOut.f4Position.xy += Offsets[i];
        triStream.Append( Out );
    }
    triStream.RestartStrip();
    for(int j=0; j<3; j++)
    {
        GSOut Out;
        Out.VSOut = In[0];
        Out.VSOut.f4Position.xy += Offsets[j]*float2(1.0, -1.0);
        triStream.Append( Out );
    }
}
```

Pixel shader:
```hlsl
struct VSOutput
{
	float4 f4Position : SV_Position;
	float3 f3Color	: COLOR;
};

struct GSOut
{
    VSOutput VSOut;
};

void main(GSOut In,
          out float4 Color : SV_Target)
{
	Color = float4(In.VSOut.f3Color,1.0);
}
```

Despite the error, shaders seem to work as expected. They also work properly in D3D11 and D3D12 back-ends.
glslang version: https://github.com/KhronosGroup/glslang/commit/5efb004d59601711cdf328c8a8bfbe7f333dc7a0
SPIRV-Tools version: https://github.com/KhronosGroup/SPIRV-Tools/commit/2d52cbee49019da5d664bb7e243fa6339c983c27

**Comment by olegviz** [comment]
some news on this issue ? 
Im also waiting for solution for our project

**Comment by anomalous42** [comment]
I'm seeing a similar problem, with a slightly different error message:

`Type mismatch on location 0.0: 'ptr to output vec4 of float32' vs 'ptr to input arr[3] of struct of (struct of (vec4 of float32, vec4 of float32, vec4 of float32, vec4 of float32, vec2 of float32), vec4 of uint32)'`

It looks like it's expanding the struct into individual elements when compiling the vertex shader, but not doing so for the tessellation control shader.

This is again coming from HLSL shaders, and despite the scary looking error from the validation layers it also seems to be rendering correctly.

**Comment by DiligentGraphics** [comment]
Yes, on Windows it still works fine, but may fail on other platforms (will certainly fail on Mac). 
glslang is very reluctant to fix this problem though multiple people have reported it. 
A current workaround is to convert HLSL to GLSL and then compile it:
https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial08_Tessellation/src/Tutorial08_Tessellation.cpp#L73

**Comment by dmaluev** [comment]
Having the same problem with geometry and hull shaders.
This is quite critical. I need geometry shader at least for point sprites.

**Comment by danginsburg** [comment]
Please check to see if this is fixed with #2217

**Comment by TheMostDiligent** [comment]
@danginsburg Vulkan validation layers are still not happy. Now the error looks little different though:
```
Diligent Engine: ERROR: Vulkan debug message (validation): UNASSIGNED-CoreValidation-Shader-InterfaceTypeMismatch
                 Number of elements inside builtin block differ between stages (vertex shader 1 vs geometry shader 3).
                 Object[0] (shader module): Handle 0xe164150000000050
```

**Comment by TheMostDiligent** [comment]
I confirm the change fixes the original problem - thank you! You can close the issue (I created it under different account and can't close it).
