### ISSUE TITLE
glslangValidator - Don't print "stdin" for errors reported

### ISSUE THREAD

**Issue by HorstBaerbel** [KhronosGroup/glslang#1743]
When reading shaders from stdin the error output is:

> C:\foo>glslangValidator.exe --stdin -S frag < bar.vert
> stdin
> ERROR: 0:5: 'attribute' : not supported in this stage: fragment
> ERROR: 0:5: '' : compilation terminated
> ERROR: 2 compilation errors.  No code generated.

This seems unnecessary and is inconvenient when calling glslangValidator from other programs and returning error messages.

**Comment by johnkslang** [comment]
I believe @svenstaro added and was using this functionality. If it is okay with everyone to see a change here, we can look at changing it.  Note that the standalone executable is file-name driven, so it might not be just a trivial deleting of strings.

**Comment by svenstaro** [comment]
Well I'm using this feature for my glsl language server.

**Comment by HorstBaerbel** [comment]
I don't see why it's necessary, but well then. Looked like a bug to me...
