### ISSUE TITLE
Error whilst building SPIRV-Tools-opt

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [KhronosGroup/glslang#1745]
Hi,

I'm quite new to the C++ workflow and have encountered the following issue when trying to turn on the optimizer in `glslang`:

```
[ 57%] Linking CXX static library libSPIRV.a
[ 57%] Built target SPIRV
[ 57%] Built target spirv-cross-glsl
Scanning dependencies of target ShaderPacker
[ 58%] Building CXX object CMakeFiles/ShaderPacker.dir/lib/ShaderPacker.cpp.o
make[2]: *** No rule to make target `external/glslang/External/spirv-tools/source/opt/libSPIRV-Tools-opt.a', needed by `../bin/ShaderPacker'.  Stop.
make[1]: *** [CMakeFiles/ShaderPacker.dir/all] Error 2
make: *** [all] Error 2
```

I've followed the mentioned [build steps](https://github.com/KhronosGroup/glslang#build-steps) in the README (meaning I've ran `./update_glslang_sources.py` and pulled in `SPIRV-Tools` like that).

Am I missing something or is this a bug? I have successfully built the project without SPIRV-Tools before).

Kind regards,

Tim

**Comment by johnkslang** [comment]
I'm don't recognize the `ShaderPacker`stuff.  where did it come from?

**Comment by TimvanScherpenzeel** [comment]
> I don't recognize the `ShaderPacker`stuff. where did it come from?

Ah sorry that is the library I'm building. It is basically about this error: `make[2]: *** No rule to make target `external/glslang/External/spirv-tools/source/opt/libSPIRV-Tools-opt.a', needed by `../bin/ShaderPacker'.  Stop.` where `external/glslang/External/spirv-tools/source/opt/libSPIRV-Tools-opt.a` doesn't exist.

**Comment by johnkslang** [comment]
I'm not sure. Looking at the Travis Linux build logs, I see:

```
[ 82%] Linking CXX static library libSPIRV-Tools-opt.a
[ 82%] Built target SPIRV-Tools-opt
...
-- Installing: /home/travis/build/KhronosGroup/glslang/build/install/lib/libSPIRV-Tools-opt.a
...
[ 92%] Linking CXX static library libSPIRV.a
[ 92%] Built target SPIRV
...
```

(Maybe I got lines out of order though.)  So, this seems like a working model you could compare against.

Is it possible your install directory is not set correctly when generating the build process with CMake?
