### ISSUE TITLE
GLSL vertex attribute overlap

### ISSUE THREAD

**Issue by Roy-AMD** [KhronosGroup/glslang#1747]
Hi Kessenich,
This issue about GLSL vertex attribute overlap.

Source string see below:
```glsl
#version 430 core
layout(location = 0) in vec4 vs_in_attrib[8][2];
in vec4 vs_in_attrib2[8][1];
out StageData {
  vec4 attrib[16];
} vs_out;
void main() {
  for (int i = 0; i < vs_in_attrib.length(); ++i) {
    vs_out.attrib[i] = vs_in_attrib[i][0] + vs_in_attrib2[i][0];
  }
}
```
The location of vs_in_attrib and vs_in_attrib2 are all be set 0, and It's seem no flag to mark the location qualifier whether be specified. 
In this case, the location of vs_in_attrib2 should be 16, If we have a flag (like ```qualifierSpecMask```) to mark it or set ```location = -1``` to indicate it was not be specified.
that can help us handling the location. If we do not do this, it will be very difficult to deal with locations in this case.
I suggest to use a mask to hold this information, it can help us keep compatibility and retaining more qualifier information.
If you think this scenario works, I'll change the code and request a merge.

Thanks
Roy 
form AMD

**Comment by Canonzki** [comment]
It's seem

**Comment by Canonzki** [comment]
I try to use 
```shell
glslangValidator --auto-map-locations -G test.vert 
spirv-cross .\vert.spv --reflect
``` 
but int result, the location still 0:
```json
{
    "entryPoints" : [
        {
            "name" : "main",
            "mode" : "vert"
        }
    ],
    "types" : {
        "_24" : {
            "name" : "StageData",
            "members" : [
                {
                    "name" : "attrib",
                    "type" : "vec4",
                    "array" : [
                        16
                    ]
                }
            ]
        }
    },
    "inputs" : [
        {
            "type" : "vec4",
            "name" : "vs_in_attrib",
            "array" : [
                2,
                8
            ],
            "location" : 0
        },
        {
            "type" : "vec4",
            "name" : "vs_in_attrib2",
            "array" : [
                1,
                8
            ],
            "location" : 0
        }
    ],
    "outputs" : [
        {
            "type" : "_24",
            "name" : "StageData",
            "location" : 0
        }
    ]
}
```

**Comment by johnkslang** [comment]
Because this has to do with inter-stage linking, it is difficult to get all the location stuff automatically, hence that functionality is not fully available.  It is best to use explicit locations in the shader.

If you have ways to improve it we can consider it. I'm somewhat wanting to have one of these though:

- keep it just obviously broken, for non-real uses (usage statement currently says "fragile, not cross stage")
- find a full fix

This is to avoid subtle bugs from near fixes that are not full fixes.

**Comment by Canonzki** [comment]
In older GLSL version, It's seems user are not be allow to use explicit location. so I think we should find a better way to save this issue.
Here's how I think about it:
when we deal a cross stage in/out value, 
* If this value are not be explicit location in both two stage, we should mark it‘s location implicit and hand it in OpenGL driver.
* If this value be explicit location in only one stage, we should set this value's location as it's specified.
* If this value be explicit a same location in two stage, we should set this value's location as it's specified.
* If this value be explicit a different location in two stage, we should throw a link error.

so, we just set it's location in compiler time, and take a location merge in link time, after that, we will get a final result. and hand it in OpenGL driver. This may cause the location to change after the link.Vertex attribute is special, the qualifier will be only declare once, and location overlap will only allow in vertex attribute, so the processing on location qualifier will be more consistent with the interface block at other stages(vertex input just won't be merge).
Maybe some of my considerations are not comprehensive enough. I will make corresponding modifications as soon as possible to verify the feasibility of this scheme. If you have other suggestions, please let me know. Your experience and suggestions will be of great help to me.

**Comment by johnkslang** [comment]
This should only be a SPIR-V issue, and SPIR-V requires the location to be declared, even if older versions of glslang did not enforce that rule.

The main issue is that we haven't yet implemented SPIR-V generation for multi-stage compilation.  We currently support multiple compilation units for a single stage, but not yet emitting multiple stages from a single invocation.
