### ISSUE TITLE
Improve Semantic Version access in the source code, to allow for easy extraction of the information by build systems like cmake

### ISSUE THREAD

**Issue by danielmrussell** [KhronosGroup/glslang#1754]
The FindZLIB.cmake module extracts the following #defines from the ZLIB source code, in order to construct the elements of its current library semantic version:
• ZLIB_VERSION_MAJOR
• ZLIB_VERSION_MINOR
• ZLIB_VERSION_PATCH

The built-in find_package hook for ZLIB that comes with cmake FindZLIB.cmake uses textual extraction (with regexps etc) to get to this information, and put it into CMAKE variables fulfilled by the find_package operation.

I am attempting to create a similar cmake find_package hook for glslang, but finding it to be a pain. The problem is, were have these defined instead:
• No #define for major version but a hard coded constant in GetSpirvGeneratorVersion(), buried in a difficult place to find (in SPIRV/GlslangToSpv.cpp)
•  GLSLANG_MINOR_VERSION
• GLSLANG_PATCH_LEVEL

I propose we standardize to Best Practices and copy the ZLIB names exactly, but with GLSLANG_ of course, and make them #defines so that it is "easy" to extract them textually from  the cmake module (by copying and modifying the built-in cmake module FindZLIB.cmake).

So the following #defines would be easily accessible from a single short header that is PURELY for recording the versioning information, ideally, or **at the very least, all together in one place.**
• GLSLANG_VERSION_MAJOR
• GLSLANG_VERSION_MINOR
• GLSLANG_VERSION_PATCH

It would make it a lot easier.

**Comment by johnkslang** [comment]
Does it work to have a localized/consistent functional interface instead of #defines?

Glslang truly is multiple tools in the same binary, and we are indeed forming the semantic version by mixing the code generator's versioning with the overall patch level.

**Comment by danielmrussell** [comment]
It's very confusing and seem out of alignment with the trending best practice, as it forces difficult or impossible decisions in the build tools department. Little things really making us waste so much time.

It has to be something readable by cmake itself, so sadly, needs to be #defines or similar. If it is embedded in functions using hard coding, then it might as well be #defined as well and then referenced instead of a hard-coded value, for instance. Even if the names were not brought into alignment with best practices around semantic versioning and cmake, it would still be helpful to be able to read the value in a way that is not super fragile.

Technically, I could parse the values out of the multiple files, and I could even parse the hardcoded value out of the function its in, but that super fragile and almost guaranteed to break once we clean up the code.

#defines less so.

**Comment by arcady-lunarg** [comment]
The version is now available in `include/glslang/build_info.h` file that is generated in the build directory, and the version also appears to be available within cmake itself with a `set(PACKAGE_VERSION)` statement.
