### ISSUE TITLE
Applying NonUniformExt on wrong element

### ISSUE THREAD

**Issue by jasuarez** [KhronosGroup/glslang#1760]
The following GLSL fragment

~~~   
#version 450
#extension GL_EXT_nonuniform_qualifier : require	
layout(set=0,binding=4,rgba32f) uniform imageBuffer data[];
layout(location = 0) out vec4     FragColor;	
layout(location = 0) in flat vec4 position;	
layout(location = 1) in flat vec2 normalpos;	
layout(location = 2) in flat int  vIndex;		
layout(location = 3) in flat int  rIndex;		
layout(location = 4) in flat int  gIndex;		
layout(location = 5) in flat int  bIndex;		
layout(location = 6) in flat int  aIndex;		
void main()									
{												
  FragColor = imageLoad(data[nonuniformEXT(rIndex)], 0);
}
~~~

When converting to SPIR-V it applies the NonUniformEXT decoration on the data[rIndex], but also on rIndex itself, which is a variable and shouldn't be decorated (it does not makes sense)

~~~
pCapability Shader
OpCapability ImageBuffer
OpCapability ShaderNonUniformEXT
OpCapability RuntimeDescriptorArrayEXT
OpCapability StorageTexelBufferArrayNonUniformIndexingEXT
OpExtension &quot;SPV_EXT_descriptor_indexing&quot;
%1 = OpExtInstImport &quot;GLSL.std.450&quot;
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %4 &quot;main&quot; %9 %16 %24 %27 %28 %29 %30 %31
OpExecutionMode %4 OriginUpperLeft
OpDecorate %9 Location 0
OpDecorate %13 DescriptorSet 0
OpDecorate %13 Binding 4
OpDecorate %16 Flat
OpDecorate %16 Location 3
OpDecorate %16 NonUniformEXT
OpDecorate %17 NonUniformEXT
OpDecorate %20 NonUniformEXT
OpDecorate %24 Flat
[...]
%14 = OpTypeInt 32 1
%15 = OpTypePointer Input %14
%16 = OpVariable %15 Input
[..]
%17 = OpLoad %14 %16
%19 = OpAccessChain %18 %13 %17
%20 = OpLoad %10 %19
%22 = OpImageRead %7 %20 %21
~~~

`%16` is the `rIndex` variable, which does not make sense to decorate.

**Comment by alegal-arm** [comment]
This seems perfectly legal due to this spec language: "This constructor syntax takes a single argument of any type and returns the value with the same type, qualified with nonuniformEXT."

Though I assume the spec intends to say "and returns the **expression** ... "

@jeffbolznv, @johnkslang

**Comment by johnkslang** [comment]
It seems to make sense. You have an input asserted to be non uniform, and the SPIR-V says the variable is non uniform.

I could understand you not wanting to see it on the variable, just on a load, but I'd want to see something truly incorrect before digging deeper.

**Comment by jeffbolznv** [comment]
I think there's a real bug here, the qualifier shouldn't be applied to the operand, just the result (or a copy of the result). It may not be a *functional* bug since adding NonUniform is more conservative, but could affect performance and isn't the intent of the shader.

I'm working on a fix.

**Comment by jeffbolznv** [comment]
I've made a PR (https://github.com/KhronosGroup/glslang/pull/1762) in which the nonuniformEXT constructor makes a copy of the object that it applies the decoration to, rather than applying it on the operand.

**Comment by johnkslang** [comment]
Do you know how that interacts with optimizers? I was partly thinking the original result, while even if it wasn't the result of optimization, it could be.

**Comment by ehsannas** [comment]
@jeffbolznv
I'm trying to figure out whether DXC/Spiregg's current implementation of non-uniform indexing is correct or not (https://github.com/microsoft/DirectXShaderCompiler/issues/2436).

1) From reading the spec:

> If an instruction loads from or stores to a resource (including atomics and image instructions) and the resource descriptor being accessed is not dynamically uniform, then the operand corresponding to that resource (e.g. the pointer or sampled image operand) must be decorated with NonUniformEXT.

my understanding is that you've introduced `OpCopyObject` to improve performance, but it should not be needed for correctness. Is that right?


2) Is it correct to say that `NonUniformEXT` should be applied to the result of loading the `nonuniformEXT` variable (not the variable itself), and then propagated **forward** until it's used in an access instruction?
  *  This is what DXC does today, and it's consistent with my understanding of the spec. It is possible that  https://github.com/microsoft/DirectXShaderCompiler/issues/2436 is potentially pointing to a driver bug.
  * Are there CTS tests for this feature that test which result-ids should be getting the decoration?

(FYI @dneto0 @alan-baker @johnkslang)

**Comment by jeffbolznv** [comment]
> my understanding is that you've introduced OpCopyObject to improve performance, but it should not be needed for correctness. Is that right?

Right, the OpCopyObject allows glslang to easily decorate the right thing without decorating "too much" as nonuniform.

> Is it correct to say that NonUniformEXT should be applied to the result of loading the nonuniformEXT variable (not the variable itself), and then propagated forward until it's used in an access instruction?

Yeah, that's the natural way for a frontend compiler to implement it. Though what really matters is only whether the operand of the memory access instruction is decorated as nonUniform.

> Are there CTS tests for this feature that test which result-ids should be getting the decoration?

I'm not sure what you mean. The CTS tests don't explore which result IDs are decorated, they just rely on the frontend compiler doing something valid.

**Comment by ehsannas** [comment]
Thanks @jeffbolznv for your quick response. That makes things more clear.
