### ISSUE TITLE
[SPIR-V] Bad codegen with -g and loops

### ISSUE THREAD

**Issue by PazerOP** [KhronosGroup/glslang#1774]
Debug information via -g is not currently usable for me because my shaders make use of loops.

Here's a minimal example:

```HLSL
float4 main() : SV_TARGET
{
	float result = 0;

	for (uint i = 0; i < 4; i++)
		result.x += 1.0f;

	return result.xxxx;
}
```

With `glslangValidator.exe -V -e main test_simple.frag.hlsl -o test_simple.frag.spv`, code generation is successful and spirv-val reports no errors. However if I try to compile with `glslangValidator.exe -V -e main -g test_simple.frag.hlsl -o test_simple.frag.spv` (added `-g`), code generation is still successful, but spirv-val gives the following error:

```
error: line 33: OpLoopMerge must immediately precede either an OpBranch or OpBranchConditional instruction. OpLoopMerge must be the second-to-last instruction in its block.
  OpLoopMerge %47 %52 None
```

Looking at the output from spirv-dis, it seems glslangvalidator is adding an `OpNoLine` where it should not:
```SPIR-V
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 7
; Bound: 61
; Schema: 0
               OpCapability Shader
          %2 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %_entryPointOutput
               OpExecutionMode %main OriginUpperLeft
          %1 = OpString "test_simple.frag.hlsl"
               OpSource HLSL 500 %1 "// OpModuleProcessed entry-point main
// OpModuleProcessed client vulkan100
// OpModuleProcessed target-env vulkan1.0
// OpModuleProcessed hlsl-offsets
#line 1
float4 main() : SV_TARGET
{
	float result = 0;

	for (uint i = 0; i < 4; i++)
		result.x += 1.0f;

	return result.xxxx;
}
"
               OpName %main "main"
               OpName %_entryPointOutput "@entryPointOutput"
               OpDecorate %_entryPointOutput Location 0
       %void = OpTypeVoid
          %4 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
    %float_0 = OpConstant %float 0
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
     %uint_4 = OpConstant %uint 4
       %bool = OpTypeBool
    %float_1 = OpConstant %float 1
        %int = OpTypeInt 32 1
      %int_1 = OpConstant %int 1
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
       %main = OpFunction %void None %4
          %6 = OpLabel
               OpLine %1 5 0
               OpBranch %46
         %46 = OpLabel
         %60 = OpPhi %float %float_0 %6 %54 %52
         %59 = OpPhi %uint %uint_0 %6 %56 %52
         %51 = OpULessThan %bool %59 %uint_4
               OpLoopMerge %47 %52 None
               OpNoLine
               OpBranchConditional %51 %52 %47
         %52 = OpLabel
               OpLine %1 6 0
         %54 = OpFAdd %float %60 %float_1
               OpLine %1 5 0
         %56 = OpIAdd %uint %59 %int_1
               OpBranch %46
         %47 = OpLabel
               OpLine %1 8 0
         %58 = OpCompositeConstruct %v4float %60 %60 %60 %60
               OpLine %1 2 0
               OpStore %_entryPointOutput %58
               OpReturn
               OpFunctionEnd
```

**Comment by johnkslang** [comment]
Yes. The spec. even says about OpNoLine:

>  It cannot be the last instruction in a block, or the second-to-last instruction if the block has a merge instruction.

So, glslang should not be putting the OpNoLine between the merge and the branch.

**Comment by dneto0** [comment]
I suggest @jaebaek address this in Glslang.  He's generating debug info for the DXC SPIR-V and should see this case.

**Comment by jaebaek** [comment]
I quickly checked this issue and I cannot reproduce the error.
I also used `git blame` and `git log -L` to check source code history and checked it with old glslang but I was not able to reproduce it either.

I guess the problem is not from glslang but from the legalization part of spirv-opt.
(because the example code is written in HLSL)

I fixed a related issue of spirv-opt (14th of this January).
See https://github.com/KhronosGroup/SPIRV-Tools/pull/3130.

I think my PR for spirv-opt solves this issue as well.
Please let me know if you can still reproduce the same error.

**Comment by dneto0** [comment]
I agree. I don't reproduce this issue.
