### ISSUE TITLE
Unable to find binding for descriptor set in reflection API

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/glslang#1778]
I'm trying to use the reflection API of GLSLang to auto generate a Vulkan descriptor layout, but I find this API does not expose the descriptor set? (or I couldn't find it). As an example, if my shader has:

```
layout (set =2, binding = 3) uniform sampler2D tex;
```

I can see the binding, but can't figure out the set. Any help would be greatly appreciated.

**Comment by reduz** [comment]
Nevermind, it seems I had to include a non-public header (Types.h)

**Comment by reduz** [comment]
Just out of curiosity, Is there any reason why this header is not public?

**Comment by johnkslang** [comment]
There is more than one interface, depending on the depth of functionality being sought.  However, the directory structure is not ideal and out of date.  Seems more dangerous to change it though than to leave it alone.
