### ISSUE TITLE
unreachable 'default'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [KhronosGroup/glslang#1780]
https://github.com/KhronosGroup/glslang/blob/625eb25d6e801311af2f587a38ff35412876dfe0/glslang/Include/BaseTypes.h#L470
this 'default' should never be reached.

since the enum 'TPrecisionQualifier' has only 4 items which are all included in switch cases.
so may be an 'assert(false)' is better than just return a "unknown precision qualifier" string as a better software engineering perspective.

**Comment by 360CodeSafe** [comment]
also:
https://github.com/KhronosGroup/glslang/blob/625eb25d6e801311af2f587a38ff35412876dfe0/glslang/Include/InfoSink.h#L94

**Comment by 360CodeSafe** [comment]
also:
https://github.com/KhronosGroup/glslang/blob/625eb25d6e801311af2f587a38ff35412876dfe0/SPIRV/SpvTools.cpp#L153

**Comment by johnkslang** [comment]
Don't these catch problems when new enumerants are added, but not yet handled in the switch statements?  Not sure I agree here with the tool's complaints.

**Comment by 360CodeSafe** [comment]
For an enum, it is better to make the switch cases to cover all the items. when new item is added in the same enum, we suggest to add a single case in switch.
For sevaral enums, it is better not to use single switch to deal all the items. When new enum is add to deal, we suggest to use a new switch.

**Comment by johnkslang** [comment]
> when new item is added in the same enum, we suggest to add a single case in switch.

Yes, and the current default message is what catches the mistake if one does not do that.
