### ISSUE TITLE
overly aggressive array bounds check for array size that is a spec constant expression

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#1783]
Sample vertex shader:

```glsl
#version 450

layout(constant_id = 0) const uint a = 1;
layout(location = 0) out uint o;

void main() {
  uint arr[a+a];
  arr[0] = 1;
  arr[1] = 2;
  o = arr[1];
}

```
compiling to generate SPIR-V, I get this:

```
$glslangValidator  -V c.vert -o c.spv
c.vert
ERROR: c.vert:9: '[' :  array index out of range '1'
ERROR: c.vert:9: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
```

Given that the spec constant is not known at compile time, it's too aggressive to error out saying that an array index of 1 is out of range.

**Comment by PazerOP** [comment]
Related: passing specialization constants as parameters to functions will cause them to be treated as compile-time constants inside the function. For example:

```HLSL
[[vk::constant_id(3)]] const int MY_SPEC_CONST = -1;

int GetValue(int something)
{
    if (something < 0)
        return -1;
    else
        return 1;
}
...
GetValue(MY_SPEC_CONST);
```

The return value of MY_SPEC_CONST will always be -1.

**Comment by johnkslang** [comment]
The defaults for specialization constants should make a shader with correct semantics, so I wouldn't want to claim error checking should not be done for that reason. What seems more odd is that the specialization constants did say to make an array of size `[1 + 1]`, for which the index `1` is in range.  I will look into it.
