### ISSUE TITLE
glslang stores images/samplers in variables when passing them to functions.

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#179]
Given a shader with the following GLSL source code

    layout(location = 0) out vec4 f_color;
    layout(location = 0) in vec4 v_color;
    layout(set = 0, binding = 1) uniform sampler2D tex;
    vec4 lookup(sampler2D t, vec2 tcoord) {
        return texture(t, tcoord);
    }
    
    void main()
    {
        f_color = v_color + lookup(tex, vec2(0.1, 0.1));
    }

When you run it through glslang, you get the followint SPIR-V:

    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 1
    ; Bound: 37
    ; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main" %24 %26
               OpExecutionMode %4 OriginLowerLeft
               OpSource GLSL 430
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %4 "main"
               OpName %16 "lookup(s21;vf2;"
               OpName %14 "t"
               OpName %15 "tcoord"
               OpName %24 "f_color"
               OpName %26 "v_color"
               OpName %29 "tex"
               OpName %32 "param"
               OpName %34 "param"
               OpDecorate %24 Location 0
               OpDecorate %26 Location 0
               OpDecorate %29 DescriptorSet 0
               OpDecorate %29 Binding 1
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeFloat 32
          %7 = OpTypeImage %6 2D 0 0 0 1 Unknown
          %8 = OpTypeSampledImage %7
          %9 = OpTypePointer Function %8
         %10 = OpTypeVector %6 2
         %11 = OpTypePointer Function %10
         %12 = OpTypeVector %6 4
         %13 = OpTypeFunction %12 %9 %11
         %23 = OpTypePointer Output %12
         %24 = OpVariable %23 Output
         %25 = OpTypePointer Input %12
         %26 = OpVariable %25 Input
         %28 = OpTypePointer UniformConstant %8

    ; Image variable here
         %29 = OpVariable %28 UniformConstant
         %30 = OpConstant %6 0.1
         %31 = OpConstantComposite %10 %30 %30
          %4 = OpFunction %2 None %3
          %5 = OpLabel
         %32 = OpVariable %9 Function
         %34 = OpVariable %11 Function
         %27 = OpLoad %12 %26
         %33 = OpLoad %8 %29
               OpStore %32 %33
               OpStore %34 %31
         %35 = OpFunctionCall %12 %16 %32 %34
         %36 = OpFAdd %12 %27 %35
               OpStore %24 %36
               OpReturn
               OpFunctionEnd
         %16 = OpFunction %12 None %13
         %14 = OpFunctionParameter %9
         %15 = OpFunctionParameter %11
         %17 = OpLabel
         %18 = OpLoad %8 %14
         %19 = OpLoad %10 %15
         %20 = OpImageSampleImplicitLod %12 %18 %19
               OpReturnValue %20
               OpFunctionEnd

When it actually handles the function call, it loads from the sampler
pointer, stores the result in a termporary variable, and passes that into
the function.  I don't think you are allowed to create temporary variables
with sampler types and store things into them.

**Comment by johnkslang** [comment]
Since a function can't assign into a sampler, this could be simplified and the problem avoided by just passing a copy of the pointer.

**Comment by jekstrand** [comment]
That seems like the reasonable thing to do.  We should make sure the spec is explicit about disallowing samplers and images in OpStore and OpPhi.

**Comment by jekstrand** [comment]
Has there been any progress on this?  There is a reasonably well-known Vulkan game that this is preventing us from running.

**Comment by johnkslang** [comment]
The spec. says 

> **OpSampledImage** instructions must not appear as operands to **OpPhi** instructions or **OpSelect** instructions, or any instructions other than the image lookup and query instructions specified to take an operand whose type is OpTypeSampledImage.

This is on the right track to prevent obsuring the original source of the resource, which is the goal.

The spirit of the requirement in this space is a simple linear deduction of what sampler/image resource is used.  Even when done optimally, it is a multi-step path for deeply nested functions.  They key is to avoid selections, which is done.

Generally, there is still these ubiquitous load/store pair passing it to the callee that could benefit for a general elimination.  In this case, what's more concerning (if I'm looking at it correctly), is it seems we store on object into a pointer, so I think the canned load/store setting up of the parameters might not be correct.

**Comment by jekstrand** [comment]
Yes, that's a pretty good sum-up.  The fact that it's multi-step to get back to the original image isn't a problem.  That's to be expected with functions.  The bigger problem is that, as soon as you store something to a variable, you loose the SSA ability to trace things back to where they came from.
