### ISSUE TITLE
Compiled SPIRV with wrong code size (not multiple of 4)

### ISSUE THREAD

**Issue by Kadowns** [KhronosGroup/glslang#1805]
I've implemented a simple wrapper for compiling my glsl code to spirv using gslang (HEAVILY based on this artcile: https://forestsharp.com/glslang-cpp/ it's basically the exact same code)

Glslang doesn't produce any errors or warnings, but my compiled spirv NEVER has a code size multiple of 4)
I haven't found any solutions anywhere, so i guess it's ok to post this issue here.

My vertex shader file (produces a SPIRV with code size of 323):
![image](https://user-images.githubusercontent.com/17485541/59626159-8eeed880-9111-11e9-80ac-9ff82d4a7e1d.png)

Fragment shader file (produces a SPIRV with code size of 134):
![image](https://user-images.githubusercontent.com/17485541/59626228-bc3b8680-9111-11e9-80ab-53dda7066542.png)

Validation layer warning:
![image](https://user-images.githubusercontent.com/17485541/59626455-4be13500-9112-11e9-9c53-04f607f4b5bd.png)

I have also double checked to see if i'm reading the file correctly, and yes, it seems that everything is ok.

**Comment by johnkslang** [comment]
It will help to see text instead of graphics, but a size of 323 likely indicates things not hooked up right, or grabbing the wrong result, or something like that:  The blog shows the SPIR-V in 

```
std::vector<unsigned int> SpirV;
```

So, it's hard to see that as not being a multiple of 4.

**Comment by Kadowns** [comment]
Oh, sorry, i'll only be posting text when refering to code from now on.
So, as i said before, my shader compiler is basically the same as the one on the blog post:
`
std::vector<uint32_t> VulkanShaderCompiler::compile_glsl(const std::string &fileName) {

    //initializes glslang
    if (!m_glslangIntitialized) {
        if (!glslang::InitializeProcess()){
            EG_CORE_FATAL("Failed to initialize vulkan shader compiler!");
            throw std::runtime_error("Failed to initialize vulkan shader compiler!");
        }
        m_glslangIntitialized = true;
    }

    //get correct shade stage based on file suffix
    EShLanguage shaderStage = get_shader_stage(get_suffix(fileName));

    //creates shader object based on shader stage
    glslang::TShader shader(shaderStage);


    std::ifstream file(fileName, std::ios::ate);
    if (!file.is_open()) {
        EG_CORE_FATAL_F("Failed to load shader: {0}", fileName);
        throw std::runtime_error("failed to open file: " + fileName);
    }

    //reads glsl file and stores on a const char* (otherwise it would not be possible to set the shader strings with a temporary value)
    size_t fileSize = (size_t) file.tellg();
    std::vector<char> buffer(fileSize);
    file.seekg(0);
    file.read(buffer.data(), fileSize);
    file.close();
    const char* cstrInput = buffer.data();

    shader.setStrings(&cstrInput, 1);


    //environment definitions
    int ClientInputSemanticsVersion = 100; // maps to, say, #define VULKAN 100
    glslang::EShTargetClientVersion VulkanClientVersion = glslang::EShTargetVulkan_1_0;
    glslang::EShTargetLanguageVersion TargetVersion = glslang::EShTargetSpv_1_0;

    shader.setEnvInput(glslang::EShSourceGlsl, shaderStage, glslang::EShClientVulkan, ClientInputSemanticsVersion);
    shader.setEnvClient(glslang::EShClientVulkan, VulkanClientVersion);
    shader.setEnvTarget(glslang::EShTargetSpv, TargetVersion);

    TBuiltInResource resources = DefaultTBuiltInResource;
    EShMessages messages = EShMsgDefault;

    const int DefaultVersion = 100;


    //preprocessing of the glsl shader (includes all files into the actual glsl string)
    DirStackFileIncluder includer;

    std::string path = get_file_path(fileName);
    includer.pushExternalLocalDirectory(path);

    std::string preprocessedGLSL;

    if (!shader.preprocess(&resources, DefaultVersion, ENoProfile, false, false, messages, &preprocessedGLSL, includer)) {
        EG_CORE_FATAL_F("GLSL Preprocessing Failed for: {0}\n Log: {1}\n DebugLog: {2}", fileName, shader.getInfoLog(), shader.getInfoDebugLog());
    }

    //updates shader strings with preprocessed glsl file
    const char* preprocessedCStr = preprocessedGLSL.c_str();
    shader.setStrings(&preprocessedCStr, 1);

    //parses the shader
    if (!shader.parse(&resources, 100, false, messages)) {
        EG_CORE_FATAL_F("GLSL Parsing Failed for: {0}\n Log: {1}\n DebugLog: {2}", fileName, shader.getInfoLog(), shader.getInfoDebugLog());
    }

    glslang::TProgram program;
    program.addShader(&shader);

    //links program with shader
    if(!program.link(messages)) {
        EG_CORE_FATAL_F("GLSL Linking Failed for: {0}\n Log: {1}\n DebugLog: {2}", fileName, shader.getInfoLog(), shader.getInfoDebugLog());
    }

    //converts glslang program to spirv format
    std::vector<unsigned int> SpirV;
    spv::SpvBuildLogger logger;
    glslang::SpvOptions spvOptions;
    glslang::GlslangToSpv(*program.getIntermediate(shaderStage), SpirV, &logger, &spvOptions);
    EG_CORE_FATAL_F("Result: {0}", logger.getAllMessages());

    return SpirV;
}
`
The result of the function above is stored on my actual VulkanShader class

`m_vertShaderCode = VulkanShaderCompiler::compile_glsl(PROJECT_ROOT + vertFileName);`

i've also debugged to see what kind of value is store inside m_vertShaderCode, and it seems pretty normal
![image](https://user-images.githubusercontent.com/17485541/59649777-28da7380-915a-11e9-87ad-8ecfd3f4c34a.png)
but as you can see, it has a size of 323 (tell me if it's relevant to post the entire vector content)

Then, the vector is later used to create a shader module, and that's when the validation layers start complaining about the size of the shader code
`
    VkShaderModuleCreateInfo createInfo = {};

    createInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;

    createInfo.codeSize = code.size();

    createInfo.pCode = code.data();

    VkShaderModule shaderModule;
    VK_CALL_ASSERT(vkCreateShaderModule(m_createInfo.device, &createInfo, nullptr, &shaderModule))`

`code.size()` returns 323, as it is the size of the vector generated in compile_glsl function

**Comment by johnkslang** [comment]
Very briefly, in case it helps (I didn't look deeply yet): The size must be a multiple of 4 when measured in bytes.  It does not need to be a multiple of 4 integers.  I wonder if the API somewhere needs a byte size instead of an integer size, like there is a missing `4 *` somewhere.

**Comment by Kadowns** [comment]
there we go
![image](https://user-images.githubusercontent.com/17485541/59681826-3409bf80-91ab-11e9-938c-ad18ddfa5506.png)

So, it come as no surprise, i was just being dumb.
I indeed forgot to multiply code.data() with the size of uint32_t, basically because before using glslang, i've been using glslangValidator to produce SPIRV binaries, and i stored the data of this files in a std::vector<char>, witch are 1 byte in size each, so the total size was always right when using code.size(),

Many thanks, and sorry for not realising this before
