### ISSUE TITLE
Specialization Constants Don't Work as Array Indices

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/glslang#1815]
I have some HLSL code that uses a spec constant to access an element of a constant array.

```
struct VS_Output
{
    float4 pos : SV_POSITION;
    float2 uv : ATTR0;
};

 cbuffer ScreenParams : register( b0 )
{
    float2 pixelSize;
    float u_phase;
    uint flip;
};

 Texture2D< float4 > tex : register( t2 );
sampler bilinearSamp : register( s3 );

[[vk::constant_id( 0 )]] const uint kernelRadius = 1;

static const uint maxKernelRadius = 6;
static const uint kernelSizes[] = { 1, 4, 9, 18, 29, 46, 63 };
static const uint maxKernelSize = kernelSizes[ maxKernelRadius ];

 cbuffer BlurData : register( b1 )
{
    float4 samples[ 63 ];
};

 float4 Blur_PS( VS_Output input ) :
    SV_TARGET
{
    float4 c = 0;

     for( uint i = 0; i < kernelSizes[ kernelRadius ]; i++ )
    {
        c += samples[ i ].z * tex.Sample( bilinearSamp, input.uv + samples[ i ].xy );
    }

     return c;
}
```

This generates code that uses the default value of the specialization constant as the array index in the for loop condition, always, regardless of what value is provided for the spec const at runtime.

Playground link: http://shader-playground.timjones.io/48da5aac3ae3ef8c57cfbcc32ebe8352

When switching to Microsoft DXC as the shader compiler, the generated code looks like what I would expect (i.e. the constant is used as the array index, not its default value).

**Comment by johnkslang** [comment]
It looks like glslang constant folded the access when it should not have.  Trying it with GLSL, glslang did not do that.  Does Microsoft DXC even support specialization constants?

I'll look at fixing it.

In the meantime, it would be less stressful on the tool chain to just make the specialization constant be the radius rather than having a mostly dead array to manage.

**Comment by nicebyte** [comment]
>  Does Microsoft DXC even support specialization constants?

I believe so, since I see `SpecId` and `OpSpecConstant` in the generated SPIR-V for that piece of code.

**Comment by johnkslang** [comment]
Ah, of course, I was thinking of a different code base.

I'm checking in a fix soon for glslang, though I don't recall that we'd invested in testing specialization constants for HLSL.

**Comment by nicebyte** [comment]
Thanks John!
