### ISSUE TITLE
Question: Can AST transform back to GLSL codes?

### ISSUE THREAD

**Issue by lishi0927** [KhronosGroup/glslang#1820]
I have read the source code in this project and I know an example in the glslangvalidator.cpp to parser the GLSL codes into an AST.
And now I want to know if the glslang project has achieved that AST can be transformed back to GLSL codes?
Thank you.

**Comment by johnkslang** [comment]
Yes, this should be entirely possible, as the AST retains original type information.

Others have made tools that can cross between many languages, via SPIR-V.  See for example https://github.com/KhronosGroup/SPIRV-Cross.
