### ISSUE TITLE
8- and 16-bit storage extensions generate invalid constants

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#1828]
#1827 updates SPIRV-Tools to include validation of 8- and 16-bit storage extensions. The validator flags glslang's constant generation for these tests as generating constants of the incorrect types. It should instead generate 32-bit type constants and use conversion instructions.

**Comment by johnkslang** [comment]
How is it working on drivers today?  Is it possible the changes should go the other direction?
