### ISSUE TITLE
glslang generates OpModuleProcessed with no corresponding command line

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#1829]
glslang can emit `OpModuleProcessed "use-storage-buffer"` but `--use-storage-buffer` isn't a valid command line parameter - I think it might just need to be hooked up as such but I'm not quite sure how this gets generated.

**Comment by johnkslang** [comment]
I think that's just through a #1821 

```
#pragma use_storage_buffer
```

**Comment by baldurk** [comment]
(Is the issue link a typo? I'm not sure how it's related)

My understanding was that glslang maintained a strong convention that anything it adds in `OpModuleProcessed` can be passed as a command-line parameter for programs to use to reconstruct the compilation environment of the original shader. If there are exceptions to that then each tool using those directives will have to maintain a list of exceptions or some translation.

For what it's worth the shader I ran into with this doesn't have that `#pragma` in it so the bit may have been set directly through the programmatic compilation interface.

**Comment by johnkslang** [comment]
> (Is the issue link a typo? I'm not sure how it's related)

Looks like GitHub auto completed my `#pragma` to something else!

I agree that this should follow the same convention as everything else; there was some historical timing reason this one was done this way (I remember the decision, not the reason).

**Comment by johnkslang** [comment]
After looking at the code, it is not clear there should be a module processed for this, unless it was selected through the pragma.

How are you seeing it?

I suspect the answer here is not to add the command-line option, but rather to not emit the OpModuleProcessed.  It looks like it's emitted in more situations than necessary.

**Comment by baldurk** [comment]
I found it on a user shader unfortunately, so I don't know exactly what the compilation environment was - I only have the source.

I had a quick look before filing the issue and it seems like `setUseStorageBuffer()` will be called for all shaders targetting SPIR-V 1.3. Is that what you mean that it's added more often than it should be?

**Comment by johnkslang** [comment]
Yes, partly: for 1.3, the command line should just be asking for 1.3, not also asking for use-storage-buffer.

It's also triggered now by the `buffer_reference` layout qualifier, which also should not come with a command-line option.

**Comment by baldurk** [comment]
A related case I just hit, for macro definitions glslang emits `OpModuleProcessed DNAME=VALUE` but that also doesn't fit the scheme because `--DNAME=VALUE` doesn't work (and strangely doesn't output an error - it just prints the help). AFAIK all the `OpModuleProcessed` specifying command line parameters should be prefixable with `--`, otherwise tools need to parse and have knowledge of glslang's command line parameters.

Hopefully this can be cleaned up with some shiny new non-semantic info, but it'll be a while before that's usable so fixing these would be nice in the interim.

**Comment by johnkslang** [comment]
Yeah, so `-D` is pretty standard and `--D` is not accepted, so printing the usage is the error message.  I'll start by adding a better error message.

**Comment by johnkslang** [comment]
Is it standard to have "--" for D?  I see gcc reject it.

I guess glslang could accept "--D" same as "-D".  Any better ideas?

**Comment by baldurk** [comment]
No I'm not aware of any compiler that uses `--D` for macro definitions. The problem isn't with `-D` existing, the problem is that without knowing all of glslang's command line options it's not possible to be 'smart' about remapping OpModuleProcessed to command line options and doing the right thing depending on what is seen. Instead I prepend -- to all `OpModuleProcessed` and assume that the convention holds in all cases. I thought that was how `OpModuleProcessed` command parameters were intended to be used.

I think perhaps a simpler solution would be to add a long-form `--macro-define NAME=VAL` option, and then emit `OpModuleProcessed macro-define NAME=VAL` instead. I don't think there's anything which says the `OpModuleProcessed` needs to map 1:1 with any particular options, and indeed I think it already doesn't.

**Comment by johnkslang** [comment]
Yes, I'm fine with moving toward everything works with "--".

I think it would be okay for `-D` and `--D` to alias, given how standard it is.  but `--define-macro` and `--undef-macro` would work.  Any final opinion between these two choices?

**Comment by baldurk** [comment]
`--define-macro` and `--undef-macro` sound good to me.

**Comment by johnkslang** [comment]
I like it too, unless it breaks anyone to just change to that in the emitted SPIR-V, in which case `--D` and `--U` would win.

**Comment by johnkslang** [comment]
I realized an "all of the above" strategy works alongside with options being passed through faithfully.

**Comment by johnkslang** [comment]
#2052 allows `--define-macro <name[=def]>` and `--D <name[=def]>` as is the convention for `--`, which uses a space.

This still doesn't allow just putting a `--` in front of the `OpModuleProcessed` string, which does not have a space.  That would mean removing all words that start with D and U from the `--` namespace.

What do you recommend?

- allowing `--U<name>` (no space) and hence no other `--` option can start with a `U`, or
- changing the output of the `OpModuleProcessed` string to include a space?

**Comment by baldurk** [comment]
My preference would be for the second option, fixing `OpModuleProcessed` to follow the rule of emitting un-prefixed command line arguments directly. Unless someone is relying on `OpModuleProcessed` emitting the `-D` form and is unable to handle it changing to `--define-macro` with a space then it's more consistent. Such a consumer would also presumably fail anyway if any new command line argument was added in `OpModuleProcessed`.

**Comment by johnkslang** [comment]
Yes, it makes sense if done hand-in-hand with changing to that spelling.

**Comment by baldurk** [comment]
Someone ran just into the original issue - that glslang produces `OpModuleProcessed "use-storage-buffer"` when targetting SPIR-V 1.3 but that's not a valid command line argument (`--use-storage-buffer`).

That still seems to be the case on latest code, should this issue be re-opened?

**Comment by johnkslang** [comment]
So, I'm eliminating the `OpModuleProcessed use-storage-buffer` stuff, because now it should always be a side effect of doing something else that itself is requested.  If this isn't the case, we should fix that.
