### ISSUE TITLE
Crash parsing gl_DepthRangeParameters builtin

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/glslang#1848]
In a specific setup (*), I get crash in glslang when parsing `gl_DepthRangeParameters` builtin.
```
struct gl_DepthRangeParameters {highp float near;highp float far;highp float diff;};
```
The crash happens in this grammar rule:
```
struct_declaration
...
    | type_qualifier type_specifier struct_declarator_list SEMICOLON {
        if ($2.arraySizes) {
            parseContext.profileRequires($2.loc, ENoProfile, 120, E_GL_3DL_array_objects, "arrayed type");
            parseContext.profileRequires($2.loc, EEsProfile, 300, 0, "arrayed type");
            if (parseContext.profile == EEsProfile)
                parseContext.arraySizeRequiredCheck($2.loc, *$2.arraySizes);
        }

        $$ = $3;

        parseContext.memberQualifierCheck($1);
        parseContext.voidErrorCheck($2.loc, (*$3)[0].type->getFieldName(), $2.basicType);
        parseContext.mergeQualifiers($2.loc, $2.qualifier, $1.qualifier, true);
        parseContext.precisionQualifierCheck($2.loc, $2.basicType, $2.qualifier);

        for (unsigned int i = 0; i < $$->size(); ++i) {
            TType type($2);
            type.setFieldName((*$$)[i].type->getFieldName());
            type.transferArraySizes((*$$)[i].type->getArraySizes());
            type.copyArrayInnerSizes($2.arraySizes);
            parseContext.arrayOfArrayVersionCheck((*$$)[i].loc, type.getArraySizes());
            (*$$)[i].type->shallowCopy(type);
        }
    }
    ;
```
Specifically, call to `transferArraySizes()` gets invalid pointer: `(*$$)[i].type->getArraySizes() == 0xfffff800` and accessing that memory later (in `parseContext.arrayOfArrayVersionCheck()`) causes segmentation fault.
Context:
- `$2.arraySizes = false`
- `i = 0`
- `(*$$)[i].type->getFieldName() = "near"`
- tail of yydebug is
```Entering state 548
Reducing stack by rule 497 (line 3348):
   $1 = nterm struct_declarator ()
-> $$ = nterm struct_declarator_list ()
Stack now 0 355 324 360 392 453 454 545
Entering state 622
Next token is token SEMICOLON ()
Shifting token SEMICOLON ()
Entering state 665
Reducing stack by rule 496 (line 3321):
   $1 = nterm type_qualifier ()
   $2 = nterm type_specifier ()
   $3 = nterm struct_declarator_list ()
   $4 = token SEMICOLON ()
```
(*): I have not been able to identify any issue in the setup external to glslang; Very little code other than glslang is executed. Unfortunately I am unable provide repro case: Doing the same thing with Standalone, the pointer `(*$$)[i].type->getArraySizes()` passed to `transferArraySizes()` has value `nullptr`.

I understand that this issue may not be in glslang and the information I have given might not be sufficient. I thought it might be useful to post this anyway, in case there is some issue in the grammar rule for example, as I do not quite follow it. Thanks!.

**Comment by johnkslang** [comment]
`type` comes from

```
struct_declarator
    : IDENTIFIER {
        $$.type = new TType(EbtVoid);
```

That constructor sets `arraySizes` to `nullptr`, then it gets pushed onto the list in `struct_declarator_list` that then gets processed in the `for` loop of the code you posted.

How it would change to -2048 I don't see, but you could potentially watch/print its value at those steps and see where it breaks down.

**Comment by tsuoranta** [comment]
I added debug prints here and there, and noticed that the address of arraySizes member is different in TType::TType constructor vs. TType::getArraySizes().
```
explicit TType::TType(): this = 0x7db668, &arraySizes = 0x7db6b0
```
vs.
```
TType::getArraySizes(): this = 0x7db668, &arraySizes = 0x7db6a8
```
This would make tail of previous field (qualifier) show up as arraySizes pointer.

How this can happen, I do not yet know. Both TType::TType() and TType::getArraySizes() are in same file, Types.h. I suppose compiler might inline them differently to different places.

**Comment by johnkslang** [comment]
The data structures have things like `#ifdef NV_EXTENSIONS` in them.  If you compiled different files inconsistently, you'd get this problem.

Make sure you have a clean build and everything builds consistently.  The value `0xfffff800` does look like it could come from the middle of TQualifier.

**Comment by tsuoranta** [comment]
Indeed, I discovered `-DAMD_EXTENSIONS -DENABLE_HLSL -DENABLE_OPT=0 -DGLSLANG_OSINCLUDE_UNIX -DNV_EXTENSIONS` are in library build and those are not currently set in the main binary.

**Comment by johnkslang** [comment]
You must build everything the same way.  I'm working on reducing this problem, but, still, your usage and the libraries must be built under the same rules.

**Comment by arcady-lunarg** [comment]
Looks like this was an error due to a mismatch in compile options. Note that the `AMD_EXTENSIONS` and `NV_EXTENSIONS` options have since been removed. @tsuoranta feel free to open a new issue if you have any further problems.
