### ISSUE TITLE
glslang -> Chromium roll fails with compiler warning

### ISSUE THREAD

**Issue by null77** [KhronosGroup/glslang#1850]
See for example https://chromium-review.googlesource.com/c/chromium/src/+/1714279

 [376/6278] CXX obj/third_party/glslang/src/glslang_sources/iomapper.o
    FAILED: obj/third_party/glslang/src/glslang_sources/iomapper.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_par...
    ../../third_party/glslang/src/glslang/MachineIndependent/iomapper.cpp:294:11: error: field 'infoSink' will be initialized after field 'currentStage' [-Werror,-Wreorder]
    , infoSink(i)
    ^
    ../../third_party/glslang/src/glslang/MachineIndependent/iomapper.cpp:295:11: error: field 'currentStage' will be initialized after field 'preStage' [-Werror,-Wreorder]
    , currentStage(EShLangCount)
    ^
    2 errors generated.

Would it be possible to either suppress these warnings in the GN file or to add the warning to the CMake build and fix it? This is currently blocking the roller.

**Comment by null77** [comment]
@dneto0 fyi

**Comment by johnkslang** [comment]
This complaint is about code that was just reverted for test-case failures.  Will ask for this to be fixed as well.
