### ISSUE TITLE
Why does glslang use relaxed precision for findLSB on literals?

### ISSUE THREAD

**Issue by afd** [KhronosGroup/glslang#1851]
If I turn the following shader into SPIR-V using the -V option:

```
#version 310 es
precision highp int;

void main() {
  int zero = 0;
  findLSB(1 << zero);
  findLSB(1 << 0);
}
```

I get:

```
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main"
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
               OpName %4 "main"
               OpName %8 "zero"
               OpDecorate %14 RelaxedPrecision
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeInt 32 1
          %7 = OpTypePointer Function %6
          %9 = OpConstant %6 0
         %10 = OpConstant %6 1
          %4 = OpFunction %2 None %3
          %5 = OpLabel
          %8 = OpVariable %7 Function
               OpStore %8 %9
         %11 = OpLoad %6 %8
         %12 = OpShiftLeftLogical %6 %10 %11
         %13 = OpExtInst %6 %1 FindILsb %12
         %14 = OpExtInst %6 %1 FindILsb %10
               OpReturn
               OpFunctionEnd
```

%14 is decorated with RelaxedPrecision, but %13 is not.  The only difference between them is that in the GLSL, the second findLSB invocation uses a compile-time constant, 1 << 0, whereas a variable, zero, is used in the first findLSB invocation.

Is this glslang behaviour intentional?

**Comment by johnkslang** [comment]
The rules are complex.  Constants are agnostic of precision until another rule imposes a precision on them, while findLSB has a declared precision of `lowp` (later versions of the spec became more nuanced about return value versus operation precision).

So, in your case, you had:

```
lowp findLSB(highp(1))
lowp findLSB(agnostic(1))
```

The agnostic one took a cue from the declared `lowp`.

**Comment by afd** [comment]
OK, thanks - that makes sense.
