### ISSUE TITLE
A way of ensuring all uniforms/variables are kept, even if not used?

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/glslang#1854]
When using Vulkan and compiling to SPIR-V, I may want to have different shaders but compatible layouts for different descriptor sets. If, in some shaders, some uniforms are not used it seems GLSLang will just wipe them out via the optimizer, which makes descriptor sets and pipeline layouts incompatible.

Is there any way to force GLSLang to keep those (and show them in the reflection API too) even if removed or optimized away from code?

**Comment by johnkslang** [comment]
Is this with GLSL or HLSL?  (Asking in relation to the required run of the spirv-opt for legalization.)

Are you seeing things disappear in the SPIR-V, or just in the reflection?

Generally agreed that glslang should not be changing interfaces, and also don't think it is, but would need an example.

I do know the original purpose for the reflection code was to explicitly filter out some unused interface elements.  That was not for the purpose of changing the interface, but for the purpose of knowing what was live and had to be set by the API.

**Comment by johnkslang** [comment]
BTW, are you using (or aware of) options like this?

```
  --reflect-all-block-variables 
```

**Comment by reduz** [comment]
I'm using GLSLang embedded and trying with:

program.buildReflection(EShReflectionAllBlockVariables);

But it doesn't seem to make a difference, specially if the variable is not used in code (behind ifdef), even if properly declared as uniform in global scope.

**Comment by reduz** [comment]
Trying to explain in a little more detail, imagine I have this:
```
layout(set=1,binding=2) uniform texture2D mytexture1;
layout(set=1,binding=3) uniform texture2D mytexture2;
```

On Shader A.GLSL, I use mytexture1 but not mytexture2. Both are declared in code, though.
On Shader B.GLSL, I use mytextyre2 but not mytexture1. Both are also declared in code.

Since the rest of the shaders and uniforms are similar, I want to reuse the descriptor pool and descriptor set for both during the run of the drawing. The problem is, if this uniform is not used, GLSLang removes it. 

As I build the descriptor set layout from the reflection, I end up with two different descriptor formats.

**Comment by johnkslang** [comment]
Glslang specifically *does not* prune interfaces just because they are used, and has extra code to ensure that.  For the code:

```
#version 450

layout(set=1,binding=2) uniform texture2D mytexture1;
layout(set=1,binding=3) uniform texture2D mytexture2;

void main() { }
```

glslang -H emits:

```
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 11

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main"
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "mytexture1"
                              Name 10  "mytexture2"
                              Decorate 9(mytexture1) DescriptorSet 1
                              Decorate 9(mytexture1) Binding 2
                              Decorate 10(mytexture2) DescriptorSet 1
                              Decorate 10(mytexture2) Binding 3
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeImage 6(float) 2D sampled format:Unknown
               8:             TypePointer UniformConstant 7
   9(mytexture1):      8(ptr) Variable UniformConstant
  10(mytexture2):      8(ptr) Variable UniformConstant
         4(main):           2 Function None 3
               5:             Label
                              Return
                              FunctionEnd
```

Both interface elements are present.
