### ISSUE TITLE
Can OpenGL ES transform into Spir-V

### ISSUE THREAD

**Issue by lishi0927** [KhronosGroup/glslang#1856]
I want to parse the AST from the OpenGL ES shaders and transform them into SPIR-V, and I use glslangValidator project with -G parameters.  But the output shows "Error: #version: ES shaders for OpenGL SPIR-V are not supported".
Are there other functions or parameters to achieve this application？
Thank you.

**Comment by johnkslang** [comment]
There is not much fundamentally preventing this.  ESSL can target Vulkan SPIR-V already.  It's probably just a matter of disabling the error message you are getting.

What version of ESSL are you using?  Do you want to test removing the error message?

The error exists, because only OpenGL desktop accepts SPIR-V (not OpenGL ES), but I could certainly see relaxing that, possibly with an option, given that both ESSL - >Vulkan exists and that OpenGL desktop accepts ESSL source; it's just the cross product of those two.

**Comment by lishi0927** [comment]
Thank you for your reply.
I use OpenGL ES 3.2. 
The code is very simple, just shown as following:
***************************************************
#version 320 es

precision mediump float;
uniform highp vec4 sk_RTAdjust;
in highp vec2 position;
in highp vec2 textureCoords;
in mediump vec4 color;
flat out mediump vec4 vcolor_Stage0;
out highp vec2 vtextureCoords_Stage0;
void main() {
    highp vec2 pos2 = position;
    vcolor_Stage0 = color;
    vtextureCoords_Stage0 = textureCoords;
    gl_Position = vec4(pos2.x, pos2.y, 0.0, 1.0);
    gl_Position = vec4(gl_Position.x * sk_RTAdjust.x + gl_Position.w * sk_RTAdjust.y, gl_Position.y * sk_RTAdjust.z + gl_Position.w * sk_RTAdjust.w, 0.0, gl_Position.w);
}
***************************************************

**Comment by xiaoqiang-wang** [comment]
@lishi0927 @johnkslang 

😀  Hello, my friend, 
I'm trying to use glslangValidator convert OpenGL ES shader to SPIR-V too.

#### But I got below error message.
````
ERROR: #version: ES shaders for Vulkan SPIR-V require version 310 or higher
ERROR: temp_shader.vert:18: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan
ERROR: temp_shader.vert:18: '' : missing #endif
ERROR: 3 compilation errors.  No code generated.
````
#### After I manully change the verison,  another error occur
```
ERROR: temp_shader.vert:18: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan
ERROR: temp_shader.vert:18: '' : missing #endif
ERROR: 2 compilation errors.  No code generated.


ERROR: Linking vertex stage: Missing entry point: Each stage requires one entry point
```


#### I can't find below key word in the "./glslang/Public/ShaderLang.h"

```
 "correct = false" and "version = 310" 
```

#### Q1. How to change the glslangValidator source code to disable those message, and generate a SPIR-V for below OpenGL ES shader?






#### Below is my shader
```
#version 300 es
#define SHADOW_MAP
#define SOFT_SHADOW
#define SV_30
#ifdef GL_ES
precision highp float;
#endif
#ifndef GL_ES
#define highp
#define mediump
#define lowp
#endif
#ifdef USE_UBOs
	#include cameraConsts;
	#include meshConsts;
	#include staticMeshConsts;
#else
	uniform highp mat4 mvp;
	uniform highp mat4 mv;
	uniform highp mat4 model;
	uniform highp vec3 view_pos;
#endif

in vec3 in_position;
in vec2 in_texcoord0;

#ifdef INSTANCING
//in mat4 in_instance_mv;
in vec4 in_instance_mv0;
in vec4 in_instance_mv1;
in vec4 in_instance_mv2;
in vec4 in_instance_mv3;

in mat4 in_instance_inv_mv;
#endif
	
out vec2 out_texcoord0;


void main()
{    
	vec3 up; 
	vec3 right;
	vec3 fwd;

#ifdef INSTANCING
	mat4 in_instance_mv = mat4(in_instance_mv0, in_instance_mv1, in_instance_mv2, in_instance_mv3);
#endif
	
#ifdef AALIGNED	
	up = vec3( 0.0, 1.0, 0.0);
#else
	up = vec3( mv[0][1], mv[1][1], mv[2][1]);
#endif

	right = vec3( mv[0][0], mv[1][0], mv[2][0]);
	
#ifdef USE_UBOs
	vec3 delta = vec3( model[3][0], model[3][1], model[3][2]) - view_posXYZ_normalized_time.xyz;
#else
	vec3 delta = vec3( model[3][0], model[3][1], model[3][2]) - view_pos;
#endif
	delta = normalize( delta);

	vec3 position = in_position.x * right + in_position.y * up + in_position.z * delta;

#ifdef INSTANCING
    mat4 mvp2 = mvp * in_instance_mv;

	gl_Position = mvp2 * vec4( position, 1.0);
#else
	gl_Position = mvp * vec4( position, 1.0);
#endif

	out_texcoord0 = in_texcoord0;
}
```

**Comment by greg-lunarg** [comment]
Are you targeting Vulkan or OpenGL?

**Comment by xiaoqiang-wang** [comment]
@greg-lunarg 
Thanks  for your reply my friend.
 
I want to convert to OpenGL ES shader to LLVM IR,  and do some optimization to IR.
but there is no Open Source Compiler for OpenGL  ES shader.


So I'm trying to convert OpenGL ES shader to SPIRV-V,  then the SPIR-V can be accepted by  "amdllpc" (AMD open source compiler, base on LLVM).

**Comment by greg-lunarg** [comment]
This command line works (with the change to 310 es):

`glslangValidator.exe -G --target-env spirv1.5 --aml -o t.vert.spv t.vert`

**Comment by xiaoqiang-wang** [comment]
@greg-lunarg 
: ) 
Thank a lot, a lot of shader need to change mannully...
