### ISSUE TITLE
Is block data size for std140 implementation dependent or not?

### ISSUE THREAD

**Issue by YunHsiao** [KhronosGroup/glslang#1864]
I'm having a really hard time finding any specification on block data size for std140 layout.
The best explanation I came about is that it's not really part of the standard, thus implementation dependent, which is not a wise choice, IMHO.

**Comment by YunHsiao** [comment]
According to the ES 3.0 spec:

> If pname is UNIFORM_BLOCK_DATA_SIZE, then the implementation-
> dependent minimum total buffer object size, in basic machine units, required to
> hold all active uniforms in the uniform block identified by uniformBlockIndex is
> returned. It is neither guaranteed nor expected that a given implementation will
> arrange uniform values as tightly packed in a buffer object. The exception to this
> is the std140 uniform block layout, which guarantees specific packing behavior
> and does not require the application to query for offsets and strides. In this case the
> minimum size may still be queried, even though it is determined in advance based
> only on the uniform block declaration (see “Standard Uniform Block Layout” in
> section 2.12.6.4).

But no where in 2.12.6.4 even mentioned UNIFORM_BLOCK_DATA_SIZE.

**Comment by johnkslang** [comment]
It is very well defined, by a somewhat difficult recursive definition in the API specification.  I happen to have it handy in my code; but I'm sure you can now find it in the spec:

```
    // When using the std140 storage layout, structures will be laid out in buffer
    // storage with its members stored in monotonically increasing order based on their
    // location in the declaration. A structure and each structure member have a base
    // offset and a base alignment, from which an aligned offset is computed by rounding
    // the base offset up to a multiple of the base alignment. The base offset of the first
    // member of a structure is taken from the aligned offset of the structure itself. The
    // base offset of all other structure members is derived by taking the offset of the
    // last basic machine unit consumed by the previous member and adding one. Each
    // structure member is stored in memory at its aligned offset. The members of a top-
    // level uniform block are laid out in buffer storage by treating the uniform block as
    // a structure with a base offset of zero.
    //
    //   1. If the member is a scalar consuming N basic machine units, the base alignment is N.
    //
    //   2. If the member is a two- or four-component vector with components consuming N basic
    //      machine units, the base alignment is 2N or 4N, respectively.
    //
    //   3. If the member is a three-component vector with components consuming N
    //      basic machine units, the base alignment is 4N.
    //
    //   4. If the member is an array of scalars or vectors, the base alignment and array
    //      stride are set to match the base alignment of a single array element, according
    //      to rules (1), (2), and (3), and rounded up to the base alignment of a vec4. The
    //      array may have padding at the end; the base offset of the member following
    //      the array is rounded up to the next multiple of the base alignment.
    //
    //   5. If the member is a column-major matrix with C columns and R rows, the
    //      matrix is stored identically to an array of C column vectors with R
    //      components each, according to rule (4).
    //
    //   6. If the member is an array of S column-major matrices with C columns and
    //      R rows, the matrix is stored identically to a row of S X C column vectors
    //      with R components each, according to rule (4).
    //
    //   7. If the member is a row-major matrix with C columns and R rows, the matrix
    //      is stored identically to an array of R row vectors with C components each,
    //      according to rule (4).
    //
    //   8. If the member is an array of S row-major matrices with C columns and R
    //      rows, the matrix is stored identically to a row of S X R row vectors with C
    //      components each, according to rule (4).
    //
    //   9. If the member is a structure, the base alignment of the structure is N , where
    //      N is the largest base alignment value of any    of its members, and rounded
    //      up to the base alignment of a vec4. The individual members of this substructure
    //      are then assigned offsets by applying this set of rules recursively,
    //      where the base offset of the first member of the sub-structure is equal to the
    //      aligned offset of the structure. The structure may have padding at the end;
    //      the base offset of the member following the sub-structure is rounded up to
    //      the next multiple of the base alignment of the structure.
    //
    //   10. If the member is an array of S structures, the S elements of the array are laid
    //       out in order, according to rule (9).
    //
    //   Assuming, for rule 10:  The stride is the same as the size of an element.
```

**Comment by YunHsiao** [comment]
Thank you for clarifying. I'm well aware of all the definitions, but there is no mentioning of **UNIFORM_BLOCK_DATA_SIZE** in this exact paragraph or any other places, it just elaborated how the block members will be layed out.

**Comment by johnkslang** [comment]
The last sentence of the introductory paragraph to the rules might hold a clue:

> The members of a top-level uniform block are laid out in buffer storage by treating the uniform block as a structure with a base offset of zero.

Looking at the structure rule (9):

> The structure may have padding at the end; the base offset of the member following the sub-structure is rounded up to the next multiple of the base alignment of the structure.

From a glslang perspective, maybe it is ambiguous whether the possible padding at the end is backed by memory or not.

I think this is either a Vulkan or OpenGL specification issue, and not a glslang issue.  Glslang computes an appropriate size for the block, which I think you can use if you want to.
