### ISSUE TITLE
More ClipDistance confusion

### ISSUE THREAD

**Issue by ben-clayton** [KhronosGroup/glslang#1868]
After reading related issues #240, #325, #472, I see that a `ClipDistance` output will be declared even if it isn't used - it's the capability that gets enabled / disabled when used. Okay.

However, I think there's a bit of a mismatch with the Vulkan spec. Under [23.2. Primitive Clipping](https://www.khronos.org/registry/vulkan/specs/1.1/html/chap23.html#vertexpostproc-clipping):

> A shader **must** write a single clip distance for each enabled clip half-space to elements of the `ClipDistance` array.

> The number of client-defined clip and cull half-spaces that are enabled is determined by the explicit size of the built-in arrays `ClipDistance` and `CullDistance`, respectively, declared as an output in the interface of the entry point of the final shader stage before clipping.

Under [30. Features](https://www.khronos.org/registry/vulkan/specs/1.1/html/chap30.html#features-shaderClipDistance) we have:

> shaderClipDistance specifies whether clip distances are supported in shader code. If this feature is not enabled, any members decorated with the `ClipDistance` built-in decoration **must** not be read from or written to in shader modules. This also specifies whether shader modules **can** declare the `ClipDistance` capability.

It seems to be that the must-write rules of `23.2. Primitive Clipping` is missing a get-out clause for declaring the `ClipDistance` array without having the `ClipDistance` capability set.

Am I missing something?

Cheers!

**Comment by johnkslang** [comment]
Agreed the Vulkan spec should not be dictating anything base on declaration of the built-in, but rather by declaration of the capability (which in turn is not required unless that ability is actually taken advantage of, through load/store): You need to really use the functionality to be required to declare the capability (for clip/cull-distance).

The "mainstream" usages are either
- that these are implicitly included whether used or not, for interface matching purposes, and that alone should not trigger need for the capability (here the size wants to be 0 but might get bumped to 1)
- that these are actually used and hence redeclared with a size or implicitly given a real size via glslang tracking maximum used index

There are other Vulkan issues around the subtleties of how big the arrays are.

But, I don't see a glslang issue here.  I think this is a specification issue, regarding the apparent contradictions.

**Comment by ben-clayton** [comment]
Thanks John, that aligns with my conclusions.
I agree this isn't a glslang issue then. Closing.
