### ISSUE TITLE
Validator not checking for functions dropping non-droppable qualifiers

### ISSUE THREAD

**Issue by solidpixel** [KhronosGroup/glslang#1870]
We've seen a mismatch between what `glslangValidator` accepts, and what the Mali shader compiler accepts in relation to qualifiers getting dropped in function calls. 

In particular we think this test shader should fail to validate because the `readonly` qualifier for the buffer is not explicitly enumerated in the function call. Currently `glslangValidator` accepts it, but Mali's shader compiler rejects it.

```
#version 310 es
precision mediump float;

layout(std430, binding=2) readonly buffer MyBuff {
	float buff[10];
} myBuff;

float myFunction(float[10] buff) {
	return buff[0];
}

out vec4 fragColor;

void main() {
	fragColor = vec4(myFunction(myBuff.buff));
}
```

The relevant part of the ESSL 3.2 specification, section 4.10 is:

> When calling user-defined functions, variables qualified with [...] readonly [...] may not be passed to functions whose formal parameters lack such qualifiers. (See section 6.1 “Function Definitions” for more detail on function calling.) It is legal to have any additional memory qualifiers on a formal parameter, but only restrict can be taken away from a calling argument, by a formal parameter that lacks the restrict qualifier.

To make this shader valid change the function parameters to:

```
float myFunction(readonly float[10] buff) {
	...
```

**Comment by johnkslang** [comment]
Glslang catches this if `readonly` is on the member.

The code is not taking into account the inheritance of `readonly` from the block to the members.

**Comment by jeffbolznv** [comment]
This change caused glslang to fail to compile a bunch of shaders in Vulkan CTS, and this issue seems like it could affect existing shaders in other apps. An example of what fails:

```
layout(set = 0, binding = 0, std430) readonly restrict buffer A {
    float b;
} a;

void main()
{
   round(a.b);
}
```

That is, you can no longer pass a value from a readonly buffer to a function as an *in* parameter. This seems surprising and unintentional, IMO, and makes readonly buffers much less usable. Since *in* parameters are only copied to the formal parameter and not from it, dropping readonly there seems like a reasonable thing to do.

@johnkslang any thoughts?

**Comment by ChrisGautier** [comment]
The specs also say:

> It is an error to pass an image variable qualified with readonly to imageStore() or other built-in functions that *modify image memory*

`round` does not modify image memory.

**Comment by jeffbolznv** [comment]
Yeah, this qualifier was originally only for images, and then SSBOs came later and some of the language may not be quite what we intended for SSBOs.

**Comment by jeffbolznv** [comment]
I'll file a GLSL bug about this, but we should consider reverting the behavior change in the meantime.

**Comment by jeffbolznv** [comment]
I filed https://github.com/KhronosGroup/GLSL/issues/83 for this
