### ISSUE TITLE
Out of bounds read (near but not NULL) when gl_PerFragment symbol is inside a function block.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#1879]
Here's a minimal test case.

```GLSL
#version 4
void d() {
  gl_PerFragment
```
which causes a segmentation fault, when validated in the fragment stage. The same applies to gl_PerVertex in the vertex stage, and possibly other interface block names, though I'm not sure about that.

**Comment by johnkslang** [comment]
This was caused by the order of error checking not quite being correct (maybe there is no correct ordering, when many checks must be done and they affect each other).  So, will check for block-name reuse twice.
