### ISSUE TITLE
texelFetch + uimage2D

### ISSUE THREAD

**Issue by HerveRV** [KhronosGroup/glslang#1886]
GLSL 4.6 core SDK 1.1.114 win10, last versions software of everything
compute shader code
layout(binding=0, r32ui) uniform readonly uimage2D TEXX;

problem case 1 :

uint AAA = texelFetch(TEXX, ivec2(gl_GlobalInvocationID.xy), 0).x;
 -> 'texelFetch' : no matching overloaded function found '=' : cannot convert from ' const float' to ' temp highp uint'

problem case 2  :

uvec4 BBB = texelFetch(TEXX, ivec2(gl_GlobalInvocationID.xy), 0);
 -> 'texelFetch' : no matching overloaded function found '=' : cannot convert from ' const float' to ' temp highp 4-component vector of uint'

I think it's a bug

**Comment by johnkslang** [comment]
`texelFetch()` works on textures, not images. 

`imageLoad()` works on images.

**Comment by HerveRV** [comment]
So, it's not a bug, thank you !
