### ISSUE TITLE
Use Google Test as the testing framework

### ISSUE THREAD

**Issue by antiagainst** [KhronosGroup/glslang#189]
The existing test harness is a home-made shell script. All the tests and the expected results are written as plain text files in an integrated test style. This is not quite easy to maintain and slow to run.

**Comment by antiagainst** [comment]
Add I'll take on this.

**Comment by yavn** [comment]
I agree things could be improved. At the moment it's quite cumbersome to fix the failing tests after a code change. There's no easy way to find which test failed first, no way to re-run it. I usually use some ad-hoc shell script to do just this.

Are you proposing to replace diff tests with some new C++ unit tests, or just use Google Test as a test runner?

**Comment by antiagainst** [comment]
@yavn: No, not only as a "test runner". The ideal outcome would be to rewrite all existing tests using the gtest framework, and I'll work towards that.

On the other side, introducing gtest will make sure all future tests are written in a much clearer way.

**Comment by antiagainst** [comment]
Done via #190.
