### ISSUE TITLE
glslang rejects seemingly valid ESSL shader due to image format mismatch

### ISSUE THREAD

**Issue by Max-Andersson** [KhronosGroup/glslang#1891]
After https://github.com/KhronosGroup/glslang/issues/1720, I'm now getting this failure _ERROR: 'format' : image formats must match_ when attempting to generate Vulkan SPIR-V for this ESSL shader.

```
#version 320 es

precision highp float;
precision highp int;

layout(location = 0) out vec4 color;

layout(rgba32f, set =0, binding = 0) uniform highp readonly image2D bound_image;

vec4 func(highp readonly image2D img, ivec2 coords) {
  return imageLoad(img, coords);
}

void main() {
  color = func(bound_image, ivec2(gl_FragCoord.xy));
}
```

Is this really correct? The OpenGL ES spec. states the following:

> Accesses to textures bound to image units do format conversions based on the format argument specified when the image is bound.

I understand from the implementation that Khronos wishes to make it legal to provide a format qualifier for function parameters, but since (at least in OpenGL ES) the access is dependent of the bound image and not the layout qualifier, I don't quite see why this needs to be a rule? Especially when taking the very strong language from the ESSL spec.:

> Layout qualifiers cannot be used on formal function parameters, and layout qualification is not included in parameter matching

Are all shaders on this form (passing an image as a function parameter) now considered invalid?

**Comment by johnkslang** [comment]
The `rgba32f` was dropped when calling the function.  I agree it's the already document hole in GLSL that should be filled.

Maybe another thing to do is allow it for Vulkan, if we knew all the front-ends.  For OpenGL, without SPIR-V, this (in)ability might be baked into shipped drivers, making it more difficult to fill the hole without an extension.

Isn't this all spec issues though?  Glslang is correctly implementing the specifications, yes?

**Comment by Max-Andersson** [comment]
> Glslang is correctly implementing the specifications, yes?

I'm not sure -I can't find any language in the ESSL spec. that explicitly disallows it (I find it illogical to mention that e.g. format qualifiers aren't part of parameter matching if you are not allowed to have it as a function parameter). If that is just a hole in the GLSL specs. that Khronos will update to explicitly disallow, then that's fine.

**Comment by johnkslang** [comment]
The ESSL 3.2 spec says, in 6.1 "Function Definitions":

> Formal parameters can have parameter, precision, and memory qualifiers, but no other qualifiers.

**Comment by Max-Andersson** [comment]
I think we're saying different things. I agree that you can not legally provide a image format qualifier on a function parameter and thus the format qualifier will always be dropped from a function parameter (this should be fixed by adding that in the GLSL spec., which is the plan). It is however unclear to me that this currently makes the function definition invalid. As I understand it, this is still legal since the parameters still match, due to the quote in the original post. It is fine to have this be illegal (since it is not clear to me from the currently existing specs. that this is illegal), I just to clarify what the expected behavior is.

On the topic of the Vulkan environment, Vulkan SPIR-V does have the Unknown image format available, which we could use for this.

**Comment by johnkslang** [comment]
>... It is however unclear to me that this currently makes the function definition invalid. As I understand it, this is still legal ...

I agree what you are saying is logical, but I think the problem is the function will generate incorrect code from not knowing the format, because it needs to know the format.

That is, the function (at least in some circumstances) needs to know, but does not know, and we don't allow the syntax to let it know.

**Comment by johnkslang** [comment]
See the specification issue discussion at https://github.com/KhronosGroup/GLSL/issues/57.

Changes here need to be driven from an extension or agreement to change the language definition.

**Comment by johnkslang** [comment]
Follow up to https://github.com/KhronosGroup/GLSL/issues/57.
