### ISSUE TITLE
Glslang is not really a "sample SPIR-V generator".

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/glslang#1893]
The description for the GitHub project says:

> Khronos reference front-end for GLSL and ESSL, and sample SPIR-V generator 

That last part isn't really accurate at this point. Many people seem to be using Glslang as the principle compiler for GLSL/HLSL/ESSL to SPIR-V conversions. The project has evolved beyond being a mere "sample" or demonstration of how to do it. So the description should probably be updated to reflect the capabilities of the tool.

**Comment by johnkslang** [comment]
What language do you propose?

Note there are other front ends generating SPIR-V, so it's not "the generator", but one of many.

**Comment by NicolBolas** [comment]
I think "a SPIR-V generator" would suffice. The point is to leave out the connotation that glslang's SPIR-V generation capabilities are experimental or otherwise just for show.

Also, considering that HLSL is supported, you might want to mention that too.

**Comment by johnkslang** [comment]
Well, in context that implies it might be a reference generator, which isn't true.  I changed it to the following:

> Khronos-reference front end for GLSL/ESSL, partial front end for HLSL, and a SPIR-V generator.
