### ISSUE TITLE
Difference between C++ API and CMD line Tools

### ISSUE THREAD

**Issue by 13431904801** [KhronosGroup/glslang#1896]
When I try to complie a hlsl demo shader file to spv format, I tried two ways: 
1. to use C++ API like this:
shader.setEnvInput(glslang::EShSourceHlsl, stage, glslang::EShClientVulkan, 100);
shader.setEnvClient(glslang::EShClientVulkan, glslang::EShTargetVulkan_1_0);
shader.setEnvTarget(glslang::EShTargetSpv, glslang::EShTargetSpv_1_0);
shader.setHlslIoMapping(true);
shader.setAutoMapBindings(true);
shader.setEntryPoint(shaderEntryPoint); // must set entry point  TODO!!
shader.setEnvTargetHlslFunctionality1();

Works well!

2. to use glslangvalidator like this:
glslangvalidator -V -D hlsl.gather.offset.dx10.frag -e main -q -o hlsl.gather.offset.dx10.frag.spv

No reflect variables found when I use spriv-cross tool to parse this spv file.

So if there is any options I miss when I use glslangvalidator? Why I get different result?

**Comment by 13431904801** [comment]
Two ways also generate two spv file with different size. glslangvalidator give a smaller one.

**Comment by johnkslang** [comment]
In one case, you use HLSL I/O mapping (selecting the `TDefaultHlslIoResolver`), and in the other case you did not.  On the command line it is `--hlsl-iomap`.  Maybe you don't need it, but to compare you should set both the same way.
