### ISSUE TITLE
Pipe IO variables are treated global

### ISSUE THREAD

**Issue by ShchchowAMD** [KhronosGroup/glslang#1898]
Should we treat pipe I/O variables ( input in first stage and output in last stage ) as global values during program linking (same scope with Uniform symbols) ?

Like, 

######### VS ############
layout(location = 0) in vec4 g_position;
layout(location = 1) in vec4 g_color;
out StageData {
  vec4 color;
} g_vs_out;
void main() {
  gl_Position = g_position;
  g_vs_out.color = g_color;
}
 
########### FS #############
in StageData {
  vec4 color;
} g_fs_in;
layout(location = 0) out vec4 g_color;
void main() {
  g_color = g_fs_in.color;
}

====================
Would this be legal or should we return an error caused by 'g_color' ?

**Comment by arcady-lunarg** [comment]
This feels like more of a spec question, but as far as my reading of the spec goes, "in" and "out" variables are not global per se, but rather "global" between the shader stage and whatever comes before or after it respectively. So in this case, there is no conflict between the two usages of g_color.

**Comment by arcady-lunarg** [comment]
Closing since this question got an answer and there was no further follow-up.
