### ISSUE TITLE
HLSL constructors cause segfault

### ISSUE THREAD

**Issue by dfranx** [KhronosGroup/glslang#1903]
Calling `float3()`, `float4()`, etc... cause segfault on this line:
https://github.com/KhronosGroup/glslang/blob/master/hlsl/hlslGrammar.cpp#L3225

arguments->getLoc() is called but arguments is equal to null.

Minimal example that crashes:
```
float4 main() : SV_TARGET
{
	return float4();
}
```

**Comment by johnkslang** [comment]
FXC says

> incorrect number of arguments to numeric-type constructor

And, while glslang is not trying to be an HLSL validator, it should catch things that lead to such failures.  It will now return

> ERROR: ...: 'one or more arguments' : Expected
