### ISSUE TITLE
Do we fully implement extension 'ARB_gpu_shader5'

### ISSUE THREAD

**Issue by ShchchowAMD** [KhronosGroup/glslang#1909]
Hi, @johnkslang , 

Have we fully implemented extension called 'ARB_gpu_shader5' in Glslang?

I found that the default extensionBehavior of this extension is EBhDisablePartial and sometimes may lead to a compile error when doing type convertion.

Best Regards,
Shaochi.

**Comment by johnkslang** [comment]
I believe it is partially, yes.  Much of it aligned with #version 400.  I don't know immediately what features are missing.  Might be interesting to see what is failing for you.
