### ISSUE TITLE
HLSL: no way to generate RWTexture2D with format rgba8?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#1912]
In Dota 2 with one of our compute shaders we are getting corruption on Intel GPUs, see https://github.com/ValveSoftware/Dota-2-Vulkan/issues/314

The problem is that the compute shader is using a RWTexture2D<float4> to output to a VK_FORMAT_R8G8B8A8_UNORM image and the ImageFormat in the OpTypeImage is rgba32f.  Oddly, validation does not complain about this issue and it has worked on other GPUs, but it is not correct.  The ImageFormat should be rgba8.

I can't seem to find any syntax for RWTexture2D<> that would yield an ImageFormat of rgba8.  I believe this is because there is not a scalar type in HLSL that would actually allow such a declaration, but perhaps we need to create one?

This appears similar to issue #895.  

CC @werman @jekstrand

**Comment by danginsburg** [comment]
It has been pointed out to me that I can use EOptionNoStorageFormat to generate OpTypeImage with Unknown format, which I think fixes the issue for this one shader because it only does shader storage writes.  However, in general this is problematic to set for all shaders because while shaderStorageImageWriteWithoutFormat may be widely supported shaderStorageImageReadWithoutFormat is not, so it might cause reads from storage images not to work if I set it globally.

Ideally this could be set with HLSL syntax on the individual declarations rather than a global option.  That, and/or having the full set of image types available via additional syntax.

**Comment by johnkslang** [comment]
Is it sufficient to have attribute syntax, reusing the GLSL strings for these?  Something like 

```
[[format::rgba8]]
```

I know some other possibilities were discussed.  Any best recommendations?

**Comment by danginsburg** [comment]
That would work for me.  It would also be useful to be able to tag it as writeonly or readonly via a similar syntax.

**Comment by johnkslang** [comment]
I'm thinking now it is better to use an `spv` name space for these things.  Maybe some were Vulkan-specific and so `vk` was deserved,  but we are trying to make SPIR-V annotations that nominally have meaning to many APIs.

So, I'm proposing we go with these:
```
[[spv::format_rgba8]]  // similarly for all ~39 formats; overrides the glslang deduction
[[spv::read_only]]
[[spv::write_only]]
```
I don't want to delay implementation for a naming discussion, but, if a different consensus is reached soon, it will be easy to switch the implementation over.

**Comment by danginsburg** [comment]
I've integrated PR #1918 here and confirmed I am able to fix my bug with it.  Syntax looks good to me, thanks for the quick turnaround!
