### ISSUE TITLE
Possibly inconsistent NaN handling with '!=' and '=='

### ISSUE THREAD

**Issue by doitsujin** [KhronosGroup/glslang#1917]
Hello,

suppose we have the following shader:
```glsl
#version 450

uniform u_data_t {
    float x, y;
};

void main() {
    bool a = x == y;
    bool b = x != y;
    ...
```
Under Vulkan semantics, the two equality checks get compiled to `OpFOrdEqual` and `OpFOrdNotEqual`, respectively. However, if I understand the definition of the two SPIR-V instructions correctly, `OpFOrdNotEqual` returns `false` if the two operands are unordered, which has the following implications:
- If at least one of `x` or `y` is NaN, `a == b == false`. This is counter-intuitive, and in case of HLSL, differs from FXC's behaviour.
- Drivers may have to insert extra instructions for `OpFOrdNotEqual` to check whether the operands are ordered, which may make computing the expressions `a != b` slower than computing `!(a == b)` in situations where NaN handling is not required.

I wasn't able to find any information on how these comparison operators are supposed to handle NaN in the GLSL spec, so my question is: Is this intended, or should `!=` be changed to emit `OpFUnordNotEqual` in this case, or am I misunderstanding the SPIR-V specification?

**Comment by johnkslang** [comment]
Right, any comparison with a NaN returns false.  I don't know about being counter-intuitive, as that's what one might expect after becoming familiar with NaNs.  Before having `isNaN()`, it was sometimes suggested to test if `a == a` returned false as a substitute.

GLSL was flexible in whether NaNs were generated and how they were operated on.

SPIR-V leaves it to the execution environment (E.g., Vulkan).  I believe this is still an open issue in Vulkan.
