### ISSUE TITLE
Memory issue.

### ISSUE THREAD

**Issue by Roy-AMD** [KhronosGroup/glslang#1920]
I try to use a multiple shader program, when delete TShader, some string member in TProgram will be delete too. and when delete TProgram, will cause crash. The string is in callGraph and ioAccessed, The string was incorrectly released when the pool(TPoolAllocator* pool) been deleted,

I noted, every TShader and TProgram use a TPoolAllocator, and should use NewPoolTString and NewPoolObject to create string and object, but when TString assign to a TString, seem will move it's allocator, I'm not very sure, but the string memory manager has some problem.

Has anyone encountered the same problem?

**Comment by johnkslang** [comment]
Can you try deleting the program first?  This could certainly use some improvement, but currently program must go before shaders.

There are a couple comments about this, but better it is more automatic.

From `ShaderLang.h`:

```
//
// N.B.: Destruct a linked program *before* destructing the shaders linked into it.
//
```

And from `Standalone.cpp`:

```
    // Free everything up, program has to go before the shaders
    // because it might have merged stuff from the shaders, and
    // the stuff from the shaders has to have its destructors called
    // before the pools holding the memory in the shaders is freed.
```

**Comment by Roy-AMD** [comment]
Thank you @johnkslang , I should read more comment, it's worked for me, but it weird. do you have any plan refine this code?
