### ISSUE TITLE
SPIR-V Mapping of memoryBarrier and groupMemoryBarrier

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/glslang#1922]
According to `12.2.11 Mapping of barriers` in GLSL 4.60

```
memoryBarrier() -> OpMemoryBarrier(/*Memory*/Device,
                           /*Semantics*/AcquireRelease |
                           UniformMemory |
                           WorkgroupMemory |
                           ImageMemory)
```

But in [GlslangToSpv](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp#L7503) we have
```
case glslang::EOpMemoryBarrier:
        builder.createMemoryBarrier(memoryBarrierScope, spv::MemorySemanticsAllMemory |
                                                        spv::MemorySemanticsAcquireReleaseMask);
```

Where `MemorySemanticsAllMemory` include `MemorySemanticsAtomicCounterMemoryMask`

I guess not sure why there is a slight disconnect between the SPIR-V mapping section and glslang

Note: this is the same thing for `groupMemoryBarrier` as well and I realize `memoryBarrierAtomicCounter` is not in the GLSL spec under the mapping section.

**Comment by johnkslang** [comment]
I believe OpenGL needs the extra bit set, while Vulkan can ignore it, and the (non-normative) mapping language was originally for Vulkan.  Perhaps this should be a specification update.
