### ISSUE TITLE
Python 3 is required even without using SPIRV-Tools

### ISSUE THREAD

**Issue by UX3D-wahlster** [KhronosGroup/glslang#1929]
[External ](https://github.com/KhronosGroup/glslang/tree/master/External) folder is not empty by default, therefore the following is always true:

```
if(IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/External)
    find_package(PythonInterp 3 REQUIRED)
endif()
```
CMake build requires PythonInterp 3 when a clean checkout of this repo is performed. But Python 3 is not actually required for building as far as i can tell.

Maybe another CMake option (like `BUILD_EXTERNAL `) is required:

```
if(BUILD_EXTERNAL AND IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/External)
    find_package(PythonInterp 3 REQUIRED)
endif()
```

Im not sure if I understood the build instructions correclty, but for me it sounded like Python is not required to build plain glslang.

Thanks for your help :)

**Comment by johnkslang** [comment]
Sounds accurate to me.

**Comment by UX3D-wahlster** [comment]
fixed with https://github.com/KhronosGroup/glslang/commit/8ba49b862cfb3449ffdfecd2e6d9c2fd5e855f1e

**Comment by akin666** [comment]
It seems this issue has re-emerged. 
commit fbe9a23baf2cb020fe3f80d68d972e2a97d9b954 moved the logic block of ```add_subdirectory(External)``` further down in the cmake file, but also refactored the code that ```find_package(PythonInterp 3 REQUIRED)``` is now always required now.

**Comment by greg-lunarg** [comment]
@akin666 I have opened a new issue for this. Do you want to submit a fix for this?

**Comment by greg-lunarg** [comment]
@akin666 Actually, I will first ask @ben-clayton to consider this since it was his change that caused the regression.
