### ISSUE TITLE
Volatile atomics always add VulkanMemoryModel

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#1936]
```
#version 450 core

layout(set=0, binding=3) volatile buffer D { uint d[]; } d;

void main()
{
    atomicExchange(d.d[0], 0);
}
```

Compiling with:
```
glslangValidator --target-env vulkan1.0 test.comp -o test.spv
```
Generates SPIR-V that includes the VulkanMemoryModel capability and Volatile memory semantics on the OpAtomicExchange instruction, but does not add the SPV_KHR_vulkan_memory_model extension. This is invalid (--target-env vulkan1.1 also has this issue).

Since the code does not enable the memory model in the GLSL, I expected a volatile decoration on the `d` variable instead.

**Comment by alan-baker** [comment]
@jeffbolznv any insights here?

**Comment by jeffbolznv** [comment]
Thanks Alan, I created PR #1937 for this.
