### ISSUE TITLE
Werror=deprecated-copy compilation issues with GCC 9.2.1

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/glslang#1939]
Including `intermediate.h` from glslang with GCC 9.2.1 (Ubuntu 19.10 comes with it) with `Werror=deprecated-copy` compilation option active results compilation errors. My understanding is that compiler now enforces (at least to some extent) rule of three.

Fix proposal in #1940

**Comment by JohannesKauffmann** [comment]
It seems that this issue can be closed, as #1940 is merged.
