### ISSUE TITLE
How to use glslang with C compiler?

### ISSUE THREAD

**Issue by sasmaster** [KhronosGroup/glslang#1951]
I read in the documentation that ShaderLang.h contains both C and C++ APIs. But I also see that C++ part of the header is not guarded against C compiler. So my C program spits tons of errors for all the .cpp API related syntax. Does it mean one can't use glslang with pure C compiler? Otherwise what do you suggest to do? Delete the CPP part from the header? 

Thanks.

**Comment by johnkslang** [comment]
The "Sh" stuff was intended to be a C interface.  Is it okay to still use a C++ compiler to create the libraries?  If so, we should be able to expose just the C interface to the that library, maybe by changing the public header to exclude the C++ interface.

**Comment by sasmaster** [comment]
Guys, IMHO it's totally unacceptable such a low level API doesn't provide clean C interface. There are companies out there which still write graphics software in C  ;)

**Comment by johnkslang** [comment]
I'm happy to work with someone to re-establish a C interface.

STL has a data() method that should be useful for wrapping functions like `GlslangToSpv()`.

**Comment by sasmaster** [comment]
> I'm happy to work with someone to re-establish a C interface.
> 
> STL has a data() method that should be useful for wrapping functions like `GlslangToSpv()`.

Then there should be another method that gives user the expected size of the buffer.  I am going to integrate glslang into commercial project so maybe I can help. C interface is of significant importance for me as I tend to use STL as seldom as possible.

**Comment by johnkslang** [comment]
Given that size is not known until after the work is done, it seems the current method could be wrapped with the C interface (intentionally avoiding what might be the correct names for the moment):

`getSizeAndHandle()`:  get the size of the return and a handle to it if necessary.  Calls `GlslangToSpv()` to compile, get a handle to the result and the size, caching the result somewhere.

`getResult()`: copy out the result into user-provided memory

Maybe that results in new methods too, but I think it's fine to compute the result at the time of the first call, rather than trying to estimate size.

**Comment by corporateshark** [comment]
@johnkslang 

We have bumped into the same problem - absence of any up-to-date C interface to `glslang` and `SPIRV`. Our use case is somewhat limited, we use these two to libraries at run time to convert GLSL shaders to SPIRV. Would there be any interest, if we publish our solution as a pull request here?

However, the only subset of features we use is the `TShader` interface and `glslang::GlslangToSpv()`.

**Comment by sasmaster** [comment]
> @johnkslang
> 
> We have bumped into the same problem - absence of any up-to-date C interface to `glslang` and `SPIRV`. Our use case is somewhat limited, we use these two libraries at run time to convert GLSL shaders to SPIRV. Would there be any interest, if we publish our solution as a pull request here?
> 
> However, the only subset of features we use is the `TShader` interface and `glslang::GlslangToSpv()`.

@corporateshark  would love to check it out.

**Comment by corporateshark** [comment]
@sasmaster That's what we have so far https://gist.github.com/corporateshark/f77e134376f89af0f586954fdccb234f

If it looks like what community requires, I will do further work to make it reusable.

There is still one issues with the `glslang` source code: some enums are declared within namespaces. This is not a problem for anyone who wants to just use this interface for DLL exports etc. However, it is not compatible with pure C.

**Comment by johnkslang** [comment]
Can they be left in the namespace, but have a switch turn the namespace on or off?  It would be better to not move a bunch of names into the global namespace.

**Comment by corporateshark** [comment]
@johnkslang There is already some level inconsistency with those names. For example, `EShLanguage` and `EShLanguageMask` are declared in the global namespace; and `EShSource`, `EShClient`, and many others are in the `glslang` namespace. If we are talking about touching these parts anyway, would not it be more consistent to pick one way or another and stick to it?

**Comment by johnkslang** [comment]
The way to be consistent with is to put them in the namespace.

There are some old ones outside the namespace due to history, and I think one that had to be, but ongoing, everything new goes in the namespace (this is been true for many years now).

I don't think there is a need to break all the current consumers here.  Maybe keep the file structure as it already is, but use a switch in the header based on C vs. C++.

**Comment by corporateshark** [comment]
@johnkslang A completely separate set of enums was created to make sure this new C-interface can be easily maintained on a long term basis as a self-contained entity.

Usage example (Vulkan 1.1):
```C++
	const char* shaderCodeVertex = ...;

	const glslang_input_t input =
	{
		.language = SH_SOURCE_GLSL,
		.stage = SH_STAGE_VERTEX,
		.client = SH_CLIENT_VULKAN,
		.client_version = SH_TARGET_VULKAN_1_1,
		.target_language = SH_TARGET_SPV,
		.target_language_version = SH_TARGET_SPV_1_3,
		.code = shaderCodeVertex,
		.default_version = 100,
		.default_profile = SH_NO_PROFILE,
		.force_default_version_and_profile = false,
		.forward_compatible = false,
		.messages = SH_MSG_DEFAULT_BIT,
	};

	glslang_initialize_process();

	glslang_shader_t* shader = glslang_shader_create( &input );

	if ( !glslang_shader_preprocess(shader, &input) )
	{
		// use glslang_shader_get_info_log() and glslang_shader_get_info_debug_log()
	}

	if ( !glslang_shader_parse(shader, &input) )
	{
		// use glslang_shader_get_info_log() and glslang_shader_get_info_debug_log()
	}

	glslang_program_t* program = glslang_program_create();
	glslang_program_add_shader( program, shader );

	if (!glslang_program_link(program, SH_MSG_SPV_RULES_BIT | SH_MSG_VULKAN_RULES_BIT))
	{
		// use glslang_program_get_info_log() and glslang_program_get_info_debug_log();
	}

	glslang_program_SPIRV_generate( program, input.stage );
	Shader->SpirV.resize( glslang_program_SPIRV_get_size( program ) );
	glslang_program_SPIRV_get( program, Shader->SpirV.data() );

	if ( glslang_program_SPIRV_get_messages(program) )
	{
		printf("%s", glslang_program_SPIRV_get_messages(program));
	}

	glslang_program_delete( program );
	glslang_shader_delete( shader );

	const VkShaderModuleCreateInfo ci =
	{
		.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
		.codeSize = Shader->SpirV.size() * sizeof(unsigned int),
		.pCode    = Shader->SpirV.data(),
	};

	VkResult result = vkCreateShaderModule(device, &ci, nullptr, ...);
```

**Comment by sasmaster** [comment]
Looks neat. Do GLSLang maintainers plan to merge this code into main repo?

**Comment by corporateshark** [comment]
@sasmaster The guts of glslang are written in C++, so it is just a wrapper, yes. `glslang_c_interface.h` is supposed to work with a C compiler.

**Comment by arcady-lunarg** [comment]
The answer to this is use glslang_c_interface.h, which you can use from a pure C program. You still need to build glslang itself with a C++ compiler, however.
