### ISSUE TITLE
[HLSL] Error during compiling arrays with constant values variables

### ISSUE THREAD

**Issue by QuantumDeveloper** [KhronosGroup/glslang#1956]
I have the following code
```
const static int permutationTableSize = 1024;
const static int gradientSetSize = 26;

cbuffer PerlinParams : register(b0)
{
	//pseudorandom hash modifiers
	int mX;
	int mY;
	int mZ;

	//permutation table
	int permutationTable[permutationTableSize];
	//gradients' set
	float3 gradientSet[gradientSetSize];
};
```
After compilation I receive the following error: ` array size must be a constant integer expression`
But this code was correctly working when I used D3DCompiler to compile it. 

Why glslang dont allow constant values to be used as array size for constant arrays?

**Comment by johnkslang** [comment]
We see `const` and `static` as contradictory qualifiers where only one is expected, that latter being non-const, and overriding the former's constness.  It should work if the `static` is removed.

**Comment by QuantumDeveloper** [comment]
@johnkslang  Yeah, you`re right. I removed static and it compiled correctly
