### ISSUE TITLE
GLSL : would defined be legally used following #if

### ISSUE THREAD

**Issue by ShchchowAMD** [KhronosGroup/glslang#1962]
Hi,

would this shader be legal or should return an error/warning :
(as whether #if !AAA here is legal? should we treat AAA here as 'defined' or character constants)

```
#version 330
precision mediump float;
in highp vec4 pos;
out float out0;

void main()
{
#define AAA defined(BBB)

#if !AAA
	out0 = 1.0;
#else
	out0 = 0.0;
#endif
	gl_Position = pos;

}

```

**Reference :**
OGLP 4.6 Core Specification 3.3 Preprocessor (P11):

> Expressions following #if and #elif are further restricted to expressions operating on literal integer constants, plus identifiers consumed by the defined operator.    Character constants are not supported.

**Comment by johnkslang** [comment]
The problem with the shader is that `defined` can't be used in an expanded macro.

**Comment by alegal-arm** [comment]
> The problem with the shader is that defined can't be used in an expanded macro.

I'm not sure I see anything in the spec that would support this statement.

**Comment by johnkslang** [comment]
It uses C++ as a normative reference for the preprocessor, which states, regarding macro expansion (replacement process):

> If the token `defined` is generated as a result of this replacement process ... the behavior is undefined.

Depending on whether relaxed errors are requested, glslang treats this as a warning or an error, as its goal is to validate that code is portable across implementations.
