### ISSUE TITLE
Remove deprecated install path for SPIRV/ folder

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/glslang#1964]
With #1963 we are installing the SPIRV/ folder into both `CMAKE_INSTALL_PREFIX/SPIRV` and `CMAKE_INSTALL_PREFIX/glslang/SPIRV`. This was to fix #1959  which broken when 7b0e236 was committed which moved the `SPIRV` folder into the `glslang` subfolder.

This is a tracking bug to remove the deprecated `CMAKE_INSTALL_PREFIX/SPIRV` installation. The plan of record is to land #1963, then update the `README.md` with a deprecation note and a 6 month lead time.  This bug will stay open during that time if folks have issues with the deprecation, please comment here. We will be installing to both `SPIRV` and `glslang/SPIRV` during the deprecation period to allow applications to migrate.

At that point, we will stop installing headers to the `CMAKE_INSTALL_PREFIX/SPIRV` folder.

**Comment by dj2** [comment]
One part we're going to have to work out is, the `SPIRV` folder exists at the top level of the glslang directory. So, currently things using CMake would do `SPIRV/GlslangToSpv.h` and it will work, that doesn't depend on the include directory.

But, if users expect to build with an installed GLSLang they will need to include `glslang/SPIRV/GlslangToSpv.h` which means your include path is different between cmake include and system include.

To fix we'd need to move the `SPIRV` folder under `glslang` in the repo, or do ... something? in cmake.

**Comment by dj2** [comment]
The deprecation date is set to: May 1, 2020

**Comment by johnkslang** [comment]
If the problem you're solving is the collision of SPIR-V headers proper (not glslang headers), and it's arguably better to use proper SPIR-V headers anyway, rather than glslang's snapshot, should we just be focusing on having glslang not overwrite those files, rather than on moving files unique to glslang?

**Comment by johnkslang** [comment]
@dj2 what's the latest best plan for this now?

It is okay to execute on it, if you'd like to submit a PR with the latest wisdom we have regarding this.

See #2216, thanks.
