### ISSUE TITLE
${CMAKE_INSTALL_LIBDIR} not respected for cmake files

### ISSUE THREAD

**Issue by Arfrever** [KhronosGroup/glslang#1965]
glslang installs cmake-generated files in hardcoded lib/cmake directory (usually /usr/lib/cmake) without respecting ${CMAKE_INSTALL_LIBDIR}.

Fix: [glslang.patch.txt](https://github.com/KhronosGroup/glslang/files/3812954/glslang.patch.txt)

**Comment by johnkslang** [comment]
Would you be willing to make a PR for users to review?

**Comment by Oxalin** [comment]
May I suggest to put the files in a single folder under "cmake"? Other lib and app seem to do so. Under Arch Linux, if I look under /usr/lib/cmake, every .cmake files is under its own app/library folder. Only glslang's files are polluting the cmake folder by dropping them all there.

Maybe ./cmake/glslang could be used?
