### ISSUE TITLE
Spurious "input primitive geometry redefinition" error in HLSL parser

### ISSUE THREAD

**Issue by Qartar** [KhronosGroup/glslang#1974]
We're seeing an issue where multiple geometry shader entrypoints in the same source file generate an error in glslangValidator when the input/output primitive type qualifiers do not match for each entrypoint. If the input and output primitive types are the same for all entrypoints then no error is generated. For example:

```
struct S {
    float clip0 : SV_Position;
    float clip0 : SV_ClipDistance0;
    float cull0 : SV_CullDistance0;
    uint vpai   : SV_ViewportArrayIndex;
    uint rtai   : SV_RenderTargetArrayIndex;
    int ii      : SV_InstanceID;
};

[maxvertexcount(4)]
void main(triangle in uint VertexID[3] : VertexID,
       inout LineStream<S> OutputStream)
{
    S s;
    OutputStream.Append(s);
}

[maxvertexcount(4)]
void notmain(line in uint VertexID[2] : VertexID,
       inout LineStream<S> OutputStream)
{
    S s;
    OutputStream.Append(s);
}
```

The shader above, which is the same as https://github.com/KhronosGroup/glslang/blob/master/Test/hlsl.semantic.geom except for the additional `notmain` shader definition, produces the following error:
```
ERROR: hlsl.semantic.geom:19: 'lines' : input primitive geometry redefinition
ERROR: hlsl.semantic.geom:19: ')' : Expected
ERROR: hlsl.semantic.geom:19: 'function parameter list' : Expected
hlsl.semantic.geom(19): error at column 17, HLSL parsing failed.
ERROR: 4 compilation errors.  No code generated.
```

I've reproduced the issue in the 1.1.97.0 SDK and on the latest revision here.

**Comment by johnkslang** [comment]
Yes, it's a bug, where seeing the keywords `triangle`, `line`, etc. triggered setting the shader's input, whether or not it was for the entry point.
