### ISSUE TITLE
CMake build options can change the binary layout of classes

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glslang#1976]
_This issue took a while to track down. I'm filing this for discussion and to confirm correct usage._

The binary layout of some of the classes (e.g. `TIntermSymbol`) in glslang can change based on the preprocessor defines (e.g. `ENABLE_HLSL`). The preprocessor defines of the consumer code must match the ones used when compiling glslang or the linker may end up choosing code that has the wrong binary layout causing all sorts of issues.

For example, the following code seems dangerous.
https://github.com/KhronosGroup/glslang/blob/9866ad9195cec8f266f16191fb4ec2ce4896e5c0/glslang/Include/intermediate.h#L1230-L1232

Depending on the CMake option ENABLE_HLSL, the binary layout of TIntermSymbol and all derived classes will change as ENABLE_HLSL adds a preprocessor define that adds a field to the class. [ENABLE_HLSL option](https://github.com/KhronosGroup/glslang/blob/9866ad9195cec8f266f16191fb4ec2ce4896e5c0/CMakeLists.txt#L31) is ON by default. Consumer code that includes `intermediate.h` will not have ENABLE_HLSL defined by default. This leads to bad behavior when statically linking as the same symbol will have two different code. Depending on which one the linker chooses, it may end up using the wrong layout.

For our usage, my fix is to disable a bunch of the options so that we don't have to add preprocessor defines to make the binary layout match the glslang build. See https://github.com/BabylonJS/BabylonNative/pull/99.

Does this sound right? Am I missing something or misusing the code in some way?

Thanks!

**Comment by johnkslang** [comment]
Your analysis is correct that compiling with different macro settings for different modes can change the layout of data.

> my fix is to disable a bunch of the options

Is your usage not HLSL?  If so, it does make sense to not turn it on when building glslang.

However, I see it is fragile to have `#ifdef` options inside struct/class.

What interfaces do you include? For HLSL, it seems there are only a few total that would need fixing.  For GLSLANG_WEB, it is off by default, and I think you'll want it off, so it won't cause a problem.

So, I think this is a total of just a few specifically for ENABLE_HLSL, and that seems fixable.

**Comment by johnkslang** [comment]
The other thing worth mentioning here is that in doing the GLSLANG_WEB work, I found not much practical benefit in small `#ifdef` in structs, just in consistency and helping to track down real code to `#ifdef`.

So, it is probably okay to remove the few that exist.

**Comment by bghgary** [comment]
> Is your usage not HLSL? If so, it does make sense to not turn it on when building glslang.

All the shaders are WebGL shaders, so they are all GLSL. HLSL is on by default and we started with the defaults. But yes, that option should be disabled for our usage.

> What interfaces do you include? 

We currently include `glslang/Public/ShaderLang.h`, `glslang/MachineIndependent/localintermediate.h` and traverse the AST to add a negative operator to dFdy when converting for D3D and Metal.

> For GLSLANG_WEB, it is off by default, and I think you'll want it off, so it won't cause a problem.

We are not on the latest yet, so we don't have the GLSLANG_WEB option. From a quick scan, it might be a beneficial option for our usage since the shader come from WebGL.

> I think this is a total of just a few specifically for ENABLE_HLSL, and that seems fixable.

I think it would be prudent to do a scan of the headers that are intended to be included by consuming code. For example, doing a quick scan of `intermediate.h`, the `AMD_EXTENSIONS` define can modify the layout of `TCrackedTextureOp`. Not sure if that causes any actual issues though.

**Comment by johnkslang** [comment]
The `AMD_EXTENSIONS` define is long gone, along with its other friends, in part due to this issue.

I've locally fixed your issue with ENABLE_HLSL, but it caused a bit of bloat I want to look at reducing first.

About `GLSLANG_WEB` you probably don't want to switch to it.  My point is that it being off by default avoids the issues your having, and we also need it to reduce bloat, so it will probably stay in place, even in structs, but without causing the problem you had.

**Comment by bghgary** [comment]
Ok, yeah, sorry, we are on an old version. We should update :-)

As for GLSLANG_WEB, the description says "Reduces glslang to minimum needed for web use". Does that mean it's intended for WASM? If so, then yeah, we probably won't use it.

**Comment by johnkslang** [comment]
> As for GLSLANG_WEB, the description says "Reduces glslang to minimum needed for web use". Does that mean it's intended for WASM? If so, then yeah, we probably won't use it.

Yes.
