### ISSUE TITLE
Compute shaders, "Contradictory local size" when merging shaders

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#1981]
Hey, I have two compute shaders, both with the same layout declared. One contains utility functions, the other is the main(). I add them both to the program. However it's failing to link with the error "Contradictory local size".
Looking at the source, this line looks suspect. 
https://github.com/KhronosGroup/glslang/blob/f4d4668529f1dad0e475295456b601353fe7cf33/glslang/MachineIndependent/linkValidate.cpp#L195

The 'empty' intermediate that is created that the other shaders are merged into is going to be defaulted to localSize = [1, 1, 1], so that line isn't ever going to evaluate to true. It'll always go into the error statement instead. Should it not instead be based on localSizeNotDefault?

Happy to create a pull request, just wanted to check my thinking. 
Thanks

**Comment by johnkslang** [comment]
The `localSizeNotDefault` was added recently, in 352e668a6.  Looking at how it behaved before that, and possibly hearing from @ShchchowAMD will probably help.

Yes, would be great to see a pull request.

**Comment by mbechard** [comment]
The other option would be to manually copy over the localSize when creating the empty intermediate. This is how the upper left origin flag is moved over.

**Comment by johnkslang** [comment]
Since we are tracking whether or not the user set this, it would be better to test for that, where you originally identified.

**Comment by ShchchowAMD** [comment]
Hi John and mbechard,

localSizeNotDefault is added for checking whether those three local sizes are default or already set by others.

If we are talking about merging shaders, this will base on both of them with an "OR" as:

After = src1 | src2.

If we already set local size to 1 explicitly, this flag will be set to true I think.

**Comment by ShchchowAMD** [comment]
Yes, you can check localSizeNotDefault if you want to know whether this local size has been manually set, even if in somewhere it is set to (1,1,1), we will still record this.

The reason is we should keep local size same.

**Comment by mbechard** [comment]
This pull also has what I think is a fix for the check just below as well, where localSizeSpecId[i] is getting overwritten if it's != TQualifier::layoutNotSet, which seems wrong. Shouldn't it only be getting overwritten if it's == TQualifier::layoutNotSet?
