### ISSUE TITLE
names containing consecutive underscores are reserved, and an error if version <= 300

### ISSUE THREAD

**Issue by ShchchowAMD** [KhronosGroup/glslang#1983]
Hi, after double checked glsl es spec 3.0,

I found in version 300 es, **consecutive underscores** within #define should be treated as **warning** instead of **error**, don't know whether what I found is right.

As the spec of v3.0 said:

> By convention, all macro names containing two consecutive underscores ( __ ) are reserved for use by underlying software layers.  Defining such a name in a shader does not itself result in an error, but may result in unintended behaviors that stem from having multiple definitions of the same name

I found this by test case as following:

> 
> #version 300 es
> precision mediump float;
> in highp vec4 dEQP_Position;
> out float v_out0;
> int out0;
> 
> #define __VALUE__	1
> 
> void main()
> {
> 	out0 = __VALUE__;
> 	gl_Position = dEQP_Position;
> v_out0 = float(out0);
> 
> }
> 
> 

Reference Version:

GLES Shading Language 3.00
Language Version: 3.00 
Document Revision: 6 29 January 2016

**Comment by johnkslang** [comment]
According to glslang:

> `//... ES 310 (and desktop) added the clarification ...`

But, right, the specifications now say that starting with 300.

**Comment by johnkslang** [comment]
This is the case for both preprocessor macro names and GLSL identifiers.

**Comment by ShchchowAMD** [comment]
Thanks for your reply.
I think now we can turn the version check to "<300" and based on whether relax errors right ?

**Comment by johnkslang** [comment]
I'm not clear what you are asking. Glslang now checks "< 300" instead of "<= 300". Are you wanting a change to glslang regarding relaxed errors?

**Comment by ShchchowAMD** [comment]
No worries, I think I find the commit from you, which has changed this part.
I got no questions for this, may thanks.
