### ISSUE TITLE
Clean cmake files installation by using a common folder

### ISSUE THREAD

**Issue by Oxalin** [KhronosGroup/glslang#1986]
Following issue 1965 and proposed pull request for commit bd69a4fb1206c3441ed56a9a058adfb6e46d55a6, the solution seems incomplete to mirror what is done with other libraries. Would it be possible to put all the .cmake files under a common folder (or under a few common folders) so it doesn't pollute ./cmake? It is done this way for other libraries (seen under Arch Linux).

We could have:
-${CMAKE_INSTALL_LIBDIR}/cmake/glslang

OR
-${CMAKE_INSTALL_LIBDIR}/cmake/hlsl

${CMAKE_INSTALL_LIBDIR}/cmake/glslang
${CMAKE_INSTALL_LIBDIR}/cmake/SPIRV
...

I can propose a patch provided that someone indicates me which solution should be implemented.

**Comment by arcady-lunarg** [comment]
This was fixed by #3027, all the glslang cmake files get installed in `${CMAKE_INSTALL_LIBDIR}/cmake/glslang/` (SPIRV-Tools creates its own subdirectories there and there are a few).
