### ISSUE TITLE
Extremely large builtins (e.g. work group size as maxint) can overflow during string construction

### ISSUE THREAD

**Issue by null77** [KhronosGroup/glslang#1987]
To reproduce, first set `TBuiltInResource.maxComputeWorkGroupCountX/Y/Z` or `TBuiltInResource.maxComputeWorkGroupSizeX/Y/Z` to max 64-bit int and then initialize as normal. The builtin string for `gl_MaxComputeWorkGroupCount` or `gl_MaxComputeWorkGroupSize` will overflow the 80 character hard limit in [Initialize.cpp](https://github.com/KhronosGroup/glslang/blob/master/glslang/MachineIndependent/Initialize.cpp#L6334) and further use will trigger internal errors.

We should probably bump up this limit so it isn't possible to overflow.

**Comment by sunsun02** [comment]
The problematic codes:

// compute
    if ((profile == EEsProfile && version >= 310) || (profile != EEsProfile && version >= 420)) {
        snprintf(builtInConstant, maxSize, "const ivec3 gl_MaxComputeWorkGroupCount = ivec3(%d,%d,%d);", resources.maxComputeWorkGroupCountX,                                                                                                  resources.maxComputeWorkGroupCountY,                                                                                                   resources.maxComputeWorkGroupCountZ);

If these values are 2147483647 (max integer), then the string is out of range

**Comment by null77** [comment]
Thanks for the fix!
