### ISSUE TITLE
Crash compiling legacy GL to SPIR-V

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#1993]
This is closely related to #124 - compiling such a shader crashes trying to look up a non-existant opcode:

```
#version 460 compatibility

void main() {
	gl_Position = ftransform(); 
}
```

I'm of course not expecting it to successfully compile, and the message about SPIR-V not supporting compatibility profile is fine, but for programs that compile user-provided GLSL to SPIR-V without knowing if the GLSL is valid it ideally shouldn't crash.

**Comment by johnkslang** [comment]
Yes it should not crash.  Incorrect semantics should result in error message, not a crash.  I'm looking into it.

**Comment by johnkslang** [comment]
`ftransform()` was still partially included in an inconsistent state for SPIR-V, rather than fully excluded.
