### ISSUE TITLE
Bug in EXT_buffer_reference2 array arithmetic and specialization constants

### ISSUE THREAD

**Issue by pixeljetstream** [KhronosGroup/glslang#2000]
```
layout(constant_id=77) const int c_size = 5;
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer TestRef {
  uint blah[c_size];
  uint blubb;
};

layout(push_constant) uniform push {
  TestRef        ref;
};

... = ref[index].blubb;  
```

generated spir-v uses a multipler that is constant 24 bytes, and not depending on the specialization constant that actually defines the size of the struct

**Comment by johnkslang** [comment]
If you are asking for blocks to have their layouts dynamically change based on specialization, that is not currently supported.

Maybe we need a way for the total size to vary if that's needed for platform-dependent variance is maximum size, but currently specializing an array embedded in a block is not a supported way of doing that.

Here is the spec language saying a bit more about it:

> Arrays inside a block may be sized with a specialization constant, but the block will have a static layout. Changing the specialized size will not re-layout the block. In the absence of explicit offsets, the layout will be based on the default size of the array.

**Comment by pixeljetstream** [comment]
Thanks, closing the issue as not a bug.
