### ISSUE TITLE
Can setInvertY work for spv backend? You know that we have so much old code written with opengl. 

### ISSUE THREAD

**Issue by snowfoxer** [KhronosGroup/glslang#2002]
Can glslang add setInvertY work for spv backend? I see the function can only support hlsl backend.
You know that we have so much old code written with OpenGL. 
And some of these code is not controlled by us.

**Comment by johnkslang** [comment]
Does this require `setInvertY`, which was added for DX incompatibility, or rather inverting the viewport, which is done in the API, not with a shader change?

**Comment by johnkslang** [comment]
Is the viewport a better solution, or do you still want to invert Y in a shader?

**Comment by snowfoxer** [comment]
OK, thanks for you advising. I will try both VK_KHR_maintenance1 and viewport invert.
