### ISSUE TITLE
Only one push_constant block is allowed per stage - identical push_constant block

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#2005]
Compiling for Vulkan.
I have a TProgram that is built up using multiple TShader objects for the same stage. Some contain utility functions, and one contains the main() for that stage. They all declare the same push_constant block. Each shader may use only a few variables of that block, but they all declare the exact same struct since a differing struct for the same stage would make no sense.
GLSLang fails with the error "Only one push_constant block is allowed per stage".
It would seem that GLSLang should compare the push_constant blocks and only error if any of the shaders have block that differs from another. Or, is there another way to share the block between the shaders that I'm missing?

Is this just a missing feature of GLSLang, or is what I'm doing somehow against a spec?
Thanks

**Comment by johnkslang** [comment]
I think your ideas of how it should work are correct.

The intersection of the two spaces of "multiple compilation units" and "new features added for Vulkan" are likely underspecified.

To follow through on the existing rules for sharing API objects between compilation units, we should allow the same declaration of push constant buffers in multiple compilation units to be a single object when linked together.

**Comment by johnkslang** [comment]
Well, push constants are just uniform blocks, and uniform blocks are just globals, and all globals share the same set of rules for linkage together between compilation units in the same stage.

So, there is likely no specification problem here.

**Comment by mbechard** [comment]
Ok, I'll look into adding support for this.

**Comment by mbechard** [comment]
Fix committed to my branch. I can't add unit tests yet though due to #2006 since any program will crash right now. I'll wait on a pull request for that.
Just starting to get familiar with this codebase so any feedback is appreciated.
