### ISSUE TITLE
Incorrect std140 offsets

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#201]
**Using glslang shipped with Vulkan SDK 1.0.3 and 1.0.5.**

The offsets from the reflection API for this block using std140 are incorrect:
```
layout(std140, binding = 1) uniform ciBlock1T {
	uniform float	uMinThresh;  // 0
	uniform float	uMaxThresh;  // 4
	uniform float	uMinSpeed;   // 8
	uniform float	uMaxSpeed;   // 12
	uniform vec3	uPredPos;    // 16
	uniform vec3	uCamPos;     // 32
	uniform float	uTimeDelta;  // 44 - should be 48
	uniform float	uTime;       // 48 - should be 52
	uniform float	uZoneRadius; // 52 - should be 56
} ciBlock1;
```

**Comment by DominikWitczakAMD** [comment]
Any update on this, please?

**Comment by johnkslang** [comment]
Is this really incorrect?  Applying the rules:

> 3. If the member is a three-component vector with components consuming N basic machine units, the base alignment is 4N.

So, the base alignment of uCamPos is 16.

>  The base offset ... is derived by taking the offset of the last basic machine unit consumed by the previous member and adding one.

So, the base offset of uTimeDelta is 32 + (12-1) + 1 = 44.

>  1. If the member is a scalar consuming N basic machine units, the base alignment is N.

So, the base alignment of uTimeDelta is 4.

> aligned offset is computed by rounding the base offset up to a multiple of the base alignment

44 rounded up to a multiple of 4 is still 44.

> Each structure member is stored in memory at its aligned offset.

Hence, uTimeDelta is stored at 44.  (This is not so different than uMaxSpeed, which was stored at 12, not 16; whichever way the machine can read uMaxSpeed, it would also read uTimeDelta.)

**Comment by Qining** [comment]
I think @johnkslang is right. The base alignment of `uTimeDelta` is 4 bytes (assume the basic unit is byte), and its base offset is 44 bytes. As 44 happens to be 11 times of 4, `uCamPos`'s alignment offset should be 44.

Rule 3 only means the base alignment of 3-element vectors are 4N, but such vectors still may occupies only 3N units. So the next element should do the round-up computation from the exactly next unit.

[Reference link](https://www.opengl.org/registry/specs/ARB/uniform_buffer_object.txt) for quick access
