### ISSUE TITLE
What is the correct intermediate SPIRV buffer size?

### ISSUE THREAD

**Issue by sasmaster** [KhronosGroup/glslang#2012]
Hi.
I have been wondering about this part of the API:

   ```
       spv::SpvBuildLogger logger;
	glslang::SpvOptions spvOptions;
	spvOptions.optimizeSize = true;
	spvOptions.validate = true;
	spvOptions.disableOptimizer = false;
	glslang::GlslangToSpv(*program.getIntermediate(shaderStage), SpirV, &logger, &spvOptions);

  ```

Then,I see different examples which are not consistent about the next part:
```
       VkShaderModuleCreateInfo createInfo = {};
	createInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
	createInfo.codeSize = SpirV.size() * sizeof(uint32_t);
	createInfo.pCode = SpirV.data();
```

Some people multiply vector of int(s) by the size of uint32_t. Why?Other people do nothing and just use the size of the vector. In other examples I have seen people copy this buffer into another one with the uint_8 type,or cast to uint8_t and divide by size of uint32_t... What is the correct .codeSize to pass into createInfo? 

Thanks in advance.

**Comment by johnkslang** [comment]
The Vulkan spec. says that `codeSize` is 

> the size, in bytes, of the code pointed to by `pCode`.

It's true that SPIR-V is a stream of 32-bit words, and most places count the words, but this place says it is bytes.
