### ISSUE TITLE
Wrong GLSL version required for int64 support

### ISSUE THREAD

**Issue by jeffbolznv** [KhronosGroup/glslang#2014]
I got an internal bug report that GL_ARB_gpu_shader_int64 didn't work in a shader using #version 430. I see this code in glslang:

```
    case INT64_T:
    case UINT64_T:
    case I64VEC2:
    case I64VEC3:
    case I64VEC4:
    case U64VEC2:
    case U64VEC3:
    case U64VEC4:
        afterType = true;
        if (parseContext.symbolTable.atBuiltInLevel() ||
            (!parseContext.isEsProfile() && parseContext.version >= 450 &&
             (parseContext.extensionTurnedOn(E_GL_ARB_gpu_shader_int64) ||
              parseContext.extensionTurnedOn(E_GL_EXT_shader_explicit_arithmetic_types) ||
              parseContext.extensionTurnedOn(E_GL_EXT_shader_explicit_arithmetic_types_int64))))
            return keyword;
        return identifierOrType();
```

I don't know where the "450" came from. https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gpu_shader_int64.txt says "OpenGL 4.0 and GLSL 4.00 are required." https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_explicit_arithmetic_types.txt says "This extension can be applied to OpenGL GLSL versions 1.40 (#version 140) and higher."

Either way, it seems like the types should require the extensions and the extensions should require a version, rather than the types directly requiring a version.

**Comment by johnkslang** [comment]
I agree it seems these tokens should not be "anding" a version check and an extension check.

**Comment by johnkslang** [comment]
A bunch of older version checks were for *less than* a version, to see if it wasn't in core if it was in an extension instead.  I believe that is the correct original design, it just wasn't always used that way.

Note though that generally we are missing a specific feature to test for an extension being used too early, but I'd like to decouple that.  Most extensions add built-ins and do the correct version check before adding them to the symbol table, so things get caught that way.
