### ISSUE TITLE
Bug introduced by PR #1977 causes error preprocessing glsl source

### ISSUE THREAD

**Issue by stuartcarnie** [KhronosGroup/glslang#2020]
PR #1977 introduced a bug which results in type comparisons to fail resulting in this error preprocessing glsl source such as the following on line 84 of a Compute shader:

```
in    highp uvec3 gl_NumWorkGroups;const highp uvec3 gl_WorkGroupSize = uvec3(1,1,1);in highp uvec3 gl_WorkGroupID;in highp uvec3 gl_LocalInvocationID;in highp uvec3 gl_GlobalInvocationID;in highp uint gl_LocalInvocationIndex;
```

more specifically 

```
const highp uvec3 gl_WorkGroupSize = uvec3(1,1,1)
```

with the following error

```
non-matching or non-convertible constant type for const initializer
```

## Root Cause

Note that PR #1977 resulted in the `structReturnIndex` field being a permanent fixture of the `TSampler` struct, but is never initialized, so must be assumed to have garbage:

https://github.com/KhronosGroup/glslang/blob/1afa2b8cc57b92c6b769eb44a6854510b6921a0b/glslang/Include/Types.h#L109

This value was always cleared when `ENABLE_HLSL` was on here:

https://github.com/KhronosGroup/glslang/blob/1afa2b8cc57b92c6b769eb44a6854510b6921a0b/glslang/Include/Types.h#L155-L159

As it is not cleared, the `operator==` function will failed randomly:

https://github.com/KhronosGroup/glslang/blob/1afa2b8cc57b92c6b769eb44a6854510b6921a0b/glslang/Include/Types.h#L230

**Comment by johnkslang** [comment]
Ah, good catch. Will fix very soon.

**Comment by stuartcarnie** [comment]
Great!

I identified the issue as I use glslang and the SPIRV-Cross projects in https://github.com/OpenEmu/OpenEmu-Shaders

**Comment by stuartcarnie** [comment]
Thanks @johnkslang – latest code works again 🎉
