### ISSUE TITLE
Assert error with gl_PointSize

### ISSUE THREAD

**Issue by dchristopherfennell** [KhronosGroup/glslang#2040]
When converting GLSL to SPIR-V, if I have more than one shader used in the vertex stage and gl_PointSize is set in a shader file that is not the main shader, I get an assert error.

**main.vert**
.....
void compute_point_size();
.....
void main()
{
    compute_point_size();
   gl_Position = .....
}

**utility.vert**
void compute_point_size()
{
    gl_PointSize = ..... // <-- assert error. remapper.size() == 0
}

**Comment by johnkslang** [comment]
I tried reproducing with a debug build and the following shaders, but it seems to work correctly.

It's possible a recent related fix fixed it.  Do you still have this problem?  If so, can you post shaders that reproduce it?

```
#version 460 
void compute_point_size();
void main()
{
  compute_point_size();
  gl_Position = vec4(1.0);
}
```
-------------------
```
#version 460 
void compute_point_size()
{
  gl_PointSize = 1.0;
}
```

**Comment by dchristopherfennell** [comment]
I agree. The latest pull does not reproduce this problem for me.

Thanks,
