### ISSUE TITLE
glslang generates duplicated MemoryBarrier instructions

### ISSUE THREAD

**Issue by weifengz** [KhronosGroup/glslang#205]
This example is for illustration purpose:
```
#version 310 es
layout(local_size_x = 8) in;
void main() {
  memoryBarrier();
  barrier();
}
```
The generated SPV:
```
         4(main):     2 Function None 3
               5:            Label
                              MemoryBarrier 7 8 
                              MemoryBarrier 7 8     <----- duplicated
                              ControlBarrier 7 7 9
                              Return
                              FunctionEnd
```

**Comment by johnkslang** [comment]
But, the source issued two barriers:

memoryBarrier -> MemoryBarrier
barrier -> MemoryBarrier + ControlBarrier

I think this is just a simple optimization that could be made, but not incorrect code.  Yes?

**Comment by Themaister** [comment]
barrier() does not imply a memory barrier, at least not in GLES 3.1.
https://www.khronos.org/registry/gles/specs/3.1/GLSL_ES_Specification_3.10.withchanges.pdf section 8.14. I couldn't find similar wording in GL 4.5 core though.

**Comment by weifengz** [comment]
Yes, I double checked ES 3.2 spec which specifically added a clarification:
_**1.1.3 Changes from GLSL ES 3.1 revision 3
• Clarified that barrier() does not order memory transactions**_

Similarly, in Chapter 4.3.8 "Shared Variables"
_In order to achieve ordering with respect to reads and writes to shared variables, a combination of control flow and memory barriers must be employed using the barrier() and memoryBarrier() functions (see section 8.15 “Shader Invocation Control Functions”)._

So, GLSLang translation of "barrier -> MemoryBarrier + ControlBarrier" seems inconsistent with ES 3.1/3.2 spec.

**Comment by weifengz** [comment]
Will this bug be fixed soon? Looks like a quick fix.

**Comment by johnkslang** [comment]
Both GLSL 4.5 and ESSL 3.2 say:

> Output variable assignments performed by any invocation executed prior to calling barrier() will be visible to any other invocation after the call to **barrier**() returns.

That does seem contradictory to what the changes made to the ESSL specification.

Best guess for now is ES intended the above quote to no longer apply, while desktop has not made this change.

So, I'm:

- changing glslang for ES but not for desktop
- raising this issue with Khronos for a resolution

**Comment by johnkslang** [comment]
Update: Khronos has decided that everything should converge towards control barriers in the tessellation control stage also synchronizing memory outputs.  SPIR-V 1.1 might revisit this, but for the current versions of ESSL, GLSL, and SPIR-V, an extra memory barrier is not needed, as it is built into the meaning of barrier().

**Comment by johnkslang** [comment]
This is fully resolved now, with spec. changes and the referring commits.
