### ISSUE TITLE
8.13.3559: test suite fails

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/glslang#2051]
Output is in attachment
[glslang_out.txt](https://github.com/KhronosGroup/glslang/files/4030308/glslang_out.txt)

**Comment by johnkslang** [comment]
> `./runtests: line 31: ../build/StandAlone/glslangValidator: No such file or directory`

This seems like an important clue.

**Comment by johnkslang** [comment]
Closing, as the attachment shows that glslang was not built, or not findable by the test suit.

**Comment by kloczek** [comment]
I see where te issue is.

In your scripts you are assuming that all binaries will be availaible in ../build base directory.

I'm building my glslang straight in source root direcory.

In other words it is kind of bug because you are forcing to use aexacly that build directory.
```
[tkloczko@barrel glslang-8.13.3743]$ ls -l StandAlone/glslangValidator
-rwxr-xr-x. 1 tkloczko tkloczko 38020232 Apr 27 09:35 StandAlone/glslangValidator
```

**Comment by johnkslang** [comment]
I think you can build where you want and point the `CMAKE_INSTALL_PREFIX` setting to a different location.  I set mine to my glslang/build/install directory (but with a full path).
