### ISSUE TITLE
Buffer references can generate invalid forward references

### ISSUE THREAD

**Issue by alan-baker** [KhronosGroup/glslang#2053]
The test spv_bufferhandle6_frag generates a forward reference to an array. This is now caught by the validator.

**Comment by johnkslang** [comment]
I only see forward references to pointer to structures, but they then get consumed by an array, which is required for a struct containing an array of pointers to its own type.

Either the spec needs to be relaxed to allow that, or that functionality needs to be disallowed, but I don't think it's right to have the GLSL support a struct with an array of pointers to the structs type (seems perfectly valid) and say the natural SPIR-V for that is illegal.

**Comment by johnkslang** [comment]
Going back to basics, what's the spec language preventing what glslang is producing?

**Comment by alan-baker** [comment]
The heart of it is that the arrays do not allow a forward reference to the element type. So when glslang uses the forward pointer in the array declaration, that is invalid as the spec stands.

**Comment by johnkslang** [comment]
Yes, I think the spec. meant to allow a struct pointing to itself and says so very directly. We should discuss within Khronos if it's meant to disallow a struct pointing to itself through an array (allowing a tree rather than just a linear list).

**Comment by johnkslang** [comment]
Khronos has agreed that other type declarations instructions can consume an OpTypeForwardPointer along the way toward its' OpTypePointer declaration. So, glslang is okay.  This will appear in the next revision of the SPIR-V specification.
