### ISSUE TITLE
https://github.com/Think-Silicon/GLOVE/issues/87

### ISSUE THREAD

**Issue by 82157402** [KhronosGroup/glslang#2060]
debug glove  , it will crash.
![image](https://user-images.githubusercontent.com/12945580/72967061-59267680-3dfb-11ea-8a79-8f17d8927901.png)

**Comment by johnkslang** [comment]
Is 3972 a line number?

Current glslang calls `.size()` from `structTypeCheck()` around line 4599.

Can we see the `struct` that triggers the problem?  The `.size()` should just be asking the number of members of the structure.
