### ISSUE TITLE
error: enumeration value 'EShTexSampTransCount' not handled in switch

### ISSUE THREAD

**Issue by timvpGoogle** [KhronosGroup/glslang#2062]
ANGLE is attempting to pick up the latest glslang, but is hitting the following error while building:

```
    FAILED: obj/third_party/glslang/src/glslang_sources/Intermediate.o
    ../../build/toolchain/clang_code_coverage_wrapper.py --target-os=chromeos --files-to-instrument=../....(too long)
    ../../third_party/glslang/src/glslang/MachineIndependent/Intermediate.cpp:2771:13: error: enumeration value 'EShTexSampTransCount' not handled in switch [-Werror,-Wswitch]
    switch (textureSamplerTransformMode) {
    ^
    1 error generated.
```

This is related to the following piece of code:

```
#ifndef GLSLANG_WEB
    // Propagate 'noContraction' label in backward from 'precise' variables.
    glslang::PropagateNoContraction(*this);

    switch (textureSamplerTransformMode) {
    case EShTexSampTransKeep:
        break;
    case EShTexSampTransUpgradeTextureRemoveSampler:
        performTextureUpgradeAndSamplerRemovalTransformation(root);
        break;
    }
#endif
```

If possible, we would also like the warning to be enabled in glslang's build to try and catch these a bit earlier.

**Comment by timvpGoogle** [comment]
This is being tracked within ANGLE with:
http://anglebug.com/4337

**Comment by null77** [comment]
If you don't want the warning on by default we could simply disable the warning in the BUILD.gn file.

**Comment by johnkslang** [comment]
Adding the C API included adding many `*Count` enums, triggering this.

Is this really the only such instance that caused a problem?  Nice if true, but I'd be a bit surprised.

We'd really like a way to statically assert two enums have the same entries without adding this count everywhere.

In this case, it seems easy enough to replace `EShTexSampTransKeep` with `default`.

**Comment by null77** [comment]
This was the only instance we saw as of right now.

**Comment by corporateshark** [comment]
@johnkslang If this is the only instance, can we just add `default: assert(0);` in there and call it a day?

**Comment by johnkslang** [comment]
Yes, will do.

**Comment by johnkslang** [comment]
Well, we now know of at least 3 instances of this.  Hoping that's the end, but wishing for the cleaner way of having the C interface mimic the C++ enums.

**Comment by johnkslang** [comment]
Known additional fixes are in 19ec0d2ff9059e8bc8ca0fc539597a771cefdc89.

**Comment by corporateshark** [comment]
@johnkslang It is possible to do it much cleaner with https://github.com/Neargye/magic_enum However, it is an additional dependency (header-only, though) and requires C++17.

**Comment by null77** [comment]
ANGLE can't use C++17 b/c we need to support Chrome.
