### ISSUE TITLE
OpImageTexelPointer: generated cube map array coordinate is not according to SPIR-V spec

### ISSUE THREAD

**Issue by mrzerg** [KhronosGroup/glslang#207]
Currently, for OpImageTexelPointer, glslangvalidator generates cube map array coordinate using GLSL style, which is a 3 component coordinate, and coord.z = layer \* 6 + face.

In SPIR-V spec, for OpImageTexelPointer, cube map array coordinate is required to be 4 component, which should be x, y, face, layer.

It seems that we need to change glslangvalidator behavior to match spec.
This means for each OpImageTexelPointer, we need to insert instructions to extract face and layer from the 3rd component of GLSL coordinate:
face = glslCoord.z % 6;
layer = glslCoord.z / 6;

**Comment by johnkslang** [comment]
I see SPIR-V saying the last component is the layer, but not specifically discussing face and layer as separate entities, so am not sure yet where this bug is (spec. or implementation).  Do you see discussion of 'face' in SPIR-V in this way, or is it possible this formula is expected.

The Vulkan API says

>... the number of cube maps in a cube map array view is layerCount / 6, and image array layer baseArrayLayer + i is face index i mod 6 of cube i / 6...

**Comment by mrzerg** [comment]
Yes you are right, I went through SPIR-V spec and Vulkan spec and didn't find anything requires 'face' to be a separate component of coordinates. I think 'face' is implicitly contained in layer as defined by the formula you quoted from Vulkan API.

So I guess we should fix SPIR-V spec, change OpImageTexelPointer to require cube map array coordinate be 3 components instead of 4.

**Comment by johnkslang** [comment]
The SPIR-V specification was fixed, to the 3-coordinate style for cube arrays:

> If Arrayed is 1:
>- 1D: 2 components
>- 2D: 3 components
>- Cube: 3 components; the face and layer combine into the 3rd component, layer_face, such that face is layer_face % 6 and layer is floor(layer_face / 6)
