### ISSUE TITLE
HLSL: log2(2) is miscompiled to 0.0

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#2070]
This shader code:

```
float main(): SV_Target0
{
	int x = 2;
	return log2(x);
}
```

When compiled with these options:

```
C:\VulkanSDK\1.1.130.0\Bin\glslangValidator.exe -H -Od -e main test.frag.hlsl
```

Produces the following (incorrect) SPIRV:

```
// Module Version 10000
// Generated by (magic number): 80008
// Id's are bound by 20

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 18
                              ExecutionMode 4 OriginUpperLeft
                              Source HLSL 500
                              Name 4  "main"
                              Name 8  "@main("
                              Name 12  "x"
                              Name 18  "@entryPointOutput"
                              Decorate 18(@entryPointOutput) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeFunction 6(float)
              10:             TypeInt 32 1
              11:             TypePointer Function 10(int)
              13:     10(int) Constant 2
              14:    6(float) Constant 0
              17:             TypePointer Output 6(float)
18(@entryPointOutput):     17(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
              19:    6(float) FunctionCall 8(@main()
                              Store 18(@entryPointOutput) 19
                              Return
                              FunctionEnd
       8(@main():    6(float) Function None 7
               9:             Label
           12(x):     11(ptr) Variable Function
                              Store 12(x) 13
                              ReturnValue 14
                              FunctionEnd
```

Instead of generating a call to log2 function, or emitting a constant, glslang just emits 0.0. Here's the SPIRV-Cross translation of this SPIRV:

```
#version 450

layout(location = 0) out float _entryPointOutput;

float _main()
{
    int x = 2;
    return 0.0;
}

void main()
{
    _entryPointOutput = _main();
}
```

**Comment by zeux** [comment]
This might be the same root cause as #1798?

**Comment by dneto0** [comment]
I reproduce this with 

     glslangValidator  -V -Od a.frag.hlsl -o a.spv -e main

**Comment by dneto0** [comment]
The problem already exists in the AST:
$ glslangValidator  -V -Od a.frag.hlsl -o a.spv -e main -i
a.frag.hlsl
Shader version: 500
gl_FragCoord origin is upper left
0:? Sequence
0:2  Function Definition: @main( ( temp float)
0:2    Function Parameters: 
0:?     Sequence
0:3      Sequence
0:3        move second child to first child ( temp int)
0:3          'x' ( temp int)
0:3          Constant:
0:3            2 (const int)
0:4      Branch: Return with expression
0:4        Constant:
0:4          0.000000
0:2  Function Definition: main( ( temp void)
0:2    Function Parameters: 
0:?     Sequence
0:2      move second child to first child ( temp float)
0:?         '@entryPointOutput' (layout( location=0) out float)
0:2        Function Call: @main( ( temp float)
0:?   Linker Objects
0:?     '@entryPointOutput' (layout( location=0) out float)

**Comment by dneto0** [comment]
Test hlsl.intrinsics.frag shows evidence that it's parsed and codegen'd correctly in some cases:

```
...
    float r042 = log2(inF0);
...
```

becomes this fragment in the test output:

```
             279:    6(float) Load 13(inF0)
             280:    6(float) ExtInst 1(GLSL.std.450) 30(Log2) 279
                              Store 278(r042) 280
```

So is the bug somehow when the value is returned?

**Comment by dneto0** [comment]
If I change the type of the x variable to float, the right code is emitted.

**Comment by dneto0** [comment]
The problem occurs even if I only assign to a variable:

```
float main(): SV_Target0
{
        float f = log2(5);
        return f;
}
```

```
gl_FragCoord origin is upper left
0:? Sequence
0:2  Function Definition: main( ( temp float)
0:2    Function Parameters: 
0:?     Sequence
0:3      Sequence
0:3        move second child to first child ( temp float)
0:3          'f' ( temp float)
0:3          Constant:
0:3            0.000000
0:4      Branch: Return with expression
0:4        'f' ( temp float)
0:?   Linker Objects
```

**Comment by johnkslang** [comment]
It's some problem with the way overloaded function resolution is done under implicit conversion.  I'll look into it.

(FXC treats these built-ins the same way as operators, somewhat ad hoc and arbitrary, while glslang uses real function prototype matching, forcing more regularity, making it a bit difficult to exactly match FXC behavior.)

**Comment by johnkslang** [comment]
I found the problem.  The conversion path to promote the argument to a single-argument built-in goes through the "unary" promotion path, which only supports ++, --, !, and ~, the traditional unary operators.

So, generally, all single-argument built-in calls needing an implicit conversion of a non-float for their argument should be failing.

**Comment by johnkslang** [comment]
In generating test cases to stress this more (built-in function selection and return type selection base on input arguments under implicit conversion), I uncovered two more issues:

1. There is a chicken-and-egg problem with many of these functions: their return type is based on their argument type, yet the argument type can get converted, this has to get sorted out in a different order than it sometimes is.

2. One path will convert a single argument having multiple components (e.g. a literal int2) into multiple arguments (i.e., two ints).

Still looking at how much to fix here, how many independent fixes there are.

**Comment by johnkslang** [comment]
The PR submitted fixes the cases submitted, because they were scalar and that was an easy path.  But, it is also an accidental fix that is not complete, as per the previous comment.  Still, it probably catches a major portion of the actual examples.

**Comment by zeux** [comment]
Thanks! I've verified that with the latest master this isn't a problem anymore. It's not clear to me what other issues exist here and if there's extra work planned here - since the original issue we ran into is now fixed I'm going to close this.
