### ISSUE TITLE
Full-featured build on Web

### ISSUE THREAD

**Issue by eugeneko** [KhronosGroup/glslang#2072]
Hello everyone!

I'm working on C++ framework that builds on all major platforms (Desktop, Mobile, Web) and I want to use glslang as 3rd-party library there.

Therefore, I need to build `glslang` on Web as if it is Desktop platform, i.e. I want to have 100% same behavior and functionality.
I don't need any grammar featurecut or minimalistic build or whatever.

Can you please help me properly configure `glslang` with this goal in mind?

I'm not sure that I have to follow instructions from "Building to WASM for the Web and Node". It seems that these instructions are not for my specific case.

This folder is also quite suspicious:
https://github.com/KhronosGroup/glslang/tree/master/glslang/OSDependent/Web
I'm not sure that I need this "zeroCopy" thing in my build but I cannot disable it.
I also don't understand how TLS thing is handled in Web build since there's no implementation for `OS_AllocTLSIndex` and so on in `OSDependent/Web`.

Thanks,
Eugene.

**Comment by johnkslang** [comment]
@zoddicus do you have any advice here?

**Comment by zoddicus** [comment]
@eugeneko Are you compiling your framework with WASM, and you want a fully featured glslang as part of that build?

**Comment by eugeneko** [comment]
@zoddicus Yes, exactly that. I actually managed to build glslang and link to it when I commented out `OSDependent/Web` part, but I didn't test if it's working as intended.

Just to make things clean -- I don't need this functionality right now, but I may need it in the future if I decide to go this way.
So I wonder if I can expect `glslang` to build and run in fully featured state in Web, or I shouldn't rely on it and should find the way around.

**Comment by zoddicus** [comment]
@kainino0x can comment on the OSDependent/Web part, since he set that up.

Actually, also @kainino0x can you comment if there is a combination of flags/builds that produces a full glslang + WASM build?

**Comment by kainino0x** [comment]
You should be able to simply build with `-DENABLE_GLSLANG_WEB=OFF`, with some caveats.

In the npm package `@webgpu/glslang` we build this as the `web-devel` build:
https://github.com/kainino0x/-webgpu-glslang/blob/9ff0950/build.sh#L43
(You can use the version of the grammar that's checked in - no rebuild of the grammar needed.)

A side effect of including this as a dependency is that you'll end up with a glslang.js/glslang.wasm build output, which presumably you don't want. It probably won't break anything, but it will waste build time. To disable that, you'll want to skip this line (which I think you figured out):
https://github.com/KhronosGroup/glslang/blob/4ecd0f6/glslang/CMakeLists.txt#L10

Unfortunately there's no way right now to do this in an Emscripten build. However we really should clean this up a little - let me take a shot at it.

---

Re: TLS: We only currently build this in single-threaded mode, so possibly `OS_AllocTLSIndex` is just not called.

**Comment by kainino0x** [comment]
BTW, what features of glslang are you using on the Web that are excluded by the current minimized `ENABLE_GLSLANG_WEB=ON` build?

**Comment by kainino0x** [comment]
Actually, what I said above is probably not true. We probably mess up the link/compile options for the rest of the project. In any case, I'll have a PR soon to clean all this up.
