### ISSUE TITLE
Linking issue building as a library, after c_interface merge (DefaultTBuiltInResource)

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/glslang#2075]
I'm trying to upgrade my project to glslang master, and having an issue.

I'm using glslang as a statically linked library and I'm building without ENABLE_GLSLANG_BINARIES so the Standalone directory is not built.

However, glslang/CInterface/glslang_c_interface.cpp is always built, but it depends on the glslang::DefaultTBuiltInResource which is defined in Standalone/ResourceLimits.cpp.

This doesn't link:

```
  ext/glslang/glslang/libglslang.a(glslang_c_interface.cpp.o): In function `glslang_shader_preprocess':
  
  C:\dev\ppsspp/ext\glslang\glslang\CInterface\glslang_c_interface.cpp:355: undefined reference to `glslang::DefaultTBuiltInResource'

```

~DefaultTBuiltInResource  is useful enough that it should be in the core and not in Standalone - it's pretty annoying to need to define your own when you just want it all set to max.~

**Comment by corporateshark** [comment]
@hrydgard `ResourceLimits.cpp` can be compiled into the `glslang` project. For example, via CMake we do it like this:

```
target_sources(glslang PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/glslang/StandAlone/ResourceLimits.cpp)
```

**Comment by hrydgard** [comment]
Yeah it isn't hard to work around that way, but I think it's an issue that a dependency on a file suddenly appeared like that, and seems like a layering violation to have things outside of Standalone depend on files inside it.

**Comment by corporateshark** [comment]
@hrydgard This issue sounds legit. We can remove the dependency on `glslang::DefaultTBuiltInResource` and make the API user always provide these values explicitly, or we can move the definition into `glslang`, if @johnkslang does not mind.

**Comment by johnkslang** [comment]
I agree layering/dependencies got inverted here.

The resource limits in StandAlone are just examples, from a spec.  Are you sure they happen to be the correct values you want to run with?  They have not been part of the library form, so that the library user can explicitly provide their own more appropriate values.

It seems the C interface when used to expose the libraries should not require the standalone resource settings. Maybe if it's very clear there is an example struct that could be queried and used that would be an okay enhancement.

We should also be careful that there isn't new code here showing up under GLSLANG_WEB, which does not need this new interface.

**Comment by hrydgard** [comment]
For my particular use case where I build this as a library, I have small demands so the defaults are just fine - though thinking about it some more, I do prefer to set them myself anyway, it's not really that useful to have a default struct baked into the library.

**Comment by sl1pkn07** [comment]
same problem when try build shaderc

build glslang and add

~~~
target_sources(glslang PRIVATE ${CMAKE_SOURCE_DIR}/StandAlone/ResourceLimits.cpp)
~~~

between this lines

https://github.com/KhronosGroup/glslang/blob/ae59435606fc5bc453cf4e32320e6579ff7ea22e/glslang/CMakeLists.txt#L88-L89

do the trick

greetings

**Comment by johnkslang** [comment]
@dneto0, this is regarding the convenience of setting resource limits with a default choice from the spec intended for the command-line version of glslang. (Library form expects the user to supply something more sensible.)

I'm not sure what shaderc does in this space; do you have input on the change requested in the previous comment?

**Comment by hrydgard** [comment]
The issue is that linking ResourceLimits.cpp accidentally became *required* after the C interface was added. It wasn't before, you could easily supply your own stuff (still can, but even so now need to link ResourceLimits.cpp).

**Comment by sfricke-samsung** [comment]
Ran into same issue, I guess to me the ways to solve this are
- Make the C interface consume a user defined `TBuiltInResource`
- Have a default `TBuiltInResource` in libglslang
- wrap including `glslang_c_interface.cpp` as a source file only if `ENABLE_GLSLANG_JS` or `ENABLE_GLSLANG_BINARIES` are set to ON as they have a definition of the `DefaultTBuiltInResource`

Not sure which one we want to choose, but I rather not have to add an extra "modify the source before building" step like I currently do now

**Comment by johnkslang** [comment]
Closing assuming that #2092 solved the main issue here.  Reopen (or open another) if there is still an issue.

**Comment by sl1pkn07** [comment]
same issue with shaderc

~~~
[29/29] Linking CXX executable glslc/glslc
FAILED: glslc/glslc 
: && /usr/bin/c++  -march=native -O2 -pipe -fno-plt -Wimplicit-fallthrough  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now    -rdynamic glslc/CMakeFiles/glslc_exe.dir/src/main.cc.o  -o glslc/glslc  glslc/libglslc.a  libshaderc_util/libshaderc_util.a  libshaderc/libshaderc.a  libshaderc_util/libshaderc_util.a  -lSPIRV-Tools-opt  -lSPIRV-Tools  -lglslang  -lOSDependent  -lOGLCompiler  -lglslang  -lOSDependent  -lOGLCompiler  -lSPIRV  -lHLSL  -lpthread && :
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../lib/libglslang.so: undefined reference to `glslang::DefaultTBuiltInResource'
collect2: error: ld returned 1 exit status
~~~
