### ISSUE TITLE
Vertex Shader location overlap, wrong?

### ISSUE THREAD

**Issue by cheako** [KhronosGroup/glslang#2085]
https://gitlab.com/cheako/hazel-rs/-/blob/d0e7f5796033b7b2193aeade0a09fe3f8566749f/src/renderer/r2d.rs#L157
```
#version 450 core

layout (location = 0) in mat4 inTransform;
layout (location = 1) in vec4 inColor;
layout (location = 2) in uint inType;
layout (location = 3) in uint inImageId;
layout (location = 4) in vec2 inPading;

layout (location = 0) out mat4 outTransform;
layout (location = 1) out vec4 outColor;
layout (location = 2) out uint outType;
layout (location = 3) out uint outImageId;

void main(){
    outTransform = inTransform;
    outColor = inColor;
    outType = inType;
    outImageId = inImageId;
}
```

Changing the location numbers I can see, it's the outColor.

https://gitlab.com/cheako/hazel-rs/-/jobs/440501688
```
             ERROR: /tmp/.tmpKAGjZ2/0.vert:10: 'location' : overlapping use of location 1
             ERROR: 1 compilation errors.  No code generated.
             
             
             ERROR: Linking vertex stage: Missing entry point: Each stage requires one entry point
             
             SPIR-V is not generated for failed compile or link
             
             failed to compile shader
```

**Comment by johnkslang** [comment]
What is the glslang issue here?

The provided shader seems to get the correct error message, so I'm not sure what's being declared as an issue.

FYI, from the specification, if it helps:

> If the declared input is an n × m matrix, it will be assigned multiple locations starting with the location specified. The number of locations assigned for each matrix will be the same as for an n-element array of m-component vectors.

**Comment by cheako** [comment]
In English please.

**Comment by johnkslang** [comment]
What issue to you have with glslang?

**Comment by cheako** [comment]
It doesn't explain well!

**Comment by johnkslang** [comment]
I see.

> Changing the location numbers I can see, it's the `outColor`.

In the error message:

> ERROR: /tmp/.tmpKAGjZ2/0.vert:10: 'location' : overlapping use of location 1

The `10` means line 10, which contains the declaration of `outColor`, so that should not require any effort of modifying the shader.
