### ISSUE TITLE
glslang::TIntermTyped* glslang::TIntermediate::fold(glslang::TIntermAggregate*): Assertion `arg1 != 0.0' failed

### ISSUE THREAD

**Issue by afd** [KhronosGroup/glslang#2091]
Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

Tool versions:

* glslangValidator commit hash: ed0da37dd994fda72dafca334a376bb762787d0b

To reproduce:

`glslangValidator -V shader.frag -o shader.frag.spv`

The following shader files are included in the attached archive, some of which are also shown inline below:

* variant/0_glsl/shader.frag

variant/0_glsl/shader.frag:

```
#version 310 es
precision highp float;

void main()
{
 mod(vec4(1.0), vec4(1.0, 0.0, 1.0, 1.0));
}

```

[bug_report.zip](https://github.com/KhronosGroup/glslang/files/4249519/bug_report.zip)

**Comment by johnkslang** [comment]
Functionality was added in December by 44e842cd9, but the assert not be there.  I'll delete it.
