### ISSUE TITLE
Compilation error when using integer samplers as constructor

### ISSUE THREAD

**Issue by prollin** [KhronosGroup/glslang#2097]
**Repro**:
```
#version 450

layout(set = 0, binding = 0) uniform texture3D t;
layout(set = 0, binding = 1) uniform sampler s;

layout(location = 0) out vec4 outFragColor;

void main()
{
    uvec2 texel = texelFetch(usampler3D(t, s), ivec3(0, 0, 0), 0).rg;
    if (texel.r > 0)
        outFragColor = vec4(0, 1, 0, 1);
    else
        outFragColor = vec4(1, 0, 0, 1);
}
```

**Result** ([shader-playground](http://shader-playground.timjones.io/24ba1cbfd86bc9500a2c14a1d983af04)) :
```
ERROR: D:\local\Temp\f6b4d14c-16e8-44fb-9574-1c5aae4e935b.tmp:10: 'usampler3D' : sampler-constructor first argument must match type and dimensionality of constructor type
```

I might very well be doing something wrong here but according to the [spec](https://github.com/KhronosGroup/GLSL/blob/28b3d1d385dddedf008482a79c5e654f54c1e424/extensions/khr/GL_KHR_vulkan_glsl.txt#L1372), every sampler type can be used as a constructor.
Using a combined texture/sampler uniform works, but is not ideal with our current shader pipeline.

**Comment by johnkslang** [comment]
Yes, `usampler3d` just needs a `utexture3d` for type matching.

**Comment by prollin** [comment]
Thank you @johnkslang ! 

While it makes perfect sense now, maybe the error message should suggest to use utexture1D/2D/3D in this case. Those new types are briefly mentioned in the spec with no example which makes them easy to miss in my opinion (especially when most online resource use combined texture/sampler syntax).

**Comment by johnkslang** [comment]
I improved the error a bit now:

```
'usampler3D' : sampler-constructor first argument must be a *texture* type matching the dimensionality and sampled type of the constructor
```
