### ISSUE TITLE
There is no c interface support for TBuiltInResource

### ISSUE THREAD

**Issue by travisfoo** [KhronosGroup/glslang#2099]
#2092 Added a requirement to pass a glslang_resource_t (TBuiltInResource) as a part of glslang_input_t. It is forward declared in glslang_c_interface.h, and the header with the definition (ResourceLimits.h) is not a c-compatible file. Therefore, the functions glslang_shader_preprocess and glslang_shader_parse do not work correctly.

**Comment by travisfoo** [comment]
I've added pull request https://github.com/KhronosGroup/glslang/pull/2100 to fix this issue.

**Comment by travisfoo** [comment]
I realized that my pull request #2100 reintroduced the issue #2075 - I've added follow up pull request #2101 to fix that issue.

**Comment by johnkslang** [comment]
#2101 was merged, but didn't reference this issue (e.g., "fix #2099").

Closing manually.
