### ISSUE TITLE
OpenCL.std and OpenCL.DebugInfo.100 resolve to the same extended instruction set in the disassember, and possibly other places

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/glslang#2114]
For the extended instruction set enum, there is only one OpenCL value, so it is impossible to distinguish between these two extensions.

See https://github.com/KhronosGroup/glslang/pull/2107 for where this occurs in the code.

**Comment by johnkslang** [comment]
I believe this was fixed by #2017.  Reopen if I'm incorrect.
