### ISSUE TITLE
Cannot use glslang with Visual Studio 2017

### ISSUE THREAD

**Issue by Hotshot5000** [KhronosGroup/glslang#2125]
After building glslang and trying to link with project I get:
`glslangd.lib(ShaderLang.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in OgreVulkanWin32Window.obj`
Visual Studio 2017 doesn't have MSC_VER 1800. Is there any way to force glslang to build for 1900?

**Comment by johnkslang** [comment]
Where do we say it's 1800?

**Comment by Hotshot5000** [comment]
When downloading the provided binaries for x64 it looks like they are built for MSVS 2013 and cannot be linked directly to a VS 2017 project.

I was trying to build glslang directly. After I build google shaderc it appears that it created the right glslang version.

I think it can be closed.
