### ISSUE TITLE
GLSL and Vulkan, supporting existing OpenGL GLSL shaders

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#2126]
This is a question/discussion, not a bug report.
My user base has a huge amount of existing GLSL shaders they have written for my application, which is currently OpenGL backed. I'm now porting to Vulkan, and all of these shaders need to continue to work without edits. GL_KHR_vulkan_glsl obviously breaks a huge amount of existing GLSL shaders. Also people enjoy being able to bring stuff from shadertoy/GLSLSandbox, which they can do right now with minimal edits, but would require far more with current GLSL for Vulkan requirements.

Ideally the shader writer shouldn't have to think at all about the underlying API used to consume the shader. It seems like the HLSL to Vulkan path is following this idea, so I see no reason why GLSL shouldn't be the same.
The GLSL writer in this usage case only knows GLSL, they don't know anything about Vulkan, descriptor sets, push constants etc.

Some things that would need to be supported:
- default uniforms - Need to be silently grouped into a uniform block
- push_constants - How a block is backed, push constant or uniform buffer, can be decided at run-time but the shader consumer, not the shader writer. Along with allowing existing GLSL to compile, this also allows the decision to back a block by push constants to be based on the host machines push constant limits, rather than hard coded.
- gl_VertexID, gl_InstanceID need to be accepted. The fact their behavior changes seems fine to me.
- Although likely not an issue for me, shared and packed layout should be accepted but ignored, since the shader writer doesn't care about how their data is backed.
- Which set each uniform belong to needs to be set by the shader consumer, so they can group the uniforms as they see fit for their engine. Maybe this is already possible by changing the intermediate data after compilation?

Adding these features is pretty much a requirement for my software, so we're going to take on the work. My main question is: should this be a branch that stays separate, or is this something which GLSLang would be interested in having merged in? And if merging is desired, is there a more formal process I should follow to further flesh out this plan?

Thanks!

**Comment by johnkslang** [comment]
One difference is that GLSL is following a standard specification, while HLSL is not.

I can see the value in having GLSL more fluidly get mapped to Vulkan rules.  I think the formalization needed to do that is a specification that says how the mapping is done.  Then, a command-line option could mean it follows the semantics of that specification.

**Comment by mbechard** [comment]
Ok sounds good. Should this go under an a GL extension the way GL_KHR_vulkan_glsl is, or something different. Not familiar with this process currently.

**Comment by johnkslang** [comment]
If it's tied to a `#extension`, then yes, it would certainly go as a vendor-specific or `EXT` extension, in the GLSL GitHub registry.

However, if this is something that does not modify the source and is tied to a command-line option, it would not have a `#extension`.  I still think it is worth writing as an extension-like document and adding to the GLSL GitHub repository.

See https://github.com/KhronosGroup/GLSL.

**Comment by mbechard** [comment]
Ok, very helpful. I don't see it being something that's enabled with #extension. I see it as a 'relaxed' extension that is built on-top of GL_KHR_vulkan_glsl. It still supports all of the additions that that extension adds, but then describes what removed features are supported, and how they are handled. I don't think it would go into SPIRV-V/OpCode discussion, as hopefully the GLSLang implementation would do the conversion at the AST/Intermediate level.

**Comment by mbechard** [comment]
Beginnings of the spec are available here:
https://github.com/mbechard/GLSL/blob/master/extensions/ext/GL_EXT_vulkan_glsl_relaxed.txt

**Comment by johnkslang** [comment]
Yes, nice.  This may be quite helpful.

**Comment by mbechard** [comment]
Ok so the code for this now complete we think. Is there a different way to of getting a GLSL extension approved vs. a regular OpenGL one. Do I just do a pull request for it?

**Comment by johnkslang** [comment]
You can just create a pull request for an EXT at https://github.com/KhronosGroup/GLSL.

**Comment by mbechard** [comment]
One issue came up you may have some thoughts on. For the atomic counters right now a different storage block is created for each binding # used. So for example

```
layout(binding = 0, offset = 0) uniform atomic_uint one;
layout(binding = 0, offset = 4) uniform atomic_uint two;
layout(binding = 1) uniform atomic_uint three;
```

Would be converted into
```
layout(std430, binding = 0) buffer gl_AtomicCounterBlock_0
{
    uint one;
    unit two;
};

layout(std430, binding = 1) buffer gl_AtomicCounterBlock_1
{
    uint three;
};
```
The assumption would be that the host application would provide a unique set # for the atomic counters to be located in so their bindings don't conflict with other resources.

An alternative approach would be to merge all of the atomic counters into a single block, sorted by binding first, followed by offset. This would avoid the messy block naming that needs to occur. The host application using glslang would be responsible for changing their atomic counter allocations to match what reflection ultimately told them where the variables ended up being located.
Any opinion on which way makes more sense?

Second question, should the functionality to change the backing of the blocks be included in this spec, or is that just a glslang feature that doesn't fit within this extension?

**Comment by mbechard** [comment]
After working with it more, the first solution seems to be nice to work with.

**Comment by johnkslang** [comment]
I suspect you'll want different blocks for different binding numbers.

Right, the implementation design does not go in the extension specification.

(Hopefully answering the question; not quite sure.)

**Comment by mbechard** [comment]
This is now merged into master.
https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_vulkan_glsl_relaxed.txt
