### ISSUE TITLE
-V incorrect constant folding?

### ISSUE THREAD

**Issue by paulthomson** [KhronosGroup/glslang#2132]
Issue found using [GraphicsFuzz](https://github.com/google/graphicsfuzz).

In the shader below, `a` and `b` should be equal, and so the shader should always output red. However, the SPIR-V that is output does not render red. 

[bug_report.zip](https://github.com/KhronosGroup/glslang/files/4343748/bug_report.zip)

Tool versions:

* glslangValidator commit hash: dbb56a1d48592d24afb89550a47bda0a9bf14df3

To reproduce:

`glslangValidator -V shader.frag -o shader.frag.spv`

The following shader files are included in the attached archive, some of which are also shown inline below:

* variant/0_glsl/shader.frag
* variant/1_spirv/shader.frag.spv
* variant/1_spirv_asm/shader.frag.asm

variant/0_glsl/shader.frag:

```
#version 310 es
precision highp float;

layout(location = 0) out vec4 _GLF_color;

void main()
{
  vec4 a = vec4(1.0, 2.0, 3.0, 4.0);
  vec4 b = vec4(mat2(vec4(1.0, 2.0, 3.0, 4.0)));
  if (a == b)
    _GLF_color = vec4(1, 0, 0, 1);
  else
    _GLF_color = vec4(0, 0, 0, 1);
}

```

variant/1_spirv_asm/shader.frag.asm:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 8
; Bound: 31
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %4 "main" %27
               OpExecutionMode %4 OriginUpperLeft
               OpSource ESSL 310
               OpName %4 "main"
               OpName %9 "a"
               OpName %15 "b"
               OpName %27 "_GLF_color"
               OpDecorate %27 Location 0
          %2 = OpTypeVoid
          %3 = OpTypeFunction %2
          %6 = OpTypeFloat 32
          %7 = OpTypeVector %6 4
          %8 = OpTypePointer Function %7
         %10 = OpConstant %6 1
         %11 = OpConstant %6 2
         %12 = OpConstant %6 3
         %13 = OpConstant %6 4
         %14 = OpConstantComposite %7 %10 %11 %12 %13
         %16 = OpConstant %6 0
         %17 = OpConstantComposite %7 %10 %16 %16 %13
         %20 = OpTypeBool
         %21 = OpTypeVector %20 4
         %26 = OpTypePointer Output %7
         %27 = OpVariable %26 Output
         %28 = OpConstantComposite %7 %10 %16 %16 %10
         %30 = OpConstantComposite %7 %16 %16 %16 %10
          %4 = OpFunction %2 None %3
          %5 = OpLabel
          %9 = OpVariable %8 Function
         %15 = OpVariable %8 Function
               OpStore %9 %14
               OpStore %15 %17
         %18 = OpLoad %7 %9
         %19 = OpLoad %7 %15
         %22 = OpFOrdEqual %21 %18 %19
         %23 = OpAll %20 %22
               OpSelectionMerge %25 None
               OpBranchConditional %23 %24 %29
         %24 = OpLabel
               OpStore %27 %28
               OpBranch %25
         %29 = OpLabel
               OpStore %27 %30
               OpBranch %25
         %25 = OpLabel
               OpReturn
               OpFunctionEnd

```

**Comment by johnkslang** [comment]
You can use `-i` to see the AST is not getting this right, so not `-V` based, so I changed the title.

I'll have a quick look, but I doubt this is an important pattern for making a constant matrix.  If the fix is complex, will leave this as low priority.

**Comment by johnkslang** [comment]
So, if there is a single argument to the constructor, it initializes the matrix diagonal from the argument, and the rest to the identity matrix.  This conflates single-scalar argument with single-non-scalar argument.  This is why it works to construct the matrix from the components, but not after passing them through a vector.

**Comment by paulthomson** [comment]
Thanks for the fast fix!
