### ISSUE TITLE
Construct a buffer reference from a uint64_t value

### ISSUE THREAD

**Issue by allanmac** [KhronosGroup/glslang#2133]
Given a buffer reference type `buf_ref_type` and the `uint64_t` device address value `dev_addr`, creating a buffer reference and assigning it to another reference compiles cleanly:

```
buf_ref_type buf_ref = buf_ref_type(dev_addr);
```
But this does not compile:
```
buf_ref_type buf_ref(dev_addr);
```
And produces an error similar to this:
```
glslangValidator -V120 -Os -S comp bufref.comp
bufref.comp
ERROR: bufref.comp:30: '' :  syntax error, unexpected IDENTIFIER, expecting RIGHT_PAREN
ERROR: 1 compilation errors.  No code generated.
```

It would be more convenient to construct the reference directly from the `uint64_t` value.

Is there a reason why this isn't feasible?

[bufref.txt](https://github.com/KhronosGroup/glslang/files/4345654/bufref.txt)

**Comment by johnkslang** [comment]
That is an advanced C++ syntax not supported in GLSL.  More simply, the following does not work:

`int i(4);`

Is that what you are asking for?  It's not about buffers, just the general constructor syntax.

GLSL does not currently include the analysis to see this is a constructor and not a function prototype declaration.

If you want to add this to GLSL, open an issue for an enhancement request in https://github.com/KhronosGroup/GLSL.

**Comment by allanmac** [comment]
Ooops, I misinterpreted the changes to 5.4.1 by `GLSL_EXT_buffer_reference`.

Thanks!
