### ISSUE TITLE
Shouldn't TIntermediate::mergeLinkerObjects be matching blocks by block-name, not instance-name

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#2136]
Currently if you have two blocks with different layouts in two compilation units, with the same block-name, but different instance-name, the validator does not fail.
[SameBlockDiffInstance2.txt](https://github.com/KhronosGroup/glslang/files/4351610/SameBlockDiffInstance2.txt)
[SameBlockDiffInstance1.txt](https://github.com/KhronosGroup/glslang/files/4351611/SameBlockDiffInstance1.txt)
I think this should fail, no?

Conversely, if you have 2+ anonymous blocks (legal ones) it will fail if they are declared in different order, since it will be trying to match up by anon@0, naming, not the block names.

[MultiAnonBlocks1.txt](https://github.com/KhronosGroup/glslang/files/4351633/MultiAnonBlocks1.txt)
[MultiAnonBlocks2.txt](https://github.com/KhronosGroup/glslang/files/4351634/MultiAnonBlocks2.txt)

Seems like the root issue is that TIntermediate::mergeLinkerObjects is matching up the blocks by instance name and not block name.

Working on a patch, but let me know if I'm off base. Thanks

**Comment by johnkslang** [comment]
This is certainly true across stages: One stage linking to the next stage is done by block name.  The specification says quite a bit about that:

> The block name (block-name) is used to match within shader interfaces ...

> ... When instance names are present on matched block names, it is allowed for the instance names to differ; they need not match for the blocks to match. ...

Note that language is about stage A interfacing with stage B, or the application interfacing with a stage.

Language is less explicit regarding matching within a stage, where multiple compilation units of the same stage link together to form a single stage, which would occur before the interface matching is done.

Essentially, compilation unit linking within a single stage is not about interface matching, so all that language about block name matching for interface matching does not apply.

While block names are for interface matching and don't have other use within the compilation unit, the instance name is a normal global variable within the compilation units, and the normal rules for those needing the same type should apply.

It almost seems forced that if the instance names match in type that the block names will also have to match.  If that's true, we could link based on either one (ignoring anonymous for the moment), and error check that the other also matches.

For anonymous names to match, I think this would also work, that if an anonymous name is, say, the 3rd member of a struct, and it matches another name, that other name would also have to be the 3rd member of a struct with the same type.  That again probably forces block names to match.

Summary:
- first principle: link within a stage by names within the shader, meaning instance/anonymous-naming, not block naming
- first principle: link across stages by block name
- likely corollary: if instance name linking is to succeed, block names probably also have to match

**Comment by mbechard** [comment]
Thank you for your detailed response. I will of course differ to your direction here. I do want to mention two data points though.

The GLSL spec defines a _shader interface_ as:

> A shader interface is defined to be one of these:
> • All the uniform variables and uniform blocks declared in a program. This spans all compilation
> units linked together within one program.

I read this to mean the rules apply for compilation units within a stage as well.

Also, for what it's worth, Nvidia's OpenGL GLSL compiler does allow different instance names for the same block name within a shader stage. I understand that is likely not relevant though.

Let me know if my interpretation of the spec line is incorrect and I'll go from there.
Thanks

**Comment by johnkslang** [comment]
> Also, for what it's worth, Nvidia's OpenGL GLSL compiler does allow different instance names for the same block name within a shader stage. I understand that is likely not relevant though.

Because blocks are per interface, and a shader can have two interfaces (in and out), this seems relevant to saying things need to match by interface name and not by block name.  Or, at minimum, first slice the block names by interface, and then match.

Unit 1:
```
in blockName1 {
...} instanceName1;

out blockName2 {
...} instanceName2;
```

Unit 2:
```
out blockname1 {
...} instanceName2;
```

**Comment by mbechard** [comment]
Hey, sorry. I'm not sure I follow your answer. I meant that Nvidia's compiler allows uniform blocks declared in multiple compilation units within the same stage to have different instance names, and matching is just done with block name. I'm not referring to in and out blocks in this issue.

**Comment by johnkslang** [comment]
Well, maybe we will end up with different rules for uniform blocks than for in/out blocks.  in/out blocks allow the re-use of the block name across the in and out interfaces, as they are two different interfaces, so linking within a stage has to be done based on the instance name, yes?

We do need to either make a uniform-only change, or also consider the impact to in/out blocks.

**Comment by mbechard** [comment]
Thanks for your patience John. I follow what the deficiency is now; my change isn't accounting for stages that have both input and output interfaces such as geometry shaders, where block-names will often be the same for the input and output interfaces, correct?

What you suggest, slicing by shader interface first then matching by block name, seems like the way forward.
So slice into sets:
* uniform block shader interfaces
* buffer block shader interfaces
* input block shader interfaces
* output block shader interfaces

And then validate within the shader interface set, matching by block name.

Interestingly, although the Nvidia compiler disallows it, the spec seems to say that a block name can be re-used in all the different shader interface types, not just the input/output ones.

> A block name is allowed to have different definitions in different shader interfaces
within the same shader, allowing, for example, an input block and output block to have the same
name. 

So it's legal to have:
```
  uniform BlockName1 {}; 
  buffer BlockName1 {};
  in BlockName1 {};
  out BlockName1 {};
```

In addition to the above checks, I may also need to also adjust instance-name validation a bit to ensure there are no conflicts.

I also think the validator is failing to account for this rule:

> Matched uniform or shader storage block names (but not input or output block names) must also
either all be lacking an instance name or all having an instance name, putting their members at the
same scoping level.

So I'll also add that also.
Sound good?

**Comment by mbechard** [comment]
For rationalizing symbols between the trees (seedIdMap, remapIds), I split up the symbols into the 4 shader interface types and 'none', when putting them into the map. If the symbol is a shader interface type it matched by the block name (getTypeName), otherwise it just matches by the symbol name.
This seems correct and the existing tests all continue to work.

**Comment by mbechard** [comment]
First pass committed:
https://github.com/mbechard/glslang/commit/9ebf9883401ef1c9650c97309c26a2b751af71ca

**Comment by johnkslang** [comment]
This sounds much closer.  I almost think it should be an error now, after separating into all these interface, to then match on block name and not on instance name (or vice versa).  Maybe we should at least emit a warning about it.

**Comment by johnkslang** [comment]
Yes, I'd say emit a warning.

I'm okay with matching by block name if a warning is emitted for block names matching but instance names not matching.  That way, both models work in practice.

**Comment by mbechard** [comment]
Ok sounds good!

**Comment by mbechard** [comment]
Given https://github.com/KhronosGroup/GLSL/issues/115, anything that needs to be tweaked to this now? Happy to do whatever change is needed.

**Comment by johnkslang** [comment]
I think going to three name spaces, like we did, provides the most portability, as shaders that succeed with three name spaces will also work with four, but the reverse is not true.

Yes?

**Comment by mbechard** [comment]
Guess it depends on which usage case of glslang is more important. If it's the certify shaders, saying "if they work in glslang, then they should work in other compilers", then yes. If the goal is becoming more of a Vulkan front-end tool, then the opposite would be better since it'll allow glslang to consume 4-namespace shaders that previously worked in other compilers when people port over the Vulkan.

**Comment by johnkslang** [comment]
Yes, agreed definitely with the first half of that (validation).

For the second half (code gen), it still helps with portability, unless content cannot be changed and doesn't need to be portable.

If you felt strongly enough to change back to 4 name spaces and give a warning on potential collisions, I'd be happy with that too.

**Comment by mbechard** [comment]
I'm good with just three. Thanks!
