### ISSUE TITLE
matching push_constants with different instance names generate invalid SPIR-V

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#2137]
The block name matches, but the instance name is different. This should be legal, but the SPIR-V incorrectly ends up with two push constant declarations.

[link.vk.pcNamingValid.0.0.txt](https://github.com/KhronosGroup/glslang/files/4352410/link.vk.pcNamingValid.0.0.txt)
[link.vk.pcNamingValid.0.1.txt](https://github.com/KhronosGroup/glslang/files/4352411/link.vk.pcNamingValid.0.1.txt)

**Comment by johnkslang** [comment]
Can we just make this a duplicate of #2137?

**Comment by mbechard** [comment]
Yep, the fixes to #2136 solve this as far as I can tell (not great with SPIR-V yet). The generated SPIRV-V no longer has multiple push constants declared.
