### ISSUE TITLE
There is no way to generate debug symbols with the C interface

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/glslang#2143]
https://github.com/KhronosGroup/glslang/blob/9659831766f1be87a6aaf6df8302ec61be0ca05a/glslang/CInterface/glslang_c_interface.cpp#L404

glslang::SpvOptions::generateDebugInfo is always false

**Comment by johnkslang** [comment]
Note that this has been conditionally set for command-line use:

https://github.com/KhronosGroup/glslang/blob/b5757b95005bbf6b0287096c5b708c5e25645311/StandAlone/StandAlone.cpp#L1146

Perhaps you can do a PR that does the same for the C interface?
