### ISSUE TITLE
Vulkan AMD can not load compiled SPIR-V shader

### ISSUE THREAD

**Issue by danilw** [KhronosGroup/glslang#2144]
I think this is AMD driver bug I have post [bugreport to AMD](https://community.amd.com/message/2964120), maybe not their bug, idk

Bug:
```
void AMD_loop_bug() {
    for (int k = 0 ; k < 1; k++) {
        for (int i = 0 ; i < 1; i++) {
            
            if(i<1000)break; //FIRST part of bug
            
            for (int j = 0 ; j < 1; j++) {
                if (true)return; //SECOND part of bug
            }
        }
        if (true)break; //THIRD part of bug, comment any of parts and bug gone
    }
}
```
1. add this function to any shader and call it `AMD_loop_bug();`
2. load compiled by glslang-compiler *spir-v* file to application
3. Vulkan application will crash on `vkCreateGraphicsPipelines` or sometime after loading shader with error `device lost` or `wait for fence failed`

**Comment by johnkslang** [comment]
I don't immediately see an issue with the SPIR-V.  Let's wait for your other bug response.
