### ISSUE TITLE
Cmake minimum version

### ISSUE THREAD

**Issue by nverno** [KhronosGroup/glslang#2145]
Should the cmake set a minimum version of 3.13.5?

I'm not too familiar with the details of cmake, but when trying to compile with versions less than 3.13.5, I run into an error for `add_link_options`, which I see on the cmake page appears to have been added in that version.

**Comment by johnkslang** [comment]
I believe we are still waiting for 3.1 and above support.  From the top of the root CMakeLists.txt:

```
# increase to 3.1 once all major distributions
# include a version of CMake >= 3.1
```

@kainino0x is there another way to accomplish 5166bc185?

I see we have some conditional support in other places, based on testing

```
if(${CMAKE_VERSION} VERSION_LESS 3.1)
```

**Comment by kainino0x** [comment]
It didn't occur to me to test with older CMake. I'll try tomorrow and see if I can get it to work with 2.8.

**Comment by nverno** [comment]
As a follow-up, maybe this should be another issue, but I believe the instructions for Building to WASM are out-of-date in the README.  For example, it doesn't appear that `ENABLE_GLSLANG_WEB` is an option any longer.  

I wasn't able to get a minimized grammar to build at all using the `WEBMIN` and `JS` variables -- for some reason `GLSLANG_WEB` wasn't being defined when compiling MachineIndependent files.  It's probably a configuration problem on my end, but it doesn't look like this project tests the minimized build on the CI?

**Comment by kainino0x** [comment]
For the readme, looks like the steps are up to date but the example command isn't. I'll fix that too.
