### ISSUE TITLE
Problematic `switch(0u): default` branch idiom in glslang output

### ISSUE THREAD

**Issue by hugoam** [KhronosGroup/glslang#2148]
It seems glslang has come up with (or increased the frequency of), sometimes in the previous months, I think, a rather peculiar pattern which looks something like this (in pseudo-code since the output is actually SPIR-V):
```
    vec4 _801;
    switch (0u)
    {
        default:
        {
            if (/* ... */)
            {
                _801 = /* assign a value */;
                break;
            }
            _801 = /* assign another value */;
            break;
        }
    }
```
This seems to happen in the HLSL to SPIR-V path at least, when inlining a function that conditionally returns different possible values, although I couldn't reduce my sample far enough to isolate exactly when that happens.
Is there a good specific reason for this peculiar idiom ?

Albeit not incorrect, this kind of code is problematic in the case of D3D related pipelines.
When fed to the D3D shader compiler, such code, having gone through glslang at some point, turns out to be highly problematic, as the D3D compiler is both incapable to correctly analyse that no code paths ends up with the variable potentially uninitialized — in the case of those tricky switch statements, and at the same time very picky about reading from unitialized variables, producing hard compile errors in those cases.

I'm not opening this issue to unequivocally say: it's something glslang should fix, but if you have any insights about how this was introduced and potential ways to workaround this problem.
The responsibility of fixing this could be pushed to the next cross compiler in the chain, but it seems a rather complex task, so I'm pessimistic about the feasability.
Fixing the D3D compiler itself doesn't seem easily doable either.
Finally, would it be conceivable to make this behavior somehow togglable trough some sort of option ?

**Comment by hugoam** [comment]
I've pinpointed the substitution of this idiom inside `SpirvToolsLegalize`, which I seemingly can disable by setting `SpvOptions::disableOptimizations` to `true`, although I'm not positive yet that this will not cause me further issues.

**Comment by hugoam** [comment]
After much investigating, it turns out this is due to a recent change indeed, but not in `glslang`, but in SPIRV-Tools
I suppose this can be closed, and I'll open an issue there to ask for directions about this
https://github.com/KhronosGroup/SPIRV-Tools/commit/e7afeb060e1637ca964c62517c3e6c225704b7eb

**Comment by johnkslang** [comment]
Thanks for figuring all that out, and for opening an issue in SPIRV-Tools.
