### ISSUE TITLE
Objects of rayQuery type need to be passed by reference to user functions as well

### ISSUE THREAD

**Issue by alelenv** [KhronosGroup/glslang#2150]
As per current code in https://github.com/KhronosGroup/glslang/blob/master/Test/baseResults/rayQuery-no-cse.rgen.out

I am seeing
91:          10 Load 89(rayQuery1)
               Store 90(param) 91
93:          14(Ray) Load 71(ray)
               Store 92(param) 93
94:    2    FunctionCall 19(doInitialize(rq1;struct-Ray-vf3-f1-vf3-f11;) 90(param) 92(param)

**Comment by dgkoch** [comment]
cc @neslimsah @tobski

**Comment by Tobski** [comment]
Ok now that you've pointed out the error I see what you mean - and agree this is a bug, as loads/stores of this type are not allowed - @neslimsah can you take a look at fixing this?

**Comment by dgkoch** [comment]
I believe this was resolved by #2157. @alelenv if so, please close (I don't have permission to).

**Comment by johnkslang** [comment]
Reminder: If you say "Fix #2150" in your commit message, it will auto-close the issue when it is merged into master.
