### ISSUE TITLE
mapIO() and Vulkan auto bindings

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#2151]
Currently running into an issue where bindings #s are duplicated when using setAutoMapBindings(true); with Vulkan.
Looking into it I realized auto mapping is only done within stages, so multiple stages can end up re-using bindings, which causes errors when trying to create the descriptor set layout due to duplicated binding numbers.
Does TDefaultIoResolver do what I want here? Should mapIO() be using TDefaultIoResolver if a resolver isn't specified? TDefaultIoResolver is currently not publicly exposed, is it hidden for some other reason?
Is this just functionality that isn't implemented yet?
Thanks

**Comment by johnkslang** [comment]
I don't think we have anything yet that will do correct mappings across stages.  You might need to use the finer grained controls we have to do that.

**Comment by mbechard** [comment]
OK thanks, we'll add a new resolve that handles this.
