### ISSUE TITLE
GL_EXT_ray_query acceleration structure issue

### ISSUE THREAD

**Issue by alelenv** [KhronosGroup/glslang#2152]
For 

`#version 460`
`#extension GL_EXT_ray_query : enable`
`layout(local_size_x = 32, local_size_y = 32) in;`
`layout(set = 0, binding = 0, rgba8) uniform image2D image;`
`layout(set = 0, binding = 1) uniform accelerationStructureEXT as ;`
`void main() { }`

Complains
vk_rayquery_basic:5: error: '' :  syntax error, unexpected IDENTIFIER, expecting LEFT_BRACE or COMMA or SEMICOLON

accelerationStructureEXT should be allowed under this extension

I see tests like https://github.com/KhronosGroup/glslang/blob/master/Test/rayQuery-allOps.comp
  
`#version 460`
`#extension GL_NV_ray_tracing : enable`
`#extension GL_EXT_ray_query : enable`
`layout(binding = 1, set = 0) uniform accelerationStructureNV rtas;`

Is relying on NV variants and hence is probably works

@dgkoch @neslimsah @Tobski

**Comment by dgkoch** [comment]
@neslimsah - do you think we can get a fix in for this ASAP (before Monday)

**Comment by neslimsah** [comment]
Fixed by #2159

**Comment by alelenv** [comment]
LGTM! Clsing

**Comment by dgkoch** [comment]
Thanks!
