### ISSUE TITLE
GL_EXT_ray_query builtins issue

### ISSUE THREAD

**Issue by alelenv** [KhronosGroup/glslang#2153]
Rayquery objects are passed to ray query builtins by reference i.e there should be no load/stores of rayquery objects

This rule is being followed inconsistently
For ex
https://github.com/KhronosGroup/glslang/blob/master/Test/rayQuery-allOps.comp

With
    `while (rayQueryProceedEXT(rayQuery))`

It generates
              65:             Label
              66:          45 Load 47(rayQuery)
              68:    67(bool) RayQueryProceedKHR 66

Note this is similar to 2150 but not same
I haven't verified every other builtin

cc @dgkoch @neslimsah @Tobski

**Comment by dgkoch** [comment]
I believe this was resolved by #2157. @alelenv if so, please close (I don't have permission to).
