### ISSUE TITLE
Is there a way to pack OpenGL style global uniforms into a UBO?

### ISSUE THREAD

**Issue by manaskulkarni786** [KhronosGroup/glslang#2158]
We have some legacy glsl shaders which cannot be modified because of compatibility issues. But we are porting our renderer to Vulkan.
The plan is to do: Legacy GLSL -> SpirV -> Spirv-Cross -> Vulkan GLSL. But the problem is with the global uniforms
Example:
```uniform vec3 cameraPos;```
```uniform mat4 mvp;```

Is there a way that glslang can put these in a uniform block before generating spirv?
Resulting code will look like
```uniform UBO```
```{```
```    uniform vec3 cameraPos;```
```    uniform mat4 mvp;```
```};```

**Comment by johnkslang** [comment]
Yes, we already do this for HLSL, and it's done in a shared base class with GLSL in case GLSL wanted to add it.

I.e., most the work is already complete for this.

See ` TParseContextBase::growGlobalUniformBlock()`.

**Comment by mbechard** [comment]
@manaskulkarni786  FYI we're working on a larger feature set that includes this:
https://github.com/KhronosGroup/glslang/issues/2126

**Comment by manaskulkarni786** [comment]
That sounds great. Any estimate on when this gets shipped with glslangValidator or glslc?

**Comment by mbechard** [comment]
Can't say for sure. The work is actively being done here though:
https://github.com/mbechard/glslang/tree/GL_EXT_vulkan_glsl_relaxed

**Comment by mbechard** [comment]
For anyone that finds this issue, this is now merged into master.
