### ISSUE TITLE
Objects of rayQueryEXT type cannot be assigned to

### ISSUE THREAD

**Issue by alelenv** [KhronosGroup/glslang#2165]
As per TSG discussion here  : 
https://gitlab.khronos.org/vulkan/vulkan/issues/1989

Opaque types like rayQuery cannot be assigned to.

Test seems to be doing just that
https://github.com/KhronosGroup/glslang/blob/master/Test/rayQuery-decls.rgen

cc @dgkoch @Tobski @neslimsah 

I have a fix

**Comment by dgkoch** [comment]
Fixed by #2166. Please close.
