### ISSUE TITLE
VS2015 compile warning spvir.h

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#2167]
Building latest master I'm getting this:

```
 1>vfx_shader_validator_glslang.cpp
 1>d:\dev\source2\main\src\thirdparty\glslang\spirv\spvir.h(238): error C2220: warning treated as 
 error - no 'object' file generated
 1>d:\dev\source2\main\src\thirdparty\glslang\spirv\spvir.h(238): warning C4458: declaration of 
 'unreachable' hides class member
 1>d:\dev\source2\main\src\thirdparty\glslang\spirv\spvir.h(299): note: see declaration of 
 'spv::Block::unreachable'
```

It's an easy fix (rename *unreachable to something else).

**Comment by johnkslang** [comment]
Well, simple enough to fix this one, will do.

However, I'm not too keen on this being a compilation error, as it's a basic language feature intended point is to provide local scopes with their own name space to allow small code snippets to be written without worrying about everything it is nested inside of.  The small bit of nested code was written by @dneto0, while the author of the outer code was @johnkslang, and it works fine in the they way that C++ intended.
