### ISSUE TITLE
Vulkan AMD driver SPIR-V loader/compiler has some very critical bugs loading SPIR-V code

### ISSUE THREAD

**Issue by danilw** [KhronosGroup/glslang#2168]
I report three bugs to AMD already, about Vulkan and SPIRV

1. [AMD driver use 6Gb RAM](https://community.amd.com/thread/248773) to load 250Kb SPIR-V (and then it work)
2. [AMD loop](https://community.amd.com/thread/250358) bug
3. [AMD any not linear logic](https://community.amd.com/thread/250887) bug 

All this bugs tested(by me and other people) and exist on 5+ different AMD hardware.

from bug 3, this code:
```
void main2()
{
 int i=0;
 if(i==0)return;
 else return;
 for (int i=0; i < 1; i++) {
 }
 return;
}
```

## How this bugs ruin real application:
**bug 1** do affect [this my shader](https://www.pouet.net/prod.php?which=84806)
**bug 2** ruin [this my shader](https://www.pouet.net/prod.php?which=85052)
**bug 3** I found just sending 128 bytes push_constants to GPU 
[tests(exe) link](https://danilw.github.io/GLSL-howto/test_AMD_shader_ub/test_AMD_shader_ub.zip), other exe to test with valid Vulkan code [valid_AMD_ub_test.zip](https://danilw.github.io/GLSL-howto/test_AMD_shader_ub/valid_AMD_ub_test.zip) Vulkan code from [SaschaWillems triangle.cpp](https://github.com/SaschaWillems/Vulkan/blob/master/examples/triangle/triangle.cpp)
(test_1 and test_3 dispaly bug on AMD, when test_2 is fine)
this how it look like on AMD
![amd](https://user-images.githubusercontent.com/24825887/78068343-e8727c00-73a0-11ea-9f29-fd96d2a5ae9e.png)

I spend days to debug it, and understand why my valid shaders does not work in Vulkan, if this is "fine" for Vulkan as technology...idk this look very broken for now, when I just touch it by launching few shaders...

**Comment by johnkslang** [comment]
Is there a glslang issue here?  If you think possibly, post the SPIR-V generated here (or the steps needed, e.g. if the code is HLSL or GLSL, and compile options).

(If it's known to be just driver issue rather than a glslang issue, please discuss with the driver providers, not here.)
