### ISSUE TITLE
Obscure compiler error with partially specialized vectors used as array size

### ISSUE THREAD

**Issue by godlikepanos** [KhronosGroup/glslang#2171]
I'm trying to use specialization constants as sizes to some arrays. There is a case though where that fails to compile with the following error:
```
error: <instruction>:35:0:0: Non-OpFunctionParameter (opcode: 81) found inside function but outside basic block
```

A minimal repro case that produces that error is the following compute shader:
```
#version 450 core

layout(constant_id = 0) const int c_0 = 1;
layout(constant_id = 1) const int c_1 = 1;
const ivec2 c = ivec2(c_0, c_1);

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

vec4 s_pixels[c[0]];

void main()
{
}
```

There might be a problem with how partially specialized vectors are handled.

**Comment by johnkslang** [comment]
@alan-baker @s-perron This looks like an error from SPIR-V tools.  I don't know root cause yet, though the OP speculation is probably on track.

Opcode 81 is `OpCompositeExtract`.

**Comment by johnkslang** [comment]
Actually I don't reproduce the message (it's not part of glslang), but we do see the bad instruction.

**Comment by godlikepanos** [comment]
Sorry I completely forgot to mention that the error appears with -Os. So yes it might be an issue in the spirv-tools optimizer.

**Comment by godlikepanos** [comment]
I've tried again to compile the shader in question without -Os and glslang gave no errors. Nevertheless, running the spirv-tools validator on the binary printed the following:
```
error: line 29: ID 18[%18] has not been defined
  %_arr_v4float_18 = OpTypeArray %v4float %18
```

This is a piece of the disassembly. The ID `%18` is defined after the `%19 = OpTypeArray %16 %18` line
```
%19 = OpTypeArray %16 %18          << Line of the error
%20 = OpTypePointer Private %19
%21 = OpVariable %20 Private
%4 = OpFunction %2 None %3
%5 = OpLabel
OpReturn
%18 = OpCompositeExtract %6 %10 0
```

That might be wrong.

**Comment by s-perron** [comment]
Thanks.  I'll take a quick look at it to see if there is anything obvious.

**Comment by s-perron** [comment]
@johnkslang The problem is the placement and opcode of the OpCompositeExtract:

```
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpReturn
         %18 = OpCompositeExtract %int %c 0
               OpFunctionEnd
```

The definition of %18 is in an invalid location: inside a function, but not in a basic block.

The problem problem, from a spir-v perspective, is that the use of %18 is suppose to the size of an array.  This is suppose to be a constant or a spec constant.  The definition of `%c` uses `OpSpecConstantComposite`, and I believe this extract should be an `OpSpecConstantOp` that does the extraction.

**Comment by johnkslang** [comment]
Yes, I saw, it is an incorrect placement for that instruction.  I believe there's an interaction with both having incomplete support for composites formed from specialization constants, the initializing needed code gen, and `main()` having no contents.  Simply adding the line

```
++s_pixels[0];
```

to `main()` will remove the bad instructions placement.  So, I imagine the OP started with a different bug, and in simplifying found this bug.

However, we have not completed full support for composites formed from specialization constants, and I suspect that's the true issue here.

Also see issue #2025.

I think this and #2025 are duplicates of #1916.

**Comment by arcady-lunarg** [comment]
Looks like this has been fixed, and glslang now generates correct code in this case using `OpSpecConstantOp CompositeExtract`.
