### ISSUE TITLE
Duplicate symbol warnings: Build failure on Win64 Pro 1909 (18363.754)

### ISSUE THREAD

**Issue by JacksonFurrier** [KhronosGroup/glslang#2172]
Hello!

I've got the following error message 
[error_build.txt](https://github.com/KhronosGroup/glslang/files/4434521/error_build.txt) , when building on Win64 with LLVM 10.0 (clang-cl, lld-linker). I don't have the same problem with LLVM 9.0 with the same compiler, linker setup. This might be an LLVM bug but at least interesting to look into this. I am using VS env 2019 (14.22.27821) v16.0.

**Comment by johnkslang** [comment]
These are defined in `spirv-tools/source/util/bitutils.h` and `spirv-tools/source/opt/scalar_analysis.h`.

So, perhaps of more interest to SPIRV-Tools.  Though, it does seem unfortunate if `shaderLang.cpp` actually has a dependency on either of those files.

I see now though this could be through hex_float.h, which has in general been a source of build issues and problems, so I also wonder about doing something different with it, at least within glslang core, which has only a small need for it.

**Comment by johnkslang** [comment]
Looking closer, I see the errors are in StandAlone.cpp.obj and spirv-remap.cpp.obj.

Are these linked together?  They should be two independent executables.

**Comment by JacksonFurrier** [comment]
It seems that they are not linked together. I see that StandAlone.cpp.obj and ShaderLang.cpp.obj are having the same symbol, so linking fails. Here is the patch 
[glslang_patch.txt](https://github.com/KhronosGroup/glslang/files/4468506/glslang_patch.txt)
if you want to give it a try with LLVM 10.0

**Comment by johnkslang** [comment]
So, those are two different libraries.  I guess each library gets a copy and then there are duplicates.  It seems like that should be okay, unless there is a way in SPIRV-Tools or in building glslang to avoid it.

**Comment by JacksonFurrier** [comment]
Will try to work it out somehow and report back as soon as I've found something. It is so weird,  that it just goes fine with LLVM 9.0

**Comment by JacksonFurrier** [comment]
"Fixed" the issue. It seems like it is a MS STL issue see: 

- https://developercommunity.visualstudio.com/content/problem/665343/vs2019-stl-with-clang-cl-and-stdc14-generates-dupl.html
- https://bitbucket.org/chromiumembedded/cef/issues/2819/windows-v79-cef_sandboxlib-std
- https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=17292
- https://bugs.llvm.org/show_bug.cgi?id=42027
The only way of making it work was to force c++17 during compilation and worked with lld-linker and msvc linker as well. I think it is good if we wait till MS STL is "fixed", if that is the root of the problem. @StephanTLavavej

**Comment by StephanTLavavej** [comment]
I forget when the fix shipped (I could find out exactly, but the programmer-archaeology would take some time). It should definitely be fixed in VS 2019 16.5, the current production release. Can you verify with that?

I believe that "VS env 2019 (14.22.27821) v16.0" is actually the VS 2019 16.2 toolset (as indicated by 14.22; yeah, the versioning system is a mess).

**Comment by JacksonFurrier** [comment]
Hello, thanks for the fast feedback Stephan!
I will check my current version and report back as soon as I got it. Will try to update and check again.

**Comment by JacksonFurrier** [comment]
Problem is gone with the latest v16.5.4 toolset. @johnkslang shall we keep the "solution" assuming one might use older version of toolset with clang-cl + lld-linker?

**Comment by johnkslang** [comment]
Do you mean force C++17?

It seems the best action is to use the versions that work.  This issue will exist to steer people to that.

**Comment by JacksonFurrier** [comment]
Alright let's just keep it as steering solution. Thank you @johnkslang.
