### ISSUE TITLE
Question : #extension GL_GOOGLE_include_directive : enable

### ISSUE THREAD

**Issue by lch32111** [KhronosGroup/glslang#2174]
Hi. I'm using glslang as a library which can help me cross-compile shaders for my engine.
I'm using glslang preprocessor to include code with `#extension GL_GOOGLE_include_directive : enable`. 

when I see the human-readable spv, it outputs
```
Source ESSL 310
SourceExtension  "GL_GOOGLE_cpp_style_line_directive"
SourceExtension  "GL_GOOGLE_include_directive"
```

So, What I'd like to ask is that,
Can I use this spir-v code in some mobile device which can not hanlde the extensions (google include, line directive extensions..)?
I didn't  test it, but I wanna know about it for free :-)

And further more, maybe I would ask this in spirv-cross github.
I will try to convert the spir-v code into msl. So I wanna know this would be valid when I convert the spir-v code with the extensions into msl. 

Thanks in advance.

**Comment by johnkslang** [comment]
The SPIR-V specification says this about **SourceExtension**:

> This has no semantic impact and can safely be removed from a module.

**Comment by lch32111** [comment]
Ah I didn't know I should look up the SPIR-V specification about this. 

Thanks!
