### ISSUE TITLE
Specialization constant not considered constant for textureLodOffset offset

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#2178]
When compiling the following shader:

```
#version 460 core

layout(constant_id = 1) const int offs = 0;
layout(binding = 0) uniform sampler2D tex;
layout(location = 0) out vec4 color_out;

void main(void)
{
  color_out = textureLodOffset(tex, vec2(0.0, 0.0), 0.0, ivec2(offs, offs));
}
```

I get

```
ERROR: a.frag:10: 'texel offset' : argument must be compile-time constant
ERROR: a.frag:10: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link
```

Even though I believe specialisation constants are considered just as compile-time as a non-specialisation constant. The SPIR-V spec only says that the `ConstOffset` parameters must be `<id>` of constant instructions, which includes spec constants.

If the `layout(constant_id = 1)` is removed, this compiles as expected.

Possibly related to #2025 since that seems to think that spec constants aren't constant in another context.

**Comment by johnkslang** [comment]
This would be different than #2025, which is missing functionality for general composites.

Here, there is additional testing done on the values at compile time, which can't be executed with a specialization constant:

```
            if (offset > resources.maxProgramTexelOffset || offset < resources.minProgramTexelOffset)
                error(loc, "value is out of range:", "texel offset",
                      "[gl_MinProgramTexelOffset, gl_MaxProgramTexelOffset]");
```

It is easy enough to drop this test and call `getType().getQualifier().isConstant()` instead of `getAsConstantUnion()`, if the specification allows for that.

**Comment by johnkslang** [comment]
I don't see the specification requiring a compile-time error for the texel offset value, so am fixing:

1. to allow specialization constants
2. only check the range when the front end knows the constant values

This way, nothing is lost, and the missing functionality is added.

**Comment by FunMiles** [comment]
There is a similar issue with subgroupBroadcast which will not accept a specialization constant as was suggested as a possible solution in https://github.com/KhronosGroup/glslang/issues/1591

**Comment by greg-lunarg** [comment]
If there is a problem with the current glslang, please open an issue with a shader which demonstrates the problem. Thanks!

**Comment by FunMiles** [comment]
> If there is a problem with the current glslang, please open an issue with a shader which demonstrates the problem. Thanks!

Is subgroupBroadcast supposed to accept a specialization constant? If it is, then I'll be happy to create an issue. My google searches have gotten me confused and it seems that for some, a specialization constant is not a full fledged constant?

**Comment by greg-lunarg** [comment]
> Is subgroupBroadcast supposed to accept a specialization constant?

Yes, I believe it should.

**Comment by FunMiles** [comment]
OK. I will create an issue with the problem before the end of the week.
