### ISSUE TITLE
Build Reflection Failed

### ISSUE THREAD

**Issue by mirocosphp** [KhronosGroup/glslang#2180]
It's my first time to use glslang c++ interface. 
I was try to use c++ interface for dumpReflection, however, somethings failed during buildRelfection(), here is my code, and vertex shader is ok since I have checked it using command tool.

Here is my code, any suggestion will be helpful...
My program stop at program.buildReflection(...);

```cpp
int main() {
   
    // vertexShader
    string code = readFile("call0004303_shader2.0.txt");
    cout << code << endl;
    const char* p[1];
    p[0] = code.c_str();
    glslang::TShader *vShader = new glslang::TShader(EShLangVertex);
    vShader->setStrings(p, 1);
    
    
    glslang::TProgram program;
    program.addShader(vShader);

    if(!program.link(EShMsgDefault)){
        puts(vShader->getInfoLog());
        puts(vShader->getInfoDebugLog());
        cout << "link falid..." << endl;
        return -1;
    }
    
    if(!program.buildReflection(EShReflectionAllBlockVariables | EShReflectionIntermediateIO))
    {
        cout << "build Reflection Error"<<endl;
    } else{
        cout << program.getNumLiveUniformBlocks() << endl;
    program.dumpReflection();
    }  
    return 0;
}
```

**Comment by johnkslang** [comment]
After you `setStrings()`, you should also say what you are targeting, with what options:

```
setEnvInput()
setEnvClient()
setEnvTarget()
```

And, definitely then parse the shader with `parse()`.

See the README (section "C++ Class Interface") and StandAlone/StandAlone.cpp for more detail.
