### ISSUE TITLE
interrupted by signal 11: SIGSEGV run-time error(Segmentation fault)

### ISSUE THREAD

**Issue by mirocosphp** [KhronosGroup/glslang#2186]
I'm using glslang c++ interface in my project.
At first I use it in **MacOSX, and it performs perfectly**.
But when I try to use it on my **Ubuntu16.04LTS,** run-time error happened;

I found that the error happens when it comes to **program.link(EshMsgDefault)**, but I dont' know 
how to fix it.

Anyone can help me with it ?

**Comment by mirocosphp** [comment]
I fixed it.
At first, to build my project, I add these in my CMakeList.txt
```
find_package(Threads)
target_link_libraries (${PROJECT_NAME} ${CMAKE_THREAD_LIBS_INIT})
```
Now I  change  cmake_minimum_required(VERSION 2.8) version to cmake_minimum_required(VERSION 3.1) and rebuild it.

Add new lib files to my project and it works!

**Comment by johnkslang** [comment]
Is something you think should be changed in the repository?

**Comment by mirocosphp** [comment]
> Is something you think should be changed in the repository?
I'm not sure. But in my condition,cmake require version should be change to 3.1 when build glslang to get the libs, also need to link pThread in my own project.
