### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/glslang#2190]
Looks like it is already cummulated +120 commits since last release.

I think that it would be good to flush currently committed changes and make new release :)

**Comment by johnkslang** [comment]
It seems somewhat stable right now, so I agree that before making the next big possibly destabilizing change, it will be time to tag and make a release.

**Comment by kloczek** [comment]
In Fedora seems some bugs/issues have been found and they've decided to switch to git snapshots.

**Comment by johnkslang** [comment]
Actually, the tag SDK-candidate-2 was also a stable (maybe ~20 commits ago).

**Comment by johnkslang** [comment]
I'm going to tag the beginning of Rev. 3 SPIR-V 1.5.  There is nothing functionally new about it, just rejiggering the headers, and things seem stable now.
