### ISSUE TITLE
How to detect new nested code block in function while generating glsl code with AST tree?

### ISSUE THREAD

**Issue by lch32111** [KhronosGroup/glslang#2202]
Hi. I'm developing glsl code generator with the glslang `TIntermediate` and `TIntermTraversal`.

I have this code 
```
void main()
{
	vec4 garbage = scene.view;
	vec2 tttt = vec2(0);
	vec3 abc = mul(vec3(3.2), 4.0);
	{
		vec4 garbage = vec4(0.0);
		vec2 tttt = vec2(0);
		vec3 abc = abc;
	}
        ....
}
```

When I found the structure of `TIntermSequence` of this function `main`, 
I cannot distinguish what statements are in the nested block of code.

Here is the Visual Studio Debugging Screenshot:
![image](https://user-images.githubusercontent.com/19434311/80728654-24d0fd80-8b42-11ea-937b-c2b1cf7a8ec8.png)

I can check the index 10 is the statements in the nested block by checking the variables in the debugging mode. But How can I detect the nested block only with the `TIntermTraversal` context?

Thanks!

**Comment by lch32111** [comment]
I just solved this by creating local symbol map of the function and storing a symbol into the map.

If I meet a symbol with the same name which already exists in the map, and has different ID, I would judge that It's nested block variable. So, I would add `_dup` into the new symbol to avoid variable declaration with the same name. Because I cannot distinguish it's in the nested block code. 

So, I close this issue.

**Comment by johnkslang** [comment]
Right, lexical nesting has been transformed to unique symbol IDs, and the lexical scopes no longer exist.  Glad you found a way that works.

During parsing, the depth of nesting level is known, and if this was important, it could be put in next to the unique ID of each symbol.
