### ISSUE TITLE
Bogus implicit type conversion errors in 8.13.3743

### ISSUE THREAD

**Issue by Akaricchi** [KhronosGroup/glslang#2206]
Consider the following shader:

```glsl
#version 330 core

out vec4 fragColor;

void main(void) {
    float foo = 42;
    foo = smoothstep(0, 1, foo);
    fragColor = vec4(foo);
}
```

Since 8.13.3743 this shader fails to compile with the following errors:

```
ERROR: 0:7: 'smoothstep' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:7: 'assign' :  cannot convert from ' global double' to ' temp float'
ERROR: 0:7: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

`double` does not even exist in unextended GLSL 330, and every other implementation that I know of (including older versions of glslang) accepts this code just fine. I believe this is a serious regression.

**Comment by johnkslang** [comment]
Agreed.

From the code, it looks like it came with a3c7a25e1, in PR #1998, which added the double prototypes into earlier versions of GLSL.

We discussed an issue related to this in the PR, and I'd guess it still isn't quite right.

cc @ShchchowAMD.

**Comment by ShchchowAMD** [comment]
Add type check in low versions.
Double will be used only when fp64 extension has been enabled in low versions.

**Comment by johnkslang** [comment]
I accepted the PR, but how did it change the set of prototypes available?  Does it truly resolve this issue?

**Comment by ShchchowAMD** [comment]
I check the case, and find the process would be as following:

1. When enabling fp64 extension, we treat DOUBLE as explicitly enabled before, using findFunction400 and allow multiple function candidates (overload).

2. When we disable fp64 extension, process would still go through findFunction120, and not allow multiple candidates, so I just disable conversions to DOUBLE. BTW, declaration with DOUBLE type would also be wrong in this case.

3. The original purpose of enabling DOUBLE in low versions at global level is that: for some cases, they use functions with DOUBLE args by enabling fp64 extension. Then, GLSL would check types in initialization step.

For this issue, I think now we won't meet this issue again as DOUBLE has been disabled defaultly and other types won't meet this issue in early conversion rules.
BTW, I'll add another process later with PR to let type check depend on extensions formally.
