### ISSUE TITLE
Visual Studio warning: unary minus operator applied to unsigned type, result still unsigned.

### ISSUE THREAD

**Issue by KaoDome** [KhronosGroup/glslang#2209]
Hi, I was building a project that uses glslang and at warning level 2 (`/W2`) VS2019 emits that warning for a comparison and assignment in _Constant.cpp_ at lines 243 and 244 (it's in the MachineIndependent folder).

I'm not used to work with that kind of integer literals, I have no idea whether the warning applies and indicates unintended consequences or it's benign, but just in case I decided to notify you guys.

![C4146](https://user-images.githubusercontent.com/61412446/81293640-ec637f00-906d-11ea-8630-55059f314683.png)

**Comment by dmaluev** [comment]
-1 is often used to set all bits to 1.
-0x8000... looks a bit strange.

**Comment by johnkslang** [comment]
Those expressions evolved a bit to avoid other platform warnings.

See 883607d5f.

GLSL is 2's complement, but C/C++ might not be.  Does dropping the `-` make it go away? I think the compilers are being a bit too picky.

**Comment by KaoDome** [comment]
I see, so those expressions already generated the same warning in the past. After seeing that commit I realized there are similar expressions above at lines 227/228 and VS doesn't complain there.

As far as I could see the only difference over there is that the case is to `int` and the literals aren't as big, it is otherwise analogous to the ones it complains about.

As for dropping the `-`, yep is enough for the compiler not to emit the warning, but is it innocuous?

**Comment by johnkslang** [comment]
Only innocuous if the compiler is treating constants as 32/64-bit 2's complement, which it probably is, despite C++ not requiring it.

**Comment by arcady-lunarg** [comment]
This was fixed by #3132.
