### ISSUE TITLE
TIntermediate memory corruption

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/glslang#221]
Not sure what's going on, but adding `TString entryPoint` to `TIntermediate` causes segfaults when I run glslang from CTS.

Here's [this line](https://github.com/KhronosGroup/glslang/blob/hlsl-frontend/glslang/MachineIndependent/localintermediate.h#L347) in context.

The program crashes on `TPoolAllocator` most of the time, [here](https://github.com/KhronosGroup/glslang/blob/hlsl-frontend/glslang/Include/PoolAlloc.h#L220).

I didn't have time to debug it further, but I think the problem is with how TString's memory is being managed. Once I removed `entryPoint` (and fixed compilation erros), the issue stopped.

**Comment by johnkslang** [comment]
I can fix this, probably later today.  I suspect the string memory lives in the wrong pool (one that got deallocated).

**Comment by johnkslang** [comment]
I had trouble reproducing this, but changed the memory that holds the entry point.  Let me know at your convenience if this helped.

**Comment by yavn** [comment]
Yeah, I expected it to be totally random, I was just lucky to get a consistent case and was able to pinpoint the bug.

This change fixes the issue for me, closing.
