### ISSUE TITLE
under glslang subdirectory not the glslang root github folder I happening an cmake dot dot error and a makefile missing

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/glslang#2212]
Hello,

under glslang subdirectory not the glslang root github folder finaly I happening an cmake dot dot error and a makefile missing :

![CMakeErrorAndMakeFileMissing](https://user-images.githubusercontent.com/30596513/81494863-4b163c00-92ac-11ea-921a-f2cbc34442ba.jpg)

Thank you in advance to repair the problems,

I have sooner finish to edite the cmakelist Under the Vulkan-Hpp GitHub :) 

Regards.

Azaretdodo.

**Comment by arcady-lunarg** [comment]
Please run cmake on the project top-level directory, i.e. create your build directory under glslang/ and not glslang/glslang. That is the correct and supported way to build glslang, and does not cause this issue.
