### ISSUE TITLE
Question: using glslang to optimize/strip down glsl shaders

### ISSUE THREAD

**Issue by gbromov** [KhronosGroup/glslang#2219]
Apologies if that's not the right place for questions, but couldn't find any better.

Is is possible to use the library to optimize glsl shaders containing lots of unnecessary code (#defines, unused functions etc). The "optimize" maybe a bit misleading, all I am looking for is removing unused code, removing defines and generally anything that would reduce the code length without modifying the compilation result. Probably something like de-compiling the generated bytecode back into glsl source?

There's already a library doing that, named glsl-optimizer (based on mesa3d), but it doesn't support newer glsl versions (the maximum supported is #version 150), and it's not maintained anymore.

**Comment by Akaricchi** [comment]
Yes, it's possible to decompile the SPIR-V back into glsl via https://github.com/KhronosGroup/SPIRV-Cross

**Comment by Roy-AMD** [comment]
I think that when you do not set the EShMsgKeepUncall option, the uncall code will be deleted. Glslang has related functions and implementations, but I am not sure whether your usage scenario is to compile glslang yourself or to use glslangValidator. GlslangValidator has this option turned off by default.

**Comment by gbromov** [comment]
Thanks for the replies!

I've played around with "glsl to spir-v to glsl", and it seems pretty close to what I need. There are couple of quirks in using this method though - 1) the glsl code must be pretty high version, 2) after spir-v code is generated another tool should be used (spirv-opt) to remove unused attributes/variants. I have to try adding all these libraries to the existing code to see whether I can make it work there, but I am optimistic.

I am curious about the EShMsgKeepUncall option - what exactly do you suggest to do with it? I should still go through spir-v / spirv-opt / spirv-cross, or am I missing something here?

**Comment by johnkslang** [comment]
`EShMsgKeepUncalled` is present for testing, and turning it into something else might have unintended consequences for one or the other.

**Comment by Roy-AMD** [comment]
> `EShMsgKeepUncalled` is present for testing, and turning it into something else might have unintended consequences for one or the other.

I think it's works stable. maybe the can have a try.

**Comment by Roy-AMD** [comment]
> Thanks for the replies!
> 
> I've played around with "glsl to spir-v to glsl", and it seems pretty close to what I need. There are couple of quirks in using this method though - 1) the glsl code must be pretty high version, 2) after spir-v code is generated another tool should be used (spirv-opt) to remove unused attributes/variants. I have to try adding all these libraries to the existing code to see whether I can make it work there, but I am optimistic.
> 
> I am curious about the EShMsgKeepUncall option - what exactly do you suggest to do with it? I should still go through spir-v / spirv-opt / spirv-cross, or am I missing something here?

Juat make sure when you link shader program, `EShMsgKeepUncalled ` are not been set in `EShMessages`, that will help you delete uncalled function.

**Comment by arcady-lunarg** [comment]
Seems like all the questions here have been answered. Between existing options, the spirv-tools, and spirv-cross, there are various options for things of this sort.
