### ISSUE TITLE
Bug: set = 0 cant be omited 

### ISSUE THREAD

**Issue by ibvfteh** [KhronosGroup/glslang#2247]
Bug: set = 0 cant be omitted for uniform acceleration structure

```
layout(binding = 0) uniform accelerationStructureEXT acc;  // creates error
```
ERROR:
[ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x1ac157ba668, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: UniformConstant id '224' is missing DescriptorSet decoration.
From Vulkan spec, section 14.5.2:
These variables must have DescriptorSet and Binding decorations specified
  %acc = OpVariable %_ptr_UniformConstant_222 UniformConstant

```
layout(binding = 0, set = 0) uniform accelerationStructureEXT acc;  // without error
```

FIX:
Set should be 0 by default for AS like in others

**Comment by johnkslang** [comment]
Yes, I thought we had something in for that, will check it out.

**Comment by johnkslang** [comment]
The following all correctly get a default `set = 0`, so this basic functionality has been in place for a long time.

```
layout(binding = 8) uniform bn { int a; } n;
layout(binding = 9) uniform texture2D t;
layout(binding = 10) uniform sampler2D s;
```

It may be that your issue is specific to ray tracing, or that the same rule does not apply?  @dgkoch?

**Comment by dgkoch** [comment]
I don't know why the rule wouldn't apply to acceleration structures - I'm guessing it was just an oversight.  cc @alelenv

**Comment by alelenv** [comment]
It was an oversight. I will push out a fix shortly
