### ISSUE TITLE
TShader::Includer::IncludeResult is unusable

### ISSUE THREAD

**Issue by TieJu** [KhronosGroup/glslang#225]
Hi,

`TShader::Includer::IncludeResult` is basically unusable, because the member `file_length` is declared as const.

**Comment by antiagainst** [comment]
@AWoloszyn @dekimir

**Comment by AWoloszyn** [comment]
Would you care to clarify what you mean by "basically unusable"?

It is used in glslang currently for a null-include result at
https://github.com/KhronosGroup/glslang/blob/master/glslang/Public/ShaderLang.h#L368

It is also used in shaderc where files are actually being included
https://github.com/google/shaderc/blob/master/libshaderc/src/shaderc.cc#L202

Furthermore it makes sense for this to be const because that provides the explicit guarantee that TPpContext will not modify that value before calling includer.releaseInclude(res), meaning releaseInclude can rely on the fact that the file_length has not changed.

**Comment by TieJu** [comment]
The const ness of this member prevents a number of patterns and usages of the structure.
You can not default construct it and therefore can not  fill it into containers like a vector if or something like that. You also can not use the 'pattern' of default constructing it and then fill it or don't fill it if you can not provide any data.

Also the argument of some sort of guarantees, the pointer to the data is not const and can be modified by the consuming code and so defeats the purpose of the guarantee that the size is constant.

Also why return a pointer of this handler, a simple value would suffice (you could argue about the string in it that would require a copy then). The provider can already provide a context to store its data for bookkeeping and such.

**Comment by dekimir** [comment]
@TieJu the usage patterns you describe are unconvincing: piecemeal filling in is just bad practice (it's better instead to delay `IncludeResult` construction until all individual parts are available), and putting `IncludeResult` into containers like `vector` that shift them around in memory can invalidate pointers to them and wreak havoc with the release process (better instead to have containers of smart pointers to `IncludeResult`).

But the bigger question you ask is a valid one: why isn't `IncludeResult` passed by value?  After analyzing this a bit, @AWoloszyn and I agree that `IncludeResult` needn't be dynamically allocated and may instead be passed by value.  The fundamental reason for passing by pointer is `releaseInclude()` -- it needs to be told exactly which `IncludeResult` glslang is done with, so the `Includer` can release the file data.  If you could devise a different method of identifying a specific `IncludeResult` to `releaseInclude()` -- perhaps via the `user_data` pointer -- you could switch to passing `IncludeResult` by value.

@TieJu would you be interested in crafting such a pull request?

**Comment by TieJu** [comment]
@dekimir The vector stuff was just an example (i know that a resize can invalidate pointers to its data), and it is still a valid use case. Imagine some one has already collected all possible include files in an vector or something like that. In the current state of the code, it makes it just inflexible and awkward to use.
In addition, returning a pointer is considered bad practice too, what if a exception is thrown or something like that.
Also you could get your const ness by changing the return type to a pointer to const, which would ensure that no element gets changed.

As with the pull request, may be on the weekend i have the time for it.

**Comment by TieJu** [comment]
In pull request #242 is my take on the include interface.

**Comment by johnkslang** [comment]
@TieJu things have changed a bit in this space.  Is this still an issue, or after ingesting this conversation, is there a different issue that is still present?  Thanks.

**Comment by TieJu** [comment]
The problem with the const member, that restricts the usage of it is still present.

**Comment by johnkslang** [comment]
I have recently adapted this for use in HLSL (last piece still missing), and think it's current state is usable. So, I can discuss this further directly myself, if need be.  Is there still an issue here?

**Comment by johnkslang** [comment]
There is now an includer included by default with glslang, usable for both HLSL and GLSL.  I wrote this, but did not encounter problems with `const`.  If there is really an issue here, I think it deserves a fresh take, being specific about the problem, relative to the current state of glslang.  Thanks.
