### ISSUE TITLE
setAutoMapBindings() doesn't work

### ISSUE THREAD

**Issue by lance-loong** [KhronosGroup/glslang#2270]
**i have call :**
        shader.setAutoMapLocations( true );
        shader.setAutoMapBindings( true );
**this is my shader:**

```
const char* szVertexShader = R"(#version 310 es
    precision mediump float;
    #define attribute in
    #define varying out

    uniform ab {
        mat4 projectionMatrix;
    } a;

    attribute vec2 position;
    attribute vec2 texCoords;
    attribute vec4 color;

    varying vec2 v_texCoords;
    varying vec4 v_color;

    void main()
    {
        gl_Position = a.projectionMatrix * vec4( position, 0.0, 1.0 );
        v_texCoords = texCoords;
        v_color = color;
    }
)";
```

```
const char* szFragmentShader = R"(#version 310 es
    precision mediump float;
    #define gl_FragColor outFragColor
    layout(location = 0) out vec4 gl_FragColor;
    #define varying in

    varying vec2 v_texCoords;
    varying vec4 v_color;

    uniform sampler2D tex;

    void main()
    {
        vec4 texColor = texture( tex, v_texCoords );
        gl_FragColor = v_color * texColor;
    }
)";
```

**this is output:**
Uniform reflection:
ab.projectionMatrix: offset 0, type 8b5c, size 1, index 0, binding -1, stages 17
tex: offset -1, type 8b5e, size 1, index -1, binding 0, stages 16

Uniform block reflection:
ab: offset -1, type ffffffff, size 64, index 0, binding 0, stages 1, numMembers 1

Buffer variable reflection:

Buffer block reflection:

Pipeline input reflection:
position: offset 0, type 8b50, size 1, index 0, binding -1, stages 1
texCoords: offset 0, type 8b50, size 1, index 0, binding -1, stages 1
color: offset 0, type 8b52, size 1, index 0, binding -1, stages 1

Pipeline output reflection:
outFragColor: offset 0, type 8b52, size 1, index 0, binding -1, stages 16

**The binding is repeated**

**Comment by johnkslang** [comment]
I see two shaders.  Shaders get auto-bindings applied independently. I'm not sure if that's the issue.  Can you be more specific?

If you are writing these shaders, it would be much better to explicitly assign bindings yourself.

**Comment by lance-loong** [comment]
thanks. I have a shader program for vertex and fragment.I set "setAutoMapBindings( true )", but "ab" and "tex" all binding 0.

**Comment by lance-loong** [comment]
I am write cross platform graphics engine.so I need autoMapBindings.
thank your suggest。
you need link two shader.
1.`#version 310 es
    precision mediump float;
    #define attribute in
    #define varying out

    uniform ab {
        mat4 projectionMatrix;
    } a;

    attribute vec2 position;
    attribute vec2 texCoords;
    attribute vec4 color;

    varying vec2 v_texCoords;
    varying vec4 v_color;

    void main()
    {
        gl_Position = a.projectionMatrix * vec4( position, 0.0, 1.0 );
        v_texCoords = texCoords;
        v_color = color;
    }
)`
2.`#version 310 es
    precision mediump float;
    #define gl_FragColor outFragColor
    layout(location = 0) out vec4 gl_FragColor;
    #define varying in

    varying vec2 v_texCoords;
    varying vec4 v_color;

    uniform sampler2D tex;

    void main()
    {
        vec4 texColor = texture( tex, v_texCoords );
        gl_FragColor = v_color * texColor;
    }
)`

**Comment by johnkslang** [comment]
Yes, this is expected behavior, that each compilation unit by default will start with binding 0.

But you can control it more carefully, like giving samplers a different binding than UBOs, using the command-line options like:

```
  --resource-set-binding [stage] name set binding
                                    set descriptor set and binding for
                                    individual resources
  --resource-set-binding [stage] set
                                    set descriptor set for all resources
  --rsb                             synonym for --resource-set-binding
  --shift-image-binding [stage] num
                                    base binding number for images (uav)
  --shift-image-binding [stage] [num set]...
                                    per-descriptor-set shift values
  --sib                             synonym for --shift-image-binding
  --shift-sampler-binding [stage] num
                                    base binding number for samplers
  --shift-sampler-binding [stage] [num set]...
                                    per-descriptor-set shift values
  --ssb                             synonym for --shift-sampler-binding
  --shift-ssbo-binding [stage] num  base binding number for SSBOs
  --shift-ssbo-binding [stage] [num set]...
                                    per-descriptor-set shift values
  --sbb                             synonym for --shift-ssbo-binding
  --shift-texture-binding [stage] num
                                    base binding number for textures
  --shift-texture-binding [stage] [num set]...
                                    per-descriptor-set shift values
  --stb                             synonym for --shift-texture-binding
  --shift-uav-binding [stage] num   base binding number for UAVs
  --shift-uav-binding [stage] [num set]...
                                    per-descriptor-set shift values
  --suavb                           synonym for --shift-uav-binding
  --shift-UBO-binding [stage] num   base binding number for UBOs
  --shift-UBO-binding [stage] [num set]...
                                    per-descriptor-set shift values
  --sub                             synonym for --shift-UBO-binding
  --shift-cbuffer-binding | --scb   synonyms for --shift-UBO-binding
```

**Comment by lance-loong** [comment]
thank you for your reply.I will try the new binding as soon as possible.
