### ISSUE TITLE
Add `-g0` to strip all debug info

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/glslang#2276]
This is a request to add a `-g0` option to strip debug info. This should add `optimizer.RegisterPass(spvtools::CreateStripDebugInfoPass());` to the optimization passes.

The reason for this request is to be able to reduce the binary size of compiled shaders when debug info doesn't really need to be shipped to users.

Note: I took a hack at adding this flag, but I see `Options` being an `int` and has all 32 bits defined. It's passed around in a lot of places but not used at all? I would have changed the type / removed it had it not been exposed in `glslang/Public/ShaderLang.h`. Not sure what's the way forward.

**Comment by johnkslang** [comment]
If you just want an option for controlling logic in `StandAlone.cpp`, just add a `bool` at the top.  E.g., see `targetHlslFunctionality1`.  The `TOptions` is what I think you are referring to as being full, but it is local to that file, for managing command options.

There is a struct `SpvOptions` that looks like how you might want to communicate this request across components within glslang.

**Comment by johnkslang** [comment]
I does sound like a good thing to add, do you still want to try, given the information in the previous comment?

**Comment by ShabbyX** [comment]
Ok, I see, I can use that to set an option in `spvOptions`, so `SpvTools.cpp` can use it. That's what you meant right?

I'll do that some time today.

**Comment by johnkslang** [comment]
Yes, if that works out, thanks.
