### ISSUE TITLE
gl_VertexIndex accepted as valid when compiling to SPIR-V for OpenGL semantics

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#229]
gl_VertexIndex is a Vulkan extension.
But compiling under glslangValidator -G accepts a shader that uses gl_VertexIndex

The following compilation succeeds, but it should fail.

```
$ cat x.vert
#version 310 es
void main() {
 int t = gl_VertexIndex;
}
$ ./StandAlone/glslangValidator -G -H x.vert | grep VertexIndex
                              Name 10  "gl_VertexIndex"
                              Decorate 10(gl_VertexIndex) BuiltIn VertexIndex
10(gl_VertexIndex):      9(ptr) Variable Input
              11:      6(int) Load 10(gl_VertexIndex)
```

Using the API, the compile succeeds when using EShMsgSpvRules, but fails when using EShMsgDefault.

**Comment by johnkslang** [comment]
I turned this off for this case, with 6f29a1bb3b276bf9586e04ea69dc0b629a6c7689.

However, the OpenGL group is still defining these semantics, and they are not yet complete, and could theoretically extend the same way Vulkan did, so I'd prefer to not yet generally engage in going down the path here of what -G semantics are.
