### ISSUE TITLE
Validation error: Invalid capability operand: 61

### ISSUE THREAD

**Issue by Nielsbishere** [KhronosGroup/glslang#2291]
The latest vulkan sdk (1.2.141.2) can't compile any shader with the extension GL_KHR_shader_subgroup_ballot. It does generate a spirv file, but it generates this issue:
`error : input:0:0:2: Invalid capability operand: 61`
This error causes the integration with visual studio to stop building the rest of my project, even though it did output something.

Version:
```
Glslang Version: 8.14.3766
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 14.3766
GLSL Version: 4.60 glslang Khronos. 14.3766
SPIR-V Version 0x00010500, Revision 3
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 8
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```

Command:
`glslangValidator -G1.5 --target-env spirv1.5 -Os -e main -o "test.comp.spv" "test.comp"`

**Comment by johnkslang** [comment]
The error message seems to come from a validator, not from glslang.  Actually, it sounds like glslang can and is compiling shaders with GL_KHR_shader_subgroup_ballot, but maybe the environment they are fed into does not support them.

Capability 61 is GroupNonUniform, which sounds correct (it came into core SPIR-V in 1.3, before that it needs an extension).  So, in a way, the error is verifying that glslang did correctly translate. Make sure you are asking for all the right Vulkan extensions and options to get the extension behavior.  And, if so, that all the validators and layers are up-to-date.

**Comment by Nielsbishere** [comment]
@johnkslang The validation, layers and compilers are all included into VSDK 1.2.141.2 right? I don't manually run the validator stage at that point yet (though I do it later, but it doesn't reach it), it automatically seems to run after the glslangValidator. I will look into my command line tools some more and post them if it is needed, with where the error happens

**Comment by Nielsbishere** [comment]
```bat
@echo off
:loop

rem Go to folder

set dir=%~d1%~p1
set str=%~n1%~x1

cd /d "%dir%"

echo -- Compiling file "%str%" in dir "%dir%"

rem do compile

glslangValidator -G1.5 --target-env spirv1.5 -Os -e main -o "%str%.spv" "%str%"
if %errorlevel% neq 0 exit /b %errorlevel%
echo -- Success compiling

rem do optimize

echo "%1.spv"
spirv-remap -v --do-everything --input "%str%.spv" --output "%CD%"
if %errorlevel% neq 0 exit /b %errorlevel%
echo -- Success remapping

rem do validate

spirv-val --target-env opengl4.5 --target-env spv1.5 "%str%.spv"
if %errorlevel% neq 0 exit /b %errorlevel%
echo -- Success validating

rem next

shift
if not "%~1"=="" goto loop
```
Output:
```
1>-- Compiling file "shadow.comp" in dir "D:\programming\repos\igx_raytracing\res\shaders\"
1>shadow.comp
1>EXEC : error : input:0:0:2: Invalid capability operand: 61
1>-- Success compiling
1>"D:/programming/repos/igx_raytracing/res/shaders/shadow.comp.spv"
1>  reading: shadow.comp.spv
1>  writing: D:\programming\repos\igx_raytracing\res\shaders\shadow.comp.spv
1>Done: 1 file(s) processed
1>-- Success remapping
1>-- Success validating
```
So even though the return code isn't invalid, it still gives that EXEC error. It runs through everything else just fine and it outputs to the spv output. It really is glslangValidator (but like you said, probably the validator part), because if I remove everything else it still throws these errors. This error then goes into my visual studio integration and results in me not being able to run the program.
This is the same issue as https://github.com/KhronosGroup/glslang/issues/2290 but with a different opcode. The opcode is generated by:
```glsl
	uvec4 hitRays = subgroupBallot(traceOcclusion(ray, payload.maxDist));
```

**Comment by johnkslang** [comment]
This sounds like glslang is supporting the functionality, but the version of the validator glslang calls does not support the functionality.  It's still in the SPIR-V validator, if you called it from glslang.  The SPIR-V specification lists capability 61 as supported by SPIR-V 1.5.

**Comment by Nielsbishere** [comment]
Hmm, any way to fix this? Because since this script is ran from visual studio, it sees this error and doesn't compile. Is glslang calling the same version validator or is there an argument I need for it?

**Comment by johnkslang** [comment]
When building your own glslang, and you have the `external` directory populated, it uses the version of the validator that is found in `glslang/update_glslang_sources.py`.  It is also possible to point to something else.

**Comment by Nielsbishere** [comment]
I didn't build it though, I'm running it from command line and using the integrated one from the vulkan sdk.

**Comment by Nielsbishere** [comment]
Same issue as with https://github.com/KhronosGroup/glslang/issues/2290, removing -Os fixed it. Though I'd say that's not a good solution.

**Comment by johnkslang** [comment]
Sounds the same. Let's use #2290 as the open one and this one as a duplicate.
