### ISSUE TITLE
glslang promotes some parameters to functions to highp

### ISSUE THREAD

**Issue by pixelflinger** [KhronosGroup/glslang#2293]
It looks like glslang turns all variables used as function parameters to `highp` using an intermediate variable. spirv-opt can remove some of them, but not all. And it also causes `?:` statements to turn into `if-then-else`, which spirv-opt cannot turn back.

Attached a simple shader showing the problem (please remove the `.txt` extension):

```
./glslangValidator --target-env opengl  test1.frag -o test1.spv
./spirv-cross --es ./test1.spv 
```

The resulting code has intermediate `highp` variables to function parameters:

```
    float x = textureLod(tex, vertex.xy, 0.0).x;
    highp float param = x;
    if (isSomething(param))
```

[test1.frag.txt](https://github.com/KhronosGroup/glslang/files/4828291/test1.frag.txt)

**Comment by johnkslang** [comment]
I am looking.

To be clear though, I know it is more subtle than the description above, as it is easy to write examples where these (promotion to highp and loss of `:?`) do not happen.

**Comment by johnkslang** [comment]
Here is part of the SPIR-V I get for this example:

```
// Module Version 10000
// Generated by (magic number): 80009
...
                              Decorate 10(x) RelaxedPrecision
                              Decorate 13 RelaxedPrecision
...
11(isSomething(f1;):     8(bool) Function None 9
           10(x):      7(ptr) FunctionParameter
              12:             Label
              13:    6(float) Load 10(x)
              15:     8(bool) FOrdLessThan 13 14
                              ReturnValue 15
```

The only function parameter is `10(x)` and it is decorated as `RelaxedPrecision`, and it is loaded into the intermediate `13`, which is also decorated as `RelaxedPrecision`, so I am not reproducing the part "glslang turns all variables used as function parameters to highp using an intermediate variable".

One issue I see is the `0.0` which does not have a precision on its own, and that invokes a precision propagation algorithm.  I see other things that are not `mediump` that arguably could be, so I'll look at those more closely.

**Comment by johnkslang** [comment]
The only problem I can see is the argument (unfortunately named 'param') to the function gets copied to a non-relaxed precision temp before passing it to the relaxed precision parameter.  Mostly, I think that would get collapsed away by drivers, but with complex tool chains it is not.

**Comment by johnkslang** [comment]
More detail:

- parameters that might be written to need extra space to hold that value, and it needs to be the same precision as the formal parameter
- the current bug is that the extra space is not **RelaxedPrecision** even when both calling argument and receiving parameter are **RelaxedPrecision**
- there is a complementary bug where in the cases that glslang directly passes, avoiding the copy, it actually should be adding a copy when the precisions don't match

Side note:

In general, you can make simpler SPIR-V with glslang by using `const` on parameters to indicate a copy is not needed for writing to.  (At least until we have an analysis path that would make it smarter, and as long as we don't go down the road of splitting one stage into multiple unlinked SPIR-V modules.)

**Comment by pixelflinger** [comment]
I have tested this patch on my original shader and it fixes almost all instances of new `highp` except for the case of a non trivial `?:`, where a `highp` is still introduced.

**Comment by johnkslang** [comment]
Thanks.  Yes, `?:` is an orthogonal issue.
