### ISSUE TITLE
uniform m{float f;};void n(){0=mat3(m) crashes glslangValidator with SIGSEGV

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#23]
The input `uniform m{float f;};void n(){0=mat3(m)` when interpereted as a fragment shader causes `glslangValidator` to crash with SIGSEGV in computeNumComponents.

**Comment by johnkslang** [comment]
Thanks, good catch.  Block names were in the symbol table to prevent redefinition of the name, but were missing a check on their use.  Fixed today in 6ab3d582d62baeafbc58ede3487e17f7666d2652.
