### ISSUE TITLE
Determine libSPIRV target 'public' interface

### ISSUE THREAD

**Issue by ben-clayton** [KhronosGroup/glslang#2308]
As [part of the work](https://github.com/KhronosGroup/glslang/issues/2283) to apply Semantic Versioning to the glslang project, we need to determine what we consider as part of the public, stable API and what is internal.

The [Semantic Versioning introduction](https://semver.org/#introduction) states:

> For this system to work, you first need to declare a public API. This may consist of documentation or be enforced by the code itself. Regardless, it is important that this API be clear and precise. Once you identify your public API, you communicate changes to it with specific increments to your version number. 

For the `glslang` target we have been able to classify [`glslang/Public/ShaderLang.h`](https://github.com/KhronosGroup/glslang/blob/master/glslang/Public/ShaderLang.h) as the public API. This is now (#2303) enforced through defaulting to `-fvisibility=hidden` and only making public the methods and types annotated with `GLSLANG_EXPORT`.

`libSPIRV` is another library that [is already found](https://www.archlinux.org/packages/extra/x86_64/glslang/) in linux distribution packages, but AFAICT, there is no clear separation between the public and private interface. As such, any changes to the [`SPIRV`](https://github.com/KhronosGroup/glslang/tree/master/SPIRV) source files will likely require a major semantic version bump, which severely reduces the benefits for semantic versioning.

I see a few options:

1. We spend the time to try classifying the public interface, and build a `SPIRV/Public/SPIRV.h` file, similar to `glslang`.

2. Remove `libSPIRV` from the 'public' interface.
It's hard to know how many people out there are using the `libSPIRV` target - but one potential solution is to make this an entirely 'private' library, and ensure this is statically linked into the `glslangValidator` executable, removing it from the install target. This would remove it from existing linux distributions, breaking anyone who is currently depending on it.

3. We simply ignore semantic versioning for `libSPIRV`. Breaking API changes to `libSPIRV` are not considered for major version bumping. Semantic versioning will only apply for the `glslang` target.

Feedback and opinions welcome.

**Comment by johnkslang** [comment]
Right, the AST -> SPIR-V generator is not based on a publicly supported interface, nor did this project ever say it was or say it should be an SO or advise that Linux distributors distribute it that way.  This project intended a few small static libraries to have their necessary smaller subsets pulled into parent projects, either into a parent's static library or a parent's SO.  As you note, the `ShaderLang.h` was in a `public` folder, while the other headers were not.  (This SO thing is like people saying a motorbike should be a car and then complaining about how stupid the motorbike was to only have 2 wheels, no windows, etc., like whoever made the motorbike really didn't know how to make cars.)  Note that most of glslangValidator's size is from adding side things like SPIRV-Tools and Google's test suite, not the core parsers/translators most other projects need.

So, we don't need to do 1.

**Comment by arcady-lunarg** [comment]
At the moment the proposed public interface to SPIRV is basically all the symbols declared in `GlslangToSpv.h`, `disassemble.h`, and `SpvTools.h`. From `Logger.h`, `spv::SpvBuildLogger::getAllMessages()` is exported. Also everything in `CInterface` is exported. Is there anything else that is needed?

**Comment by arcady-lunarg** [comment]
The symbols tagged with GLSLANG_EXPORT in #3705 are the proposed public interface to the `SPIRV` library (which got merged into glslang proper recently). If anyone has any comments about that, I'm going to leave the PR open for a week or so.
