### ISSUE TITLE
spv.ext.World3x4.rahit appears to be broken or flakey

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/glslang#2342]
This test passes on my Linux workstation, but fails on my MBP with the following error:

4: [ RUN      ] Glsl/CompileToSpirv14Test.FromFile/spv_ext_World3x4_rahit
4: /Users/rharrison/workspace/glslang/gtests/TestFixture.h:148: Failure
4: Expected equality of these values:
4:   expected
4:     Which is: "spv.ext.World3x4.rahit\n// Module Version 10400\n// Generated by (magic number): 8000a\n// Id's are bound by 90\n\n                              Capability RayTracingProvisionalKHR\n                              Extension  \"SPV_KHR_ray_tracing\"\n               1:             ExtInstImport  \"GLSL.std.450\"\n                              MemoryModel Logical GLSL450\n                              EntryPoint AnyHitKHR 4  \"main\" 43 60 78 87 89\n                              Source GLSL 460\n                              SourceExtension  \"GL_EXT_ray_tracing\"\n                              Name 4  \"main\"\n                              Name 8  \"k\"\n                              Name 12  \"ndx\"\n                              Name 14  \"col\"\n                              Name 25  \"row\"\n                              Name 39  \"p\"\n                              Name 43  \"gl_LaunchIDEXT\"\n                              Name 53  \"r\"\n                              Name 60  \"gl_WorldToObject3x4EXT\"\n                              Name 66  \"indexable\"\n                              Name 72  \"c\"\n                              Name 78  \"result\"\n                              Name 87  \"attribs\"\n                              Name 89  \"hitValue\"\n                              Decorate 43(gl_LaunchIDEXT) BuiltIn LaunchIdKHR\n                              Decorate 60(gl_WorldToObject3x4EXT) BuiltIn WorldToObjectKHR\n                              Decorate 78(result) DescriptorSet 0\n                              Decorate 78(result) Binding 0\n                              Decorate 89(hitValue) Location 0\n               2:             TypeVoid\n               3:             TypeFunction 2\n               6:             TypeFloat 32\n               7:             TypePointer Function 6(float)\n               9:    6(float) Constant 1233125376\n              10:             TypeInt 32 1\n              11:             TypePointer Function 10(int)\n              13:     10(int) Constant 4294967295\n              15:     10(int) Constant 0\n              22:     10(int) Constant 3\n              23:             TypeBool\n              32:     10(int) Constant 4\n              35:     10(int) Constant 1\n              37:             TypeVector 10(int) 3\n              38:             TypePointer Function 37(ivec3)\n              40:             TypeInt 32 0\n              41:             TypeVector 40(int) 3\n              42:             TypePointer Input 41(ivec3)\n43(gl_LaunchIDEXT):     42(ptr) Variable Input\n              44:             TypeVector 40(int) 2\n              47:             TypeVector 10(int) 2\n              55:             TypeVector 6(float) 4\n              56:             TypeMatrix 55(fvec4) 3\n              57:             TypeVector 6(float) 3\n              58:             TypeMatrix 57(fvec3) 4\n              59:             TypePointer Input 58\n60(gl_WorldToObject3x4EXT):     59(ptr) Variable Input\n              65:             TypePointer Function 56\n              70:             TypeVector 10(int) 4\n              71:             TypePointer Function 70(ivec4)\n              76:             TypeImage 10(int) 3D nonsampled format:R32i\n              77:             TypePointer UniformConstant 76\n      78(result):     77(ptr) Variable UniformConstant\n              86:             TypePointer HitAttributeKHR 57(fvec3)\n     87(attribs):     86(ptr) Variable HitAttributeKHR\n              88:             TypePointer IncomingRayPayloadKHR 57(fvec3)\n    89(hitValue):     88(ptr) Variable IncomingRayPayloadKHR\n         4(main):           2 Function None 3\n               5:             Label\n            8(k):      7(ptr) Variable Function\n         12(ndx):     11(ptr) Variable Function\n         14(col):     11(ptr) Variable Function\n         25(row):     11(ptr) Variable Function\n           39(p):     38(ptr) Variable Function\n           53(r):      7(ptr) Variable Function\n   66(indexable):     65(ptr) Variable Function\n           72(c):     71(ptr) Variable Function\n                              Store 8(k) 9\n                              Store 12(ndx) 13\n                              Store 14(col) 15\n                              Branch 16\n              16:             Label\n                              LoopMerge 18 19 None\n                              Branch 20\n              20:             Label\n              21:     10(int) Load 14(col)\n              24:    23(bool) SLessThan 21 22\n                              BranchConditional 24 17 18\n              17:               Label\n                                Store 25(row) 15\n                                Branch 26\n              26:               Label\n                                LoopMerge 28 29 None\n                                Branch 30\n              30:               Label\n              31:     10(int)   Load 25(row)\n              33:    23(bool)   SLessThan 31 32\n                                BranchConditional 33 27 28\n              27:                 Label\n              34:     10(int)     Load 12(ndx)\n              36:     10(int)     IAdd 34 35\n                                  Store 12(ndx) 36\n              45:   41(ivec3)     Load 43(gl_LaunchIDEXT)\n              46:   44(ivec2)     VectorShuffle 45 45 0 1\n              48:   47(ivec2)     Bitcast 46\n              49:     10(int)     Load 12(ndx)\n              50:     10(int)     CompositeExtract 48 0\n              51:     10(int)     CompositeExtract 48 1\n              52:   37(ivec3)     CompositeConstruct 50 51 49\n                                  Store 39(p) 52\n              54:    6(float)     Load 8(k)\n              61:          58     Load 60(gl_WorldToObject3x4EXT)\n              62:          56     Transpose 61\n              63:     10(int)     Load 14(col)\n              64:     10(int)     Load 25(row)\n                                  Store 66(indexable) 62\n              67:      7(ptr)     AccessChain 66(indexable) 63 64\n              68:    6(float)     Load 67\n              69:    6(float)     FMul 54 68\n                                  Store 53(r) 69\n              73:    6(float)     Load 53(r)\n              74:     10(int)     ConvertFToS 73\n              75:   70(ivec4)     CompositeConstruct 74 15 15 35\n                                  Store 72(c) 75\n              79:          76     Load 78(result)\n              80:   37(ivec3)     Load 39(p)\n              81:   70(ivec4)     Load 72(c)\n                                  ImageWrite 79 80 81 SignExtend \n                                  Branch 29\n              29:                 Label\n              82:     10(int)     Load 25(row)\n              83:     10(int)     IAdd 82 35\n                                  Store 25(row) 83\n                                  Branch 26\n              28:               Label\n                                Branch 19\n              19:               Label\n              84:     10(int)   Load 14(col)\n              85:     10(int)   IAdd 84 35\n                                Store 14(col) 85\n                                Branch 16\n              18:             Label\n                              Return\n                              FunctionEnd\n"
4:   real
4:     Which is: "spv.ext.World3x4.rahit\n// Module Version 10400\n// Generated by (magic number): 8000a\n// Id's are bound by 90\n\n                              Capability RayTracingProvisionalKHR\n                              Extension  \"SPV_KHR_ray_tracing\"\n               1:             ExtInstImport  \"GLSL.std.450\"\n                              MemoryModel Logical GLSL450\n                              EntryPoint AnyHitKHR 4  \"main\" 43 60 78 87 89\n                              Source GLSL 460\n                              SourceExtension  \"GL_EXT_ray_tracing\"\n                              Name 4  \"main\"\n                              Name 8  \"k\"\n                              Name 12  \"ndx\"\n                              Name 14  \"col\"\n                              Name 25  \"row\"\n                              Name 39  \"p\"\n                              Name 43  \"gl_LaunchIDEXT\"\n                              Name 53  \"r\"\n                              Name 60  \"gl_WorldToObject3x4EXT\"\n                              Name 66  \"indexable\"\n                              Name 72  \"c\"\n                              Name 78  \"result\"\n                              Name 87  \"attribs\"\n                              Name 89  \"hitValue\"\n                              Decorate 43(gl_LaunchIDEXT) BuiltIn LaunchIdKHR\n                              Decorate 60(gl_WorldToObject3x4EXT) BuiltIn WorldToObjectKHR\n                              Decorate 78(result) DescriptorSet 0\n                              Decorate 78(result) Binding 0\n                              Decorate 89(hitValue) Location 0\n               2:             TypeVoid\n               3:             TypeFunction 2\n               6:             TypeFloat 32\n               7:             TypePointer Function 6(float)\n               9:    6(float) Constant 1233125376\n              10:             TypeInt 32 1\n              11:             TypePointer Function 10(int)\n              13:     10(int) Constant 4294967295\n              15:     10(int) Constant 0\n              22:     10(int) Constant 3\n              23:             TypeBool\n              32:     10(int) Constant 4\n              35:     10(int) Constant 1\n              37:             TypeVector 10(int) 3\n              38:             TypePointer Function 37(ivec3)\n              40:             TypeInt 32 0\n              41:             TypeVector 40(int) 3\n              42:             TypePointer Input 41(ivec3)\n43(gl_LaunchIDEXT):     42(ptr) Variable Input\n              44:             TypeVector 40(int) 2\n              47:             TypeVector 10(int) 2\n              55:             TypeVector 6(float) 3\n              56:             TypeMatrix 55(fvec3) 4\n              57:             TypeVector 6(float) 4\n              58:             TypeMatrix 57(fvec4) 3\n              59:             TypePointer Input 56\n60(gl_WorldToObject3x4EXT):     59(ptr) Variable Input\n              65:             TypePointer Function 58\n              70:             TypeVector 10(int) 4\n              71:             TypePointer Function 70(ivec4)\n              76:             TypeImage 10(int) 3D nonsampled format:R32i\n              77:             TypePointer UniformConstant 76\n      78(result):     77(ptr) Variable UniformConstant\n              86:             TypePointer HitAttributeKHR 55(fvec3)\n     87(attribs):     86(ptr) Variable HitAttributeKHR\n              88:             TypePointer IncomingRayPayloadKHR 55(fvec3)\n    89(hitValue):     88(ptr) Variable IncomingRayPayloadKHR\n         4(main):           2 Function None 3\n               5:             Label\n            8(k):      7(ptr) Variable Function\n         12(ndx):     11(ptr) Variable Function\n         14(col):     11(ptr) Variable Function\n         25(row):     11(ptr) Variable Function\n           39(p):     38(ptr) Variable Function\n           53(r):      7(ptr) Variable Function\n   66(indexable):     65(ptr) Variable Function\n           72(c):     71(ptr) Variable Function\n                              Store 8(k) 9\n                              Store 12(ndx) 13\n                              Store 14(col) 15\n                              Branch 16\n              16:             Label\n                              LoopMerge 18 19 None\n                              Branch 20\n              20:             Label\n              21:     10(int) Load 14(col)\n              24:    23(bool) SLessThan 21 22\n                              BranchConditional 24 17 18\n              17:               Label\n                                Store 25(row) 15\n                                Branch 26\n              26:               Label\n                                LoopMerge 28 29 None\n                                Branch 30\n              30:               Label\n              31:     10(int)   Load 25(row)\n              33:    23(bool)   SLessThan 31 32\n                                BranchConditional 33 27 28\n              27:                 Label\n              34:     10(int)     Load 12(ndx)\n              36:     10(int)     IAdd 34 35\n                                  Store 12(ndx) 36\n              45:   41(ivec3)     Load 43(gl_LaunchIDEXT)\n              46:   44(ivec2)     VectorShuffle 45 45 0 1\n              48:   47(ivec2)     Bitcast 46\n              49:     10(int)     Load 12(ndx)\n              50:     10(int)     CompositeExtract 48 0\n              51:     10(int)     CompositeExtract 48 1\n              52:   37(ivec3)     CompositeConstruct 50 51 49\n                                  Store 39(p) 52\n              54:    6(float)     Load 8(k)\n              61:          56     Load 60(gl_WorldToObject3x4EXT)\n              62:          58     Transpose 61\n              63:     10(int)     Load 14(col)\n              64:     10(int)     Load 25(row)\n                                  Store 66(indexable) 62\n              67:      7(ptr)     AccessChain 66(indexable) 63 64\n              68:    6(float)     Load 67\n              69:    6(float)     FMul 54 68\n                                  Store 53(r) 69\n              73:    6(float)     Load 53(r)\n              74:     10(int)     ConvertFToS 73\n              75:   70(ivec4)     CompositeConstruct 74 15 15 35\n                                  Store 72(c) 75\n              79:          76     Load 78(result)\n              80:   37(ivec3)     Load 39(p)\n              81:   70(ivec4)     Load 72(c)\n                                  ImageWrite 79 80 81 SignExtend \n                                  Branch 29\n              29:                 Label\n              82:     10(int)     Load 25(row)\n              83:     10(int)     IAdd 82 35\n                                  Store 25(row) 83\n                                  Branch 26\n              28:               Label\n                                Branch 19\n              19:               Label\n              84:     10(int)   Load 14(col)\n              85:     10(int)   IAdd 84 35\n                                Store 14(col) 85\n                                Branch 16\n              18:             Label\n                              Return\n                              FunctionEnd\n"
4: With diff:
4: @@ -51,11 +51,11 @@
4:                44:             TypeVector 40(int) 2
4:                47:             TypeVector 10(int) 2
4: -              55:             TypeVector 6(float) 4
4: -              56:             TypeMatrix 55(fvec4) 3
4: -              57:             TypeVector 6(float) 3
4: -              58:             TypeMatrix 57(fvec3) 4
4: -              59:             TypePointer Input 58
4: +              55:             TypeVector 6(float) 3
4: +              56:             TypeMatrix 55(fvec3) 4
4: +              57:             TypeVector 6(float) 4
4: +              58:             TypeMatrix 57(fvec4) 3
4: +              59:             TypePointer Input 56
4:  60(gl_WorldToObject3x4EXT):     59(ptr) Variable Input
4: -              65:             TypePointer Function 56
4: +              65:             TypePointer Function 58
4:                70:             TypeVector 10(int) 4
4:                71:             TypePointer Function 70(ivec4)
4: @@ -63,7 +63,7 @@
4:                77:             TypePointer UniformConstant 76
4:        78(result):     77(ptr) Variable UniformConstant
4: -              86:             TypePointer HitAttributeKHR 57(fvec3)
4: +              86:             TypePointer HitAttributeKHR 55(fvec3)
4:       87(attribs):     86(ptr) Variable HitAttributeKHR
4: -              88:             TypePointer IncomingRayPayloadKHR 57(fvec3)
4: +              88:             TypePointer IncomingRayPayloadKHR 55(fvec3)
4:      89(hitValue):     88(ptr) Variable IncomingRayPayloadKHR
4:           4(main):           2 Function None 3
4: @@ -111,6 +111,6 @@
4:                                    Store 39(p) 52
4:                54:    6(float)     Load 8(k)
4: -              61:          58     Load 60(gl_WorldToObject3x4EXT)
4: -              62:          56     Transpose 61
4: +              61:          56     Load 60(gl_WorldToObject3x4EXT)
4: +              62:          58     Transpose 61
4:                63:     10(int)     Load 14(col)
4:                64:     10(int)     Load 25(row)
4: 
4: The following warnings/errors occurred:
4: 
4: [  FAILED  ] Glsl/CompileToSpirv14Test.FromFile/spv_ext_World3x4_rahit, where GetParam() = "spv.ext.World3x4.rahit" (2 ms)
4: [----------] 28 tests from Glsl/CompileToSpirv14Test (31 ms total)

Applying the patch fixes the test for my Mac, but fails in appveyor, https://github.com/KhronosGroup/glslang/pull/2340

**Comment by johnkslang** [comment]
This is showing the two matrix types declared in reverse order, with consumptions also reversed. So, in both versions, the SPIR-V is correct.

We'll need to find why they are sometimes declare in reverse order, not just change test results.

**Comment by johnkslang** [comment]
Fixed by #2343.  gcc and clang evaluate function parameters in opposite order.

Another real issue here is that the Travis CI results are not showing up in the summary of bot runs, yet they are best at finding these platform differences.
