### ISSUE TITLE
Shared object ODR violations between glslang and SPIRV

### ISSUE THREAD

**Issue by ben-clayton** [KhronosGroup/glslang#2346]
## Problem

In #2271 we untangled a cyclic dependency between the `glslang` and `SPIRV` targets. This was solved by creating a new static `MachineIndependent` target which was linked by both `glslang` and `SPIRV` targets.

The `CI-ubuntu-clang-cmake-shared` test failure in https://github.com/KhronosGroup/glslang/pull/2336 has highlighted that we have duplicate public symbols found in both shared objects, which creates an ODR violation (undefined behaviour) - with real-world behaviour of double-delete crashes of global variables.

This problem is partly caused by https://github.com/KhronosGroup/glslang/issues/2308, because `SPIRV` has no public interface, and is exposing the same `MachineIndependent` symbols as `glslang` by default.

The logical solution here is to make the shared `MachineIndependent` symbols hidden. In doing this, I've noticed one further complication - the internal use of thread-local-storage allocators:

The `OGLCompilersDLL`'s [`InitThread()`](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/OGLCompilersDLL/InitializeDll.cpp#L95) function [initializes the TLS allocator to `nullptr`](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/OGLCompilersDLL/InitializeDll.cpp#L113), and is assigned an allocator in various places in `MachineIndependent/ShaderLang.cpp` ([1](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/glslang/MachineIndependent/ShaderLang.cpp#L444), [2](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/glslang/MachineIndependent/ShaderLang.cpp#L458), [3](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/glslang/MachineIndependent/ShaderLang.cpp#L1468), etc).

`SPIRV` uses bits of `MachineIndependent` which require a `TPoolAllocator` to be assigned. Interestingly there are no calls to `SetThreadPoolAllocator()` in `SPIRV`. Nor are there any in `StandAlone`. This suggests to me that `SPIRV` has been depending on an allocator still being bound from earlier calls into `glslang`.

With the symbol visibility fixed, `SPIRV` no longer can use the bound allocator from `glslang` as these targets are now entirely isolated - and we get a nullptr deference crash when `glslang::GlslangToSpv()` attempts to use the allocator to: 

```
#0  0x00007ffff621b8b7 in glslang::TPoolAllocator::push (this=0x0) at ../glslang/MachineIndependent/PoolAlloc.cpp:172
#1  0x00007ffff609cda3 in glslang::GlslangToSpv (intermediate=..., spirv=std::vector of length 0, capacity 0, logger=0x7fffffffcb60, options=0x7fffffffcbe0) at ../SPIRV/GlslangToSpv.cpp:8742
#2  0x00000000004e8b43 in CompileAndLinkShaderUnits (compUnits=std::vector of length 1, capacity 1 = {...}) at ../StandAlone/StandAlone.cpp:1172
#3  0x00000000004e99cb in CompileAndLinkShaderFiles (Worklist=...) at ../StandAlone/StandAlone.cpp:1254
#4  0x00000000004ea580 in singleMain () at ../StandAlone/StandAlone.cpp:1329
#5  0x00000000004eafb5 in main (argc=8, argv=0x7fffffffdb68) at ../StandAlone/StandAlone.cpp:1383
```

## Proposed solution

I propose that we have a default thread-local `TPoolAllocator` to use when no other allocator is set, and have the `SPIRV` target use this.

Note: [`PoolAlloc.cpp`](https://github.com/KhronosGroup/glslang/blob/master/glslang/MachineIndependent/PoolAlloc.cpp) has quite a bit of complexity due to the use of the [`OS_*TLSValue`](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/glslang/OSDependent/osinclude.h#L43-L49) functions. I'm guessing that these functions predate the glslang [use of C++11](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/CMakeLists.txt#L215), which has first-class support for the `thread_local` storage class. Switching to using `thread_local` would greatly simplify this fix.

**Comment by johnkslang** [comment]
I think those functions predate the actual calendar year 2011 by about 9 years.

**Comment by lance-loong** [comment]
@ben-clayton hi, Thread-local storage is not supported for IOS 8.0,How can I modify this?

**Comment by johnkslang** [comment]
I can revert this, if we haven't yet built on assuming it is done.  That would be your local workaround as well, if you want to try and report back.

@ben-clayton is taking some time off right now, so might not respond right away.  Any concerns with reverting this one?

**Comment by lance-loong** [comment]
I am try solve this problem. this is a [solution](https://github.com/lance-loong/glslang/commit/232e083228bb1a76483ca492caa5a4e3d7726dcb).but it's not perfect answer.

**Comment by ben-clayton** [comment]
That's really unfortunate, but I'm happy to revert for now. I can put together a PR that does this.

**Comment by lance-loong** [comment]
OK.

**Comment by ben-clayton** [comment]
@lance-loong - does https://github.com/KhronosGroup/glslang/pull/2361 fix your issue?

**Comment by lance-loong** [comment]
@ben-clayton yes.it's fix.

**Comment by ben-clayton** [comment]
We've reverted the fix for this, so we should keep this issue open.

**Comment by ubitux** [comment]
I've been hit by this issue with a shared build of glslang on macOS:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x5b26)
  * frame #0: 0x000000010110ae64 libSPIRV.dylib`glslang::TPoolAllocator::push() + 20
    frame #1: 0x0000000100fd0a48 libSPIRV.dylib`glslang::GlslangToSpv(glslang::TIntermediate const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&, spv::SpvBuildLogger*, glslang::SpvOptions*) + 88
    frame #2: 0x000000010103e02b libSPIRV.dylib`glslang_program_SPIRV_generate_with_options + 91
    frame #3: 0x000000010103dfc4 libSPIRV.dylib`glslang_program_SPIRV_generate + 36
```

I see that it's been disabled because of iOS 8 but… iOS 8 has been replaced by iOS 9 more than 7 years ago. Any reason to continue trying to support non compliant c++11 toolchains?

**Comment by arcady-lunarg** [comment]
This has been solved by the simple expedient of merging the glslang and SPIRV targets into a single library.
