### ISSUE TITLE
Bug: user-provided #line directives are ignored

### ISSUE THREAD

**Issue by Crisspl** [KhronosGroup/glslang#2355]
Not sure if this is not an issue for glslang.
Anyway... user-provided `#line` directives seems to be ignored while generating another `#line`s during insterting contents of `#include`d sources (that's what I think is happening). Example input:
```
#version 430 core

layout (location = 0) in vec3 Pos;
layout (location = 0) out vec3 outPos;

#line 1 "test.glsl"

#include "g.glsl"

vec3 whatever()
{
	return vec4(1.0); //cannot convert return value to function return type
}

void main()
{
	gl_Position = Pos.xyzz;
}
```
I'm getting error reported in line 12, which is correct assuming there's no `#line 1` at line 6. So expected result is error reported at line 6.
Same issue was posted on shaderc repository since I'm not sure where to report this (we're using glslang via shaderc). https://github.com/google/shaderc/issues/1114

**Comment by johnkslang** [comment]
This shader should get an error on actual line 6, because the extension was not declared.

Does shaderc compile this to the 12th line without complaining about that?

After I add

```
#extension GL_GOOGLE_cpp_style_line_directive : enable
#extension GL_GOOGLE_include_directive : enable
```

I get 

```
ERROR: test.glsl:2: '#include' : Could not process include directive for header name: g.glsl
ERROR: test.glsl:6: 'return' : cannot convert return value to function return type
```

So, that part seems to be working.

**Comment by Crisspl** [comment]
Because `#include` wasnt resolved. When your compiler resolves `#include` it puts `#line` after included contents to denote on which line of original source was `#include`. Like:
```
#version 430 core

layout (location = 0) in vec3 Pos;
layout (location = 0) out vec3 outPos;

#line 1 "test.glsl"

***contents of g.glsl***
#line X "test.glsl"

vec3 whatever()
{
	return vec4(1.0); //cannot convert return value to function return type
}

void main()
{
	gl_Position = Pos.xyzz;
}
```
The problem is that value of `X` seems to ignore the `#line 1 "test.glsl"` before. And that's where the badly reported error lines come from I suppose. Make sure that `#include "g.glsl"` is resolved properly and g.glsl is not empty and see what happens.

**Comment by johnkslang** [comment]
How are you doing this without declaring the extensions?

**Comment by Crisspl** [comment]
Tried with 
```
#extension GL_GOOGLE_cpp_style_line_directive : enable
#extension GL_GOOGLE_include_directive : enable
```
Nothing changes. Can you please try reproduce the bug according to my instructions above?

**Comment by johnkslang** [comment]
`#line` is standard GLSL, from first release.  Giving file names as an operand requires the extension. We aren't seeing the same things. How are you executing glslang?

**Comment by Crisspl** [comment]
Via shaderc as I noted before. Specifically `shaderc::Compiler::PreprocessGlsl()`, then `shaderc::Compiler::CompileGlslToSpv()`. What I noticed just now is when I go with `CompileGlslToSpv` only (without explicitely preprocessing in separate pass), I'm correctly getting error reported at line 6. So I guess the problem is somewhere there... I'll make some more tests, but not today

**Comment by johnkslang** [comment]
It sounds like shaderc is a non-conforming front-end for GLSL, which is really a serious problem, if it is accepting illegal GLSL, which we then exchange, and cannot get the same results due to that.

Is this the case?

@dneto0?

Shaderc will have to do all support for GLSL accepted by shaderc, if it's not using the same semantics as glslang, and it should probably advertise that it's not correctly parsing the Khronos standard.

**Comment by Crisspl** [comment]
Ok, never mind, the problem was on our side. Both glslang and shaderc works fine. Thank you for your time.
