### ISSUE TITLE
Should "#extension xxx : warn" generate OpSourceExtension decoration in SPIRV?

### ISSUE THREAD

**Issue by ShchchowAMD** [KhronosGroup/glslang#2358]
ATT, should behavior WARN, like "#extension xxx : warn", generate OpSourceExtension decoration in SPIRV?

REQUIRE and ENABLE would do so, should WARN do that as well?

SPEC:

> Behave as specified by the extension extension_name, except issue warnings on any detectable use of that extension, unless such use is supported by other enabled or required extensions. If all is specified, then warn on all detectable uses of any extension used. Warn on the #extension if the extension extension_name is not supported.

**Comment by johnkslang** [comment]
Probably correct, only `require` and `enable` should generate `OpSourceExtension`.

**Comment by johnkslang** [comment]
I couldn't edit my comment for some reason, so I deleted it.

I think all three of `enable`, `require`, and `warn` should generate `OpSourceExtension`.  Will fix it.

**Comment by johnkslang** [comment]
This is further complicated by existing incorrect use of the list of requested extensions.  Some PRs incorrectly created a parallel but deficient model (`requestedExtensions`, via an odd `extensionRequested()` ) instead of the correct map of current extension behaviors, `extensionBehavior` via `checkExtensionsRequested()`.  This is hard to spot, because the parallel usage spelling is so close to the original.

Now, I see this comment about the new one:

```
    // JohnK: I think this function should go away.
    // This data structure is just a log to pass on to back ends.
    // Versioning and extensions are handled in Version.cpp, with a rich
    // set of functions for querying stages, versions, extension enable/disabled, etc.
```

So, first step here is to fix that.

**Comment by ShchchowAMD** [comment]
Understand.
It seems that this **requestedExtensions** map would decide which extensions can generate OpSourceExtensions.
It would usually be **enable/require** extensions.

However, SPIR-V specification indicates this decoration could be removed safely, but somewhere we may need it to identify whether a specific extension has been used and check the dependency of its features.

**Comment by johnkslang** [comment]
It's best to have the `OpSourceExtension` there when the source used the extension, and `warn` still means "used the extension".  So, this should be fixed.

The bigger thing is this creeping of language-specific semantics into the AST, when it really belongs in the parsers.  I've been looking at how to fix that today, and it's not a small thing, but really should be done.

This creation of a parallel-yet-lower-quality way of dynamically tracking current extension state should not have happened, but the names were so close to the original names that it was hard to see it was happening.

**Comment by johnkslang** [comment]
I opened #2366 to fix the bigger issue here first.

**Comment by ShchchowAMD** [comment]
Get it, thanks very much.
Besides, seems the new GetVersion function and related settings should be modified only when we change interfaces/options in glslang?
If I don't modify existed functions (like, parameter list) or adding new options, does that means I don't need to change its versions?

**Comment by johnkslang** [comment]
Yes, if I understand correctly.
