### ISSUE TITLE
GLSL frexp translated to SPIR-V FrexpStruct

### ISSUE THREAD

**Issue by mvainola** [KhronosGroup/glslang#2364]
glslangValidator translates `frexp` in GLSL to `FrexpStruct` in SPIR-V. For `modf` the output is `Modf` and not `ModfStruct`. I'm not sure if this is intended but I expected `frexp` to be translated to `Frexp`.

I have attached two GLSL compute shaders and the corresponding SPIR-V disassembly produced using the latest master-tot Linux release binary (a1a497f).

```
$ glslangValidator -V --spirv-dis frexp.comp.glsl
```

[frexp.comp.glsl.txt](https://github.com/KhronosGroup/glslang/files/5021995/frexp.comp.glsl.txt)
[frexp.comp.spvasm.txt](https://github.com/KhronosGroup/glslang/files/5021996/frexp.comp.spvasm.txt)
[modf.comp.glsl.txt](https://github.com/KhronosGroup/glslang/files/5021998/modf.comp.glsl.txt)
[modf.comp.spvasm.txt](https://github.com/KhronosGroup/glslang/files/5021999/modf.comp.spvasm.txt)

Tagging @paulthomson

**Comment by johnkslang** [comment]
Is it incorrect to translate to FrexpStruct instead of Frexp?

**Comment by johnkslang** [comment]
Unless we need to change it, I think it is fine.  If one form gets deprecated, that would be a good time to change.  Otherwise, this provides a broader testing footprint.
