### ISSUE TITLE
[SPIR-V] Incorrect OpSpecConstantComposite constituents

### ISSUE THREAD

**Issue by da3k** [KhronosGroup/glslang#237]
It looks like OpSpecConstantComposite constituents are being directly translated from the GLSL syntax, with no additional transformations that are in many cases required to generate valid SPIR-V. 

In the example below, the code generated for OpSpecConstantComposite has a list of constituents that directly matches the flat list of arguments passed to the GLSL matrix constructor. However, according to the spec, the constituents should instead be columns of the matrix (two vec2() composites).

GLSL source:
```
#version 440

layout(constant_id = 1) const float sc0 = float(1);

layout (set = 0, binding = 0, std430) writeonly buffer Output {
    float result[4];
} sb_out;

const mat2 m0 = mat2(sc0, 2, 3, 4);
const mat2 m1 = mat2(1, sc0, 3, 4);
const mat2 m2 = mat2(1, 2, sc0, 4);
const mat2 m3 = mat2(1, 2, 3, sc0);

void main (void)
{
    float sum_m0 = float(0);
    float sum_m1 = float(0);
    float sum_m2 = float(0);
    float sum_m3 = float(0);

    for (int i = 0; i < 2; ++i)
    for (int j = 0; j < 2; ++j)
    {
        sum_m0 += float(m0[i][j]);
        sum_m1 += float(m1[i][j]);
        sum_m2 += float(m2[i][j]);
        sum_m3 += float(m3[i][j]);
    }

    sb_out.result[0] = sum_m0;
    sb_out.result[1] = sum_m1;
    sb_out.result[2] = sum_m2;
    sb_out.result[3] = sum_m3;
}

```
SPIR-V generated (first OpSpecConstantComposite):
```
...
%35 = OpTypeMatrix %34 2
%36 = OpSpecConstant %6 1
%37 = OpConstant %6 2
%38 = OpConstant %6 3
%39 = OpConstant %6 4
%40 = OpSpecConstantComposite %35 %36 %37 %38 %39
...

```
GLSL constructors like "vec4(sc0)" are also being translated directly, where OpSpecConstantComposite is incorrectly generated with only one sc0 in the constituents list instead of four.

**Comment by Qining** [comment]
Thanks @da3k , I will go ahead and take care of this.

**Comment by Qining** [comment]
Hi @da3k @johnkslang, PR #241 should fix this issue, pleas take a look. Thanks.

**Comment by johnkslang** [comment]
I verified this is indeed working correctly now.
