### ISSUE TITLE
HLSL mesh/task shaders

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/glslang#2372]
Hello!
Does glslang support HLSL mesh/task shaders? If it does not, are there plans to enable the support?

I am trying to compile the shader below:

```hlsl
struct VertexOut
{
    float4 Position : SV_Position;
    float4 Color    : COLOR0;
};

[NumThreads(1,1,1)]
[OutputTopology("triangle")]
void main(uint gtid : SV_GroupThreadID,
          uint gid  : SV_GroupID,
          out indices  uint3     tris[1],
          out vertices VertexOut verts[3])
{
    SetMeshOutputCounts(3, 1);

    tris[0] = uint3(0, 1, 2);

    verts[0].Position = float4(-1, -1, 0, 1);
    verts[1].Position = float4( 0,  1, 0, 1);
    verts[2].Position = float4( 1, -1, 0, 1);

    verts[0].Color    = float4(1, 0, 0, 1);
    verts[1].Color    = float4(0, 1, 0, 1);
    verts[2].Color    = float4(0, 0, 1, 1);
}
```

with the following command line:

```
glslangValidator.exe -V -D -e main -S mesh mesh_test.mesh.hlsl
```

The compilation fails with the following errors:

```
WARNING: mesh_test.mesh.hlsl:7: 'NumThreads' : unrecognized attribute
WARNING: mesh_test.mesh.hlsl:8: 'OutputTopology' : unrecognized attribute
ERROR: mesh_test.mesh.hlsl:11: ')' : Expected
ERROR: mesh_test.mesh.hlsl:11: 'function parameter list' : Expected
mesh_test.mesh.hlsl(11): error at column 21, HLSL parsing failed.
ERROR: 3 compilation errors.  No code generated.
```

**Comment by johnkslang** [comment]
@dgkoch?

**Comment by dgkoch** [comment]
> Does glslang support HLSL mesh/task shaders? 

Not that I'm aware of. 
glslang support GLSL mesh/task shaders via the NV extension and DXC supports HLSL mesh/task shaders via the NV extension. 

> If it does not, are there plans to enable the support?

AFAIK - HLSL support in glslang is mostly legacy at this point and isn't being extended for SM 6.x features.  Maybe @johnkslang has more to say about that.

**Comment by TheMostDiligent** [comment]
> AFAIK - HLSL support in glslang is mostly legacy at this point and isn't being extended for SM 6.x features. Maybe @johnkslang has more to say about that.

Does this mean there are no plans to extend HLSL support in glslang in the future? That would be really unfortunate.

**Comment by dmaluev** [comment]
> HLSL support in glslang is mostly legacy at this point and isn't being extended for SM 6.x features.
Seriously? glslang is becoming yet another buggy Cg Toolkit.

**Comment by dmaluev** [comment]
>HLSL support in glslang is mostly legacy at this point and isn't being extended for SM 6.x features.

Seriously? glslang is becoming yet another buggy Cg Toolkit.

**Comment by greg-lunarg** [comment]
SM 6.x support will continue through dxc: https://github.com/microsoft/DirectXShaderCompiler

Is there a reason that this would not be an acceptable path moving forward? Would be very interested to hear detailed concerns if so.

**Comment by TheMostDiligent** [comment]
@greg-lunarg In our project (https://github.com/DiligentGraphics/DiligentEngine) we use glslang as universal shader compiler, which gives a number of benefits:

* Common backend for HLSL and GLSL produces consistent SPIRV which is easier to maintain (we've had few issues related to DXC producing different SPIRV)
* HLSL can be used as universal shading language for all platforms
* glslang is compact, so we can bundle it with the library on all platforms (including mobile platforms) to allow run-time shader compilation

We now started adding more next-gen features (mesh shaders, ray tracing, etc.), so for us ideal option would be if glslang supported all these features.
DXC is much larger and bundling it with the library is almost not an option. Besides, it is only available on Linux and Mac besides Windows, which may not be the problem for mesh shaders, however may cause problems in the future.

So, yes, DXC is an acceptable path but not so ideal.

**Comment by dmaluev** [comment]
DXC is an acceptable path for SM 6.0. But can you guarantee that previous versions of HLSL are well supported by glslang? For example, if I'll encounter some bug with shader compilation for SM 5.0 and I'll post an issue here on github, is it possible that I'll get a reply like "just use DXC"?

**Comment by greg-lunarg** [comment]
Thank you for your responses.

Some SM 6 functionality has been added to glslang (eg Wave). I think adding Mesh shading to HLSL support would probably be a similar effort and would be accepted.

I think that fixes to SM 5 functionality would continue to be accepted. Since glslang is "the" GLSL shader compiler for Vulkan, it is not in danger of becoming a backwater.

**Comment by TheMostDiligent** [comment]
@greg-lunarg Thanks! That sounds reassuring. What about ray tracing?

**Comment by dgkoch** [comment]
HLSL support for ray tracing is also expected to be via DXC.

**Comment by TheMostDiligent** [comment]
@dgkoch round 2 then: does this mean that ray tracing support will not be enabled in glslang?

**Comment by dgkoch** [comment]
> @dgkoch round 2 then: does this mean that ray tracing support will not be enabled in glslang?

GLSL ray tracing support will be (and is) enabled in glslang. There is no current plan to add HLSL ray tracing support, but I'm sure patches would be accepted if someone wanted to take it on.

**Comment by TheMostDiligent** [comment]
Ok, thanks for the answers!
