### ISSUE TITLE
Disallow opaque types as function return values?

### ISSUE THREAD

**Issue by Tobski** [KhronosGroup/glslang#2382]
The following glsl code compiles to SPIR-V without complaint:

```glsl
#version 460
#extension GL_EXT_samplerless_texture_functions : enable
layout (binding = 0, set = 0) uniform texture2D myTexture;
layout (location = 0) out vec4 fragColor;
texture2D foo(texture2D bar)
{
	return bar;
}
texture2D fool(texture2D bar)
{
	return bar;
}
void main()
{
	fragColor = texelFetch(fool(foo(myTexture)), ivec2(gl_FragCoord), 0);
}
```

However the generated SPIR-V involves loading from `myTexture` in `foo`, then loading from that returned object in `fool` which means you're loading from an already loaded object (i.e. the SPIR-V is both invalid and nonsensical). This load has to be part of the function body AFAICT because of the way *OpReturnValue* works. For a single load everything sort of maybe works, but once you throw two functions together it just breaks down.

As far as I can tell, the GLSL spec doesn't actually allow this usage - it doesn't allow opaque types as function returns, for instance. So potentially opaque types on user-defined functions should be an error? The only wrinkle here is that there are constructors that return these types (e.g. sampler2D(texture2D, sampler)), which need to continue to work, which may have an effect on the code used to fix this.

**Comment by johnkslang** [comment]
> So potentially opaque types on user-defined functions should be an error?

Sounds right.

> The only wrinkle here is that there are constructors

Constructors will go down a different semantic checking path, so there shouldn't be an issue here.  (Paths split soon after the common syntax is recognized.)

It just seems like there is a missing semantic check on the return-value type functions.

**Comment by arcady-lunarg** [comment]
As of commit 16526fd9d2fdff115451d2dbaa8436ad06707fa5, samplers and textures can only be used as return values if GL_ARB_bindless_texture is enabled, and that extension cannot be enabled for generating SPIR-V code. Can this be closed now?
