### ISSUE TITLE
Trivial GLSL generates invalid SPIR-V: missing capabilities

### ISSUE THREAD

**Issue by polarina** [KhronosGroup/glslang#2399]
The following GLSL vertex shader will compile to invalid SPIR-V:
```glsl
#version 450

void main() {
	gl_Position = vec4(0.0f);
}
```

Compile with `glslangValidator glsl.vert --target-env vulkan1.0 -o glsl.spv`:

```spirv
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 20
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %_
               OpSource GLSL 450
               OpName %main "main"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
    %float_0 = OpConstant %float 0
         %17 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %main = OpFunction %void None %3
          %5 = OpLabel
         %19 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %19 %17
               OpReturn
               OpFunctionEnd
```

Observe the member decorations for the `ClipDistance` and the `CullDistance` builtins. The SPIR-V specification require the `ClipDistance` and the `CullDistance` capabilities to be enabled for these, respectively. These capabilities are missing from the generated SPIR-V shader.

Ideally the compiler should omit these built-ins from `gl_PerVertex` when not needed since these capabilities requires optional functionality to be enabled in Vulkan, namely `shaderClipDistance` and `shaderCullDistance`.

**Comment by johnkslang** [comment]
It is their use, not their declaration, that requires the capabilities.  Confusing, I know, and complicated.  But it is okay and correct.  The interface alone does not require the underlying platform to have the ability.

**Comment by polarina** [comment]
@johnkslang thank you for the reply. I wouldn't mind pursuing a pull request to SPIR-V and the Vulkan spec to better clarify this. Do you have any suggestions for me on how to best approach this? Thanks!

**Comment by johnkslang** [comment]
This has already been discussed, and I'm pretty sure the Vulkan spec explains already that this is about actual use, not only declaration.  You can read about it by searching for the built-in name and capability name in the Vulkan specification.
