### ISSUE TITLE
"#line 0%\n" crashes glslangValidator with SIGFPE

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#24]
The input `"#line 0%\n"` when interpereted as a fragment shader causes glslangValidator to crash with SIGFPE in Pp.cpp (`op_mod`).

**Comment by xorgy** [comment]
As far as I'm aware `#line` doesn't take expressions of any sort, only a digit sequence.

**Comment by xorgy** [comment]
There are two problems here:
 - Currently glslang's `#line` takes expressions and not just integer literals.
 - `op_mod` and `op_div` both accept zero operands in positions they shouldn't.

**Comment by johnkslang** [comment]
Regarding this one:

> - Currently glslang's `#line` takes expressions and not just integer literals, I'm not certain it should allow macro expansion either.

The specifications call these out:

> #line must have, after macro substitution...
> ...line and source-string-number are constant integral expressions

**Comment by xorgy** [comment]
TIL. :thought_balloon:

**Comment by johnkslang** [comment]
This is now fixed, in d2762564dce131339df576721c0156b35e78ea58.

Thanks for reporting.
