### ISSUE TITLE
TPoolAllocator::allocate throwing Segfault on Linux

### ISSUE THREAD

**Issue by Destranix** [KhronosGroup/glslang#2412]
First: I haven't yet done much Investigation, so it might be possible, that the issue is in my code and not in yours. But at first view it seems possible, that lies in your application.

See:
https://github.com/Destranix/glslang_Java

On Windows all tests work without problems. On Linux, a segfault occurs, when calling TShader.setStrings. The segfault occurs in the TPoolAllocator::allocate, while calling NewPoolTString.

The error did not occur in a previous commit.

Thanks in advance.

**Comment by johnkslang** [comment]
> The error did not occur in a previous commit.

Do you have the specific commits you know where it worked and where it did not?

**Comment by Destranix** [comment]
Worked with(or a commit a little bit later or earlier.):
1ef2e250fc36d862573cc5e92f04b1d0e2d89867
Does not work with:
f05c076e26b04cbcc9bf2df815bbdc9c620d89ad

**Comment by Destranix** [comment]
I just noticed, that the error also occurs on windows. (Windows 7) I did nit notice that before, because I unintendenly tested agains an old version of my project.

It says the error occurs at PoolAlloc.cpp:245.(Based on a selfwritten method, so not necessarily reliable)
It's an "SE Exception: Access Violation" on Window.

**Comment by Destranix** [comment]
I've verified the location of the error using the following simple test application:
```
#include <stdio.h>
#include <glslang/Public/ShaderLang.h>
#include <glslang/Include/Common.h>

using namespace glslang;

int main(void){
	if(!InitializeProcess()){
		fprintf(stderr, "Error Init!");
		return -1;
	}
	NewPoolTString("abc_test");
	FinalizeProcess();
	return 0;
}
```

VisualStudio compiler says, "this" is "nullptr"

**Comment by johnkslang** [comment]
The last example code is not a real use of the glslang API; maybe it is a helpful reduction/isolation, but seems to skip some normal steps.  So, I want to verify about the original use.  What is the sequence of API calls that leads to the issue?  It is quite possible that not calling the entry points in the right order can lead to problems.  Much of that is covered in the README, and looking inside ShaderLang.cpp can also help.

**Comment by Destranix** [comment]
> The last example code is not a real use of the glslang API

I know. I'm actually using your TString-Allocationfunction for allocation of normal strings for my own application. Isn't that allowed? shouldn't allocation of TStrings be valid at every point after initializsation, since TStrings are used as parameters for some functions?

> What is the sequence of API calls that leads to the issue?

Basically the ones seen in the example. In my application ther's a call to Glsl- and Essl-VersionStringfunction and a creation of a TShader instance inbetween.

>  It is quite possible that not calling the entry points in the right order can lead to problems.

Which functions do I have to call to be able to allocate TStrings using your function?

**Comment by johnkslang** [comment]
The TStrings come from the currently active memory pool, which is is a function of which thread as well as where you are in time on the timeline `pre-init -> init -> building shaders -> parsing -> lowering -> finalizing -> post finalize`.  I don't think you want to try to time things just right.

Now, you could likely leverage all existing code for you personal use by allocating your own pool, and using that as a template argument to existing code, which only defaults to the current pool thing described above when you don't supply your own.

**Comment by Destranix** [comment]
Ok, I understand.

Thanks for your help.
