### ISSUE TITLE
fatal error: 'spirv-tools/libspirv.h' file not found

### ISSUE THREAD

**Issue by timvpGoogle** [KhronosGroup/glslang#2413]
Chromium is failing to build with the latest glslang:

```
FAILED: obj/third_party/glslang/src/glslang_validator/StandAlone.o 
../../build/toolchain/clang_code_coverage_wrapper.py --target-os=linux /home/timvp/code/depot_tools/.cipd_bin/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/glslang/src/glslang_validator/StandAlone.o.d -DENABLE_OPT=1 -DDCHECK_ALWAYS_ON=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-5627-gf086e85e-2\" -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_DEBUG=0 -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=5f64b417e1018dcf8fcc81dc2714e0f264b9b911 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_HLSL=1 -Igen/third_party/glslang/src/include -I../.. -Igen -I../../third_party/glslang/src -Woverflow -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -enable-dse-memoryssa=false -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fprofile-instr-generate -fcoverage-mapping -mllvm -limited-coverage-experimental=true -fno-use-cxa-atexit -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -Wno-conversion -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../third_party/glslang/src/StandAlone/StandAlone.cpp -o obj/third_party/glslang/src/glslang_validator/StandAlone.o
In file included from ../../third_party/glslang/src/StandAlone/StandAlone.cpp:48:
In file included from ../../third_party/glslang/src/StandAlone/../SPIRV/GlslangToSpv.h:42:
../../third_party/glslang/src/StandAlone/../SPIRV/SpvTools.h:47:10: fatal error: 'spirv-tools/libspirv.h' file not found
#include "spirv-tools/libspirv.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```

The file appears to be present at `External/spirv-tools/include/spirv-tools/libspirv.h`, but it just can't be found for whatever reason.

Any ideas?

**Comment by johnkslang** [comment]
This was touched on by the most recent commit, which worked in many environments, but I guess not this one.

I'll revert the most recent commit, and the author can try again.

**Comment by timvpGoogle** [comment]
Sounds good.   For the full context, here is the failing roll:

https://chromium-review.googlesource.com/c/chromium/src/+/2450120

**Comment by johnkslang** [comment]
If the revert worked, can you close (or ask me to)?  Thanks.

**Comment by timvpGoogle** [comment]
I just restarted the Chromium autoroller, so I can't say for sure that it worked or not until that's finished:
https://chromium-review.googlesource.com/c/chromium/src/+/2454535

I think we can go ahead and close this bug for now and (re)open a bug if necessary.

Thanks for the quick turnaround on this.

**Comment by timvpGoogle** [comment]
The build completed successfully and the roll merged.   Thanks again.

**Comment by phniix** [comment]
Totally unbeknownst to me that this would come through as causing an error. The CMakeLists.txt files were updated accordingly. The build farm tests all passed. 

@timvpGoogle Looks like you guys used a different build system. That system is not hooked up to glslang's CI, and build instructions don't point to covering BUILD.gn.. Did you test the latest change on a separate branch before pulling it into production ? Does your team have expertise to cross-reference the changes made in the CMakeLists file, and port them to BUILD.gn ?

The snippet you provided I was only able to extract a small set of include directories:
```
-Igen/third_party/glslang/src/include 
 -I../.. 
 -Igen 
 -I../../third_party/glslang/src 
```
Not seeing the rest of it, makes it hard to assess what should be added.. but a suspicion is that the include path doesn't point to what is needed for that target. Did you look more into it ?

What will be helpful is more output, for sure. That way we can see what's going on. Of course, I don't have your build system, or know what it is, so not sure how much I can be of great help in testing out any changes. 

Can you post more of the output that you shared above ? I tried looking at the logs from what you shared, but it appears to be a rabbit warren of data and information, and I couldn't get the basic information that would be useful for me. 

Better yet, if you/your teams can point out where to make the changes to the BUILD.gn files, I'll gladly apply them to get this change reinstated. 

@johnkslang Looks like there are heaps of build systems in this library that need to be accounted for. That makes it awfully challenging for contributions to be added that affect the build scripts, and results in such issues as we see here. To probability of things going awry is high. Given there is a CI, it would be terrific if we get all these build systems accounted for, so this type of stuff can get caught. Is this the plan to do so ? Do all these other users that contribute to the build scripts outside of CMake, have an easy way for contributors to test branches/PR on their build systems ? 

I will add, that I don't see it on the Build steps, that we really need to account for all these other different build systems. It's rather odd, but I can appreciate how its all put together. Should some of these other build systems take some ownership of reflecting their nuanced configurations from the canonical CMake configuration ?

It really does come across that we should only really concern ourselves with CMake, it being the real deal, and have other's that maintain all those other scripts as a reference to the CMake. 

I'll happily submit a 3rd PR, but it seems to be rather ridiculous that the only thing holding these very useful additions has been non-familiarity of the build systems and build pipelines associated with glslang. I think we can all agree that this is a time sink nobody really wants.

**Comment by timvpGoogle** [comment]
Hi,

Sorry for the late reply.

The glslang updates are tested on the Commit Queue (CQ) before they land in the Chromium tree.   Since that failed due to the build errors, these changes never made it into production.

Admittedly, I don't know what's involved with updating glslang's `CMakeLists.txt` and `BUILD.gn` to make sure they stay in sync, beyond whoever is making the changes doing it themselves.

I didn't look into the changes any further than getting the bug opened.   I'm not really an expert in this area; the reason I discovered the bug was simply that it was my turn to monitor the autoroller bots and try to keep them green/healthy.

Looking at the logs, I think you found everything:

```
FAILED: obj/third_party/glslang/src/glslang_validator/StandAlone.o 
../../build/toolchain/clang_code_coverage_wrapper.py --target-os=linux --files-to-instrument=../../.code-coverage/files_to_instrument.txt /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/glslang/src/glslang_validator/StandAlone.o.d -DENABLE_OPT=1 -DDCHECK_ALWAYS_ON=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-5627-gf086e85e-2\" -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -D_LIBCPP_DEBUG=0 -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=5f64b417e1018dcf8fcc81dc2714e0f264b9b911 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DENABLE_HLSL=1 -Igen/third_party/glslang/src/include -I../.. -Igen -I../../third_party/glslang/src -Woverflow -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -enable-dse-memoryssa=false -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fprofile-instr-generate -fcoverage-mapping -mllvm -limited-coverage-experimental=true -fno-use-cxa-atexit -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -Wno-conversion -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../third_party/glslang/src/StandAlone/StandAlone.cpp -o obj/third_party/glslang/src/glslang_validator/StandAlone.o
In file included from ../../third_party/glslang/src/StandAlone/StandAlone.cpp:48:
In file included from ../../third_party/glslang/src/StandAlone/../SPIRV/GlslangToSpv.h:42:
../../third_party/glslang/src/StandAlone/../SPIRV/SpvTools.h:47:10: fatal error: 'spirv-tools/libspirv.h' file not found
#include "spirv-tools/libspirv.h"
```

I definitely share your pain that these types of build issues within Chromium's GN build system can be painful to deal with; I'm not actually part of the Chromium team either, I also just work on a component Chromium imports and uses.   Unfortunately, I can't offer much more help, since our process within the team would be to recreate the build issue locally to recreate and fix it.   That's certainly possible for you to do, but a bit painful since Chromium is large.

If you're interested in going that route, the instructions are here:
https://chromium.googlesource.com/chromium/src/+/master/docs/linux/build_instructions.md

You would then need to just cherry-pick your changes into `third_party/glslang/` to see recreate what the CQ bots were seeing.

It's entirely possible that @johnkslang has a better approach though.

**Comment by johnkslang** [comment]
I also don't simultaneously fully understand all the build environments.

There is a simple question here though: given how many build environments are not having a problem finding a header, I wonder why another is.

I'll reopen this for further discussion.

**Comment by ben-clayton** [comment]
I had previously looked into adding presubmits for the `.gn` builds, but I struggled to find good examples for setting up a standalone build environment.
If someone from chrome can point me in the right direction on how to set up a minimal GN build for glslang, I can knock together presubmit checks in an hour or so.

**Comment by null77** [comment]
@ben-clayton you can ping me offline, happy to help. ideally we could set up an standalone ANGLE integration to test.

**Comment by ShabbyX** [comment]
It should be possible to add a Travis build that runs a script that clones depot_tools+ANGLE, modifies DEPS to point to the github commit being tested, and runs an ANGLE build.

**Comment by ben-clayton** [comment]
> It should be possible to add a Travis build that runs a script that clones depot_tools+ANGLE, modifies DEPS to point to the github commit being tested, and runs an ANGLE build.

@null77 and I discussed this approach offline. I'm not particularly keen on depending on ANGLE as we'd then end up with a circular build dependency (glslang pulls ANGLE to build, ANGLE pulls glslang to build). In this situation, there's no clean way to make a significant breaking change, as there's no possible way to atomically update glslang and ANGLE in one commit - you'd end up with one of the projects being temporarily broken. I also feel that having glslang depend on ANGLE as part of a presubmit might end up putting too much burden on external developers (i.e. do we really expect someone to have to perform a full ANGLE build just to reproduce and fix a presubmit failure?)

@null77 pointed me at the standalone .gn build environment in the VVL. I'll spend a few hours tomorrow seeing if I can replicate something similar to that. With this, presubmit times should be significantly shorter, and we can make an effort to document the process of reproducing a minimal .gn build.

**Comment by ben-clayton** [comment]
Created #2421 for GN presubmits.

**Comment by phniix** [comment]
Hi,

It's all good. I'm just getting to your reply now, so it seems right on time :) 

I find that async messaging has a way of eliminating, to much of a degree, the elements of time, so what constitutes as late is harder to grasp. :) 

I appreciate your awesome response!


> The glslang updates are tested on the Commit Queue (CQ) 

Brilliant, so this is the staging/testing area. Thanks for describing your role and how you discovered this bug. All that information is really crucial to understanding and constructing context.

You bring up a good point about the process your team would be taking. It would be a great service for the community, to perhaps discuss with your team, if this is something that could become more common. This would likely be able to leverage the wider expertise and infrastructure already in place for Chromium, and more than likely lead to not only a logged issue like this one, but an accompanying fix. :D 

Total win.

You are spot on about this step being plausible for me, and in fact, anyone to do. In my case, it definitely places a barrier, which limits my capacity to contribute. Not sure what others think.

I appreciate the pointer to the build instructions, and the strategy to cherry-pick the change. Alas, it is unlikely I will be able to do this anytime soon.

On what you wrote:

> updating glslang's CMakeLists.txt and BUILD.gn to make sure they stay in sync, beyond whoever is making the changes doing it themselves.

..was my hypothesis, and really up's the ante on what contributors need to additionally account for. 

> Looking at the logs, I think you found everything:

Cool! Thanks for the log dump.

I believe what is needed to be added is the `spirv-tools` directory in the include path.

`-I ../../spirv-tools/include`

^^^ That's more of a conceptual description of what we need, as I don't know the actual path.

The two changes that were made in CMake in https://github.com/KhronosGroup/glslang/pull/2408 were:

https://github.com/KhronosGroup/glslang/blob/50bf17fe59d7e2e0f9f759a569dca98d34aa2c73/gtests/CMakeLists.txt#L88
https://github.com/KhronosGroup/glslang/blob/50bf17fe59d7e2e0f9f759a569dca98d34aa2c73/StandAlone/CMakeLists.txt#L74

Taking a look at `BUILD.gn`,

Line 72: `spirv_tools_dir = glslang_spirv_tools_dir`

So we want to find the CMake equivalent of ENABLE_OPT.. which, I'm going to guess is here:

https://github.com/KhronosGroup/glslang/blob/f4f1d8a352ca1908943aea2ad8c54b39b4879080/BUILD.gn#L251

If that is the case, it looks like we would want to add the include directory into that `if (invoker.enable_opt) {` block:

```
include_dirs += [ "${spirv_tools_dir}/include" ]
```

But we need to also have this `if` block that has the `include_dirs +=` inside wherever ENABLE_OPT=1 is defined, so:

`executable("glslang_validator") {`
`executable("spirv-remap") {`

I have never worked with your `BUILD.gn`, and am simply inferring the changes that need to be made. It would be great if some of your team could take a look at this.

Could you, or someone in your team, make these small additions and test on your infrastructure ?

(@timvpGoogle)

**Comment by phniix** [comment]
Hi,

I'm glad I'm not alone in getting caught out by all the different build environments.

Just ran a quick survery, and it appears to me the following exist:
- Android.mk
- BUILD.bazel
- BUILD.gn
- CMakeLists.txt 

Reasons why some are working versus not working, is dependent on the define `ENABLE_OPT=1` being specified. I bet if we start introducting that into all the build environments, we will see similar issues. 

It would be good if all the build environments were supported in glslang's CI.

Would this be something that we could get added ?

What we seem to have exposed here, is that the barrier to entry for contributors making such changes is quite high. Could some ideas be shared, or discussion had with these other build system teams, that would help reduce this barrier for contributors ? I feel it would greatly benefit the community if we could reduce the complexity we have discovered here.

(@johnkslang)

**Comment by phniix** [comment]
Thank you @ben-clayton @null77 @ShabbyX for stepping in and stepping up to help us all out with this!!

The community is grateful !

**Comment by ben-clayton** [comment]
Hi @phniix,

> It would be good if all the build environments were supported in glslang's CI.

Out of your list of build systems, I believe `BUILD.gn` is the only one that is currently untested. See [the Kokoro directory](https://github.com/KhronosGroup/glslang/tree/master/kokoro) for the current build configurations / scripts.

Once #2421 lands, I'll add the necessary CI configs for GN builds.

Many thanks,
Ben

**Comment by phniix** [comment]
Hiya @ben-clayton ! :D 

Really nice to see that the CI has got a handle on pretty much everything we need in that directory, and many thanks for showing me that directory.

Based on what I described earlier about the different build config files, it may just be that some of these configs don't exercise the full extent of the options being utilised by CMake and GN. This may lead to holes.. and from a contributor's standpoint, takes a lot of the fun out of contributing as they now need to learn all these new build systems in those rare occasions.

Perhaps that's something that can be looked into, now that we have a better understanding of the CI systems that are in full flight. It could be something like guidelines or quick start F.A.Q. for contributors, or some policies for those specific build system maintainers that could be employed in order to benefit the community.

All this stuff is really great, and it makes it possible to get https://github.com/KhronosGroup/glslang/issues/2405 out the door for everyone to use much much sooner.

Thanks for all your help on this!

**Comment by ben-clayton** [comment]
Hi @phniix ,

> Based on what I described earlier about the different build config files, it may just be that some of these configs don't exercise the full extent of the options being utilised by CMake and GN. This may lead to holes.. and from a contributor's standpoint, takes a lot of the fun out of contributing as they now need to learn all these new build systems in those rare occasions.

Yes, it's quite possible / likely that we're not building every build flag option. If there's flavors you (or anyone else) feel should be tested, please file a separate bug, and I'll get them added to the presubmits. 

> Perhaps that's something that can be looked into, now that we have a better understanding of the CI systems that are in full flight. It could be something like guidelines or quick start F.A.Q. for contributors, or some policies for those specific build system maintainers that could be employed in order to benefit the community.

I agree that each contributor shouldn't need to understand all the different build systems, and hopefully they won't need to. That said, if we're presubmit checking these build systems, then there should be documentation on how to reproduce. I've added GN build instructions to #2422. We're lacking documentation on building with Bazel and with Android.mk. I'll file some bugs to get this added.

> Thanks for all your help on this!

No worries!

Cheers,
Ben

**Comment by ben-clayton** [comment]
https://github.com/KhronosGroup/glslang/pull/2429 completes the work to add a `.gn` presubmit.

**Comment by ben-clayton** [comment]
I think this issue can now be closed.

**Comment by null77** [comment]
Nice work Ben! Thanks for improving the status quo for GN maintenance.

**Comment by phniix** [comment]
Yep, I totally echo @null77 - top shelf @ben-clayton , top shelf indeed.
👏👏👏

> Yes, it's quite possible / likely that we're not building every build flag option. If there's flavors you (or anyone else) feel should be tested, please file a separate bug, and I'll get them added to the presubmits.

Yes, I think the goal that we should strive for in terms of the presubmit pipelines is representative parity. In that, I mean it mightn't make sense to have a specific build target for a platform, and that's okay, but otherwise, we should aim for parity.

I'll add a broad brush issue to have an analysis across the different build systems, and for any gaps to be filled in, so that we can achieve representative parity.
