### ISSUE TITLE
Document build process for Bazel [BUILD.bazel]

### ISSUE THREAD

**Issue by ben-clayton** [KhronosGroup/glslang#2426]
The presubmits test the Bazel build system for [Windows](https://github.com/KhronosGroup/glslang/tree/master/kokoro/windows-msvc-2015-release-bazel), [macOS](https://github.com/KhronosGroup/glslang/tree/master/kokoro/macos-clang-release-bazel) and [Linux](https://github.com/KhronosGroup/glslang/tree/master/kokoro/linux-clang-release-bazel), but we currently do not have any documentation on how to locally reproduce these build environments.
We should add this documentation.

Related: https://github.com/KhronosGroup/glslang/issues/2413#issuecomment-712100571

**Comment by arcady-lunarg** [comment]
We no longer test the Bazel build system.
