### ISSUE TITLE
Fragment shader ray query, invalid SPIR-V

### ISSUE THREAD

**Issue by JayEff87** [KhronosGroup/glslang#2430]
Hello,

I've run into what I believe is a bug with glslValidator - although it could be the khronos validation layer too: Having tested it with functional shader code, the shader program runs fine, despite the validation error message.
I've got the following fragment shader:
```glsl
#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable

layout(location = 0) out vec4 outColor;

layout(binding = 1, set = 0) uniform accelerationStructureEXT topLevelAS;

void main() {
  outColor = vec4(0.0);
}
```
It compiles without issue, but upon loading the spir-v via `vkCreateShaderModule`, I get a validation error:
```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x1c6cf1057b8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Opcode TypeAccelerationStructureKHR requires one of these capabilities: RayQueryProvisionalKHR RayTracingNV RayTracingProvisionalKHR
  %49 = OpTypeAccelerationStructureKHR
```
The error is gone if I remove the declaration of topLevelAS. The error is also gone as soon as I actually make use of the topLevelAS in the code somewhere, so it's not exactly critical. I've tested it with the current master branch of glslang. Maybe some optimizing happens, the code compiles without the mentioned capabilities, which results in the error?

**Comment by johnkslang** [comment]
cc @dgkoch @Tobski

**Comment by dgkoch** [comment]
> The error is gone if I remove the declaration of topLevelAS. The error is also gone as soon as I actually make use of the topLevelAS in the code somewhere, so it's not exactly critical.

I'm not that familiar with the SPIR-V generation pass, but it sounds like the capabilities that are output are based on must be based on what is used by the code part, but not the declarations.  I don't know if that is unique to the AS type or if that also happens with other types as well.

**Comment by johnkslang** [comment]
For clip/cull distance, the specification allows needing the capability only on actual use, not on declaration.  I don't know the case for this issue, but normally we would include both declaration and use for needing the capability.  If so, glslang might just be missing an `addCapability` call when emitting the SPV declaration.

**Comment by dgkoch** [comment]
I think clip/cull is special case because it is a builtin declaration, and the way those are handled would have made every shader have the clip/cull capabilities. So agree that we must be missing the addCapability on the AS SPV declaration.

**Comment by dgkoch** [comment]
PR #2469 should fix this
