### ISSUE TITLE
Invalid shader OpEntryPoint

### ISSUE THREAD

**Issue by nitronoid** [KhronosGroup/glslang#2431]
The SPIR-V spec states:[ "Interface is a list of <id> of global OpVariable instructions"](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpEntryPoint)
However glslang doesn't seem to respect this rule and adds OpFunctionParameter instruction IDs to the list.
The relevant snippet is here I believe: https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp#L1727
It is checking `builder.isPointer(id)` but should it not also be checking `builder.isVariable(id)`?

Thanks

CC: @baxab

**Comment by johnkslang** [comment]
Do you have example input of current glslang making such SPIR-V?

Note that the first code inside the test you pointed to filters out GLSL-level parameters:

```
  if (!symbol->getType().getQualifier().isParamInput() &&
            !symbol->getType().getQualifier().isParamOutput())
```

And then there is final protection of seeing if it is global before adding it to the list:

```
builder.isGlobalStorage(id)
```

Though the behavior overall is version dependent.

**Comment by nitronoid** [comment]
Hi John,

consider this minimal shader:
```glsl
#version 410

layout(location = 0) out mediump vec4 out_color;

uniform sampler2DShadow shadow_map;


float get_linear_shadow(sampler2DShadow shadow_map, vec3 coord)
{
   return float(texture(shadow_map, coord));
}

void main()
{
    out_color = vec4(get_linear_shadow(shadow_map, vec3(0.5)));
}
```

When compiling with glslangValidator:
```bash
$ glslangValidator --version
Glslang Version: 8.13.3743
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 13.3743
GLSL Version: 4.60 glslang Khronos. 13.3743
SPIR-V Version 0x00010500, Revision 3
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 8
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100

$ glslangValidator -V --target-env spirv1.5 --aml --amb repro.frag -o repro.spv
```

We can see the issue when validating:
```
$ spirv-val repro.spv
error: line 44: Interfaces passed to OpEntryPoint must be of type OpTypeVariable. Found OpFunctionParameter.
  %shadow_map = OpFunctionParameter %_ptr_UniformConstant_8
```

The OpEntryPoint instruction has the following declaration:
```spirv
OpEntryPoint Fragment %main "main" %shadow_map %out_color %shadow_map_0
```

**Comment by johnkslang** [comment]
It's a bit old, I'm not sure.  Current glslang lists exactly two variables for OpEntryPoint and spirv-val does not complain about it.  The two variables are indeed the two globals, and not parameters.

Maybe make sure both your validator and glslang are up to date.

**Comment by nitronoid** [comment]
Hi John,

You're correct, the code in this area is different on master than on the tagged release I'm using and the additions you've pointed out do fix the issue.

As far as I can tell I'm using the latest tagged release, do you know when we can expect a new release of the compiler?

Thanks

**Comment by johnkslang** [comment]
Glslang now has a recent tag.  Your version was from April 27, 2020. We'd also tagged for the SDK on July 26th.  So, it's been about every 3 months recently.
