### ISSUE TITLE
glslangvalidator.exe

### ISSUE THREAD

**Issue by ReadZead** [KhronosGroup/glslang#2437]
where do I get/find the .exe? I need it for linter-glsl package for atom

**Comment by amdrexu** [comment]
You can install Vulkan SDK to get the binary: https://vulkan.lunarg.com/sdk/home. But the binary might lag behind the code base on GitHub.

**Comment by arcady-lunarg** [comment]
The best way to get the binary is via the Vulkan SDK releases from LunarG. New releases are done on a fairly regular basis.
