### ISSUE TITLE
Macro with concatenation used in #if causing preprocessor error

### ISSUE THREAD

**Issue by rdb** [KhronosGroup/glslang#2443]
Take this example:
```cpp
#version 430

#define HAVE_PLUGIN_XYZ 1

#define HAVE_PLUGIN(x) (HAVE_PLUGIN_ ## x)

#if HAVE_PLUGIN(XYZ)
#error yes
#else
#error no
#endif
```
This produces the following error:
```
ERROR: test.comp:7: 'preprocessor evaluation' : expected ')' 
ERROR: test.comp:7: '#if' : unexpected tokens following directive 
ERROR: test.comp:7: '' : missing #endif 
ERROR: test.comp:7: '' : compilation terminated 
ERROR: 4 compilation errors.  No code generated.
```

However, this pattern behaves as expected in `cpp` (producing the expected "yes" or "no" error depending on the value of HAVE_PLUGIN_XYZ)

**Comment by johnkslang** [comment]
This is a request to rerun macro expansion on the results of token pasting.  Would need to check if that's truly portable behavior.  It might not be, and that would matter if not all IHVs taking GLSL as input support it, or if the C++ spec says what happens is undefined.

**Comment by rdb** [comment]
I'll see if I can find some spec to confirm this, but I just want to add that this comes from a GLSL shader that has been used in production for years without issues on AMD, Intel and NVIDIA cards.

**Comment by rdb** [comment]
C11 spec, section 6.10.3.3 (emphasis mine):
> 3. For both object-like and function-like macro invocations, before the replacement list is reexamined for more macro names to replace, each instance of a ## preprocessing token in the replacement list (not from an argument) is deleted and the preceding preprocessing token is concatenated with the following preprocessing token. Placemarker preprocessing tokens are handled specially: concatenation of two placemarkers results in a single placemarker preprocessing token, and concatenation of a placemarker with a non-placemarker preprocessing token results in the non-placemarker preprocessing token. If the result is not a valid preprocessing token, the behavior is undefined. **The resulting token is available for further macro replacement.** The order of evaluation of ## operators is unspecified.

I also just double-checked that the Mesa Intel drivers on Linux and NVIDIA drivers on Windows both produce the expected behaviour.

**Comment by rdb** [comment]
@johnkslang Upon further investigation, glslang expands the result of token-pasting just fine; the issue here is that token-pasting isn't being performed at all when a function macro is invoked from an `#if`.  This works fine:
```
int a = HAVE_PLUGIN(XYZ);
```
I verified that the while loop in `TPpContext::tokenPaste` is never even being entered in the original example.

**Comment by johnkslang** [comment]
Good catch, thanks.
