### ISSUE TITLE
funny-looking release tag '10-11.0.0'?

### ISSUE THREAD

**Issue by tjaalton** [KhronosGroup/glslang#2450]
Was this tagged by mistake?

**Comment by johnkslang** [comment]
`glslangValidator.exe -v` shows `Glslang Version: 10:11.0.0`, using the new semantic versioning scheme.  (@ben-clayton)

Unfortunately, `:` as part of the version cannot be in a tag, git doesn't allow that.  So, I have wondered about fixing the version to not have a `:`.

**Comment by ben-clayton** [comment]
[Original discussion about prefixing the glslang version with the SPIR-V generator version here](https://github.com/KhronosGroup/glslang/pull/2277#issuecomment-645365363).

Personally, I'm not keen on the `:` prefix - I would probably just enforce bumping the version major for all SPIR-V generator changes, and document the SPIR-V generator version in the release notes.

**Comment by johnkslang** [comment]
FYI, all these numbers are base 10.

**Comment by johnkslang** [comment]
Also of fundamental note here is that semantic versioning sounds great for one thing.  But once a tool is multiple things it gets difficult, and some compromises are to be expected.

**Comment by Biswa96** [comment]
I would suggest **not** to use colon `:` or hyphen `-` in version. In ArchLinux, the [package version][1] uses those characters for different meanings.

[1]: https://wiki.archlinux.org/index.php/PKGBUILD#pkgver

**Comment by greg-lunarg** [comment]
glslang will be using the traditional major.minor.patch for tags going forward and dealing with generator changes per above suggestion from @ben-clayton
