### ISSUE TITLE
Recursive macro expansion

### ISSUE THREAD

**Issue by TerisGH** [KhronosGroup/glslang#2455]
Not sure if this behavior is expected, but the following code results in a compile error on the second line in main():
```
#version 450 core

layout(location = 0) out float Out;

layout(push_constant) uniform UBlock {
    float value;
} uInstance;
#define value uInstance.value
#define saturate(X) clamp( X, 0, 1 )

void main ()
{
    Out = value;
    Out = saturate(value);
}
```
The error is "'uInstance' : no such field in structure".
Inspecting the output with -E flag, the line gets preprocessed to:
Out = saturate(uInstance . uInstance . value);

**Comment by arcady-lunarg** [comment]
This has been fixed by https://github.com/KhronosGroup/glslang/pull/3114.
