### ISSUE TITLE
Copy paste bug inside glslang/MachineIndependent/reflection.h

### ISSUE THREAD

**Issue by qarmin** [KhronosGroup/glslang#2475]
https://github.com/KhronosGroup/glslang/blob/dd69df7f3dac26362e10b0f38efb9e47990f7537/glslang/MachineIndependent/reflection.h#L160

**Comment by johnkslang** [comment]
I don't immediately see the bug.  Note one side is about `In` while the other is about `Out`.

**Comment by qarmin** [comment]
Yup, I missed that and don't know why Cppcheck reported this.
