### ISSUE TITLE
Unreachable code after return inside SPIRV/GlslangToSpv.cpp

### ISSUE THREAD

**Issue by qarmin** [KhronosGroup/glslang#2477]
Strange that after case is return, and after that is later a code

https://github.com/KhronosGroup/glslang/blob/e11a2c8bece3dffc2fa6bfd1669b23c6f913ff07/SPIRV/GlslangToSpv.cpp#L3675-L3684

**Comment by johnkslang** [comment]
@Tobski could you have a look?  It's a good illusion, but needs a fix.

**Comment by arcady-lunarg** [comment]
Duplicate of #2763 which has already been fixed.
