### ISSUE TITLE
rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT appears to have the wrong type in glslangValidator's SPIR-V output

### ISSUE THREAD

**Issue by NeilBickford-NV** [KhronosGroup/glslang#2483]
Hi all! Here's a short summary of this issue: glslangValidator appears to output an `int` return type instead of a `uint` return type for [`rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT`](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_query.txt#L381) when translating GLSL to SPIR-V. This can result in an "inconsistent SPIR-V" Vulkan validation error when using this function, although it's possible to work around it by casting to `int`. Part of the bug might originate from [this line](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp#L7994).

Suppose one has a file called `raygen.comp.glsl` with the following code:
~~~ glsl
#version 460
#extension GL_EXT_ray_query : require

layout(local_size_x = 16, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;

void main()
{
  rayQueryEXT rayQuery;
  rayQueryInitializeEXT(rayQuery,       // Ray query
                        tlas,           // Top-level acceleration structure
                        0,              // Ray flags
                        0xFF,           // 8-bit instance mask
                        vec3(0),        // Ray origin
                        0.0,            // Minimum t-value
                        vec3(1, 0, 0),  // Ray direction
                        10000.0);       // Maximum t-value

  while(rayQueryProceedEXT(rayQuery))
  {
  }

  // Get the ID of the shader:
  const uint sbtOffset = rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT(rayQuery, true);
}
~~~

If they translate this file to a SPIR-V file named `comp.spv` using `glslangValidator --target-env vulkan1.2 raygen.comp.glsl` and try to load its content as a shader module in Vulkan with the validation layers enabled, they'll likely get a `UNASSIGNED-CoreValidation-Shader-InconsistentSpirv` validation error:

~~~
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2eee7dd7558, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: OpStore Pointer <id> '32[%sbtOffset]'s type does not match Object <id> '36[%36]'s type.
  OpStore %sbtOffset %36
~~~

The output of `spirv-dis comp.spv` contains the following lines:

~~~
       %uint = OpTypeInt 32 0
...
%_ptr_Function_uint = OpTypePointer Function %uint
...
  %sbtOffset = OpVariable %_ptr_Function_uint Function
...
         %35 = OpRayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR %int %rayQuery %int_1
               OpStore %sbtOffset %35
~~~

This appears to say that `OpRayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR` returns an int; however, `rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT` returns a uint, looking at the [GLSL_EXT_ray_query spec](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_query.txt#L381).

Searching the codebase, I think one part of the difference might come from https://github.com/KhronosGroup/glslang/blob/master/SPIRV/GlslangToSpv.cpp#L7994 ?

~~~ cpp
    case glslang::EOpRayQueryGetIntersectionInstanceShaderBindingTableRecordOffset:
        typeId = builder.makeIntType(32);
~~~

(e.g. maybe this should be `builder.makeUintType(32)`?)

Daniel Koch has also mentioned that `rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT` is the only integer-returning function in `GLSL_EXT_ray_query` that returns a `uint` instead of an `int`.

One workaround (which I'm using for the moment) is to both declare the type of `sbtOffset` as a `const int` and to explicitly cast to an `int`:

~~~ glsl
  const int sbtOffset = int(rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT(rayQuery, true));
~~~

This explicit cast to int appears to be necessary, since without it glslangValidator reports a compilation error:

~~~
raytrace.comp.glsl:25: '=' :  cannot convert from ' global uint' to ' const (read only) highp int'
~~~

Similarly, keeping `sbtOffset` as a `uint` and using an explicit cast to `uint`, e.g.

~~~ glsl
  const uint sbtOffset = uint(rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT(rayQuery, true));
~~~

isn't enough to work around the issue, because it produces the same inconsistent SPIR-V error. (It looks like explicitly casting to an int and then to a uint does also work, though!)

**Comment by dgkoch** [comment]
See https://github.com/KhronosGroup/glslang/pull/2484 for fix and tests.

**Comment by dgkoch** [comment]
Thanks for the very detailed report, test case, and pointing out the bug ;-)

**Comment by dgkoch** [comment]
Fix merged, but I don't seem to be able to close the issue.
