### ISSUE TITLE
spir-v:  ImageRead code generation generates result type other than 4-elem vector, for HLSL compilation

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#2486]
SPIRV-Tools has added validation of OpImageRead result type.
https://github.com/KhronosGroup/SPIRV-Tools/pull/4072 

For Vulkan, the result type must be a 4-element vector.
Glslang code generation for HLSL does not always follow this rule.

Failures in the test suite are:

[ FAILED ] 4 tests, listed below:
[ FAILED ] ToSpirv/HlslCompileTest.FromFile/hlsl_rw_register_frag, where GetParam() = 16-byte object <CC-16 01-9A 2D-56 00-00 23-EF 02-9A 2D-56 00-00>
[ FAILED ] ToSpirv/HlslCompileTest.FromFile/hlsl_rw_scalar_bracket_frag, where GetParam() = 16-byte object <E2-16 01-9A 2D-56 00-00 23-EF 02-9A 2D-56 00-00>
[ FAILED ] ToSpirv/HlslCompileTest.FromFile/hlsl_rw_vec2_bracket_frag, where GetParam() = 16-byte object <13-17 01-9A 2D-56 00-00 23-EF 02-9A 2D-56 00-00>
[ FAILED ] Hlsl/HlslIoMap.FromFile/spv_rw_autoassign_frag, where GetParam() = 40-byte object <07-3B 01-9A 2D-56 00-00 23-EF 02-9A 2D-56 00-00 05-00 00-00 0A-00 00-00 14-00 00-00 0F-00 00-00 1E-00 00-00 01-01 00-00>

**Comment by greg-lunarg** [comment]
Fixed by #2706
