### ISSUE TITLE
10-11.0.0: messy tagging

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/glslang#2493]
Is 10-11.0.0 official?
Why it has dash in the version tag?
None of the packaging software allows to use dash in version tag.

**Comment by greg-lunarg** [comment]
OK. I am working on a solution...

**Comment by greg-lunarg** [comment]
@kloczek What is the syntax you want to see for version tags? I am presuming Major.Minor.Patch. Let me know if you want to see something different.

**Comment by kloczek** [comment]
In version string can be used digits and dots.
If you want on github you can use prefix `v` because that prefix is automatically sipped on generate autogenerated tagged tar bal;l availaible in `arvive/<tag>.tar.gz` archives.

In this case question is: what was the propose `10-11.0.0`?
Did you think about `10.11.0.0`?

You can add new tag on top of existing tag or exact hash and than delete old tag (if you widh).

**Comment by greg-lunarg** [comment]
The leading 10- is not consistent with semantic versioning. My plan is to remove this tag and replace it with 11.0.0.

I will also be adding the tag 11.1.0 to the later commit c594de2.

I will comment here when this is complete.

**Comment by kloczek** [comment]
OK 👍

**Comment by greg-lunarg** [comment]
I have completed the tasks I described above.

I believe I have addressed your concerns and will close this issue. Please reopen if this is not the case.

**Comment by kloczek** [comment]
Yep it looks now as it shopuld be.
Thx :)

**Comment by orbea** [comment]
@greg-lunarg and @kloczek I agree the new tag name is better, but please don't delete old tags in the future. Downstream distros might be using them.
