### ISSUE TITLE
11.1.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/glslang#2494]
``
$ rpm -qa ^spirv*
spirv-tools-libs-2020.6-2.fc34.x86_64
spirv-tools-2020.6-2.fc34.x86_64
spirv-headers-devel-1.5.4.raytracing-2.fc34.noarch
spirv-tools-devel-2020.6-2.fc34.x86_64
```
```
+ cd glslang-11.1.0
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 -C x86_64-redhat-linux-gnu test ARGS=--output-on-failure
make: Entering directory '/home/tkloczko/rpmbuild/BUILD/glslang-11.1.0/x86_64-redhat-linux-gnu'
Running tests...
/usr/bin/ctest --force-new-ctest-process --output-on-failure
Test project /home/tkloczko/rpmbuild/BUILD/glslang-11.1.0/x86_64-redhat-linux-gnu
    Start 1: glslang-testsuite
1/1 Test #1: glslang-testsuite ................***Failed    7.37 sec
Running reflection...
Comparing single thread to multithread for all tests in current directory...
Running entry-point renaming tests
Running ill-defined uncalled function
Tests Succeeded.
Running explicit stage test and compound suffix tests
Running hlsl offsets
Running hlsl offsets
Configuring HLSL descriptor set and binding number manually
Testing per-descriptor-set IO map shift
Testing SPV no location
Testing SPV Debug Information
2,3d1
< error: SPIRV-Tools Validation Errors
< error: Invalid SPIR-V binary version 1.3 for target environment SPIR-V 1.0 (under OpenGL 4.5 semantics).
Testing Includer
Testing -D and -U
Testing --client and --target-env
spv.targetVulkan.vert
spv.targetOpenGL.vert
spv.targetVulkan.vert
spv.targetVulkan.vert
spv.targetVulkan.vert
spv.targetOpenGL.vert
spv.targetVulkan.vert
spv.targetOpenGL.vert
spv.targetVulkan.vert
Testing GLSL entry point rename
Testing remapper error handling
Testing position Y inversion
Testing hlsl_functionality1
Testing HLSL-specific PP feature expansion
Testing nan-clamp
Tests Failed.

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   7.37 sec

The following tests FAILED:
          1 - glslang-testsuite (Failed)
Errors while running CTest
make: *** [Makefile:140: test] Error 8
make: Leaving directory '/home/tkloczko/rpmbuild/BUILD/glslang-11.1.0/x86_64-redhat-linux-gnu'
```

**Comment by greg-lunarg** [comment]
Thank you for pointing out the previous error. That is very helpful. It suggests that this is a problem not with the current glslang configuration, but a longer standing problem with glslang on Linux.

**Comment by greg-lunarg** [comment]
OK. After some investigation I have learned this much...

The "error" you are seeing is NOT really erroneous behavior on the part of glslangValidator on Linux. It is a problem with incorrect expected test results generated by an incorrectly behaving glslangValidator on Windows.

I will shortly fix glslangValidator on Windows and fix the expected test results.

Shall I tag the new commit with 11.1.1?

**Comment by kloczek** [comment]
I thing that it is not so critical :) but I think that other peple may be reporting that issu eas well so probably it would be good to have clean tagged version.
If you have patch for that issue I would be glad to test it before you will commit that fix and/or make new release.

Thx for quick reply.
Happy New Year (in UK is already 0:40) :)
