### ISSUE TITLE
Regression: Python 3 is required even without using SPIRV-Tools

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#2496]
See #1929

**Comment by greg-lunarg** [comment]
@ben-clayton Could you take a look at this? Apparently https://github.com/KhronosGroup/glslang/commit/fbe9a23baf2cb020fe3f80d68d972e2a97d9b954 caused this regression.

**Comment by johnkslang** [comment]
An important refinement of the question here is whether it is python 3 or just python at all that is the issue.

From the original issue it seems like the goal was to avoid python. The script could probably work with 2.7 or 3 (maybe with tweaks?), but of course if the goal is to avoid python for core glslang, that would not be a fix. 

Then, the question would be, is running this script really necessary for an end consumer versus someone wanting to do something upstream, etc.

**Comment by ben-clayton** [comment]
Sorry about this - I remember discussing internally whether python was a build requirement before making these changes, and we had incorrectly decided it was.

I see 3 options here:

1. Require python (I'd strongly encourage 3 over [end-of-life 2.x](https://www.python.org/doc/sunset-python-2/))
2. Reimplement [build_info.py](https://github.com/KhronosGroup/glslang/blob/master/build_info.py) in C++ using std [regex](https://en.cppreference.com/w/cpp/regex), have this built as a tool used for later build stages.
3. Commit the generated the `build_info.h` file.

If we went with 3, then we'd have to ensure that the file does not get out of sync with the [CHANGES.md](https://github.com/KhronosGroup/glslang/blob/master/CHANGES.md) file. This could be done with a presubmit test.

**Comment by johnkslang** [comment]
I think python is required for true glslang development and upstreaming, versus a downstream consumer-only situation.  But, we should first know what the request even is; no python versus no python 3.

(We similarly offload the need for bison for grammar creation for such situations.)

**Comment by greg-lunarg** [comment]
My interpretation is that there is currently a dependency on Python even when SPIRV-Tools is not built in. This contradicts the README.md. The issue is not the version of Python, but Python generally.

**Comment by greg-lunarg** [comment]
As for a solution, let's start with the one that is the least work and the most maintainable: require Python. How big a deal is it to add this as a dependency @johnkslang?

**Comment by greg-lunarg** [comment]
Anyone building a glslang that needs to support HLSL already has had to use Python. So it is probably the biggest deal to those who are solely GLSL users.

**Comment by johnkslang** [comment]
We should hear from users how big a deal it is to need python 3.  I can imagine it is a pain when they're already currently working just fine without python, or python 2.7, and it's a big mess to dual install python and have everything grab the correct version.  (What a mistake to call two different languages the same name!)

**Comment by greg-lunarg** [comment]
Given that adding the Python dependence will be non-trivial for some, and is avoidable, my vote would be for 3 next. We already have some manual aspects of release, so adding to this process will not be that radical.

Any strong objections?

**Comment by nihui** [comment]
Hi
As a downstream glslang user, in order to avoid the build dependency of python, we have been using the old version of glslang.
I hope that glslang can be build more simply to adapt to more platforms and systems.

As far as I know, python is only used to generate some version information. I think we can allow the caller to define this information through cmake variables, so that the call of python can be skipped. It is rough but works.

**Comment by LaySoe** [comment]
Thankfully service

**Comment by greg-lunarg** [comment]
@ben-clayton I would like to go with solution #3 above. Did you want to make the changes or shall I?

**Comment by ben-clayton** [comment]
I'm afraid I do not have the time right now to look into this.

I've realized there's a 4th option - that we parse the version information using CMake regex (assuming everyone asking for dropping the python dep is using CMake here), and write out the `build_info.h` file from CMake.
[I've actually done this already with another project](https://github.com/google/marl/blob/main/cmake/parse_version.cmake), and the logic could just be reused.

I'd also be happy with checking in the `build_info.h` file, but be aware of the N different build systems. At least most of these now have presubmit checks in place.

**Comment by proydakov** [comment]
I implemented fix https://github.com/KhronosGroup/glslang/pull/2526

**Comment by greg-lunarg** [comment]
#2526 merged.
