### ISSUE TITLE
Combining -G and -D is currently not supported and should generate error.

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#2497]
It was not the intention that -G would work with -D, that is, that glslangValidator would create SPIR-V from HLSL source that would work with OpenGL. Specifically, it would not join separate texures and samplers into single sampled textures.

The man page should be changed to point out this is not allowed and an error should be generated from glslangValidator when attempted.

FWIW, it is reported that running the resultant SPIR-V from HLSL into spirv-cross to get GLSL and running that back through glslangValidator can create the desired result.

**Comment by greg-lunarg** [comment]
See #1417 for more details.

**Comment by johnkslang** [comment]
As #1417 points out, this is a valid request for an enhancement.  So, just clarifying this specific issue is simply to disallow it until it works correctly.
