### ISSUE TITLE
Converting uint to/from pointers with Vulkan PhysicalStorageBuffer64 using 32-bit wide ints

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/glslang#2510]
While trying add validation for Vulkan https://github.com/KhronosGroup/SPIRV-Tools/pull/4122

`VUID-StandaloneSpirv-PhysicalStorageBuffer64-04710`

>  If the PhysicalStorageBuffer64 addressing model is enabled, OpConvertUToPtr and OpConvertPtrToU must use an integer type whose Width is 64

The following two tests are failing CI

- `Test/spv.bufferhandle9.frag`
- `Test/spv.bufferhandle18.frag`

due to using 32-bit ints even with `--target-env vulkan1.2` set

**Comment by greg-lunarg** [comment]
@sfricke-samsung Are you working on a PR or do you want me to do it?

**Comment by sfricke-samsung** [comment]
I will assign to myself, if I find time is too finite or something else, will ping you for some help

**Comment by sfricke-samsung** [comment]
The error was with SPIR-V Val, all is fixed and good now
