### ISSUE TITLE
Passing "gtextureXX" object to "gsamplerXX" function does not result in compile error

### ISSUE THREAD

**Issue by djewsbury** [KhronosGroup/glslang#252]
When using separate texture/sampler objects (as described in https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt), gtextureXX can be incorrectly used with functions such as "texture", "texelFetch" without a compile error. 

However, on nvidia devices this will generate a VK_ERROR_INVALID_SHADER_NV error code if the bytecode is used with vkCreateGraphicsPipeline.

*To reproduce:*

Using the "separate_image_sampler.cpp" sampler in the LunarG samples, change line 75:

> "    vec4 resColor = texture(sampler2D(tex, samp), inTexCoords);\n"

to:

> "    vec4 resColor = texture(tex, inTexCoords);\n"

The shader will compile in "init_shaders" successful. But the sample will fail in "init_pipeline."

It's potential confusing because the gtextureXX objects and gsamplerXX objects are so similar. Also, some functions (such as texelFetch) feel like they might work with a gtextureXX object. But this doesn't seem to be guaranteed by GL_KHR_vulkan_glsl. It might be clearer if it just generated a compile error.

**Comment by johnkslang** [comment]
Agreed.  This is fixed with 2921e0c54a95264a6fd193c79c814f2869ef9a2d.
