### ISSUE TITLE
can atomic counter speicifed with location ?

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2520]
Hi ,
   I have a question about why the glsang don't report the errors:  atomic counter can not specified with location. I don't know if I missed anything, thank you，

here is the testsuit cmd:
glcts.exe --deqp-case=ES31-CTS.functional.uniform_location.negative.atomic_vertex 

`#version 310 es
precision highp float;
layout(location = 3, binding = 0, offset = 0) uniform atomic_uint uni0;
in highp vec4 dEQP_Position;
out float out0;

void main()
{
	out0 = 0.0;
	gl_Position = dEQP_Position;
}`

**Comment by greg-lunarg** [comment]
Yes, specifying location on an atomic_uint is not defined and should be an error.

In order to make this change with as little disruption as possible, could you please open an issue against CTS for this and any other such tests and post that issue here. Once that is addressed we can make this change without breaking CTS.

**Comment by ZhiqianXia** [comment]
@greg-lunarg that's a great idea , but I just  found two CTS test have this issue so far.  And I not sure the workflow about this project.  Is it  necessary to open a new issue If i want submit my PR ?  thank you.

**Comment by ZhiqianXia** [comment]
@greg-lunarg Hi greg, I also found some test should report error (not same error), but it didn't. Should I open a new issue for each error ?

**Comment by greg-lunarg** [comment]
> Is it necessary to open a new issue If i want submit my PR ? thank you.

For CTS, if you just have have a PR, it might be sufficient to just submit. I am not sure, but it is worth a try.

> I also found some test should report error (not same error), but it didn't. Should I open a new issue for each error ?

For either glslang or CTS, you should open an issue for each different problem. Thanks!

**Comment by ZhiqianXia** [comment]
@greg-lunarg thanks. May be this issue should be closed , if i submit

**Comment by ShchchowAMD** [comment]
Fixed locally, will update soon.

BTW, if you found some ES CTS cases failed, please at me. Some local commits haven't been upstreamed to glslang. Was making local testing. Wish this would help.

@ZhiqianXia

**Comment by ZhiqianXia** [comment]
@ShchchowAMD Thank your reachout.  I also submit the [PR](https://github.com/KhronosGroup/glslang/pull/2525) for this issue.

**Comment by greg-lunarg** [comment]
Fixed with merge of #2525
