### ISSUE TITLE
Crashes in release

### ISSUE THREAD

**Issue by Vironacorus** [KhronosGroup/glslang#2521]
After building glslang with instructions I opened glslang.sln and changed configuration to Release. I built in release and copied necessary .lib/.h files into glslang_release.

I use C interface.
```

glslang_shader_t* shader = glslang_shader_create(&input);

HERE >	if (!glslang_shader_preprocess(shader, &input))
```

in operator new (MSVC - file: new_scalar.cpp)
```
	const glslang_input_t input =
	{
		.language = GLSLANG_SOURCE_GLSL,
		.stage = stage,
		.client = GLSLANG_CLIENT_VULKAN,
		.client_version = GLSLANG_TARGET_VULKAN_1_0,
		.target_language = GLSLANG_TARGET_SPV,
		.target_language_version = GLSLANG_TARGET_SPV_1_0,
		.code = shader_code,
		.default_version = 100,
		.default_profile = GLSLANG_NO_PROFILE,
		.force_default_version_and_profile = false,
		.forward_compatible = false,
		.messages = GLSLANG_MSG_DEFAULT_BIT,
		.resource = &res
	};
```

this is my input

I also saw it crashing on other functions in glslang, but this is where it mostly crashes. I assume some glslang function overrides memory block or something...

**Comment by Vironacorus** [comment]
Or maybe I built it wrong.. idk

**Comment by Vironacorus** [comment]
(But issue isnt' solved)

**Comment by greg-lunarg** [comment]
Is this a recent regression, or the first time you have built and run this?

**Comment by Vironacorus** [comment]
@greg-lunarg Previously I was using debug mode but I wanted to test my program in release mode once and it crashed.

**Comment by greg-lunarg** [comment]
Not sure why Release would fail if Debug works.

I will share the code we use to test the (Release) glslang libs shipped with the SDK. Maybe that will help.

**Comment by greg-lunarg** [comment]
[CMakeLists.txt](https://github.com/KhronosGroup/glslang/files/5921477/CMakeLists.txt)
[glsl_test.cpp.txt](https://github.com/KhronosGroup/glslang/files/5921485/glsl_test.cpp.txt)

Put these in a scratch directory with a build directory and cd to the build directory. Then do:

cmake -G 'Visual Studio 16 2019' -A x64 -T v140 -D INCLUDE_PATH=inc_dir -D LIB_PATH=lib_dir  .. 
cmake --build . --config Release
Release\glsl_test.exe

where inc_dir is the directory with all the required glslang include files (see the organization of the SDK Include directory) and lib_dir is the directory containing all the libs.

**Comment by greg-lunarg** [comment]
The inc_dir contains the glslang directory and here is the contents of glslang:

glslang/:
Include  MachineIndependent  Public  SPIRV

glslang/Include:
arrays.h     Common.h         intermediate.h  ResourceLimits.h
BaseTypes.h  ConstantUnion.h  PoolAlloc.h     Types.h

glslang/MachineIndependent:
localintermediate.h  Versions.h

glslang/Public:
ShaderLang.h

glslang/SPIRV:
GlslangToSpv.h  Logger.h  spirv.hpp  spvIR.h  SPVRemapper.h  SpvTools.h

**Comment by greg-lunarg** [comment]
Also remove .txt from glsl_test.cpp.txt :)

**Comment by Vironacorus** [comment]
Ok let me see

**Comment by Vironacorus** [comment]
cmake --build . --config Release

doesn't work for some reason

It gives me this error:

```
error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using
 the v140 build tools, please install Visual Studio 2015 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
[C:\Users\User\Desktop\test\ZERO_CHECK.vcxproj]
```

**Comment by greg-lunarg** [comment]
Sorry, what version of Visual Studio are you building with?

**Comment by Vironacorus** [comment]
@greg-lunarg Visual Studio 2019 (16)...

**Comment by greg-lunarg** [comment]
OK, then please use this instead of the first line above:

cmake -G 'Visual Studio 16 2019' -A x64 -D INCLUDE_PATH=<inc_dir> -D LIB_PATH=<lib_dir> ..

All of these should be in the <lib_dir>:

GenericCodeGen.lib
glslang.lib
HLSL.lib
MachineIndependent.lib
OGLCompiler.lib
OSDependent.lib
SPIRV.lib
SPVRemapper.lib

**Comment by Vironacorus** [comment]
@greg-lunarg 
It worked in this project, so something needs to be wrong with my code. I will try to debug a bit and then inform you

**Comment by Vironacorus** [comment]
@greg-lunarg If you could help me, check this file: https://github.com/Vironacorus/ShaderSight/blob/main/shader.c

**Comment by Vironacorus** [comment]
I think it might be other piece of code, that's causing the issue, but it's finally crashing on glslang functions for some reason. I'm closing the issue.
