### ISSUE TITLE
TShader::preprocess does not work with GL_EXT_ray_tracing enabled

### ISSUE THREAD

**Issue by Luke-Filewalker** [KhronosGroup/glslang#2533]
When I try to preprocess a raygen shader with #extension GL_EXT_ray_tracing : enable and with version EShTargetSpv_1_4 correctly set, TShader::preprocess returns with an error of :

ERROR: 0:5: 'GL_EXT_ray_tracing' : not supported for current targeted SPIR-V version
ERROR: 0:5: '#extension' : extra tokens -- expected newline
ERROR: 2 compilation errors.  No code generated.

After some debugging I found the source of the error beeing in TParseVersions::extensionRequires(), since GL_EXT_ray_tracing requieres EShTargetSpv_1_4 but the present version is always EShTargetSpv_1_0. When skipping this check it works as expected.

**Comment by greg-lunarg** [comment]
Just pushed #2532. Please retry with this fix.

**Comment by Luke-Filewalker** [comment]
Works now, thanks
