### ISSUE TITLE
Which tag / branch should be used for latest stable version?

### ISSUE THREAD

**Issue by axsaucedo** [KhronosGroup/glslang#2539]
Currently the releases seem to have a broad range of different naming conventions, including "master-tot", "SDK-candidate-<...>", and some more intuitive versions such as "11.0.1".  Which would be the right tag to use to match the currently released stable version, is it 11.0.1? For example, currently VCPKG seems to be using a branch that doesn't align to the versioned tags that are available in the repo.

**Comment by greg-lunarg** [comment]
I am calling the latest version 11.1.0 because it has some new functionality (supports new language features). I will be tagging ecd9bb202ffb0b48868ec23d1c3288670ba98abe with "11.1.0" shortly.

Please re-open if you have follow up questions or comments.

**Comment by axsaucedo** [comment]
Ok thank you @greg-lunarg I have opened an issue in the vcpkg repo to confirm that this is the correct branch/tag to use https://github.com/microsoft/vcpkg/issues/16305

**Comment by greg-lunarg** [comment]
I have created tag 11.2.0.
