### ISSUE TITLE
The default precision of gl_SampleMaskIn in glsl 450

### ISSUE THREAD

**Issue by amyliu01** [KhronosGroup/glslang#2541]
Hi, glslang experts

We meet a precision problem about gl_SampleMaskIn in ANGLE ( shader transform: gles -> glsl 450 -> spirv). Please help to verify.
We have a ESSL fragment shader like this：

void main (void)
{
     mediump int maskBitCount = 0;
     for (int i = 0; i < 32; ++i)
             if (((gl_SampleMaskIn[0] >> i) & 0x01) == 0x01)
                     ++maskBitCount;

     if (maskBitCount < u_minBitCount || maskBitCount > u_maxBitCount)
             fragColor = vec4(1.0, 0.0, 0.0, 1.0);
     else
             fragColor = vec4(0.0, 1.0, 0.0, 1.0);
}

In gles3.2, gl_SampleMaskIn is defined as highp, so the rightShift operation from 0 to 31 is valid.
https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html
The built-in special variables that are accessible from a fragment shader are intrinsically declared as follows:
in highp int gl_SampleMaskIn[(gl_MaxSamples+31)/32];

But in glsl 450 (which is used by ANGLE), gl_SampleMaskIn seems to be defined as the default precision mediump.
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf
The fragment language has the following predeclared globally scoped default precision statements:
precision mediump int;
In the fragment language, built-in variables are intrinsically declared as:
in int gl_SampleMaskIn[];

When ANGLE handles the transformation of gl_SampleMaskIn, we find that the RelaxedPrecision decoration is added. It may cause problem in driver since gl_SampleMaskIn is right shifted from 0 to 31 and driver chooses 16-bit to store the value of gl_SampleMaskIn.

"
	Line 379: OpName %24 "gl_SampleMaskIn"
	Line 403: OpDecorate %24 RelaxedPrecision
	Line 404: OpDecorate %24 Flat
	Line 405: OpDecorate %24 BuiltIn SampleMask
"

Do you have any idea to fix the issue in glslang ？
Thanks a lot.

**Comment by john-xujun** [comment]
Hi @ShabbyX,
Is there anyone you can suggest to take a look at this issue?

**Comment by johnkslang** [comment]
How is the shader version declared and compiled?

Desktop versions that don't target Vulkan should ignore precision qualifiers, while desktop versions that target Vulkan should default to highp.

From the 4.60.7 specification (which is where the Vulkan language was added):

> 4.7. Precision and Precision Qualifiers
>
>When not targeting Vulkan: Precision qualifiers are added for code portability with OpenGL ES, not for functionality. They have the same syntax as in OpenGL ES, as described below, but they have no semantic meaning, 

> 4.7.3. Default Precision Qualifiers
>
> For any type that accepts a precision qualifier, the default precision qualification will be highp. Because all types requiring a precision qualifier have a default precision, there are no errors for omission of a precision qualifier.

**Comment by ShabbyX** [comment]
@johnkslang This is the shader as generated by ANGLE:

```
// GLSL
//
// #version 310 es
// #extension GL_OES_sample_variables : require
// layout(location = 0) out mediump vec4 fragColor;
// uniform highp int u_minBitCount;
// uniform highp int u_maxBitCount;
// void main (void)
// {
// 	mediump int maskBitCount = 0;
// 	for (int i = 0; i < 32; ++i)
// 		if (((gl_SampleMaskIn[0] >> i) & 0x01) == 0x01)
// 			++maskBitCount;
// 
// 	if (maskBitCount < u_minBitCount || maskBitCount > u_maxBitCount)
// 		fragColor = vec4(1.0, 0.0, 0.0, 1.0);
// 	else
// 		fragColor = vec4(0.0, 1.0, 0.0, 1.0);
// }


#version 450 core

layout(set=0, binding=0, std140) uniform defaultUniformsFS
{
    int _uu_minBitCount;
    int _uu_maxBitCount;
};
struct ANGLEDepthRangeParams {
highp float near;
highp float far;
highp float diff;
highp float reserved;
};
layout(location=0) out mediump vec4 _ufragColor;
layout(set=0, binding=1) uniform ANGLEUniformBlock{
vec4 viewport;
uint clipDistancesEnabled;
uint xfbActiveUnpaused;
int xfbVerticesPerInstance;
int numSamples;
ivec4 xfbBufferOffsets;
uvec4 acbBufferOffsets;
ANGLEDepthRangeParams depthRange;
} ANGLEUniforms;
void main(){
mediump int _umaskBitCount = 0;
for (mediump int _ui = 0; (_ui < 32); (++_ui))
{
if ((((gl_SampleMaskIn[0] >> _ui) & 1) == 1))
{
(++_umaskBitCount);
}
}
if (((_umaskBitCount < _uu_minBitCount) || (_umaskBitCount > _uu_maxBitCount)))
{
(_ufragColor = vec4(1.0, 0.0, 0.0, 1.0));
}
else
{
(_ufragColor = vec4(0.0, 1.0, 0.0, 1.0));
}
}
```

This is compiled with:

```
    constexpr EShMessages messages = static_cast<EShMessages>(EShMsgSpvRules | EShMsgVulkanRules);
    ...
    bool result = shader->parse(&builtInResources, 450, ECoreProfile, false, false, messages);
```

**Comment by greg-lunarg** [comment]
Even the glsl 450 spec says that mediump has no meaning. It also says that int must be 32 bits. It also explicitly and implicitly states that each element of gl_SampleMaskIn[] must be 32 bits.

So I agree that glslang is in error to attach the RelaxedPrecision decoration to gl_SampleMaskIn for a glsl 450 shader.

I will assign this to myself unless someone has started a fix, in which case please comment here.

**Comment by greg-lunarg** [comment]
Slight correction: I still maintain that glslangValidator should not generate the RelaxedPrecision for gl_SampleMaskIn here, but with different reasoning closer to what @johnkslang was getting at.

First, I am presuming you are targeting Vulkan. Not sure if that is completely implied by the parse() call above. Please let me know if that is not true.

Given a Vulkan target, that means that the GL_KHR_vulkan_glsl extension is invoked. This means that, similar to 4.60.7 language that @johnkslang pointed to, all ints are highp by default so gl_SampleMaskIn should be highp and not decorated RelaxedPrecision.

I have verified this bug using the command line interface as well.

**Comment by greg-lunarg** [comment]
Interesting observation and possible workaround: removing the mediump from the other ints in the program also causes the RelaxedPrecision on gl_SampleMaskIn to go away. So this suggests to me that this is not about an incorrect default precision of gl_SampleMaskIn, but the mediump precision of _ui (incorrectly) propagating across the >> to the load and even the declaration of gl_SampleMaskIn?!?!

**Comment by ShabbyX** [comment]
That's interesting. Unfortunately, we'd prefer not to have to work around this (we do take advantage of the performance gain that comes with lower precision), especially as this should be fixable in the source :)

**Comment by greg-lunarg** [comment]
No worries. I should have a simple fix shortly.
