### ISSUE TITLE
is this allowed by glslang - variable initialization as X=-X

### ISSUE THREAD

**Issue by danilw** [KhronosGroup/glslang#2542]
minimal code:

```
void test(out float val){
    val=-val; // is val initialized?
}
```
in Nvidia OpenGL GLSL driver compiler `val` will be initialized

related to Nvidia Vulkan driver bug 
https://forums.developer.nvidia.com/t/shader-behavior-on-unitialized-variable-maybe-bug/168947

**Comment by johnkslang** [comment]
It is quite difficult to solve and/or specify a near-complete solution to knowing a variable is used before it is initialized. So, the GLSL specification does not include requirements for error messages about uninitialized variables. So, glslang does not include analysis for this.

Your example might even depend on what is happening outside `test()` in a compiler that does such analysis after inlining.

The specification touches on this:

> Compilers, in general, accept programs that are ill-formed, due to the impossibility of detecting all ill-formed programs. Portability is only ensured for well-formed programs, which this specification describes. Compilers are encouraged to detect ill-formed programs and issue diagnostic messages, but are not required to do so for all cases.

(Consumption of uninitialized variables is ill-formed and non-portable but not required to generate an error.)

**Comment by danilw** [comment]
> Your example might even depend on what is happening outside test() in a compiler that does such analysis after inlining.

http://shader-playground.timjones.io/62d20e031c5d884afde509037209a8d4

this `fragColor-= fragColor;` result this code:
```
    mov r32773, r32768
    mov r32774, r32768
    sub r32775, r32774, r32773
    mov r32768, r32775
```

so this means result of `fragColor-= fragColor;` depends on the GPU driver

in Nvidia OpenGL, this does initialize, in Nvidia Vulkan its not

I think it completely related to Nvidia GPU drivers so I close this, this is not glslang issue
