### ISSUE TITLE
Where do the header files inside the `StandAlone` directory get installed?

### ISSUE THREAD

**Issue by aliPMPAINT** [KhronosGroup/glslang#2547]
So, after the installation (sudo make install) where do header files inside the `StandAlone` directory get installed(like `StandAlone/ResourceLimits.h`)?

**Comment by greg-lunarg** [comment]
All the headers that are part of the external interface can be found in <install_dir>/include/glslang/Include/, where <install_dir> is the installation directory you have specified.

You can set the install directory using -DCMAKE_INSTALL_PREFIX on the configuration cmake. This variable defaults to /usr/local on UNIX and c:/Program Files on Windows.

FYI, StandAlone/ResourceLimits.h is not part of the external interface, although glslang/Include/ResourceLimits.h is.

Please reopen if you have further questions.
