### ISSUE TITLE
gl_MaxCombinedTextureImageUnits Default value.

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2550]
Hi ,
I found that gl_MaxCombinedTextureImageUnits have different value for different spec version.  But we just set the defaut value
as 80 at ResourceLimits.cpp. if i have a 320es shader which binding value  exceed  gl_MaxCombinedTextureImageUnits. there is a error occur. I think that we should set the ResourceLimits base on the version instead of the fixed value. 

@greg-lunarg Do you have other ideas?

For exampe:
For oes: (ch 7.2 Built-In Constants)
310 : 32
320 : 96 

For ogl:
330 : 48
400 ~ 440 : 80
450 ~ 460 : 96

**Comment by greg-lunarg** [comment]
@ZhiqianXia Curious why you closed this?

**Comment by ZhiqianXia** [comment]
Sorry for my careless , it's not related to the glslang code.
