### ISSUE TITLE
GL_ARB_sparse_texture_clamp not supported in raytracing shaders

### ISSUE THREAD

**Issue by nbentyNV** [KhronosGroup/glslang#2551]
Trying to use `textureGradOffsetClampARB` in a miss shaders results in compilation error - `'textureGradOffsetClampARB' : no matching overloaded function found`.

The bug was traced to this snippet, which ignores raytracing shaders:
```
 // Add to the per-language set of built-ins
                                            if (bias || lodClamp != 0) {
                                                stageBuiltins[EShLangFragment].append(s);
                                                stageBuiltins[EShLangCompute].append(s);
                                            } else
                                                commonBuiltins.append(s);
```

**Comment by greg-lunarg** [comment]
Which other ray tracing shaders should we enable besides miss shaders? Presuming all?

**Comment by greg-lunarg** [comment]
@dgkoch Can you answer the question above?

**Comment by dgkoch** [comment]
When we discussed internally before @nbentyNV filed the issue @jeffbolznv said: 

> This seems to assume that lodClamp is only for implicit lod functions, but that's not true in this case

So I believe that means it should be supported in all shader stages.

**Comment by greg-lunarg** [comment]
@dgkoch @jeffbolznv  All ray-tracing stages or ALL stages?

**Comment by jeffbolznv** [comment]
The grad functions can work in all stages.
