### ISSUE TITLE
glslangValidator: using layout(depth_unchanged) may produce invalid SPIR-V

### ISSUE THREAD

**Issue by ilkkasaa** [KhronosGroup/glslang#2555]
Using `depth_unchanged` GLSL layout qualifier in fragment shader produces invalid SPIR-V if `gl_FragDepth` is written in the shader.
This can be reproduced with the following GLSL shader:
```
#version 430
layout(location = 0) out vec4 outColor;
layout(depth_unchanged) out float gl_FragDepth;
void main() {
  outColor = vec4(1.0, 0.0, 0.0, 1.0);
  gl_FragDepth = gl_FragCoord.y;
}
```
The generated SPIR-V is missing `DepthUnchanged` and `DepthReplacing` execution modes, but still writes to `FragDepth`. Looking at the code, the behavior seems to be intentional for some reason:
https://github.com/KhronosGroup/glslang/blob/b0f8a0c3abb943910d0a99df9da5e34d10273a4b/SPIRV/GlslangToSpv.cpp#L1554
Looks like the code is rather old and the SPIR-V specs about `FragDepth` and `DepthUnchanged` have been clarified afterwards, so that might explain the unexpected behavior.

While the depth shouldn't be changed by the shader if `DepthUnchanged` is used, it's still allowed to write to `FragDepth` and in that case `DepthReplacing` execution mode must be used to avoid undefined behavior. From SPIR-V spec: 
```
DepthReplacing
This mode declares that this entry point dynamically writes the FragDepth-decorated variable. Behavior is undefined if this mode is declared and an invocation does not write to FragDepth, or vice versa. Only valid with the Fragment Execution Model.
```
```
DepthUnchanged
Indicates that per-fragment tests may assume that any FragDepth built in-decorated value written by the shader is the same as the fragment’s interpolated depth value (given by the z component of the FragCoord built in-decorated variable). Other stages of the pipeline use the written value as normal. Only valid with the Fragment execution model.
```

**Comment by greg-lunarg** [comment]
@ilkkasaa Are you planning to submit a PR or shall I?

**Comment by greg-lunarg** [comment]
Never mind. I am submitting a PR.

**Comment by ilkkasaa** [comment]
Nice, thanks!
