### ISSUE TITLE
Can we add maximum number of uniform buffer or shader storage block bindings into glslang code ?

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2562]
Hi , @greg-lunarg @johnkslang 
    I have a question about here's why not include the maximum number of uniform buffer or shader storage block bindings into the  built-in constants. but i did find out some description at ogl4.5 spec and some cts test also test this feature. Is there any historical reason here?  if these constant is useful for gpu back-end , Can we add them ,just like truely built-in constants,  into glslang code ? thank you. 

**ogl4.5 spec :** chapter 4.4.5 Uniform and Shader Storage Block Layout Qualifiers
> If the binding point for any uniform or shader storage block instance is less than zero, or greater than or
> equal to the implementation-dependent maximum number of uniform buffer bindings, a compile-time
> error will occur. 

```
shader
ES31-CTS.functional.layout_binding.negative.ssbo.vertex_binding_over_max
layout(std140, binding = 8) buffer ColorBuffer0
{
       highp vec4 color1;
       highp vec4 color2;
} colors0;
```

**Comment by greg-lunarg** [comment]
It seems to me you are asking for something that is currently not in the GLSL spec or any of its extensions, especially the GL_KHR_vulkan_glsl extension.

If this is true, then please start by filing an issue against https://github.com/KhronosGroup/GLSL to have the spec augmented with your desired feature. (I believe this is the place to file issues against specific GLSL extensions. @gnl21 please correct if I am wrong.)

If this is not true and there is some part of GLSL or its extensions that we are not implementing, please point to the part of the spec we are missing and re-open.

**Comment by ZhiqianXia** [comment]
greg, thanks to your suggestion.

**Comment by ZhiqianXia** [comment]
@greg-lunarg 
Hi greg , i find the useful info for MaxUniformBufferBinding. Here is a MAX UNIFORM BUFFER BINDINGS value at spec glspec46 , which value is 84. This requirement wasn't writed into languge spec, but the feature was writed into glspec and  tested at CTS.  So i think it  is a default requirement, even though it wasn't listed at glsl spec. I think we should add the Max Uniform buffer binding feature into glslang. As for max ssbo binding, i did't find any support materials so far. But i think it is similar to MaxUniformBufferBinding.  Happy to hear any form of feedback from you! 

**shader** :
 **layout(binding=84, std140)  uniform uniform0_block {float uniform0_a; float uniform0_b; } ;**

**reference**:
https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.compatibility.pdf   page 804

**Comment by gnl21** [comment]
Hi @ZhiqianXia, could you clarify what you're asking for? Are you looking for a constant in the language, something like `gl_MaxUniformBufferBinding`, or a feature in glslang to allow you to vary the max uniform buffer binding to better represent implementations that your code might run on? Or something else?

**Comment by ZhiqianXia** [comment]
@gnl21, thanks to your quickly respond.  I'm looking a Built-In Constants just like gl_MaxUniformBufferBinding, which can make glslang report an exeed max binding error, when shader declare binding is 84. I didn't find similar Constants like gl_MaxUniformBufferBinding in glsl spec,  but i find a similar things in glspec.

**Comment by gnl21** [comment]
The GLSL spec currently says:
> If the binding point for any uniform or shader storage block instance is less than zero, or greater than or 
equal to the implementation-dependent maximum number of uniform buffer bindings, a compile-time 
error will occur.

so I think that glslang should be producing an error for this already. There's no built-in constant for shaders to read, but the limits are still checked by the language.

Because there will be many implementations of GLSL that have already shipped and do not include these constants we'd need an extension to actually expose the constants to shaders, and I don't really see a compelling use for one at the moment. I'm not against the principle, and it's the kind of thing that might be nice to clean up for consistency, but there doesn't seem much drive for it right now.
