### ISSUE TITLE
Image Operand Offset can only be used with OpImage*Gather operations

### ISSUE THREAD

**Issue by dmaluev** [KhronosGroup/glslang#2568]
Hello!
I've switched to SDK 1.2.170.0. And now I'm getting this warning.
Is it because I'm using offsets in Sample methods?
`t.SampleCmpLevelZero(s, tc, z, offset).r;`

**Comment by greg-lunarg** [comment]
Never mind. I found it. This message is coming from spirv-val, the SPIR-V validator. This new check was added in this release.

The rule is that Image Operand **non-constant** Offset can only be used with OpImage*Gather operations.

Please re-open if you have further questions.
