### ISSUE TITLE
sparseTextureGatherOffsetsARB supported by GL_ARB_sparse_texture2 should only take constant integer offsets

### ISSUE THREAD

**Issue by pmistryNV** [KhronosGroup/glslang#2580]
Presently Test cases spv.float16Fetch.frag and spv.sparseTexture.frag use non constant integral offsets which result in generation of ImageSparseDrefGather with ConstOffsets as "Image opreand" bit mask but non constant integer offsets.

As per GL_ARB_sparse_texture2 it clearly states

**Do a texture gather operation as in textureGatherOffset(), but return  texture access residency information from the function and the filtered  lookup result in the out parameter <texel>**

This means these offsets cannot be non constant. Hence this needs to be fixed in TParseContext::builtInOpCheck

**Comment by greg-lunarg** [comment]
Thank you for the bug report. Will you be submitting a fix?

**Comment by pmistryNV** [comment]
Yes I will submit a change for the same.

**Comment by greg-lunarg** [comment]
Fixed by #2590
