### ISSUE TITLE
CMake 2.8 can't generate makefiles

### ISSUE THREAD

**Issue by dmikis** [KhronosGroup/glslang#259]
2.8 is listed as minimum required version of CMake in all scripts, but `StandAlone/CMakeLists.txt` and `gtests/CMakeLists.txt` use `target_include_directories` which is 3.0 feature. I think, `cmake_minimum_required` commands should state 3.0 as minimum required version.

**Comment by antiagainst** [comment]
AFAICT, `target_include_directories()` is not a 3.0 feature; it is introduced at least in [2.8.12](https://cmake.org/cmake/help/v2.8.12/cmake.html#command:target_include_directories), which is [released on 8 Oct 2013](https://cmake.org/Wiki/CMake_Released_Versions). I'm not sure how extensively we want the backward compatibility to be; but I assume it's OK to bump the minimum version number to 2.8.12? What's your opinion, @johnkslang?

**Comment by dmikis** [comment]
You're absolutely right, it was my mistake. I'm using cmake 2.8.1 (still on Ubuntu Lucid), and it doesn't have this command. But there is no sense in supporting it, I'll just obtain newer CMake somehow. However, bumping minimum required to 2.8.12 may be appropriate.
