### ISSUE TITLE
Get uniform location generated by AutoMapLocations

### ISSUE THREAD

**Issue by codingoat** [KhronosGroup/glslang#2591]
I would like to compile GLSL code that does not contain explicit uniform locations into SPIR-V (`autoMapLocations=true`), then query the assigned locations using `program->getUniform(i).getType()->getQualifier().layoutLocation`, but it is always `4095`. When I use SPIRV-Cross to create GLSL code from the resulting SPIR-V binary, the generated code does not contain explicit uniform locations either. Why is this the case?

**Comment by greg-lunarg** [comment]
Please note that autoMapLocations only applies to input and output variables.

Please reopen if you have further questions.

**Comment by paroj** [comment]
> Please note that autoMapLocations only applies to input and output variables.

I got the impression that #1019 relaxed this to uniforms as well?
