### ISSUE TITLE
gl_SampleMask.length Method not be supported.

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2592]
Hi , @greg-lunarg 
   I found that glsang will output a error about gl_SampleMask.**length**() ,  
`error(loc, "", function->getName().c_str(), "array must be declared with a size before using this method");`
according to the spec description , gl_SampleMask is build-in output unsized-array variable at fragment shader. 
So I think maybe we should do some job for it at  **isRuntimeLength** function . Do you have any idea about that ?

``` 
if (length == 0) {
#ifndef GLSLANG_WEB
    if (intermNode->getAsSymbolNode() && isIoResizeArray(type))
        error(loc, "", function->getName().c_str(), "array must first be sized by a redeclaration or layout qualifier");
    else if (isRuntimeLength(*intermNode->getAsTyped())) {
        // Create a unary op and let the back end handle it
        return intermediate.addBuiltInFunctionCall(loc, EOpArrayLength, true, intermNode, TType(EbtInt));
    } else
#endif
        error(loc, "", function->getName().c_str(), "array must be declared with a size before using this method");
}
```

```
#version 320 es
layout(location = 0) out mediump vec4 fragColor;
void main (void)
{
       for (int i = 0; i < gl_SampleMask.length(); ++i)
              gl_SampleMask[i] = int(0xAAAAAAAA);
 
       fragColor = vec4(0.0, 1.0, 0.0, 1.0);
}
```

**Comment by greg-lunarg** [comment]
It seems to me that this is not a valid shader. More specifically, gl_SampleMask.length() is not a valid function call in this shader.

The GLSL spec says:

> This array [gl_SampleMask] must be sized in the fragment shader either implicitly or explicitly, to be
> no larger than the implementation-dependent maximum sample-mask (as an array of 32bit
> elements), determined by the maximum number of samples.

In section Arrays 4.1.9, it says this about explicitly sizing arrays:

> When an array size is specified in a declaration, it must be an
> integral constant expression [...] greater than zero. Except for the last
> declared member of a shader storage block [...] the size of an array
> must be declared (explicitly sized) before it is indexed with anything other than a constant integral
> expression.

It says this about implicitly sizing arrays:

> It is legal to declare an array without a
> size (unsized) and then later redeclare the same name as an array of the same type and specify a
> size, or index it only with constant integral expressions (implicitly sized). 

This shader does not size gl_SampleMask explicitly. Thus it cannot be indexed with anything
other than a constant integral. So this shader is invalid.

Even if the loop did not index gl_SampleMask, taking the length of an implicitly sized arrays violates the spec. Also from 4.19:

> The length() method cannot be called on an array that is not runtime sized and also has not yet
> been explicitly sized; this results in a compile-time error.

As you can see, the rules that show this is not valid are in plain sight in the spec and can be found with some searching. Unlike my predecessor, I don't have the entire spec and code base in my head :) so it takes time for me to research these questions. In the future, please make sure that something is truly a bug before reporting. Thanks!

If you believe my analysis to be in error, please feel free to re-open.

**Comment by ZhiqianXia** [comment]
Hi Gerg,
     I think your analysis is great, but there may be an exception.  **"This array [gl_SampleMask] must be sized in the fragment shader either implicitly or explicitly "**  is right , but  we have to noticed that gl_SampleMask is a build-in variable. This special variable do not declare like common arrray. In fact, We use **gl_NumSamples** to declare gl_SampleMask. (I get the info from reference 1) .  

**reference**
1. https://www.khronos.org/registry/OpenGL/extensions/OES/OES_sample_variables.txt
2. [oes320](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf) ch 7.1.5

**Comment by greg-lunarg** [comment]
I am sorry, but I am not sure what you are asking. If you have a shader which you believe glslangValidator is not correctly handling, please post it here with a description of the incorrect behavior. Thanks!

By my understanding, gl_NumSamples cannot be used for an array size since an array size must be a constant and gl_NumSamples is a uniform variable.

**Comment by ZhiqianXia** [comment]
I'm Sorry , i have a typo at last commit.

We use **gl_MaxSamples** to declare gl_SampleMask.

```
out highp    int  gl_SampleMask[(gl_MaxSamples+31)/32];
const mediump int gl_MaxSamples = 4;
```

**Comment by ZhiqianXia** [comment]
@greg-lunarg There is TBuiltInResource structure , it have a member named maxSamples. the length of gl_SampleMask can depend on it.
