### ISSUE TITLE
Checking for supported subgroup operations

### ISSUE THREAD

**Issue by BastiaanOlij** [KhronosGroup/glslang#2594]
Hey all,

Sorry if this is not the right place to ask a question but we're kind of stuck on this and don't know where these discussions are normally held.

We've run into a snag running Godot on mobile hardware that does support Vulkan 1.1/SpirV 1.3 but has limited support for subgroups. While we thought we were doing the right thing in switching to fallback logic if support is not there it does not seem to work.

Is this information even available in GLSLang or is the expectation that we supply different shaders based on checking `VkPhysicalDeviceSubgroupProperties` ourselves?

We were hoping to be able to do something like:
```
#if defined(GL_KHR_shader_subgroup_ballot)
#extension GL_KHR_shader_subgroup_ballot : enable

.. do our stuff ...
#else
.. do our fallback stuff ...
#endif
```

Thanks,

Bastiaan Olij
Godot Engine

**Comment by greg-lunarg** [comment]
In general, I believe there is a slack channel for Vulkan, and that is often the best place for getting your questions out in front of many eyeballs. Only problem is I am not sure how to get on that channel. I will try to get you information.

On this topic, I am willing to tell you what I know.

In general, glslang, as an offline compiler, does not have information on what features are available on a platform at runtime.

There have been previous attempts to introduce a "pre-processing" capability in SPIR-V, but at the moment, one does not exist.

If you were willing to do your SPIR-V generation at run-time, then you could do something similar to what you are attempting above, utilizing glslang's pre-processing capabilities, but you would create your own macro definition to query and define it from the glslang command if conditions warranted.

At the moment I think that encompasses all of your options.

Feel free to re-open if you have follow-up questions.

**Comment by BastiaanOlij** [comment]
Thanks Greg! Would love to join the Vulkan slack channel, does sounds like a better place to ask these types of questions :)

**Comment by greg-lunarg** [comment]
Vulkan Slack access:

1. Go to Khronos.org
2. Select Vulkan
3. Now he is on the Vulkan landing page
4. Scroll down till he sees “Vulkan slack” . That link goes to the slack channel
