### ISSUE TITLE
"float a[];float b = float(a)" fails an assertion in Types.h through glslangValidator

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#26]
The input `float a[];float b = float(a)` (casting from an array with no explicit size) causes glslangValidator to fail an assertion (`isExplicitlySizedArray()`) and abort through libc instead of printing an error.

**Comment by xorgy** [comment]
This works with other explicit type conversions as well({vec,mat}{2..4} etc.).

**Comment by xorgy** [comment]
`int i=int[]()` is another way to hit this.

**Comment by johnkslang** [comment]
Commit efb84617222a9b76e029ba7e784f274af8df109d fixes this.
