### ISSUE TITLE
glslang ast not right for findMSB with uint and int 

### ISSUE THREAD

**Issue by chuxin12345** [KhronosGroup/glslang#2610]
Hi, I use glslang to genrate the opengl ast and found below issue for findMSB func.

eg. a vert shader with 430 core

#version 430 core

layout(binding = 0, std430) buffer Data {
    uvec4 inUvec4;
    ivec4 inIvec4;

    uvec4 outUvec4;
    ivec4 outIvec4;
};

void main()
{
	outIvec4.x = findMSB(inUvec4.x); // **it should gen "findMSB ( global uint)"**
	outIvec4.y = findMSB(inIvec4.x);  //  **it should gen "findMSB ( global int)"**
}

and the glslang ast gen below:

glslangValidator.exe -i debug.vert
debug.vert
Shader version: 430
0:? Sequence
0:12  Function Definition: main( ( global void)
0:12    Function Parameters:
0:14    Sequence
0:14      move second child to first child ( temp int)
0:14        direct index ( temp int)
0:14          outIvec4: direct index for structure (layout( column_major std430 offset=48) buffer 4-component vector of int)
0:14            'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of uint inUvec4, layout( column_major std430 offset=16) buffer 4-component vector of int inIvec4, layout( column_major std430 offset=32) buffer 4-component vector of uint outUvec4, layout( column_major std430 offset=48) buffer 4-component vector of int outIvec4})
0:14            Constant:
0:14              3 (const uint)
0:14          Constant:
0:14            0 (const int)
0:14        findMSB ( global int)
0:14          direct index ( temp uint)
0:14            inUvec4: direct index for structure (layout( column_major std430 offset=0) buffer 4-component vector of uint)
0:14              'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of uint inUvec4, layout( column_major std430 offset=16) buffer 4-component vector of int inIvec4, layout( column_major std430 offset=32) buffer 4-component vector of uint outUvec4, layout( column_major std430 offset=48) buffer 4-component vector of int outIvec4})
0:14              Constant:
0:14                0 (const uint)
0:14            Constant:
0:14              0 (const int)
0:15      move second child to first child ( temp int)
0:15        direct index ( temp int)
0:15          outIvec4: direct index for structure (layout( column_major std430 offset=48) buffer 4-component vector of int)
0:15            'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of uint inUvec4, layout( column_major std430 offset=16) buffer 4-component vector of int inIvec4, layout( column_major std430 offset=32) buffer 4-component vector of uint outUvec4, layout( column_major std430 offset=48) buffer 4-component vector of int outIvec4})
0:15            Constant:
0:15              3 (const uint)
0:15          Constant:
0:15            1 (const int)
0:15        findMSB ( global int)
0:15          direct index ( temp int)
0:15            inIvec4: direct index for structure (layout( column_major std430 offset=16) buffer 4-component vector of int)
0:15              'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of uint inUvec4, layout( column_major std430 offset=16) buffer 4-component vector of int inIvec4, layout( column_major std430 offset=32) buffer 4-component vector of uint outUvec4, layout( column_major std430 offset=48) buffer 4-component vector of int outIvec4})
0:15              Constant:
0:15                1 (const uint)
0:15            Constant:
0:15              0 (const int)
0:?   Linker Objects
0:?     'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of uint inUvec4, layout( column_major std430 offset=16) buffer 4-component vector of int inIvec4, layout( column_major std430 offset=32) buffer 4-component vector of uint outUvec4, layout( column_major std430 offset=48) buffer 4-component vector of int outIvec4})
0:?     'gl_VertexID' ( gl_VertexId int VertexId)
0:?     'gl_InstanceID' ( gl_InstanceId int InstanceId)

please check and fix, thx~

**Comment by greg-lunarg** [comment]
I believe you are misreading the AST output, although I would admit that it is a little deceptive.

In the line:

`0:14 findMSB ( global int)`

`global int` refers to the **result** of the findMSB operation, NOT the operand.

To prove this, consider the following similar shader:

```
#version 430 core

layout(binding = 0, std430) buffer Data {
   vec4  inFvec4;
   ivec4 outIvec4;
};

void main()
{
   outIvec4.x = floatBitsToInt(inFvec4.x);
}
```

Now look at the AST output:

```
t2.frag
Shader version: 430
0:? Sequence
0:8  Function Definition: main( ( global void)
0:8    Function Parameters:
0:10    Sequence
0:10      move second child to first child ( temp int)
0:10        direct index ( temp int)
0:10          outIvec4: direct index for structure (layout( column_major std430 offset=16) buffer 4-component vector of int)
0:10            'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of float inFvec4, layout( column_major std430 offset=16) buffer 4-component vector of int outIvec4})
0:10            Constant:
0:10              1 (const uint)
0:10          Constant:
0:10            0 (const int)
0:10        floatBitsToInt ( global int)
0:10          direct index ( temp float)
0:10            inFvec4: direct index for structure (layout( column_major std430 offset=0) buffer 4-component vector of float)
0:10              'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of float inFvec4, layout( column_major std430 offset=16) buffer 4-component vector of int outIvec4})
0:10              Constant:
0:10                0 (const uint)
0:10            Constant:
0:10              0 (const int)
0:?   Linker Objects
0:?     'anon@0' (layout( binding=0 column_major std430) buffer block{layout( column_major std430 offset=0) buffer 4-component vector of float inFvec4, layout( column_major std430 offset=16) buffer 4-component vector of int outIvec4})
```

Notice the line:

`0:10        floatBitsToInt ( global int)`

As you know, int is the result, float is the operand.

I inspected the original AST with the debugger and the node for the findMSB call was correct.

Please re-open if you find a problem with my analysis.

**Comment by chuxin12345** [comment]
ok, warm reply, thx~
