### ISSUE TITLE
Feature Request: Expose option to combine textures and samplers to the StandAlone Application

### ISSUE THREAD

**Issue by Rob2309** [KhronosGroup/glslang#2611]
In #591 the functionality to automatically combine HLSL Texture*D and SamplerState objects was implemented. Since then, this functionality was not exposed to the StandAlone Application via any argument. Exposing it would simplify creating HLSL -> Vulkan shaders a lot for me, since I wouldn't need to write an own Application that uses the glslang lib anymore.

**Comment by greg-lunarg** [comment]
I am open to this, although I don't have the funding to implement it right now. I would welcome an implementing PR.

I would prefer the option to be --hlsl-sampled-textures, or something similar. Should ideally start with --hlsl.
