### ISSUE TITLE
'gl_VertexID' : undeclared identifier

### ISSUE THREAD

**Issue by sergorl** [KhronosGroup/glslang#2615]
I have `GL_version = 3.1.0 - Build 27.20.100.8984` and I see that OpenGL 3.1 supports 140 version of GLSL from this https://en.wikipedia.org/wiki/OpenGL_Shading_Language

Also I see that `gl_VertexID` is supported by GLSL 140 from this https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_VertexID.xhtml

But this shader:

```c
attribute vec3 coord3d;
attribute vec3 v_color;
uniform mat4 mvp;
varying vec3 f_color;

void main(void) {
	gl_Position = mvp * vec4(coord3d, 1.0);
	f_color = v_color;
  
    
	if (gl_VertexID == 0 || 
		gl_VertexID == 1 ||
		gl_VertexID == 2 ||
		gl_VertexID == 3 ||
		gl_VertexID == 4 ||
		gl_VertexID == 5)
	{
		f_color = vec4(1.0, 0.0, 0.0, 1.0);
	}
}

```
gives me:

```
ERROR: ERROR: 2:13: 'gl_VertexID' : undeclared identifier
```

Why does it happen? How can I fix it?

**Comment by greg-lunarg** [comment]
You do not have a #version 140 line in your shader. Without this the compiler assumes #version 110 which I believe does not define gl_VertexID.

Please re-open if my analysis is erroneous.
