### ISSUE TITLE
'gl_VertexID' : undeclared identifier for GLSL 140

### ISSUE THREAD

**Issue by sergorl** [KhronosGroup/glslang#2617]
I have `GL_version = 3.1.0 - Build 27.20.100.8984` and I see that OpenGL 3.1 supports 140 version of GLSL from this https://en.wikipedia.org/wiki/OpenGL_Shading_Language

Also I see that `gl_VertexID` is supported by GLSL 140 from this https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_VertexID.xhtml

But this shader:

```c
attribute vec3 coord3d;
attribute vec3 v_color;
uniform mat4 mvp;
varying vec3 f_color;

void main(void) {
	gl_Position = mvp * vec4(coord3d, 1.0);
	f_color = v_color;
  
    
	if (gl_VertexID == 0 || 
		gl_VertexID == 1 ||
		gl_VertexID == 2 ||
		gl_VertexID == 3 ||
		gl_VertexID == 4 ||
		gl_VertexID == 5)
	{
		f_color = vec4(1.0, 0.0, 0.0, 1.0);
	}
}

```
gives me:

```
ERROR: ERROR: 2:13: 'gl_VertexID' : undeclared identifier
```

Why does it happen? How can I fix it?

Also including `#version 140`

```c

#version 140

attribute vec3 coord3d;
attribute vec3 v_color;
uniform mat4 mvp;
varying vec3 f_color;

void main(void) {
	gl_Position = mvp * vec4(coord3d, 1.0);
	f_color = v_color;
  
    
	if (gl_VertexID == 0 || 
		gl_VertexID == 1 ||
		gl_VertexID == 2 ||
		gl_VertexID == 3 ||
		gl_VertexID == 4 ||
		gl_VertexID == 5)
	{
		f_color = vec4(1.0, 0.0, 0.0, 1.0);
	}
}

```
gives me:

`ERROR: D:\repositories\activePen\activePen\shaders\cube.v.glsl:
ERROR: ERROR: 2:2: '' : syntax error: #version must come before any other token`

**Comment by greg-lunarg** [comment]
When I cut and paste the shader above into file t.vert and execute

`$ /cygdrive/c/Users/Greg/dev/glslang/build/StandAlone/Release/glslangValidator.exe t.vert`

I get:

```
t.vert
WARNING: 0:4: attribute deprecated in version 130; may be removed in future release
WARNING: 0:5: attribute deprecated in version 130; may be removed in future release
WARNING: 0:7: varying deprecated in version 130; may be removed in future release
ERROR: 0:21: 'assign' :  cannot convert from ' const 4-component vector of float' to ' smooth out 3-component vector of float'
ERROR: 0:21: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

I suspect you have a hidden non-whitespace character in your file. Cut and paste the text above into a new file and try again.

Please comment if my analysis is incorrect and I will reopen.
