### ISSUE TITLE
glslang compiler error for #extension EXT_gpu_shader4 : require   

### ISSUE THREAD

**Issue by chuxin12345** [KhronosGroup/glslang#2635]
Hi, 
Below vertex shader meet compiler error:

#version 120   
#extension EXT_gpu_shader4 : require    

varying vec3 eyeNormal;
varying vec3 eyePosition;

void main() {  
    vec4 vertex;    
    vec3 normal;    

    vertex = gl_Vertex;  
    normal = gl_Normal;  

    // Transform the position 
    gl_Position = gl_ModelViewProjectionMatrix * vertex;    

    // Transform the normal for per-pixel lighting
    eyeNormal = gl_NormalMatrix * normal;
    
    // Transform the position to eye-space
    eyePosition = (gl_ModelViewMatrix * gl_Vertex).xyz;  
}

ERROR: 0:2: '#extension' : extension not supported: EXT_gpu_shader4
ERROR: 0:2: '#extension' : extra tokens -- expected newline
ERROR: 0:2: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.

Besides, if note the "#extension EXT_gpu_shader4 : require" and the shader can compiler success.

**Comment by greg-lunarg** [comment]
It appears that entire gpu_shader4 extension was subsumed into the core spec, so, as you noticed, the #extension statement is not needed.

Since glslangValidator is not obligated to accept EXT extension statements, I do not consider this a bug. Please re-open if you disagree with my analysis.

**Comment by chuxin12345** [comment]
Hi, 

yes, but some shader still can't work, consider below vertex shader:

#version 120                                                     
#extension EXT_gpu_shader4 : require                             
 
// samplers used as the vertex and normal source                                             
uniform samplerBuffer vertexSampler;
uniform samplerBuffer normalSampler;
                                          
varying vec3 eyeNormal;
varying vec3 eyePosition;
                                                 
void main() {                                    
    vec4 vertex;                            
    vec3 normal;                               

    //                                                                 
    // Fetch the vertex components
    //
    
    // First, scale the vertex index by three, because each component is stored separately
    int offset = int(gl_Vertex.x);
    
    // Fetch x, y, and z
    vertex = texelFetchBuffer( vertexSampler, offset);
    //vertex.x = texelFetchBuffer( vertexSampler, offset).x;       
    //vertex.y = texelFetchBuffer( vertexSampler, offset + 1).x;   
    //vertex.z = texelFetchBuffer( vertexSampler, offset + 2).x;   
    //vertex.w = 1.0;                                              
    
    //
    // Fetch the normal components
    //
                 
    // Scale by 3, since the components are stored separately                               
    offset = int(gl_Vertex.y);
    
    // Fetch x, y, and z
    normal = texelFetchBuffer( normalSampler, offset).xyz;
    //normal.x = texelFetchBuffer( normalSampler, offset).x;       
    //normal.y = texelFetchBuffer( normalSampler, offset + 1).x;   
    //normal.z = texelFetchBuffer( normalSampler, offset + 2).x;   
                                                 
    // Transform the position        
    gl_Position = gl_ModelViewProjectionMatrix * vertex;         
                              
    // Transform the normal for per-pixel lighting               
    eyeNormal = gl_NormalMatrix * normal;
    
    // Transform the vertex to eye-space for lighting
    eyePosition = (gl_ModelViewMatrix * vertex).xyz;
}


it can't solved by glslang, please help to confirm.
Thx~
