### ISSUE TITLE
[SPIR-V] Dubious std430 packing in certain cases

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#264]
Here's a shader which is testing packing in certain cases:

```
#version 310 es
layout(local_size_x = 1) in;

struct S0
{
   vec3 a[1];
   float b;
};

struct Content
{
   S0 m0;
   float m1;
};

layout(binding = 1, std430) buffer SSBO1
{
   Content content;
} ssbo_430;

layout(binding = 0, std140) buffer SSBO0
{
   Content content;
} ssbo_140;

void main()
{
   ssbo_430.content = ssbo_140.content;
}
```

Which gives
```
                              Decorate 10 ArrayStride 16
                              MemberDecorate 11(S0) 0 Offset 0
                              MemberDecorate 11(S0) 1 Offset 16
                              MemberDecorate 12(Content) 0 Offset 0
                              MemberDecorate 12(Content) 1 Offset 32
                              MemberDecorate 13(SSBO1) 0 Offset 0
                              Decorate 13(SSBO1) BufferBlock
                              Decorate 15(ssbo_430) DescriptorSet 0
                              Decorate 15(ssbo_430) Binding 1
                              Decorate 18 ArrayStride 16
                              MemberDecorate 19(S0) 0 Offset 0
                              MemberDecorate 19(S0) 1 Offset 16
                              MemberDecorate 20(Content) 0 Offset 0
                              MemberDecorate 20(Content) 1 Offset 32
                              MemberDecorate 21(SSBO0) 0 Offset 0
                              Decorate 21(SSBO0) BufferBlock
                              Decorate 23(ssbo_140) DescriptorSet 0
                              Decorate 23(ssbo_140) Binding 0
```
The offset of 32 here for the second float member m1 seems off, it seems like the second float is aligned to 16 bytes for some reason. Is this according to std430/std140 spec? I can't find anything that would explain this alignment at least.

**Comment by yavn** [comment]
This is a very interesting report, actually. The behavior seems to be correct to me, but nevertheless may require a slight clarification in the Vulkan spec. But first things first.

The rules for laying out buffers can be found in OpenGL spec (OpenGL 4.5, ch. 7.6.2.2 *Standard Uniform Block Layout*), and in Vulkan spec (ch. 14.5.4 *Offset and Stride Assignment*).

The interesting bit that explains Offset 32 on `m1` member is here (from OpenGL spec, emphasis is mine):

> 9 . If the member is a structure, the base alignment of the structure is N, where
N is the largest base alignment value of any of its members, and rounded
up to the base alignment of a vec4. The individual members of this sub-
structure are then assigned offsets by applying this set of rules recursively,
where the base offset of the first member of the sub-structure is equal to the
aligned offset of the structure. **The structure may have padding at the end;
the base offset of the member following the sub-structure is rounded up to
the next multiple of the base alignment of the structure.**

The base alignment of `S0` is 16, so the float that comes after `m0` has to be aligned to the multiple of 16, i.e. 32 (size of `S0` is 20). Whether the layout is std140 or std430 makes no difference in this particular example.

Now the part that caught my attention is that the Vulkan spec is missing the rule about "the following member", which applies to the member after an array and after a structure. It is clearly stated that Vulkan rules correspond to std140 and std430, so maybe the spec should be amended to include these rules.

@johnkslang do you think this may be an issue with Vulkan spec?

**Comment by Themaister** [comment]
@yavn Ah, yes. That wording does indeed explain the results I'm getting.

**Comment by johnkslang** [comment]
Agreed with the above analysis, and that the Vulkan specification could use an additional rule to make it clear.  I'm transferring this issue to a merge request against the Vulkan specification.  Thanks.
