### ISSUE TITLE
glslang TShader parse() missing variable declaration

### ISSUE THREAD

**Issue by jinialadin1** [KhronosGroup/glslang#2675]
I tried to use `TShader.intermediate` 's treeRootNode for shader conversion.
But simple variable declaration has been missing. I tried to find the issue or cause of the trouble but I couldn't find.

```cpp
glslang::TShader shader(EShLanguage::EShLangVertex);
shader.setStringsWithLengths(&code, &codeSize, 1); //code -> vertex shader code
shader.setEnvInput(glslang::EShSourceGlsl, EShLanguage::EShLangVertex, glslang::EShClientNone, 0);
shader.setEnvClient(glslang::EShClientNone, (glslang::EShTargetClientVersion) 0);
shader.setEnvTarget(glslang::EShTargetNone, (glslang::EShTargetLanguageVersion) 0);
EShMessages parseMessages = (EShMessages)(EShMsgDefault);

if (false == shader.parse(defaultTBuiltInResource, 300, false, parseMessages))
```

below is vertex shader code
```hlsl
#version 300 es
vec4 a_PositionLS;
vec3 a_NormalLS;

   ...

void main()
{
    vec3 _lvs_vertex = vec3(a_PositionLS);
    vec4 _lvs_position;
    vec3 _lvs_normal = normalize(a_NormalLS);
   ...
    gl_Position = _lvs_position; //it really used. not a trash variable
```

![image](https://user-images.githubusercontent.com/16120321/123782693-8f312980-d910-11eb-9ac4-081cd556cb83.png)

<details><summary>In TEXT</summary>
<p>

[0]	0x0000012692658048 {sequence={ size=1 } qualifier={ size=0 } name="" ...}	TIntermNode * {glslang::TIntermAggregate}
[glslang::TIntermAggregate]	{sequence={ size=1 } qualifier={ size=0 } name="" ...}	glslang::TIntermAggregate
glslang::TIntermOperator	{op=EOpSequence (1) operationPrecision=EpqNone (0) }	glslang::TIntermOperator
sequence	{ size=1 }	glslang::TVector<TIntermNode *>
[capacity]	1	__int64
[allocator]	{allocator={pageSize=8192 alignment=16 alignmentMask=15 ...} }	std::_Compressed_pair<glslang::pool_allocator<TIntermNode *>,std::_Vector_val<std::_Simple_types<TIntermNode *> >,0>
[0]	0x0000012692657eb8 {left=0x0000012692657d38 {id=896 flattenSubset=-1 name="_lvs_vertex" ...} right=0x0000012692657838 {...} }	TIntermNode * {glslang::TIntermBinary}
[glslang::TIntermBinary]	{left=0x0000012692657d38 {id=896 flattenSubset=-1 name="_lvs_vertex" ...} right=0x0000012692657838 {...} }	glslang::TIntermBinary
glslang::TIntermOperator	{op=EOpAssign (567) operationPrecision=EpqNone (0) }	glslang::TIntermOperator
left	0x0000012692657d38 {id=896 flattenSubset=-1 name="_lvs_vertex" ...}	glslang::TIntermTyped * {glslang::TIntermSymbol}
[glslang::TIntermSymbol]	{id=896 flattenSubset=-1 name="_lvs_vertex" ...}	glslang::TIntermSymbol
TIntermNode	{loc={name=0x0000000000000000 <NULL> string=0 line=80 ...} }	TIntermNode
type	{basicType=EbtFloat (1) vectorSize=3 matrixCols=0 ...}	glslang::TType
right	0x0000012692657838 {sequence={ size=1 } qualifier={ size=0 } name="" ...}	glslang::TIntermTyped * {glslang::TIntermAggregate}
[glslang::TIntermAggregate]	{sequence={ size=1 } qualifier={ size=0 } name="" ...}	glslang::TIntermAggregate
glslang::TIntermOperator	{op=EOpConstructVec3 (471) operationPrecision=EpqNone (0) }	glslang::TIntermOperator
sequence	{ size=1 }	glslang::TVector<TIntermNode *>
[capacity]	1	__int64
[allocator]	{allocator={pageSize=8192 alignment=16 alignmentMask=15 ...} }	std::_Compressed_pair<glslang::pool_allocator<TIntermNode *>,std::_Vector_val<std::_Simple_types<TIntermNode *> >,0>
[0]	0x0000012692657558 {id=854 flattenSubset=-1 name="a_PositionLS" ...}	TIntermNode * {glslang::TIntermSymbol}
[glslang::TIntermSymbol]	{id=854 flattenSubset=-1 name="a_PositionLS" ...}	glslang::TIntermSymbol
glslang::TIntermTyped	{type={basicType=EbtFloat (1) vectorSize=4 matrixCols=0 ...} }	glslang::TIntermTyped
id	854	int
flattenSubset	-1	int
name	"a_PositionLS"	std::basic_string<char,std::char_traits<char>,glslang::pool_allocator<char> >
constArray	{unionArray=0x0000000000000000 <NULL> }	glslang::TConstUnionArray
constSubtree	0x0000000000000000 <NULL>	glslang::TIntermTyped *
__vfptr	0x00007ff98d0b4898 {editor.dll!const glslang::TIntermSymbol::`vftable'} {0x00007ff98a6e3614 {editor.dll!TIntermNode::getLoc(void)const }, ...}	void * *
loc	{name=0x0000000000000000 <NULL> string=0 line=80 ...}	glslang::TSourceLoc
[Raw View]	{...}	glslang::TVector<TIntermNode *>
qualifier	{ size=0 }	glslang::TVector<enum glslang::TStorageQualifier>
name	""	std::basic_string<char,std::char_traits<char>,glslang::pool_allocator<char> >
userDefined	false	bool
optimize	true (205)	bool
debug	true (205)	bool
pragmaTable	0x0000000000000000 <NULL>	glslang::TPragmaTable *
TIntermNode	{loc={name=0x0000000000000000 <NULL> string=0 line=80 ...} }	TIntermNode
type	{basicType=EbtFloat (1) vectorSize=3 matrixCols=0 ...}	glslang::TType
__vfptr	0x00007ff98d0b4de8 {editor.dll!const glslang::TIntermBinary::`vftable'} {0x00007ff98a6e3614 {editor.dll!TIntermNode::getLoc(void)const }, ...}	void * *
loc	{name=0x0000000000000000 <NULL> string=0 line=80 ...}	glslang::TSourceLoc
[Raw View]	{...}	glslang::TVector<TIntermNode *>
qualifier	{ size=0 }	glslang::TVector<enum glslang::TStorageQualifier>
name	""	std::basic_string<char,std::char_traits<char>,glslang::pool_allocator<char> >
userDefined	false	bool
optimize	true (205)	bool
debug	true (205)	bool
pragmaTable	0x0000000000000000 <NULL>	glslang::TPragmaTable *
__vfptr	0x00007ff98d0b51a0 {editor.dll!const glslang::TIntermAggregate::`vftable'} {0x00007ff98a6e3614 {editor.dll!TIntermNode::getLoc(void)const }, ...}	void * *
loc	{name=0x0000000000000000 <NULL> string=0 line=80 ...}	glslang::TSourceLoc
[1]	0x0000012692651b28 {sequence={ size=1 } qualifier={ size=0 } name="" ...}	TIntermNode * {glslang::TIntermAggregate}
[glslang::TIntermAggregate]	{sequence={ size=1 } qualifier={ size=0 } name="" ...}	glslang::TIntermAggregate
glslang::TIntermOperator	{op=EOpSequence (1) operationPrecision=EpqNone (0) }	glslang::TIntermOperator
sequence	{ size=1 }	glslang::TVector<TIntermNode *>
[capacity]	1	__int64
[allocator]	{allocator={pageSize=8192 alignment=16 alignmentMask=15 ...} }	std::_Compressed_pair<glslang::pool_allocator<TIntermNode *>,std::_Vector_val<std::_Simple_types<TIntermNode *> >,0>
[0]	0x0000012692651a28 {left=0x00000126926518a8 {id=898 flattenSubset=-1 name="_lvs_normal" ...} right=0x0000012692651518 {...} }	TIntermNode * {glslang::TIntermBinary}
[glslang::TIntermBinary]	{left=0x00000126926518a8 {id=898 flattenSubset=-1 name="_lvs_normal" ...} right=0x0000012692651518 {...} }	glslang::TIntermBinary
glslang::TIntermOperator	{op=EOpAssign (567) operationPrecision=EpqNone (0) }	glslang::TIntermOperator
glslang::TIntermTyped	{type={basicType=EbtFloat (1) vectorSize=3 matrixCols=0 ...} }	glslang::TIntermTyped
op	EOpAssign (567)	glslang::TOperator
operationPrecision	EpqNone (0)	glslang::TPrecisionQualifier
left	0x00000126926518a8 {id=898 flattenSubset=-1 name="_lvs_normal" ...}	glslang::TIntermTyped * {glslang::TIntermSymbol}
[glslang::TIntermSymbol]	{id=898 flattenSubset=-1 name="_lvs_normal" ...}	glslang::TIntermSymbol
TIntermNode	{loc={name=0x0000000000000000 <NULL> string=0 line=87 ...} }	TIntermNode
type	{basicType=EbtFloat (1) vectorSize=3 matrixCols=0 ...}	glslang::TType
right	0x0000012692651518 {operand=0x0000012692650c38 {id=859 flattenSubset=-1 name="a_NormalLS" ...} }	glslang::TIntermTyped * {glslang::TIntermUnary}
[glslang::TIntermUnary]	{operand=0x0000012692650c38 {id=859 flattenSubset=-1 name="a_NormalLS" ...} }	glslang::TIntermUnary
glslang::TIntermOperator	{op=EOpNormalize (272) operationPrecision=EpqHigh (3) }	glslang::TIntermOperator
operand	0x0000012692650c38 {id=859 flattenSubset=-1 name="a_NormalLS" ...}	glslang::TIntermTyped * {glslang::TIntermSymbol}
[glslang::TIntermSymbol]	{id=859 flattenSubset=-1 name="a_NormalLS" ...}	glslang::TIntermSymbol
TIntermNode	{loc={name=0x0000000000000000 <NULL> string=0 line=87 ...} }	TIntermNode
type	{basicType=EbtFloat (1) vectorSize=3 matrixCols=0 ...}	glslang::TType
TIntermNode	{loc={name=0x0000000000000000 <NULL> string=0 line=87 ...} }	TIntermNode
type	{basicType=EbtFloat (1) vectorSize=3 matrixCols=0 ...}	glslang::TType
__vfptr	0x00007ff98d0b4de8 {editor.dll!const glslang::TIntermBinary::`vftable'} {0x00007ff98a6e3614 {editor.dll!TIntermNode::getLoc(void)const }, ...}	void * *
loc	{name=0x0000000000000000 <NULL> string=0 line=87 ...}	glslang::TSourceLoc
[Raw View]	{...}	glslang::TVector<TIntermNode *>
qualifier	{ size=0 }	glslang::TVector<enum glslang::TStorageQualifier>
name	""	std::basic_string<char,std::char_traits<char>,glslang::pool_allocator<char> >
userDefined	false	bool
optimize	true (205)	bool
debug	true (205)	bool
pragmaTable	0x0000000000000000 <NULL>	glslang::TPragmaTable *
__vfptr	0x00007ff98d0b51a0 {editor.dll!const glslang::TIntermAggregate::`vftable'} {0x00007ff98a6e3614 {editor.dll!TIntermNode::getLoc(void)const }, ...}	void * *
loc	{name=0x0000000000000000 <NULL> string=0 line=87 ...}	glslang::TSourceLoc

</p>
</details>

as you can see the `TInternNode[0]` and `TInternNode[1]`
just simple declaration without initializing **`vec4 _lvs_postion;`** has been missed.

Any idea to make that line survive? or is this kind of some option mistake?
Thank for your effort.

**Comment by greg-lunarg** [comment]
It seems that some optimization/pruning of the AST is occurring involving _lvs_position, likely because it is uninitialized. As such, while the AST is not an exact representation of the original shader, it seems that it can be considered at least functionally correct.

Since I don't see any incorrectness, I will close this. However, if you feel this shader is in some way functionally incorrect, please feel free to re-open.
