### ISSUE TITLE
cross compile domain shader failed

### ISSUE THREAD

**Issue by zhrit** [KhronosGroup/glslang#2676]
I am tring to cross compile a domain shader in hlsl to a post-tessellation vertex function in metal use glslang+spirv-cross

**Comment by zhrit** [comment]
This is part of my source  hlsl code, it works well:

struct VertexShaderInput
{
	float3 pos : POSITION;
	float3 color : COLOR0;
};

struct VertexShaderOutput
{
	float3 pos : POSITION;
	float3 color : COLOR0;
};

VertexShaderInput main(VertexShaderInput input)
{
	return input;
}

VertexShaderOutput VS(VertexShaderInput input)
{
	VertexShaderOutput output;
	output.pos = input.pos * 0.5555;
	output.color = input.color;
	return output;
}

struct PatchTess
{
	float EdgeTess[4] : SV_TessFactor;
	float InsideTess[2] : SV_InsideTessFactor;
};

PatchTess ConstantHS(InputPatch<VertexShaderInput, 4> patch, 
	uint patchID : SV_PrimitiveID)
{
	PatchTess pt;
	pt.EdgeTess[0] = 3; // Left edge
	pt.EdgeTess[1] = 3; // Top edge
	pt.EdgeTess[2] = 3; // Right edge
	pt.EdgeTess[3] = 3; // Bottom edge
	pt.InsideTess[0] = 3; // u-axis (columns)
	pt.InsideTess[1] = 3; // v-axis (rows)
	return pt;
}

struct HullShaderOut
{
	float3 PosL : POSITION;
	float3 color : COLOR0;
};

[domain("quad")]
[partitioning("integer")]
[outputtopology("triangle_cw")]
[outputcontrolpoints(4)]
[patchconstantfunc("ConstantHS")]
[maxtessfactor(64.0f)]
HullShaderOut HS(InputPatch<VertexShaderInput, 4> p, 
	uint i : SV_OutputControlPointID,
	uint patchId : SV_PrimitiveID)
{
	VertexShaderOutput vs_out = VS(p[i]);
	HullShaderOut hout;
	hout.PosL = vs_out.pos;
	hout.color = vs_out.color;
	return hout;
}

struct DomainOut
{
	float4 PosH : SV_POSITION;
};

[domain("quad")]
DomainOut DS(PatchTess patchTess,
	float2 uv : SV_DomainLocation,
	const OutputPatch<HullShaderOut, 4> quad)
{
	DomainOut dout;
	float3 v1 = lerp(quad[0].PosL, quad[1].PosL, uv.x);
	float3 v2 = lerp(quad[2].PosL, quad[3].PosL, uv.x);
	float3 p = lerp(v1, v2, uv.y);
	dout.PosH = float4(p, 1.0f);
	return dout;
}

float4 PS(DomainOut input) : SV_TARGET
{
	return float4(1.0, 1.0, 1.0, 1.0f);
}

After the cross compilation, I got the msl code below:
 
[[ patch(quad, 0) ]] vertex DS_out DS(DS_patchIn patchIn [[stage_in]], float2 gl_TessCoord [[position_in_patch]])
{
    DS_out out = {};
    out.gl_Position = float4(mix(mix(patchIn.gl_in[0].quad_PosL, patchIn.gl_in[1].quad_PosL, float3(float3(gl_TessCoord, 0).x)), mix(patchIn.gl_in[2].quad_PosL, patchIn.gl_in[3].quad_PosL, float3(float3(gl_TessCoord, 0).x)), float3(float3(gl_TessCoord, 0).y)), 1.0);
    return out;
}

It does not work, because "[[ patch(quad, 0) ]]" is wrong, it should be replaced with "[[ patch(quad, 4) ]]"

I dont know whether it is a bug of glslang or spirv-cross?  
Maybe I did something wrong.
Looking forward to your reply, thank you.

**Comment by greg-lunarg** [comment]
I think this problem is best dealt with by posting to spirv-cross. spirv-cross can then determine if the SPIR-V that is being generated by glslang is bad. I am going to close for now. Please re-open if it is determined if the SPIR-V that is being generated by glslang is bad.
