### ISSUE TITLE
how to turn these temporary variables output off when dump glslang to spv file?

### ISSUE THREAD

**Issue by mirocosphp** [KhronosGroup/glslang#2696]
![2021-07-17 17-47-48 的屏幕截图](https://user-images.githubusercontent.com/39593790/126033082-17d6410c-61a9-451b-aafe-d3a19cfa7beb.png)

how to cut these temporary variables like _93 _97 off?

**Comment by greg-lunarg** [comment]
This output appears to be from spirv-cross. If so, this issue is misplaced; please open an issue there. If not, please re-open with a description of how to recreate.
