### ISSUE TITLE
Segfault while parsing preprocessor arguments larger than 128 characters.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#27]
For example, 
``` GLSL
#if 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

Crashes `glslangValidator` with a segmentation fault.

**Comment by johnkslang** [comment]
For the original title "#extension...", this is fixed, it's a duplicate.

For the current report "#if...", I can't reproduce it, long tokens work correctly.  Is it still present for you?

Thanks.

**Comment by xorgy** [comment]
@johnkslang Looks like this is now also fixed, I think it was a different but related bug to something else you fixed.

**Comment by xorgy** [comment]
@johnkslang Looks like this is now also fixed, I think it was a different but related bug to something else you fixed, and it died along with it.
