### ISSUE TITLE
`layout(std430) uniform;` invalid even with `GL_EXT_scalar_block_layout`

### ISSUE THREAD

**Issue by francesca64** [KhronosGroup/glslang#2714]
It looks like `GL_EXT_scalar_block_layout` is checked when `std430` is used on uniform blocks: https://github.com/KhronosGroup/glslang/blob/fc9897d1ba419063a67b105ccf5a6364402a1ea7/glslang/MachineIndependent/ParseHelper.cpp#L8388

But there's a different check added in #2396 specifically for `layout(std430) uniform;` that unconditionally disallows it: https://github.com/KhronosGroup/glslang/blob/fc9897d1ba419063a67b105ccf5a6364402a1ea7/glslang/MachineIndependent/ParseHelper.cpp#L3664-L3666

The explanation even references [the same quotation that `GL_EXT_scalar_block_layout` removes](https://github.com/KhronosGroup/GLSL/blob/bce9ef1fa197b0f0b9357cf9db2afd000f76e4e2/extensions/ext/GL_EXT_scalar_block_layout.txt#L87-L89), so I'd assume `layout(std430) uniform;` should be allowed when `GL_EXT_scalar_block_layout` is used?

**Comment by greg-lunarg** [comment]
Agree. This should be allowed.

**Comment by greg-lunarg** [comment]
I have created a fix. I will submit it shortly.
