### ISSUE TITLE
glslangValidator formatting of warnings/errors not clickable from IDE

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/glslang#2717]
I tried switching our codebase over to use glslangValidator from shaderc, and that broke all of our warning/error clickthrough from IDE's such as Xcode.  I then noticed that shaderc reformats the warning/errors so that they are IDE friendly.  Fixing this would make working on large shader codebases much more pleasant.

**Comment by greg-lunarg** [comment]
Could you give an example of a good shaderc message and its unfriendly glslang counterpart?

**Comment by alecazam** [comment]
This is how shaderc reformats the errors that it gets back.   These are clickable when using absolute paths.  So now I have Xcode run our make file, that calls shaderc, and shaderc dumps these out to the Xcode IDE.  Then I can clickthrough to errors and warnings.   We're only using shaderc now, so I don't have a glslangValidator example.  

/Users/me/folder/Shaders/Sand.frag:8: error: '' :  syntax error, unexpected IDENTIFIER
1 error generated.

And this is a warning.  I think Xcode is producing the line/location off the warning
/Users/me/folder/Shaders/Intermediate/Sand.macos.vs.metal:130:7: warning: unused function 'Foo' [-Wunused-function]
float Foo(thread const float& v, thread const float& a, thread const float& b)

**Comment by arcady-lunarg** [comment]
I think there should be enough between #3467 and #3614 that you can pass the right options to get your clickable errors with the full path and the column number easily enough with the right options.
