### ISSUE TITLE
Invalid SPIR-V generated when assigning to swizzle from increment applied to swizzled matrix

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/glslang#2725]
The following shader generates invalid SPIR-V:

```c
#version 310 es

precision mediump float;

layout(location=0) in float zero;
layout(location=0) out vec4 color;

void main()
{
    vec4 v = vec4(zero);
    mat3 m = mat3(zero);
    v.wx += ++(m[1].yx);

    color = vec4(0, v.w, 0, 1);
}
```

Looking at the generated SPIR-V, glslang is attempting to compile the following code:

```c
v.wx += ++(m[1].yx);
```

To the following SPIR-V (written in GLSL form):

```c
temp1 = ++(m[1].yx);
temp2 = v.wx + temp1;
v = temp2.x;
v.x = temp2.y;
```

The first assignment back to `v` is missing `.w` which causes a SPIR-V validation error. The issue is that glslang is attempting to reuse the access chain it created to load `v`, instead of creating a new access chain for the specific component it's writing to. Looking at `Builder::accessChainStore`, I don't see anything obviously wrong.

The issue is not reproducible if the `++` is removed, or if the matrix is turned into a vector. So the bug is not an obvious one.

**Comment by y-novikov** [comment]
@jeremy-lunarg , #2702 is in regression range and seems related

**Comment by y-novikov** [comment]
"In regression range" as in: we've discovered this issue when rolling glslang into Chromium. See crbug.com/1238056

**Comment by greg-lunarg** [comment]
Yes, we have confirmed the regression. Thanks! A fix is in transit...

**Comment by y-novikov** [comment]
Thank you for the quick fix, I've confirmed that this fixes our WebGL test failure.
