### ISSUE TITLE
Stop assigning Location decorations to ray payloads and callable data

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#2736]
The SPIR-V spec says:
> **Location**
>
> Apply only to a variable or a structure-type member. *Location* is an unsigned 32-bit integer that forms the main linkage for Storage Class **Input** and **Output** variables:
> - between the client API and vertex-stage inputs,
> - between consecutive programmable stages, or
> - between fragment-stage outputs and the client API.
>
> It can also tag variables or structure-type members in the **UniformConstant** Storage Class for linkage with the client API.
>
> Only valid for the **Input**, **Output**, and **UniformConstant** Storage Classes.

The SPV_KHR_ray_tracing spec does not modify this language.  However, GLSLang (at least the version in the Vulkan CTS) currently passes through the location from GLSL which is used for matching ray payloads and callable data with the corresponding `traceRayEXT()` or `executeCallableEXT()` instruction.  This is a left-over from the old SPV_NV_ray_tracing extension which also did the matching via location numbers.  The KHR extension does the matching using actual pointers in **OpTraceRayKHR** or **OpExecuteCallableKHR**.

**Comment by greg-lunarg** [comment]
Do you have a shader that exhibits this behavior?

**Comment by jekstrand** [comment]
@djdeath should be able to help you out there.

**Comment by djdeath** [comment]
Hey @greg-lunarg, there are a bunch CTS raytracing tests reproducing this. Like `dEQP-VK.ray_tracing_pipeline.misc.cullmask_tri`.

**Comment by djdeath** [comment]
Most tests have this bit : 
```
layout(location = 0) rayPayloadInEXT      uint   dummy;
```

**Comment by greg-lunarg** [comment]
@dgkoch Could you please take a look or refer someone who can?

**Comment by greg-lunarg** [comment]
@dgkoch Ping :)

**Comment by dgkoch** [comment]
I've seen and trying to get someone to look at it.
