### ISSUE TITLE
Improvements to the core glsl language

### ISSUE THREAD

**Issue by Luke-Filewalker** [KhronosGroup/glslang#2742]
Are there plans to improve the glsl language. This could be from simple features like default parameters for functions, till more complex ones like interfaces/classes and/or templates? It seems to me that there was no progress made in this direction in the last couple of years. Features like these would make it much easier to write clean and compact code. If there is already an ongoing discussion, please refer me to it.

**Comment by greg-lunarg** [comment]
This really not a glslang issue. Please open an issue at https://github.com/KhronosGroup/GLSL
