### ISSUE TITLE
I was testing this further and this may be C++ phenomenon, maybe in too used to C, this behavior persists with public members, both inherited and not.

### ISSUE THREAD

**Issue by LaySoe** [KhronosGroup/glslang#2743]
I was testing this further and this may be C++ phenomenon, maybe in too used to C, this behavior persists with public members, both inherited and not.

Which still does not make it better, and it being undocumented is even worse

_Originally posted by @okawo80085 in https://github.com/ValveSoftware/openvr/issues/1583#issuecomment-907682024_

**Comment by greg-lunarg** [comment]
As far as I can tell, this is not reporting error against glslang, but rather some C++ compiler. I will therefore close.

**Comment by okawo80085** [comment]
Fine by me, the original issue is for OpenVR API, not glslang, no idea how it ended up here
