### ISSUE TITLE
glslangValidator mishandles do-while scope rules

### ISSUE THREAD

**Issue by ianromanick** [KhronosGroup/glslang#2744]
Page 45 of the GLSL 4.60.7 specification says:

> The body of a do-while loop introduces a new scope lasting only between the do and while (not including the while test 
expression), whether or not the body is simple or compound:

```
    int i = 17;
    do
        int i = 4; // okay, in nested scope_
    while (i == 0); // i is 17, scoped outside the do-while body
```

However, when trying to compile this very code from the specification, `glslangValidator` produces a compilation error:

```
$ ./install/bin/glslangValidator /tmp/page-45.frag 
/tmp/page-45.frag
ERROR: 0:6: 'i' : redefinition 
ERROR: 0:6: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```

I discovered this while discussing another related issue in Mesa in https://gitlab.freedesktop.org/mesa/piglit/-/merge_requests/569.  As far as I can tell, NVIDIA closed-source drivers correctly compile this code.

**Comment by greg-lunarg** [comment]
Agree this is a bug.

If anyone decides to work on a solution, please post here to avoid duplicated effort.
