### ISSUE TITLE
TShader::parse and TShader::preprocess potentially leak TPoolAllocator

### ISSUE THREAD

**Issue by Slagh** [KhronosGroup/glslang#275]
Calling preprocess(...) then parse(...) on the same instance will leak a TPoolAllocator since it unconditionally replaces the member pointer 'pool'.

**Comment by johnkslang** [comment]
@AWoloszyn Does this interact with what you were investigating?

**Comment by johnkslang** [comment]
This leak is fixed by recent "Memory... " commits that have each object install it's own pool, which it will also later destroy (as long as the containing object is destroyed).
