### ISSUE TITLE
Incomplete cmake find_package support

### ISSUE THREAD

**Issue by rhabacker** [KhronosGroup/glslang#2751]
According to https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#libraries-providing-config-file-packages, libraries that want to support cmake find_package() in configuration mode must install a set of files as shown for the VulkanSceneGraph package.  

```
/usr/lib64/cmake/vsg/vsgConfig.cmake
/usr/lib64/cmake/vsg/vsgConfigVersion.cmake
/usr/lib64/cmake/vsg/vsgTargets-relwithdebinfo.cmake
/usr/lib64/cmake/vsg/vsgTargets.cmake
```
Once these files are installed, the vsg library can be added as a dependency to a package with cmake support by using 
```
find_package(vsg)
``` 
to a CMakeLists.txt file.

A look into the installed files of the glslang package (see for example at [openSUSE](https://build.opensuse.org/package/show/openSUSE%3AFactory/glslang)
```
/usr/lib64/cmake/HLSLTargets-relwithdebinfo.cmake
/usr/lib64/cmake/HLSLTargets.cmake
/usr/lib64/cmake/OGLCompilerTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OGLCompilerTargets.cmake
/usr/lib64/cmake/OSDependentTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OSDependentTargets.cmake
/usr/lib64/cmake/SPIRVTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRVTargets.cmake
/usr/lib64/cmake/SPVRemapperTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPVRemapperTargets.cmake
/usr/lib64/cmake/glslang-default-resource-limitsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/glslang-default-resource-limitsTargets.cmake
/usr/lib64/cmake/glslangTargets-relwithdebinfo.cmake
/usr/lib64/cmake/glslangTargets.cmake
/usr/lib64/cmake/glslangValidatorTargets-relwithdebinfo.cmake
/usr/lib64/cmake/glslangValidatorTargets.cmake
/usr/lib64/cmake/spirv-remapTargets-relwithdebinfo.cmake
/usr/lib64/cmake/spirv-remapTargets.cmake
```
shows that there are no `*Config.cmake` and *Version.cmake` files. 

For example, trying to use the `glslang` package with 
```
find_package(glslang) 
```
will not find this package. Similar happens with the other provided packages `SPIRV`, `HLSL`, etc.

This problem has been currently documented on https://github.com/vsg-dev/VulkanSceneGraph/issues/322#issuecomment-915160228.

**Comment by greg-lunarg** [comment]
I am open to this improvement but do not have the resources to address it in the near future. If someone wishes to create such a change, please leave a comment to avoid duplicate effort.

**Comment by ncesario-lunarg** [comment]
@rhabacker Is this still an issue? `find_package(glslang)` seems to work for me as expected on linux (testing with cmake 3.26.4).

**Comment by rhabacker** [comment]
The mentioned pr #2989 fixed this issue.
