### ISSUE TITLE
Compiler warnings for unreachable code

### ISSUE THREAD

**Issue by stuartcarnie** [KhronosGroup/glslang#2763]
In both the following case statements, it is unclear if the `addExtension` and `addCapability` APIs should be called and whether there is a bug present because they are not:

https://github.com/KhronosGroup/glslang/blob/0f886fe7d3c05c4292fb338c6bf1c75912af9439/SPIRV/GlslangToSpv.cpp#L3943-L3948

**Comment by greg-lunarg** [comment]
Yes, thanks. I think this code is meant to be live. It also looks like the wrong capabilities as well. A bit of a cut-and-paste-and-edit that didn't get edited.
