### ISSUE TITLE
glslang not emitting LogicalAnd for uniforms inside a uniform block

### ISSUE THREAD

**Issue by BartmanAbyss** [KhronosGroup/glslang#2765]
Even with the latest commit, glslang only generates LogicalAnd in SpirV for comparisons of non-block uniforms. With comparisons of uniforms in blocks this generates very unreadable code. See attached files
Used command line: 
```
glslangValidator.exe -H --target-env opengl good.vert >good.spirv
glslangValidator.exe -H --target-env opengl bad.vert >bad.spirv
```
[bad.spirv](https://github.com/KhronosGroup/glslang/files/7206172/bad.spirv.txt)
[bad.vert](https://github.com/KhronosGroup/glslang/files/7206173/bad.vert.txt)
[good.spirv](https://github.com/KhronosGroup/glslang/files/7206174/good.spirv.txt)
[good.vert](https://github.com/KhronosGroup/glslang/files/7206175/good.vert.txt)

When running the SPV through SPIRV-Cross this results in
```
bool _17 = UC != 0;
bool _26;
if (_17)
    _26 = UB == 2.0f;
else
    _26 = _17;
if (_26)
```
instead of
`if ((UC != 0) && (UB == 2.0f))`

I would be willing to take a look at that myself if I got some pointers on where to look...

**Comment by greg-lunarg** [comment]
Pretty sure this cannot be changed.

In good.vert, UB and UC are allocated in SPIR-V UniformConstant storage. These are always guaranteed to be allocated (in Vulkan) and so they are always safe to load.

In bad.vert, UB and UC are allocated in SPIR-V Uniform storage. These variables may be not be fully allocated (in Vulkan), so it is not always safe to load them.

The conditional if ((UC != 0) && (UB == 2.0f)) is a short-circuit conditional, that is, the second term of the && is only evaluated if the first is true. So the load of UB is only safe if UC != 0. That is why the evaluation of UB == 2.0f is kept under the conditional.

Now, the allocation rules for Uniform and UniformConstant above are true for Vulkan, but I am not sure if they are true for OpenGL. If you can find documentation that guarantees Uniform is always fully allocated for OpenGL, then we can generate the "good" SPIR-V for bad.vert.

In the meantime, I will close this. Please comment on this issue if you find such documentation, and I will re-open.
