### ISSUE TITLE
GLSLANG fails on SHARED mode compilation of FFMPEG. 

### ISSUE THREAD

**Issue by vivazkote** [KhronosGroup/glslang#2769]
Hello!
GLSLANG fails on SHARED mode compilation of FFMPEG. (while STATIC compilation is good.)
Also, on 19 september I have good build, so maybe some fail happend after this date?

```
LD	libavfilter/avfilter-8.dll
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x4e): undefined reference to `glslang::TShader::TShader(EShLanguage)'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x82): undefined reference to `glslang::TShader::setStrings(char const* const*, int)'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0xc9): undefined reference to `glslang::TShader::parse(TBuiltInResource const*, int, EProfile, bool, bool, EShMessages, glslang::TShader::Includer&)'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0xe9): undefined reference to `glslang::TProgram::TProgram()'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x12a): undefined reference to `glslang::TProgram::link(EShMessages)'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x17f): undefined reference to `glslang::GlslangToSpv(glslang::TIntermediate const&, std::vector<unsigned int, std::allocator<unsigned int> >&, spv::SpvBuildLogger*, glslang::SpvOptions*)'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x1d3): undefined reference to `glslang::TProgram::getInfoLog()'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x203): undefined reference to `glslang::TShader::getInfoLog()'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x2c1): undefined reference to `glslang::InitializeProcess()'
ld.exe: libavfilter/glslang.o:glslang.cpp:(.text+0x309): undefined reference to `glslang::FinalizeProcess()'
collect2.exe: error: ld returned 1 exit status
```

**Comment by greg-lunarg** [comment]
19 September 2021?

**Comment by vivazkote** [comment]
Yees. In 19 I did successful build of ffmpeg as Shared. Yesterday tried again and failed.

**Comment by greg-lunarg** [comment]
I am not aware of any changes in the last month to glslang that would have changed this. What was the last commit hash that you are certain worked for you? Perhaps it was older than September 19?

**Comment by greg-lunarg** [comment]
About a year ago two new libraries were added: GenericCodeGen.lib and MachineIndependent.lib. Perhaps those are not being included in the Shared build.

**Comment by vivazkote** [comment]
well, can't tell. Only day is 19Sept. Or I can send you binaries. probably useless??

**Comment by greg-lunarg** [comment]
Don't send binaries.

**Comment by greg-lunarg** [comment]
At the moment glslang is not supporting a shared build and not creating any shared objects. This is a known problem. See #2283 #2346 #2196. This issue is currently not at the front of my queue, so it may not be resolved soon, at least by me.

So if you are doing a shared build, it is probably part of your build process so I would suggest looking there. If there any problems with the static libs we are delivering, please respond to this issue and I will re-open.
