### ISSUE TITLE
gl_ViewPortMask enabled by GL_NV_viewport_array2 should be supported from version 430 onwards

### ISSUE THREAD

**Issue by pmistryNV** [KhronosGroup/glslang#2785]
Presently TBuiltins::initialize enables gl_ViewPortMask builtin constant for Tesselation/Geometry and Vertex shaders only after version 450 and this needs to be corrected to version 430.

**Comment by pmistryNV** [comment]
@greg-lunarg let me know if I should push a fix for the same?

**Comment by greg-lunarg** [comment]
Let me know.

**Comment by greg-lunarg** [comment]
I have a PR and will be posting shortly.
