### ISSUE TITLE
glslangValidator segfaults when parsing some conversions of ivec2 to vec2.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#28]
This shader ~~curiously~~ results in a segmentation fault.

```GLSL
#version 120
vec3 m(vec2);
vec3 o() {
  m(ivec2(O));
}
```

~~Funnily enough, it also happens when the `#version 120` has no space between the directive and its argument(that is, `#version120`), not sure what that's about.~~

**Comment by johnkslang** [comment]
#version120 (no space) means you have an invalid directive, and you get the default #version.  There is a real bug in the conversion algorithm for changing the ivec2(X) to vec2(X), fix will be in soon, but the bug is there whether or not the #version was botched.

**Comment by johnkslang** [comment]
Commit 8ba301c7c2ab3a701cd0f865b8104a007d785b0e fixes this.
