### ISSUE TITLE
HLSL intrinsics

### ISSUE THREAD

**Issue by steve-lunarg** [KhronosGroup/glslang#280]
Hi,

I plan to contribute some intrinsics code to the HLSL translator, and have started investigating the situation.  Any early input is appreciated.

Attached is a table resulting from manually comparing the public HLSL intrinsics documentation to the latest SPIR-V spec and GLSL extension spec.  It provides, e.g, mappings to similar SPIR-V opcodes (e.g, lerp->FMix), and supported argument types on both sides (perhaps only one supports mats).  It's more terse than readable, but there is a magic decoder ring at the top.  Line endings are Unix flavored.

This does not yet attempt to address design decisions such as how best to handle differences in guarantees around numeric edge cases, handling the common matrix arguments, or what might or might not deserve new opcodes.  That all needs discussion and input, and I will make a proposal... but in its own thread.  Oh, I'll get to the texture stuff - it's all TODO.

A few things that've come up:

1. I waved my hands vaguely upon encountering memory barrier intrinsics.  It will take me some time just to digest them and their relation to the SPIR-V ops.  If anyone "just knows" something here, I'm all ears!

2. Ditto for Process2DQuadTessFactorsAvg and friends.

3. I'm interested in any corrections, in particular, where I've mentioned HLSL seemed under-documented in some way.

4. I'm interested in mistakes around NOEQUIV, which means I didn't know of any similar SPIRV opcode.  For example, "printf".  I might have false negatives or positives.

Thanks,
   steve

[intrinsic-notes.txt](https://github.com/KhronosGroup/glslang/files/264131/intrinsic-notes.txt)

**Comment by steve-lunarg** [comment]
New table with texture intrinsics filled in.  (The texture intrinsics are deprecated in newer versions of HLSL, but still available via option).

[intrinsic-notes.txt](https://github.com/KhronosGroup/glslang/files/266965/intrinsic-notes.txt)

**Comment by johnkslang** [comment]
One key thing (or mode) will be to have a *best approximation* way to 

- run an HLSL shader on the existing definition of SPIR-V as used currently in drivers for Vulkan, which
- might put some constraints on the initial set of HLSL shaders that are supported.

That could be backed up by a *best representation* mode that uses SPIR-V in the most accurate way for HLSL, which

- might initially be outside what Vulkan drivers currently support,
- generate enhancement requests for what form of SPIR-V that Vulkan drivers should accept, and 
- could also generate new functionality requests for SPIR-V.

I would start with the *best approximation* mode.

**Comment by steve-lunarg** [comment]
Agreed.

**Comment by steve-lunarg** [comment]
Attaching the latest version of the intrinsic-notes.txt for future archaeology, then closing the issue, since this is pretty well sorted now.

[intrinsic-notes.txt](https://github.com/KhronosGroup/glslang/files/342159/intrinsic-notes.txt)
