### ISSUE TITLE
isNan and isInf in Constant.cpp produce wrong results on big-endian systems

### ISSUE THREAD

**Issue by mhillenbrand** [KhronosGroup/glslang#2802]
Both attempt to decode a `double` into high and low 32-bit `int`s via a union:

https://github.com/KhronosGroup/glslang/blob/8f56d738000ba2b39595160b2d345821ce03d18f/glslang/MachineIndependent/Constant.cpp#L49-L52

On little-endian systems that works as intended. On big-endian systems, such as s390x, the 32-bit ints end up in reversed order and thus the two functions fail to detect Infs or NaNs.

Reproduction: `glslangValidator -C -i Test/constFold.frag` and compare `out10` and `out11` to expected values -- on s390x, they are all 0 since none of the NaN or Inf conditions are detected correctly.

**Comment by dneto0** [comment]
I believe that the use of the union exercised undefined behaviour.  It's a type-based alias analysis violation.
C++14 3.10 "Lvalues and rvalues" says what types can be loaded from memory locations, depending on what types were used to write those locations.

Thanks for fixing this!

**Comment by greg-lunarg** [comment]
Had to revert #2803 with #2809; see issue #2808.

**Comment by mhillenbrand** [comment]
In my patch, I missed moving the `#include <cfloat>` that is required on Windows. Fixing and testing...
