### ISSUE TITLE
I/O variables declared as locals with GL_EXT_spirv_intrinsics

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/glslang#2804]
A recent fix of spirv-val revealed bad SPIR-V generation for test spv.intrinsicsSpirvLiteral.vert. The variables vec4In and vec4Out are declared in the generated SPIR-V as storage class Function rather than Input and Output, respectively. This seems related to the GL_EXT_spirv_intrinsics extension since replacing the extension trappings in the GLSL source with a simple assignment gives correct declarations.

@amdrexu Can you please fix this test or find someone who can?

**Comment by amdrexu** [comment]
Yes, I will take a look.

**Comment by greg-lunarg** [comment]
Fixed by #2831
