### ISSUE TITLE
Please move resource_limits_c.h from private to public header paths

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/glslang#2822]
The Vulkan SDK is now shipping with the static library libglslang-default-resource-limits.a 

To use this library, the user currently has to manually bring in the prototypes from:
/Glslang/StandAlone/resource_limits_c.h

This needs to be relocated to make it public in:
/Glslang/glslang/Include

**Comment by ubitux** [comment]
Alternatively, maybe `glslang_input_t.resource` could also accept a `NULL`?

**Comment by SetoKaiba** [comment]
And also, ResourceLimits.h
