### ISSUE TITLE
Anyway to override #version for Vulkan targets?

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#2850]
Is there a way either from the command line or programmatically to override or ignore the `#version` preprocessor directive in the source file when compiling for Vulkan targets? I wasn't able to find anything in the docs or the source code. 

It would make porting older GLSL shaders to Vulkan a bit easier. `-R`,  `--amb`, and `--aml` make it signifcantly easier to get older shader libraries working on Vulkan and the `#version` preprocessor directive seems to be the last obstacle that prevents a clean compile.

**Comment by greg-lunarg** [comment]
Not that I know of.

I think command line (or library interface) override is the way to go. The compiler needs some expectations of version.

I would support such a PR to glslang. Others have been asking as well.

**Comment by chaoticbob** [comment]
Hi Greg, I put a PR (#2851) for this. Not sure if it's complete enough. PTAL and let me know.

**Comment by greg-lunarg** [comment]
Fixed by #2851
