### ISSUE TITLE
Build issues on "pseudo" Linux Debian (Stable)

### ISSUE THREAD

**Issue by chiaravalle** [KhronosGroup/glslang#2860]
Hello everyone, I tried to build glslangValidator on a Termux system, in Android.
The system is almost 100% Debian compatible, so I followed the Linux build steps, but, even if the build and installation went fine, I don't have glslangValidator binary (at least, not in path).
Trying to launch it, return this:
`bash: glslangValidator: command not found`

What should I do?

Thanks in advance for any help.
Cheers =)

**Comment by chiaravalle** [comment]
P.S.: I found the binary in /root/glsl/glslang/Test/glslangValidator and it runs well.
How can I install it?

**Comment by jeremy-lunarg** [comment]
Have you tried adding it to your `PATH`?

**Comment by chiaravalle** [comment]
Yes, but still getting that error

Il Ven 7 Gen 2022, 17:57 Jeremy Hayes ***@***.***> ha scritto:

**Comment by jeremy-lunarg** [comment]
You appear to be using a plugin for VSCode. Is that correct?

I'm not familiar with that plugin or VSCode. Does this anything in this [thread](https://stackoverflow.com/questions/64034864/what-is-the-correct-way-to-set-the-glsland-validator-path-on-the-glsl-lint-exten) offer insight into the problem?

Perhaps try investigating the following configuration setting?

`"glsllint.glslangValidatorPath": "/home/<username>/glslang/bin/glslangValidator"`

**Comment by chiaravalle** [comment]
Il Ven 7 Gen 2022, 18:06 Jeremy Hayes ***@***.***> ha scritto:

> You appear to be using a plugin for VSCode. Is that correct?
>
Yes, it is

> I'm not familiar with that plugin or VSCode. Does this anything in this
> thread
> <https://stackoverflow.com/questions/64034864/what-is-the-correct-way-to-set-the-glsland-validator-path-on-the-glsl-lint-exten>
> offer insight into the problem?
>
Somewhat

> Perhaps try investigating the following configuration setting?
>
> "glsllint.glslangValidatorPath":
> "/home/<username>/glslang/bin/glslangValidator"
>
No, still getting the error

**Comment by jeremy-lunarg** [comment]
Please try posting your issue in the [plugin](https://github.com/hsimpson/vscode-glsllint) repository. They should be able to help you configure your environment development.

**Comment by chiaravalle** [comment]
Ok, I will.
Thanks by the way

Il Ven 7 Gen 2022, 23:12 Jeremy Hayes ***@***.***> ha scritto:
