### ISSUE TITLE
Add a "mvp* vec4(in_pos, 1.0)" analysis pass in glslang

### ISSUE THREAD

**Issue by xiaoqiang-wang** [KhronosGroup/glslang#2869]
Hello, 
  I want to add a transformation analysis pass in glslang.

### To analysis whether a vertex position match below tranformation or not.
``` Shader
//in vec3 in_pos;

//uniform mat4 mvp;

gl_Position = mvp * vec4(in_pos, 1.0);
```

----

I want the pass run after  Front-end Paser, and visit the AST

##### For below test code, I want the analysis pass can return "true", for others return "false".
```Shader
precision highp float;

attribute vec4 a_vertex;

uniform vec4 u_modelview;


void main()
{
        gl_Position = u_modelview * vec3(a_vertex.xyz, 1.0);
}


```

**Comment by greg-lunarg** [comment]
I am sorry, but this functionality does not match the current purpose of this code base, which is to:

1) Validate GLSL shaders
2) Generate intermediate code (AST, SPIR-V) for GLSL and HLSL shaders.

As such, I would not accept such a capability into this code base.

I suggest you develop and distribute this capability yourself, incorporating glslang in a manner consistent with its licensing.
