### ISSUE TITLE
gl_in max array index

### ISSUE THREAD

**Issue by James-Jones** [KhronosGroup/glslang#287]
The shader below geometry shader is successfully compiles with glslang. I suspect it shouldn't do since the gl_in index is larger than the number of vertices in the input primitive topology.
# version 330

layout(triangle_strip, max_vertices = 6) out;
layout(triangles) in;

in vec2 gtexcoord[];
in vec4 gbasecolor[];

out vec2 ftexcoord;
out vec4 fbasecolor;

void main(void)
{
gl_Position = gl_in[100].gl_Position;
}

**Comment by James-Jones** [comment]
Given the below, 200 and 300 are reported as out of bounds, but 100 is not.
gl_Position = gl_in[100].gl_Position;
EmitVertex();
gl_Position = gl_in[200].gl_Position;
EmitVertex();
gl_Position = gl_in[300].gl_Position;
EmitVertex();
EndPrimitive();

**Comment by johnkslang** [comment]
The size to compare was correct, but the check was happening on all but the first time, due to code order. 

Fixed.
