### ISSUE TITLE
Symbolic/Automatic Differentiation Implementation in glsl

### ISSUE THREAD

**Issue by fknfilewalker** [KhronosGroup/glslang#2870]
Hi, I would like to implement either symbolic diff or autodiff into glsl/glslang for a research project. Maybe someone who is familiar with the code can give me some hints were I would need to start or what the best approach would be. 

I included some references that show similar implementations for other gpu languages. Most notable for directx [1] and cuda [2] but also cg [3].

[1] https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/SymbolicDifferentiationInGPUShadersTechReport.pdf
[2] https://rgl.epfl.ch/publications/NimierDavidVicini2019Mitsuba2
[3] http://www.doc.ic.ac.uk/~bkainz/publications/Kainz_ad2008.pdf

**Comment by greg-lunarg** [comment]
FWIW, glslang compiles HLSL as well. Not sure if it supports the features you would need, but if so, it would be that much less work to add it to GLSL.

**Comment by fknfilewalker** [comment]
Sadly it was removed from directx some time ago. If I remember correctly it was removed before/when microsoft made the switch to dxc? I think having it in glsl would be great because it is open, extensible and heavily used by students and the rest of the science community.

**Comment by allanmac** [comment]
If this describes your problem:

- Vulkan 1.2 + GLSL is an acceptable target.
- Most of your shaders are expected to be compute shaders working on storage buffers.

Then I'd recommend leveraging [buffer references](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_buffer_reference.txt) to jumpstart your compute shader work and avoid a lot of complexity (e.g. descriptor sets) until it's absolutely necessary.

**Comment by fknfilewalker** [comment]
I need it mostly for ray tracing, right now I do symbolic diff in matlab and copy paste the output code, but it would be really nice to have it directly in the compiler.

I thought about buffer refs but way to laborious.

**Comment by greg-lunarg** [comment]
Any additional features to glslang must first start with changes to GLSL and its extensions. Please file an issue here: https://github.com/KhronosGroup/GLSL and point to this issue, which I will be closing.
