### ISSUE TITLE
Improve comment for setEnvInput()

### ISSUE THREAD

**Issue by jljusten** [KhronosGroup/glslang#2872]
I'm trying to use glslang 11.7.1 with the renderdoc project. Renderdoc bundles glslang 8.13.3743.

Renderdoc calls `setEnvInput()` with a version parameter of 100, and uses it to pre-process GLSL (not GLSL+SPIR-V) sources.

Since glslang 6274ec5c (glslang 11.2.0), this appears to cause the glslang to define `GL_SPIRV` during pre-processing. `GL_SPIRV` ends up causing issues for the GLSL source output from the glslang pre-processor due to `#ifdef GL_SPIRV` usage by renderdoc.

Looking at the glslang README.md, it seems that `0` is recommended for the `version` parameter of `setEnvInput()` "For just validating (not generating code)".

What would be the recommended `version` value for using to glslang to pre-process GLSL (but, not GLSL+SPIR-V) sources? Is there anything in the glslang documentation that I'm missing that would clear this up? Why does setting it to a non-zero value cause glslang to define `GL_SPIRV`?

**Comment by jljusten** [comment]
To provide a bit more context,

https://github.com/KhronosGroup/glslang/blob/c9706bdda0ac22b9856f1aa8261e5b9e15cd20c5/glslang/Public/ShaderLang.h#L532-L538

sets `environment.input.dialectVersion = version;`

then

https://github.com/KhronosGroup/glslang/blob/c9706bdda0ac22b9856f1aa8261e5b9e15cd20c5/glslang/MachineIndependent/ShaderLang.cpp#L732-L733

sets `spvVersion.openGl = environment->input.dialectVersion;`

and, finally:

https://github.com/KhronosGroup/glslang/blob/c9706bdda0ac22b9856f1aa8261e5b9e15cd20c5/glslang/MachineIndependent/Versions.cpp#L610-L615

defines `GL_SPIRV` if `spvVersion.openGl` is non-zero.

**Comment by jljusten** [comment]
@greg-lunarg: Thanks for the answer! Based on your reply, clearly renderdoc would want to use 0 in this case to avoid `GL_SPIRV` being defined.

In reading the comments describing the `setEnvInput` parameters:

https://github.com/KhronosGroup/glslang/blob/c9706bdda0ac22b9856f1aa8261e5b9e15cd20c5/glslang/Public/ShaderLang.h#L509-L517

It still is not clear why a version of 0 would mean `GL_SPIRV` undefined, and non-zero would mean `GL_SPIRV` is defined. I didn't see anything in the extension spec that helps. Perhaps if the function comment included wording like:

```
    // The version indicates the input SPIR-V version, and GL_SPIRV
    // will be defined to this value (if non-zero) for OpenGL shaders.
```

Or, something like that?

I did ask renderdoc to change this parameter to 0, but I was unable to convince them to based on the vague (?) comment for the function. I might be able to use your comment here to help convince them, but, nevertheless, it might be worth clarifying this in the comment in the code. What do you think?

**Comment by greg-lunarg** [comment]
I believe this function is sufficiently documented for developers who understand the specs. At this moment, there are just three valid possibilities for the values of client and version:

EShClientNone, 0 => SPIR-V is not being generated; no macros defined

EShClientVulkan, 100 => SPIR-V generated targeting Vulkan; GLSL interpreted by KHR_vulkan_glsl extension version 100 ; #define VULKAN 100 generated

EShClientOpenGL, 100 => SPIR-V generated targeting OpenGL; GLSL interpreted by ARB_gl_spirv extension version 100; #define GL_SPIRV 100 generated

Any other values will give undefined behavior.

Let me know if the compiler is doing the wrong thing for one of the three possibilities above.

This interface is not intended to have user friendly error messages. If invalid combinations are passed, undefined behavior will occur.

**Comment by jljusten** [comment]
I guess what makes it seem vague to me (and perhaps others) is the implicit assumption that the version parameter has anything at all to do with SPIR-V. It could also be interpreted as the glsl version, for example.

I think that is what @baldurk is saying with "Looking at the documentation in the headers for that parameter it doesn't seem like 0 would be an appropriate value, rather it should probably be the version passed in as used for the #version since setEnvInput is explicitly noted to be describing the source language not any target": https://github.com/baldurk/renderdoc/pull/2457#issuecomment-1019468495

Even just renaming the `setEnvInput()` parameter from `version` to `spirvVersion` could help provide a bit more context. Or mentioning SPIR-V in the comment to the function.

**Comment by baldurk** [comment]
My confusion came from how the three properties are described in the comments, including implicitly by the options available in the enums. SPIR-V is only mentioned in relation to the 'target', and the comments for `setEnvInput` explicitly call out that it's not describing the target, which put me on the wrong path.

I thought this meant that `setEnvInput` described purely the language, `setEnvClient` described vulkan vs opengl GLSL, and `setEnvTarget` described whether compilation targetted SPIR-V or not (and its version, 1.0, 1.1, etc). So GL SPIR-V vs non-SPIR-V would be conditional on what the target was rather than the input version.

I think I understand what is meant now and it makes sense, but I do agree it could be better commented/documented. Even listing the valid options above as non-exhaustive examples (to allow for future options without becoming stale) would help a lot. At least to clarify that selecting OpenGL as a client means OpenGL SPIR-V via ARB_gl_spirv.

**Comment by greg-lunarg** [comment]
To be clear, this entry point does indeed only describe the source input language. For GLSL, there are three dialects: Core (or none), OpenGL client (via ARB_gl_spirv extension) and Vulkan client (via KHR_vulkan_glsl). The version is not a SPIRV version, but the version of the dialect extension, or 0 if Core.

I will attempt to improve the comment.
