### ISSUE TITLE
Unable to parse built-ins: non-matching or non-convertible constant type for const initializer

### ISSUE THREAD

**Issue by ESarti** [KhronosGroup/glslang#2875]
The full error:
```
Unable to parse built-ins
ERROR: 0:1: 'const' : non-matching or non-convertible constant type for const initializer 
INTERNAL ERROR: Unable to parse built-ins
```
I'm getting the above error while trying to compile a simple shader for Vulkan, using GLSL #version 450. The error only appeared when I updated to the latest master branch, it was working fine with an earlier version of glslang I was using (GLSLANG_MINOR_VERSION 13). I'm using the code below to parse the shader.

```c++
glslang::TShader* shader = new glslang::TShader(stage);
shader->setEnvInput(glslang::EShSourceGlsl, stage, glslang::EShClientVulkan, 100);
shader->setEnvClient(glslang::EShClientVulkan, glslang::EShTargetVulkan_1_0);
shader->setEnvTarget(glslang::EShTargetSpv, glslang::EShTargetSpv_1_0);
shader->setStringsWithLengths(shaderStrings.data(), shaderLengths.data(), shaderLengths.size());
shader->parse(&DefaultTBuiltInResource, 110, true, (EShMessages)(EShMessages::EShMsgAST | EShMessages::EShMsgVulkanRules | EShMessages::EShMsgDebugInfo));
```

This is the shader I'm using but I don't think the shader matters and would happen with any code as the error is being generated by the builtins.
```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec3 fragColor;
layout(location = 1) in vec2 fragTexCoord;

layout(location = 0) out vec4 outColor;

void main() 
{
	outColor.rgb = vec3(1.0) * 1.5;
	outColor.a = 1.0;
} 
```

Backtrace to the error:
```
1  glslang::TParseContext::executeInitializer                                 ParseHelper.cpp   7477 0x555555969a63 
2  glslang::TParseContext::declareVariable                                    ParseHelper.cpp   7273 0x5555559689cf 
3  yyparse                                                                    glslang.y         1203 0x5555559f55af 
4  glslang::TParseContext::parseShaderStrings                                 ParseHelper.cpp   209  0x55555594129d 
5  (anonymous namespace)::InitializeSymbolTable                               ShaderLang.cpp    275  0x55555577b2fe 
6  (anonymous namespace)::InitializeSymbolTables                              ShaderLang.cpp    338  0x55555577b722 
7  (anonymous namespace)::SetupBuiltinSymbolTable                             ShaderLang.cpp    467  0x55555577bf16 
8  (anonymous namespace)::ProcessDeferred<(anonymous namespace)::DoFullParse> ShaderLang.cpp    944  0x555555788717 
9  (anonymous namespace)::CompileDeferred                                     ShaderLang.cpp    1325 0x55555577e449 
10 glslang::TShader::parse                                                    ShaderLang.cpp    1910 0x55555577fea5 
11 glslang::TShader::parse                                                    ShaderLang.h      663  0x55555578d822 
12 glslang::TShader::parse                                                    ShaderLang.h      669  0x55555578d8bf 
```

**Comment by ESarti** [comment]
After some digging, I identified the root of the problem. Inside `TParseContext::executeInitializer`, when it checks for constness, it checks if the types of the variable and initializer are the same, by using the equality operator.

The equality operator of `TType` checks, amongst other things, `TTYpe::sameElementShape`, and this function checks if the `sampler` fields are the same for both types, disregarding whether or not the variable itself is a sampler.

It appears that the variable contains some old state when it comes to its `sampler` field and thus the type of variable and initializer don't match and returns that error. I "fixed" by changing the first equality inside `TTYpe::sameElementShape` from this:
```cpp
sampler == right.sampler
```

To this:

```cpp
((basicType != EbtSampler && right.basicType != EbtSampler) || sampler == right.sampler)
```

**Comment by greg-lunarg** [comment]
Thanks for the fix! I will put together a PR shortly.

**Comment by ESarti** [comment]
The reason I didn't make a PR was that while the fix I found should be safe because sampler state is only relevant if the variable is a sampler, maybe it should be investigated how the TType for an int ends up with old/non-zeroed sampler state?

**Comment by greg-lunarg** [comment]
OK. I will take a look. Thanks!

**Comment by greg-lunarg** [comment]
I cannot recreate the problem. Every TType constructor that I see seems to clear sampler, but there could be a hole somewhere, I just can't find it.

Please go ahead and make the PR which I think is an improvement.

**Comment by ESarti** [comment]
Oh, I thought you were doinng the PR? If you don't mind doing it yourself, I'd appreciate it, else I can work on it this weekend.

**Comment by greg-lunarg** [comment]
OK. I will do the PR.

Ultimately, it would be nice if you could find the source of the sampler corruption since you are able to currently reproduce it.

**Comment by greg-lunarg** [comment]
One fairly simple, if possibly tedious, method to find the error is to do a binary chop on master and figure out which commit introduced the regression.

**Comment by greg-lunarg** [comment]
> One fairly simple, if possibly tedious, method to find the error is to do a binary chop on master and figure out which commit introduced the regression.

My co-worker reminded me that the origin of the regression may just be that things shifted enough to cause the uninitialized member to be exposed and may not be the actual origin of the initialization hole.

Probably the best solution is to find where the TType is created and find the initialization hole there.
