### ISSUE TITLE
11.8.0 tag is missing

### ISSUE THREAD

**Issue by jbeich** [KhronosGroup/glslang#2880]
c34bb3b6c55f probably needs to show up as [11.8.0](https://github.com/KhronosGroup/glslang/releases/tag/11.8.0). Similar to how [11.7.0](https://github.com/KhronosGroup/glslang/releases/tag/11.7.0) used 925503088e2b.

Required by [shaderc 2022.0](https://github.com/google/shaderc/releases/tag/v2022.0): google/shaderc@50c1da3c0c82 depends on 9ebd8ff6c1d2.

**Comment by jbeich** [comment]
Note, found while trying to build shaderc 2022.0 which requires glslang 11.8.0.

**Comment by greg-lunarg** [comment]
Tag pushed. Sorry for the lapse.
