### ISSUE TITLE
build  it for tvOS

### ISSUE THREAD

**Issue by azureplus** [KhronosGroup/glslang#2882]
[ 19%] Building CXX object glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch
/var/folders/_l/20f4004537g0n0k2g6vwblqm0000gn/T/cmake_pch-2853c7.bc:1:1: error: expected top-level entity

make[3]: *** [glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx.pch] Error 1
make[2]: *** [glslang/CMakeFiles/MachineIndependent.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

**Comment by greg-lunarg** [comment]
I am not resourced to fix the build for this platform. If someone wishes to submit a fix, I would be willing to consider it.

**Comment by azureplus** [comment]
> 

m1

**Comment by SpaceIm** [comment]
Add `-DENABLE_PCH=0` while calling cmake. I believe that glslang should disable PCH by default for all compilers.

**Comment by greg-lunarg** [comment]
@azureplus Please see the workaround or submit a PR disabling PCH similar to #2925.

@SpaceIm I don't completely disagree with your suggestion to disable PCH by default for all compilers, but I am not sure what the overall implications might be. For the moment, I am going to choose to disable selectively as problems arise. I do thank you for recognizing the problem, helping me to recognize the problem and submitting the PR.

**Comment by greg-lunarg** [comment]
@azureplus I am asking you to submit the PR because you are in the best position to test if the fix works.

You will essentially need to add to the test modified by #2925. You will "OR" in the following to the test:

("${CMAKE_SYSTEM_NAME}" STREQUAL "tvOS")

If the fix does not work, let me know and I will re-open the issue.
