### ISSUE TITLE
Basic problem (link error)

### ISSUE THREAD

**Issue by Kaninchen221** [KhronosGroup/glslang#2889]
It's my first time with Glslang and I try convert glsl to spirv using StandAlone.cpp code as reference.
My problem is: I can't use `glslang::GlslangToSpv(...);` I get link error because it's not imported.
The declaration is that:
```
namespace glslang {

void GetSpirvVersion(std::string&);
int GetSpirvGeneratorVersion();
void GlslangToSpv(const glslang::TIntermediate& intermediate, std::vector<unsigned int>& spirv,
                  SpvOptions* options = nullptr);
void GlslangToSpv(const glslang::TIntermediate& intermediate, std::vector<unsigned int>& spirv,
                  spv::SpvBuildLogger* logger, SpvOptions* options = nullptr);
void OutputSpvBin(const std::vector<unsigned int>& spirv, const char* baseName);
void OutputSpvHex(const std::vector<unsigned int>& spirv, const char* baseName, const char* varName);

}
```
So there shouldn't be something like `SPRIV_API` between `void` and `GlslangToSpv`?

**Comment by greg-lunarg** [comment]
Are you trying to do dynamic linking?

**Comment by Kaninchen221** [comment]
> Are you trying to do dynamic linking?

I will try that

**Comment by Kaninchen221** [comment]
I think I just forget to link against SPIRV in cmake but now I get error about can't open SPIRVd.lib.

**Comment by greg-lunarg** [comment]
That is a debug library.

**Comment by Kaninchen221** [comment]
So I can't just fetch this in cmake and link against him in my project? I need to follow the guide in readme and install him?

**Comment by greg-lunarg** [comment]
No, you do not need to install.

**Comment by greg-lunarg** [comment]
You can also specify an install directory within your project directory.

**Comment by greg-lunarg** [comment]
In general, many have found it possible to link to glslang. I have done it myself. As such, I will be closing this issue. B I would be happy to answer additional questions or make small improvements where they would help. Just add them here and I will reopen if warranted.
