### ISSUE TITLE
design choices for HLSL intrinsic -> SPIR-V opcodes

### ISSUE THREAD

**Issue by steve-lunarg** [KhronosGroup/glslang#289]
Categorizing the [raw data from the table here](https://github.com/KhronosGroup/glslang/issues/280), I see the broad categories below.  I've proposed below how each should be handled.  Soliciting disagreements.

### Summary: 

The cases below can be handled via a HLSL compatibility extension which shares opcode values as far as possible with current SPIR-V opcodes, extending them in cases such as additional type support or stronger numeric guarantees with no backwards compatibility troubles.   Extended opcodes would be introduced where there is no simple mapping.  This means many HLSL shaders could work without the HLSL extension being implemented, as long as they didn't use the extended features.  This desire also motivates some simple decompositions where an additional opcode could also be introduced.

### Details:

1. HLSL intrinsics accepting data types not accepted by SPIR-V opcodes (or for that matter, GLSL intrinsics).  This is fairly ubiquitous, primarily in the case of matrix types, but in others too, such as doubles where SPIR-V cannot accept them.

  _Example:_ abs(float3x3)

  _Proposal_: Where functionality is otherwise identical, extend current SPIR-V opcode to handle the new types, when operating in HLSL compatibility mode.  This is backwards compatible.

2. HLSL intrinsics mapping to multiple SPIR-V opcodes based on data type.

  _Example_: mul(x,y) -> VectorTimesScalar, VectorTimesMatrix, MatrixTimesScalar, etc.

  _Proposal_: I believe these cases can be statically determined at translation time with no loss of performance or generality via static type analysis.  So, just map them accordingly.  There are perhaps half a dozen such intrinsics.

3. Cases where HLSL makes stronger numeric guarantees than the corresponding SPIR-V opcode.

  _Example_: pow(x,y): HLSL ties down some INF cases that SPIR-V leaves undefined.

  _Proposal_: In HLSL compatibility mode, tighten up the SPIR-V guarantees.  This is also backwards compatible.  Undefined behavior can produce an Inf or a NaN.  Anyway, it seems lower priority to get working.  It rarely matters in real shaders.

4. Cases where an HLSL intrinsic cannot be translated to a single SPIR-V opcode, but there is a straightforward decomposition.

  _Example_: sincos -> separate sin & cos

  _Proposal_: In most cases, do the decomposition during translation, per the desire to let many shaders run without requiring extended downstream functionality.  Often, hardware can do a sin & a cos faster together than separately, so this is a potential performance loss on such HW.  However, compiler backends usually attempt to perform such combining when possible, since the shader could have written them separately in the source language, so in practice I don't foresee much detriment.  This does not preclude later introduction of a native opcode.

5. Cases where functionality is identical, but argument sequence differs.

  _Example_: InterlockedAdd: uses output parameter, where SPIR-V atomic add uses return.

  _Proposal_: Map during translation, again per desire for shaders to work without HLSL specifics downstream.  AFAIK there is no performance drawback.

6. Cases with no similar opcode or simple decomposition.

   _Examples_: printf
             D3DCOLORtoUBYTE4
             msad4

   _Proposal_: Introduce new opcodes in an HLSL compatibility mode.  If a shader uses these, it'll need them implemented.  In some cases such as D3DCOLORtoUBYTE4, a decomposition can be created, but awkwardly, and it would be more burdensome to recover.  I've marked such cases in the table with NOEQUIV.

7. Cases with flow control differences.

   _Examples_: clip(x).  HLSL intrinsic accepts a numeric value.  The SPIR-V opcode would have to be protected under flow control.

   _Proposal_: Create a new opcode.  This could also be done in a "low downstream requirements" mode by introducing the required flow control during translation.  Ideally though, it's kept.  It's easier for downstream code to introduce the flow control if needed, than to recover the parameter version if desired from upstream-introduced flow control.

8. EvaluateAttributeSnapped class.  HLSL offset is given as integer location on a 16x16 grid.  SPIR-V offsets are given as float pixels.

  _Proposal_: Translate the single packed integer to 2 floats during translation.

**Comment by oscarbg** [comment]
Just thinking how HLSLcross project (https://github.com/James-Jones/HLSLCrossCompiler) which translates HLSL opcodes from compiled DX bytecode file format to GLSL deals with this issues..
I asume not much thinking has been done in HLSLcross so most issues will be present..

Also would be interesting how SPIR-V code differs from this proposal vs going from HLSL to SPIR-V via:
DX HLSL fx compiler->HLSLcrosscompiler->GLSLang

Finally also thinking if not will be good to have an option of glslang taking HLSL opcodes directly from fxc produced DXBC files similar to HLSLcross and converting to SPIR-V opcodes avoiding parsing/lexing HLSL shaders..

**Comment by steve-lunarg** [comment]
Thanks for the comments Oscarbg!

I suspect there are multiple things in play, since that project is coming at it from a different direction.  Since HLSL is a high level language and DX bytecode is asm-like, certain decompositions (such as component-wise matrix ops, say) may have already been performed by the fxc bytecode compiler and thus no longer appear in regenerated code.  Some numeric edge case behaviors can probably be ignored with little ill effect in the real world, since few shaders depend on them.

> Also would be interesting how SPIR-V code differs from this proposal vs going from HLSL to SPIR-V via: DX HLSL fx compiler->HLSLcrosscompiler->GLSLang

One worry I would have is information loss through the DX bytecode.  Sometimes you can have a go at recovery or reconstruction, but it's often an imperfect or inconvenient process relative to preservation.

**Comment by johnkslang** [comment]
> Also would be interesting how SPIR-V code differs from this proposal vs going from HLSL to SPIR-V via:
DX HLSL fx compiler->HLSLcrosscompiler->GLSLang

There is quite a bit of information loss.  SPIR-V has native idioms for high-level constructs we care about.

Further, if we want to add anything feature to the HLSL, say a specialization-constant syntax, or any other GLSL-for-SPIR-V syntax, we need to control the definition of the language.
