### ISSUE TITLE
glslang report a error for location qualifer 'origin_upper_left'

### ISSUE THREAD

**Issue by ZhiqianXia** [KhronosGroup/glslang#2896]
Hi , I got the shader from ogl test suit, but i find that the glslang report a error for origin_upper_left.  I serach the code at parserhelper.cpp + line 5506, there is some code for it.  but i don't know what happen for it. 

shader : 

#version 150 core
#extension GL_ARB_explicit_attrib_location : enable
#ifdef GL_ES
precision mediump float;
#endif

layout (origin_upper_left,pixel_center_integer) in vec4 gl_FragCoord;
float myGlobalVar = gl_FragCoord.x;
layout (origin_upper_left,pixel_center_integer) in vec4 gl_FragCoord;

in vec4 i;

layout (location = 0) out vec4 myColor;

const float eps=0.001;

void main() {
    myColor = vec4(0.2);
    if (gl_FragCoord.y >= 10) {
        myColor.b = 0.8;
    }
    if (gl_FragCoord.y == trunc(gl_FragCoord.y)) {
        myColor.g = 0.8;
    }
    if (gl_FragCoord.x == trunc(gl_FragCoord.x)) {
        myColor.r = 0.8;
    }

    vec4 diff = gl_FragCoord - i;
    if (abs(diff.z)>eps) myColor.b = 0.5;
    if (abs(diff.w)>eps) myColor.a = 0.5;
}

ERROR: #version: Desktop shaders for OpenGL SPIR-V require version 330 or higher
ERROR: D:\local\Temp\d7828f8b-0cdf-4480-9d22-4c8108e46165.tmp:9: 'origin_upper_left' : unrecognized layout identifier, or qualifier requires assignment (e.g., binding = 4) 
ERROR: D:\local\Temp\d7828f8b-0cdf-4480-9d22-4c8108e46165.tmp:9: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

**Comment by ZhiqianXia** [comment]
shader:

#version 140

#extension GL_ARB_fragment_coord_conventions: require
#extension GL_ARB_explicit_attrib_location : enable

#ifdef GL_ES
precision mediump float;
#endif

in vec4 i;

layout (origin_upper_left,pixel_center_integer) in vec4 gl_FragCoord;
layout (location = 0) out vec4 myColor;

const float eps=0.001;

void main() {
    myColor = vec4(0.2);
    if (gl_FragCoord.y >= 10) {
        myColor.b = 0.8;
    }
    if (gl_FragCoord.y == trunc(gl_FragCoord.y)) {
        myColor.g = 0.8;
    }
    if (gl_FragCoord.x == trunc(gl_FragCoord.x)) {
        myColor.r = 0.8;
    }

    vec4 diff = gl_FragCoord - i;
    if (abs(diff.z)>eps) myColor.b = 0.5;
    if (abs(diff.w)>eps) myColor.a = 0.5;
}

**Comment by ZhiqianXia** [comment]
fix the issue by https://github.com/KhronosGroup/glslang/pull/2897

**Comment by greg-lunarg** [comment]
Fixed by #2897
