### ISSUE TITLE
E: Unable to locate package glslang-tools

### ISSUE THREAD

**Issue by ja99** [KhronosGroup/glslang#2900]
Hi everybody,

my system (Ubuntu 18.04) can't find glsllang-tools.
Every source I found said it would be fixed by a `sudo apt update` but this isn´t the case.
I´ve also tried `sudo apt-get dist-upgrade` and `sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"` to no prevail.

The complete error is:
`(base) janis@janis-Ubuntu18:/etc/apt/sources.list.d$ sudo apt-get install libvulkan-dev glslang-tools cmake -y`

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package glslang-tools`

Thank you very much in advance!

**Comment by johnzupin** [comment]
I don't believe Canonical provides a glslang-tools package for Ubuntu 18.04, Ubuntu versions after 18.04 do though.

LunarG has a repository that does provide a glslang package for 18.04. Go to https://vulkan.lunarg.com/sdk/home and look for the Ubuntu tab under the Linux section to see the instruction how to set it up.

**Comment by ja99** [comment]
> I don't believe Canonical provides a glslang-tools package for Ubuntu 18.04, Ubuntu versions after 18.04 do though.
> 
> LunarG has a repository that does provide a glslang package for 18.04. Go to https://vulkan.lunarg.com/sdk/home and look for the Ubuntu tab under the Linux section to see the instruction how to set it up.

Worked great, Thank you!
