### ISSUE TITLE
glslang_optimization_level_t is exposed but can't be used

### ISSUE THREAD

**Issue by ubitux** [KhronosGroup/glslang#2907]
From the C interface, it seems we can't use the exposed optimization level:

```c
/* EShOptimizationLevel counterpart  */
typedef enum {
    GLSLANG_OPT_NO_GENERATION,
    GLSLANG_OPT_NONE,
    GLSLANG_OPT_SIMPLE,
    GLSLANG_OPT_FULL,
    LAST_ELEMENT_MARKER(GLSLANG_OPT_LEVEL_COUNT),
} glslang_optimization_level_t;
```

This is never used anywhere in the codebase. Indeed, it seems to default to the slow path:

```c
struct SpvOptions {
    SpvOptions() : generateDebugInfo(false), stripDebugInfo(false), disableOptimizer(true),
        optimizeSize(false), disassemble(false), validate(false) { }

/* ... */

GLSLANG_EXPORT void glslang_program_SPIRV_generate(glslang_program_t* program, glslang_stage_t stage)
{
    spv::SpvBuildLogger logger;
    glslang::SpvOptions spvOptions;
    spvOptions.validate = true;

    const glslang::TIntermediate* intermediate = program->program->getIntermediate(c_shader_stage(stage));

    glslang::GlslangToSpv(*intermediate, program->spirv, &logger, &spvOptions);

    program->loggerMessages = logger.getAllMessages();
}
```

**Comment by greg-lunarg** [comment]
These values are only intended for the generation of the intermediate/AST, not for the generation of SPIR-V. Only the "no generation" and "none" values are practically honored in the ultimate C++ code.

While these are technically not used in the C interface at the moment (the "none" value is currently the default), it is possible that someone may wish to add them to the C interface at some point, so I will leave them here. I will add a comment to reduce confusion.
