### ISSUE TITLE
Is location decoration missing for input/output structure variables?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#291]
## From Christopher Gautier:

glslangValidator does not decorate non-built-in input and output structures:

```
layout(location=2) in vec4 i1;
layout(location=3) in struct { vec4 v; } i2;
layout(location=0) out vec4 o;
```

produces:

```
EntryPoint Fragment 4  "main" 9 11 15
...
Name 9  "o"
Name 11  "i1"
MemberName 13 0  "v"
Name 15  "i2"
...
Decorate 9(o) Location 0
Decorate 11(i1) Location 2
```

i1 is decorated, but not i2, even though 1) it is listed in the OpEntryPoint list, and 2) it has a location assigned in the GLSL source.

Output variables are similarly impacted.

**Comment by scyganINTEL** [comment]
Yes it is missing, and it is an issue affecting CTS.

I have started playing with that issue in #294, but it is rather an RFC at this moment.

**Comment by johnkslang** [comment]
#294 looked like forward progress, so I pulled it in.

A part that wasn't quite clear yet was distinguishing between an object and a type.  An object can have a location, not a type.

The pending action needed here is probably additional tests bracketing this behavior to make sure it's correct.

**Comment by scyganINTEL** [comment]
The spec says struct type must have a location here:
```
The layout of a structure type used as an Input or Output depends on whether it is also a Block (i.e. has a Block decoration).

If it is a not a Block, then the structure type must have a Location decoration
```

My reading of that is both object (all variables listed in OpEntryPoint) and type should have location - what indeed is strange.

**Comment by johnkslang** [comment]
I mean, from a GLSL perspective, a struct member as a type can't have a location, only an instantiated object member can. In SPIR-V, the way an instantiated object member gets a location is from its type's member.

**Comment by johnkslang** [comment]
Current glslang is getting this:

```
                              Decorate 9(i1) Location 2
                              Decorate 10 Location 3      // an OpTypeStruct
                              Decorate 12(i2) Location 3  // an OpVariable
                              Decorate 14(o) Location 0
```

So, it is now working, but perhaps too well (maybe this bug was fixed by too many people), as two different things are getting location 3: the input variable is getting it as well as the struct.  It should not be on the struct (only struct members, if the members were decorated).

I'm going to fix this to conform to the specification.

**Comment by johnkslang** [comment]
With commit 22e0d41448487645ca4bdbab6b14034ed8c4f36f, I now get the following correct result:

```
                              Decorate 9(i1) Location 2  // an OpVariable
                              Decorate 12(i2) Location 3 // an OpVariable
                              Decorate 14(o) Location 0  // an OpVariable
```
