### ISSUE TITLE
Add auto-location-assigning mode to glslang, with linking

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#292]
## From Michał Pyrzowski:

If an explicit location is not specified for interface variables in the GLSL shader than the glslang generated SPIR-V code does not contain location decorations for those variables.

Such SPIR-V code does not follow Vulkan validation rule:

> All variables (or block members) in the Input and Output storage class must have a location decoration.

The cross-stage linking would probably be the best solution to the problem.

I suppose that if Glslang is unable to generate a valid Vulkan SPIR-V from the provided GLSL source than at least the user should be notified of it. It could be done by a warning/error message.

**Comment by johnkslang** [comment]
Correct.  Glslang is not inventing location information; that currently needs to come from the shader.

**Comment by scyganINTEL** [comment]
CC @scyganINTEL

**Comment by johnkslang** [comment]
Note auto-numbering is required by the HLSL path.  There is the in/out interface that needs location numbers, and then the resource/buffer interfaces that need binding numbers.  Wondering about leverage/interaction between these.

**Comment by ChrisGautier** [comment]
I second the emission of e.g. an error message. We have seen content broken because of the absence of locations.

**Comment by arcady-lunarg** [comment]
This has been implemented, please see the `--auto-map-locations` command-line option. There are no plans to implement the cross-stage form of this at this time.
