### ISSUE TITLE
Linking errors when building with ubsan due to missing exported types

### ISSUE THREAD

**Issue by Iisus** [KhronosGroup/glslang#2920]
Hi!

When building my application with `-fsanitize=undefined`, I get the following linking errors due to TShader and TProgram not being exported:
```
undefined reference to `typeinfo for glslang::TShader'
undefined reference to `typeinfo for glslang::TProgram'
```
Would it be possible to export those classes, not just their methods? Or do you have other suggestions on how to solve this? Currently, as a workaround, I disable checks that need rtti (`-fno-sanitize=vptr`).

**Comment by greg-lunarg** [comment]
Currently we only support static linking. It is not clear that this is an issue against static linking. Therefore I will close this for now. If you can give further details that there is a problem with static linking, please provide them and I will re-open.

**Comment by ashpil** [comment]
Experiencing this as well, looks like it somehow has something to do with RTTI -- compiling glslang with `-frtti` resolves the issue without having to turn off ubsan features.

**Comment by arcady-lunarg** [comment]
From the [ubsan documentation](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks):
> -fsanitize=vptr: Use of an object whose vptr indicates that it is of the wrong dynamic type, or that its lifetime has not begun or has ended. Incompatible with -fno-rtti [...]
Are you using this option? If so, you will need to enable rtti, which is disabled by default for glslang.
