### ISSUE TITLE
Can't build with mingw on windows

### ISSUE THREAD

**Issue by AndreyMlashkin** [KhronosGroup/glslang#2922]
originally reported on https://github.com/conan-io/conan-center-index/issues/10134

When compiling with mingw on windows, there is a compiler error occurs
[ 27%] Built target SPVRemapper
[ 28%] Building CXX object source_subfolder/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/iomapper.cpp.obj
[ 30%] Building CXX object source_subfolder/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/InfoSink.cpp.obj
[ 31%] Building CXX object source_subfolder/glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/Initialize.cpp.obj
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:192: MapViewOfFileEx: Attempt to access invalid address.

**Comment by greg-lunarg** [comment]
I am sorry to hear about your build troubles, but it is beyond my charter to address this problem or guarantee compilation with all possible compilers. The current repo builds utilizing MSVS C++11, so the troubles you are seeing would seem to be with the compiler you are using. I would suggest filing an issue with that compiler.

**Comment by SpaceIm** [comment]
@greg-lunarg It's fixed by setting `ENABLE_PCH` to `OFF` by default if `MINGW`.

**Comment by greg-lunarg** [comment]
@SpaceIm Thanks for the fix!
