### ISSUE TITLE
Error in continous_deployment script 

### ISSUE THREAD

**Issue by Yaraslaut** [KhronosGroup/glslang#2942]
During zip section of the script following command is used:

https://github.com/KhronosGroup/glslang/blob/2f5bc0b7414f5d063b9c2fcf231469aec1e549d3/.github/workflows/continuous_deployment.yml#L77-L90

In such way for the directory  `/include/glslang/*` only files directly inside this path will be included and archive will contain only empty folders in this path. You can check it in you last released archives.
You can add recursive option to add all *.h files inside include. simply:
`zip -r ${ARCHIVE} ....`

**Comment by jeremy-lunarg** [comment]
Fixed by #2979.
