### ISSUE TITLE
glslang output errors for whole file?

### ISSUE THREAD

**Issue by fknfilewalker** [KhronosGroup/glslang#2949]
Is it possible that glslang can give you the errors for the whole file and not only the most recent one?

**Comment by greg-lunarg** [comment]
Can you give an example of the behavior you are seeing and what you would like to see instead?

**Comment by fknfilewalker** [comment]
To get an output of all the lines that have an error. For instance there is GLSL Lint for Visual Studio Code, which takes the error output from glslangValidator to show you the line at which an error occured, but since glslangValidator only shows you the first error it encounters you also only see one error. In general the way of fixing glsl errors is, run the validator, fix error, run again, fix next one, run again ... and so on

**Comment by fknfilewalker** [comment]
Consider the following compute shader. Both lines in the main contain an error.
```glsl
#version 460
void main() {
    vec2 error1 = vec3(1);
    vec2 error2 = vec3(1);
}
```
When running glslangValidator the output is
```
ERROR: 0:5: '=' :  cannot convert from ' const 3-component vector of float' to ' temp 2-component vector of float'
ERROR: 0:5: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```
better would be 

```
ERROR: 0:5: '=' :  cannot convert from ' const 3-component vector of float' to ' temp 2-component vector of float'
ERROR: 0:6: '=' :  cannot convert from ' const 3-component vector of float' to ' temp 2-component vector of float'
ERROR: 2 compilation errors.  No code generated.
```

**Comment by greg-lunarg** [comment]
The glslangValidator -C option should give you what you are looking for. Let me know if it doesn't and I will re-open.

FWIW, that is EOptionCascadingErrors if you are using the API.
