### ISSUE TITLE
Invalid SPIR-V Generated For samplerBuffer in SPIR-V 1.6

### ISSUE THREAD

**Issue by qingyuanzNV** [KhronosGroup/glslang#2956]
In SPIR-V 1.6 spec, it is no longer valid to create a sampled image with dimension of buffer. Specifically, quote the following spec text:
```
OpTypeSampledImage
Declare a sampled image type, the Result Type of OpSampledImage, or an externally combined sampler
and image. This type is opaque: values of this type have no defined physical size or bit pattern.
Image Type must be an OpTypeImage. It is the type of the image in the combined sampler and image
type. It must not have a Dim of SubpassData. Additionally, starting with version 1.6, it must not have a
Dim of Buffer.
```

However, in glslang, we'll still emit OpTypeSampledImage and OpSampledImage for samplerBuffer. Translation of samplerBuffer into SPIR-V needs to be clarified and fixed.

One possible fix could be: https://github.com/KhronosGroup/glslang/commit/b3e89690ee0362680e653607fbac5e1f094bfff4

**Comment by greg-lunarg** [comment]
I get what you are doing with b3e8969. Essentially, if someone tries to combine a sampler to a buffer, ignore (throw away) the sampler and keep going. The sampler is never going to be needed anyway.

It doesn't solve the problem if the user declares a samplerBuffer targeting spirv1.6, but maybe that can be a different issue.

**Comment by qingyuanzNV** [comment]
If user declares a samplerBuffer, the fix is at line 4161 so we don't make it a sampledImage.
However, this implementation feels a little hacky to me. I suppose the spec should eventually remove samplerBuffer.

**Comment by qingyuanzNV** [comment]
> > However, this implementation feels a little hacky to me.
> 
> Yes. My concern is to silently accept the samplerBuffer but just create a buffer in the spirv, which would not match what the user is expecting.
> 
> Then, if we are not supporting samplerBuffer from first principles, I do not feel right about allowing it to be created with a constructor.
> 
> It feels to me the solution is to give an error that samplerBuffer is not supported for spirv1.6.
> 
> @gnl21 What do you think of giving such an error?

As far as I know, both samplerBuffer and textureBuffer are referred as "Uniform Texel Buffers". It looks like samplerBuffer was a workaround for buffering in the OpenGL era, which couldn't be sampled anyway. In vulkan context, they almost can be used interchangeably. I could be wrong though.

**Comment by greg-lunarg** [comment]
If indeed you think it is acceptable to generate a textureBuffer in SPIR-V for a GLSL samplerBuffer going forward, that works for me. Thanks for your perspective!

Given this, I will move ahead with the review.
