### ISSUE TITLE
Remove the GLSLANG_WEB build define?

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/glslang#2958]
The `GLSLANG_WEB` build configuration was added early in the WebGPU lifetime. The WGSL spec has changed since it was added so there is a good chance it is no longer valid with what WebGPU expects from SPIR-V.

The usage of the build configuration is also very invasive and makes the code difficult to work with.

@dneto0

**Comment by eugeneko** [comment]
It also does not work. glslang cannot compile with `GLSLANG_WEB` due to multiple missing elements.

**Comment by dneto0** [comment]
I endorse deleting this support.
