### ISSUE TITLE
glslang doesn't enforce GLSL linking rules

### ISSUE THREAD

**Issue by weifengz** [KhronosGroup/glslang#296]
This simple pair of shaders should have failed to generate spv with linking option due to mismatched uniform blocks, but SPV was generated successfully.

FS:
#version 310 es
precision highp float;
layout(location = 0) out vec4 color;
layout(set = 0, binding = 0) uniform myUBO {
  vec4 base;
};
void main()
{
  color = base + 1.0;
}

VS:
#version 310 es
layout (set = 0, binding = 1) uniform myUBO {
  mat4 m;
};
void main()
{
  gl_Position = m[1];
}

**Comment by johnkslang** [comment]
Note glslang is not yet a link-time validator, only a compile-time validator.

This is a duplicate of issue #89.

**Comment by johnkslang** [comment]
Transferring comment over to #89.
