### ISSUE TITLE
The custom preamble string should be after the `#version` line in preprocess output 

### ISSUE THREAD

**Issue by chirsz-ever** [KhronosGroup/glslang#2967]
I want to get the preprocess result and the source uses the `#include` extension, so the code is like:

```cpp
glslang::TShader tshader(stage);
EShMessages msg = EShMsgSpvRules;
Includer includer;
std::string ppOutput;
tshader.setStringsWithLengthsAndNames(src_strs, src_sizes, src_names, 1);
tshader.setPreamble("#extension GL_GOOGLE_include_directive: require\n");
tshader.preprocess(&resource, 310, EEsProfile, true, false, msg, &ppOutput, includer);
```

the `src` which is the content of `/path/to/example.vert` is:

```glsl
#version 310 es

#include "defs.h"

void main()
{
    gl_Position = vec4(position, 0.0, 1.0);
    texCoord = (position * 0.5) + 0.5;
}
```

`/path/to/defs.h`:

```glsl
layout(location = 0) in vec2 position;
layout(location = 0) out vec2 texCoord;
```

And after the preprocess, the `ppOutput` is:

```glsl
#extension GL_GOOGLE_include_directive : require
#version 310 es

#line 1 "/path/to/defs.h"
layout(location = 0)in vec2 position;
layout(location = 0)out vec2 texCoord;
#line 4 "/path/to/example.vert"

void main()
{
    gl_Position = vec4(position, 0.0, 1.0);
    texCoord =(position * 0.5)+ 0.5;
}
```

The `ppOutput` cannot be passed to parser, because its `#version` line is not at the first line.

Is it a recommended practice to use the `#extension` line as the custom preamble string?

**Comment by greg-lunarg** [comment]
My interpretation is: No.

Rather, include the `#extension GL_GOOGLE_include_directive: require` in example.vert just under the #version.

Please reopen this issue if my solution does not work for you.
