### ISSUE TITLE
Compiling without HLSL causes the source to not be set in localIntermediate.h

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/glslang#2969]
In `localIntermediate.h` there is an ENABLE_HLSL block for the `setSource` method. If HLSL is disabled then `setSource` does not assign the `source` variable.

This then means that `enhancedMsgs` does not work as it's conditional on the source begin set to GLSL in order to get enhanced messages.

**Comment by greg-lunarg** [comment]
Yes. I will post a fix shortly.
