### ISSUE TITLE
Feature Request: A command line option to specify the type of the shader

### ISSUE THREAD

**Issue by pendingchaos** [KhronosGroup/glslang#299]
There is no command line option to override the type of the shader determined by the filename extension (or specify the type if it could not be determined). Could this be added?

**Comment by johnkslang** [comment]
This got added a while back, as the `-S` option: 

```
  -S <stage>  uses explicit stage specified, rather then the file extension.
              valid choices are vert, tesc, tese, geom, frag, or comp
```
