### ISSUE TITLE
Is there a compatibility guarantee for the mangling algorithm?

### ISSUE THREAD

**Issue by chirsz-ever** [KhronosGroup/glslang#2996]
For example, the GLSL code `vec3 blend(vec3, vec3, float) { ... }` will produce a `OpName %id "blend(vf3;vf3;f1;"` instruction, is there a guarantee to generate the same mangled name in future versions of glslang?

**Comment by greg-lunarg** [comment]
There is no guarantee per se, but for all shaders that compile today, we do not foresee the mangled names changing, and they can be assumed to be stable for all practical purposes.
