### ISSUE TITLE
Optimization performance needs improvement for this sample file

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#2999]
The attached GLSL file is somewhat large, but nothing crazy, 2685 lines. Compiling it with (running in release build):
`glslangValidator tk3.frag --target-env vulkan1.1 --sdub DefaultUniformBlock 1 0 --amb --aml -R -V -Os -H
`
takes ~4 minutes, and generates a 55,000 line long SPIR-V file. The ids grow into the many 100,000s. Almost all of the time (84%) is spent in spvtools::opt::analysis::DefUseManager::EraseUseRecordsOfOperandIds

With optimizations disabled the SPIR-V is only 11,000 lines.

Although I assume this is likely a spirv-opt bug, I'm posting here as a first step incase the optimizations applied by glslang with -Os need to be tweaked to handle this case.

Can anything be done to improve this? My users are generating procedural shaders and end up with code like this, which I think is reasonable. The Nvidia OpenGL GLSL compiler compiles this quite quickly.

[tk3.frag.txt](https://github.com/KhronosGroup/glslang/files/9313295/tk3.frag.txt)

**Comment by greg-lunarg** [comment]
I think it is an issue with spirv-tools.

d18d0d introduced a change that degraded compile time for large SPIRV.

It was reverted with faa8d6.

The previous released glslang known goods had the degrading code. The most recent glslang known good have the revert.

Could you please try your compile with a very recent spirv-tools and report back?

**Comment by mbechard** [comment]
Ok thanks, confirmed things run fast with the latest known_good commit hashes
