### ISSUE TITLE
Sequence of eight #endifs trigger a segmentation fault

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#30]
```GLSL
#endif
#endif
#endif
#endif
#endif
#endif
#endif
#endif
```
, Or any other sequence of eight or more unmatched `#endif` directives, triggers a segmentation fault in `glslang::TParseContext::outputMessage`.

**Comment by johnkslang** [comment]
See also issue #29.

**Comment by xorgy** [comment]
Thanks to @antiagainst, PR #194 resolves this issue.
