### ISSUE TITLE
Support gles shader versions earlier than 310 spec

### ISSUE THREAD

**Issue by konnery** [KhronosGroup/glslang#3004]
Hi, esteemed Khronos Group, our team found that glslang does not support gles shader versions earlier than 310 spec and does not support some gles features very well. 
We would like to know if the glslang project has any plans to support the full gles,  and if not, if we can contribute to the community when we expand it.

**Comment by greg-lunarg** [comment]
I am not aware of any plans. And yes, we will accept contributions to improve this.
