### ISSUE TITLE
1.3.224.0: install path of cmake files

### ISSUE THREAD

**Issue by kloczek** [KhronosGroup/glslang#3008]
Just updated my glslang rpm package and found that new version provides cmake module.
```console
    File not found: /home/tkloczko/rpmbuild/BUILDROOT/glslang-1.3.224.0-2.fc35.x86_64/usr/include/SPIRV
    Installed (but unpackaged) file(s) found:
   /usr/share/glslang/glslang-config-version.cmake
   /usr/share/glslang/glslang-config.cmake
   /usr/share/glslang/glslang-targets-relwithdebinfo.cmake
   /usr/share/glslang/glslang-targets.cmake
```
Those files should be installed in `$(libdir)/cmake/glslang`

**Comment by jeremy-lunarg** [comment]
This sounds like an _RPM_ package maintenance issue. Can you file an issue with the package maintainer?

**Comment by kloczek** [comment]
So you want to say that you don;t knoiw what are the base paths in which cmake is looking for modules?

**Comment by jeremy-lunarg** [comment]
Please take a look at #3009. Let me know if it addresses this issue. Thanks.

**Comment by kloczek** [comment]
This PR still is incorrect.
Everywhere should be `s/${CMAKE_INSTALL_LIBDIR}/${PROJECT_NAME}/${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}/`
Base directory where cmake is lookimng for modules in subdirectories is `$(libdir)/cmake`.
