### ISSUE TITLE
`gl_MeshPrimitivesEXT` corruption

### ISSUE THREAD

**Issue by unit-a-user** [KhronosGroup/glslang#3017]
ANY case of `gl_MeshPrimitivesEXT` isn't passing any validation. Application always crash with vector error and invalid op code. 

(In my case is `gl_MeshPrimitivesEXT[localPrimitive].gl_PrimitiveID = int(primitiveId);`)

```
Vulkan Debug Error: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x21b6bf34b10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid capability operand: 5283
Vulkan Debug Error: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x21b6bf34b10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid capability operand: 5283
```

```
Debug Assertion Failed!

Program: ...dationLayers\build\install\lib\VkLayer_khronos_validation.dll
File: C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.34.31721\include\vector
Line: 50

Expression: can't dereference out of range vector iterator

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
```

**Comment by unit-a-user** [comment]
(In my case is `gl_MeshPrimitivesEXT[localPrimitive].gl_PrimitiveID = int(primitiveId);`)

**Comment by unit-a-user** [comment]
Also: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4515, https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4516

**Comment by spnda** [comment]
The validation layers (and the embedded spirv-val) don't know about the extension yet and give you that error because it simply doesn't know the operand IDs for the new extension. This is not an issue with glslang.

**Comment by greg-lunarg** [comment]
Based on comments from @spnda I will close. If you have any issues after updating spirv-val and VVL, please comment here.
