### ISSUE TITLE
GLSL: Add support for keyword `inline` and `noinline`

### ISSUE THREAD

**Issue by chirsz-ever** [KhronosGroup/glslang#3018]
`inline` and `noinline` are reserved keywords in OpenGL GLSL versions 1.40 and OpenGL ES ESSL versions 3.10, which are the lowest version requirement of [GL_KHR_vulkan_glsl](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt).

It is very suitable to set `Function Control` field for an [OpFunction](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpFunction) instruction when the source code uses `inline` or `noinline`.

Would This feature need to update `GL_KHR_vulkan_glsl`, or introduce a new extension?

**Comment by greg-lunarg** [comment]
> Would This feature need to update GL_KHR_vulkan_glsl, or introduce a new extension?

Yes, one of these would be needed to be able to add support.

**Comment by jbarnoin** [comment]
@greg-lunarg 
I've been looking for how to prevent a function being inlined in GLSL and found this issue. I don't quite understand why it was closed as completed above.
The spec still lists noinline as a keyword reserved for future use, and trying to use it in code results in a reserved keyword error. I haven't found an extension to allow this either.
SPIR-V supports this as of this commit, and so does HLSL, but I can't find anything about GLSL. https://github.com/KhronosGroup/SPIRV-Tools/pull/3858

Was this closed as completed by mistake or is there something else I'm missing?

**Comment by arcady-lunarg** [comment]
In the end it's a GLSL spec issue, because glslang is the GLSL reference compiler. Since there is no extension specification for this feature, we can't just implement something. You can open an issue in the [GLSL](https://github.com/KhronosGroup/GLSL) repository, or if you want to try your hand at spec writing, you can write an extension spec for this feature.

**Comment by jbarnoin** [comment]
@arcady-lunarg Right. For now I mostly wanted clarification that this issue wasn't really "completed" in the sense of the keywords now being functional in GLSL, despite the closing reason for this issue, to clear up any misunderstanding.

I guess your message provides this clarification for now, for anyone finding this issue who might think the feature has been integrated.

**Comment by arcady-lunarg** [comment]
I think it's more that we didn't give too much thought to which category of "closed" was being applied when clicking the button.

**Comment by jbarnoin** [comment]
I figured as much, thanks for clarifying.
