### ISSUE TITLE
'atomic counter types' : not allowed when using GLSL for Vulkan

### ISSUE THREAD

**Issue by vlj** [KhronosGroup/glslang#303]
When I'm compiling a shader with the -V command line argument it fails when I'm declaring "layout(binding = 0) uniform atomic_uint PixelCount;" with the following message :
"'atomic counter types' : not allowed when using GLSL for Vulkan"

With the -G flag it builds but emit the
 "TBD functionality: Is atomic_uint an opaque handle in the uniform storage class, or an addresses in the atomic storage class?"
 warning.
What is the replacement for atomic counter in GLSL for Vulkan ? Looking at the parser code it looks like there is no other way to emit the EbtAtomicUint token.

**Comment by johnkslang** [comment]
I believe this should work, but is a bit behind because Vulkan does not require this as a base capability.  (Need to verify.)

**Comment by Sheeg** [comment]
Is there an update on support for atomic counter types?

**Comment by thekitchensink** [comment]
Any updates yet?

**Comment by johnkslang** [comment]
OpenGL supports atomic_uint, but Vulkan does not, and glslang correctly reflects this.
