### ISSUE TITLE
glslang performance compared to naga 

### ISSUE THREAD

**Issue by KlingelingelingDerEiermann** [KhronosGroup/glslang#3035]
Hey i read this and i was a really bit shocked that naga is supposed to be 30x faster than glslang when compiling glsl code
http://kvark.github.io/naga/shader/2022/02/17/shader-translation-benchmark.html

What is the reason ? Just curious =)

**Comment by jeremy-lunarg** [comment]
It appears to be a translator; not a compiler.

**Comment by KlingelingelingDerEiermann** [comment]
> GLSL to SPIR-V
> [...]
> Nobody else processes GLSL inputs, so we are only comparing Naga with Glslang. Naga is roughly 30x faster. I’m sure Glslang does a lot of work in validating the incoming GLSL that we aren’t, so that explains some of that difference. It’s also probably trying to optimize the result. We’ll be working on configuring the build to do less of that.

It is GLSL -> SPIRV, so its a compiler. It is also a translator, because it can convert SPIRV -> GLSL

**Comment by greg-lunarg** [comment]
We are not sure offhand the reason for the difference. If you find out, let us know. Thanks!
