### ISSUE TITLE
How can i use glslang to get AST of a hlsl/glsl file?

### ISSUE THREAD

**Issue by cx-zzz** [KhronosGroup/glslang#3039]
I am a newer and i want to get AST of hlsl/glsl file to build a compute graph, but i dont konw how to do this, if anyone can tell me how or give me some demo codes?
Thank you!

**Comment by ProkopRandacek** [comment]
There is the `-i` option you can give to `glslangValidator`.

**Comment by cx-zzz** [comment]
Thank you for your reply, but i want to traverse the ast in my code, is this a way to do this?

**Comment by ProkopRandacek** [comment]
afaik there is no other way of getting the ast than the `-i` flag. And it is quite a bad way too, if you want to parse it.

Using entire compiler just for the parser is questionable. Especially when the ast is not meant to be exposed to other programs like here. Perhaps writing your own parser would be easier than dealing with this rather complex dependency?

Alternatively there is a https://github.com/gfx-rs/naga project that supports exporting the ast as a dot file, which is in my opinion way better option than the `-i` flag here. Although it does not support hlsl.

**Comment by jeremy-lunarg** [comment]
The AST interface isn't exported. If you're looking for examples for how you might consume AST, you can look at the traverser (GlslangToSpv.h) and spir-v builder (SpvBuilder.h).
