### ISSUE TITLE
PrimitiveTriangleIndicesEXT array size not matching OutputPrimitivesEXT

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/glslang#3041]
@pmistryNV for the VUID

> VUID-PrimitiveTriangleIndicesEXT-PrimitiveTriangleIndicesEXT-07058
The size of the array decorated with PrimitiveTriangleIndicesEXT must match the value specified by OutputPrimitivesEXT

If I have a GLSL shader such as 

```glsl
#version 460
#extension GL_EXT_mesh_shader : enable
layout(max_vertices = 1) out;
layout(max_primitives = 2) out;
layout(triangles) out;
void main()
{
    gl_PrimitiveTriangleIndicesEXT[0] = uvec3(1, 1, 1);
}
```

I get 

```swift
OpExecutionMode %main OutputPrimitivesEXT 2
OpDecorate %var BuiltIn PrimitiveTriangleIndicesEXT
%v3uint = OpTypeVector %uint 3
%uint_6 = OpConstant %uint 6
%array = OpTypeArray %v3uint %uint_6
%ptr = OpTypePointer Output %array
%var = OpVariable %ptr Output
```

So not sure if this is a Spec ambiguity or Glslang bug, but for `array size` I would expect `OpTypeArray` to be only `2` and not `6`

**Comment by pmistryNV** [comment]
Let me have a look at it. Thanks for pointing it out
