### ISSUE TITLE
gl_CullPrimitiveEXT producing invalid SPIR-V

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/glslang#3044]
@pmistryNV So trying to add more `spirv-val` support (https://github.com/KhronosGroup/SPIRV-Tools/pull/4957) and seems `spv_ext_meshShaderBuiltins_mesh` (`spv.ext.meshShaderBuiltins.mesh` test is failing from

> VUID-CullPrimitiveEXT-CullPrimitiveEXT-07036
The variable decorated with CullPrimitiveEXT must be declared as an array of boolean values

as I am getting an array of structs instead

```swift
%bool = OpTypeBool
%gl_MeshPerPrimitiveEXT = OpTypeStruct %int %int %int %bool %int
%_arr_gl_MeshPerPrimitiveEXT_uint_32 = OpTypeArray %gl_MeshPerPrimitiveEXT %uint_32
%_ptr_Output__arr_gl_MeshPerPrimitiveEXT_uint_32 = OpTypePointer Output %_arr_gl_MeshPerPrimitiveEXT_uint_32
%gl_MeshPrimitivesEXT = OpVariable %_ptr_Output__arr_gl_MeshPerPrimitiveEXT_uint_32 Output
```

Simple way to reproduce

```glsl
#version 460
#extension GL_EXT_mesh_shader : enable
layout(max_vertices=4) out;
layout(max_primitives=4) out;
layout(triangles) out;
void main() {
    gl_MeshPrimitivesEXT[0].gl_CullPrimitiveEXT = false;
}
```

**Comment by greg-lunarg** [comment]
@pmistryNV Any thoughts?

**Comment by pmistryNV** [comment]
Let me have a look

**Comment by pmistryNV** [comment]
Let me file a bug against the spec

**Comment by pmistryNV** [comment]
Filed https://gitlab.khronos.org/vulkan/vulkan/-/issues/3296 against the spec https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/CullPrimitiveEXT.html

**Comment by greg-lunarg** [comment]
As it has been decided that this is a problem with the VUID and not glslang, I am closing this.
