### ISSUE TITLE
ABI break between 11.11 and 11.12

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/glslang#3052]
Commit 11.12.0~18^2 changed the ABI of `struct TBuiltInResource`, but the SONAME did not change for the glslang 11.12 release. I think this _may_ be a problem because end-user programs are defining TBuiltInResource of their own and then probably passing it whereever else.
In a 11.11-based source (game) the `maxDualSourceDrawBuffersEXT` member would mean to a 11.12 system glslang `maxMeshOutputVerticesEXT`.

```
abidiff libglslang.so.11.11.0 libglslang.so.11.12.0

  [C] 'function int ShCompile(const ShHandle, const char* const*, const int, const int*, const EShOptimizationLevel, const TBuiltInResource*, int, int, bool, EShMessages)' at ShaderLang.cpp:1477:1 has some indirect sub-type changes:
    parameter 6 of type 'const TBuiltInResource*' has sub-type changes:
      in pointed to type 'const TBuiltInResource':
        in unqualified underlying type 'struct TBuiltInResource' at ResourceLimits.h:52:1:
          type size changed from 3072 to 3360 (in bits)
          9 data member insertions:
            'int maxMeshOutputVerticesEXT', at offset 2944 (in bits) at ResourceLimits.h:145:1
            'int maxMeshOutputPrimitivesEXT', at offset 2976 (in bits) at ResourceLimits.h:146:1
            'int maxMeshWorkGroupSizeX_EXT', at offset 3008 (in bits) at ResourceLimits.h:147:1
            'int maxMeshWorkGroupSizeY_EXT', at offset 3040 (in bits) at ResourceLimits.h:148:1
            'int maxMeshWorkGroupSizeZ_EXT', at offset 3072 (in bits) at ResourceLimits.h:149:1
            'int maxTaskWorkGroupSizeX_EXT', at offset 3104 (in bits) at ResourceLimits.h:150:1
            'int maxTaskWorkGroupSizeY_EXT', at offset 3136 (in bits) at ResourceLimits.h:151:1
            'int maxTaskWorkGroupSizeZ_EXT', at offset 3168 (in bits) at ResourceLimits.h:152:1
            'int maxMeshViewCountEXT', at offset 3200 (in bits) at ResourceLimits.h:153:1
          2 data member changes:
            'int maxDualSourceDrawBuffersEXT' offset changed from 2944 to 3232 (in bits) (by +288 bits)
            'TLimits limits' offset changed from 2976 to 3264 (in bits) (by +288 bits)
```

**Comment by jengelh** [comment]
gzdoom compiled with glslang 11.11 attempting to run on /usr/lib64/libglslang.so.11.12

![gzdoomGLS11-on-systemGLS12](https://user-images.githubusercontent.com/8861948/197651964-7bc91699-7e68-4c47-89af-16b53cf2ba27.png)

gzdoom compiled with glslang 11.12 attempting to run on /usr/lib64/libglslang.so.11.11

![gzdoomGLS12-on-systemGLS11](https://user-images.githubusercontent.com/8861948/197652006-289dc115-9842-4265-a49e-1bb39f2f50db.png)

**Comment by greg-lunarg** [comment]
Yes, technically this can be considered an ABI change requiring a bump in the major version.

Frankly, this pieced of the interface is problematic and should be rewritten to avoid constant major revision bumping.

In the meantime, I would suggest changing your app to future-proof against this struct changing in non-compatible ways as it has done here.

I would suggest changing your app to always allocate and zero this struct based on its declaration in ResourceLimits.h and initialize the members you care about and know about in a symbolic manner.

**Comment by jengelh** [comment]
>I would suggest changing your app to always allocate and zero this struct based on its declaration in ResourceLimits.h

If my program has a `int f(const TBuiltInResource *r) { return r->limits.whileLoops; }`, and a (claiming-to-be-compatible-by-way-of-same-SONAME) libglslang changes its own idea of what a TB should be, the existing app binary is just dead in the water. I do not see how a dynamic allocation would change this. glslang can only fix this by making TBuiltInResource an incomplete type (to the public, i.e. header consumers) and providing _set/_getters.

**Comment by greg-lunarg** [comment]
I agree TB is better as an opaque type with default initialization and _set/_getters.

However, glslang lib is currently only delivered for static linking. So if anyone picks it up, they need to pretty much rebuild anyway, so any changes to TB should be picked up. Right?

One way or the other, this interface needs to be improved to future-proof it from changes to TB. 

If we stay with a struct TB, we could provide a default initialization value for it. There is such a thing in Standalone, so we could move that into the public interface. Would that work?

Somehow we have managed to get this far with TB as a struct and I am worried about changing it to an opaque class and the larger disruption incompatibility and disruption would cause.

**Comment by greg-lunarg** [comment]
This is related: https://github.com/KhronosGroup/glslang/issues/2822

**Comment by jengelh** [comment]
>glslang lib is currently only delivered for static linking

I don't think so. glslang has supported shared library building for a long time. Devs are aware since at least issue #2373 / commit fbe9a23baf2cb020fe3f80d68d972e2a97d9b954 , that glslang is built as a shared library by users.

**Comment by greg-lunarg** [comment]
> I don't think so. glslang has supported shared library building for a long time. Devs are aware since at least issue https://github.com/KhronosGroup/glslang/issues/1484 / commit https://github.com/KhronosGroup/glslang/commit/fbe9a23baf2cb020fe3f80d68d972e2a97d9b954 , that glslang is built as a shared library by users.

Ah, for Linux. OK.

**Comment by jeremy-lunarg** [comment]
We've incremented the major revision number in our latest release to reflect this breakage. Sorry for the inconvenience.
