### ISSUE TITLE
Token pasting not working

### ISSUE THREAD

**Issue by gregschlom** [KhronosGroup/glslang#3072]
Given the following shader program:

test.comp:
```glsl
#version 450

#define FOO 1

void main(void) {
  int a = 1 ## FOO;
}
```

Compiled with `glslangValidator -E .\test.comp`, I get the following error:

```
ERROR: .\test.comp:6: '#' : preprocessor directive cannot be preceded by another token
ERROR: 1 compilation errors.  No code generated.
```

Here's the output of `glslangValidator -v`:

```
Glslang Version: 10:11.8.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.8.0
GLSL Version: 4.60 glslang Khronos. 11.8.0
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 10
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```

Regular macro processing works. For example, compiling this program:
```glsl
#version 450

#define FOO 1

void main(void) {
  int a = FOO;
}
```

Correctly outputs:
```
#version 450



void main(void){
  int a = 1;
}
```

I'm really not sure what's going on here. I tried both `glslc` and `glslangValidator`. It looks like a preprocessor bug maybe?

In theory token pasting should be handled [here](https://github.com/KhronosGroup/glslang/blob/master/glslang/MachineIndependent/preprocessor/PpScanner.cpp#L1139). However for some reason this is not working and I'm getting [this error message instead](https://github.com/KhronosGroup/glslang/blob/master/glslang/MachineIndependent/preprocessor/PpScanner.cpp#L1154)

I'd appreciate any help.

**Comment by greg-lunarg** [comment]
The ## can only appear in a #define. I believe this is a standard C preprocessor restriction.

Please reopen if you believe my answer to be in error.
