### ISSUE TITLE
How to distinguish whether a symbol has an type keyword in front of it or not in AST?

### ISSUE THREAD

**Issue by Mirocos** [KhronosGroup/glslang#3078]
Suppose I have such glsl code
```glsl
1  vec3 node0 = vec3(0.1);
2  vec3 node1 = vec3(0.2);
3  node0 = node0 * 2.0;
```
The only way I can find to distinguish the different of `node0` in line `3` and `node1` in line `2` is that in glslang, AST traverser will traverse `node1`  deeper than `node0`, and this only happned if this two symbols have same ancestor, and we start travesing from that ancestor.

But Is there any members or attributes in `TIntermSymbol` that could mark this feature?

**Comment by greg-lunarg** [comment]
What feature do you need marked?

**Comment by greg-lunarg** [comment]
OK, you want to know if there is a way to tell if a statement in the AST was preceded by a type. The answer is unfortunately no.
