### ISSUE TITLE
glslangValidator: Missing generation of necessary capabilities for use of OpGroupNonUniformF*

### ISSUE THREAD

**Issue by mmoult** [KhronosGroup/glslang#3084]
According to the SPIR-V spec, the operations OpGroupNonUniformFAdd, OpGroupNonUniformFMul, OpGroupNonUniformFMax, and OpGroupNonUniformFMin require three capabilities: GroupNonUniformArithmetic, GroupNonUniformClustered, and GroupNonUniformPartitionedNV (see https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformFAdd). When emitting SPIR-V for some GLSL code, the validator is producing the group non uniform SPIR-V operation, but not all of its necessary capabilities.

For example, when validating the below GLSL fragment shader:
```
#version 430
#extension GL_KHR_shader_subgroup_clustered: enable
layout(location = 0) out uint result;
void main (void)
{
    subgroupClusteredAdd(1.0, 1);
    result = 0;
}
```
the validator emits
```
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 11
; Bound: 15
; Schema: 0
               OpCapability Shader
               OpCapability GroupNonUniform
               OpCapability GroupNonUniformClustered
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %result
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 430
               OpSourceExtension "GL_KHR_shader_subgroup_basic"
               OpSourceExtension "GL_KHR_shader_subgroup_clustered"
               OpName %main "main"
               OpName %result "result"
               OpDecorate %result Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %float_1 = OpConstant %float 1
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
     %uint_3 = OpConstant %uint 3
%_ptr_Output_uint = OpTypePointer Output %uint
     %result = OpVariable %_ptr_Output_uint Output
     %uint_0 = OpConstant %uint 0
       %main = OpFunction %void None %3
          %5 = OpLabel
         %11 = OpGroupNonUniformFAdd %float %uint_3 ClusteredReduce %float_1 %uint_1
               OpStore %result %uint_0
               OpReturn
               OpFunctionEnd
```

Note that `OpGroupNonUniformFAdd` (see %11) is emitted for the `subgroupClusteredAdd` call in the original source. Similarly, a call to `subgroupClusteredMul` emits OpGroupNonUniformFMul, `subgroupClusteredMax` emits OpGroupNonUniformFMax, and `subgroupClusteredMin` emits OpGroupNonUniformFMin.

In each of these cases, the required GroupNonUniformClustered capability is generated, but not GroupNonUniformArithmetic and GroupNonUniformPartitionedNV.

The glslangValidator which produced this erroneous SPIR-V was built from source on Linux on commit `2b2523fb` from the master branch. Since OpGroupNonUniformF* operations are only available starting in SPIR-V version 1.3, to reproduce this error, you will need to specify a higher target than default (assuming that the fragment shader is called "test.frag"):
```
glslangValidator --target-env spirv1.3 -V test.frag
```
The problem also appears on targets SPIRV1.4, SPIRV1.5, and SPIRV1.6.

**Comment by greg-lunarg** [comment]
From SPIR-V 1.6 spec, section 2.1 Language Capabilities:

```
If an instruction, enumerant, or other feature specifies multiple enabling capabilities, only one such
capability needs to be declared to use the feature.
```

I believe in each of the cases you describe, at least one of the required capabilities was declared, so I believe the code generated by glslang for all these cases is valid.

Please respond to this issue if you think I have erred.
