### ISSUE TITLE
glslangValidator: Generation of undefined operation (OpGroupNonUniformPartitionNV) in SPIR-V

### ISSUE THREAD

**Issue by mmoult** [KhronosGroup/glslang#3085]
According to the spec, `OpGroupNonUniformPartitionNV` is currently reserved, but not defined (see https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformPartitionNV). However, the validator is emitting that instruction for GLSL sources with call(s) to `subgroupPartitionNV`. 

For example, when validating the below GLSL geometry shader:
```
#version 410
#extension GL_NV_shader_subgroup_partitioned: enable
layout(lines) in;
layout(points, max_vertices = 1) out;

void main (void)
{
  subgroupPartitionNV(0);
}
```
the validator produces the following (disassembled) SPIR-V:
```
; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 11
; Bound: 11
; Schema: 0
               OpCapability Geometry
               OpCapability GroupNonUniformPartitionedNV
               OpExtension "SPV_NV_shader_subgroup_partitioned"
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Geometry %main "main"
               OpExecutionMode %main InputLines
               OpExecutionMode %main Invocations 1
               OpExecutionMode %main OutputPoints
               OpExecutionMode %main OutputVertices 1
               OpSource GLSL 410
               OpSourceExtension "GL_KHR_shader_subgroup_basic"
               OpSourceExtension "GL_NV_shader_subgroup_partitioned"
               OpName %main "main"
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
       %uint = OpTypeInt 32 0
     %v4uint = OpTypeVector %uint 4
       %main = OpFunction %void None %3
          %5 = OpLabel
         %10 = OpGroupNonUniformPartitionNV %v4uint %int_0
               OpReturn
               OpFunctionEnd
```
which uses the currently undefined operation, `OpGroupNonUniformPartitionNV`.

If the operation was to be formally defined by the specification now, the current codegen may be correct for the new SPIR-V version, but codegen would need to be altered for all versions before the operation was first defined (unless the operation was defined retroactively through SPIR-V 1.3).

The glslangValidator which produced this erroneous SPIR-V was built from source on Linux on commit `2b2523fb` from the master branch. Since `subgroup op` is only available starting in SPIR-V version 1.3, to reproduce this error, you will need to specify a higher target than default (assuming that the geometry shader is called "test.geom"):
```
glslangValidator --target-env spirv1.3 -V test.geom
```
The problem also appears on targets SPIRV1.4, SPIRV1.5, and SPIRV1.6.

**Comment by greg-lunarg** [comment]
This seems like an oversight on the part of the SPIR-V spec guardians. Looking at the spec for the GLSL extension GL_NV_shader_subgroup_partitioned,  subgroupPartitionNV maps directly to OpGroupNonUniformPartitionNV, so it seems         OpGroupNonUniformPartitionNV is well defined.

So I would consider this a bug with the SPIR-V spec. I would suggest opening an issue there.
