### ISSUE TITLE
Constant unsigned integer expressions in HLSL unsupported

### ISSUE THREAD

**Issue by TheJackiMonster** [KhronosGroup/glslang#3089]
I was trying to compile the shadow denoiser shaders from [here](https://github.com/GPUOpen-Effects/FidelityFX-Denoiser) with Glslang but I ran into an issue:

```
[ERROR]: Shader parsing failed {
ERROR: /tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h:293: ':' : Expected 
ERROR: /tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h:293: 'initializer' : Expected 
ERROR: /tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h:293: 'b10u' : unknown variable 
ERROR: /tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h:293: ';' : Expected 
ERROR: /tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h:293: 'then statement' : Expected 
ERROR: /tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h:293: 'declaration' : Expected 
/tmp/vkcv_tmp_VlNB6M/ffx_denoiser_shadows_tileclassification.h(293): error at column 47, HLSL parsing failed.
ERROR: 7 compilation errors.  No code generated.
```

For context: I compile shaders in a temporary directory to handle include paths without the need of shipping the shaders in local directories as permanent files.

Anyway the causing problem is that these HLSL shaders utilize constant expression for their bitmasks like this:
```
#define TILE_META_DATA_CLEAR_MASK 0b01u
#define TILE_META_DATA_LIGHT_MASK 0b10u
```

These constant expressions seem not be handled properly though. Because the parser tells me, it wouldn't expect such an expression or it tries to parse it as a variable which it can't find. I'm usually not working with HLSL. So I'm not sure whether these expressions are in spec or not. But I assume it should be interpreted as binary values (0b01u -> 1) and (0b10u -> 2).

**Comment by greg-lunarg** [comment]
Yes, you have found an issue. The following is correctly compiled by dxc but glslang gives errors as above:

float4 MainPs(void) : SV_Target0
{
      float4 vTest = float4(0.0,0.0,0.0,0.0);
      uint u = vTest.x > 0.0 ? 0b010101u : 0u;

      return vTest;
}

FWIW, the 0b syntax seems to be accepted as an initializer by glslang, but is not correctly generating the right value to store into u. The following compiles with compiler error, but does not generate the correct value for the 0b constant:

float4 MainPs(void) : SV_Target0
{
      float4 vTest = float4(0.0,0.0,0.0,0.0);
      uint u = 0b010101u;

      return vTest;
}
