### ISSUE TITLE
Push constant nested struct alignment/padding issue

### ISSUE THREAD

**Issue by rhuff-lucasfilm** [KhronosGroup/glslang#3091]
We have the following set of structures that we are using for push constants:

struct StructA
{
uint64_t valA; // this is technically a reference to a buffer in our shader but I don't think that matters for this discussion
uint valB;
uint valC;
uint valD;
};

struct StructB
{
StructA aValues;
uint valE;
uint valF;
};

I think that struct A will have an alignment of 8 bytes and size of 24. The Vulkan spec points to section 7.6.22 "Standard Uniform Block Layout" of the OpenGL specification which says:

"If the member is a structure, the base alignment of the structure is N, where N is the largest base alignment value of any of its members, and rounded up to the base alignment of a vec4. The individual members of this substructure are then assigned offsets by
applying this set of rules recursively, where the base offset of the first member of the sub-structure is equal to the aligned offset of the structure. The structure may have padding at the end; the base offset of the member following the sub-structure is rounded up to
the next multiple of the base alignment of the structure."

By those rules the base offset of the member following the sub structure (valE) is rounded up to the next multiple of the base alignment of the structure (8). However, spirv-dis shows that the offset of valE in this scenario is 20 when I believe it should be 24.

This is easy to work-around by inserting explicit padding or making valD a uint64_t so not a show-stopper but it did take some time to diagnose and seems like an error WRT the spec.

This is with Vulkan SDK 1.3.224.0 and the spv was generated with "glslangValidator --target-env vulkan1.2".

I incorrectly posted this in the SPIRV-Tools repository first (https://github.com/KhronosGroup/SPIRV-Tools/issues/5010).

**Comment by greg-lunarg** [comment]
Agreed, valE should be aligned on 8 bytes ie at offset 24.

**Comment by greg-lunarg** [comment]
Given the following GLSL:

```
#version 400

#extension GL_EXT_shader_explicit_arithmetic_types_int64: require

struct StructA
{
    uint64_t valA;
    uint valB;
    uint valC;
    uint valD;
};

struct StructB
{
    StructA aValues;
    uint valE;
    uint valF;
};

layout(push_constant) uniform Material {
    StructB sb;
} matInst;

void main()
{
}

```

compiled with:

`glslangValidator.exe -V --target-env vulkan1.2 -o t.vert.spv t.vert`

I get the following SPIR-V:

```
               OpCapability Shader
               OpCapability Int64
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %matInst
               OpSource GLSL 400
               OpSourceExtension "GL_EXT_shader_explicit_arithmetic_types_int64"
               OpName %main "main"
               OpName %StructA "StructA"
               OpMemberName %StructA 0 "valA"
               OpMemberName %StructA 1 "valB"
               OpMemberName %StructA 2 "valC"
               OpMemberName %StructA 3 "valD"
               OpName %StructB "StructB"
               OpMemberName %StructB 0 "aValues"
               OpMemberName %StructB 1 "valE"
               OpMemberName %StructB 2 "valF"
               OpName %Material "Material"
               OpMemberName %Material 0 "sb"
               OpName %matInst "matInst"
               OpMemberDecorate %StructA 0 Offset 0
               OpMemberDecorate %StructA 1 Offset 8
               OpMemberDecorate %StructA 2 Offset 12
               OpMemberDecorate %StructA 3 Offset 16
               OpMemberDecorate %StructB 0 Offset 0
               OpMemberDecorate %StructB 1 Offset 24
               OpMemberDecorate %StructB 2 Offset 28
               OpMemberDecorate %Material 0 Offset 0
               OpDecorate %Material Block
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %ulong = OpTypeInt 64 0
       %uint = OpTypeInt 32 0
    %StructA = OpTypeStruct %ulong %uint %uint %uint
    %StructB = OpTypeStruct %StructA %uint %uint
   %Material = OpTypeStruct %StructB
%_ptr_PushConstant_Material = OpTypePointer PushConstant %Material
    %matInst = OpVariable %_ptr_PushConstant_Material PushConstant
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpReturn
               OpFunctionEnd
```

Notice in particular:

`OpMemberDecorate %StructB 1 Offset 24`

Please supply a compilable shader and command  line that recreates the problem you are seeing and I will re-open.

**Comment by rhuff-lucasfilm** [comment]
I hadn't realized the difference caused by scalar block layout WRT to struct padding so I had over-simplified my test case.  My local results match yours and our production code is specifying 'scalar' in the layout for these.

If I build a spv file with your source but with the added scalar layout for the pushbuffer then trying to get spirv-cross to output glsl with "spirv-cross -V test.vert.spv" outputs:
"SPIRV-Cross threw an exception: Buffer block cannot be expressed as any of std430, std140, scalar, even with enhanced layouts. You can try flattening this block to support a more flexible layout."

Which makes me wonder how I ever got the "layout(push_constant, std430) uniform Material" output from spirv-cross based on our production shaders when I looked at this previously.  Anyway, that is something for me to sort out.

Thanks!
