### ISSUE TITLE
undefined reference to 'glslang::GlslangToSpv'

### ISSUE THREAD

**Issue by JophiMa** [KhronosGroup/glslang#3106]
I'm currently trying  to write a simple function to compile glsl to spir-v for my project.

Used libraries:
libshaderc_combined, libSPIRV, libSPIRV-Tools, libSPIRV-Tools-opt
These were installed using pacman from the official arch linux repo and not built from source, so they are potentially behind the current master branch. However seeing as the version is stated as 11.13.0 it should be up-to-date from what i can see.

My compiler flags include  -L./lib,  -lvulkan, -ldl, -lpthread, -glfw3, -lglslang, -lSPIRV, -lSPIRV-Tools, -lSPIRV-Tools-opt, -shaderc_combined in that order.

I have also already verified that the function exists inside my copy of libSPIRV.a using "nm -A libSPIRV.a | grep GlslangToSpv" so in theory at least this should compile no problem. However as stated in the title i get the following:

`/usr/bin/ld: ./lib/libshaderc_combined.a(compiler.cc.o): in function shaderc_util::Compiler::Compile(shaderc_util::string_piece const&, EShLanguage, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, std::function<EShLanguage (std::ostream*, shaderc_util::string_piece const&)> const&, shaderc_util::CountingIncluder&, shaderc_util::Compiler::OutputType, std::ostream*, unsigned long*, unsigned long*) const':
(.text+0x7a2b): undefined reference to glslang::GlslangToSpv(glslang::TIntermediate const&, std::vector<unsigned int, std::allocator<unsigned int> >&, glslang::SpvOptions*)'`

I haven't found anyone mention this on here, so if this has a fix in master please let me know.
Cheers.

**Comment by greg-lunarg** [comment]
What if you use this order?: -L./lib, -lvulkan, -ldl, -lpthread, -glfw3, -lSPIRV, -lSPIRV-Tools, -lSPIRV-Tools-opt, -shaderc_combined, -lglslang

**Comment by greg-lunarg** [comment]
There is more than one library for glslang. Replace -lglslang with

-lglslang, -lGenericCodeGen, -lglslang-default-resource-limits, -lHLSL, -lMachineIndependent, -lOGLCompiler, -lOSDependent

**Comment by greg-lunarg** [comment]
Or try moving -lSPIRV to the end:

-L./lib, -lvulkan, -ldl, -lpthread, -glfw3, -lSPIRV-Tools, -lSPIRV-Tools-opt, -shaderc_combined, -lglslang, -lSPIRV

or both.

**Comment by greg-lunarg** [comment]
Sorry. It was just brought to my attention that -shaderc_combined should contain all dependencies. So having that at the end should provide a sufficient backstop.

What is your complete compiler command? On Linux, all of your project files (.o, .cpp, etc) must go before the -L and -l options. Is that the case?

**Comment by jeremy-lunarg** [comment]
A couple of notes:

1. You appear to be using `libshaderc_combined.a`. That is provided by the [shaderc](https://github.com/google/shaderc/tree/main/libshaderc) repository; not this repository.
2. I was able to successfully compile the "[smoke test](https://github.com/google/shaderc/blob/main/libshaderc/src/shaderc_c_smoke_test.c)" provided by shaderc using the following command-line:
`g++ -I ./include/shaderc/ -L ./lib/ shaderc_c_smoke_test.c -l:libshaderc_combined.a -lpthread`
My directory structure was as follows:
```
<root>/shader_c_smoke_test.c
<root>/include/shaderc/shaderc.h
<root>/lib/libshaderc_combined.a
```

**Comment by jeremy-lunarg** [comment]
I'm closing this for now as I don't believe there is an issue with glslang. Please reply if you disagree. Thanks.
