### ISSUE TITLE
Please tag the new version for ArchLinux and other Linux distributions

### ISSUE THREAD

**Issue by vityafx** [KhronosGroup/glslang#3109]
ArchLinux package relies on the tags in the repository. The latest tag is `11.13.0`, and it doesn't contain the critical fix that was done a while ago: https://github.com/KhronosGroup/glslang/commit/bec8359bf7e22c7106b87f2356ef4a5571489861

Perhaps, some other Linux distributions also depend on the tag.
This is a low-effort job; please tag either `11.13.1` or `11.14.0` depending on your choice.

**Comment by jeremy-lunarg** [comment]
We'll be creating a 11.14.0 soon which will include that fix.

**Comment by jeremy-lunarg** [comment]
Due to an accidental breakage in one of the ABIs, we've decided to tag the new release using an incremented major revision. Please see the release notes for 12.0.0. Thanks.
