### ISSUE TITLE
macro expanded twice, leading to unexpected generated code.

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#3112]
This was originally filed as https://github.com/google/shaderc/issues/1288
The original submitter is @jeroenbakker-atmind, a Blender developer.

It seems macros that are used as parameters to another macro call can be expanded twice.
See the expression `m(pPosition)`.

This is a minimal reproducer:

```
#version 450

layout(push_constant) uniform constants {
  vec4 pPosition;
}
PushConstants;
#define pPosition (PushConstants.pPosition)

layout(location=0) out vec3 o;

#define m(p)  vec4(p,1.0);

void main() {
  gl_Position = m(pPosition);
}
```

glslangValidator -E y.vert shows:

```
$ glslangValidator -E y.vert
#version 450

layout(push_constant)uniform constants {
  vec4 pPosition;
}
PushConstants;


layout(location = 0)out vec3 o;



void main(){
  gl_Position = vec4((PushConstants .(PushConstants . pPosition)), 1.0);;
}
```

I'm not enough of an expert preprocessor macro expansion.  The Glsl 4.5 spec says

> #define and #undef functionality are defined as is standard for C++ preprocessors for macro definitions
both with and without macro parameters.

When I use `clang -E` to run the C++ preprocessor I get this main function out of it:
```
void main() {
  gl_Position = vec4((PushConstants.pPosition),1.0);;
}
```

**Comment by arcady-lunarg** [comment]
This does appear to be a bug, given the spec language and the fact that both GCC and Clang behave differently from glslang here. I'm taking a look at this, and have a preliminary fix though it needs more testing.
