### ISSUE TITLE
Compiling GLSL/ESSL to SPIR-V for Vulkan with precision decorations.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glslang#312]
Some Vulkan drivers use the precision decorations in SPIR-V for certain optimizations. However, when compiling regular GLSL (say #version 440 core) no precision decorations show up in the SPIR-V. When compiling ESSL (say #version 310 es) the precision decorations are maintained but there is no support for enhanced layouts which limits the use of push constants.

**Comment by johnkslang** [comment]
Yes, this is a new need to simultaneously have desktop features plus **ReducedPrecision**.

However, glslang is conforming to the current specifications in that desktop #versions are not allowed to assign semantic meaning to precision qualifiers.

Given that the need is real, but the specifications say not to, Khronos will discuss changing the specifications.  Fundamentally, this has been a breakage in the guiding principle "same syntax => same semantics", and strategically, it would be good to go in the direction of fixing that.

Some analysis is needed for both glslang and the specifications regarding any desktop paths that have been able to ignore precision qualifiers and hence have some yet-to-be-resolved interactions with precision qualifiers.

Expect an update later this week.

**Comment by mre4ce** [comment]
Thanks John! Instead of adding ReducedPrecision to the desktop versions, I have made a local change to glslang to allow GL_ARB_enhanced_layouts with #version 310 es, which suits my purposes right now.

**Comment by johnkslang** [comment]
This was fixed in Khronos long ago, to have desktop GLSL pass on precision qualifiers to SPIR-V, instead of dropping them.
