### ISSUE TITLE
Glsl/CompileToSpirv14Test.FromFile failures with latest SPIRV-Tools

### ISSUE THREAD

**Issue by amaiorano** [KhronosGroup/glslang#3124]
The latest SPIRV-Tools has added new validation that makes some of the Glsl/CompileToSpirv14Test.FromFile fail, specifically:

```
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] Glsl/CompileToSpirv14Test.FromFile/spv_ext_meshShaderBuiltins_mesh, where GetParam() = "spv.ext.meshShaderBuiltins.mesh"
[  FAILED  ] Glsl/CompileToSpirv14Test.FromFile/spv_ext_meshShaderRedeclBuiltins_mesh, where GetParam() = "spv.ext.meshShaderRedeclBuiltins.mesh"
[  FAILED  ] Glsl/CompileToSpirv14Test.FromFile/spv_460_subgroupEXT_mesh, where GetParam() = "spv.460.subgroupEXT.mesh"
```

See [here for a log from our bot](https://fusion2.corp.google.com/invocations/146f30ad-f9ba-4b3b-b3d9-e61e939b23ff/targets/graphics_shader_compiler%2Fspirv-tools%2Fshaderc-smoketest%2Fcontinuous/log).

The diff is because of validation errors like:
```
The following warnings/errors occurred:
error: SPIRV-Tools Validation Errors
error: [VUID-CullPrimitiveEXT-CullPrimitiveEXT-07036] According to the Vulkan spec BuiltIn CullPrimitiveEXT variable needs to be a boolean array.Member #3 of struct ID <90> is not an array.
  %gl_MeshPerPrimitiveEXT = OpTypeStruct %int %int %int %bool %int
  ```

I believe the tests need to be updated to pass validation, and the expectations updated as well.

**Comment by dneto0** [comment]
The SPIRV-Tools change https://github.com/KhronosGroup/SPIRV-Tools/pull/5080 is from @spencer-lunarg

**Comment by greg-lunarg** [comment]
The prevailing opinion is that glslang and its tests are correct, and the Vulkan spec and https://github.com/KhronosGroup/SPIRV-Tools/pull/5080 are in error. Please see https://github.com/KhronosGroup/glslang/issues/3044.
