### ISSUE TITLE
mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by amayra** [KhronosGroup/glslang#3138]
can't run mpv when i use the build [glslang](https://github.com/KhronosGroup/glslang) from the git 

for more info you can check this issue here https://github.com/mpv-player/mpv/issues/11320

**Comment by arcady-lunarg** [comment]
The major version of glslang was bumped from 11 to 12 after an inadvertent ABI break. Building glslang version 12.x produces libglslang.so.12, while libglslang.so.11 would only be present if building earlier versions. I don't think this is a glslang problem.
