### ISSUE TITLE
Build failing with GCC13 on master commit

### ISSUE THREAD

**Issue by DeadSix27** [KhronosGroup/glslang#3139]
`glslang/glslang/MachineIndependent/SymbolTable.h:70:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?`

Somewhere it forgets to include cstdint, I'm using latest MinGW commit and GCC13.0.1

**Comment by JohannesKauffmann** [comment]
This is not MinGW specific, but GCC 13. See https://gcc.gnu.org/gcc-13/porting_to.html.

**Comment by DeadSix27** [comment]
> This is not MinGW specific, but GCC 13. See https://gcc.gnu.org/gcc-13/porting_to.html.

Ah thanks for clarifying, makes sense.

**Comment by hydra3333** [comment]
Hi.

Just a gentle prompt to please apply the patch asap.

Without it some mingw based builds systems, including MABS, cannot build your product ... which is a great deal less than ideal :)
