### ISSUE TITLE
2 strange code fragments

### ISSUE THREAD

**Issue by mjunix** [KhronosGroup/glslang#3142]
1.
https://github.com/KhronosGroup/glslang/blob/6d41bb9c557c5a0eec61ffba1f775dc5f717a8f7/glslang/HLSL/hlslParseHelper.cpp#L7564-L7568

The check `candidateList[0]->getBuiltInOp() == EOpMethodAppend` is repeated on lines 7564 and 7568. Perhaps second instance is just redundant or perhaps it should have been checked against something else?

2.
https://github.com/KhronosGroup/glslang/blob/6d41bb9c557c5a0eec61ffba1f775dc5f717a8f7/SPIRV/SpvBuilder.cpp#L2761-L2762
`texArgs`-array is initialized to size 10. Then a lot of statements of the form `texArgs[numArgs++] = ...` follows. I don't know if it it possible in practice but isn't there a possibility of `numArgs` going out of bounds?

**Comment by greg-lunarg** [comment]
> Perhaps second instance is just redundant or perhaps it should have been checked against something else?

I think the duplicate was added as they did not notice it was already included above. I think it is just redundant and I will submit a PR to remove it.

**Comment by greg-lunarg** [comment]
> isn't there a possibility of numArgs going out of bounds?

Well, maybe not today, but possibly tomorrow. I will recode with something a little more future-proof.

**Comment by arcady-lunarg** [comment]
Taking this one from Greg per his suggestion.
