### ISSUE TITLE
Is the ENABLE_GLSLANG_JS and ENABLE_GLSLANG_WEBMIN working?

### ISSUE THREAD

**Issue by SergioRZMasson** [KhronosGroup/glslang#3149]
Hi,

I'm trying to reduce the size of a binary that consumes glslang as a library. Since my shaders all follow GLES 310 for the web I'm trying enable ENABLE_GLSLANG_WEBMIN in order to strip out all unnecessary glslang code. However, when enable that in CMake I get lots of compiler errors. Is that feature ready?

**Comment by arcady-lunarg** [comment]
That option is meant for building glslang itself for the web, i.e. to run as a WebAssembly binary. If you're not doing that, I would recommend just compiling with `-DENABLE_HLSL=OFF` and possibly using clang rather than gcc, which produces a marginally smaller binary in my quick experiment.

**Comment by SergioRZMasson** [comment]
I'm currently using MSVC from the 12.0 branch. I run the cmake config with the -DENABLE_HLSL=OFF -DENABLE_GLSLANG_JS=ON and -DENABLE_GLSLANG_WEBMIN=ON. I'm using Visual Studio 2019 and targeting x64 Release. 

Once I try to build the glslang.js project I get multiple compiler errors such as:

```
5>D:\glslang\glslang\Include\../Include/Types.h(540,9): error C2065: 'nullInit': undeclared identifier
```

Look at Types.h I see:

```
// drop qualifiers that don't belong in a temporary variable
    void makeTemporary()
    {
        semanticName = nullptr;
        storage = EvqTemporary;
        builtIn = EbvNone;
        clearInterstage();
        clearMemory();
        specConstant = false;
        nonUniform = false;
        nullInit = false;
        defaultBlock = false;
        clearLayout();
#ifndef GLSLANG_WEB
        spirvStorageClass = -1;
        spirvDecorate = nullptr;
        spirvByReference = false;
        spirvLiteral = false;
#endif
    }
```

It seems like nullInit is not been guarded by #ifndef GLSLANG_WEB, that's why I though this feature might not be fully implemented. Am I doing something wrong? Or is the Visual Studio workflow not supported for this flag?

**Comment by SergioRZMasson** [comment]
I also get similar errors when compiling main using those same flags in Ubuntu 20.04 using gcc

**Comment by SergioRZMasson** [comment]
@arcady-lunarg , do you guys have some particular instructions on how to use those flags properly?

**Comment by arcady-lunarg** [comment]
We have since gotten rid of the `ENABLE_GLSLANG_WEB` option entirely, so it won't be causing build issues anymore.
