### ISSUE TITLE
Upstream, libplacebo now fails to build because glslang no longer installs a header file it requires

### ISSUE THREAD

**Issue by hydra3333** [KhronosGroup/glslang#3150]
Hello.

Upstream, libplacebo now fails to build because glslang no longer installs 'Public/ResourceLimits.h' into 'include/glslang/Public/'.

It seems it used to get installed until fairly recently (the last 3 weeks or so ?).

These configure options have remained unchanged, so it's not that :-

	'configure_options' : '. {cmake_prefix_options} -DCMAKE_INSTALL_PREFIX={target_prefix} '
		'-DCMAKE_BUILD_TYPE=Release '
		'-DUNIX=OFF '
		'-DBUILD_SHARED_LIBS=OFF '
		'-DBUILD_EXTERNAL=OFF '
		'-DSKIP_GLSLANG_INSTALL=OFF '
		'-DENABLE_GLSLANG_INSTALL=ON '
		'-DENABLE_GLSLANG_BINARIES=OFF '
		'-DENABLE_GLSLANG_JS=OFF '
		'-DENABLE_OPT=ON '
		'-DENABLE_CTEST=OFF '
		'-DENABLE_GLSLANG_WEBMIN=OFF '
		'-DENABLE_SPVREMAPPER=ON '
		'-DUSE_CCACHE=OFF '

How do we fix it ?

Cheers

**Comment by greg-lunarg** [comment]
Yes, sorry, this is a regression. I will fix.
