### ISSUE TITLE
VK_EXT_mesh_shader local workgroup size (maxTaskWorkGroupSize) gives compiler error

### ISSUE THREAD

**Issue by rsahlin** [KhronosGroup/glslang#3151]
When compiling a task shader using a local_size_x of 1024, on a device that supports this max task workgroup size, gives compiler error.
ERROR: test.task:6: 'local_size' : too large, see gl_MaxTaskWorkGroupSizeEXT

Using VulkanSDK  1.3.239 (shaderc v2023.1 v2023.1)

The task shader:
```
#version 450
 
#extension GL_EXT_mesh_shader : require


layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_WorkGroupID.x * gl_WorkGroupSize.x + gl_LocalInvocationID.x;
    EmitMeshTasksEXT(1, 1, 1);
}
```
Run on an AMD GPU (win 11 using beta adrenalin driver) that reports the following VkPhysicalDeviceMeshShaderPropertiesEXT using vulkaninfosdk.exe

```
VkPhysicalDeviceMeshShaderPropertiesEXT:
----------------------------------------
        maxTaskWorkGroupTotalCount            = 67107840
        maxTaskWorkGroupCount: count = 3
                65535
                65535
                65535
        maxTaskWorkGroupInvocations           = 1024
        maxTaskWorkGroupSize: count = 3
                1024
                1024
                1024
        maxTaskPayloadSize                    = 16384
        maxTaskSharedMemorySize               = 65520
        maxTaskPayloadAndSharedMemorySize     = 81920
        maxMeshWorkGroupTotalCount            = 67107840
        maxMeshWorkGroupCount: count = 3
                65535
                65535
                65535
        maxMeshWorkGroupInvocations           = 256
        maxMeshWorkGroupSize: count = 3
                256
                256
                256
        maxMeshSharedMemorySize               = 65520
        maxMeshPayloadAndSharedMemorySize     = 65520
        maxMeshOutputMemorySize               = 65536
        maxMeshPayloadAndOutputMemorySize     = 81920
        maxMeshOutputComponents               = 127
        maxMeshOutputVertices                 = 256
        maxMeshOutputPrimitives               = 256
        maxMeshOutputLayers                   = 8
        maxMeshMultiviewViewCount             = 6
        meshOutputPerVertexGranularity        = 1024
        meshOutputPerPrimitiveGranularity     = 1024
        maxPreferredTaskWorkGroupInvocations  = 1024
        maxPreferredMeshWorkGroupInvocations  = 256
        prefersLocalInvocationVertexOutput    = true
        prefersLocalInvocationPrimitiveOutput = true
        prefersCompactVertexOutput            = true
        prefersCompactPrimitiveOutput         = true
```
Lowering the local_size_x to 128 removes the compiler error.

**Comment by arcady-lunarg** [comment]
It appears that what you need here is to pass custom resource limits to the compiler. If you are using glslangValidator, you can run `glslangValidator -c > mylimits.conf` to generate a config file, then edit the appropriate lines in it, in your case `MaxWorkGroupSizeX_EXT` and friends to match what your hardware allows. Then, when you compile your shader, you can pass the config file to the compiler alongside the shader, like so `glslangValidator -V myShader.task mylimits.conf` and it will use these new limits. If you are using shaderc, it provides its own mechanisms for providing the same information.

**Comment by rsahlin** [comment]
Thanks for the reply @arcady-lunarg 

Ok, I see
For my project I compile Vulkan shaders to SPIRV on the fly.
Is it possible to set a number of configuration limits via command line instead of a .conf file?

**Comment by arcady-lunarg** [comment]
The .conf file is the only way to do it with glslangValidator. If you use shaderc (which is a wrapper around glslangValidator) it does seem to provide a way to set individual limits directly from the command line.

**Comment by rsahlin** [comment]
Ok, I see.
shaderc does not seem to include extension limits. 
Limits that are listed after `maxsamples` are missing, I will reach out to shaderc and ask them about this.
Thanks for your help @arcady-lunarg :-)

The following limits are missing from glslc (shaderc) compared to glslangValidator:

```
MaxMeshOutputVerticesNV 256
MaxMeshOutputPrimitivesNV 512
MaxMeshWorkGroupSizeX_NV 32
MaxMeshWorkGroupSizeY_NV 1
MaxMeshWorkGroupSizeZ_NV 1
MaxTaskWorkGroupSizeX_NV 32
MaxTaskWorkGroupSizeY_NV 1
MaxTaskWorkGroupSizeZ_NV 1
MaxMeshViewCountNV 4
MaxMeshOutputVerticesEXT 256
MaxMeshOutputPrimitivesEXT 256
MaxMeshWorkGroupSizeX_EXT 128
MaxMeshWorkGroupSizeY_EXT 128
MaxMeshWorkGroupSizeZ_EXT 128
MaxTaskWorkGroupSizeX_EXT 128
MaxTaskWorkGroupSizeY_EXT 128
MaxTaskWorkGroupSizeZ_EXT 128
MaxMeshViewCountEXT 4
MaxDualSourceDrawBuffersEXT 1
nonInductiveForLoops 1
whileLoops 1
doWhileLoops 1
generalUniformIndexing 1
generalAttributeMatrixVectorIndexing 1
generalVaryingIndexing 1
generalSamplerIndexing 1
generalVariableIndexing 1
generalConstantMatrixVectorIndexing 1
```
