### ISSUE TITLE
Support the generation of spirv NonSemantic.DebugBreak

### ISSUE THREAD

**Issue by jiaolu** [KhronosGroup/glslang#3157]
Is it possible to support the [NonSemantic.DebugBreak](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/nonsemantic/NonSemantic.DebugBreak.asciidoc) in glslang ?

I am thinking about there are two ways to suppor this spirv in the glslang.
First we add gdb like option to the glslang .ie.

glslangValidator -breakPoint 10 -breakFile "compute.comp". 

Or we can have new instruction like debugBreak. but this require new glsl extension ?

I prefer first option, as we don't need to change glsl source file .

**Comment by arcady-lunarg** [comment]
I think the command line option approach is a reasonable one, but I am curious about the envisioned use case for setting breakpoints via glslang. Is there a debugger that would be repeatedly calling glslang to recompile GLSL source code just to set breakpoints?

**Comment by jiaolu** [comment]
currently there is no such debugger.  i figure workflow is different in vendors.  might be better implemented in game engine?

**Comment by arcady-lunarg** [comment]
My main concern here is that while this does seem like a potentially reasonable feature, it would add a certain inevitable amount of complexity to the code, which we would really only want to maintain if it's actually useful to someone. For example, I could just as easily imagine a debugger modifying a SPIR-V module directly by parsing the debug info to find the appropriate DebugLine and inserting the breakpoint op right after it, or doing something else that doesn't require touching glslangValidator at all.

**Comment by ShchchowAMD** [comment]
https://github.com/KhronosGroup/glslang/pull/3171

**Comment by arcady-lunarg** [comment]
Come to think of it, I think this would be a better fit for SPIR-V tools, and I would prefer not to implement this feature in glslang.
