### ISSUE TITLE
Changing SPIR-V default to no debug names. Does this break anything?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#316]
Glslang currently includes **OpName** debug instructions in generated SPIR-V, by default.

The default should be to not include these; when needed, it should be requested.  Note the specification says:

>  This has no semantic impact and can safely be removed from a module.

Glslang should help ensure nothing accidentally depends on this, as well as generate smaller SPIR-V files by default. (There have been some reports of accidental dependence on debug information.)

Are there any concerns with changing this default?

Or, what options should be employed to generate debug information?

**Comment by Themaister** [comment]
OpName is crucial for being able to obtain sane output from tools like SPIRV-Cross for debugging and reflection purposes, so I would strongly suggest keeping it at least as an easily accessible option, maybe something like -g to match C compilers, unless that's already taken.

I wouldn't mind making no OpName default, but I worry that OpName implementation would get far less testing were it to be non-default.

**Comment by baldurk** [comment]
:+1: to the above from a debugging standpoint. Having naming information makes frame debugging _much_ easier.

Potentially a middle ground would be only naming externally visible objects, like input/output structures, bound resources, entry point, etc and stripping the naming of local variables. That still does decrease the quality of the output of SPIRV-Cross and other tools for generating human-readable representations of the SPIR-V, so I would remain in favour of keeping the behaviour as-is by default.

FWIW looking at the D3D compiler, it will emit the equivalent of global OpName information for reflection by default and you have to pass a command switch / flag bit to strip that data out. It also provides functionality for stripping the data out of an already compiled blob. What you need to opt-in to is including verbose debugging information where e.g. the source files are included verbatim and line number information is provided - which AFAIK glslang does not support yet. But making that opt-in is a no-brainer :smile:.

**Comment by steve-lunarg** [comment]
Note that there has already been some limited driver exposure to absence of debug names: the spirv-remap utility with "--strip all" will strip debug info from an existing module, and I believe it has been used in that capacity with various drivers.  I recall one driver bug being uncovered and fixed.

It's not evidence nothing would be broken, but it is evidence the situation should not be terribly dire, as it has already been exercised in a limited capacity.

**Comment by johnkslang** [comment]
With commit 44d2728e3d45bd064a4e6bf23d9c1793dc0da839, glslang now has a `-g` debug-style option.  It currently emits source code (in **OpSource**) and line information (**OpLine**).

For this issue, we should probably change to having **OpName** emitted only when `-g` (`EShMsgDebugInfo`) is used.

**Comment by johnkslang** [comment]
Closing as things currently are. We don't have justification for changing the current middle ground.
