### ISSUE TITLE
Ternary operator to conditionally copy from SSBO or shared memory fails.

### ISSUE THREAD

**Issue by dnfield** [KhronosGroup/glslang#3164]
Using a ternary operator to conditionally copy from either a `shared` buffer or an SSBO results in this error:

```
shaderc: internal error: compilation succeeded but failed to optimize: OpStore Pointer <id> '50[%50]'s type does not match Object <id> '63[%63]'s type.
  OpStore %50 %63
```

```glsl
layout(local_size_x = 512, local_size_y = 1) in;
layout(std430) buffer;

struct MyStruct {
  uint a;
  uint b;
  uint c;
};

layout(binding = 0) buffer MyStructs {
  uint count;
  MyStruct data[];
}
my_structs;

layout(binding = 1) buffer Output {
  uint a;
  uint b;
  uint c;
}
o;

shared MyStruct s[512];

void main() {
  s[0] = MyStruct(1, 2, 3);
  s[1] = MyStruct(1, 2, 3);
  s[2] = MyStruct(1, 2, 3);
  s[3] = MyStruct(1, 2, 3);

  uint id = gl_GlobalInvocationID.x;
  MyStruct ms =
      id > my_structs.count ? s[id - my_structs.count] : my_structs.data[id];

  atomicAdd(o.a, ms.a);
  atomicAdd(o.b, ms.b);
  atomicAdd(o.c, ms.c);
}
```

It's not clear to me if this is expected to fail or not, but a more helpful error message would be appreciate if it is expected to fail.

**Comment by greg-lunarg** [comment]
Can you please give us a reproducing shaderc or glslangValidator command line?

**Comment by dnfield** [comment]
```
./glslc --target-env=vulkan1.1 -O shader.comp
shaderc: internal error: compilation succeeded but failed to optimize: OpStore Pointer <id> '48[%48]'s type does not match Object <id> '61[%61]'s type.
  OpStore %48 %61
```

**Comment by dnfield** [comment]
Also reproduces without specifying the `--target-env`, e.g. `./glslc -O shader.comp` where shader.comp is the file in the original comment.

**Comment by arcady-lunarg** [comment]
The error message from spirv-opt actually comes from SPIR-V validation failing, running spirv-val on the file also produces the exact same message. This is clearly a bug, though I agree that the error message from spirv-opt could be a bit clearer about what is happening.

**Comment by arcady-lunarg** [comment]
I've looked at this and what is happening is that the values in the two branches of the conditional have the same GLSL-level types, but different SPIR-V level types (the struct in the buffer is decorated with offsets, the struct in the shared array is not) and glslang was not handling that case correctly. This requires adding some code similar to what was done for function parameters in https://github.com/KhronosGroup/glslang/issues/2637.
