### ISSUE TITLE
Double matrix created with float values

### ISSUE THREAD

**Issue by iostrowsINTEL** [KhronosGroup/glslang#318]
At dmat creation matrix is filled with float values instead of double. Combined with double spec constants, that leads to inconsistency in OpSpecConstantComposite instruction, because:
`
Result Type must be a composite type, whose top-level members/elements/components/columns have the same type as the types of the Constituents
`

From dEQP-VK.pipeline.spec_constant.graphics.vertex.composite.array.dmat3x2

**GLSL:**
<pre>
layout(constant_id = 1) const double sc0 = double(1);
...
const dmat3x2 a0[3] = dmat3x2[3](<b>dmat3x2(sc0)</b>, dmat3x2(2), dmat3x2(3));
</pre>

**SpirV:**
```
%6 = OpTypeFloat 64
...
%25 = OpSpecConstant %6 1
%26 = OpTypeVector %6 2
%27 = OpTypeMatrix %26 3
%28 = OpTypeFloat 32
%29 = OpConstant %28 1
%30 = OpConstant %28 0
%31 = OpSpecConstantComposite %26 %25 %30
%32 = OpSpecConstantComposite %26 %30 %25
%33 = OpConstantComposite %26 %30 %30
%34 = OpSpecConstantComposite %27 %31 %32 %33
```

Proposed fix in #317

**SpirV after fix:**
```
%6 = OpTypeFloat 64
%9 = OpConstant %6 0
...
%25 = OpSpecConstant %6 1
%26 = OpTypeVector %6 2
%27 = OpTypeMatrix %26 3
%28 = OpConstant %6 1
%29 = OpSpecConstantComposite %26 %25 %9
%30 = OpSpecConstantComposite %26 %9 %25
%31 = OpConstantComposite %26 %9 %9
%32 = OpSpecConstantComposite %27 %29 %30 %31
```

**Comment by johnkslang** [comment]
Good catch, and I merged the PR.
