### ISSUE TITLE
Continuous build of the latest main branch does not provide Windows binaries

### ISSUE THREAD

**Issue by mbouron** [KhronosGroup/glslang#3186]
It appears that the continuous build of the latest main branch (main-tot) does not provide Windows binaries while the legacy one (master-tot) does. Is there a specific issue preventing the upload of the Windows binaries for the main branch ?

Also, are there plan to provide binaries of glslang releases ?

I think that providing both (main + releases) could benefit other projects CIs depending on glslang.

**Comment by jeremy-lunarg** [comment]
This was accidentally broken but has been fixed as part of #2980. Thanks!
