### ISSUE TITLE
Should texelFetch() work with gtextureXX?

### ISSUE THREAD

**Issue by pdaniell-nv** [KhronosGroup/glslang#320]
This issue is related to issue #252.

Should glslang allow texelFetch() to work with the non-sampled gtextureXX opaque handles? It seems like it would be useful since the sampler isn't needed for texelFetch(). However, the GL_KHR_vulkan_glsl spec is not clear about this.

If glslang is currently correct and texelFetch() should only work with sampled-images gsamplerXX then it seems as though this is a little inconsistent with SPIR-V. According to GL_KHR_vulkan_glsl texelFetch() maps to OpImageFetch. In the SPIR-V spec OpImageFetch takes in an OpTypeImage rather than a OpTypeSampledImage. I think this means that glslang is generating incorrect SPIR-V for texelFetch().

Or maybe the SPIR-V spec is wrong and OpImageFetch should take in a OpTypeSampledImage?

**Comment by johnkslang** [comment]
GLSL:

 - `texelFetch()` is for a sampled image (a GLSL *sampler*)
 - `imageLoad()` is for an unsampled image (a GLSL *image*)

SPIR-V:
 - **OpImageFetch** is for a sampled image
 - **OpImageRead** is for an unsampled image

So, there is a good 1:1 correspondence between 

 - GLSL `texelFetch()` -> SPIR-V **OpImageFetch**
 - GLSL `imageLoad()` -> SPIR-V **OpImageRead**

> Should glslang allow texelFetch() to work with the non-sampled gtextureXX opaque handles? It seems like it would be useful since the sampler isn't needed for texelFetch().

No. There was quite a bit of Khronos debate on this, with the final decision being despite the attractiveness, it couldn't yet be done.  More on this should be taken up internally in Khronos.

>  GL_KHR_vulkan_glsl spec is not clear about this.

Where?  Note is not normative for GL_KHR_vulkan_glsl to say how to translate, but there is a guideline section.

> OpImageFetch takes in an OpTypeImage rather than a OpTypeSampledImage.

But the SPIR-V specification does say

> **OpImageFetch**
>
> Fetch a single texel from a sampled image.
> ...
> *Image* must be an object whose type is **OpTypeImage** [whose] *Sampled* operand must be 1.

So, it has to be a kind of resource/memory/logical-object thing that is sampled, but the instruction isn't taking the sampler, just the image.  That is, the sampler doesn't matter, but the kind of object that is being accessed does matter.

If this latter part seems incorrect, this should be taken up in a SPIR-V forum.

**Comment by pdaniell-nv** [comment]
Thanks for the explanation. I'm still unsure whether glslang has a bug or not. The SPIR-V spec expects OpImageFetch to take a OpTypeImage, but glslang doesn't generate that. Here is an example:
```
#version 450 core
in vec2 vTexCoord;
out vec4 oFrag;
layout(binding = 0) uniform texture2D tex;
layout(binding = 1) uniform sampler samp;

void main()
{
  oFrag = texelFetch(sampler2D(tex,samp), ivec2(vTexCoord * 61.0), 0);
}
```

Generates:
```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 31

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9 22
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "oFrag"
                              Name 12  "tex"
                              Name 16  "samp"
                              Name 22  "vTexCoord"
                              Decorate 12(tex) DescriptorSet 0
                              Decorate 12(tex) Binding 0
                              Decorate 16(samp) DescriptorSet 0
                              Decorate 16(samp) Binding 1
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
        9(oFrag):      8(ptr) Variable Output
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypePointer UniformConstant 10
         12(tex):     11(ptr) Variable UniformConstant
              14:             TypeSampler
              15:             TypePointer UniformConstant 14
        16(samp):     15(ptr) Variable UniformConstant
              18:             TypeSampledImage 10
              20:             TypeVector 6(float) 2
              21:             TypePointer Input 20(fvec2)
   22(vTexCoord):     21(ptr) Variable Input
              24:    6(float) Constant 1114898432
              26:             TypeInt 32 1
              27:             TypeVector 26(int) 2
              29:     26(int) Constant 0
         4(main):           2 Function None 3
               5:             Label
              13:          10 Load 12(tex)
              17:          14 Load 16(samp)
              19:          18 SampledImage 13 17
              23:   20(fvec2) Load 22(vTexCoord)
              25:   20(fvec2) VectorTimesScalar 23 24
              28:   27(ivec2) ConvertFToS 25
              30:    7(fvec4) ImageFetch 19 28 Lod 29
                              Store 9(oFrag) 30
                              Return
                              FunctionEnd
```

Note that %19 is OpTypeSampledImage rather than OpTypeImage. Is that intended?

**Comment by johnkslang** [comment]
> Note that %19, the input to OpImageFetch, is of type OpTypeSampledImage rather than OpTypeImage. Is that intended?

Seems out of date.  It is a natural translation of the provided GLSL, but the SPIR-V specification indicates the 'tex' needs to be pulled out of the constructed pair.

Some archaeology... Change log for Rev. 1: 

> Remove image-"Query" overloading on image/sampled-image type and "fetch" on non-sampled images, by adding the **OpImage** instruction to get the image from a sampled image.

So, the instruction **OpImage** (extract the image from a sampled image) was added late in SPIR-V development to support the late change that **OpImageFetch** took an image.

Will mark this as a glslang bug for code-generation correctness.

**Comment by johnkslang** [comment]
The fetch path was indeed missing the generation of the **OpImage** instruction.  
Commit a5c33d6ffb34ccede5b233bc724c907166b6e479 fixes this.

**Comment by pdaniell-nv** [comment]
Verified the new glslang output looks correct to me. Thanks.
