### ISSUE TITLE
Targeting vulkan1.3 enables LocalSizeId execution mode even if using constant workgroup sizes.

### ISSUE THREAD

**Issue by mdibble** [KhronosGroup/glslang#3200]
Compiling the following shader with `--target-env vulkan1.3` causes the shader to execute in LocalSizeId mode:
```
#version 450

layout (local_size_x = 256) in;

void main() { }
```

This leads to a validation error upon pipeline creation:

"LocalSizeId execution mode used but maintenance4 feature not enabled The Vulkan spec states: If execution mode LocalSizeId is used, maintenance4 must be enabled (https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-RuntimeSpirv-LocalSizeId-06434)"

The output of `glslangValidator.exe --target-env vulkan1.3 shade_test.comp -H` is as follows:

```
shade_test.comp
// Module Version 10600
// Generated by (magic number): 8000b
// Id's are bound by 11

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main"
                              ExecutionModeId 4 LocalSizeId 7 8 8
                              Source GLSL 450
                              Name 4  "main"
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 0
               7:      6(int) Constant 256
               8:      6(int) Constant 1
               9:             TypeVector 6(int) 3
              10:    9(ivec3) ConstantComposite 7 8 8
         4(main):           2 Function None 3
               5:             Label
                              Return
                              FunctionEnd
```

I'm wondering if there's a reason for why the shader executes in LocalSizeId mode, or if this is unintended. It seems maintenance4 was promoted to core in Vulkan 1.3, but still must be explicitly enabled.

**Comment by keithlostracco** [comment]
Currently experiencing the same issue. I changed compiled command to  `--target-env  vulkan1.2`  and the shader compiles using LocalSize (where 1.3 compiles with LocalSizeId)
