### ISSUE TITLE
C++ API generates invalid SPIR-V code, error: Codesize must be a multiple of 4

### ISSUE THREAD

**Issue by alexpanter** [KhronosGroup/glslang#3202]
Hi,

So the error is kind of what the title says. This is the input vertex shader:
```glsl
#version 450

vec2 positions[3] = vec2[](
	vec2(0.0, -0.5),
	vec2(0.5, 0.5),
	vec2(-0.5, 0.5)
);

void main()
{
	gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);
}

```

And this is the error, caught by validation layers after `glslang` apparently checks that the generated shader is okay:

> Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01376 ] Object 0: handle = 0x56011dc404d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x70816513 | SPIR-V module not valid: Codesize must be a multiple of 4 but is 273 The Vulkan spec states: If pCode is a pointer to SPIR-V code, codeSize must be a multiple of 4 (https://vulkan.lunarg.com/doc/view/1.3.243.0/linux/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01376)

I generate the code with these steps (from GLSL to SPIR-V):
```cpp
glslang::InitializeProcess();

std::vector<char> buffer; // <-- contains vertex shader, null-terminated

EShLanguage lang = EShLangVertex;
glslang::TShader shader(lang);

// TODO: We need an includer for recursive shader inclusion
glslang::TShader::ForbidIncluder includer;

// TODO: Adding sources to the shader
std::forward_list<const char*> shaderStringsList;
shaderStringsList.push_front(buffer.data());

std::vector<const char*> shaderStrings;
for (const char* str : shaderStringsList)
{
	shaderStrings.push_back(str);
}
shader.setStrings(shaderStrings.data(), shaderStrings.size());

const int version = 100;
shader.setEnvInput(glslang::EShSourceGlsl, lang, glslang::EShClientVulkan, version);

// Get the active Vulkan version of the client process (Vulkan 1.3)
glslang::EShTargetClientVersion targetApiVersion = glslang::EShTargetVulkan_1_3;
shader.setEnvClient(glslang::EShClientVulkan, targetApiVersion);

// NOTE: Ray tracing shaders REQUIRED SPIR-V 1.4!
glslang::EShTargetLanguageVersion spirvVersion = glslang::EShTargetSpv_1_3;
shader.setEnvTarget(glslang::EshTargetSpv, spirvVersion);

shader.setEntryPoint("main");

// TODO: Probably need a mapper from physical device limits to glslang resource limits!
TBuiltInResource* resources = GetResources();
const int defaultVersion = 450;
const bool forwardCompatible = false;
const EShMessages messageFlags = (EShMessages)(EShMsgSpvRules | EShMsgVulkanRules);
if (!shader.parse(resources, defaultVersion, forwardCompatible, messageFlags, includer))
{
	// Logging an error, ie. nothing is logged here
	return VK_NULL_HANDLE;
}

glslang::TProgram program;
program.addShader(&shader);
if (!program.link(messageFlags))
{
	// Logging an error, ie. nothing is logged here
	return VK_NULL_HANDLE;
}

// Convert the intermediate generated by glslang to Spir-V
glslang::TIntermediate& intermediateRef = *(program.getIntermediate(lang));
std::vector<uint32_t> spirv;
glslang::SpvOptions options{};
options.validate = true; // <-- makes no difference
glslang::GlslangToSpv(intermediateRef, spirv, &options);

// Create shader module
VkShaderModule module;
VkShaderModuleCreateInfo createInfo{};
createInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
createInfo.codeSize = spirv.size();
createInfo.pCode = spirv.data();
VkResult result = vkCreateShaderModule(dev, &createInfo, nullptr, &module);
if (result != VK_SUCCESS)
{
	// Logging an error. HERE, an error is actually logged
	return VK_NULL_HANDLE;
}

return module;
```

**Comment by r-potter** [comment]
```
std::vector<uint32_t> spirv;
VkShaderModuleCreateInfo createInfo{};
createInfo.codeSize = spirv.size(); // Should be spirv.size() * sizeof(uint32_t)
VkResult result = vkCreateShaderModule(dev, &createInfo, nullptr, &module);
```
Cutting this down to the minimal cause. `VkShaderModuleCreateInfo::codeSize` is supposed to be size in bytes, but you are passing size in 32-bit words

**Comment by alexpanter** [comment]
@r-potter that worked - thank you! I'm a bit surprised I missed that one...

On to the next topic (I hope you don't mind!):
```cpp
// TODO: We need an includer for recursive shader inclusion
glslang::TShader::ForbidIncluder includer;
```

As you can see, I'm trying to do some kind of _recursive_ shader file inclusion, to be able to fully support `#include` inside shader files. But there is no documentation anywhere (that I could find), which explains how to to this.

So my intuition was to use an `Includer`, since that may be passed as an extra parameter to `TShader::parse()`. Do you have a working example (I _want_ to use the C++ API), or could you be so kind as to give me a few hints?

Thank you for  the help!

**Comment by turol** [comment]
@alexpanter I've used this interface in my demo:

https://github.com/turol/smaaDemo/blob/f52b68fc442437900e41a8ec29ee3080d460ea67/renderer/RendererInternal.h#L273
https://github.com/turol/smaaDemo/blob/f52b68fc442437900e41a8ec29ee3080d460ea67/renderer/RendererCommon.cpp#L997

**Comment by alexpanter** [comment]
@turol Thank you for that! After some experimentation, I have arrived at sort of the same thing:
* Class that inherits (and completes) `TShader::Includer`
* Use a hashed data structure for storing sources (I use `std::map`)

I'm currently working on it, so it's very nice to see that my idea wasn't far off! I consider this quite complicated, so I'm going to write a guide about it once I'm done. Again, thank you for the assistance!
