### ISSUE TITLE
Syntax error on unknown type

### ISSUE THREAD

**Issue by karyon** [KhronosGroup/glslang#321]
i have code like this

```
struct SomeStruct {
    vec4 someVector;
};

layout (std140, binding = 0) uniform vplBuffer_
{
    SomeStruct vplBuffer[256];
};
```

which works.

now i'm using GL_ARB_shading_language_include to move the struct definition to a separate file, since i use it in multiple shaders. since that extension is not supported (see https://github.com/KhronosGroup/glslang/issues/249), SomeStruct is unknown. 
the validator now aborts due to a "syntax error". in that line.

some more robustness in such cases would be nice so people that use shader includes can still have the rest of their files validated. Although i do realize that the root problem is actually the other issue (as in, if the includes worked, i wouldnt mind if the validator aborted on unknown struct names)

**Comment by arcady-lunarg** [comment]
@karyon have you tried the `-C` option? Does it address your complaint here?

**Comment by karyon** [comment]
This was seven years ago, I can't tell.

**Comment by arcady-lunarg** [comment]
Thanks, in that case, I think it's safe to close the issue.
