### ISSUE TITLE
Shader compiles with both scalar and std430 layouts applied at the same time

### ISSUE THREAD

**Issue by dustContributor** [KhronosGroup/glslang#3244]
Hi! I have a tiny shader that's like this:

```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require

layout(scalar, std430, buffer_reference, buffer_reference_align = 8) readonly buffer Vertices
{
    vec3 items[];
};

layout(push_constant) uniform Registers
{
    Vertices vertices;
} registers;

layout (location = 0) out vec3 passColor;

void main() {
    restrict vec3 inPos = registers.vertices.items[gl_VertexIndex].xyz;
    passColor = (inPos + vec3(1.0)) * vec3(0.5);
    gl_Position = vec4(inPos, 1);
}
```

I mistunderstood the spec and added both `scalar` and `std430` layouts to the `Vertices` definition. I've been told this is actually not valid since both layouts are exclusive (I actually only wanted `scalar` in this particular case), yet it seems to compile fine, instead of throwing an error. Here is my version output just in case:

> glslangValidator -v
Glslang Version: 11:12.2.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 12.2.0
GLSL Version: 4.60 glslang Khronos. 12.2.0
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 11
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100

From what i've tried it seems it applies the last layout specified in the list. That is to say, `scalar, std430` applies `std430`, whereas `std430, scalar`  applies the `scalar` layout.

Is  this intended behavior, or should it throw a compile error?

EDIT: It seems it also compiles fine if I specify the layout any number of times, for example: `scalar, scalar, std430, scalar, scalar` also compiles just fine, and seems to apply the `scalar` layout.

**Comment by arcady-lunarg** [comment]
A close reading of both the spec for [GL_EXT_scalar_block_layout](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_scalar_block_layout.txt) and section 4.4.5 of the [GLSL spec](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf#page=91) indicates that multiple layout qualifiers can be specified and later ones override earlier ones as relevant to their specific semantics. Therefore, the behavior glslang is exhibiting is the one intended by the spec.

**Comment by dustContributor** [comment]
Ah I see. I didn't think it'd be specified that way, thanks.
