### ISSUE TITLE
SPV: ClipDistance Builtin is used without declaring ClipDistance capability

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#325]
This issue is related to https://github.com/KhronosGroup/glslang/commit/ebb505355d59f61dfc9547f81e14b2d9cd1eb2f0 and shows that it didn't go far enough.

Example shader:
```
#version 440
void main (void)
{
    gl_Position = vec4(1.0);
}
```

The use of gl_Position forces the creation of the gl_PerVertex struct:
```
out gl_PerVertex {
 vec4 gl_Position;
 float gl_PointSize;
 float gl_ClipDistance[];
};
```
But this shader doesn't actually use gl_ClipDistance, so glslang doesn't declare the ClipDistance capability.   (That's the purpose of the previous commit: to avoid declaring ClipDistance in this case.)

The trouble is that the full struct is still declared, including the OpMemberDecorate ... Builtin ClipDistance
```
               OpName %11 "gl_PerVertex"
               OpMemberName %11 0 "gl_Position"
               OpMemberName %11 1 "gl_PointSize"
               OpMemberName %11 2 "gl_ClipDistance"
...
               OpMemberDecorate %11 0 BuiltIn Position
               OpMemberDecorate %11 1 BuiltIn PointSize
               OpMemberDecorate %11 2 BuiltIn ClipDistance
```

The validator then complains that the builtin ClipDistance is used without declaring the ClipDistance capability.

**Comment by johnkslang** [comment]
It's declared, but not used.  That was the compromise we'd reached, as the specifications require the declaration, but the coder doesn't want the dependency on the capability.

So, the validator should only complain if there is an instruction that reads/writes or otherwise makes use of the feature.

(At least until a specification change is driven.)

GLSL specification:

> In the vertex language, the built-ins are intrinsically declared as:

```
...
out gl_PerVertex {
    vec4 gl_Position;
    float gl_PointSize;
    float gl_ClipDistance[];
    float gl_CullDistance[];
};
```

KHR_vulkan_glsl:

```
in/out gl_PerVertex {
    gl_Position
    gl_PointSize
    gl_ClipDistance
    gl_CullDistance
}                        (name of block is for debug only)
```

So this was the minimum "breakage" to make.

**Comment by TiemoJung** [comment]
Issue https://github.com/KhronosGroup/glslang/issues/315 describes the same thing. In https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/600 it is suggested to define the interface block explicitly to avoid this.

**Comment by dneto0** [comment]
My first thought is that it's weird to relax the validator for this case.  It adds complexity, and it's hard to tell where to stop such reasoning.  For example, would it be ok to declare a bunch of new non-standard types that are then never "used"?

About the interface-matching case:  Let's say you have a gl_PerVertex struct in a vertex shader that doesn't declare ClipDistance capability, but still has the struct decorated with a ClipDistance.  Also, let's say you want to match that interface with a fragment shader that *does* use ClipDistance and therefore also declares the ClipDistance capability.  Then the implementation accepting such a pipeline accepts ClipDistance and you haven't saved anything in the vertex shader by *not* declaring the ClipDistance capability.

My preference is to have the compiler avoid decorating that member with the ClipDistance builtin.

The "let's add features to ES" sounds like a good long-term path.  Convergence of shader language dialects seems like a good goal.

Housekeeping:  I'm ok closing this bug as a duplicate of #315.  I didn't realize it existed.

**Comment by johnkslang** [comment]
> ... it's hard to tell where to stop such reasoning

Agreed.

This is a very special case driven by the pragmatic issues specifically just for clip distance and cull distance.

There is no excuse to aggrandize or further propagate this comprise to any other aspect the specifications and implementations.
