### ISSUE TITLE
GL_ARB_shader_storage_buffer_object

### ISSUE THREAD

**Issue by HeXiaoZhi** [KhronosGroup/glslang#3263]
glcts.exe --deqp-case=KHR-GL45.shader_subroutine.ssbo_atomic_image_load_store
The extension "GL_ARB_shader_storage_buffer_object" can be used in version 400~420, but glslang settings can only be used in OGL420.

**Comment by arcady-lunarg** [comment]
This does appear to be a bug, the extension spec says
```
OpenGL 4.0 (either core or compatibility profile) is required.

This extension is written against the OpenGL 4.2 (Compatibility Profile) Specification.
```
It should be a simple matter of changing the version check for enabling the corresponding features to check for 4.0 instead of 4.2, as well as moving the tests from 420.frag to 400.frag.

**Comment by HeXiaoZhi** [comment]
Has this issue  been fixed?

**Comment by ncesario-lunarg** [comment]
@HeXiaoZhi I don't believe it has. I was about to check and put up a PR if it hasn't been fixed already.
