### ISSUE TITLE
glslangValidator symlink cannot be created in a distro package build environment

### ISSUE THREAD

**Issue by AdrianVovk** [KhronosGroup/glslang#3281]
Version: 12.3.1

```
CMake Error: failed to create symbolic link 'glslangValidator': Read-only file system
```

Basically, cmake tries to symlink into /usr/bin/glslangValidator -> glslang, but it completely ignores $DESTDIR. In a distro packaging environment DESTDIR will be set somewhere (in my case, to /buildstream-install/), and the rest of the system (including /usr) will be mounted read-only.

**Comment by ms178** [comment]
This is probably the reason for the bug I am seeing when compiling glslang 12.3.1 on Arch Linux, as glslangValidator currently won't be found any longer in projects relying on it (e.g. Mesa). I hope the linked pull request will take care of this problem. With glslang 12.2.0 everything is fine.
