### ISSUE TITLE
Can't pass `ByteAddressBuffer` as function parameter in HLSL with `--target-env vulkan1.2`

### ISSUE THREAD

**Issue by Ryp** [KhronosGroup/glslang#3297]
The following HLSL compute shader compiles but fails validation for  `--target-env vulkan1.2`
```hlsl
[[vk::binding(0, 0)]] ByteAddressBuffer buffer_position_ms;
[[vk::binding(1, 0)]] RWByteAddressBuffer r;

float3 pull_position(ByteAddressBuffer buffer_position, uint vertex_id)
{
    return asfloat(buffer_position.Load3(vertex_id * 3 * 4));
}

[numthreads(64, 1, 1)]
void main(uint gi : SV_GroupIndex)
{
    float3 position_ms = pull_position(buffer_position_ms, gi);

    r.Store3(0, asuint(position_ms));
}
```
`spirv-val` Error:
```
StorageBuffer pointer operand '54[%buffer_position_ms]' requires a variable pointers capability
  %57 = OpFunctionCall %v3float %pull_position_block__u1_0_1_u1_ %buffer_position_ms %param
```
`spirv-opt` Error if I take the resulting `.spv` file
```
Interfaces passed to OpEntryPoint must be of type OpTypeVariable. Found OpFunctionParameter.
```
This is the invocation for glslang:
```
glslangValidator --target-env vulkan1.2 -g -e main -V -D bug.comp.hlsl -o bug.spv
```

Linking #2264 since they seem related

**Comment by ncesario-lunarg** [comment]
Looks like this is hitting an assert in the SPIRV-Tools optimizer: https://github.com/KhronosGroup/SPIRV-Tools/blob/bfc94f63a7adbcf8ae166f5f108ac9f69079efc0/source/opt/def_use_manager.cpp#L56.

**Comment by greg-lunarg** [comment]
@ncesario-lunarg Can you confirm this is legal HLSL using dxc?

**Comment by greg-lunarg** [comment]
@ncesario-lunarg I have confirmed dxc handles this shader.

**Comment by ncesario-lunarg** [comment]
spirv-opt was asserting in the middle of legalization due to an `OpFunctionParameter` occurring in the `OpEntryPoint`. #3314 should address this. @Ryp can you confirm #3314 fixes your issue?
