### ISSUE TITLE
Add OpenSSF Scorecard Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [KhronosGroup/glslang#3299]
Hi, here is Joyce again (#3148 and #3168) and I'd like to make another supply chain security suggestion.

I'd like to suggest a tool that might help you track supply-chain security practice improvements. The tool is called the OpenSSF Scorecard Action, and it proactively runs the Scorecard on your repository to warn you of any security practice changes. This is important for improving your project's supply-chain security.

The OpenSSF Scorecard Action has been adopted by over 1800 projects, including some prominent ones like [Tensorflow](https://github.com/tensorflow/tensorflow), [Angular](https://github.com/angular/angular), [Flutter](https://github.com/flutter/flutter), [sos.dev](https://sos.dev/) and [deps.dev](https://deps.dev/).

I would be happy to create a pull request to add this action to your project. Optionally, the action can also publish your results to the OpenSSF REST API, which allows you to add a badge with your project's score to your README. Let me know if the PR is welcome and I'll submit it ASAP.

You can find more information about the OpenSSF Scorecard Action here: https://www.github.com/ossf/scorecard-action

If you have any questions, please don't hesitate to reach out to me.

### Additional Context

Badge Example:
![image](https://github.com/KhronosGroup/glslang/assets/22223372/55215c9b-a310-42c6-a367-3ae6a313e59a)

**Comment by arcady-lunarg** [comment]
I think this will need to be discussed internally within Khronos first, we will get back to you once we have done that.

**Comment by joycebrum** [comment]
Sure, anything I can help with, let me know.

**Comment by arcady-lunarg** [comment]
Given SPIRV-Tools has decided to go with this, I think this is reasonable for glslang as well. We would welcome a pull request of this nature.
