### ISSUE TITLE
Add support for GL_EXT_texture_shadow_lod for Vulkan

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#3302]
The following extension was added to GLSL and adds useful texture operations that are currently missing in GLSL: https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_shadow_lod.txt

The lack of this extension prevents slang from exposing some texture operations: https://github.com/shader-slang/slang/issues/3090

**Comment by danginsburg** [comment]
Are there plans to un-WIP this PR and submit it?  Is it blocked by anything?

**Comment by ncesario-lunarg** [comment]
No, this is not blocked on anything, I just don't like the way I currently have it implemented and I'm looking for a "less hacky" approach (we currently don't support an extension that adds overloads to existing built-in functions). I plan on putting this up today one way or the other, though.
