### ISSUE TITLE
Build failure on Ubuntu 16.10

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/glslang#332]
On most linux builds, the code `return std::isinf(x) && (x >= 0);` is used for testing against positive infinity.  However on an Ubuntu 16.10 install, this fails to compile because the code is using the <math.h> header, which has no guarantee of defining `std::isinf`.  In fact, on the target system, compilation fails because my version of math.h uses a `#define` to make `isinf` equal to `__builtin_isinf_sign`, which then fails because there's no definition for `std::__builtin_isinf_sign`.

**Comment by jherico** [comment]
Fixed by https://github.com/KhronosGroup/glslang/pull/331

**Comment by johnkslang** [comment]
Merged.
