### ISSUE TITLE
Hash pin GitHub Actions on workflows

### ISSUE THREAD

**Issue by joycebrum** [KhronosGroup/glslang#3321]
Hi again, I'd like to suggest another security practice related to make the workflows as safe as possible.

Since GitHub does not provide immutable releases, hash pinning is a way of:

- prevent tag renaming attacks
- increase stability - prevent CI from break due to breaking changes on new releases blindly upgraded.
- avoid blind updates to malicious releases

And to help on keeping this versions up to date, I'd suggest adopting dependabot. Dependabot identifies and notifies security releases and it also tries to identify breaking changes and flag them on the respective PRs.

Let me know if you want to discuss more about this practice and if you have any concerns. 

Otherwise, let me know if a PR is welcome and I'll be glad to work on configuring dependabot and hash pinning the actions.

### Additional Context:

A [tag renaming attack][tag-renaming] is a type of attack whereby an attacker:
- Hijack an action.
- Upload a malicious version.
- Replace existing tags with malicious versions.

Github also recommends to **always** hash pin third party actions (see [Security Hardening for GitHub Actions][github-hashpin]). I believe it is worth it to hash pin **all** actions, not only third parties: github owned actions are still open sourced and can be compromised, even if they are significantly safer than any other action.

[tag-renaming]: https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash
[github-hashpin]: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by arcady-lunarg** [comment]
This seems like a reasonable thing and I think worth doing especially as we have started to rely on more third-party actions.  cc: @juan-lunarg

**Comment by juan-lunarg** [comment]
Agreed. We use lots of third-party actions so this seems like a good idea.

>  let me know if a PR is welcome and I'll be glad to work on configuring dependabot and hash pinning the actions.

A PR would be welcomed. I can then help spread this practice into more repos.

**Comment by joycebrum** [comment]
Thanks! Will send the PR soon.
