### ISSUE TITLE
textureOffset doesn't need GL_EXT_texture_shadow_lod in GLSL 440 and beyond shaders

### ISSUE THREAD

**Issue by AlexGalazin-IMG** [KhronosGroup/glslang#3325]
https://github.com/KhronosGroup/glslang/commit/ffefbcd9f36efcec0a940aa96eb99f0c6055cd2a introduced a regression by requiring GL_EXT_texture_shadow_lod to be requested for GLSL '450 core' shaders that contain 'float textureOffset (sampler2DArrayShadow sampler, vec4 P, ivec2 offset )'. This function is defined in at least GLSL 440, hence no other extensions should be needed.

Reporducer"

```
#version 450 core
layout(location = 0) out mediump vec4 o_color;
layout(location = 0) in highp vec4 v_texCoord;
layout(set = 0, binding = 0) uniform highp sampler2DArrayShadow u_sampler;
layout(set = 0, binding = 1) uniform buf0 { highp vec4 u_scale; };
layout(set = 0, binding = 2) uniform buf1 { highp vec4 u_bias; };

void main()
{
	o_color = vec4(textureOffset(u_sampler, v_texCoord, ivec2(7, -8)), 0.0, 0.0, 1.0);
}
```

Error log:

```
---
fragment compile log:
---

ERROR: 0:10: 'textureOffset' : required extension not requested: GL_EXT_texture_shadow_lod

ERROR: 0:10: '' : compilation terminated 

ERROR: 2 compilation errors.  No code generated.
```

**Comment by AlexGalazin-IMG** [comment]
@ncesario-lunarg please have a look

**Comment by ncesario-lunarg** [comment]
I might be reading the [spec](https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureOffset.xhtml), but it looks like `float textureOffset(sampler2DArrayShadow sampler, vec4 P, vec2 offset)` exists, but not `float textureOffset(sampler2DArrayShadow sampler, vec4 P, ivec2 offset)`. i.e., it looks like there is no existing API in core that takes a type of `ivec2` as the `offset` parameter? That is one of the overloads that is added in https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_shadow_lod.txt.

That said, `float textureOffset(sampler2DArrayShadow sampler, vec4 P, vec2 offset)` doesn't seem to work in glslang at all, which doesn't seem right either.

**Comment by ncesario-lunarg** [comment]
For whatever reason, that spec I referenced does not seem to be correct. https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html does appear to be correct. I'll put up a PR to remove that overload from the extension. The bias version (`float textureOffset(sampler2DArrayShadow sampler, vec4 P, ivec2 offset, float bias)`) will still require that extension if I understand correctly.

**Comment by AlexGalazin-IMG** [comment]
https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureOffset.xhtml - this is not a normative spec but basically a manual. Yes, you found the correct normative GLSL spec but bear in mind that different versions of GLSL defined these overloads slightly differently. You might want to compare https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.30.pdf vs https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.40.pdf
