### ISSUE TITLE
Need to propagate 64 bit options correctly in glslang standalone

### ISSUE THREAD

**Issue by pmistryNV** [KhronosGroup/glslang#3348]
https://github.com/KhronosGroup/glslang/commit/4c57db1595462c51d5080893f65c42fc1f318146 introduced a 64 bit TOptions in StandAlone.cpp that get's passed down as a 32 bit option in ShConstructCompiler and ShCompile. Causing loss of precision.

These functions need to be corrected to take 64 bit flags. This has a wider implac since ShConstructCompiler and ShCompile are exposed API's of the library.

**Comment by pmistryNV** [comment]
@ncesario-lunarg for visibility

**Comment by arcady-lunarg** [comment]
@pmistryNV Do you know if these options actually get used anywhere? As far as I have been able to figure out, they are not and compiler options are set by calling methods on the compiler object. It seems suspicious that the options enum is only available in `StandAlone.cpp`. I think this section of the code could use some cleanup in general but I don't think anything particularly bad is happening here.

**Comment by pmistryNV** [comment]
Both API's are exposed externally in shaderLang.h as GLSLANG_EXPORT, not sure who uses these API's.
