### ISSUE TITLE
glslang_shader_preprocess results in segmentation fault

### ISSUE THREAD

**Issue by SeleDreams** [KhronosGroup/glslang#3361]
I've been trying to use glslang in my C program in order to compile my glsl es 2.0 code into spirv, however i seem to hit a roadblock pretty early on.
It seems like it crashes with a segmentation fault when glslang_shader_preprocess is called, though I guess the issue might occur earlier when glslang_shader_create is called.
![image](https://github.com/KhronosGroup/glslang/assets/16335601/9187276a-2702-4495-aed9-f4f3cfadc3ca)
I basically followed the example that was given and linked glslang using cmake (`glslang::glslang glslang::glslang-default-resource-limits glslang::SPIRV stdc++`)
I'm not sure where the issue might come from

**Comment by evopen** [comment]
May I ask how you solved this?
