### ISSUE TITLE
 line number for OpDebugFunction and OpDebugScope are always 0

### ISSUE THREAD

**Issue by chaocNV** [KhronosGroup/glslang#3367]
These appears to be a TODO when implementing OpDebugFunction and OpDebugScope. 

I did a implementation that properly produce the line of function definition instead of 0 for above opcode at following PR
https://github.com/KhronosGroup/glslang/pull/3357

@arcady-lunarg @ncesario-lunarg

**Comment by arcady-lunarg** [comment]
Thanks, I'll take a look at the PR now.

**Comment by arcady-lunarg** [comment]
The associated PR was merged, this should have been closed.
