### ISSUE TITLE
Option to not output any .spv file but only output a .spvasm file

### ISSUE THREAD

**Issue by Wallby** [KhronosGroup/glslang#3368]
I.e. `glslangValidator --spirv-dis -V -S vert myvertexshader.glsl | more +1 > myvertexshader.spvasm` would generate a file vert.spv.

Is there any way to prevent the file vert.spv from being created? ~A way to work around it currently is to specify `-o myvertexshader.spvasm` such that the file will get overwritten, but it seems not ideal.~

The support for .spvasm generation also isn't very clean currently as the first line that is output if using `--spirv-dis` or `-H` (not sure if `-H` is anything other than `--spirv-dis` and `-V` combined?) is the input filename, hence the `|  more + 1` is required to remove that otherwise spirv-as outputs an error.

**Comment by Wallby** [comment]
Correction, the suggested workaround using `-o` didn't work.

**Comment by Wallby** [comment]
Seems like glslangValidator also doesn't use stderr either as I tried.. `glslangValidator -spirv-dis -V -S vert -o . myvertexshader.glsl 1> myvertexshader.spvasm` to only save stdout and not stderr to myvertexshader.spvasm, but the error ended up in myvertexshader.spvasm.

**Comment by Wallby** [comment]
`glslangValidator --spirv-dis -V -S vert -o NUL myvertexshader.glsl` works on windows. Haven't tested whether `glslangValidator --spirv-dis -V -S vert -o /dev/null myvertexshader.glsl` works on linux.

**Comment by arcady-lunarg** [comment]
You certainly can use `/dev/null` as an output file on Linux and that works. If that is not adequate for your needs, you're welcome to submit a patch to improve things. Also note that `-H` and `--spirv-dis` actually use different output formats for the SPIR-V, for various historical reasons and the `--spirv-dis` format is the one you can pass to `spirv-as`.

**Comment by ncesario-lunarg** [comment]
`-o /dev/null` in conjunction with `--quiet` (if you want to get rid of the first line of output) should dump valid spirv assembly to stdout. e.g.,
```bash
glslang -o /dev/null --spirv-dis --quiet ... | spirv-as -o ... /dev/stdin
```
I'm not sure what the equivalent of `/dev/stdin`/`/dev/stdout` is on Windows, though.

**Comment by Wallby** [comment]
> `-o /dev/null` in conjunction with `--quiet` (if you want to get rid of the first line of output) should dump valid spirv assembly to stdout. e.g.,
> 
> ```shell
> glslang -o /dev/null --spirv-dis --quiet ... | spirv-as -o ... /dev/stdin
> ```
> 
> I'm not sure what the equivalent of `/dev/stdin`/`/dev/stdout` is on Windows, though.

Tested and `-o CON` and `-o CONOUT$` work for stdout on windows.
As there is `--stdin` for glslangValidator `/dev/stdin` is not required.

Is there any reason there is no builtin support for anonymous pipes (for windows.. _pipe/CreatePipe)?

**Comment by ncesario-lunarg** [comment]
> Is there any reason there is no builtin support for anonymous pipes (for windows.. _pipe/CreatePipe)?

I don't think there was a specific reason, but rather this feature just wasn't a priority (and you can get the same functionality without too much additional typing). Unfortunately, I believe that is still the case. That said, PRs are always welcome :)
