### ISSUE TITLE
bool debug type not generated for non semantic debugging

### ISSUE THREAD

**Issue by chaocNV** [KhronosGroup/glslang#3376]
It appears that when we make bool type in SPIRV builder via` Id Builder::makeBoolType(bool const compilerGenerated)`, it has a hidden argument of `bool const compilerGenerated = true`. And generating debug type for bool is always gated on that argument being false: 
```
if (emitNonSemanticShaderDebugInfo && !compilerGenerated)
{
        auto const debugResultId = makeBoolDebugType(32);
        debugId[type->getResultId()] = debugResultId;
}
```
I believe this is redundant as there is no harm in creating a debug bool type regardless. It's a primitive type like int/float and those do not have this check. Currently all the usage of makeBoolType do not pass in a false argument and therefore bool debug type is never generated. 

My suggested fix would be remove `compilerGenerated ` from `makeBoolType` entirely. If you agree, I can create a PR for it. 

To illustrate the problem, following shader would crash in glslang currently:
```

#version 460

uniform UBO {
    bvec2 uniform_bvec2;
};

buffer SSBO {
    bvec2 buffer_bvec2;
};



void main() {
    buffer_bvec2 = uniform_bvec2;
}

```

**Comment by arcady-lunarg** [comment]
Yeah, I think the correct thing is to just always emit the boolean debug type and I would welcome a PR. Before you create the PR however, it would be a good idea to check that this works fine in renderdoc, since that is the ultimate consumer of this debug info.

**Comment by chaocNV** [comment]
PR created 

> Yeah, I think the correct thing is to just always emit the boolean debug type and I would welcome a PR. Before you create the PR however, it would be a good idea to check that this works fine in renderdoc, since that is the ultimate consumer of this debug info.

PR created. I'm not very familiar with renderDoc. Could you help give this a quick run on it if you have the setup?

**Comment by arcady-lunarg** [comment]
This has been fixed by the linked PR.
