### ISSUE TITLE
update_glslang_sources.py crashes under Python 3.12 because it uses now-removed distutils package

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/glslang#3393]
Python's [`distutils`](https://docs.python.org/3.11/library/distutils.html) library was deprecated, and as of Python 3.12, has been removed.

`distutils` is used by the mandatory script `update_glslang_sources.py`, which, under Python 3.12, [causes a crash](https://github.com/KhronosGroup/MoltenVK/actions/runs/6777012874/job/18419777348?pr=2060) (_see Fetch Dependencies dropdown_).

On some platforms, Github CI [uses Python 3.12](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md#python) by default.

**Comment by arcady-lunarg** [comment]
This could be replaced with `os.makedirs(exist_ok=True)`, which exists since Python 3.2 (2011). I'll make a PR to do this.
