### ISSUE TITLE
requesting sanity check on HLSL memory barrier mapping to SPIR-V

### ISSUE THREAD

**Issue by steve-lunarg** [KhronosGroup/glslang#341]
I am adding HLSL memory barrier intrinsics which map to SPIR-V, but I have no direct experience with these intrinsics in any shading language.  I have created these mappings: if someone with detailed knowledge of the space sees a problem, it would be good to hear this :).

* AllMemoryBarrier (+WithGroupSync)
    Will map to spv::OpMemoryBarrier with spv::ScopeCrossDevice and spv::MemorySemanticsAllMemory
    +WithGroupSync will be OpControlBarrier, which is *also* a memory barrier in SPIR-V, using the same scope and memory semantic.

* DeviceMemoryBarrier (+WithGroupSync):
    Will map to spv::ScopeDevice and spv::MemorySemanticsAllMemory

*  GroupMemoryBarrier (++WithGroupSync):
    Will map to spv::ScopeWorkgroup and spv::MemorySemanticsWorkgroupMemoryMask

**Comment by johnkslang** [comment]
Did you find something that implies cross-device barriers?  I doubt this is implemented.

**Comment by steve-lunarg** [comment]
Thanks... the HLSL docs are a bit ... unspecific in this area.  I was initially thinking cross device would be "safe", but I've since been convinced by @johnkslang that may not be the case.  So if All becomes device scoped:

AllMemoryBarrier: ScopeDevice + MemorySemanticsAllMemory (which no longer requires a new AST opcode, since it matches an existing one for both memory and control).

DeviceMemoryBarrier: ScopeDevice + CrossWorkgroupMemory (_??_)  This would match the existing AST OpGroupMemoryBarrier, but there's no AST op for the control form AFAIK).

GroupMemoryBarrier: ScopeWorkgroup + MemorySemanticsWorkgroupMemory (this does **not** match EOpGroupMemoryBarrier... but maybe it's what EOpGroupMemoryBarrier should really be?)
