### ISSUE TITLE
glslang_shader_preprocess crashes in subcall SetupBuiltinSymbolTable

### ISSUE THREAD

**Issue by xzores** [KhronosGroup/glslang#3414]
See image, the crash happens in SetupBuiltinSymbolTable. This happens on the newest version.
![image](https://github.com/KhronosGroup/glslang/assets/17770917/8ff0b81e-ef23-4085-a1ae-f7ad460feebc)

![image](https://github.com/KhronosGroup/glslang/assets/17770917/3b078e70-8f6e-416f-bbf3-ea06df8fc425)

glslang_shader_create seems to work.

The input passed:
```
input : glslang.input_t = {
        language = .SOURCE_GLSL,
        stage = stage,
        client = .CLIENT_VULKAN,
        client_version = .TARGET_VULKAN_1_2,
        target_language = .TARGET_SPV,
        target_language_version = .TARGET_SPV_1_5,
        code = shaderSource,
        default_version = 100,
        default_profile = .NO_PROFILE,
        force_default_version_and_profile = false,
        forward_compatible = false,
        messages = .MSG_DEFAULT_BIT,
        resource = glslang.default_resource(),
    };
```

The string passed : 
```
#version 450 core

layout (location = 0) in vec2 inPos;
layout (location = 1) in vec2 inUV;

layout (location = 0) out vec2 outUV;

out gl_PerVertex 
{
    vec4 gl_Position;   
};

void main(void)
{
	gl_Position = vec4(inPos, 0.0, 1.0);
	outUV = inUV;
}
```

**Comment by arcady-lunarg** [comment]
I'm afraid I can't reproduce this without more information. Could you attach the parts of your code that are calling into glslang, preferably in the form of a small standalone program I can compile and run? Also, could you give me a backtrace from the crash?

**Comment by xzores** [comment]
You can find all the code/bins in the repo : https://github.com/xzores/Odin-glsl-lang, it is bindings for the odin lang, I might have done something wrong, but I am unable to find the issue. I did check the passed values in the debugger and they all seemed fine.
You can find the code to compile inside Tests and the odin code can be compiled with `odin test . -debug` or `odin test .`

**Comment by arcady-lunarg** [comment]
Unfortunately I don't think we can help you debug FFI bindings for a non-C/C++ language. If you can reproduce this from C++ somehow, feel free to reopen. Maybe you forgot to link the C++ standard library somehow?

**Comment by ConorDamery** [comment]
Right ok, so doing a bit more digging into the issue I found this resource: https://lxjk.github.io/2020/03/10/Translate-GLSL-to-SPIRV-for-Vulkan-at-Runtime.html

I noticed the example code in the readme didn't show the initialization and finalize functions, my issue above is simply fixed by calling:

```
int ret = glslang_initialize_process(); // Not sure how to handle the return int code?
glslang_finalize_process();
```

**Comment by arcady-lunarg** [comment]
@ConorDamery if you think you can make the README clearer on this point, patches are definitely welcome.
