### ISSUE TITLE
textureProj() with vec4 coordinates

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/glslang#343]
This is a follow-up of #319 

The last comment was

@ChrisGautier
>  I think the problem is not fully addressed. There was a small SPIR-V spec inconsistency (now resolved), but there is still a glslangValidator issue.
> 
> In ESSL, textureProj on a sampler2D can be provided either a vec3 or a vec4 argument. From the ESSL specs:
> 
> gvec4 textureProj (gsampler2D sampler, vec3 P [, float bias] )
> gvec4 textureProj (gsampler2D sampler, vec4 P [, float bias] )
> 
> The third component of P is ignored when sampler has type gsampler2D and P has type vec4.
> 
> But from the SPIR-V perspective, in both cases, the w coordinate remains in the third position, since "all unused components will appear after all used components". That means glslangValidator should compact the ESSL vec4 'P' parameter into a vec3, by deleting the unused third parameter.

What defines the issue. 

I agree with @ChrisGautier, that glslang should do some magic for 
```
gsampler2D sampler, vec4 P
```
, so perspective division (last component of P) is moved to last used (*3rd*) component of `<Coordinate>` in `OpImageSampleProj*`.

If not, SPIR-V spec should change, again :).

**Comment by johnkslang** [comment]
Yes, Khronos agreed to "close up" the coordinates, which includes *q*, so glslang should follow that.

**Comment by johnkslang** [comment]
This is done by commit 65336488a8bfd53b09ee9b58cc2238c074efeb94.

Let me know if that's the full issue solved.

**Comment by ChrisGautier** [comment]
Thanks @johnkslang , I consider the issue resolved now.
