### ISSUE TITLE
no longer compiling with __linux__

### ISSUE THREAD

**Issue by Radamanthe** [KhronosGroup/glslang#344]
```
From b8d37c14878531b0ecfc691987911b15566ce71c Mon Sep 17 00:00:00 2001
From: Alexandre BACQUART <tek512DELETEME@gmail.com>
Date: Fri, 17 Jun 2016 06:06:09 +0200
Subject: [PATCH] fix __linux__ compilation failure

In a conform C/C++ environment, <math.h> doesn't introduce std::isinf (<cmath> does).

---
 glslang/MachineIndependent/intermOut.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/glslang/MachineIndependent/intermOut.cpp b/glslang/MachineIndependent/intermOut.cpp
index a5a6f2c..aad65e8 100644
--- a/glslang/MachineIndependent/intermOut.cpp
+++ b/glslang/MachineIndependent/intermOut.cpp
@@ -50,7 +50,7 @@ namespace {
 bool is_positive_infinity(double x) {
 #ifdef _MSC_VER
   return _fpclass(x) == _FPCLASS_PINF;
-#elif defined __ANDROID__ || defined __linux__ || __MINGW32__ || __MINGW64__
+#elif defined __ANDROID__ || __MINGW32__ || __MINGW64__
   return std::isinf(x) && (x >= 0);
 #else
   return isinf(x) && (x >= 0);
-- 
2.8.1
```

**Comment by johnkslang** [comment]
I didn't fully follow this.  Do we need to back out a previous change, or move a __linux__ elsewhere?

That is, is the above requesting the indicated change be made?

Thanks.

**Comment by HypnoGenX** [comment]
Removing the '|| defined __linux__' from line 51 in intermOut.cpp fixed the broken build issue for me.

**Comment by johnkslang** [comment]
The `__linux__` for `std::isinf` on line 53 was added Feb. 23 by @Marqin in commit  6df2cdbb8a0d09a381bfa230e0c91b05fc6b36fa.

Line 42 controls `cmath.h`.

So, my view shows  `__linux__` bringing in `cmath.h` and then using  `std::isinf`, consistent with what your email is suggesting.

Would like to converge on something, not ping pong.  Is it possible you don't have the code it line 42?

```
#ifdef _MSC_VER
#include <float.h>
#elif defined __ANDROID__ || defined __linux__ || __MINGW32__ || __MINGW64__
#include <cmath>
#else
#include <math.h>
#endif
```

**Comment by HypnoGenX** [comment]
Not entirely comfortable speculating, but in my case the problem seems to lie in the Vulkan-LoaderAndValidation project, which is where I ran into the glslang build failing.

It pulls in glslang as an external dependency, and it looks like it then checks out a specifict commit (4678ca9dacfec7a084dbc69bbe568bdad6889f1b as of this writing). Checking that out manually, it indeed lacks the cmath.h include, which does show up in the current HEAD of glslang. So maybe this should be a bug report for that project instead?

**Comment by Radamanthe** [comment]
Ok guys, sorry it's not the right place to report it. This issue is indeed fixed on glslang master branch. As HypnoGenX suggested, I will report it downstream. But I'm not sure which one of LunarG/VulkanSamples (which I use) or KhronosGroup/Vulkan-LoaderAndValidationLayers (which I don't use directly) I should report it to. Are you sure validation layers is the one deciding which commit to sync with?

**Comment by HypnoGenX** [comment]
Looks like https://github.com/LunarG/VulkanSamples uses the same build method, and is pulling in the same revision (in https://github.com/LunarG/VulkanSamples/blob/master/glslang_revision). So I'm thinking the bug should be reported both there and for the validation layers.

I've taken the liberty of reporting to both of them:
- https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/681
- https://github.com/LunarG/VulkanSamples/issues/93

**Comment by Marqin** [comment]
I've added there `__linux__` because of that bug - https://github.com/KhronosGroup/glslang/issues/171
