### ISSUE TITLE
Documentation for textureGatherLod

### ISSUE THREAD

**Issue by Ravbug** [KhronosGroup/glslang#3474]
I see references to `textureGatherLod` in glslang, such as here: https://github.com/KhronosGroup/glslang/blob/1952e63d437beb0a3ba7df27f34ced0cef656824/glslang/MachineIndependent/intermOut.cpp#L927C55-L927C71

However, I don't see any information about this function anywhere online. Does glslang support it, and if so, where can I find information about its usage and behavior?

**Comment by ncesario-lunarg** [comment]
Looks like that is for https://registry.khronos.org/OpenGL/extensions/AMD/AMD_texture_gather_bias_lod.txt and was added in https://github.com/KhronosGroup/glslang/pull/912.
