### ISSUE TITLE
Test failure with tip-of-tree spirv-tools

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/glslang#3505]
When building glslang with tip-of-tree spirv-tools (which contains https://github.com/KhronosGroup/SPIRV-Tools/commit/784b064f90a597d2478064161438f4986485b5d4) the glslang tests fail with:

`out/Debug/gtests/glslangtests --gtest_filter="Glsl/CompileVulkanToSpirvTest.FromFile/spv_bufferhandle3_frag"`

```
The following warnings/errors occurred:
error: SPIRV-Tools Validation Errors
error: [VUID-StandaloneSpirv-Input-09557] Input/Output interface variable id <42> contains a PhysicalStorageBuffer pointer, which is not allowed. If you want to interface shader stages with a PhysicalStorageBuffer, cast to a uint64 or uvec2 instead.
  %k = OpVariable %_ptr_Input__ptr_PhysicalStorageBuffer_t4 Input
```

**Comment by dj2** [comment]
@spencer-lunarg

**Comment by spencer-lunarg** [comment]
sorry @arcady-lunarg I totally dropped to ball and forgot to warn you of this (wasn't sure why I didn't expect glslang to possibly do this)

https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6344

We decided in the Working Group that Physical Storage Buffers should **not** directly be used as an interface storage class it really gets messy deciding how to mark Location in the interface, so instead they should be sent as `int 64` or `uvec2` across stages

for glslang, I think the simplest solution is to just warn the developers its not legal... maybe it is easy to just parse it as a int64 interface, but rather get this fixed first

**Comment by dj2** [comment]
Will this be relatively quick to fix, or should we revert the spirv-tools change until we can get glslang ready to work with it?

**Comment by spencer-lunarg** [comment]
@dj2 so talking to @arcady-lunarg we feel this whole thing is sticky because in GLSL, this interface usage is "allowed"... basically this probably should have got more agreement from everyone

**Comment by arcady-lunarg** [comment]
The offending SPIRV-Tools change got reverted and shows no sign of coming back. I'm going to close this issue for now.
