### ISSUE TITLE
SPIRV/GlslangToSpv.h with /Wall and warnings as errors.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glslang#352]
Some of these have been covered by other issues, but I'm including SPIRV/GlslangToSpv.h in a project with /Wall and warnings as errors (on Windows) and I'm getting quite a few warnings. I don't mind the glslang code itself but it would be nice if the commonly included headers compiled without warnings. To make things compile I have to disable the following warnings:

    #pragma warning( disable : 4061 )	// enumerator 'EvqLast' in switch of enum 'glslang::TStorageQualifier' is not explicitly handled by a case label
    #pragma warning( disable : 4365 )	// 'argument' : conversion from '__int64' to 'size_t', signed/unsigned mismatch
    #pragma warning( disable : 4510 )	// 'glslang::TShader::Includer::IncludeResult' : default constructor could not be generated
    #pragma warning( disable : 4625 )	// 'glslang::TIntermTyped' : copy constructor could not be generated because a base class copy constructor is inaccessible or deleted
    #pragma warning( disable : 4512 )	// 'glslang::TShader::Includer::IncludeResult' : assignment operator could not be generated
    #pragma warning( disable : 4610 )	// struct 'glslang::TShader::Includer::IncludeResult' can never be instantiated - user defined constructor required
    #pragma warning( disable : 4626 )	// 'glslang::TIntermTyped' : assignment operator could not be generated because a base class assignment operator is inaccessible or deleted
    #pragma warning( disable : 4640 )	// 'unexpectedIncludeResult' : construction of local static object is not thread-safe

**Comment by johnkslang** [comment]
I fixed most of these, by using /W4, as /Wall is a crazy amount of noise.  "Noise" includes the complaints about a `switch` not explicitly handling a `case`, even though it has a `default

**Comment by mre4ce** [comment]
Thanks John!
