### ISSUE TITLE
Missing function return type validation leads to Vulkan validation error (OpReturnValue)

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/glslang#353]
Just noticed this while rewriting a shader for adding fog to a scene.

Consider the following excerpt from a fragment shader:

	vec4 fog(float density)
	{
		const float LOG2 = -1.442695;
		float dist = gl_FragCoord.z / gl_FragCoord.w;
		float d = density * dist;
		return 1.0 - clamp(exp2(d * d * LOG2), 0.0, 1.0);
	}

	void main()
	{	
		const vec4 fogColor = vec4(0.47, 0.5, 0.67, 0.0);
		outFragColor = mix(vec4(1.0), fogColor, fog(0.25));	
	}

The fog function has a return type of vec4 but only returns a single float. Creating a SPIR-V shader from this source works fine and no error is generated. 

Using such a shader in a Vulkan application will then result in a validation layer error:

> ERROR: [SC] Code 5 : SPIR-V module not valid: OpReturnValue Value <id> '150's type does not match OpFunction's return type.

Which is actually correct, as the return type of the function is obviously wrong. 

Shouldn't this be captured by the reference compiler?

**Comment by johnkslang** [comment]
Perhaps an implicit conversion didn't take place? That belongs in GLSL -> AST in glslang, if allowed by the specification.  If not, should be a GLSL validation error.  Will fix glslang one way or the other.

**Comment by johnkslang** [comment]
So, glslang will say this:

> WARNING: 0:7: 'return' : type conversion on return values was not explicitly allowed until version 420

Though, it does seem misplaced in this case.

**Comment by johnkslang** [comment]
The part that checked if the full composite type matched (e.g., scalar vs. vector) was missing, but is now present, and catches this as an incorrect shader.

(GLSL does not yet allow implicit conversion from scalar to vector, etc.)
