### ISSUE TITLE
Didn't dectect shader error: return type in function didn't match prototype.

### ISSUE THREAD

**Issue by mrzerg** [KhronosGroup/glslang#356]
Take a simple shader as example, the following shader should generate a compile error, please see the types in bold text:

#version 450

layout(location = 0) in vec3 inUVW;
layout(location = 0) out vec4 outFragColor;

**float** hash(vec3 v)
{
    **return fract(v);**
}

void main()
{
    float temp = hash(inUVW);
    outFragColor = vec4(temp, 0, 0, 1);
}

**Comment by baldurk** [comment]
I think this is a dupe of #353.

**Comment by mrzerg** [comment]
Yes, thank you for figuring it out.
