### ISSUE TITLE
When will this be fixed? I have already sent PR

### ISSUE THREAD

**Issue by GermanAizek** [KhronosGroup/glslang#3567]
https://github.com/KhronosGroup/glslang/blob/b34f619e1c85810dcb3c578107d2e48ba4ee2b37/glslang/MachineIndependent/Constant.cpp#L698-L699

change from `getI64Const()` to `getU64Const()`

**Comment by GermanAizek** [comment]
PR has merged but there is still no fix in the master branch,
https://github.com/KhronosGroup/glslang/pull/3450

**Comment by arcady-lunarg** [comment]
The main branch is called `main` and not `master`, the commit in that PR has already been merged into `main`.
