### ISSUE TITLE
Support for VK_KHR_uniform_buffer_standard_layout

### ISSUE THREAD

**Issue by Trider12** [KhronosGroup/glslang#3652]
[VK_KHR_uniform_buffer_standard_layout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_uniform_buffer_standard_layout.html) allows uniform buffers to use the std430 layout. When compiling a shader using this feature I get:

```
'std430 requires the buffer storage qualifier' : required extension not requested: GL_EXT_scalar_block_layout
```
Adding this extension does fix the error, but I don't understand, why I have to do that. This is a separate extension. Vulkan has a corresponding [VK_EXT_scalar_block_layout](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_scalar_block_layout.html) extension for it.

I understand that glsl has no corresponding extension to  VK_KHR_uniform_buffer_standard_layout, so it's not possible to request it from the shader source, but a command line option and a boolean parameter in the API can do that. SPIRV-Tools has `--uniform-buffer-standard-layout` and `void spvValidatorOptionsSetUniformBufferStandardLayout(spv_validator_options options, bool val);` respectively.

**Comment by arcady-lunarg** [comment]
Per the [GLSL spec](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf), 
> a shader using the std430 qualifier on a uniform block will result in a compile-time error, unless it is also declared with push_constant.

The only way to modify that is by requesting an extension. In this case, the extension is [GL_EXT_scalar_block_layout](https://github.com/KhronosGroup/GLSL/blob/main/extensions/ext/GL_EXT_scalar_block_layout.txt) and says:
>    Additionally, this extension now allows uniform blocks to be decorated with the std430 layout.

As to why it works this way, GLSL and SPIR-V are language that do not just work with Vulkan, so they each have their own extensions. In this case, the one GLSL extension maps to these two separate Vulkan extensions and at the SPIR-V level there are no extensions, it's just that the offsets declared in the SPIR-V are different.
