### ISSUE TITLE
The order of sampler2D objects after conversion depends on the order in which they are used.

### ISSUE THREAD

**Issue by vinsentli** [KhronosGroup/glslang#3655]
The order of sampler2D objects after conversion depends on the order in which they are used.

This is my source shader:
```glsl
#version 460

layout(set = 0, binding = 0) uniform sampler2D texUnit0;
layout(set = 0, binding = 1) uniform sampler2D texUnit1;
layout(set = 0, binding = 2) uniform sampler2D texUnit2;
layout(set = 0, binding = 3) uniform sampler2D texUnit3;

void main()
{
    lowp vec4 color3 = texture(texUnit3, texCoord_f);
    lowp vec4 color0 = texture(texUnit0, texCoord_f);
    lowp vec4 color1 = texture(texUnit1, texCoord_f);
    lowp vec4 color2 = texture(texUnit2, texCoord_f);

    outColor = vec4(1,1,1,1);
}

``` 

After transfer by glslang + spriv-cross,

the reflect json file:
```
"textures" : [
        {
            "type" : "sampler2D",
            "name" : "texUnit0",
            "set" : 0,
            "binding" : 0
        },
        {
            "type" : "sampler2D",
            "name" : "texUnit1",
            "set" : 0,
            "binding" : 1
        },
        {
            "type" : "sampler2D",
            "name" : "texUnit3",
            "set" : 0,
            "binding" : 3
        },
        {
            "type" : "sampler2D",
            "name" : "texUnit2",
            "set" : 0,
            "binding" : 2
        }
    ]
``` 

my OpenGLES shader :
```glsl
#version 300 es

uniform highp sampler2D texUnit3;
uniform highp sampler2D texUnit0;
uniform highp sampler2D texUnit1;
uniform highp sampler2D texUnit2;
``` 

my metal shader : 
```c++
fragment main0_out main0(main0_in in [[stage_in]], 
texture2d<float> texUnit3 [[texture(0)]], texture2d<float> texUnit0 [[texture(1)]], 
texture2d<float> texUnit1 [[texture(2)]], texture2d<float> texUnit2 [[texture(3)]], 
sampler texUnit3Smplr [[sampler(0)]], sampler texUnit0Smplr [[sampler(1)]], 
sampler texUnit1Smplr [[sampler(2)]], sampler texUnit2Smplr [[sampler(3)]])
``` 

The texture binding number  in metal shader is different from the original opengl shader.

**Comment by arcady-lunarg** [comment]
What is your full workflow here? How do you go from your original GLSL to your metal shader? In any case, the order of the samplers shouldn't really matter in any case: in Vulkan (and Metal), what matters is the binding number for each one, while in OpenGL (and OpenGL ES) what matters is the name. Perhaps what is happening here is that the binding numbers get lost when you run spirv-cross and get GL ES. However, it does appear that the order in which the sampler variable are emitted is the order in which they are used rather than the order in which they are declared.

**Comment by vinsentli** [comment]
> What is your full workflow here? How do you go from your original GLSL to your metal shader? In any case, the order of the samplers shouldn't really matter in any case: in Vulkan (and Metal), what matters is the binding number for each one, while in OpenGL (and OpenGL ES) what matters is the name. Perhaps what is happening here is that the binding numbers get lost when you run spirv-cross and get GL ES. However, it does appear that the order in which the sampler variable are emitted is the order in which they are used rather than the order in which they are declared.


@arcady-lunarg 
You can look the metal shader carefully.
The texture binding number in metal shader is different from the original opengl shader.

**Comment by vinsentli** [comment]
I known this is the bug of SPIRV-Cross.

**Comment by vinsentli** [comment]
CompilerMSL::Options::enable_decoration_binding
