### ISSUE TITLE
Change to CMake install rule for the include directory?

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/glslang#3681]
It seems like there are lots of missing headers in the install/include directory now. For example MachineIndependent seems to only come with Versions.h now, and is missing other useful headers such as iomapper.h.
SPIRV is missing SpvTools.h is another example of a useful header that's no longer copied.
Is there a new workflow to follow?

**Comment by arcady-lunarg** [comment]
The pruning of headers was intentional, but it is possible that I may have been too enthusiastic with cutting things down and am certainly open to adding things back if someone complains that they need them. Mostly the goal was to avoid exposing all the private insides of the compiler as a public API because it would be impossible to maintain a stability guarantee there. I will take a look at those two headers and either add them back in or find some way for you to access the equivalent functionality.

**Comment by mbechard** [comment]
Thanks, at the top level I include
```
#include <glslang/Public/ShaderLang.h>
#include <glslang/MachineIndependent/iomapper.h>
#include <glslang/SPIRV/disassemble.h>
#include <glslang/SPIRV/SpvTools.h>
```

The complete list of missing headers due to chained includes is:

Include/Common.h
Include/PoolAlloc.h
Include/Types.h
Include/BaseTypes.h
Include/arrays.h
Include/SpirvInstrinsics.h
Include/ConstantUnion.h
Include/gl_types.h

MachineIndependent/iomapper.h
MachineIndependent/LiveTraverser.h
MachineIndependent/reflection.h
MachineIndependent/localintermediate.h
MachineIndependent/intermediate.h

SPIRV/SpvTools.h

**Comment by arcady-lunarg** [comment]
That transitive set definitely includes some things I would prefer not to expose as public API, but also I don't think those transitive headers are strictly necessary for what you want to access. I'll work on making a PR.

**Comment by arcady-lunarg** [comment]
Adding `SPIRV/SpvTools.h` required just a bit of mucking around with includes to get rid of transitive dependencies. I made a PR for that here: #3683. The iomapper.h header looks like it's more deeply entwined with various glslang innards, so I think for that I would want to know a bit more about how you use it so that we can determine a suitable public interface.

**Comment by mbechard** [comment]
Sure, I use classes exposed in iomapper.h to do this:

```
glslang::TDefaultGlslIoResolver* resolver = nullptr;
for (auto e : GX_ShaderStage())
{
  auto& stage = myShaderInfo->stages[e];
  if (!stage.isValid())
	  continue;
  
  auto* intermediate = program.getIntermediate(convertStage(e));
  resolver = new glslang::TDefaultGlslIoResolver(*intermediate);
  break;
}

glslang::TGlslIoMapper* remapper = new glslang::TGlslIoMapper();

if (!program.mapIO(resolver, remapper))
{
  std::cout << "GLSL mapIO Failed for:" << std::endl;
  std::cout << program.getInfoLog() << std::endl;
  std::cout << program.getInfoDebugLog() << std::endl;
  myCompileSuccess = false;
}
delete resolver;
delete remapper;

```

**Comment by arcady-lunarg** [comment]
Thanks. That same functionality recently got exposed via the C interface, I'll make a PR to make this work with the C++ interface as well without exposing too much of the internals.

**Comment by arcady-lunarg** [comment]
I think this is going to take a bit of work and will probably require writing a new wrapper class for this functionality, which will probably just be a slightly more object oriented version of the C API and will require some changes on your end to use this new API.

**Comment by mbechard** [comment]
No problem, happy to change my usage.

**Comment by arcady-lunarg** [comment]
@mbechard Could you take a look? We've added some functions to `ShaderLang.h` which should be adequate for your usage, and closely parallel the C API as well.

**Comment by mbechard** [comment]
Looks like I'm missing access to `setAutoPushConstantBlock()` that used to be part of the glslang::TIoMapper. Could that be made virtual in the base class?
Also the `glslang::SpirvToolsEliminateDeadInputComponents()` workflow requires access to the `spv_target_env`, which I previously got via
`spv_target_env targetEnv = glslang::MapToSpirvToolsEnv(intermediate->getSpv(), &logger);`
But I don't have access to the SpvVersion anymore since intermediate is now an opaque type.

**Comment by arcady-lunarg** [comment]
Some of the SpirvTools entry point take an intermediate and mostly just use it to do `MapToSpirvToolsEnv(intermediate.getSpv(), logger)`. Maybe we should either make the entry points you need take the intermediate, or maybe even make MapToSpirvToolsEnv take an intermediate (or introduce an overload that does this).

**Comment by mbechard** [comment]
Yep, makes sense to me.

**Comment by arcady-lunarg** [comment]
@mbechard Would you be able to make a PR to update `SpvTools.h` by tomorrow? Then we can get it in before the release that's supposed to happen at the end of tomorrow and not have to break the ABI again.

**Comment by mbechard** [comment]
Yep I can do this tonight
