### ISSUE TITLE
Misplaced minus sign...should be in exponent

### ISSUE THREAD

**Issue by robertschulman1** [KhronosGroup/glslang#3687]
Document Revision 17 of The OpenGL ES Shading Language doc (dated May 12 2009) has a typo in Section 4.5.1. The typo is in the sentence describing minimum range requirements for floating point representations. The text reads that the range is "(-2 ** 62, 2 ** 62)"; the text should be "(2 ** -62, 2 ** 62)".

**Comment by robertschulman1** [comment]
Oops. never mind.

**Comment by robertschulman1** [comment]
Brain cramp at this end. Bad reading of parsing priority order of a minus sign,

**Comment by arcady-lunarg** [comment]
No worries, for future reference though this is the repository for the glslang compiler, issues with the GLSL language spec itself should be filed in https://github.com/KhronosGroup/GLSL
