### ISSUE TITLE
SPIR-V for gl_NumSamples

### ISSUE THREAD

**Issue by ChrisGautier** [KhronosGroup/glslang#369]
glslangValidator translates accesses to _gl_NumSamples_ (and _gl_SampleID_, for comparison) to SPIR-V as follows:

```
           OpName %14 "gl_SampleID"
           OpName %17 "gl_NumSamples"
           ...
           OpDecorate %14 BuiltIn SampleId
           ...
           %14 = OpVariable %13 Input
           %16 = OpTypePointer UniformConstant %11
           %17 = OpVariable %16 UniformConstant
```

Note the **UniformConstant** storage space. It contradicts the Vulkan specs:

> Variables identified with the **UniformConstant** storage class are used only as handles to refer to opaque resources. Such variables must be typed as **OpTypeImage**, **OpTypeSampler**, **OpTypeSampledImage**, or arrays of only these types. Variables of type **OpTypeImage** must have a **Sampled** operand of 1 (sampled image) or 2 (storage image).

A related problem is that there is no SPIR-V **BuiltIn** value for _gl_NumSamples_.

But perhaps _gl_NumSamples_ was not meant to be supported in SPIR-V natively, in which case GL_KHR_vulkan_glsl should document that. One can compare _gl_NumSamples_ with _gl_DepthRangeParameters_. The latter is explicitly removed in GL_KHR_vulkan_glsl.

**Comment by johnkslang** [comment]
`gl_NumSamples` is no longer declared now for SPIR-V targets.

Also, a Khronos-internal bug has been created for clarifying GL_KHR_vulkan_glsl.
