### ISSUE TITLE
How to set source information after the move to public headers?

### ISSUE THREAD

**Issue by iwubcode** [KhronosGroup/glslang#3691]
In version 13, you could attach source information to the SPIRV glslang created with [setSourceFile](https://github.com/KhronosGroup/glslang/blob/7c4d91e7819a1d27213aa3499953d54ae1a00e8f/glslang/MachineIndependent/localintermediate.h#L1084) and [addSourceText](https://github.com/KhronosGroup/glslang/blob/7c4d91e7819a1d27213aa3499953d54ae1a00e8f/glslang/MachineIndependent/localintermediate.h#L1086).  This was useful when wanting to see the original source in a tool like RenderDoc.  [With the move of TIntermediate to the internal API](https://github.com/KhronosGroup/glslang/issues/3320), what is the way to handle this now in glslang and still use the public interface?

**Comment by arcady-lunarg** [comment]
This got added to the C interface as `glslang_program_set_source_file` and `glslang_program_add_source_text` but equivalent entry points did not get added to the C++ interface. I'll make a PR to add these as methods on `TProgram`.
