### ISSUE TITLE
glslc will produce different output file names based on extension

### ISSUE THREAD

**Issue by KoT3isGood** [KhronosGroup/glslang#3696]
Vertex and fragment shaders will have their extension in SPIR-V file name:
shader.vert -> shader.vert.spv
shader.frag -> shader.frag.spv
But ray tracing pipeline shaders won't:
shader.rgen -> shader.spv
shader.rchit -> shader.spv
shader.rmiss -> shader.spv

**Comment by arcady-lunarg** [comment]
The glslc command comes from [shaderc](https://github.com/google/shaderc), which is a separate project from glslang. Is your issue with glslang or glslc? If it's the latter, you should open the issue in that repository.
