### ISSUE TITLE
Cache for builtin symbol tables not sensitive to GLSL vs. HLSL source language

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/glslang#370]
This is similar to #166 but now the difference that is not being accounted for is a switch between source languages GLSL and HLSL.

That is, SetupBuiltinSymbolTable takes a "source" parameter of type EShSource but then the check for an entry in CommonSymbolTable is not sensitive to that parameter, and the function can early-return when it should not.  In that case you can try to process an HLSL source program when you have builtins for GLSL, or vice versa.

**Comment by johnkslang** [comment]
Fixed by 0a6fb8549456c0b9d016eed5dec0cff1e2029662.
