### ISSUE TITLE
Error for '#' in middle of line but ifdef'd out

### ISSUE THREAD

**Issue by rj123-nv** [KhronosGroup/glslang#3704]
After commit feb5437 (PP: Report an error when a # is not the first thing on a line ), code that uses '#' in the middle of a line now errors.

We have code that is meant to interop with C++, which is ifdef'd out when compiling through glslang, but will still error.

Here's a small example:

```#version 460
#if 0
#define STRINGIFY(A) #A
#endif
void main()
{
}
```

error:
` error: '#' : (#) can be preceded in its line only by spaces or horizontal tabs`

Could we relax the error so it doesn't apply to code that's inactive at preprocess-time?
Maybe the check could be moved out of scanToken?

**Comment by arcady-lunarg** [comment]
Yes, this is definitely a bug. If you want to make a patch for it, I would be happy to accept it.

**Comment by rj123-nv** [comment]
I can work on a patch. Would it make sense to add a bool field to the PPContext saying if we're currently skipping to an #else/#elif/#endif, and turn off the check if true?
