### ISSUE TITLE
Wrong offsets in buffer_reference

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/glslang#3715]
During creation of pipeline with `pSpecializationInfo: a = 2, b = 2` I get an error:
 > [ VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06849 ] Validation Error   | Objects: {} | Queues: {} | CommandBuffers: {} | MessageID = 0x437c19d3 | Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06849 ] | MessageID = 0x437c19d3 | vkCreateComputePipelines(): pCreateInfos[0].stage After specialization was applied, VkShaderModule 0xcb89ee0000000315[trace.comp] produces a spirv-val error (stage VK_SHADER_STAGE_COMPUTE_BIT):
Structure id 14 decorated as Block for variable in PhysicalStorageBuffer storage class must follow scalar storage buffer layout rules: member 1 at offset 4 overlaps previous member ending at offset 7
  %Tree = OpTypeStruct %_arr_float_x %_arr_float_y
. The Vulkan spec states: If a shader module identifier is not specified, the shader code used by the pipeline must be valid as described by the Khronos SPIR-V Specification after applying the specializations provided in pSpecializationInfo, if any, and then converting all specialization constants into fixed constants (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06849)

Minified shader:
```glsl
#version 460 core

#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : enable

layout(constant_id = 0) const uint x = 1;
layout(constant_id = 1) const uint y = 1;

layout(buffer_reference, scalar, buffer_reference_align = 8) readonly buffer Tree
{
    float a[x];
    float b[y];
};

bool traceRay(Tree tree)
{
    return tree.a[0] < 0.0f;
}

layout(push_constant, scalar) uniform PushConstants
{
    Tree tree;
};

void main()
{
    traceRay(tree);
}
```
Invocation:
```bash
glslangValidator -gVS -g --target-env vulkan1.3 --spirv-val shaders/trace.comp.glsl --depfile shaders/trace.comp.spv.d -o shaders/trace.comp.spv
```
Versions:
```bash
# glslangValidator -v
Glslang Version: 11:14.2.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 14.2.0
GLSL Version: 4.60 glslang Khronos. 14.2.0
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 11
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```
NVIDIA Driver version: `555.58.02`
`vulkan-validation-layers-1.3.275-1`

**Comment by arcady-lunarg** [comment]
This is an interesting side effect of specialization but if you read the GLSL spec in section 4.11, it does say

> Arrays inside a block may be sized with a specialization constant, but the block will have a static
layout. Changing the specialized size will not re-layout the block. In the absence of explicit offsets,
the layout will be based on the default size of the array

So the result that you are getting is indeed the expected one: specializing the module doesn't re-layout the structs. You can of course put a `layout(align = 8)` qualifier on the struct members and then it will for an array size of 2, but will leave gaps when x is 1.

**Comment by tomilov** [comment]
Thank you for the explanations.
