### ISSUE TITLE
Token pasting not supported with profile es

### ISSUE THREAD

**Issue by s-perron** [KhronosGroup/glslang#3733]
For some reason, there is an error that token pasting is not supported for the ES profile. I do not understand that error because token pasting is part of the preprocessor, and does not affect any of the features used.

There is a work around to first preprocess the file one it own, and then to compile it, but that should not be necessary.

## Test case
```
#version 320 es

#define PASTE(x) AA##x

layout(location = 0) out int v;

void main() {
  int AAA = 0;
  v = PASTE(A);
}
```

## Failing command

```
» glslang t.frag --target-env vulkan1.1 --client vulkan100                                                                                                                                                                                    
t.frag
ERROR: t.frag:9: 'token pasting (##)' : not supported with this profile: es
ERROR: t.frag:9: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
```

## Workaround

```
» glslang t.frag -E | glslang --target-env vulkan1.1 --client vulkan100 --stdin -S frag                                                                                                                                                   
stdin
```

## Shader Playground link

https://shader-playground.timjones.io/658fd0ef0bf9052dc7fcf0077ea38c15

**Comment by arcady-lunarg** [comment]
Per the [GLSL ES 3.20 spec](https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf#page=19),
> There are no number sign based operators (e.g. no # or #@), no ## operator, nor is there a sizeof
operator.
So this is in fact working as designed.
