### ISSUE TITLE
vulkan-sdk-* tag for 15.0.0

### ISSUE THREAD

**Issue by sertonix** [KhronosGroup/glslang#3744]
There is no git tag yet for 15.0.0 using the `vulkan-sdk-*` scheme. Is that intentional or has that been forgotten?

**Comment by jeremy-lunarg** [comment]
Not yet. SDK is incoming. Please stand by. :smile:

**Comment by arcady-lunarg** [comment]
The `vulkan-sdk-1.3.296.0` tag has been created and points to the 15.0.0 release.
