### ISSUE TITLE
add headers installation through cmake instead of by hand

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/glslang#375]
when run `make install` only install the libraries. the headers should be installed by hand

please add cmake rules for install the headers by `make install`

**Comment by sirpalee** [comment]
I have to second this. Without the installed headers, installing the static libraries makes no sense.

Note, this could causes issues with the spirv compiler, as it refers to the glslang headers relative to the file, which would not remain the same once the headers are installed.

**Comment by Ralith** [comment]
This was fixed by #706, right?

**Comment by sl1pkn07** [comment]
yes!

tnks!
