### ISSUE TITLE
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)

### ISSUE THREAD

**Issue by LUser-12** [KhronosGroup/glslang#3752]
Hello i am trying to build gslang and whenever i try to clone it i get this:

error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 2764 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

I an on popos 22.04

**Comment by arcady-lunarg** [comment]
This sounds like a git error and not anything to do with glslang specifically, and it sounds like you get the error before you even finish cloning the repository. Maybe it's a github problem?
