### ISSUE TITLE
gl_Layer issues on fragment shaders

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/glslang#376]
When compiling a fragment shader using gl_Layer, seems that GlslangToSpv.cpp will not add spv::CapabilityGeometry which will later fail the validation layer. Is this a validation issue or is the SPIRV correct in this case?

**Comment by johnkslang** [comment]
Probably missed because it would be a fragment stage saying the **Geometry** capability is needed.

The SPIR-V spec. does say use of the **Layer** Builtin requires the **Geomtery** capability.  Will fix.
