### ISSUE TITLE
"gl_MaxCombinedTextureImageUnits (using array)" Vulkan

### ISSUE THREAD

**Issue by Chrjstoph** [KhronosGroup/glslang#377]
Hi,  i try to use texture2D[] arrays.

It appears that glslangvalidator causes the invocation of "gl_MaxCombinedTextureImageUnits (using array)" when binding the array with texture2D [78+].

It there anything else to do but to run the validator with "-V"?

Or is it broken as suggested here:
 https://forums.khronos.org/showthread.php/13109-Vulkan-(vs-)-MultiDrawIndirect?p=40488&viewfull=1#post40488

**Comment by Duttenheim** [comment]
You are sure this isn't the limitation encountered when running TShader::parse? I got the same issue, then just changed the TBuiltInResource.maxCombinedTextureImageUnits to a big number, and that solved the problem.

**Comment by johnkslang** [comment]
Yes, this should be controlled through a configuration.  See the usage and `.conf`.
