### ISSUE TITLE
Validation error when compiling shaders with `-gVS` using Vulkan SDK 1.3.296.0

### ISSUE THREAD

**Issue by imrodriguezro** [KhronosGroup/glslang#3781]
Hello,

I updated my Vulkan SDK to the latest version and I get an error from the validation layers when the spirv files are used for creating graphics pipelines:

```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55555768cf10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: NonSemantic.Shader.DebugInfo.100 DebugTypePointer: expected operand Base Type must be a result id of DebugTypeBasic
    %41 = OpExtInst %void %1 DebugTypePointer %37 %uint_3 %uint_0
```
    
Is this a known issue or something? can I do something from my side to silence the error?

**Comment by spencer-lunarg** [comment]
@imrodriguezro the `UNASSIGNED-CoreValidation-Shader-InconsistentSpirv` is an old error message, I think you might have an old validation layer, not sure if it will fix it or not

**Comment by imrodriguezro** [comment]
@spencer-lunarg thanks for your answer. So, what you're saying is that the `glslang` that comes with the latest Vulkan SDK to this date is considered already old? or that the validation error layer is old?

**Comment by spencer-lunarg** [comment]
It seems you have an old Validation Layer, the current layer would produce that error message

So to just confirm, if you go `where glslang.exe` (or `which glslang` on max/linux) does it it have a number to the SDK, make sure it is at 1.3.296 (the latest version) ... sometimes people grab the SDK, but the Environment Path is not setup and it points to an older SDK instead
