### ISSUE TITLE
SPIR-V intrinsics spirv_execution_mode not works with SignedZeroInfNanPreserve

### ISSUE THREAD

**Issue by GinShio** [KhronosGroup/glslang#3794]
According to vulkan spec 1.3.296:
> + If the environment is not specified in the SPIR-V then it is determined as follows:
>   * If any of the following conditions are true then the flags NSZ, NotInf, and NotNaN are assumed:
>     - **The entry point does not use the Execution Mode SignedZeroInfNanPreserve with a bit-width corresponding to one of the operands or to the result type.**

If I understand correctly, I should use execution mode **[SignedZeroInfNanPreserve](https://www.google.com.hk/url?sa=t&source=web&rct=j&opi=89978449&url=https://htmlpreview.github.io/%3Fhttps://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_float_controls.html&ved=2ahUKEwjG29LyrN6JAxV8R2wGHfCCBysQFnoECBEQAQ&usg=AOvVaw1ocFeXo3pARsHQSdURj9cK)** if I want to disable the `NotNaN` flag. Therefore, I want to use spirv intrinsic in glsl. But it looks cannot work.

For example,
```glsl
#version 450

#extension GL_EXT_spirv_intrinsics : enable

layout(local_size_x = 16, local_size_y = 16) in;

spirv_execution_mode(extensions=["SPV_KHR_float_controls"], capabilities=[4466], 4461);
// spirv_execution_mode(4461);  // SignedZeroInfNanPreserve

layout(std430, binding = 0) buffer SSBO {
  vec4 o[256];
};

layout(binding = 2) uniform UBO {
  vec4 v4[256];
};

const float kNan = 0.0 / 0.0;

//                     Quiet NaN,   Signaling NaN, Infinity,    Real (1.0)
const uvec4 k4 = uvec4(0x7FF0FFFFu, 0xFFA0FFFFu,   0x7F800000u, 0x3F800000u);

void main() {
  vec4 r0 = v4[gl_LocalInvocationID.x];
  r0.y = uintBitsToFloat(r0.y == 1.0 ? k4.x : 0u);
  r0.x = r0.x != 0.0 ? 0.0 : r0.y;
  o[gl_LocalInvocationID.x] = mix(vec4(1.0, 0.0, 0.0, 1.0), vec4(0.0, 1.0, 0.0, 1.0), notEqual(vec4(r0.xxxx), vec4(0.)));
}
```

Either glslc or glslangValidator, compiler generates spv file. But when I disassemble the file, get a error:
```
error: input:0:0:8: End of input reached while decoding OpExecutionMode starting at word 39: expected more operands after 3 words.
```

**Comment by arcady-lunarg** [comment]
Quoting the [SPV_KHR_float_controls spec](https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_float_controls.asciidoc), it says that 

> **SignedZeroInfNanPreserve**
... Only affects instructions operating on a scalar or a composite type derived from a scalar floating-point type defined by the extra operand of OpExecutionMode

So you need to put an extra operand for the bit width in your spirv_execution_mode() statement, like so:
```
spirv_execution_mode(extensions=["SPV_KHR_float_controls"], capabilities=[4466], 4461, 32);
```
That should make things work. If you use float16s or doubles, you would need to put separate spirv_execution_mode statements for those.

**Comment by GinShio** [comment]
**Thanks very much!** It works!
