### ISSUE TITLE
Invalid SPIR-V when compiling GLSL with -gVS debug information

### ISSUE THREAD

**Issue by JonasRock** [KhronosGroup/glslang#3802]
Hello,

Compiling the following GLSL code using glslangValidator produces no diagnostics.

```
#version 450

layout (location = 0) out vec4 out_frag_color;

float eval() {
    vec4 shadow_coords = vec4(1.0f, 1.0f, 1.0f, 1.0f);
    if (shadow_coords.w > 0.0 && 0.5 < shadow_coords.z) {
        return 0.0;
    }
    return 1.0f;
}

void main() {
    out_frag_color = vec4(eval(), 1.0f, 1.0f, 1.0f);
}
```

However, when compiling with the -gVS option to generate debug information, spirv-val generates the following error:

```
error: line 102: OpPhi must appear within a non-entry block before all non-OpPhi instructions (except for OpLine, which can be mixed with OpPhi).
  %69 = OpPhi %bool %60 %22 %68 %61
```

These errors do NOT appear when either the left or the right part of the if statement condition is removed (for example, using `if (shadow_coords.w > 0.0)` or `if (0.5 < shadow_coords.z)` instead) or when compiling without the -gVS option.

The full command used to compile the code:
```
glslangValidator -e main -gVS -V -o shaders/test.frag.spv shaders/test.frag
```

Used glslangValidator version:

```
Glslang Version: 11:14.1.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 14.1.0
GLSL Version: 4.60 glslang Khronos. 14.1.0
SPIR-V Version 0x00010600, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 11
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
```

**Comment by arcady-lunarg** [comment]
Could you try this with a newer version of glslang? We fixed a bug related to this recently and I can't reproduce your issue with a recent build.

**Comment by JonasRock** [comment]
Using the current continous release build fixed the issue. Thank you.
