### ISSUE TITLE
include file in glsl code

### ISSUE THREAD

**Issue by edrickhong** [KhronosGroup/glslang#381]
More of a question, but is it possible to include other files in glsl?

**Comment by johnkslang** [comment]
Are you asking if GLSL supports `#include`?  Only through an extension. Glslang has infrastructure support for it, used by shaderc.  The "hard" part is basically done, but not hooking it up to specific extensions or concrete rules for "path" semantics.

**Comment by edrickhong** [comment]
GL_ARB_shading_language_include

Is this the extension? I have it enabled but i get am unexpected include preprocessor.

I'm using it like this:

#extension GL_ARB_shading_language_include : require

#include "test.glsl"

Am I using it wrong?

**Comment by johnkslang** [comment]
It is not yet hooked up.  The details of the low-level mechanism are done, but not the actual plumbing of it through to a specific policy and extension.

**Comment by edrickhong** [comment]
Alright. Thanks for the help.
