### ISSUE TITLE
Assertion crash in arrays.h when binding an unsized atomic_uint array uniform with binding.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#382]
Running glslangValidator with this input:
```glsl
#version 420
layout(binding=0) uniform atomic_uint a[];
```
as a fragment shader fails this assertion:
```
glslangValidator: /glslang/MachineIndependent/../Include/arrays.h:246: int glslang::TArraySizes::getCumulativeSize() const: Assertion `sizes.getDimSize(d) != UnsizedArraySize' failed.
fish: “../build/StandAlone/glslangVali…” terminated by signal SIGABRT (Abort)
```

This assertion should maybe be replaced with an error check before getCumulativeSize is ever called.

**Comment by xorgy** [comment]
There's also a bunch of weird stuff in `arrays.h`, like this:
```c++
const int UnsizedArraySize = 0;
...
struct TSmallArrayVector {
...
    unsigned int getDimSize(int i) const
    {
        assert(sizes != nullptr && (int)sizes->size() > i);
        return (*sizes)[i].size;
    }
...
struct TArraySizes {
...
    int getDimSize(int dim) const { return sizes.getDimSize(dim); }
...
    bool isInnerImplicit() const
    {
        for (int d = 1; d < sizes.size(); ++d) {
            if (sizes.getDimSize(d) == (unsigned)UnsizedArraySize)
                return true;
        }

        return false;
    }
...
```
Where there seems to be some disagreement as to whether UnsizedArraySize should be signed or unsigned.

Though I'm not sure that much can be done about this; as I understand it, these are public API header files.

**Comment by johnkslang** [comment]
These are layers of implementation, each layer exposing its own semantics by building on the layer below it.  So, they don't intrinsically have to match, and I think were matching some higher-level expectations (like at the lowest level, we know array sizes are unsigned, but at a higher level, existing code manipulating them used signed, and maybe even -1 historically for unsized).  History.

I will certainly look into fixing the bug.
