### ISSUE TITLE
Vertex info : Can't convert to expr: texelFetch 

### ISSUE THREAD

**Issue by raven02** [KhronosGroup/glslang#386]
We're from RPCS3 which uses the glslang for our Vulkan graphic backend

We hit the following error on NV system (AMD system is fine) and bisect found out it breaks at this commit https://github.com/KhronosGroup/glslang/commit/a5c33d6ffb34ccede5b233bc724c907166b6e479

```
{rsx::thread} RSX: ERROR: [Driver] Code 2 : Vertex info
 -----------
(0) : fatal error C9999: Can't convert to expr: texelFetch 
```

**Comment by baldurk** [comment]
Not trying to speak for them, but I reported this to nvidia - it's a problem in their shader compiler and will be fixed in an upcoming driver release.

**Comment by raven02** [comment]
Alright . Thanks a lot.
