### ISSUE TITLE
Process for cleanly shutting down glslang is unclear

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#389]
I'm using glslang as a static library (not a dll) in my program, and I'm unclear on exactly how a clean shutdown should happen.

Currently I'm calling these functions exactly once at startup and shutdown as described in `ShaderLang.h`:

``` cpp
// Call this exactly once per process before using anything else
bool InitializeProcess();

// Call once per process to tear down everything
void FinalizeProcess();
```

This works OK, but it causes some leaks - `InitializeProcess()` &rarr; `ShInitialize()` calls `InitProcess()` in `InitializeDll.cpp`. However in contrast, `FinalizeProcess()` &rarr; `ShFinalize()` does _not_ call the corresponding `DetachProcess()` in `InitializeDll.cpp`. At the moment as far as I can see, `DetachProcess()` is not called anywhere outside the `DllMain` in `OSDependent/Windows/main.cpp`.

The code for `DetachProcess()` calls `ShFinalize()` which seems backwards, but that'd be easy enough to fix. I tried modifying my code to call that instead, what I found was there are leaks/double deletes that can happen with the thread pool allocators.

A pool allocator is created initially for each thread inside `InitializeMemoryPools()`. Some code like `SetupBuiltinSymbolTable()` will temporarily `SetThreadPoolAllocator()` to a local allocator, then switch back to the previous one - this is fine. However `TShader::parse()`, `TShader::preprocess()`, and `TProgram::link()` all set do `SetThreadPoolAllocator()` to point to an object-owned allocator, and throw away the previous one - causing a leak. I think also if there are multiple objects alive on the same thread, they will continually overwrite the previous allocator with their own. Then finally there's a double delete if you ever do end up calling `DetachProcess()` or `DetachThread()` as it will try to delete the last allocator set by a `TShader` or `TProgram` and crash.

I think if I understand right, those three functions (`TShader::parse`, `TShader::preprocess`, and `TProgram::link`) should do the same push/pop as `SetupBuiltinSymbolTable` does to restore the last one after they've done their work on that thread. Maybe it's worth replacing `Get/SetThreadPoolAllocator()` with `Push/PopThreadPoolAllocator()` ?

Hopefully that's clear. I don't mind putting together a PR if the above solution sounds reasonable, but I wanted to check my understanding first.

As a related aside, although I don't use it myself, if you do try and use glslang on multiple threads there's not a public interface to call `DetachThread()` on the subsequent threads, so they will leak as well. The `DllMain` I mentioned calls into the internal `glslang::DetachThread()`.

**Comment by xorgy** [comment]
For what it's worth, even the standalone `glslangValidator` binary leaks memory. It's possible that clean shutdown is not possible with the current API.

**Comment by hrydgard** [comment]
Isn't it time to get rid of the global state entirely and add a context object, that can hold all the various global caches? Then creating/destroying this context object would be enough, and you can safely have multiple contexts to compile on multiple threads. IMHO, glslang should not concern itself with threads at all.

**Comment by johnkslang** [comment]
I believe all the issues brought up by the OP have been addressed by recent "Memory;..." commits.  You can call InitializeProcess and FinalizeProcess many times, it will count, and only do process tear down on the final FinalizeProcess. Per-thread pools have been removed, to eliminate the need for DetachThread.  Objects (shader, compiler, linker, and program) now own their own pools and do their own allocation/deallocation of their pools.
