### ISSUE TITLE
Crash when doing texture-lookups inside non-main functions

### ISSUE THREAD

**Issue by Silverlan** [KhronosGroup/glslang#397]
The following shader causes a crash inside 'createGraphicsPipelines' (Access violation reading location 0x000000000000004C), no warnings are generated:

Fragment shader:
> #version 400
> 
> #extension GL_ARB_separate_shader_objects : enable
> #extension GL_ARB_shading_language_420pack : enable
> 
> in vec2 vs_vert_uv;
> 
> layout(set = 0,binding = 0) uniform sampler2D u_texture;
> 
> layout(location = 0) out vec4 fs_color;
> 
> vec4 get_test(sampler2D tex,vec2 UV) {return texture(tex,UV);}
> 
> void main()
> {
> 	fs_color = get_test(u_texture,vs_vert_uv);
> }

Vertex shader:
> #version 400
> 
> #extension GL_ARB_separate_shader_objects : enable
> #extension GL_ARB_shading_language_420pack : enable
> 
> layout(location = 0) in vec2 in_vert_pos;
> layout(location = 1) in vec2 in_vert_uv;
> 
> out vec2 vs_vert_uv;
> 
> void main()
> {
> 	gl_Position = vec4(in_vert_pos,0.0,1.0);
> 	vs_vert_uv = in_vert_uv;
> }

The problematic line is _"fs_color = get_test(u_texture,vs_vert_uv);"_. This happens since the latest github version (16-07-19), it worked fine on the previous build I tried it on (16-05-04).
It also doesn't crash if you add an additional texture-lookup right before the call to "get_test", or if "get_test" is removed:
> void main()
> {
> 	texture(u_texture,vs_vert_uv);
> 	fs_color = get_test(u_texture,vs_vert_uv);
> }

I've used _glslang::GlslangToSpv_ to translate the shaders to spirv.

**Comment by johnkslang** [comment]
This looks like a driver bug.  The SPIR-V looks correct.

(This repository is for the case that glslang generates incorrect SPIR-V, not for the case that correct SPIR-V is not handled correctly be a driver.)

Can you check with the driver vendor or otherwise post how you think the SPIR-V is incorrect?

**Comment by Silverlan** [comment]
Well, it crashes since I've updated to the latest github-version of glslang. I didn't update anything else, not the driver or the Vulkan API.
If I go back to the previous version of glslang, it once again works fine. The data that is being generated by '_glslang::GlslangToSpv_' is very slightly different between the two glslang versions (New version is 76 bytes smaller), so there's definitely something happening differently with the new version.

**Comment by johnkslang** [comment]
A single GLSL shader can turn into many different, yet valid, SPIR-V shaders.  I suspect the driver works correctly with one valid form, but not with another.  It may be related to not copying samplers, but rather more  directly passing them.  The driver should handle both ways, as both are valid.

I'm willing to fix glslang, but need an actual handle on what incorrect thing it is doing.  The form of SPIR-V it generates will evolve over time, and drivers need to accept all valid forms of SPIR-V.

**Comment by Silverlan** [comment]
Alright, looks like it's indeed a driver bug. I've switched from my AMD card to my Nvidia card, no crashes there.
I'll try to figure out what's going on with my AMD card as soon as I can.
Thanks for the help.
