### ISSUE TITLE
#extension with 128 subsequent non-whitespace bytes triggers illegal instruction (SIGILL)

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#40]
```GLSL
#extension 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

Smells like it's jumping into some undefined memory, which seems to me like a liability to me.

**Comment by johnkslang** [comment]
Stack overrun; I found one bad stack variable holding a token that wasn't sized to match the official token length.  Commit f330f081298cd4b3474ded25ec22017e71c7dd7d fixed this.  I suspect all these similar issues are the same thing.
