### ISSUE TITLE
Segmentation fault when referencing a parametric macro with a quotation mark in a declaration.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#407]
```GLSL
#define m()
int m"
```
Triggers a segmentation fault.

**Comment by johnkslang** [comment]
This created a token string of no length (a string of 0 size). All tokenization paths need a non-0-length token to process. (Nullptr strings were caught, but not strings of no length.)

**Comment by xorgy** [comment]
NUL vs. NULL. ;-)
