### ISSUE TITLE
Infinite loop in scanner 

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#408]
```GLSL
#define m#0#
#if m
```
Causes an infinite loop in the scanner.

(the `0` character can be any character string, including valid preprocessor directive names)

**Comment by johnkslang** [comment]
This was caused by a single # as last character in macro.

This would look ahead for a second #, for token pasting, and if not found, backup one token.  This is fine, unless at the end of line, which would backup the #, rather than the non-existent look ahead token.
