### ISSUE TITLE
#extension with a single argument extending to the 128th column, bearing an opening paren, causes segfault.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#41]
```GLSL
#extension 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000(
```

**Comment by johnkslang** [comment]
I found one bad stack variable holding a token that wasn't sized to match the official token length.  Commit f330f081298cd4b3474ded25ec22017e71c7dd7d fixed this.

**Comment by xorgy** [comment]
Yeah, I saw that 80-char stack variable, assumed that was part of the problem.

Thanks. :-)
