### ISSUE TITLE
HLSL: structure cast with zero

### ISSUE THREAD

**Issue by xen2** [KhronosGroup/glslang#412]
I have been following development of HLSL and are happy to see that since cbuffer have been added, our HLSL can mostly be converter to SPIR-V as is, good work!

There is still one small thing that fails (that we could easily workaround on our side, but still letting you know because it is valid HLSL):

```
struct PS_OUTPUT 
{
    float4 ColorTarget_id1 : SV_Target0;
};
void myfunc()
{
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
}
```

works with FXC compiler, but fails with glslang:

```
ERROR: 0:572: 'constructor' : not enough data provided for construction
ERROR: 0:572: '=' :  cannot convert from 'const float' to 'temp structure{temp 4-component vector of float ColorTarget_id1}'
```

**Comment by xen2** [comment]
Note: this is not a blocker for us

**Comment by johnkslang** [comment]
Thanks for posting this, will add it to the list.

**Comment by dankbaker** [comment]
This is used quite a bit by us, but can work around for now. needs to get fixed though. It's not an uncommon pattern in HLSL, often used for VSs because HLSL enforces that all parameters have something by default.

**Comment by johnkslang** [comment]
Note this is also already captured in issue #362.
