### ISSUE TITLE
Flat applied on top-level struct, against specs

### ISSUE THREAD

**Issue by ChrisGautier** [KhronosGroup/glslang#418]
Question: Can interpolation qualifiers such as **Flat** be applied on top-level structures, or per-member only?

The SPIR-V specs seem clear to me that they can only be applied per member or scalar/vector, but not structures:

```
2.21 Instructions

Object: An instantiation of a non-void type, either as the Result <id> of an
operation, or created through OpVariable.
```

```
3.20 Decoration

Flat
Apply to an object or a member of a structure type. The object or member must
be a scalar or vector of floating-point type or integer type. Arrays of these
types are also allowed.
```

So **Flat** cannot be applied to a structure, only a scalar or vector. However, the following commit in glslangValidator contradicts that:

```
commit 76d4dfcd51f9b1624b6241a82969c7423aabf82f
Author: John Kessenich <cepheus@frii.com>
Date:   Thu Jun 16 12:43:23 2016 -0600
    SPV non-functional: minor readability improvements for texturing.
```

Consider the following shader extract:
```
#version 310 es
struct S
{
    mediump int a;
};

layout(location = 0) in flat S var;
// ...
```
Before that commit, the SPIR-V looked like this:
```
               OpName %21 "S"
               OpMemberName %21 0 "a"
               OpName %23 "var"
               OpMemberDecorate %21 0 RelaxedPrecision
               OpMemberDecorate %21 0 Flat
               OpMemberDecorate %21 0 Location 0
         %21 = OpTypeStruct %6
         %22 = OpTypePointer Input %21
         %23 = OpVariable %22 Input
         %26 = OpAccessChain %25 %23 %24
```

After the commit, the SPIR-V looks like this:
```
               OpName %21 "S"
               OpMemberName %21 0 "a"
               OpName %23 "var"
               OpMemberDecorate %21 0 RelaxedPrecision
               OpDecorate %23 Flat
               OpDecorate %23 Location 0
         %21 = OpTypeStruct %6
         %22 = OpTypePointer Input %21
         %23 = OpVariable %22 Input
         %26 = OpAccessChain %25 %23 %24
```

The SPIR-V specs are arguably correct, because being able to apply **Flat** on top-level structure creates issues regarding how to propagate decorations, and resolve conflicts of the form "**Flat** on the top-level structure + **Perspective** on a structure member".

**Comment by johnkslang** [comment]
Just to see if this clears things up first:  The commit changed the **Flat** from a *structure  type* to an *object*.  When the spec says things can go on a structure-type member it's meaning not the structure type, and when it says it can go on an object, it is not excluding that the type of the object is a structure (typically).

So, two dimensions here (type vs. object) and (structure vs. member) to be clear with in our language.

Those few lines of code now have quite a history between different parties changing it different ways, so we really need to start with what's correct and make sure we are fixing the right thing (spec. or implementation).  I'll look deeper into this.

**Comment by johnkslang** [comment]
First, my apologies for accidentally getting unrelated functional code in what was supposed to be a non-functional change.  That's not how we intend to do things.

Now, let's see what should actually be happening. The specification also says:

> When applied to structure-type members, the Decorations Noperspective, **Flat**, Patch, Centroid, and Sample can only be applied to the top-level members of the structure type. (Nested objects' types cannot be structures whose members are decorated with these decorations.)

That is, **Flat** should not be inherited throughout a nested type.  It does not say it must be inherited to the top level.  (That would be needed for blocks, where they can be specified in GLSL per member, for example, but not required for a struct, where the whole struct gets decorated.)

(This was pointed out in the May 6 commit 8add151c4bed52798e21ae6c675652a30f76235e, which also evolved where **Flat** is applied.)

And, slightly updating the quote from above, what the latest spec (rev. 6) says about Flat is:

> **Flat**
>
> Apply to an object or a member of a structure type. Indicates no interpolation will be done. The non-interpolated value will come from a vertex, as described in the API specification. The object or member must be a scalar or vector of floating-point type or integer type. Arrays of these types are also allowed. Only valid for the Input and Output Storage Classes.

So, we have one rule saying it can only apply to top-level members, and another rule saying it can't apply to structure types.  Together, that implies that top-level members cannot be structures, meaning there cannot be nested structures in input and output.

However, structures are not disallowed as top-level members of blocks (which in SPIR-V have a structure type).  The only way to make something flat in the following case is to make the block-structure member be decorated as flat, as the rules are clearly saying don't go deeper than that:

```
struct S {  vec4 v; };
in inName {  flat S s; };  // SPIR-V says to make s Flat, and glslang does that
```

Given that structures should not be disallowed here, I suspect the rule saying **Flat** only applies to scalars/vectors is the overly restrictive one, especially given how clearly the other rule mentions not decorating members of nested structures (as opposed to saying "no structures").

Thus, **Flat** can apply to objects or block member types that are structures, and there is further not a requirement that **Flat** be pushed into the top-level members of a structure object, only that they can't be pushed further down than that.

Implementations have to implement their own inheritance, given these rules, so they should be able to handle an aggregate in general that is decorated as **Flat**.

I will open a specification bug about the contradiction between the different areas around implying structures can be flat, or cannot be.  I think it unlikely that flat-structure functionality would be removed, so suspect the contradiction will be resolved in terms of allow structure objects and block-members that are structures to be decorated as **Flat**.

**Comment by ChrisGautier** [comment]
Thanks @johnkslang for the detailed answer. I was unsure whether to open a glslang or a SPIR-V issue. I'm happy with discussing the topic further in KhronosGroup/SPIRV-Headers#17 and I will close this ticket.
