### ISSUE TITLE
Files with a UTF-8 BOM marker confuse the #version check

### ISSUE THREAD

**Issue by DeanoC** [KhronosGroup/glslang#425]
The #version check looks at the first byte of a file, if the file has a UTF-8 BOM marker this fails as # is not the first byte (it is the first character though...).

Whilst it may be that it shouldn't handle BOM files, would be nice to fire a warning at least as its largely a hidden error (most editors will hide the BOM so its correct to visual inspection)

**Comment by mknejp** [comment]
Seems like looking at the first byte of the file is incorrect anyways according to the spec:

> The #version directive must occur in a shader before anything else, except for comments and white space

**Comment by johnkslang** [comment]
> The #version check looks at the first byte

I don't think that is true:

 - The #version finder skips initial characters to find the first #version, it does not require # as the first byte.
 - The #version semantics checking enforces ES vs. desktop rules, which differ, but neither requires # in the first byte.

> if the file has a UTF-8 BOM marker this fails 

Isn't it correct to fail?

Note there is no formal specification of processing "a file", and that is absent in the programmatic (use through API) use of glslang.  It is just a convenience provided by the standalone command-line version that turns a file into a text string. Maybe you want to provide an enhancement to the standalone tool that processes BOM files the way you think is correct?

**Comment by DeanoC** [comment]
You're correct about the whitespace and comment (I just checked the code) but it doesn't skip the BOM markers. The consumeWhitespaceComment returns with the BOM lined up so the next get() returns the first BOM byte. This then fails the if(get() != '#') check, so the version declaration is skipped.

A warning (as its easy to detect) would help users, in the case where I detected it, it took a while to figure out. The text editors loaded the file correctly showing #version correct but glslang seems to get the wrong version. Yes in theory it should have been cleaned off by the loader before passing to glslang, but a warning (i.e. BOM marker detected in shader string) might be nice.

**Comment by johnkslang** [comment]
> it doesn't skip the BOM markers

Correct.  There is nothing in the spec about doing that, and the "inside" of glslang, where it's looking for # should not do that.

If you want a change, I see two choices:

1. change the standalone wrapper to strip these off before handing to through glslang's API

2. change the standalone wrapper to detect and warn

I don't immediately know how to do BOM detection or proper testing of it, so a PR would help.

**Comment by DeanoC** [comment]
Since 4.1 GLSL (section 3.1) is spec'ed to be UTF8, BOM handling is a part of that.

According to wikipedia "If the BOM character appears in the middle of a data stream, Unicode says it should be interpreted as a "zero-width non-breaking space" (inhibits line-breaking between word-glyphs)."

GLSL is spec'ed as 
"The #version directive must occur in a shader before anything else, except for comments and white space"

I guess its a matter of opinion whether a "zero-width non-breaking space" is technically a "white space" but I think its a reasonable assumption.

I'm happy to add the fix and PR but it doesn't belong in the standalone wrapper (I for example didn't discover the bugs with the standalone) imho. Its a property of UTF-8 that should be handled regardless of how the string was loaded etc.

**Comment by johnkslang** [comment]
Ah, I think I conflated "Byte Order Marker" with "Bill Of Materials."  So, this is what Wikipedia also describes as

> The Unicode Standard permits the BOM in UTF-8, but does not require or recommend its use. Byte order has no meaning in UTF-8, so its only use in UTF-8 is to signal at the start that the text stream is encoded in UTF-8.

Yes?

**Comment by DeanoC** [comment]
I've added a pull request https://github.com/KhronosGroup/glslang/pull/430 that solves this bug by removing all multibyte UTF8 character from the source strings. This means the BOM marker is removed as expected but doesn't make GLSLang in spec for shader version >= 4.1. For that the parser would need to become UTF8 aware, which is a much bigger issue and ideally done by someone who knows UTF8 well and the lexer/parser of GLSL to a good degree.
