### ISSUE TITLE
HLSL: discussion: matrix dereferencing order

### ISSUE THREAD

**Issue by steve-lunarg** [KhronosGroup/glslang#433]
I think master has an error for HLSL around the indirection order into matrices.  Several web sources such as [this one](https://anteru.net/) say, when considering a single matrix indirection m[0], _"In **HLSL, this will return the first row**, in GLSL, the first column. That also extends to the constructors, which initialize the members in the "natural" order."_   (Bolding mine).  Note that this holds true independent of layout qualifier.

Thus, given a float3x2 m, m[0] is a float**2**.  Current master returns a float3, causing valid code to fail to compile.  I have a partial fix as #432 for discussion.

The fix addresses the type issue above, and gets what I believe is the right answer when const folding indirections.  See Tests/hlsl.matrixindex.frag examples and resulting AST for illustration of this result.  However, I believe it would get the wrong answer in the non-const folded case.

SPIR-V defines the first EOpAccessChain index into a matrix to be a column vector, matching the OpTypeMatrix definition, and also GLSL.  Thus, PR #432 is incomplete: given a non-const-folded m[0], it will produce a column vector.  That is incorrect for HLSL.

This can be fixed by component shuffling when handling the dereference, but awkwardly.  Perhaps since most downstream compilers will perform component-level optimization, it doesn't matter much in the end?  Feels worth talking about though.

**Comment by johnkslang** [comment]
I think the alternative is to consider imagining HLSL matrices are transposed through the whole stack, which might make everything magically work as is.

E.g., starting with SPIR-V, instead of considering OpTypeMatrix to be a set of columns, it is instead a set of vectors, and you can by convention think of them as rows or as columns.

This will especially work if the "natural" semantic order for OpenGL is column-major and the natural semantic order for HLSL is row-major.

It takes time to think this all the way through, so will admit I haven't done that, but I think it is an alternative worth considering.

**Comment by steve-lunarg** [comment]
Hmm, interesting idea; I'll have to think it over.  For that to work out, at the least the current HLSL declarations would have to be reversed for non-square mats (lest the dereferenced types are wrong), although that's easy to do.  Also, at some point the rubber meets the layout-road; maybe something would have to reverse around qualifiers presented downstream so everything magically works out in the end.  If possible, it would be convenient.

> It takes time to think this all the way through

Indeed.

**Comment by johnkslang** [comment]
> at some point the rubber meets the layout-road

Outside the compiler stack.  The app might or might not already want to send the correct transposition, or have to transpose, and drivers might have flags for this.  E.g., in GLSL the row_major layout sets a bit that says transpose behind the scenes in memory, so that should exist already.

Note that `vector * matrix` can have operands reversed and get the correct result when swapping rows for columns.

**Comment by dankbaker** [comment]
By default, HLSL matrices exported to the app are column major.  However, it's changeable by using the row_major or column_major keyword, which IIRC only impacts global scoped parameters. 

This impacts the code generation, and might require some acrobatics if EOpAccessChain  can only do column access

As an example:
```
row_major float4x4 Mat;
uint index;

float4 main() : SV_POSITION
{
    return Mat[index];
}

```
Generates a very simple shader in D3D:
```
vs_4_0
dcl_constantbuffer CB0[5], dynamicIndexed
dcl_output_siv o0.xyzw, position
dcl_temps 1
mov r0.x, cb0[4].x
mov o0.xyzw, cb0[r0.x + 0].xyzw
ret
```

Where as the default column major does something very knarly 

```
float4x4 Mat;
uint index;

float4 main() : SV_POSITION
{
    return Mat[index];
}
```

which requires some acrobatics to make work:

```
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000} }
dcl_constantbuffer CB0[5], immediateIndexed
dcl_output_siv o0.xyzw, position
dcl_temps 1
mov r0.x, cb0[4].x
dp4 o0.x, cb0[0].xyzw, icb[r0.x + 0].xyzw
dp4 o0.y, cb0[1].xyzw, icb[r0.x + 0].xyzw
dp4 o0.z, cb0[2].xyzw, icb[r0.x + 0].xyzw
dp4 o0.w, cb0[3].xyzw, icb[r0.x + 0].xyzw
ret
```

If this a problem, can just not support it in the near term as it's very uncommon HLSL.

**Comment by steve-lunarg** [comment]
> By default, HLSL matrices exported to the app are column major. However, it's changeable by using the row_major or column_major keyword, which IIRC only impacts global scoped parameters.

It's my understanding that the first matrix dereference returns a row vector regardless of row_major or column_major layout qualifier, so it seems to me that the indirection issue exists regardless of layout.

I'm inclined to pursue @johnkslang's idea that the whole stack can operate as it does today for GLSL, essentially swapping rows and columns, so that the SPIR-V dereference returning a column vector will return what is really a row.  That would be modulo fixing current related defects in the HLSL FE, which for example get types wrong and cause compilation errors where there should be none.  I haven't yet convinced myself that there are zero necessary transpositions for this to all work out (even if implicit, e.g, by swapping a qualifier), but it certainly might be the case.  It would be convenient!

At a high level, it feels to me like: (1) there are current defects, and (2) maybe something fairly easy can happen to get everything correct, instead of something fairly hard.

**Comment by dankbaker** [comment]
I think inverting it is fine, D3D has always been inverted from GL.  Just understand that row_major really only impacts the uniforms.  

Here's some cases that show you the difference
```
float4x4 Mat1;

float4 test1() : SV_POSITION
{
    return Mat1[0];
}


row_major float4x4 Mat2;

float4 test2() : SV_POSITION
{
    return Mat2[0];
}


float4 ArrayMat[4];

float4 test3() : SV_POSITION
{
  column_major  float4x4 Mat = float4x4(ArrayMat[0],ArrayMat[1],ArrayMat[2],ArrayMat[3]);

   return Mat[0];
}

float4 test4() : SV_POSITION
{
   row_major float4x4 Mat = float4x4(ArrayMat[0],ArrayMat[1],ArrayMat[2],ArrayMat[3]);

   return Mat[0];
}
```

test1 and test2  produce different code, while test3 and test4 produce identical code. column_major  was really added so that the CPU could upload 3x4 matrices which take only 3 cycles and less data to do a bone transform vs row_major which ended up being a mad chain and would take 4 cycles. It's sort of a historical legacy thing, but plenty of code still does it that way.

**Comment by steve-lunarg** [comment]
I pushed a PR #485 to explore @johnkslang's idea above: "it is instead a set of vectors, and you can by convention think of them as rows or as columns."  This essentially aliases HLSL Mrc (natural order, not necessarily physical order) onto GLSL Mcr (again natural order, not necessarily layout, which can be set either way via qualifiers).  Some changes were needed to get there, since the HLSL path was internally inconsistent.

This accomplishes the following:

- Matrix dereference types are correct now, so type errors (properly) disappear when dereferencing non-square mats.
- We get the right answer for const-folded indirections into HLSL matrices. 
- I believe we would also get the right answer for non-const-folded indirections.
- However, the r/c distinction matters for V*M, M*V, and M*M cases.  If you alias Mrc onto Mcr, even if they are both (say) M23, downstream code currently expects the first dimension to be a column, semantically.  The branch currently switches the arg order (e.g, mul(a,b)->mul(b,a)) to avoid downstream errors in these cases, but this is in effect adding an implicit matrix transpose.  There's also an implicit transpose by the act of aliasing Mrc onto Mcr, so perhaps this works out, but I need to think about it more.

That's where the branch sits at the moment.

**Comment by tfoleyNV** [comment]
I just want to chime in to give a "+1" to the idea of inverting the notion of "row" and "column" for HLSL, including swaping the operands to M*M, M*v, and v*M. The result is far more consistent (basically, an NxM matrix is always a short array [N] of M-vectors), and you avoid making l-values that are even messier than swizzles already make them.

I've implemented a system that generated both HLSL and GLSL by using this pattern before, and it basically Just Works.

**Comment by steve-lunarg** [comment]
Cool, thanks @tfoleyNV.  What you describe including the mul order swap should be akin to what's in #485, so it's a valuable data point.  I'll move the branch foward to more recent code; it has aged off of master by quite a bit.

**Comment by steve-lunarg** [comment]
Updated as #505 (that was easier git-wise than keeping it under #485, which I have closed).

**Comment by steve-lunarg** [comment]
Closing issue as #505 is merged.  If there are issues that arise, they can be handle specifically.
