### ISSUE TITLE
HLSL: Getting lots of errors on InitializeSymbolTable parsing

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#438]
I'm getting a bunch of errors in yacc parsing with the initial symbol table buildups. It appears to be the Sampler types that are not parsing, though I don't know the grammar well enough to know why they aren't.  Related code would be in hlslParseables. is anyone else seeing this? I am building it in 64 bit mode.

**Comment by johnkslang** [comment]
A bigger thing going on here is what path HLSL intrinsics should take to get into the symbol table.  There are a few things pending there.  But, there are certainly lots of people building and using glslang, which includes the HLSL stuff, without error, and a few actually using the HLSL stuff successfully.

Any input on these topics @steve-lunarg?

**Comment by dankbaker** [comment]
I swear I didn't see this until I brought down latest code today. This is a segment of what I see when it's trying to build the HLSL symbol tables for intrinsics:

vec2 GetSamplePosition(texture2DMS, int);
vec2 GetSamplePosition(utexture2DMS, int);
vec2 GetSamplePosition(itexture2DMS, int);
vec2 GetSamplePosition(texture2DMSArray, int);
vec2 GetSamplePosition(utexture2DMSArray, int);
vec2 GetSamplePosition(itexture2DMSArray, int);

Unable to parse built-ins
ERROR: 0:874: '' :  syntax error
INTERNAL ERROR: Unable to parse built-ins
ERROR: 0:1: '' :  syntax error
INTERNAL ERROR: Unable to parse built-ins
ERROR: 0:292: '' :  syntax error
INTERNAL ERROR: Unable to parse built-ins
ERROR: 0:1: '' :  syntax error
INTERNAL ERROR: Unable to parse built-ins

vec2 GetSamplePosition(texture2DMS, int);
vec2 GetSamplePosition(utexture2DMS, int);
vec2 GetSamplePosition(itexture2DMS, int);
vec2 GetSamplePosition(texture2DMSArray, int);
vec2 GetSamplePosition(utexture2DMSArray, int);
vec2 GetSamplePosition(itexture2DMSArray, int);

**Comment by johnkslang** [comment]
Probably because you didn't request SPIR-V.  If you, for example, say -D but not -V, it does something like the above.  Right now (and this hinges on my comment of deciding the right path for HLSL intrinsics), you have to use the path HLSL -> SPIR-V.

(You can tell if what's supposed to work is working if the tests pass.)

**Comment by johnkslang** [comment]
Assuming this is no longer an issue.
