### ISSUE TITLE
<bad token> generated for <= operator

### ISSUE THREAD

**Issue by cgrant78** [KhronosGroup/glslang#440]
I'm seeing the case where running a shader through the preprocessor glslang::TShader::preprocess is generating <bad token> for the <= operator. I may be violating posting rules with the somewhat large snippet below, but here goes.

Source:
float3 CalculateSubPixelValue( in float3 current, in float3 previous, in float pixelShift )
{
	float r = current.r;
	float g = current.g;
	float b = current.b;
	CONST float oneThird = (1.0/3.0);
	CONST float twoThird = (2.0/3.0);
	
	if( pixelShift <= oneThird )
	{
		float z = 3.0 * pixelShift;
		
		r = mix( current.r, previous.b, z );
		g = mix( current.g, previous.r, z );
		b = mix( current.b, previous.g, z );		
	}
	else
	if( pixelShift <= twoThird )
	{
		float z = 3.0 * pixelShift-1.0;
		
		r = mix( previous.b, previous.g, z );
		g = mix( previous.r, previous.b, z );
		b = mix( previous.g, previous.r, z );	
	}
	else
	if( pixelShift < 1.0 )
	{
		float z = 3.0 * pixelShift-2.0;
		
		r = mix( previous.g, previous.r, z );
		g = mix( previous.b, previous.g, z );
		b = mix( previous.r, previous.b, z );		
	}
	
	return( float3( r, g, b ) );
}

Output ( preprocessed ):
     vec3 CalculateSubPixelValue(in vec3 current, in vec3 previous, in float pixelShift)
{
 float r = current . r;
 float g = current . g;
 float b = current . b;
     const float oneThird =(1.0 / 3.0);
     const float twoThird =(2.0 / 3.0);
 if(pixelShift <bad token> oneThird)
 {
  float z = 3.0 * pixelShift;
  r = mix(current . r, previous . b, z);
  g = mix(current . g, previous . r, z);
  b = mix(current . b, previous . g, z);
 }
 else
 if(pixelShift <bad token> twoThird)
 {
  float z = 3.0 * pixelShift - 1.0;
  r = mix(previous . b, previous . g, z);
  g = mix(previous . r, previous . b, z);
  b = mix(previous . g, previous . r, z);
 }
 else
 if(pixelShift < 1.0)
 {
  float z = 3.0 * pixelShift - 2.0;
  r = mix(previous . g, previous . r, z);
  g = mix(previous . b, previous . g, z);
  b = mix(previous . r, previous . b, z);
 }
 return(vec3(r, g, b));
}

float3, CONST are #define which were accurately substituted in the output. 

It seems like the bad tokens are not show up in the post, so I"m also going to attach the preprocessed output as a file.

[ex.txt](https://github.com/KhronosGroup/glslang/files/405038/ex.txt)

**Comment by johnkslang** [comment]
This was just (coincidentally) fixed Aug. 4th with 9f9bad09b4f2bb8dc3653643b3e0ff244b4358b5.  That being said, there is not yet a promise that all whitespace is being handled correctly by -E functionality (it is not part of the specification, validation, or compilation to SPIR-V).

Reopen if you already tried that commit and the issue is more subtle than that.
