### ISSUE TITLE
HLSL: Auto promotion of scalar types to vector does not work

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#441]
in HLSL, though I believe it may warn you now, you can do things like

float V = 1;
float3 MyVal = V;

Which is equivalent to,

float V = 1;
float3 MyVal = V.xxx;

Not super high priority, as we can fix those auto promotion cases in our code, but this fairly common thing to see in HLSL code (at least the scalar promotion type).

**Comment by johnkslang** [comment]
Auto-smearing scalar -> vector was recently added for assignment (maybe not initializers though? I'll check), and is now being added for <, <=, >, and >=.  Will close this when those are done.

**Comment by johnkslang** [comment]
Note this is also already captured in issue #362.

**Comment by johnkslang** [comment]
@dankbaker the sample

```
float V = 1;
float3 MyVal = V;
```

works for me, so not sure what you saw not working.

Commit 4583b61e205e7901f5be69f81ddb95ce8830be16 broadened this for relational comparisons, and includes your test.

Reopen with a test case that fails if you still see it.

**Comment by dankbaker** [comment]
Seems like latest drop fixed the issue, no longer repros for me.
