### ISSUE TITLE
Spurious error message when packing double into unused components of second location of dvec3.

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/glslang#443]
Compiling this (fragment) shader for Vulkan:

```
#version 450

layout(location=0) in flat dvec3 p;
layout(location=1, component=2) in flat double q;

layout(location=0) out vec4 x;

void main() {
	x = vec4(vec3(p), float(q));
}
```

produces the following error, but should work:
```
ERROR: 0:4: 'location' : overlapping use of location 1
ERROR: 1 compilation errors.  No code generated.
```

**Comment by johnkslang** [comment]
Found it in the spec: 

> A dvec3 will consume all four components of the first location and components 0 and 1 of
the second location. This leaves components 2 and 3 available for other component-qualified
declarations.

Will fix soon.
