### ISSUE TITLE
HLSL: Cannot have pixel shaders in same files as a vertex shaders

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#446]
It appears that sampler objects are filtered off during the creation of the symbol tables, this means if you have both a pixel shader and a vertex shader in the same file (which is ubiquitous in HLSL), it will not compile. The symbol tables should be created for all targets, and only failed during the actual compilation.

Here is a very simple shader:
 
```
SamplerState SS_DEFAULT       : register(s0);
Texture2D TestRTTexture : register(t17);

struct VSOut
{
    float4 fPos    : SV_POSITION;
	float2 fTex	   : TEXCOORD;
};

float4 DummyFuncion( VSOut Input ) : SV_TARGET0
{
	float4 RenderColor = TestRTTexture.Sample(SS_DEFAULT, float2(0.1, 0.2));//Input.fTex);
	
	return RenderColor;
}

float4 main() : SV_POSITION
{
	return 0;
}
```

The presence of DummyFuncion when main is attempted to compile will cause parsing to fail. Going to look into it some more, but it might be faster for someone else. The issue might be inside the intermediate part for GLSL.

**Comment by johnkslang** [comment]
It will be easier if you follow the basic markdown language GitHub is using. Check out https://guides.github.com/features/mastering-markdown/

Probably the minimum needed is to escape your code so that it is not randomly driving markdown features.  E.g.:

\`\`\`
if (a < b)
    c = d; // indented in what I actually typed in
\`\`\`

Will come out as 

```
if (a < b)
    c = d; // indented in what I actually typed in
```

I don't know about files, but the semantic's checker is definitely in only one stage-mode at a time, as the rules are stage-dependent, so string parsing is also tied to a parse context that first selects the stage, which also sets up the right symbols for that stage.  There is certainly the choice though on whether to enter a symbol as being stage dependent or useful for all stages.

**Comment by dankbaker** [comment]
I'll take a look, as a rule for HLSL, all things should parse if it's ever valid for any target. Validation should occur only at compilation time.


Ok, I updated the formatting.

Intrsinics are an area that is definitely implemented far differently. HLSL did not do name mangling like GLSL, instead the intrinsics were stored in more of a table similar to the source table format created - with a precedent order for matching. Parsing in HLSL is only profile specific when it compiles either .fx files or back compat, otherwise it the grammar is identical.

I'll mess around with changing when the functions added to the symbol tables, maybe I can fix it relatively easily. There's no work around for this for us.

**Comment by johnkslang** [comment]
The grammar is also identical for GLSL and glslang in general.  It is semantic checking that is per-stage, hence the need to know a specific stage. Function-calling syntax is a postfix-grammar rule, whose precedence is fixed by the syntax. I need to understand the issue deeper to give better advice though.

**Comment by dankbaker** [comment]
I believe the issue is that at parse time it is attempting to resolve a built-in function that doesn't exist on the target that's being compiled. But that's fine in HLSL so long as that function isn't refernced, and in fact will happen all the time with pixel and vertex shaders existing in same file. Need to double check the symbol tables for intrinsics, but I believe they have a shader stage, that prob needs to be set to ALL for every intrinsic and only fail further down the stream if said intrinsic doesn't exist for target.

**Comment by dankbaker** [comment]
Indeed, there is a stage mask in TBuiltInParseablesHlsl::initialize. That' can't be there, otherwise things won't parse. Going to try to remove it.

**Comment by johnkslang** [comment]
> I'll take a look, as a rule for HLSL, all things should parse if it's ever valid for any target. Validation should occur only at compilation time.

Not sure when compilation time is. This HLSL -> SPIR-V translator roughly has the following logical stages:

1. tokenize for PP
2. tokenize for HLL
3. grammar acceptance
4. AST building and semantic checking (mostly so the AST is valid)
5. AST -> SPIR-V translator

I suspect some higher-level design decision is needed as to how to handle multiple stages in the same compilation unit.

**Comment by dankbaker** [comment]
When I say compilation time, I mean after the AST is built (e.g. stage 5). I think this structure of validation is probably due to the origins of this being a validator program, rather then more of a compiler. In the HLSL compiler, target specific validation never really occurred on the AST itself, it occurred during the rough equiv of stage 5.

I don't really see any way around this. Either step 5 needs to be modified to do validation and semantic checking, or there needs to be a new step which does the semantic checking but which ignores dead parts of the AST.  I don't believe validating the AST against target specific features while it;s being built will be possible.

**Comment by johnkslang** [comment]
I think everything will be fine, we just have sort through it.  Here's some useful points:

- This project actually does not have HLSL validation as a goal, it assumes getting valid HLSL in.
- We are indeed weakening what needs to be checked while building the AST, to be much more liberal.
- SPIR-V itself also allows multiple stages within the same compilation unit, much like what you want from HLSL.
- The grammar and the fundamental checking that must be done to build a valid AST are in fact independent of stage.

So, I think the puzzle entirely is solvable.  I suspect there are two needs here:

1. Stop doing stage-specific semantic checking for HLSL, which would include having the union of all intrinsics available while building the AST.

2. High-level mechanics for managing multiple entry points within a single compilation unit.

**Comment by dankbaker** [comment]
Sure, I will mess around with enabling all the intrinsics tomorrow. I'm getting close to getting my diagnostic shader through.

**Comment by dankbaker** [comment]
I removed the stage check and indeed, it gets through. I will submit a PR once my last PR goes through.

**Comment by johnkslang** [comment]
This is settled now, as all intrinsics are accepted, we have a clear single entry point that is declared, as well as a declared stage, so some stage specific choices actually make sense.  But, shaders should no longer be rejected for containing an intrinsic call for a different stage than the declared stage.
