### ISSUE TITLE
HLSL: Misc casting issues regarding scalar/vectors

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#453]
Super set of issue #442, collecting to make a more general case. All of these produce identicle code in HLSL, but some fail in glslang front end.

Here is a reference case that works:

```
uint uBufferValue;
uint uBufferIndex;
Buffer<uint> TestUAVBuffer;

float4 main(  ) : SV_POSITION
{
    if(TestUAVBuffer.Load(uBufferIndex.x).x == uBufferValue)
         return float4(1,0,1,1);
    else
        return float4(0,0,1,1);
}
```

This one fails to compile, but is valid
```
uint1 uBufferValue;
uint uBufferIndex;
Buffer<uint> TestUAVBuffer;

float4 main(  ) : SV_POSITION
{
    if(TestUAVBuffer.Load(uBufferIndex.x).x == uBufferValue)
         return float4(1,0,1,1);
    else
        return float4(0,0,1,1);
}
```
This one also fails to compile, but is valid
```
uint1 uBufferValue;
uint uBufferIndex;
Buffer<uint1> TestUAVBuffer;

float4 main(  ) : SV_POSITION
{
    if(TestUAVBuffer.Load(uBufferIndex.x).x == uBufferValue)
         return float4(1,0,1,1);
    else
        return float4(0,0,1,1);
}
```

But this one compiles and is valid

```
uint uBufferValue;
uint uBufferIndex;
Buffer<uint1> TestUAVBuffer;

float4 main(  ) : SV_POSITION
{
    if(TestUAVBuffer.Load(uBufferIndex.x).x == uBufferValue)
         return float4(1,0,1,1);
    else
        return float4(0,0,1,1);
}
```

Which is sort of strange since it appears that binary expressions can sometimes be mismatched in terms of scalar/vector, but not other times. Maybe the return type is assumed to always be a scalar if 1D?

**Comment by johnkslang** [comment]
It is true that the conversions between scalars, vectors of size 1, and other vectors are not yet correctly or fully implemented.

(When we say something fails, I'm not always following what's supposed to happen where. E.g., it will help to identify things like "passing in glslang but shouldn't be according to XXX", "failing, as it should", "failing in glslang but expected to work by XXX", etc.  Thanks!)

**Comment by dankbaker** [comment]
yeah, we need a proper shorthand for GLSLang HLSL vs FXC reference HLSL.  Otherwise it gets confusing. Sicne it's Vulkan, Maybe VHLSL?

**Comment by johnkslang** [comment]
I regret naming any of this HLSL, because it is a new thing that happens to be more compatible with multiple other languages than is GLSL, and using a recursive decent parser than allows adaptation to a mixture of languages, whereas the GLSL parser is very hard-nosed about GLSL semantics because it serves as a validator for Khronos.

It's really a playground for SPIR-V generation of a whole family of high-level languages.  So, HLSL stands for "High Level SPIR-V Lab".  Note it is parameterized by a source-language enumerant.

For immediate projects at hand, let's just identify what is needed versus what is happening, and the word "fail" by itself is ambiguous.  Lots of stuff is supposed to fail.

**Comment by dankbaker** [comment]
It's not to late to name it.  I agree, it shouldn't be called HLSL. Perhaps SVSL for Spir-V Shading Language? It will also help reenforce that it's not going to be 100% identical to HLSL.

**Comment by dankbaker** [comment]
Here's a simple little test that causes an assert in the SPRIV translator. Just posting it here to add to any unit test. Code can be fixed by changing UnitValue to scalar.

```
float1 UnitValue;
float4 Val1;

float4 main( uint VertexID : SV_VertexID ) : SV_POSITION
{ 
     float4 vPos = Val1 + UnitValue.xxxx;
      
     return vPos;
}
```

**Comment by johnkslang** [comment]
These examples all work now.
