### ISSUE TITLE
HLSL: Proposal, add layout syntax for variables as equivalant to a register postexpression

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#454]
The problem is that HLSL actually lacks the binding information to specify where something goes in the language for D3D12 style descriptor sets. You end up binding to a register ala D3D11 style and then providing a remap table, which is sort of awkward. By making it a post expression similar to the register keyword, it's easy to make code that can compile on both SVSL and HLSL

```
#ifdef D3D
#define layout(a,b) dummy
#endif

float  ZDepth : register(c3) : layout(set=1,binding=2);
float4 Val1;

float4 main( uint VertexID : SV_VertexID ) : SV_POSITION
{ 
     float4 vPos = Val1 + ZDepth.xxxx;
      
     return vPos;
}
```

In D3D12, when you create the pipeline you'd end up having a table that says C3->set1,binding3. 

The HLSL will ignore semantics it doesn't recognize without errors or warnings so this code can be perfectly valid so long as there is a precedent in SVSL about which one to apply (I'd say that last one in the list).

In fact, could just ignore the register keyword altogether and make people bind it the GL/Vulkan way.

**Comment by StarsX** [comment]
I don't think it is that necessary. It seems that in HLSL Shader Model 5.1 (DX12), we have to declare the register as register(b#, space#), and thus b# and space# should be mapped to the binding and set respectively. For DX11 style register(b#), it may be regarded as set=0 implicitly.

**Comment by johnkslang** [comment]
Both ideas are now supported: layout() can be a postdecl, and spaceN is accepted as Vulkan descriptor set.
