### ISSUE TITLE
Texture information overloads missing for KHR_vulkan_glsl texture handles.

### ISSUE THREAD

**Issue by Duttenheim** [KhronosGroup/glslang#469]
The functions textureSize and textureQueryLevels doesn't seem to be implemented for the KHR_vulkan_glsl texture types without a combined sampler, i.e. texture2D, textureCube, etc. The KHR_vulkan_glsl doesn't mention how this is to be expressed.

Trying to directly pass for example a texture2D to textureSize or textureQueryLevels, like so:

```
uniform texture2D Texture;
uniform sampler Sampler;
...
ivec2 size = textureSize(Texture, 0);
```

Results in:
`
Assertion failed: node->getOp(), file glslang\spirv\glslangtospv.cpp, line 1256.
`

Working around the problem is possible, trying to construct a sampler like this works fine:

```
uniform texture2D Texture;
uniform sampler Sampler;
...
ivec2 size = textureSize(sampler2D(Texture, Sampler), 0);
```

However constructing a sampler2D and passing it like this:

```
uniform texture2D Texture;
uniform sampler Sampler;
...
const sampler2D samp = sampler2D(Texture, Sampler);
vec2 size = textureSize(samp, 0);
```

Also results in: 
`
Assertion failed: node->getOp(), file glslang\spirv\glslangtospv.cpp, line 1256.
`

Because of this, there is no way to pass a constructed sampler down to a function. And I wouldn't expect it to be valid either, since the KHR_vulkan_glsl states: 

'Constructors can then be used to combine a sampler and a texture at the point of making a texture lookup call: texture2D(sampler2D(t, s), ...);'

However since there is currently no way to get the texture size or query the number of mips, they must be supplied through uniforms, rendering the textureSize and textureQueryLevels functions broken for the sampler free texture handles.

**Comment by arcady-lunarg** [comment]
Support for this feature has since been added in e47bfaedf6a01ceb96c706efb6838987b4406874 and the functions in question should work now. Closing the issue.
