### ISSUE TITLE
Change "glslangValidator" -> "glslang"

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#47]
glslangValidator is becoming a SPIR-V front end, as well as a validator.  Khronos decided it should be name just "glslang".  So this change in the built executable name will likely occur at some point.

Are there any concerns about doing this?

**Comment by xorgy** [comment]
I'd say that the binary name counts as part of the API, and changing its name is a breaking change.
If we're doing semantic versioning, this means that the major revision ought to change.

**Comment by johnkslang** [comment]
Interesting point.  Note that the glslang libraries do indeed have an API for creating/compiling/linking/etc. shaders, and as functionality has been added, we've been careful to not break it.  Roughly, the original 3Dlabs (deprecated now) C-functional API was version 1.x, and the new C++-object API is version 2.x, and this will stay backward compatible through the binary name change.  I would not consider the name of the binary to be part of the API, though I do recognize changing it would break tools.

**Comment by ioquatix** [comment]
I think this is a good idea. Not only is `glslangValidator` a long name for a command, it also no longer accurately reflects what the command does.

Rather than just hastily changing it's name, perhaps a full review of how the command works, including help output would be worth reviewing.

**Comment by ioquatix** [comment]
It's been 4 years since this issue was first raised, has there been any update?

**Comment by xorgy** [comment]
I suspect packagers would just include a symlink anyway, seems low risk, but come to think of it who really cares what the binary is called?

**Comment by ncesario-lunarg** [comment]
Would installing a symlink (`glslangValidator` -> `glslang` or vice-versa) be acceptable here? If not, and "nobody really cares" as @xorgy says, then I propose closing this issue.

**Comment by ioquatix** [comment]
I don't think "nobody cares" - it's probably more an issue of "it's good for developer UX". A symlink for compatibility seems reasonable to me.
