### ISSUE TITLE
Clip Distance always added as member decoration even if not used?

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#472]
My test GLSL shader
```
#version 450

layout(set=0,binding=0) buffer Dynamics
{    
     layout(offset=0)  vec4 s_Color;
     layout(offset=16) vec4 s_Color2;
     layout(offset=32) vec2 Scale;
     layout(offset=40) vec2 Offset;
     layout(offset=48) float ZDepth;
} DynamicsI;

layout(set=1,binding=0) uniform samplerBuffer V_Position;
layout(set=1,binding=1) uniform samplerBuffer V_TexCoord;

out vec2 Tex;

void main() 
{
    vec4 Pos = texelFetch (V_Position, gl_VertexIndex );
    Pos.xy = Pos.xy * DynamicsI.Scale + DynamicsI.Offset;
 
    Tex = texelFetch (V_TexCoord, gl_VertexIndex ).xy;
    gl_Position = Pos;
}

```
Will fail creation, with this message:

SC (ERROR): object: 0x0 type: 0 location: 8648 msgCode: 5: SPIR-V module not valid: Operand 4 of MemberDecorate requires one of these capabilities: ClipDistance 

Looking through the SPRIV, I see:
```
    MemberDecorate 47(gl_PerVertex) 0 BuiltIn Position
    MemberDecorate 47(gl_PerVertex) 1 BuiltIn PointSize
    MemberDecorate 47(gl_PerVertex) 2 BuiltIn ClipDistance
    MemberDecorate 47(gl_PerVertex) 3 BuiltIn CullDistance
```

Which appears to be because of 
```
    // version >= 150
            stageBuiltins[EShLangVertex].append(
                "out gl_PerVertex {"
                    "vec4 gl_Position;"     // needs qualifier fixed later
                    "float gl_PointSize;"   // needs qualifier fixed later
                    "float gl_ClipDistance[];"
                    );         
```

code in Initialize.cpp.  I guess I'm not understanding what's going on here. It looks like this feature isn't supported by the device I am trying to create on (and AMD desktop card), but I'm not actually using the decoration, SPIRV is just outputting over generalized information. Is that what's going on? What's supposed to happen for optional features like this, are there profiles?

**Comment by johnkslang** [comment]
We had a big discussion about this internally to Khronos a while back and the decision was that it is okay to decorate with ClipDistance (and similar), but it's the actual reading and writing that needs the capability.  Unless you read or wrote to clip distance, you are not really using the hardware feature, and the hardware capability is not in use, so the capability does not need to be declared, and the consumer should not care.  The reasons are somewhat complex, but have to do with cross-stage linking and some other things.

**Comment by dankbaker** [comment]
That's fine, but the debug validation layer is failing me because of it which is super annoying. Can we get the validation removed for this? e.g. the decoration doesn't fail validation just if it's used?

**Comment by ratchetfreak** [comment]
if you want things to get moving on validation then you can add an issue to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/ (the repo with the actual validation)

**Comment by johnkslang** [comment]
This should be fixed now, via https://github.com/KhronosGroup/SPIRV-Tools/issues/365.
