### ISSUE TITLE
HLSL: output semantic handling for vertex shader

### ISSUE THREAD

**Issue by StarsX** [KhronosGroup/glslang#475]
Hi,
I find currently there seems no valid SPIR-V code could be generated, which could be really run to replace the glsl shader. I tried to modify some codes on semantics:

	void HlslParseContext::handleSemantic(TType& type, TString& semantic)
	{
	    // TODO: need to know if it's an input or an output
	    // The following sketches what needs to be done, but can't be right
	   // without taking into account stage and input/output.
		std::transform(semantic.begin(), semantic.end(), semantic.begin(), ::toupper);
	
		if (semantic == "PSIZE")
			type.getQualifier().builtIn = EbvPointSize;
		else if (semantic == "SV_POSITION" && language != EShLangFragment)
			type.getQualifier().builtIn = EbvPosition;
		else if (semantic == "POSITION")
			type.getQualifier().builtIn = EbvPosition;
		else if (semantic == "FOG")
			type.getQualifier().builtIn = EbvFogFragCoord;
		else if (semantic == "DEPTH" || semantic == "SV_DEPTH")
			type.getQualifier().builtIn = EbvFragDepth;
		else if (semantic == "VFACE" || semantic == "SV_ISFRONTFACE")
			type.getQualifier().builtIn = EbvFace;
		else if (semantic == "VPOS" || semantic == "SV_POSITION")
			type.getQualifier().builtIn = EbvFragCoord;
		else if (semantic == "SV_CLIPDISTANCE")
			type.getQualifier().builtIn = EbvClipDistance;
		else if (semantic == "SV_CULLDISTANCE")
			type.getQualifier().builtIn = EbvCullDistance;
		else if (semantic == "SV_VERTEXID")
			type.getQualifier().builtIn = EbvVertexId;
		else if (semantic == "SV_VIEWPORTARRAYINDEX")
			type.getQualifier().builtIn = EbvViewportIndex;
		else
		{
			unsigned int location;
			int suc = sscanf(semantic.c_str(), "LOCATION%u", &location);
			if (suc)
			{
				type.getQualifier().layoutLocation = location;
				type.getQualifier().smooth = true;
			}
		}
	}

and

    if (inEntrypoint) {
        // parameters are actually shader-level inputs
		for (int i = 0; i < function.getParamCount(); i++)
		{
			if (function[i].type->getQualifier().isParamOutput())
				function[i].type->getQualifier().storage = EvqVaryingOut;
			else
				function[i].type->getQualifier().storage = EvqVaryingIn;
		}
    }

in TIntermAggregate* HlslParseContext::handleFunctionDefinition(const TSourceLoc& loc, TFunction& function).

My simple DX12 style HLSL vertex shader with output parameter can be compiled and run successfully to replace a full glsl shader:
`
	void main(uint vid : SV_VertexID,
		out float4 Pos : SV_Position,
		out float2 Tex : location0) 
	{
		Tex = 2.0 * float2(vid >> 1, vid & 1);
		Pos = float4(Tex * 2.0 - 1.0, 0.5, 1.0);
	}
`

Therefore, I suggest to fix the related code like what I've mentioned above. Since I'm not quite familiar with compilers, I'm afraid I cannot directly help to improve the project, but I'm very familiar with HLSL. Hence, this is only a little suggestion, hoping it will be useful.

**Comment by johnkslang** [comment]
Thanks.  @dankbaker had mentioned completing this function, any update or decision Dan?  Thanks.

**Comment by dankbaker** [comment]
Sure, I'll do a first pass on it.

-D

**Comment by johnkslang** [comment]
This looks useful too, curious if you'd agree:

https://anteru.net/blog/2016/mapping-between-hlsl-and-glsl/

**Comment by StarsX** [comment]
Yes, I think it is a good summary. Anyway, SV_Position is the most important semantic.
Besides, [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509647(v=vs.85).aspx) says:
_In general, data passed between pipeline stages is completely generic and is not uniquely interpreted by the system; arbitrary semantics are allowed which have no special meaning. Parameters (in Direct3D 10 and later) which contain these special semantics are referred to as System-Value Semantics._

So I think handleSemantic() only needs to handle the SV semantics, while other semantics can be omitted here first. In terms of the other semantics for pipeline stage passing, since they are allowed to be arbitrarily named by users, they may be handled here using two counters to record the order for determining the layout location, something like this (only for reference):
```
	if (inEntrypoint) {
		// parameters are actually shader-level inputs
		unsigned int inCount = 0, outCount = 0;
		for (int i = 0; i < function.getParamCount(); i++)
		{
			if (function[i].type->getQualifier().isParamOutput())
			{
				if (function[i].type->getQualifier().builtIn == EbvNone)
					function[i].type->getQualifier().layoutLocation = outCount++;
				function[i].type->getQualifier().storage = EvqVaryingOut;
			}
			else
			{
				if (function[i].type->getQualifier().builtIn == EbvNone)
					function[i].type->getQualifier().layoutLocation = inCount++;
				function[i].type->getQualifier().storage = EvqVaryingIn;
			}
		}
	}
```
in handleFunctionDefinition(). Besides, for example, void main (..., ..., out ...., uniform ...), the uniform arguments cannot be counted into varying I/O either, but here I don't know how to represent them.

Additionally, semantics in HLSL are case insensitive, as I remembered.

**Comment by dankbaker** [comment]
SV_ semantics are case insensitive. The only thing that's not in that chart is the fact that in some cases there are multiple fields, e.g. SV_Target is equiv to SV_Target0, and I beleive SV_Target2, for example, would be "layout(location=2) out" in GLSL. 

In DX10+, semantics have no meaning other then the SV_ ones.They are only used for validation between a stages, e.g.as a verification that the value in a specific slot matches what the shader stage thinks the previous stage put there. They can be safely ignored. You' have to make a compat mode for DX9 semantics, but I don't think it's worth worrying about DX9 at this point.

Also, there is no SV_GroupIndex looks like, which would be: SV_GroupIndex = SV_GroupThreadID.z*dimx*dimy + 
                      SV_GroupThreadID.y*dimx + 
                      SV_GroupThreadID.x;

where dimx and dimy are the threadgroupsize.

I can take a crack at it, but my problem is not being familiar enough with the GL equivalent of the values.

**Comment by StarsX** [comment]
SV_TARGET0~SV_TARGETN do not determine the built-in property, but determine the layout location instead.
As I did an experiment on how the non-SV semantics are matched between VS and PS:
![vs](https://cloud.githubusercontent.com/assets/11565995/17828484/a17ee63a-66c5-11e6-9e3b-5771262ae3f7.png)
![vs_asm](https://cloud.githubusercontent.com/assets/11565995/17828483/a162fe34-66c5-11e6-97b7-ed001cad5ae4.png)
![ps](https://cloud.githubusercontent.com/assets/11565995/17828485/aafdda4a-66c5-11e6-966a-e053e2b7528d.png)
![ps_asm](https://cloud.githubusercontent.com/assets/11565995/17828486/ab3d0742-66c5-11e6-89d7-e21806a0d1be.png)
 I find the official HLSL compiler is not able to do the matching at all, though [MSDN](https://msdn.microsoft.com/windows/uwp/gaming/glsl-to-hlsl-reference) says the semantics must be matched. It seems that the register number (layout location) is just determined by the declaration order.

**Comment by StarsX** [comment]
![ps_svpos](https://cloud.githubusercontent.com/assets/11565995/17828540/2dbbb9ce-66c7-11e6-8941-434cfd52d928.png)
![ps_svpos_asm](https://cloud.githubusercontent.com/assets/11565995/17828541/2ddddd9c-66c7-11e6-8490-e49af77f9536.png)
The official MS HLSL compiler even does not match SV_POSITION for its register assignment. Thus, I conclude that the declaration order is the only key to determined the register number, rather than the semantics. The declaration order in HLSL must be consistent on VS and PS.

**Comment by dankbaker** [comment]
In DX10, only the binding order matters, otherwise semantics are just for validation which can't be done at compile time since the shader stage pairing isn't known. SV_ named vars never get routed to general outputs from a shader stage, since they are System Values.

In DX9, non SV names have register assignment associated with them, e.g. TEXCOORD0-8 and COLOR0-1 IIRC.
