### ISSUE TITLE
What is current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [KhronosGroup/glslang#478]
It's not clear to me how the version numbering of this software works just by inspecting the tags. The current Homebrew formula is building from the 3.0 tag (https://github.com/KhronosGroup/glslang/archive/3.0.tar.gz). See

https://github.com/Homebrew/homebrew-core/blob/8722e3126fb784d14a91eaa79b1161d6af984077/Formula/glslang.rb#L4

Is that the current stable version? If not, what tag and revision is considered the current stable version and what is the appropriate version number? More generally, how can we track this information so that the formula can be updated correctly?

Thanks!

**Comment by johnkslang** [comment]
Master is kept stable.  Tags are introduced for larger changes to semantics that might impact someone, but the code base is still stable.  Semantic changes are made in a well-defined specified way, like having #version 400 shaders use the correct #version 400 overloaded function selection rules under implicit conversion.

I recommend periodically updating to the most recent and verifying it works in your tool chain, independent of tags.

**Comment by ilovezfs** [comment]
Unfortunately in Homebrew, we basically live and die by tags because that's how the package manager knows whether or not to upgrade someone's local installation with a new prebuilt binary or if the person's local installation is already up to date. Also, we don't like to "invent" version numbers that don't actually exist in upstream because that's not really our place.

Would you be willing to create new tags with monotonically increasing version numbers when you feel there are sufficient changes to warrant pushing out an upgrade to your user base? That's all that's actually needed for us to upgrade the formula since GitHub automatically makes a tarball download available for each tag. That allows us to ensure security as well by verifying the tarball's checksum.

**Comment by johnkslang** [comment]
Yes, we can consider something like this.  I'm going to merge this with issue #452.

**Comment by ilovezfs** [comment]
thanks!
