### ISSUE TITLE
New GLSL warnings with VS 2015

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/glslang#486]
C:\dev\vulkan\VulkanSamples\external\glslang\StandAlone\ResourceLimits.cpp(244): warning C4996: 'strtok': This function
 or variable may be unsafe. Consider using strtok_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See o
nline help for details. [C:\dev\vulkan\VulkanSamples\external\glslang\build\StandAlone\glslang-default-resource-limits.
vcxproj]
C:\dev\vulkan\VulkanSamples\external\glslang\StandAlone\ResourceLimits.cpp(246): warning C4996: 'strtok': This function
 or variable may be unsafe. Consider using strtok_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See o
nline help for details. [C:\dev\vulkan\VulkanSamples\external\glslang\build\StandAlone\glslang-default-resource-limits.
vcxproj]
C:\dev\vulkan\VulkanSamples\external\glslang\StandAlone\ResourceLimits.cpp(441): warning C4996: 'strtok': This function
 or variable may be unsafe. Consider using strtok_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See o
nline help for details. [C:\dev\vulkan\VulkanSamples\external\glslang\build\StandAlone\glslang-default-resource-limits.
vcxproj]

**Comment by johnkslang** [comment]
@antiagainst Any input on this?

**Comment by antiagainst** [comment]
I've uploaded PR #488 for this.

Although `strtok_s` is suggested by MSVC, it has different signatures than the C11 one as commented on #488.
