### ISSUE TITLE
GLSL include extension and SPIR-V?

### ISSUE THREAD

**Issue by acterhd** [KhronosGroup/glslang#497]
Hello. How will working GLSL include extension with SPIR-V?

**Comment by johnkslang** [comment]
Can you give an example of what you are looking for? Thanks.

**Comment by acterhd** [comment]
I have no examples, but have https://www.opengl.org/registry/specs/ARB/shading_language_include.txt

**Comment by johnkslang** [comment]
glslang can be expanded to include functionality for extensions.  Read `../glslang/MachineIndependent/Versions.*` for examples.

If they translate to existing SPIR-V, then this is just a glslang change.  If SPIR-V needs to be extended, then first a SPIR-V extension needs to be written.

**Comment by acterhd** [comment]
Will support of bindless textures?
