### ISSUE TITLE
HLSL: hlsl.sample.basic.dx10.frag failing?

### ISSUE THREAD

**Issue by tfoleyNV** [KhronosGroup/glslang#504]
The tracking issue for HLSL parsing seems to imply that HLSL method calls for texture sampling are implemented, but I just checked out the top-of-tree master branch, builtin glslangValidator with CMake (VS2013, Debug, x64) and then ran:

    glslangValidator.exe -D .\Test\hlsl.sample.basic.dx10.frag

and I get a bunch of errors:

```
.\Test\hlsl.sample.basic.dx10.frag
WARNING: 0:4: 'immediate sampler state' : unimplemented
ERROR: 0:70: 'Sample' : no matching overloaded function found
ERROR: 0:71: 'Sample' : no matching overloaded function found
ERROR: 0:72: 'Sample' : no matching overloaded function found
ERROR: 0:74: 'Sample' : no matching overloaded function found
ERROR: 0:75: 'Sample' : no matching overloaded function found
ERROR: 0:76: 'Sample' : no matching overloaded function found
ERROR: 0:78: 'Sample' : no matching overloaded function found
ERROR: 0:79: 'Sample' : no matching overloaded function found
ERROR: 0:80: 'Sample' : no matching overloaded function found
ERROR: 0:82: 'Sample' : no matching overloaded function found
ERROR: 0:83: 'Sample' : no matching overloaded function found
ERROR: 0:84: 'Sample' : no matching overloaded function found
ERROR: 12 compilation errors.  No code generated.
```

When I single-step through the call to `symbolTable.findFunctionNameList` in `HlslParseContext::findFunction`, I never see a case where a level of the symbol table contains an entry for `"Sample"`.

(Also: isn't it a bit odd for this lookup to walk the symbol table for the lexical scope of the call site, rather than a symbol table associated with the type on which the method is being called?)

**Comment by johnkslang** [comment]
@steve-lunarg: can you reply to this one?

**Comment by steve-lunarg** [comment]
For a reason I'm not sure about off hand but will investigate, you need to supply a SPIR-V generation option, such as -V or -H.  Doing that yields this output, where the warning is expected:

```
./install/bin/glslangValidator -V -D ../Test/hlsl.sample.basic.dx10.frag

WARNING: ../Test/hlsl.sample.basic.dx10.frag:4: 'immediate sampler state' : unimplemented 

```

**Comment by tfoleyNV** [comment]
Great. That workaround should be enough for me right now.

My actual use case is driving glslang through the API, so I'll need to see what the `-V` option actually turns into, but that should be easy enough.

**Comment by johnkslang** [comment]
The point is to request SPIR-V generation for Vulkan, as HLSL only works correctly when doing that.  In the API, it is `EShMsgSpvRules | EShMsgVulkanRules`.

**Comment by johnkslang** [comment]
Another note, as the previous post must seem odd, is that GLSL also has different semantics/rules based on whether it is targeting SPIR-V and also whether it is targeting Vulkan or OpenGL, as each modifies the source language itself to support the slightly different features allowed.  For HLSL, the only flavor we're even trying to support right now is SPIR-V for Vulkan.

**Comment by tfoleyNV** [comment]
Yes, that makes sense. It might be a nice small fix to have the the HLSL option imply the SPIR-V and Vulkan ones, then (either as part of options parsing, or at the level of the `EShMsg*` flags).

But that would be a different issue, so I'm closing this one.

**Comment by johnkslang** [comment]
> It might be a nice small fix to have the the HLSL option imply the SPIR-V and Vulkan ones

These paths could be made to work in the future.

For now, I just added (d4032293cebd730be66a4324118a0b4ba88b9fb7) an error message if SPIR-V and Vulkan weren't requested.
