### ISSUE TITLE
TShader::parse() can return true after a HLSL parsing failure

### ISSUE THREAD

**Issue by jshofmann** [KhronosGroup/glslang#510]
I've been trying to use glslang to compile our HLSL code base into SPIR-V but have run into a problem where it's failing to parse the HLSL, printing a report of that failure to stdout, but TShader::parse() then returns true. I tracked the problem down to glslang/HLSL/glslParseHelper.cpp line 127 (13 September 2016 version of the source on github) where if HlslGrammar::parse() returns false it will printf() the error report but not increment numErrors or assign that error report to TShader's info log. Is this behavior by design? How can I detect and report this error to my tool's error management system? Thanks!

**Comment by johnkslang** [comment]
I added a return false here.  This was added by requested of @dankbaker.  Dan, does this not work if it goes through the info log; i.e., it has to be printf() to do what you are after? If it can go through the standard `error(...)` mechanism, that would be cleaner.

**Comment by dankbaker** [comment]
I had it use printf because everywhere else was using printf, though I think the correct thing to do is to use stderr instead. I would have done that except for the fact none of the other error messages were using stderr.

**Comment by johnkslang** [comment]
I see.

Everything else (~900 places) use the infoLog, except some command line stuff and internal errors, but this is from the parser, not the standalone tool.

I take a go at fixing it, and then we can iterate/converge if necessary, but multiple folks are losing this important message.

**Comment by dankbaker** [comment]
The previous message there that this one replaced was also a printf, so I didn't change it to do something different, the only change I made was to provide more information about what it was saying. IIRC, the old one just said "HLSL translation failed." with no info about where, but it was also a printf.

**Comment by johnkslang** [comment]
Okay, I understand, thanks.

The bigger issue is all the 900 others use the normal glslang form of reporting an error, so I feel somewhat stuck between making this one match those, versus the others to match this form and possibly breaking existing tools that know how to parse the ones glslang has always used.

I'll stick with the hybrid compromise for now, and close this, as it's targeted at the disappearance of the error.

**Comment by johnkslang** [comment]
See the prefix() and location() methods in infoSink.h.
