### ISSUE TITLE
clang 3.9 -DCMAKE_BUILD_TYPE=Release miscompiles hlsl.forLoop.frag test

### ISSUE THREAD

**Issue by jfroy** [KhronosGroup/glslang#511]
Building glslang with clang 3.8.1 in Release passes the test, clang 3.9 fails the test. Building Debug or MinSizeRel doesn't fail. That's all the information I have right now.

**Comment by jfroy** [comment]
I've ran the test with asan, msan and ubsan and they reported nothing. valgrind is also OK. So it's almost certainly an LLVM bug.

**Comment by johnkslang** [comment]
Can this be closed as not being a glslang bug?

**Comment by jfroy** [comment]
I'm trying to gather more data with valgrind and other tools to see if glslang has undefined behavior code, or some other bug, but so far it looks like not. I do wonder if this bug should remain open and reference the LLVM bug I'm preparing for tracking purposes.

**Comment by jfroy** [comment]
LLVM bug filed. https://llvm.org/bugs/show_bug.cgi?id=30602

**Comment by jfroy** [comment]
This no longer reproduces with llvm svn. Hopefully it will be fixed in llvm 4.0 and not regress. It may be worth while to setup a clang buildbot for the project if there is CI infrastructure.
