### ISSUE TITLE
Wrong link to the repo in the build instructions

### ISSUE THREAD

**Issue by annygakh** [KhronosGroup/glslang#528]
I am following build instructions and the url gives me an issue

> 1) Check-Out this project
> 
> cd <parent of where you want glslang to be>
> git clone git@github.com:KhronosGroup/glslang.git
> 
> 

`Cloning into 'glslang'... Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.`

The url should simply be https://github.com/KhronosGroup/glslang.git, correct? Will submit a pull request for this.

**Comment by johnkslang** [comment]
It depends on whether you are using SSH or HTTPS.  Both are valid.  Most people who heavily use GitHub will use SSH.

See https://help.github.com/articles/generating-an-ssh-key/
