### ISSUE TITLE
Inline functions and inline spir-v

### ISSUE THREAD

**Issue by edrickhong** [KhronosGroup/glslang#534]
Just curious if this is being looked into. It would be pretty useful to have these, especially since the optimizer is still WIP.

**Comment by johnkslang** [comment]
Agreed.  I think the main discussion is about where an optimizer belongs. As part of glslang, or separate tools in https://github.com/KhronosGroup/SPIRV-Tools.

**Comment by johnkslang** [comment]
It is now pretty clear we want glslang to focus on correct semantic translation and https://github.com/KhronosGroup/SPIRV-Tools to focus on optimization. These issues are being handled there.
