### ISSUE TITLE
GetGlobalLock() called before InitializeGlobalLock()

### ISSUE THREAD

**Issue by schwa423** [KhronosGroup/glslang#552]
While debugging a hang caused by my pull request (https://github.com/KhronosGroup/glslang/pull/539), I discovered that there is a call to GetGlobalLock() before InitializeGlobalLock() is ever called.

I observed this when running many (all?) of the tests on Ubuntu 14.04.  It seems quite likely that this occurs with every run of the glslangValidator app, on all platforms.

**Comment by arcady-lunarg** [comment]
The `GetGlobalLock()` and `InitializeGlobalLock()` functions have been deprecated and replaced with a global `std::mutex` that does not require an initialization function.
