### ISSUE TITLE
Incorrect handling of gl_NumSamples by glsl -> SPIR-V translator

### ISSUE THREAD

**Issue by KamuisanMobica** [KhronosGroup/glslang#553]
I noticed that there is no SPIR-V equivalent for gl_NumSamples.

On the other hand glslang is trying to convert gl_NumSamples to variable with UniformConstant storage class:

%1 = OpTypeInt 32 1
%2 = OpTypePointer UniformConstant %1
%3 = OpVariable %3 UniformConstant

which I think is incorrect, because the Vulkan spec states that:

"Variables identified with the UniformConstant storage class are used only as
handles to refer to opaque resources. Such variables must be typed as
OpTypeImage, OpTypeSampler, OpTypeSampledImage, or arrays of only these types."

Full glsl shader source:
# version 440

layout(location = 0) out vec2 fs_out_color;
void main (void)
{
    if(gl_NumSamples == 2)
        fs_out_color = vec2(0.0, 1.0);
    else
    fs_out_color = vec2(1.0, 0.0);
};

SPIR-V translation:

OpCapability Shader
%1 = OpExtInstImport &quot;GLSL.std.450&quot;
OpMemoryModel Logical GLSL450
OpEntryPoint Fragment %4 &quot;main&quot; %18
OpExecutionMode %4 OriginUpperLeft
OpDecorate %18 Location 0
%2 = OpTypeVoid
%3 = OpTypeFunction %2
%6 = OpTypeInt 32 1
%7 = OpTypePointer UniformConstant %6
%8 = OpVariable %7 UniformConstant
%10 = OpConstant %6 2
%11 = OpTypeBool
%15 = OpTypeFloat 32
%16 = OpTypeVector %15 2
%17 = OpTypePointer Output %16
%18 = OpVariable %17 Output
%19 = OpConstant %15 0
%20 = OpConstant %15 1
%21 = OpConstantComposite %16 %19 %20
%23 = OpConstantComposite %16 %20 %19
%4 = OpFunction %2 None %3
%5 = OpLabel
%9 = OpLoad %6 %8
%12 = OpIEqual %11 %9 %10
OpSelectionMerge %14 None
OpBranchConditional %12 %13 %22
%13 = OpLabel
OpStore %18 %21
OpBranch %14
%22 = OpLabel
OpStore %18 %23
OpBranch %14
%14 = OpLabel
OpReturn
OpFunctionEnd

**Comment by johnkslang** [comment]
Agreed gl_NumSamples is a special case, already having special handling due to its inconsistent nature.  Will look more deeply at how to handle this.

**Comment by johnkslang** [comment]
Khronos has decided gl_NumSamples is not supported for Vulkan. There are no "uniform" built-ins in Vulkan. Glslang currently reflects this decision.
