### ISSUE TITLE
HLSL -> Spir-v: Ressource mapping control

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/glslang#554]
Hi,
the current way how are bindings and sets are translated from HLSL is very restricted. Especially if you think about Vulkan and the option there to segment ressources into different descriptor sets.

Currently you can only set an offset for the output binding indices and no control over the used descriptor set.

A better way would be to have an option to provide a callback that handles the mapping.

If no one is already working on it, i can provide a pull request with our implementation as soon as it is done (can take a couple of days/weeks, depends on when i get around to finish it up).

**Comment by johnkslang** [comment]
Sounds like a possible way of handling it, though a pretty new thing to do in glslang.

@steve-lunarg does this interact with your current plans for managing binding numbers?

**Comment by TiemoJung** [comment]
Pull request #562 has the proposed changes, it is untested though and needs feedback.

**Comment by steve-lunarg** [comment]
I commented in the PR.

**Comment by hrydgard** [comment]
#562 wsa merged, should this be open?

Also, I missed this issue before I opened https://github.com/KhronosGroup/glslang/issues/591 , which is a bit related. The merged pull request does not seem to provide a facility for such merging, though, unless I'm missing something.

**Comment by johnkslang** [comment]
Closing this one for mapping, leaving #591 open for combining.
