### ISSUE TITLE
StructuredBuffer syntax not supported

### ISSUE THREAD

**Issue by jonckennedy** [KhronosGroup/glslang#569]
The HLSL parser currently doesn't support this syntax :
```
  struct data
  {
    float4 val1;
  }

  shared StructuredBuffer<data> gData : register(t123)
```

Not sure if this falls into your RWBuffer work?

**Comment by johnkslang** [comment]
It was listed as "arbitrary return" in issue #362.  I updated that line to say structure and point here.
