### ISSUE TITLE
spirv return block

### ISSUE THREAD

**Issue by sylware** [KhronosGroup/glslang#58]
Return statements in loops inside a void-returning function generates a branch instruction which targets
the function terminating return block.
It means there is a branch from inside a nested flow control
to an outside return block. There is no other other way than performing a full 2 pass transform in order to know if a branch targets a return block.
Additionnaly, if a return block in not in the nested flow control, we cannot use statically allocated hardware resource.
Do I miss something?

**Comment by mknejp** [comment]
If I understand the spec correctly the only branches that can leave a structured control flow are *branch blocks*, *continue blocks* and *return blocks*. So branching out of a loop to a return block (unless it's the loop's merge block) violates the rules.

See https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_a_id_structuredcontrolflow_a_structured_control_flow

**Comment by johnkslang** [comment]
Yes, it is correct that to exit a loop with a return, it should be a direct return, not a branch to a block containing a return.  Glslang needs to be updated for this rule.  (It inherited some logic to merge at the end of main, which needs to be simlified.)

**Comment by sylware** [comment]
Ok. Feel free to close this bug once the related code simplify is published :)

**Comment by johnkslang** [comment]
Fixed by e770b3e6cfc8907a7ca4e8517ab7dd066d610f04.
