### ISSUE TITLE
In standard C++ preprocessors, 'defined' is an invalid macro name.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#59]
The GLSL specification (this text appears to be the same in all versions of the specification) says this:
```
#define and #undef functionality are defined as is standard for C++ preprocessors for macro definitions
both with and without macro parameters.
```

So it follows that using `defined` as a macro name should throw an error, as is standard for C and C++ preprocessors, `defined` is not a valid macro name.
For example, clang gives:
```C
test.c:1:9: error: 'defined' cannot be used as a macro name
#define defined definer
        ^
```
and GCC gives almost identically:
```C
test.c:1:9: error: "defined" cannot be used as a macro name
 #define defined definer
         ^
```

**Comment by johnkslang** [comment]
Thanks.  I haven't yet verified with the normative reference for the preprocessor; is it just 'defined' or are there any other preprocessor "keywords" this applies to as well?

**Comment by xorgy** [comment]
I haven't actually paid $300 for a copy of the standard, so there could still be more. But from a quick skim of the relevant file in Clang, there don't seem to be others.

defined is AFAIK the only preprocessor operator other than the basic maths operators (+, -, /, *, %, etc.), and those are caught by the "'#define' : must be followed by macro name" error.

**Comment by Kristine1975** [comment]
The draft versions of the C++ standard (essentially the same as the final version) can be freely downloaded at:
C++11: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3337.pdf
C++14: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf
C++1z: https://isocpp.org/std/the-standard

I haven't found the corresponding clause in the C++ standard, but I'd wager "defined" cannot be redefined because it's used by the preprocessor in "#if defined(...)".

**Comment by xorgy** [comment]
I've confirmed that both Clang and GCC treat this as a fatal error for all of the standard C++ modes. This as @Kristine1975 points out, makes basic sense.
“...defined as is standard for C++ preprocessors for macro definitions...” to my ears seems like they want the behaviour of the preprocessors and not necessarily just the standard.

@johnkslang: It seems the standards are a bit lazy here, though I'm not in the group to say. ;-)

**Comment by johnkslang** [comment]
The “...defined as is standard for C++ preprocessors for macro definitions...” is referring to the following from the GLSL language specification:

10 Normative References
1. International Standard ISO/IEC 14882:1998(E). Programming Languages – C++.
Referenced for preprocessor only.

So, that is what should be checked for these semantics.

**Comment by Kristine1975** [comment]
>International Standard ISO/IEC 14882:1998(E). Programming Languages – C++.

In that case the standard can be downloaded here: http://nepsweb.co.uk/langstand/isoCPP/ISO14882.pdf (no idea if that's official). Although I don't think there were (m)any changes concerning the preprocessor between C++98 and C++11.

**Comment by xorgy** [comment]
There doesn't appear to be any mention of this in 14882:1998's section macro replacement (16.3)

The basic problem is that, although you can test if `defined` is #defined in the macro namespace(using `defined`), you cannot test its value in #if and other conditionals since the parser is looking for `defined` as a keyword in that context.

So in glslang,
```GLSL
#define defined 1

#if defined defined
  #error "defined defined"
#endif

#if defined
  #error "defined?"
#endif
```
gives 
```
ERROR: 0:4: '#error' : defined defined  
ERROR: 0:7: 'preprocessor evaluation' : incorrect directive, expected identifier 
ERROR: 0:8: '#error' : defined?  
ERROR: 3 compilation errors.  No code generated.
```

**Comment by Kristine1975** [comment]
>It is possible to disambiguate this by accepting a lone `defined` as an identifier, but parsing it as the keyword when an identifier follows, maybe this is the intent of the C++ committee

I personally doubt that, since context-sensitive keywords didn't exist in C/C++ until C++11, where `overload` and `final` were introduced.

clang is really pedantic about adhering to the C++ standard, so if it doesn't accept a piece of code it's likely the code is non-conforming. So glslang should just do what clang does ;-)

**Comment by xorgy** [comment]
To be clear, no C++ implementation that I can easily try will accept this. G++ won't, Clang won't, VC++ won't.

[Mesa catches the same case glslang currently does](http://cgit.freedesktop.org/mesa/mesa/tree/src/glsl/glcpp/glcpp-parse.y#n1581), however it seems to suffer from the same ambiguity.

**Comment by xorgy** [comment]
In 16.8.3 of 14882:1998
>If any of the pre-defined macro names in this subclause, or the identifier defined, is the subject of a
#define or a #undef preprocessing directive, the behavior is undefined.

**Comment by Kristine1975** [comment]
> In my laziness, I glossed over the relevant section in my first read. 16.8.3 states that behaviour is undefined.

In your defense, one would expect paragraph 16.8p3 in section 16.3, where `#define` is specified, not in a section titled "predefined macro names."

Incidentally the GLSL spec also says:

>Except as noted below, it behaves as the C++ standard preprocessor

I for one look forward to doing meta-programming in the GLSL preprocessor :smile:

**Comment by xorgy** [comment]
To be clear, the section in C++98 and C99 are both equivalent, as _shall not_ really means _without inviting undefined behaviour, may not_. Unlike an RFC standard _SHALL_, it means that an implementation can choose to implement it in any way.

**Comment by potswa** [comment]
"Shall" in the C standard does usually mean what you expected it to mean — not undefined behavior. It appears to be an error of omission in the standard, that this particular constraint was not listed under a **Constraints** heading. In C++, "shall" always means compile-time diagnosis or runtime UB, which is a different policy.

I think the intent of C is to require that `#define defined` produce an error message. On the other hand, C++ says "undefined behavior" instead of "shall not" because its preprocessor specification is lagging. C is currently more authoritative, in this case at least, however it still missed the mark.

By the way, the latest edition of C is C11, not C99.

**Comment by xorgy** [comment]
That's how it works when you're reading a constraint. But since 6.10.4 is not in a constraint, "shall not" means UB.
>If a ‘‘shall’’ or ‘‘shall not’’ requirement that appears outside of a constraint is violated, the
behavior is undefined. Undefined behavior is otherwise indicated in this International
Standard by the words ‘‘undefined behavior’’ or by the omission of any explicit definition
of behavior. There is no difference in emphasis among these three; they all describe
‘‘behavior that is undefined’’.

Buying PDFs for $300 a pop is not at the top of the list under my hobbyist budget, unfortunately; So I'm stuck with C99 for now.
And for the purposes of GLSL, the relevant specification is C++98, not any C spec.

**Comment by potswa** [comment]
Yes, I explained that too, already. Please read the second paragraph of my reply carefully.

**Comment by xorgy** [comment]
Sorry about that again, these specs are so confusing.
[David Krauss in my thread on this on the C++ std-discussion forum seems to agree with your interpretation of C11 §5.1.1.3/1](https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/xm76K9Vj2g0), I agree that it overrides §4/2 

With that said, it remains the case that in C++98 this is just "undefined behaviour".
This makes the glslang decision less clear-cut, though I would suspect the "right thing" is to take the opportunity to throw an error, if that opportunity is there.

Again, sorry for not reading your original comment fully.

**Comment by potswa** [comment]
Further confusing matters, actually the wording didn't change between C89 and C99. Both say "shall not." It was C++ that introduced phrase "undefined behavior" into the spec. Sorry for making the assertion without double checking that.

Furthermore, it looks like C++ was fairly consistent about changing "shall not" into "UB" in **Semantics** sections only. This deserves further investigation… thanks for bringing it to light.

**Comment by johnkslang** [comment]
Thanks for all the reserach.

Given the likelihood there is source #defining "defined", I think this is the right thing to do, pull request applied.
