### ISSUE TITLE
Feature request: Option to automatically combine images/samplers when possible

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/glslang#591]
In HLSL, you can't specify a combined image/sampler, instead you always have a separate sample and use that to sample an image. In OpenGL GLSL though, you bind samples and images together to "texture image units", while in Vulkan you can do it either way. Some vendors recommend combined samplers because they take less valuable register space in shaders.

In order to generate OpenGL-compatible GLSL from SPIR-V generated from HLSL, spirv-cross thus has to use heuristics to combine images and samplers. Often people simply specify one sampler per texture, so you have a sampler in s0 and a texture in t0 - that can be trivially combined into a combined image/sampler in binding 0.

Arguably, this combining step really belongs in glslang as an option, not in spirv-cross - that way you can compile HLSL but still end up with combined image/samplers for optimal performance in Vulkan, without taking a detour through spirv-cross to generate GLSL again and then compile that to achieve the same effect.

Alternatively, maybe it should be in spirv-tools, as an optional post process step on the SPIR-V?

Thoughts?

**Comment by TiemoJung** [comment]
Started to work on this problem, see pull request #674

**Comment by johnkslang** [comment]
This was added by #856.
