### ISSUE TITLE
read file from stdin

### ISSUE THREAD

**Issue by krux02** [KhronosGroup/glslang#598]
I have a library, wher the shader is partially written by the library user, and partially generated at compile time. The full shader itself exists only in text form, and never as a file. It would be nice, if I could run this validator on the generated shader source, without the requirement, to write it into a temp file. If glslangValidator could read a file from stdin, I could leave out the creation of the temporary file, and have (in my opinion) more pretty code.

**Comment by johnkslang** [comment]
Does it work to also use glslang in library form? The could be much faster if you are already driving your tool chain programmatically rather than from the command line.

**Comment by krux02** [comment]
Sadly it does not work in library form. I use the programming language nim, and I am running the command line tool from the compilation. The language is able to run arbitrary code at compile time, but it is not possible (yet), to call into C/C++ libraries during compilation. All I can do at the moment is to use the command line tool, and parse the output.

**Comment by krux02** [comment]
thanks a lot for this option.
