### ISSUE TITLE
HLSL: using classes in hlsl shaders

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#602]
Hello. We're currently checking how to use glslang to convert our custom HLSL shaders (defined using classes concept) to SPIR-V. For now HLSL parser only accepts struct declaration, classes and OOP concepts (mostly inheritance) are not implemented.
Can you please tell me if you plan to add this concept in some future releases? Or how complicated it would be to implement it in the current solution?

**Comment by johnkslang** [comment]
What functionality do you need to be present? I don't think this is currently planned, but it would depend on need and complexity.
