### ISSUE TITLE
Register not ignored when layout is present?

### ISSUE THREAD

**Issue by dankbaker** [KhronosGroup/glslang#606]
I have this line of code:

   layout(set=2,binding=0)Texture2D<float4> i_InputTextureMap : register(t16);

which gets bound to set 2, binding=16, but I would expect it to get bound to 0 since layout should have precedent over register, is that not the intended behavior?

This isn't a blocker by any means, I am just trying to figure out if the behavior matches the intention.

**Comment by kennyalive** [comment]
We also have this issue and for us it's kind of blocker. I made a local change that fixes this in some scenarios but I'm not familiar with a codebase and probably my change is just a hack for particular use case.
It would be nice to have a fix for this. The expectation is if HLSL is compiled to SPIR-V and set/binding is provided then the register should not be taken into account.

**Comment by johnkslang** [comment]
I'm sure we can have any policy here, it seemed somewhat arbitrary.  But, is there some consensus (or logic?) that the Vullkan settings win?  I guess I can see that.

**Comment by johnkslang** [comment]
See #1148 for another example.

**Comment by kennyalive** [comment]
I had the following thoughts: in a shading language by default we use binding semantic that is native to this language. But if we use an extension that adds binding rules from another language then this extension should overwrite (if we have a collision) the original ones. 
Thanks.
