### ISSUE TITLE
HLSL: Support SM6.0 new wave intrinsics..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/glslang#618]
I know even it isn't supported currently via a oficial shader compiler from Microsoft, but specs are published anyway: https://msdn.microsoft.com/en-us/library/windows/desktop/mt733232(v=vs.85).aspx
all new Shading language 6.0 intrinsics::
Wave Query,Wave Vote,Wave Broadcast,Wave Reduction,Wave Scan and Prefix,Quad-wide Shuffle operations,etc..
Don't know if it will require Vulkan 1.1 specs for some of the new intrinsics but Nvidia and AMD Vulkan drivers both seem to support some shuffle instrinsics either via extension (AMD) or NV (feeding direct GLSL)..

**Comment by johnkslang** [comment]
Logged in issue #362.
