### ISSUE TITLE
HLSL shader compiling although there is an undeclared variable

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#626]
Hi.
The following HLSL shaders will compile and generate a SPIRV file

`static float g_array [ ] = { 1, 2, 3, 4, 5 };
float main() {
	return g_array[undeclaredIndex];
}
`
Even though there is an undeclared variable

Just wondering if this is a bug or some special cases?

It comes because of this instructions in HlslParseContext::handleVariable function:
`// Recovery, if it wasn't found or was not a variable.
if (! variable)
{
  variable = new TVariable(string, TType(EbtVoid));
}`

In what cases would we need to recover, or create a void variable in case of we cannot find it?

**Comment by johnkslang** [comment]
The recovery code was inherited from GLSL, where it is used to continue parsing to catch additional errors when compilation is not stopping after the first error.

For HLSL, we are far from writing a validator, or anything that correctly rejects shaders. There are, however, three errors checked for and given around the area you are discussing.

It is fine to catch and report obvious errors however. In general, other tool chains need to be used to validate that an HLSL shader is correct, based on what semantic rule set you want to validate against.

**Comment by johnkslang** [comment]
This is now emitted for the example:

```
ERROR: t.vert:1: 'undeclaredIndex' : unknown variable
```

From commit 1e275c8486325aaab34734ad9a650c0121c5efdb, which was also triggered by a different PR.
