### ISSUE TITLE
[SPIRV] Invalid SSA and missing OpPhi?

### ISSUE THREAD

**Issue by sylware** [KhronosGroup/glslang#63]
#version 450
layout(location = 0) in vec4 in_position;

void main()
{
        float y;

        if(in_position[0]>50.0)
                y=1.0;
        else
                y=2.0;

        gl_Position[0] = y;
}

It seems to generate invalid SSA because it is assigning 2 times a variable, probably because it misses a phi SSA function.
Or do I miss something?

**Comment by mknejp** [comment]
There are really two models that SPIR-V supports. The one chosen by glslang seems to be a load/store model without `OpPhi`. The alternative is to use only `OpPhi` and do without loads/stores where possible. Both are equally valid (if side effects are handled properly) and one can transform the former into the latter.

**Comment by sylware** [comment]
Then why keeping phi? Is phi that efficient at removing excessive load/store?
(Because phi is kind of complex to implement on SIMD machines)

**Comment by sylware** [comment]
It seems since spirv is based on ssa, but not formal ssa,
phi may be more an extra implementation burden than anything else.
There is a bug an khronos bugzilla for the spirv product.
