### ISSUE TITLE
HLSL: structs can declare members having same name

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#630]
Hi, I noticed HLSL shaders defining a struct having members with same names will get compiled without errors.

For example:

static struct {
	float4 f;
	float4 f;
    bool b;
} S2;

float4 PixelShaderFunction() : COLOR0
{
    return S2.f;
}

**Comment by johnkslang** [comment]
Keep in mind that glslang is not an HLSL validator.

**Comment by johnkslang** [comment]
From a previous issue you submitted:

> In general, other tool chains need to be used to validate that an HLSL shader is correct...

**Comment by Joojooo** [comment]
Got it, thanks for your answer
