### ISSUE TITLE
HLSL: vector truncation not working

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/glslang#631]
Hi,

HLSL allows implicit vector truncation from vector to scalars, by simply taking the first component of that vector. We use this in our shaders extensively.

But as it looks like the hlsl front end does not handle this case.
Instead we get this:
ERROR: :1367: '=' :  cannot convert from 'temp 4-component vector of float' to 'temp float'
(1367): error at column 235, HLSL parsing failed.

The line in question is basically this:
float val = tex.SampleLevel(float4(xy,0,0));

**Comment by steve-lunarg** [comment]
A SWAG from the behavior: it looks like there may be a vec->scalar path missing or broken, where vec->smallervec is OK.  Test shader below.  In all cases the truncations work for float1, but not for float.

```
void fn1(float  x) { }
void fn2(float1 x) { }
void fn3(float3 x) { }

float4 f4;

float3 main() : SV_Target0
{
    // Initializers
    float  x  = f4;  // ERROR in glslang
    float1 x1 = f4;  // OK in glslang

    // Assignments
    float  y;
    float1 y1;
    y  = f4;         // ERROR in glslang
    y1 = f4;         // OK in glslang

    float3 z = f4;   // OK in glslang

    fn1(f4);         // ERROR in glslang (no matching overloaded function found)
    fn2(f4);         // OK in glslang
    fn3(f4);         // OK in glslang

    f4 + 3.0;        // OK in glslang
    3.0 + f4;        // OK in glslang

    return f4;
}

```

**Comment by TiemoJung** [comment]
Hi,

the pull request #652 should handle the case.
