### ISSUE TITLE
Android continuous integration.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glslang#634]
Any thoughts on adding Android support to the continuous integration?

The Vulkan-Samples repository uses glslang for the VK_LAYER_OCULUS_glsl_shader layer which is similar to the VK_NV_glsl_shader extension except that it works with any Vulkan driver on all major platforms: Windows, Linux, macOS and Android.

The Vulkan-Samples repository is also setup with continuous integration for all these platforms. In particular, the relevant compilation setup for glslang can be found here:

https://github.com/KhronosGroup/Vulkan-Samples/tree/master/external/libs/glslang

It would be nice to get the same continuous integration setup for the glslang repository so we catch issues as early as possible.

**Comment by antiagainst** [comment]
I think with #889 we can mark this as resolved?
