### ISSUE TITLE
[SPIR-V] short circuiting of logical operators

### ISSUE THREAD

**Issue by mknejp** [KhronosGroup/glslang#64]
The GLSL and ESSL specifications say the following about the order of evaluation of the logical operators in **5.9 Expressions**
> The logical binary operators and (`&&`), or (`||`), and exclusive or (`^^`) operate only on two
Boolean expressions and result in a Boolean expression. And (`&&`) will only evaluate the right
hand operand if the left hand operand evaluated to true. Or (`||`) will only evaluate the right hand
operand if the left hand operand evaluated to false. Exclusive or (`^^`) will always evaluate both
operands.

This behavior doesn't seem to be translated to SPIR-V. The code always evaluates both sides and combines them with `OpLogicalXX`. Wouldn't the correct behavior be a conditional branch to evaluate the second operand depending on the first?

**Comment by johnkslang** [comment]
Yes.  This is now done, by 7c1aa1026ebf7cb7f29aaf5859e9fc99af2cb044.
