### ISSUE TITLE
PpTokens.obj can't be found

### ISSUE THREAD

**Issue by monajalal** [KhronosGroup/glslang#645]
Any idea why I get this error in Visual Studio 2015?

Severity	Code	Description	Project	File	Line	Category	Source	Suppression State	Tool
Error	LNK1181	cannot open input file 'C:\Users\mona\playing-for-data\renderdoc\renderdoc\driver\shaders\spirv\x64\Debug\PpTokens.obj'	renderdoc	C:\Users\mona\playing-for-data\renderdoc\renderdoc\LINK	1	fatal	Build

**Comment by johnkslang** [comment]
The source for that has changed recently, is it compiling without errors for you? Several environments seem to be building it okay, but maybe there is something specific to your environment that doesn't like one of the changes. If we can identify that, we can get it fixed.
