### ISSUE TITLE
[spirv] opphi generation

### ISSUE THREAD

**Issue by sylware** [KhronosGroup/glslang#65]
Is there a way to make glslang generate some basic spirv using intermediate
object ids which would be used in an opphi instruction (which can use only intermediate object id).
It seems the variable/opstore/opload work around is always used.

**Comment by johnkslang** [comment]
Generally eliminating a bunch of load/stores ("mem -> reg") is future work.  It does make an OpPhi for a do-while loop to handle continue, though that very special case might go away with an upcoming control-flow change to SPIR-V.

**Comment by sylware** [comment]
SPIR-V Control flow will significantly change? That's a big thing.

I guess that change is to allow naive and simple transformation software
implementations, without denying ultra complex optimizing transformation
software implementations.

**Comment by johnkslang** [comment]
No, not significantly.  Still the same CFG with the same concept of annotating nested structure on top of it.  I shouldn't have made a future-looking statement.

The minor point is the current OpPhi generated is pretty special case and might change, and the major point is how/when/should glslang generally generate "in register" form of data flow, which would involve OpPhi in general when control flow is present.  I don't have answers right now.

**Comment by johnkslang** [comment]
Update: The recent change (7c1aa1026ebf7cb7f29aaf5859e9fc99af2cb044) to handle && and || short circuiting was done using OpPhi, so it is now pretty easy to get OpPhi to show up (use a non-trivial right operand to && or ||).

Example pseudo code:

```
r1 <- left operand
if (r1)
    r2 <- right operand
r3 = phi(r1, r2)
```
