### ISSUE TITLE
HLSL: crash when parsing uninitialized arrays

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#651]
Hi,

Uninitialized arrays will make glslang to crash.

For example:

static const float3 colors[5];
float3 compute(){
	return colors[1];
}

Maybe it would be more convenient to detect this case and return an error instead?

**Comment by johnkslang** [comment]
Agreed. Fixed by aa6d56298d779965b48f012e84c98ef97b1ea53c, by giving a warning and zero-initializing the const.
