### ISSUE TITLE
HLSL: Missing implementation of D3DCOLORtoUBYTE4 in to Spir-V

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/glslang#657]
Hi,

if a shader uses D3DCOLORtoUBYTE4 build in function, the spir-v translator crashes, because D3DCOLORtoUBYTE4 is undefined.

**Comment by steve-lunarg** [comment]
I might be able to implement that, if I can find something to tell me what it does.  Do you happen to have a reference?  I recall seeing a functional description sometime in the past, but the only sources I can find now are remarkably unspecific.

(In any case, it shouldn't crash...)

**Comment by TiemoJung** [comment]
Hi,

a working implementation can be found in hlsl2glsl.
Like here https://github.com/aras-p/hlsl2glslfork/blob/aa227a5482e0e1405d0517bf4d8b9e0c27edac01/hlslang/GLSLCodeGen/hlslSupportLib.cpp#L1075

**Comment by steve-lunarg** [comment]
Ok, thanks - that's simple enough.  For some reason I had been thinking it was something more complex.  

Implementation in PR #659.

msad4() is still unimplemented.

**Comment by johnkslang** [comment]
This is merged now.
