### ISSUE TITLE
[SPIR-V] texelFetch not yet implemented

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#67]
This seems like a pretty glaring omission.  I took a look at the code and it doesn't look like this should take much time for someone who knows what they're doing with it.  However, my knowledge of the glslang code-base is slim at best and I wasn't seeing exactly how it should be added.

**Comment by johnkslang** [comment]
@jekstrand There are plenty of omissions, it's work in progress.  Thanks for the submission on this one, closing.
