### ISSUE TITLE
HLSL matrix naming sets \ swizzle accessors not parsing or supported

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#670]
It looks like matrix naming sets \ swizzle accessors are not parsed or supported properly.

C:\VulkanSDK\1.0.37.0\Bin>glslangValidator.exe -H -D -S vert -e main Vertex.hlsl
Vertex.hlsl
ERROR: Vertex.hlsl:120: '_11_21_31' : does not apply to this type: temp 3X3 matrix of float
ERROR: Vertex.hlsl:120: '' : missing #endif
ERROR: Vertex.hlsl:120: 'assignment expression' : Expected
Vertex.hlsl(120): error at column 14, HLSL parsing failed.
ERROR: 4 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link

float3x3 createMat3x3(float3 a, float3 b, float3 c)
{
   float3x3 m;
   **m._11_21_31 = a;**
   m._12_22_32 = b;
   m._13_23_33 = c;
   return m;
}

https://msdn.microsoft.com/en-us/library/windows/desktop/bb509634(v=vs.85).aspx#Matrix

Is this already a known issue?

Thank you,
Graham

**Comment by johnkslang** [comment]
I think previous workloads were not requiring this feature, so it is simply not implemented yet.  Will look into it.

**Comment by johnkslang** [comment]
Parsing the syntax and making r-values would be trivial enough; the hard part of this is creating an l-value out of a random subset of a matrix. Neither SPIR-V nor the glslang AST have support for that, so it will need to be transformed into a set of single-component l-values.

Do you have uses like the following?

```
++m._11_21_13;
foo(m._11_21_13); // for void(foo out float3) { ... }
m._11_21_13 += a;
```

@steve-lunarg, I believe you did l-value work recently for similar constructs for image read/write. Is there anything to leverage?

**Comment by gwihlidal** [comment]
I don't believe we have pre\post increment cases of accessor swizzles, or passing them into functions. I've only identified assigning into the matrix subset, or getting a matrix subset and assigning into a temporary float3 or float4.

**Comment by johnkslang** [comment]
The full syntax parsing, and any use of matrix swizzles that degenerate to individual components or rows are now handled in 001dfa1.

Simple assignment into arbitrary matrix swizzles are handled by fdf6347.

Use of non-degenerate matrix swizzles as r-values is not yet supported.

**Comment by gwihlidal** [comment]
This works, thank you!
