### ISSUE TITLE
HLSL default function parameters are not supported

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#671]
It appears that default function parameters are not currently supported:

float4 calcFog(
	float3		worldSpacePos,
	float3		camPos,
	half		sunDotEye,
	half		isNotSky, 
	half		fogMultiplier,
	half3		skyFogColor,
	float3		fogColor, 
	float4		fogParams,
	float4		fogCoefficients,
	float4		fogColorCoefficients, 
	float		fogStartDistance,
	float4		heightFogCoefficients, 
	float2		forwardScatteringParams,
	float3		forwardScatteringColorPresence,
	float2		enabledFogMode,
	out float3	forwardLightScatteringOut,
	**float		depthBasedFogFactor = 1.0f**
{
…
}

C:\VulkanSDK\1.0.37.0\Bin>glslangValidator.exe -H -D -S vert -e main Vertex.hlsl
Vertex.hlsl
ERROR: Vertex.hlsl:1835: ')' : Expected
ERROR: Vertex.hlsl:1835: 'initializer' : Expected
Vertex.hlsl(1835): error at column 29, HLSL parsing failed.
ERROR: 3 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link

**Comment by johnkslang** [comment]
Your example is missing a ')', as reported. Can you try with correct syntax?

**Comment by steve-lunarg** [comment]
Also, make sure you're on a recent master.  Support when in with #647, but just recently.

I tried the example above with the paren added, and called calFog successfully with and without supplying the default param.

**Comment by gwihlidal** [comment]
The missing parenthesis was a transcribing error :) Was on the next line in source. Just tried latest code and it works! (original tests were just 1.0.37 pre-compiled, but now I'm testing from latest compiled source). Closing.
