### ISSUE TITLE
HLSL infinity constant not supported

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#672]
The infinity constant 1.#INF or -1.#INF is not supported in HLSL

i.e.

float i = 1.#INF;

or

bool testFloat(float v)
{
	return !isnan(v) && v != 1.#INF && v != -1.#INF;
}

Thanks,
Graham

**Comment by johnkslang** [comment]
I'll look at adding that syntax.

Note that isinf(f) is present, and might be faster to write your code as

```
    return !isnan(v) && ! isinf(v);
```

I don't know how flexible your code base is though.

**Comment by gwihlidal** [comment]
It would definitely be possible for that, but we've had some old driver bugs in the past where testing against isfinite would be incorrect :) We can definitely clean this up if needed, but mention it for completeness. Though, the helper functions won't allow assigning +/-INF to a variable, like for bounding box expansion. Definitely a low priority issue, regardless.

**Comment by johnkslang** [comment]
Addressed by https://github.com/KhronosGroup/glslang/pull/833.
