### ISSUE TITLE
HLSL component-level gather compare unimplemented

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#673]
Using component-level gather component will throw an unimplemented error.

i.e.

v1[(ic) / 2] = tex.GatherCmpRed(sampComp, tc.xyz, depth, int2(col, _row));

C:\VulkanSDK\1.0.37.0\Bin>glslangValidator.exe -H -D -S vert -e main Pixel1.hlsl
Pixel1.hlsl
ERROR: Pixel1.hlsl:4674: '' : unimplemented: component-level gather compare
ERROR: Pixel1.hlsl:4674: '' : missing #endif
ERROR: Pixel1.hlsl:4674: 'then statement' : Expected
ERROR: Pixel1.hlsl:4674: 'for sub-statement' : Expected
ERROR: Pixel1.hlsl:4674: 'for sub-statement' : Expected
Pixel1.hlsl(4674): error at column 78, HLSL parsing failed.
ERROR: 6 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link

Thanks,
Graham

**Comment by gwihlidal** [comment]
The comment at https://github.com/KhronosGroup/glslang/blob/master/hlsl/hlslParseHelper.cpp#L2424 mentions no way to map the component-wise comparison forms.

Matthäus Chajdas helpfully pointed out that OpImageDrefGather should likely work in this case (for depth comparisons):
https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageDrefGather
OpImageDrefGather <id> <result id> tex (tc.xy, arrayIndex) tc.z (x, y)

There could be instances like GatherCmdGreen that wouldn't work this way, presumably.

**Comment by johnkslang** [comment]
Do you need this for components other than red (component 0)?

GLSL and SPIR-V don't appear to simultaneously support the combination of gather + compare + component.  E.g., the **OpImageDrefGather** instruction does not have a component operand.

If you need a multi-component comparison texture, and to gather from a non-0 component under comparison, I think we're looking at functionality outside the realm of what Vulkan/SPIR-V currently support.

**Comment by johnkslang** [comment]
Closing, as this was fixed by the above commits.
