### ISSUE TITLE
glslangValidator issues no message when it fails to write to a file because the file was read-only

### ISSUE THREAD

**Issue by Ashalah** [KhronosGroup/glslang#676]
This happens when using source control systems like Perforce, which marks your files readonly until you check them out. If someone forgets to check out the .spv file they may not realize glslangValidator didn't actually modify the .spv file because it doesn't give you any warnings or errors.

**Comment by johnkslang** [comment]
Addressed in a simple way by 8f674e8.

**Comment by Ashalah** [comment]
Thanks for the fix!
