### ISSUE TITLE
HLSL: No way to change matrix packing

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glslang#677]
In D3D there are several ways to change the default matrix packing in a way that affects the entire shader:

- Compile with D3DCOMPILE_PACK_MATRIX_ROW_MAJOR (default is column-major)
- Add #pragma pack_matrix(row_major) (https://msdn.microsoft.com/en-us/library/windows/desktop/dd607354(v=vs.85).aspx)

It would be nice if glslang supported one of these (the first one would require some way to set it through C++ interface).

**Comment by redorav** [comment]
I want to add to this that casting a matrix like

row_major float3x3 = (row_major float3x3) mat4x4;

doesn't work if you add the xx_major qualifier to it

**Comment by LoopDawg** [comment]
Partially addressed by #1011, which adds the pragma but not the cast.

**Comment by LoopDawg** [comment]
For completeness: it appears there's also an issue around passing qualified mats to functions.  There is no mechanism in place for handling a majorness mismatch.

**Comment by zeux** [comment]
#pragma pack_matrix(row_major) works now; it would probably be nice to have support for casts/etc. but the major use case here was "all matrices are row major" so I'll close this issue; if somebody cares about specifying row/column major on some matrices and not others feel free to open another one :)
