### ISSUE TITLE
Lots of new warnings 

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/glslang#687]
Trying to update LVL to latest glslang, but getting loads of new warning of the type...

/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp: In member function ‘spv::Id {anonymous}::TGlslangToSpvTraverser::createInvocationsOperation(glslang::TOperator, spv::Id, std::vector<unsigned int>&, glslang::TBasicType)’:
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpNull’ not handled in switch [-Wswitch]
         switch (op) {
                ^
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpSequence’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpLinkerObjects’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpFunctionCall’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpFunction’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpParameters’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpNegative’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpLogicalNot’ not handled in switch [-Wswitch]
/home/mikew/gits/github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/external/glslang/SPIRV/GlslangToSpv.cpp:4173:16: warning: enumeration value ‘EOpVectorLogicalNot’ not handled in switch [-Wswitch]

**Comment by johnkslang** [comment]
Does adding a 'default' clear those up?

**Comment by mikew-lunarg** [comment]
Yes, it seems so

**Comment by mikew-lunarg** [comment]
created PR #689

**Comment by johnkslang** [comment]
Merged, thanks.
