### ISSUE TITLE
MSVC comple error: local function definitions are illegal

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glslang#691]
C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(3979): error C2601: 'glslang::TParseContext::setLayoutQualifier' : local function definitions are illegal [C:\projects\vulkan-samples\build\external\libs\glslang\glslang.vcxproj]
          C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(3777): this line contains a '{' which has not yet been matched
C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(4245): error C2601: 'glslang::TParseContext::mergeObjectLayoutQualifiers' : local function definitions are illegal [C:\projects\vulkan-samples\build\external\libs\glslang\glslang.vcxproj]
          C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(3777): this line contains a '{' which has not yet been matched
C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(4304): error C2601: 'glslang::TParseContext::layoutObjectCheck' : local function definitions are illegal [C:\projects\vulkan-samples\build\external\libs\glslang\glslang.vcxproj]
          C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(3777): this line contains a '{' which has not yet been matched
C:\projects\glslang\glslang\MachineIndependent\ParseHelper.cpp(4354): error C2601: 'glslang::TParseContext::layoutTypeCheck' : local function definitions are illegal [C:\projects\vulkan-samples\build\external\libs\glslang\glslang.vcxproj]

**Comment by johnkslang** [comment]
This got fixed by 2043da90df1d46c2f5981e8b3be469ebab341bb2.
