### ISSUE TITLE
HLSL parser crash : empty struct assignment

### ISSUE THREAD

**Issue by Sypher64** [KhronosGroup/glslang#699]
Hi, I have some HLSL shaders that may use empty structs in particular #define configurations.

The vertex shader below will provoke  assert(assignList != nullptr) in HlslParseContext::handleAssign() and then crash.

/////////////////////

struct SEmpty {};

struct VS_INPUT		{
	float4	Position 	: POSITION;
	SEmpty  Empty;
};

struct VS_OUTPUT {
	float4 RasterPos	: SV_Position;
};

VS_OUTPUT vsMain(const VS_INPUT v)
{
	SEmpty EmptyVar = v.Empty;
	
	VS_OUTPUT Output;
	Output.RasterPos = float4(1,1,1,1);
	return Output;
}

///////////////////

**Comment by johnkslang** [comment]
This takes a different path than it did Jan 25, and no longer triggers any issues.

It generates SPIR-V that does a struct assignment with no members, so it's conceivable that some drivers might not expect that.  I think we need to find out.  It's quite risky to early-eliminate the assign, as so much code expects something to be generated for an assignment.

789086a adds a test for this, so we can watch for any regressions.
