### ISSUE TITLE
SPV "missing functionality" calls exit(1) or will crash

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#7]
The MissingFunctionality() function in SPIRV/SpvBuilder.cpp [here](https://github.com/KhronosGroup/glslang/blob/master/SPIRV/SpvBuilder.cpp#L2129) calls exit(1) unconditionally. This is a problem if glslang is used as a library and not as part of the standalone validator, because then there's no hope of recovering or continuing execution if the application can handle SPIR-V failing to compile.

There's also at least one case - I'd guess more - where if this exit() call is removed then the code will crash later on. I ran into this in GlslangToSpv.cpp around line 808:

```cpp
    case glslang::EOpFunctionCall:
    {
        if (node->isUserDefined())
            result = handleUserFunctionCall(node);
        else
            result = handleBuiltInFunctionCall(node);

        if (! result) {
            spv::MissingFunctionality("glslang function call");
            glslang::TConstUnionArray emptyConsts;
            int nextConst = 0;
            result = createSpvConstant(node->getType(), emptyConsts, nextConst);
        }
        builder.clearAccessChain();
        builder.setAccessChainRValue(result);

        return false;
    }
```

Where setAccessChainRValue ends up accessign a NULL pointer when it calls getTypeId().

**Comment by johnkslang** [comment]
Right:  When functionality is missing, either error recovery code needs to be written, or processing must stop.  Virtually all of these should disappear as SPIR-V nears completion, so it's not worth investing much in the error recovery code yet.

Agreed if any live on, a better mechanism (registered call back?) is needed.

**Comment by johnkslang** [comment]
MissingFunctionality() no longer calls exit(), as of 50e57560a1024589a48933439e687ecbbfa7ba88.  This is called only rarely now, and of those virtually all (dynamically) can recover.  All that are actually hit should be gone soon as well.
