### ISSUE TITLE
SPIRV: Token layout of OpAtomicXXX instructions is incorrect

### ISSUE THREAD

**Issue by amdrexu** [KhronosGroup/glslang#70]
According to latest SPIRV spec, the first source operand "Pointer" should be a pointer variable. Because OpAtomicXXX will be applied to shader image atomic operations, this pointer could be a pointer to a variable or be an image texel pointer.

GLSL:
#version 450

buffer Buffer
{
    uint u1;
} buf;

void main()
{
    atomicAdd(buf.u1, 1);
}

Faulted SPIRV:
16:      7(int) Constant 1
...
14:    13(ptr) AccessChain 10(buf) 12
15:      7(int) Load 14
17:      7(int) AtomicIAdd 15 Device None 16

Correct SPIRV
15:      7(int) Constant 1
...
14:    13(ptr) AccessChain 10(buf) 12
16:      7(int) AtomicIAdd 14 Device None 15

The load operation is unnecessary.

**Comment by johnkslang** [comment]
@amdrexu your analysis looks correct, other comments are on the pull request.

**Comment by johnkslang** [comment]
The broader pull request has been merged.
