### ISSUE TITLE
HLSL : cbuffer default value not supported

### ISSUE THREAD

**Issue by Sypher64** [KhronosGroup/glslang#700]
A constant buffer declaration with default values will not compile.
/////////////////////
cbuffer Constants
{
  float a,b,c;
  float d = 1.0f;
};

/* main */
////////////////////

example of error message produced :

ERROR: 0:23: ',' : Expected 
ERROR: 0:23: 'struct member declarations' : Expected 
(null)(23): error at column 17, HLSL parsing failed.
ERROR: 3 compilation errors.  No code generated.

**Comment by johnkslang** [comment]
Do you just need this to compile, or do you also need the initialization to happen? That is, can you use the API to set up the values yourself, and then just want the shader to compile, ignoring the values?

**Comment by Sypher64** [comment]
Compiling would be nice for a start. For the initialization a trick would be to use dx11 reflection to get the values and then manually set them at vulkan runtime, but it require some extra work. 

Thank you

**Comment by johnkslang** [comment]
One interesting new thing to do is design a sideband mechanism, where an HLL -> SPIR-V emits two outputs. This aspect is transferred to issue #701.

Leaving this open to make the parsing not fail.

**Comment by johnkslang** [comment]
Parsing struct members with initializers is fixed by 18adbdb.
