### ISSUE TITLE
HLSL - Missing support for f16tof32 and f32tof16

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#709]
The following is currently unimplemented:
```
    case EOpF16tof32:
    case EOpF32tof16:
        {
            // Temporary until decomposition is available.
            error(loc, "unimplemented intrinsic: handle natively", "f32tof16", "");
            break;
        }
```

Perhaps it is possible to use (pseudo code):

```
f16tof32 -> unpackHalf2x16(bitfieldExtract(src.select_component, 0, 16)).x
f32tof16 -> bitfieldExtract(packHalf2x16(vec2(src.comp)), 0, 16)
```
https://www.opengl.org/sdk/docs/man4/html/bitfieldExtract.xhtml
https://www.opengl.org/sdk/docs/man4/html/unpackHalf2x16.xhtml
https://www.opengl.org/sdk/docs/man4/html/packHalf2x16.xhtml

Thank you,
Graham

**Comment by steve-lunarg** [comment]
#740.
