### ISSUE TITLE
Apple Metal shader input support?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/glslang#717]
Hi,
seeing glslang is gaining HLSL support as input format for SPIRV output, don't know if much interest but asking for support for Apple Metal shaders as input for generating SPIRV output..
with that glslang should support shaders of all major graphics APIs (OpenGL,DirectX and Apple Metal)..
this could be potentially interesting for porting existing Metal MacOS and IOS apps/games to Android using Vulkan API.. perhaps should be better asking Apple to open source their Metal shader compiler so some of their Metal shader parsing could be reused.. should make sense now that Microsoft also has open sourced their DXIL shader compiler for Shader model 6.0..
Interesting in hearing what people think about this idea..
Thanks..

**Comment by oscarbg** [comment]
Also noting that SPIRV-Cross supports Metal output so SPIRV->Metal shader it's already done, and I'm asking the other way Metal shader->SPIRV..

**Comment by arcady-lunarg** [comment]
There are no plans to do this, and it sounds like there is not much interest in implementing this. If anyone wants to take a stab at implementing a Metal frontend for glslang, patches are of course welcome, but for now I think it's best to close this issue.
