### ISSUE TITLE
Function returning garbage flagged by gcc

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/glslang#718]
```
[    9s] /home/abuild/rpmbuild/BUILD/glslang-3.0.g1077/hlsl/hlslGrammar.cpp:2333:44: warning: no return statement in function returning non-void [-Wreturn-type]
[    9s]          tFinalize& operator=(tFinalize&) { }
[    9s]                                             ^
```
Culprit commit:
```
commit 32fd5d26e3576619205671f12d125d6375252fc6
Author: John Kessenich
Date:   Thu Feb 2 14:55:02 2017 -0700

    Memory/constructor/warning clean-up. Addresses issue #705.
```

**Comment by johnkslang** [comment]
It's dead code. We have dualing warnings. I'll change it to a different one. Someday we'll get to use ` = delete`.

**Comment by jengelh** [comment]
Well either it's
```
void operator=(tFinalize &) }{
```
or
```
tFinalize &operator=(tFinalize &a) { return a; }
```
then. Even if pronounced dead.

**Comment by dgkoch** [comment]
Unfortunately this new code causes warnings on certain microsoft compilers: 

glslang\hlsl\hlslGrammar.cpp(2530) : error C2220: warning treated as error - no 'object' file generated
glslang\hlsl\hlslGrammar.cpp(2530) : warning C4822: 'glslang::HlslGrammar::acceptPostfixExpression::tFinalize::operator =' : local class member function does not have a body
glslang\hlsl\hlslGrammar.cpp(2531) : warning C4822: 'glslang::HlslGrammar::acceptPostfixExpression::tFinalize::tFinalize' : local class member function does not have a body

Apparently the commonly used "disable copy and assignment" prototype-only-declarations do not work well on locally declared classes.

Additional information on this 4822 error: 
https://msdn.microsoft.com/en-us/library/x2ybs5zk.aspx
https://connect.microsoft.com/VisualStudio/feedback/details/802033/incorrect-warning-c4822-on-local-class-a-if-a-default-is-defined
http://stackoverflow.com/questions/18979503/why-locally-defined-struct-in-function-need-assignment-operator-copy-construct

**Comment by johnkslang** [comment]
Okay, trying with an implementation of the dead methods this time. Hopefully this shuts up all compilers.

**Comment by dgkoch** [comment]
Thanks @johnkslang that seems to have worked for our plethora of compilers
