### ISSUE TITLE
Public Binaries Not Working Correctly

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glslang#719]
The primary website,

https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/

Provides a link to public binaries,

https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/

Which when downloaded and used on Windows, are providing the following error when used with extensions supported in the glslang source code,

"WARNING: 0:2: '#extension' : extension not supported: GL_AMD_shader_trinary_minmax"

Which implies either the binary is of the wrong version or is not getting the default behavior,

option(ENABLE_AMD_EXTENSIONS "Enables support of AMD-specific extensions" ON)

**Comment by johnkslang** [comment]
The binaries are not updated often.

I need to come up to speed on how to do this through GitHub anyway.

**Comment by johnkslang** [comment]
I've updated the Windows' binary in the traditional location.

**Comment by ratchetfreak** [comment]
FYI: https://help.github.com/articles/creating-releases/

**Comment by RaymanNg** [comment]
The binaries provided in [https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/](https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/)
not working 

I get below error

```
PS C:\Users\Rayman\Downloads> .\glslangValidator.exe --help
Program 'glslangValidator.exe' failed to run: The specified executable is not a valid application for this OS
platform.At line:1 char:1
+ .\glslangValidator.exe --help
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\glslangValidator.exe --help
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

And the binaries in 
[https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Debug.zip](https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Debug.zip)
output nothing

But the one in windows-x64-Release version works correctly, which is very strange to me

**Comment by arcady-lunarg** [comment]
The mechanism for building public binaries has changed substantially since then, and the current main-tot windows build does appear to work: https://github.com/KhronosGroup/glslang/releases/tag/main-tot
