### ISSUE TITLE
Better CMake support

### ISSUE THREAD

**Issue by Synxis** [KhronosGroup/glslang#731]
I don't want to be harsh, but either the CMake scripts are not really good, or I did not understand the build at all.

We should have:
 - correct dependencies (`glslang` depends on `OSDependent` IIRC, it should be reflected in the CMake)
 - correct includes (using `target_include_directories` so that it is automatically set when using in another project)
 - consistent target names (why `glslang` then `HLSL`, `SPIRV` and finally `SPVRemapper` ?)

I can do all the changes listed above and create a pull request if needed.

**Comment by johnkslang** [comment]
I'm open to improvements that don't break existing usage. There have been a few people contributing to the CMake scripts.

**Comment by Synxis** [comment]
Perfect, I'll do a pull request when it's ready !
