### ISSUE TITLE
Incomplete preprocessor string literals with UTF-8 start bytes (0xC2..0xFF) crash validator.

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#738]
glslangValidator aborts in `glslang::TPpContext::TokenStream::putSubtoken` when the file ends inside a preprocessor string literal where the final byte is a UTF-8 sequence starting byte (0xC2 through 0xFF); for example, if the shader string is `"#define A\"\377"`.

```
glslangValidator: /home/aaron/src/glslang/glslang/MachineIndependent/preprocessor/PpTokens.cpp:101: void glslang::TPpContext::TokenStream::putSubtoken(int): Assertion `(subtoken & ~0xff) == 0' failed.
fish: “~/src/glslang/build/StandAlone/…” terminated by signal SIGABRT (Abort)
```

I found this while testing a glslangValidator package for Emacs, this sort of bug is easy to run into.

**Comment by xorgy** [comment]
The same assertion fails with recursive token pasting, e.g.:
```GLSL
#define a(x)##
a(a())
```

**Comment by johnkslang** [comment]
The original issue was an assert() placed in the wrong location (non-debug mode worked correctly). Moved to correct location.
