### ISSUE TITLE
Missing functionality: struct comparison

### ISSUE THREAD

**Issue by galpeter** [KhronosGroup/glslang#74]
When trying to compile a shader which contains struct comparison the following error is reported: `Missing functionality: Composite comparison of non-vectors`.

Test case:
```
#version 140
in highp vec4 a_position;

struct S { int a; int b; };

void main (void)
{
    S a, b;
    if(a==b) {}

    gl_Postion = a_position;
}
```
Compiled with the `glslangValidator test.vert -V` command.

**Comment by johnkslang** [comment]
Now implemented, by 2211835b4d24734c6ba204d501860d4d081de4a0.
