### ISSUE TITLE
Redundant/wrong code in TParseContext::declareBlock

### ISSUE THREAD

**Issue by randomascii** [KhronosGroup/glslang#741]
In change 04b1c6ed4c1918d691c4a9477bfb7c1e117d16de, contributed in January 2014, the following block of code was added:

    // "The offset qualifier can only be used on block members of blocks declared with std140 or std430 layouts."
    // "The align qualifier can only be used on blocks or block members, and only for blocks declared with std140 or std430 layouts."
    if (currentBlockQualifier.hasAlign() || currentBlockQualifier.hasAlign()) {
        if (defaultQualification.layoutPacking != ElpStd140 && defaultQualification.layoutPacking != ElpStd430) {

The VC++ /analyze bot on Chromium recently noticed that this looked suspicious, saying:
glslang\machineindependent\parsehelper.cpp(5605) : warning C6287: Redundant code:  the left and right sub-expressions are identical.

I agree that the code looks suspicious. I have no idea what the correct code is and I'm not sure if the author (John Kessenich <cepheus@frii.com>) is still active in this project.

Worth investigating to see if this represents anything important, or just to clean it up so that the code better reflects the intent.

**Comment by turol** [comment]
Based on the comment I'd say one of those should be hasOffset().

**Comment by johnkslang** [comment]
Right. I'll fix shortly.

**Comment by johnkslang** [comment]
The fix is actually more subtle: The code is block level, not member level, and `offset` doesn't apply to blocks, so the code is correct, just redundant.  The comment should be at the per-member level, but per-member was missing the `offset` check. So, it looks like there was a history issue with blocks vs. members.

Checking in fix now.
