### ISSUE TITLE
Logic between OpFunctionCall and parameters

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#749]
Hi, if I convert this HLSL shader:

`struct AStruct{
    float2 Position;
    float4 Color;
};

void Compute_id0(AStruct s) {}

void PSMain() {
	AStruct s;
	Compute_id0(s);
	Compute_id0(s);
}`

The SPV bytecode I receive will show the following instructions (for PSMain function):

10:                              TypePointer Function 9(AStruct)
15(PSMain():            2 Function None 3
16:                              Label
**17(s):            10(ptr)    Variable Function
18(param):   10(ptr)    Variable Function
21(param):   10(ptr)    Variable Function**
19:          9(AStruct)    Load 17(s)
                                   Store 18(param) 19
20:          2                  FunctionCall 13(Compute_id0(struct-AStruct-vf2-vf41;) 18(param)
22:          9(AStruct)    Load 17(s)
                                   Store 21(param) 22
23:          2                  FunctionCall 13(Compute_id0(struct-AStruct-vf2-vf41;) 21(param)
                                  Return
                                  FunctionEnd

Is there a reason why it creates a new variable everytime we call a function with the 's' parameter?
Woudn't be possible to directly call OpFunctionCall instruction with the original variable (17)? 
I would assume that by doing so the function called will directly modify the original variable (since the parameter is a pointer on the struct), and so it would be equivalent of using an 'inout' qualifier?

(FYI I tried the same sample with an "inout" qualifier, a new variable is still created, but after the function call this new variable will be copied back to the original one. so I'm wondering why we can't simply directly use the original one and avoid 2 unnecessary copy)

Thanks for your support!

**Comment by johnkslang** [comment]
The semantics are copy-in/copy-out. While `Compute_id0` is running, it could write to `s`, but that write is only to modify the copy, not the original.

If you say `const in s`, the copy won't be made.  An optimization to see if `s` is ever modified could also be added to avoid the copy, but we're looking toward optimizers being independent tools.

**Comment by Joojooo** [comment]
Thanks for your quick answer.

So if I understand correctly, in the case of an '**inout**' function parameter. we could always directly replace all those instructions:

Load 17(s)
Store 18(param) 19
FunctionCall 13(Compute_id0(struct-AStruct-vf2-vf41;) 18(param)
Load 18(param)
Store 17(s) 21

By this one:
FunctionCall 13(Compute_id0(struct-AStruct-vf2-vf41;) 17(s)

If this is correct, wouldn't it be better for glslang parser to do it by default, or there are some reasons not to?

**Comment by ratchetfreak** [comment]
When doing mem2reg it's easier to eliminate 17 in that case and leave 18 as is.

otherwise you need to do a load-store elimination pass to minimize the area that 17 touches

**Comment by johnkslang** [comment]
@Joojooo that doesn't work in general:

```
a = 5;
foo(a, a);

foo(inout a, inout b) // gets two copies of 5
{
    a = 4;  // one copy is now 4
    b == 5; // the other copy is still 5
}
```

**Comment by Joojooo** [comment]
Indeed, good point. Thank you for the answer
