### ISSUE TITLE
Remove or replace deprecated C interface?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#751]
@realitix reports this interface no longer works.

The current preferred interface within glslang is the C++ class interface, so if the C interface in this project no longer works, it should be removed or corrected.  Note that currently shaderc has a working C interface for glslang.

**Comment by realitix** [comment]
see #184 too

**Comment by corporateshark** [comment]
PR #2038

**Comment by johnkslang** [comment]
This is now merged.  Let's try it as the new C API, and make incremental issues/fixes from there.
