### ISSUE TITLE
Wrong scalar-to-vector type deduction in ternary operator with vector condition

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/glslang#752]
The following valid HLSL code is not compilable with glslang:
```hlsl
float4 VS() : SV_Position
{
    float2 a = float2(1, 2);
    float2 b = float2(2, 1);
    return (a < b ? 1.0 : 2.0).xyxy; // ERROR 'xyxy' : vector swizzle selection out of range
}
```
This error message is invalid for HLSL, because the constant literals 1 and 2 are implicitly casted
to a vector with the same size as the boolean vector inside the condition.

The condition expression 'a < b' is from type `bool2`, the type of the subexpressions '1.0' and '2.0' is `float`, so the type of the entire ternary expression is implicitly `float2`.

A correct translation to GLSL could look like this:
```glsl
#version 450
void main()
{
    vec2 a = vec2(1, 2);
    vec2 b = vec2(2, 1);
    gl_Position = mix(vec2(1.0), vec2(2.0), lessThan(a, b)).xyxy;
}
```

**Comment by johnkslang** [comment]
This works correctly now, due to recent changes.
