### ISSUE TITLE
HLSL - identifier expected (float to int cast, then comparison)

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#754]
#define Types_Test1 1u

struct TestInfo
{
	float	testType;
	float3 unused;
};

uint getTestValue(in TestInfo testInfo)
{
	if (uint(testInfo.testType) == Types_Test1) // line 737
	{
		return 1;
	}

	return 2;
}

D:\Test.hlsl:737: error: 'identifier' : Expected

**Comment by johnkslang** [comment]
The grammar thinks the `if (uint...` is declaring a type, will fix.
