### ISSUE TITLE
HLSL - Missing support for remaining buffer types

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#757]
**I wanted to get an official ticket to track progress on the remaining HLSL buffer types that are missing or incomplete:**

ByteAddressBuffer
RWByteAddressBuffer
AppendStructuredBuffer
ConsumeStructuredBuffer

**This includes support for things like:**

- Atomic op methods, e.g, mybuf.InterlockedAdd(...) on RWByteAddressBuffer.
 https://msdn.microsoft.com/en-us/library/windows/desktop/ff471475(v=vs.85).aspx
- IncrementCounter/DecrementCounter methods (i.e. D3D11_BUFFER_UAV_FLAG_COUNTER)
 https://msdn.microsoft.com/en-us/library/windows/desktop/ff471497(v=vs.85).aspx
 https://msdn.microsoft.com/en-us/library/windows/desktop/ff471495(v=vs.85).aspx
- Append and Consume versions (i.e. D3D11_BUFFER_UAV_FLAG_APPEND)
 https://msdn.microsoft.com/en-us/library/windows/desktop/ff471448%28v=vs.85%29.aspx

For the append/consume counters, DX does this by masquerading a buffer slot as an associated index to a counter slot, since counters are not a native concept in DX (boo).

So, binding a buffer (with counter) at slot 2, would under the hood also refer to a counter at slot 2 (in the case of AMD GDS memory). Since GDS isn't exposed on Vulkan (yet?), we probably just need to hide a 32 bit dword in memory that represents the counter itself, possibly by using a buffer type. We can be pretty flexible on the binding here, as long as we can correlate the buffer to the counter wrt. binding slot.

Thanks for adding in the other types!

Graham

**Comment by gwihlidal** [comment]
Here's a super simple append test case:
```
struct DummyType
{
	float2 dummy1;	// 0
	float2 dummy2;	// 8
	float4 dummy3;	// 16
	float  dummy4;	// 24
};	

AppendStructuredBuffer<DummyType> g_testQueue : register(u0);

[numthreads(8, 8, 1)]
void main(
	uint3 GroupID : SV_GroupID, 
	uint3 DispatchThreadID : SV_DispatchThreadID,
	uint3 GroupThreadID : SV_GroupThreadID, 
	uint GroupIndex : SV_GroupIndex)
{
	DummyType dummy;
	dummy.dummy1 = float2(1, 2);
	dummy.dummy2 = float2(3, 4);
	dummy.dummy3 = float4(5, 6, 7, 8);
	dummy.dummy4 = 9;

	g_testQueue.Append(dummy);
}
```

**Comment by gwihlidal** [comment]
Mikko Strandborg mentioned that they, in HLSLcc, translate this into a UAV + a 4-byte atomic buffer for the counter, and they use a similar setup for GLSL and Metal translations.

https://github.com/Unity-Technologies/HLSLcc/blob/master/src/toGLSLDeclaration.cpp#L2702

See: sUAV.bCounter

For Vulkan, each append/consume buffer uses 2 slots.

**Comment by Anteru** [comment]
Alternative (if the buffer size is known) is to place the counter at the end of the buffer. Removes the need for a second allocation and binding two things, but obviously doesn't work if the size isn't known up-front.

**Comment by steve-lunarg** [comment]
> (gwihlidal): Atomic op methods, e.g, mybuf.InterlockedAdd(...) on RWByteAddressBuffer.

That should be working now (in master).  If it doesn't seem to be, it's probably something specific to a particular use, in which case I'll have a look at the repro case.

The counter flavors are not implemented yet though.  About that:

> (Anteru): obviously doesn't work if the size isn't known up-front ... Or you could place the counter at the beginning of the buffer, but needs more indexing magic.

Yeah; the structuredbuffers have runtime sized array members, so beginning is better.  I have some in-progress code for that, but it was unclear to me from online documentation whether that was a valid place for the counter to go.  It seems like it's something that the application would be exposed to, which would constrain the answer.

If you all think it's OK to store it as the first element of the SSBO holding the structuredbuffer contents, I can pursue that.  I just didn't want to invest a lot of time going in a bad direction.

**Comment by chaoticbob** [comment]
> Yeah; the structuredbuffers have runtime sized array members, so beginning is better, if indeed it can even be part of the buffer at all. I have some in-progress code for that, but it was unclear to me from online documentation whether that was a valid place for the counter to go. It seems like it's something that the application would be exposed to, which would constrain the answer. E.g, external buffer as in the link above, vs buffer member.

Is it necessary to use the runtime size? One of the ways the counter is handled in D3D12 is to have the uint tacked to the end of the buffer, resulting in total size = buffer size + sizeof(uint). 

Just curious if some of the complication with the counter is the difference between the D3D12 vs D3D11 approaches?

**Comment by steve-lunarg** [comment]
There were some external discussions about this which settled on having the counter as a separate buffer.  I don't know that an array size is available to the shader, so putting it at buffer end is problematic, but also in DX they appear to be attached to a view rather than the structured buffer object.

glslang now implements the counter methods using separate counter buffers, with one exception to be fixed shortly.  It also provides a reflection query as follows to obtain an index to the buffer object in the reflection database that is associated with a structured buffer of the provided index, or -1 if there is no associated counter:

`int TProgram::getUniformBlockCounterIndex(int index) const;`

There's one matter not yet implemented: the counter methods can only be used on globally scoped variable names, not on structured buffers passed as function parameters.  A fix for that is in progress and it should be resolved fairly soon, but it doesn't work in master as of 27-Apr-2017.

**Comment by chaoticbob** [comment]
@steve-lunarg Thank you for the work on #860. 

I wanted to check some details for Append/Consume buffer behavior to make sure my understanding is correct: 

1. It looks like the counter is placed at the beginning of the buffer?
2. Assuming #1 is true, both members for the descriptor that appear in the SPIR-V shows an offset of 0, and the code looks like it addresses the Append/Consume starting at index 1?
3. Since the SPIR-V looks like it consumes two binding slots, should the descriptor binding referencing the buffer in the Vulkan code do the same?

**Comment by LoopDawg** [comment]
Hi @chaoticbob,

1. The counter is a separate buffer composed of a single uint member.  That choice was settled on after some discussions with folks who had used this feature in DX where, for example, the count is attached to a view to a buffer, and multiple views can have different counter values.

2. The counter will have an offset of 0 within its own buffer (it's the only member).

3. Yes: two binding slots.  The counter will be given its own binding number during the io mapping process, assuming you enable that.  The obvious thing you'll want to know is, "for a given AppendBuffer, what is the binding of the associated counter buffer?"  There is a handy reflection query for that purpose, as follows:

    int TProgram::getUniformBlockCounterIndex(int index) const;

The index you pass in is an index in the uniform block reflection for the base buffer.  The return value is either -1, meaning there was no associated counter buffer, or it is the index in the uniform block reflection of the associated counter buffer.  You can then use the normal reflection API to, for example, query its type information.

**Comment by LoopDawg** [comment]
BTW, unless there are objections, I think this issue could be marked as implemented.  It's been exercised at least a little bit in a rendering test, so is nominally functional.  If problems would appear in the future, they can be handled as specific defects against some part of the behavior.

**Comment by chaoticbob** [comment]
Hi @LoopDawg,

Thanks for the clarification. Updated my simple test cases for D3D12 and Vulkan using the same HLSL source and they're working as expected.

**Comment by LoopDawg** [comment]
Glad to hear it!
