### ISSUE TITLE
Multiview: wrong storage class of variables decorated as ViewIndex

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/glslang#759]
glslang generates following SPIR-V for ViewIndex builld-in from multiview EXT:
```
Decorate 12(gl_ViewIndex) BuiltIn ViewIndex
....
12(gl_ViewIndex):     11(ptr) Variable UniformConstant
```

However the Vulkan spec says: 
```
The code:ViewIndexKHX decoration can: be applied to a shader *input*`
```

My reading of above is the variable storage should be 'Input', not 'UniformConstant'

**Comment by RealTimeDeployment** [comment]
Target" (1) "
Actual " (2) "
Desired" (3) "
X=Voltage
Y=Amperage 
Z=Resistance or weighted member 
{If X2 " not = to" X1 then
X2/Y1=Z2 ; Z2*Y1=X3
Return(X3 ; Z2)
X3 ; Z2>Target
X3 ; Z2=Target}
Rewrite as needed for compliance. Pretty sure Equation is correct,  test to verify. Actual or target Y coefficient = Desired X coefficient "needed"/Actual Z
Logic: Actual Z2 was different than / target constant weighted members / Corrected X needed to "offset" incorrect Z as Actual X was < target X ; ohms law amps=volts/resistance x to z inverse relationship is equal when applied against Y as xy or equal parts of relationship to watts and proportional equal inverse relation to resistance.  
crappy keyboard on android does have correct symbols needed for math.
As short and simplified as I can get it, hope this is compliant, fix as needed to insert the equation. If it works will sign cla.

**Comment by RealTimeDeployment** [comment]
Forgot most important part for z 
If Actual X < Target X
Z1-z2= Zn
Z1+Zn= Z3 or "actual Z"
Other way regressive
If Actual X > Target X 
Then Zn should be a negative number. 
Z3×Y1=X3
Return ( X3 ; Z3 )
X3 ; Z3 > Target 
X3 ; Z3 = Target
Sorry about that

**Comment by dgkoch** [comment]
This is being clarified in the VK_KHX_multiview spec that "The variable decorated with code:ViewIndex must: be declared using the code:Input storage class."

**Comment by johnkslang** [comment]
Is it also correct then that these are

```
in int gl_ViewIndex;
in int gl_DeviceIndex;
```

so that they map the input storage class in SPIR-V?  They were added to glslang as `uniform`.

**Comment by johnkslang** [comment]
I think the `in` vs. `uniform` distinction would now be a spec. modification, if anything, as that shouldn't break GLSL content, but is needed to get correct SPIR-V content. Hence, that's addressed by 7a44a31.

**Comment by dgkoch** [comment]
They are already defined as "in" in the GLSL spec. See
https://www.khronos.org/registry/vulkan/specs/misc/GL_EXT_device_group.txt
https://www.khronos.org/registry/vulkan/specs/misc/GL_EXT_multiview.txt

**Comment by johnkslang** [comment]
Okay, everything should be good now then, closing.

**Comment by johnkslang** [comment]
Actually, those specs leave the storage qualifier off and don't say where to add them. They say to add them to the built-ins, but not where, or whether they are in in/out blocks, etc. They do refer to them as input variables, but it's not enough resolution to know how to add them.

I think this delta needs to be described against the 4.50 specification.

**Comment by johnkslang** [comment]
I reverted this until knowing more about it, and also to see what impact it had on the test bot.

**Comment by johnkslang** [comment]
c08fb8ab9c0d3aeafe11a8eeeed177c882ef76a9 correctly implements what the extension is supposed to say. Updated extensions will be published in the future. Main point is the variables are **in** (**Input** SPIR-V), and only device index is available in compute shaders.
