### ISSUE TITLE
Stack smashing when parsing `int t[5][5][][][][][][] = 0`

### ISSUE THREAD

**Issue by xorgy** [KhronosGroup/glslang#769]
Haven't had time to debug, but when I parse
```
int t[5][5][][][][][][] = 0
```
glslang blows up somewhere in glslang::Type::getCompleteString()

**Comment by johnkslang** [comment]
Not sure about "stack smashing", it is getting appropriately intercepted by snprintf(), which raises asserts, or so.  Guess this could be handled by installing the right parameter verification handlers, but I'm worried about OS dependencies in all this, and feel safer just doing it explicitly in the source.
