### ISSUE TITLE
HLSL - Math operations (+, -, * and /) between two bools doesn't work: Non-logical ops convert bool to int

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#770]
Hi,

I have this minimal example of valid hlsl code

```
struct VS_INPUT { float4 pos : POSITION; };
struct VS_OUTPUT { float4 pos : SV_POSITION; };

VS_OUTPUT test_vx(VS_INPUT input)
{
       VS_OUTPUT output;
       output.pos = input.pos;
	   
	   bool a = true;
	   bool b = false;
	   bool c = a * b;

       return output;
}
```

which doesn't compile because it's multiplying two boolean values. In hlsl this is valid and used often without explicit casting (if I cast a and b to float before multiplying it works)

**Comment by johnkslang** [comment]
Do you have a definition for what these operations are supposed to do? Logical and/or/etc.?  Or cast to int?

**Comment by redorav** [comment]
I don't have anything solid as to where this is defined, but what I've seen happens in hlsl microcode is bools get ANDed with a mask so that an infinity becomes a 1 (This doesn't happen normally i.e. if you only use that bool for a branch), and then those get multiplied as if they were floats.

So if you imagine this code:
```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = input.x > 0.5;
	
	if(a)
		return float4(1, 0, 0, 0);
	else
		return float4(0, 1, 0, 0);
}
```

The compiled code is

```
lt r0.x, l(0.500000), v0.x
if_nz r0.x
  mov o0.xyzw, l(1.000000,0,0,0)
  ret
else
  mov o0.xyzw, l(0,1.000000,0,0)
  ret
endif
ret
```

HLSL avoids the AND by checking for not-zero, and generally does it this way for if statements. However if I directly return input multiplied by a

```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = input.x > 0.5;
	return input * a;
}
```

```
lt r0.x, l(0.500000), v0.x
and r0.x, r0.x, l(0x3f800000)
mul o0.xyzw, r0.xxxx, v0.xyzw
ret
```

The AND is there to be able to treat the bool as a 1 and gets mutiplied as if it were a float.

If I do this for integers,

```
int4 test_px(int4 input : TEXCOORD0) : SV_Target0
{
	bool a = input.x > 1;
	return input * a;
}
```

```
ilt r0.x, l(1), v0.x
and r0.x, r0.x, l(1)
imul null, o0.xyzw, r0.xxxx, v0.xyzw
ret
```

So it seems like bool casts itself to whatever type it needs, to be able to get multiplied by either float or int. I don't know how glsl does this though.

**Comment by johnkslang** [comment]
These look like conversion rules for mixing bools and numeric types. Yes? These should be working basically correctly already, though there are a few pending conversion issues to fix.

However, this issue is not about mixing types, but about `bool OP bool`.  E.g., it as completely logical (pardon the pun) that `true * true == true`, `true + false == true`, etc. but less obvious for minus and divide.

**Comment by redorav** [comment]
Well that's the interesting bit, they don't behave like bools at all. This shader

```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = true, b = true;
	return a + b;
}
```

returns 2.

```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = true, b = true;
	return a + b;
}
```

returns 0,

```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = true, b = true;
	return a * b;
}
```

returns 1

and

```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = true, b = true;
	return a * b;
}
```

doesn't compile as you're dividing by zero.

**Comment by johnkslang** [comment]
Note the original bug was about `bool = bool OP bool`, but the subsequent discussion has always involved conversions to numeric types, which I think are already done correctly. I'll try to figure it out though.

**Comment by redorav** [comment]
My apologies, my first comment deviated from the original question, but the second comment is in line with the question in that it provides examples of what bool OP bool does in hlsl.

**Comment by johnkslang** [comment]
Maybe I'm not seeing it, but doesn't it always show `(float)(bool OP bool)` and not `(bool OP bool)`? It's not a regular language in some ways, so hard to use logic on it sometimes, but if we did, for example, the above is still not enough to know what type `(bool OP bool)` is, though the 2 (vs. 1) it does strongly imply it's either int or float.

This example makes it somewhat clearer:

```
int fun(bool a)  { return a; }
int fun(int a)   { return a; }
int fun(float a) { return a; }

float main() : SV_Target0
{
    bool a = true;
    bool b = true;
    return fun(a);      // returns 1, => a is a bool
    return fun(a && b); // returns 1, => a && b is a bool
    return fun(a & b);  // returns 1, => a & b is a bool
    return fun(a+b);    // returns 2, => a + b is an int
}
```

**Comment by redorav** [comment]
Right, I understand what you mean now and you have a point in that implicitly casting to float could maybe influence the behavior. However even when not cast to float the arithmetic operations behave as if they were.

```
float4 test_px(float4 input : TEXCOORD0) : SV_Target0
{
	bool a = true, b = true;
	if((a + b) == true)
		return float4(1, 0, 0, 0);
	else
		return float4(0, 1, 0, 0);
}
```

This always returns the second value (0, 1, 0, 0)

**Comment by johnkslang** [comment]
>  even when not cast to float the arithmetic operations behave as if they were

Or, as my experiment showed, they are converted to `int`.  Wouldn't your example would get the same result whether converted to int or float?  Both are true: `1 + 1 != 1` and `1.0 + 1.0 != 1.0`.

**Comment by redorav** [comment]
I think you're right that it casts to an int in your experiment and prefers that over a float. I was curious to see what happens in the absence of fun(int a) so I did this:

```
int fun(bool a)  { return a; }
int fun(int a)   { return a; }

float main() : SV_Target0
{
    bool a = true;
    bool b = true;
    return fun(a+b);    // returns 1 if fun(int) is commented out, 2 otherwise
}
```
