### ISSUE TITLE
HLSL - Ignore inline keyword in functions

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#771]
Hi,

Somehow in our code many functions have ended up with the inline keyword in it. Sometimes people copy-paste C++ code and then port it to shader code. Because fxc and Cg ignore the inline keyword we've been able to get away with it but it upsets glslang. It's not a big issue as we probably should just remove those inline keywords anyway but just to make you aware.

```
inline float function_with_inline(float x)
{
	return x;
}

float4 test_px()
{
    float x = function_with_inline(1.0f);
    return x.rrrr;
}
```

**Comment by johnkslang** [comment]
That one is easy.  Note SPIR-V does have a function control for specifying `Inline` but these generally have not been hooked up yet, so that aspect is pending.  (It'll likely be inlined anyway by the next layer down.)
