### ISSUE TITLE
HLSL token pastes after expand instead of before? (Opposite of C++.)

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#772]
I have another bug, this time for the preprocessor. It seems like we can't use a defined token inside a define expression. So something like the following won't work.

```
#define DEFINE_TEXTURE(name) Texture2D name; SamplerState name##_ss;
#define SAMPLE_TEXTURE(name, uv) name.Sample(name##_ss, (uv).xy)

#define test_texture2 test_texture

DEFINE_TEXTURE(test_texture)

float4 test_px(float4 input : TEXCOORD0)
{
    float4 tex = SAMPLE_TEXTURE(test_texture2, input.xy);
    return tex;
}
```

**Comment by johnkslang** [comment]
This may be a difference from C++, and hence GLSL.  In C++ you paste before you expand.

Both C++ and glslang create a token `test_texture2_ss` because those are the tokens you requested to be pasted.

**Comment by johnkslang** [comment]
Fixed by https://github.com/KhronosGroup/glslang/pull/1031
