### ISSUE TITLE
HLSL - Implicit cast from float to bool

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#778]
Hi again,

We're currently transitioning all our hlsl->glsl conversion process to be based on glslang which is why I'm reporting a few bugs lately.

I've got a shader I've pushed through glslang and then to glsl using SPIRVCross. We do conditionals on float shader constants which fxc has no issues with, and these propagate into the glsl code. However it seems the glsl spec doesn't allow this sort of downcasting and won't compile the shader saying "implicit cast from "float" to "bool" "

Thank you!

**Comment by johnkslang** [comment]
Right, GLSL won't implicitly cast from a numeric type to bool, and that is unlikely to change (would be a Khronos specification issue, not a glslang issue).

What is the request though? Is there a shader that is supposed to work, but does not work (post an example)? Or a request for SPIRVCross to generate different GLSL (would be a request for that project)?

**Comment by redorav** [comment]
Right, sorry, the minimal example is this:

```
float main(float input : TEXCOORD0) : SV_Target0
{
    if(input)
		return 0.0;
	else
		return 1.0;
}
```

The resulting glsl from going to hlsl -> SPIR-V -> glsl is a shader where a float is being used like a bool, so it ends up being a float but evaluated inside an if( )

**Comment by johnkslang** [comment]
The `if(input)` should generate SPIR-V that branches on a Boolean, not a float. So, that is a bug in HLSL -> SPIR-V generation.  Will fix.
