### ISSUE TITLE
HLSL vertex shader emits empty struct as output.

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#785]
```
struct DEFAULT_VS_IN 
{
    float4 position : POSITION;
};

struct DEFAULT_VS_OUT 
{ 
    float4 hwPosition : SV_Position;
};

DEFAULT_VS_OUT default_vx ( DEFAULT_VS_IN input ) 
{ 
    DEFAULT_VS_OUT output ;	
    output.hwPosition = input.position;
    return output; 
}
```
Creates a SPIR-V module which has an empty output struct.
```
37(DEFAULT_VS_OUT):             TypeStruct
              38:             TypePointer Output 37(DEFAULT_VS_OUT)
39(@entryPointOutput):     38(ptr) Variable Output
```

This seems like a regression as in e4e8f7b7a31a751be285b64741465b769f5f146f no such struct was emitted, and no output variable was defined, which made sense.

**Comment by johnkslang** [comment]
The problem is, empty structs are legal HLSL, and they can be part of the interface. Is this truly incorrect, or just unexpected?

**Comment by redorav** [comment]
Are they also legal SPIRV? I had this issue while translating a SPIRV shader into glsl. For some reason the glsl compiler doesn't like empty structs (it actually complains about nested structs but removing the empty struct keeps it happy)

**Comment by johnkslang** [comment]
Empty structs are not legal GLSL.  They are legal SPIR-V.  (Could see some driver issues due to that.)

**Comment by Themaister** [comment]
Is it legal to have an output variable which is an empty struct though? Does it consume a location, can you write an empty struct to it?

**Comment by johnkslang** [comment]
Yes, you can make an empty struct, assign (with `=`) an empty struct to an empty struct, declare it as an output. I don't think it takes space.

**Comment by kholtnv** [comment]
Just FYI, "empty" structs are implemented in C++ as having 1 byte. The reason for this is for pointers and addresses. Two objects (variables) are not allowed to occupy the same address. (So you can always be assured that &A != &B even when they are "empty".) This may not be an issue with only "logical addressing mode" languages.

**Comment by kholtnv** [comment]
For SPIR-V if the struct sizes were actually 0 wouldn't you violate this SPIR-V rule: 
The ArrayStride, MatrixStride, and Offset Decorations must be large enough to hold the size of the objects they affect (that is, specifying overlap is invalid).

**Comment by johnkslang** [comment]
> Just FYI, "empty" structs are implemented in C++ as having 1 byte.

That conflates representation with implementation. This topic is all about representation.  SPIR-V is a high-level IR.

> For SPIR-V if the struct sizes were actually 0 wouldn't you violate this SPIR-V rule:

Can you give an example? I can't imagine what empty structs have to do with matrices.

HLSL doesn't seem to allocate any locations for an empty struct, which would not work if we gave it size.

I'm pretty sure where this is all heading is to support empty structs, so if you think the specification needs a language change, can you propose the specific new language on a specification repository?

**Comment by kholtnv** [comment]
> That conflates representation with implementation. This topic is all about representation. SPIR-V is a high-level IR.

I don't have the C++ standard in front of me but perhaps if you say that sizeof(char) is an implementation detail then yes (sizeof(E) => 1  where E is an empty struct).

The example I was thinking of was an _array_ of empty structs... Wouldn't all the members collide on offset 0? Perhaps it is academic and an implementation wouldn't care anyway.

I agree that SPIR-V should support this but would caution about how to interpret this especially for languages that support pointers and addresses.

**Comment by johnkslang** [comment]
@kholtnv The issue you are posting on (here) is about input/output of logically empty structs. SPIR-V for graphics does not have sizeof. **Offset** and **ArrayStride** *do not* apply to input/output. There are no addresses to compare.

I'd like to keep this issue about its title.

**Comment by johnkslang** [comment]
Clarifying my answer to @Themaister:

Yes, *HLSL* lets you make an empty struct, assign (with =) an empty struct to an empty struct, and declare it as an output. It does not seem to consume any locations in the input/output interface.

(That's all just me reporting what HLSL allows.)

Further, SPIR-V supports empty structs, but is not an optimizer.

I think the only topic for discussion here is whether empty structs should be skipped when SPIR-V lists the input/output interface.

**Comment by Themaister** [comment]
Well, if it is indeed allowed, oddly enough, I'll find a workaround.

Working on the assumption that empty structs don't consume a location it should be possible to avoid emitting any interface variables which are empty structs and mask out all reads and writes to such types in GLSL.

**Comment by johnkslang** [comment]
For glslang, I think we could skip listing them in the interface (not quite sure), but it is harder to dead-code eliminate them on the fly, due to chains of expressions needing to stay intact.

**Comment by Themaister** [comment]
It would probably be okay to eliminate interface variables which are empty structs, and remove any OpStore which references an empty struct. OpLoad of empty struct could be replaced with an OpUndef perhaps?

**Comment by johnkslang** [comment]
Well, now you are discussing doing SPIR-V transforms, which I'm fine with, there are DCE transforms coming on line that will do this best. I want to stick to what glslang can do here, which operates at the AST level where assignments of empty structs have results that can be consumed, and which does not include general DCE, but I think it could include skipping empty structs in the I/O list.

**Comment by Themaister** [comment]
Ok, so I was a bit confused. It seems like the SPIR-V only declares the struct, and declares the output variable, it never actually writes an empty struct to the output variable.

Sounds like a fairly straight forward fix to just not declare empty structs which are never used anyways, and not declare I/O variables which are empty structs. The workaround in SPIRV-Cross was trivial here, but I suspect drivers will trip on empty structs used as I/O variables.

**Comment by johnkslang** [comment]
Drivers should be able to consume SPIR-V with empty structures, but an "all of the above" strategy makes sense too: Drivers support it, DCE passes eliminate it, glslang skips over it.  Glslang has to be dealing with them in general though, so I don't want to have a blanked request that glslang contains a full-elimination transform, when that should be in DCE pass anyway.

Conclusion for glslang: I'll look into "interface skipping" of empty structs.
