### ISSUE TITLE
HLSL - isfinite() not supported for shader other than OpenCL

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#786]
Hi,
I have this minimal shader:

```
cbuffer Example
{
	float4 input;
};

float main() : SV_Target0
{
    // I need a possible source of nan/infinity or fxc will ignore the isfinite test
    float testValue = input.x / input.y;
    if(isfinite(testValue))
        return input.z;
    return input.w;
}
```

This doesn't work because (I'm told from SPIRV-Cross) isfinite isn't defined for shaders other than Kernel. Is there a chance we could translate this to !isnan(value) && !isinf(value) for other shaders?

**Comment by steve-lunarg** [comment]
Ah, so it's not.  #817.  It's decomposed unconditionally, though strictly speaking it could pass through for CS.
