### ISSUE TITLE
HLSL - Structured buffer produces SSBO and variable with the same name; drivers crash.

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#787]
Some drivers crash with duplicate variable names, which occurs through the normal structured buffer path that generates both the SSBO and variable with the same name

Simple repro shader:

```
RWStructuredBuffer<uint4> Destination : register(u0);

cbuffer Constants : register(b0)
{
	uint value;
	uint destinationBufferSize;
};

[numthreads(256,1,1)]
void main(uint3 tg_id : SV_GroupID, uint3 gt_id : SV_GroupThreadID)
{
	uint offset1 = (tg_id.x * 2 + 0) * 256 + gt_id.x;
	uint offset2 = (tg_id.x * 2 + 1) * 256 + gt_id.x;

	Destination[offset1] = value;
	Destination[offset2] = value;
}
```
Which produces SPIR-V:
```
              OpName %Destination "Destination"
              OpMemberName %Destination 0 "@data"
              OpName %Destination_0 "Destination"
```

> This appears to be a SPIR-V consumer compilation error. I'm not sure if it's due to invalid SPIR-V or not. The internal error is:
> (0) : error C1002: the name "Destination" is already defined at (0)

Is it valid in SPIR-V to have duplicate names like this, and the associated drivers should be improved and/or can this be fixed in glslang by adding a suffix or something to the shadowed variable?

Thanks!
Graham

**Comment by johnkslang** [comment]
Yes, it is valid to have duplicate **OpName** information, or none. It is for debuggers. No driver should depend on it.  It is easy to have multiple names that are the same in different scopes.

Virtually all SPIR-V linkage (accept the entry-point name) should be numeric: binding number, set number, location number, member number, ... Not **OpName**.  Such drivers need to be fixed.

I believe the remapper in glslang or some tools in SPIR-V Tools can be used to strip debug information.

**Comment by gwihlidal** [comment]
Ok, good to know. I'll relay the information to get the driver more robust in this area. Is there a quick change I can make to glslang to mutate this particular case w/ structured buffers to avoid duplicate names while the drivers are fixed?

**Comment by gwihlidal** [comment]
Actually, I just reflect on the names and then strip them out in the meantime. Thank you
