### ISSUE TITLE
matrix-majorness ignored when on nested structure members

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#789]
Hi,

I'm having an issue with a shader that's as follows:

```
cbuffer Example
{
	row_major float4x4 mat1;
	float4 vec1;
};

float4 default_px ( ) : SV_Target0
{
	return mul(mat1, vec1);
}
```

This seems to make the SPIR-V make the matrix as column_major (which then propagates to GLSL). If I specify column_major then the SPIR-V makes it row_major. If I don't put anything, it remains as row_major (which is incorrect in hlsl as the default is column major) I've searched for it in the code and this commit https://github.com/KhronosGroup/glslang/commit/10f7fc739cd4501ee18a1ea7db781bdb1de000b4 seems to suggest a very conscious decision. I don't understand why it's been done this way, hence the question.

**Comment by redorav** [comment]
Just to expand on this, if I have the cbuffer inside a struct, then the layout qualifier is completely ignored... this is a bit of a deal breaker for us.

```
struct MyBuffer
{
	column_major float4x4 mat1;
	float4 vec1;
};

cbuffer Example
{
	MyBuffer g_MyBuffer;
};

float4 default_px () : SV_Target0
{
	return mul(g_MyBuffer.mat1, g_MyBuffer.vec1);
}
```

**Comment by johnkslang** [comment]
Answering the basic question: because HLSL is row-major oriented, and SPIR-V is column-major oriented, we map HLSL rows to SPIR-V columns, and hence to AST columns.  Yes, it's opposite day, and that works.

Now, if a needed qualifier is being ignored, that is a different topic. Is it captured anywhere else?

**Comment by redorav** [comment]
I'm fine with it being swapped if it works although I don't quite understand what you mean when you say hlsl is row major oriented, as my understanding from this sentence "Matrix packing order for uniform parameters is set to column-major by default" was that the physical layout of matrices is done by columns.

In any case, the first example shader correctly captures this inversion, so setting row_major in hlsl ends up as column_major in SPIR-V and viceversa.

In the second shader however, no matter what I set it to it always ends up being row major.

**Comment by redorav** [comment]
@johnkslang Looking at the generated code I understand now why it's doing the inversion, it's also inverting the matrix operations so mul(mat, vec) ends up being vec * mat. Thanks!

**Comment by LoopDawg** [comment]
There's a #1010 for the qualifiers-in-structs-in-buffers issue above.

Also, there may be a few other matrix layout issues: the pack_matrix pragma isn't yet implemented, and there might be an issue around function calls with different matrix layouts.
