### ISSUE TITLE
[SPIRV] spacing parameters and winding layouts are ignored for tess eval shaders

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#79]
#version 450
    
    layout(fractional_even_spacing, quads, ccw, point_mode) in;
    patch in vec4 vFoo;
    
    void main()
    {
        gl_Position = vec4(vFoo.xy + gl_TessCoord.xy, 0.0, 1.0);
    }

                              Source GLSL 450
                              Capability Tessellation
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint TessellationEvaluation 4  "main"
                              ExecutionMode 4 InputQuads *Only InputQuads is added*
                              Name 4  "main"
                              Name 11  "gl_PerVertex"
                              MemberName 11(gl_PerVertex) 0  "gl_Position"
                              MemberName 11(gl_PerVertex) 1  "gl_PointSize"
                              MemberName 11(gl_PerVertex) 2  "gl_ClipDistance"
                              MemberName 11(gl_PerVertex) 3  "gl_CullDistance"
                              Name 13  ""
                              Name 17  "vFoo"
                              Name 23  "gl_TessCoord"
                              ...

**Comment by johnkslang** [comment]
Such modes weren't completed yet.  Did a round of catching all like this, including spacing, depth, depth replacing, winding, and point mode.  In commit e690332c3c2a5f4badbd6d5f67767f84ae5e08a4.
