### ISSUE TITLE
[SPIRV] gl_PerVertex struct for gl_in does not mark members as builtin in eval shaders

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#80]
Seems like a bug since it's inconsistent with geometry shader behavior for example.

    #version 450
    
    layout(fractional_even_spacing, quads, ccw, point_mode) in;
    patch in vec4 vFoo;
    
    void main()
    {
        gl_Position = vec4(gl_in[0].gl_Position.xy + vFoo.xy + gl_TessCoord.xy, 0.0, 1.0);
    }

                              Source GLSL 450
                              Capability Tessellation
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint TessellationEvaluation 4  "main"
                              ExecutionMode 4 InputQuads
                              Name 4  "main"
                              Name 11  "gl_PerVertex"
                              MemberName 11(gl_PerVertex) 0  "gl_Position"
                              MemberName 11(gl_PerVertex) 1  "gl_PointSize"
                              MemberName 11(gl_PerVertex) 2  "gl_ClipDistance"
                              MemberName 11(gl_PerVertex) 3  "gl_CullDistance"
                              Name 13  ""
                              Name 16  "gl_PerVertex"
                              MemberName 16(gl_PerVertex) 0  "gl_Position"
                              MemberName 16(gl_PerVertex) 1  "gl_PointSize"
                              MemberName 16(gl_PerVertex) 2  "gl_ClipDistance"
                              MemberName 16(gl_PerVertex) 3  "gl_CullDistance"
                              Name 20  "gl_in"
                              Name 26  "vFoo"
                              Name 32  "gl_TessCoord"
                              MemberDecorate 11(gl_PerVertex) 0 BuiltIn Position
                              MemberDecorate 11(gl_PerVertex) 1 BuiltIn PointSize
                              MemberDecorate 11(gl_PerVertex) 2 BuiltIn ClipDistance
                              MemberDecorate 11(gl_PerVertex) 3 BuiltIn CullDistance
                              Decorate 11(gl_PerVertex) Block *Associated with gl_out, marked builtin*
                              Decorate 16(gl_PerVertex) Block *The input is not*

**Comment by johnkslang** [comment]
Bug in the front-end proper (non SPIR-V).  Fixed by b5c046e58b216ee27fbdc1e3826a6d26868bfd86.
