### ISSUE TITLE
HLSL: Missing scalar-to-struct cast, and invalid type constructors

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/glslang#805]
As stated [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb172396(v=vs.85).aspx), scalar-to-structure type casts are supported in HLSL, but glslang does not support it:
```hlsl
struct VertexOut {
    float4 position : SV_Position;
    float2 texCoord : TEXCOORD;
};
VertexOut main() {
    return (VertexOut)1;
}
```
Compiling this with `glslangValidator -D -e main -S vert -V ScopeTest1.hlsl` produces this output:
```
.\ScopeTest1.hlsl
ERROR: .\ScopeTest1.hlsl:6: 'constructor' : Number of constructor parameters does not match the number of structure fields 
ERROR: .\ScopeTest1.hlsl:6: 'return' : type does not match, or is not convertible to, the function's return type 
.\ScopeTest1.hlsl(6): error at column 21, HLSL parsing failed.
ERROR: 3 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
```
On the other hand, glslang supports an invalid type constructor:
```
struct VertexOut {
    float4 position : SV_Position;
    float2 texCoord : TEXCOORD;
};
VertexOut main() {
    return VertexOut((float4)1, (float2)1);
}
```
This **invalid** HLSL code compiles silently with glslang, but HLSL does not support such type constructors like in GLSL. The new DirectX Shader Compiler reports this:
```
hlsl.hlsl:8:9: error: constructors only defined for numeric base types
        return VertexOut((float4)1, (float2)1);
               ^
```

**Comment by johnkslang** [comment]
This was done just for zero-initialization so far.  Generalizing to any scalar expression now.
