### ISSUE TITLE
Wrong std430 packing?

### ISSUE THREAD

**Issue by neXyon** [KhronosGroup/glslang#821]
Hello,

I have seen issue #264 which seems to be similar to the problem I have. With the following shader code:

```
struct Vertex {
    vec3 pos;
    vec3 normal;
    vec2 texCoord;
};

layout(std430, binding = 2) buffer vertexbuffer
{
    Vertex vertices[];
};
```

I get the following translation

```
                              MemberDecorate 67(Vertex) 0 Offset 0
                              MemberDecorate 67(Vertex) 1 Offset 16
                              MemberDecorate 67(Vertex) 2 Offset 32
                              Decorate 68 ArrayStride 48
                              MemberDecorate 69(vertexbuffer) 0 Offset 0
                              Decorate 69(vertexbuffer) BufferBlock
                              Decorate 71 DescriptorSet 0
                              Decorate 71 Binding 2
                              Decorate 74 ArrayStride 4
```

which is clearly not packed as I would have expected.

The Vulkan standard specifically mentions std430 for storage buffers:

> Member variables of an OpTypeStruct with a storage class of PushConstant (push constants), or a storage class of Uniform with a decoration of BufferBlock (storage buffers) must be laid out as above, except for array and structure base alignment which do not need to be rounded up to a multiple of 16.

And while #264 mentions the OpenGL standard with

> 9 . If the member is a structure, the base alignment of the structure is N, where
> N is the largest base alignment value of any of its members, and rounded
> up to the base alignment of a vec4. The individual members of this sub-
> structure are then assigned offsets by applying this set of rules recursively,
> where the base offset of the first member of the sub-structure is equal to the
> aligned offset of the structure. The structure may have padding at the end;
> the base offset of the member following the sub-structure is rounded up to
> the next multiple of the base alignment of the structure.

the standard also says:

> When using the std430 storage layout, shader storage blocks will be laid out in buffer storage identically to uniform and shader storage blocks using the std140 layout, except that the base alignment and stride of arrays of scalars and vectors in rule 4 and of structures in rule 9 are not rounded up to a multiple of the base alignment of a vec4.

As far as I understand, that's the whole difference between std430 and std140? If I'm wrong, what would I have to change to get a packed result?

**Comment by johnkslang** [comment]
> which is clearly not packed as I would have expected.

I actually don't know what you expected.

If I read your SPIR-V subset correctly, you have a bunch of vec3 and vec2 and they each get their own vec4 slot, which is pretty much how this all works.

Your structure still contains vec3, which means, from rule 9:

> the base alignment of the structure is N, where N is the largest base alignment value of any of its members

That gives you an alignment of 16, before you even get to the part:

> and rounded up to the base alignment of a vec4

So, the "rounded up" bit wasn't doing anything additional in rule 9, hence, the std430 rule won't change it.

**Comment by neXyon** [comment]
> I actually don't know what you expected.

As I wrote, I expected a packed (= no padding) structure. There is actually a [packed layout](https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)#Memory_layout), but glslang doesn't support it apparently:

> 'packed' : not allowed when generating SPIR-V

This is strange considering, that I could define the layout manually when writing SPIR-V assembly instead of GLSL code.

I guess at least for now at least I just can't get it and have to use single floats/a float array?

**Comment by johnkslang** [comment]
Packed doesn't mean no padding, it means platform-specific (implicit) layout.  SPIR-V does not have platform-specific implicit layout, only explicit layout, because it is a portable form. Glslang only deals with the explicit forms, `packed` is just a pass through (non-SPIR-V) to drivers for OpenGL.

**Comment by johnkslang** [comment]
I think a key thing here is that GLSL (not just glslang) supports different layout(...) based on whether the target is SPIR-V.  So far, you have not identified a place where glslang is deviating from specification.

**Comment by neXyon** [comment]
So this is not an issue actually and can be closed. There is no way to get no padding with GLSL -> SPIR-V, right?

**Comment by johnkslang** [comment]
Right, you can only get no padding if you make the types fit together. You can declare the "wrong logical" types that do fit together physically, and do your own pack/unpack, but I don't recommend this. So, the best place to be is to rearrange things to reduce padding:

- combine vec3 + float (not float + vec3)
- combine vec2 + vec2 (keep naturally aligned)
- generally, put a big thing followed by a small thing, so the small thing can fill the gap at the end of the big thing (the opposite order would push the big thing out to the next naturally-aligned boundary)
