### ISSUE TITLE
#pragma once silently ignored

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/glslang#824]
I realize that the GLSL specification explicitly states that this is expected behaviour:

> If an implementation does not recognize the tokens following #pragma, then it will ignore that pragma. 

However since this is such a common pragma in other preprocessors I kind of expected it to work could we either get a warning / notice that it's not supported, or have support for it?

**Comment by redorav** [comment]
I was looking to open this exact bug when I found this, just wanted to add that fxc does support this pragma for hlsl, but in glslang it currently doesn't work.

**Comment by johnkslang** [comment]
I'll put in the warning for now.

Reading a bit about `#pragma once`, it seems quite ill-defined what "the same file" means, given a variety of ways to create multiple paths to the same file (different relative paths, file-system links, etc.), and given ambiguity around what to do with copies of the same file to different names or same names in different locations.

Do we know what choices FXC made, or what is most standard or desirable?

**Comment by Jasper-Bekkers** [comment]
Closing due to lack of traction.
