### ISSUE TITLE
Compiled .spv issue (error C0000: syntax error, unexpected $undefined at token "<undefined>")

### ISSUE THREAD

**Issue by stelar7** [KhronosGroup/glslang#829]
When trying to run the shader below i end up with these errors: 

```
ERROR: [8791161401044] Code 5 : SPIR-V module not valid: Invalid SPIR-V magic number.
ERROR: [1787611608] Code 2 : Vertex info
-----------
0(1) : error C0000: syntax error, unexpected $undefined at token "<undefined>"

WARNING: [8791154191136] Code 9 : vkCreateGraphicsPipelines: returned VK_ERROR_INVALID_SHADER_NV, indicating that one or more shaders failed to compile or link
```

>  $undefined at token "\<undefined\>"

The shaders are valid as far as my knowledge goes;
[.vert](https://github.com/stelar7/vulkanEngine/blob/master/src/main/resources/shaders/test.vert) [vert.spv](https://github.com/stelar7/vulkanEngine/blob/master/src/main/resources/shaders/compiled/vert.spv) 
[.frag](https://github.com/stelar7/vulkanEngine/blob/master/src/main/resources/shaders/test.frag) [frag.spv](https://github.com/stelar7/vulkanEngine/blob/master/src/main/resources/shaders/compiled/frag.spv)

**Comment by johnkslang** [comment]
What made the SPIR-V and what complained about the magic number?

Mostly likely, the magic number is bad, which means you don't have good SPIR-V, which means it's not really what glslang made, which means it's not a glslang issue. However, that's a long string of logic that needs to be verified.

**Comment by stelar7** [comment]
The SPIR-V is made by compiling the vert file that I've included in the post above with glslangValidator.exe from the 1.0.42.1 SDK.

What complained was my own application. ([compiled](https://drive.google.com/open?id=0B0-yhT37ZE4hd0RSUV9Dd0lwV1U), [source](https://github.com/stelar7/vulkanEngine))

**Comment by steve-lunarg** [comment]
For what it's worth, I tried:

1. Compiling the two attached GLSL sources with the latest glslang master, and it produces identical SPIR-V to the above attachments.

2. Running both of the resulting SPIR-V binaries through spirv-val, and there were no complaints from the validator.

**Comment by johnkslang** [comment]
I did a hexdump of the attached vert.spv file, and the magic number is correct.
