### ISSUE TITLE
HLSL: missing implicit type-cast in array indices

### ISSUE THREAD

**Issue by LukasBanana** [KhronosGroup/glslang#830]
Array indices are implicitly casted to integral types in HLSL (here DX9 HLSL, but also valid for DX10 HLSL):
```
uniform float index;
uniform float table[10];
float4 main() : COLOR0
{
    return table[index];
}
```
But with glslang and SPIRV-Cross, the following invalid GLSL code is generated:
```
#version 450

layout(std140) uniform _Global
{
    float index;
    float table[10];
} _16;

layout(location = 0) out vec4 _entryPointOutput;

vec4 _main()
{
    return vec4(_16.table[_16.index]);
}

void main()
{
    _entryPointOutput = _main();
}
```
The array index `_16.index` must be casted to type `int`.

**Comment by steve-lunarg** [comment]
This should already be fixed in #825.  I tried the example above, and it yields this on master, which is converting the float index to an integer type:

```
              22:    6(float) Load 21
              23:     11(int) ConvertFToU 22
              24:     20(ptr) AccessChain 16 18 23
```

Is there another issue remaining?

**Comment by LukasBanana** [comment]
Ok, I didn't used the latest version. I see it has been merged into master just a day ago.
Thanks for quick reply.

**Comment by steve-lunarg** [comment]
Ok, glad to hear that's all it was.  Thanks!
