### ISSUE TITLE
HLSL - Parser fails with cbuffers missing a terminating semicolon

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/glslang#832]
It looks like HLSL allows for cbuffers defined without a terminating semicolon. If it's an easy fix, it would be nice to support this in glslang (even if just for the HLSL frontend), to make porting huge codebases easier. 

```
cbuffer cb0 : register(b0)
{
	float3	g_systemCenter;
	uint 	g_cloudType;
	float4	g_cloudOffsetAndScale;
	float4	g_cloudCoverageExponent;
	float4	g_cloudFade;
	float3  g_lightDir;
	uint    g_dusterPosTexWidth;
}
```
Dx11/SunCloudRadiosityVisibilityCS.cs:16: error: ';' : Expected
Dx11/SunCloudRadiosityVisibilityCS.cs: Dx11/SunCloudRadiosityVisibilityCS.cs(16): error at column 8, HLSL parsing failed.

**Comment by johnkslang** [comment]
Should be an easy fix.

**Comment by johnkslang** [comment]
HLSL is wacky.  `struct { };` and `class { };` have to end in semicolon, while `tbuffer { }` and `cbuffer { }` do not.
