### ISSUE TITLE
HLSL: emit OpLoopMerge Unroll for HLSL [unroll]

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#836]
I believe that currently [unroll] in the HLSL does not result in OpLoopMerge Unroll in the SPIR-V.  Please add support for this, it is a feature relied upon by a lot of HLSL for performance.

**Comment by gwihlidal** [comment]
This is definitely a critical optimization for us, as well

**Comment by johnkslang** [comment]
This is listed in #362, where I have bumped it to the top of the list (reflecting priority order).

The following is outside the scope of glslang, but I trust you are also lobbying IHVs to respect the SPIR-V hints for this?

**Comment by steve-lunarg** [comment]
I wonder if IHVs may often unroll a loop even without an explicit hint.

**Comment by TimothyLottes** [comment]
John, definitely want those hints to work in GLSL source as well.
