### ISSUE TITLE
scalars need to smear to vectors for shift operations

### ISSUE THREAD

**Issue by fluxlalonde** [KhronosGroup/glslang#839]
glslangValidator crashes on the following input:

    flux@breadboard:~/glslang/build/StandAlone$ cat dummy.hlsl 
    float4 dummyPixelShader() : SV_TARGET
    {
    	uint iData = 0x45;
    	// Assumes converted to uint2(iData, iData), 0xFFFF -> uint2(0xFFFF, 0xFFFF) and second 0xFFFF = float2(0xFFFF, 0xFFFF0)
    	float2 singleInt = float2(iData >> uint2(0, 16)) & uint2(0xFFFF, 0xFFFF)) / 0xFFFF;
    	return singleInt.xyxy;
    }
    flux@breadboard:~/glslang/build/StandAlone$ ./glslangValidator -D -V -S frag -e dummyPixelShader dummy.hlsl
    Segmentation fault (core dumped)
    flux@breadboard:~/glslang/build/StandAlone$

**Comment by johnkslang** [comment]
Note that fxc rejects this shader, so I assume this is somewhat theoretical.  (All compilers want & to have integer-domain types.)

I'll still look at fixing it to handle it better.  It is probably constant folding after a semantic error has been caught, but before termination.

**Comment by johnkslang** [comment]
The crash is fixed now, and I suspect the real problem you are after is that `iData >> uint2(0, 16)` is not working right.  Will look at that next.
