### ISSUE TITLE
glslang doesn't provide input/output primitive execution modes for geometry shaders

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/glslang#84]
In Geometry shaders, you are required to specify the input and output primitive type in the GLSL code.  In SPIR-V this is represented by SpvExecutionModeInput* and SpvExecutionModeOutput* execution modes.  However, glslang doesn't provide this information in the shader.

**Comment by jekstrand** [comment]
It also always reports 0 for MaxVertices

**Comment by jekstrand** [comment]
I found the root problem.  In ShCompile, glslang does the compilation which stores all this metadata in a TIntermediate.  It then calls the "machine dependent compiler" with the root of the AST, a version, and a profile.  It completely throws away the metadata.  I'm not sure what the "proper" thing to do here.  Maybe just pass the whole TIntermediate to the compiler->compile() function?

**Comment by johnkslang** [comment]
There are two interfaces, an old deprecated C interface, and a new preferred C++ interface.  The new interface has a TProgram class, which has a getIntermediate() method.  This is what you would want to use as the start to translate the AST to some other form.  TIntermediate has a getTreeRoot() to get the AST.  Tintermediate is the complete representation, and has a intra-stage linker that takes two compilation units for the same stage and merges them together into one.

The old vs. new is explained in both the README and in the interface header, ShaderLang.cpp.

The old one that used inheritance to flesh out a back end was not desirable for the way glslang is used today.  Are you wanting that form, or a C interface?  Or is the new interface workable?

**Comment by jekstrand** [comment]
As long as the new interface allows you to get at the TIntermediate, I don't really care.  I'm looking at what comes out of the vulkancts; I guess I should file the bug there.
