### ISSUE TITLE
OpUConvert for specialization constant

### ISSUE THREAD

**Issue by amdrexu** [KhronosGroup/glslang#848]
In SPIR-V spec, OpUConvert is disallowed for OpSpecConstantOp unless Kernel capability is present. Apparently, glslang will not declare Kernel capability. So this means OpUConvert is forbidden for OpSpecConstantOp. This brings some problems to us if we have such shader:

```
layout(constant_id = 103) const uint su = 4;
const uint64_t u_to_u64 = uint64_t(su);
```

A similar case is OpBitcast, we emulate it in glslang by OpIAdd (dest = iadd src, 0). How should we handle OpUConvert? The emulation is definitely not so simple.

**Comment by johnkslang** [comment]
Shouldn't the extension that adds 64-bit integers also add OpUConvert?

**Comment by amdrexu** [comment]
Yes, current implementation does generate OpUConvert in OpSpecConstantOp. Let's look at this shader:

```
#version 450 core

#extension GL_ARB_gpu_shader_int64: enable

layout(constant_id = 100) const uint u32 = 4;

const uint64_t u64 = uint64_t(u32);

void main()
{
}
```
```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 10

                              Capability Shader
                              Capability Int64
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main"
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              SourceExtension  "GL_ARB_gpu_shader_int64"
                              Name 4  "main"
                              Name 7  "u32"
                              Decorate 7(u32) SpecId 100
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 0
          7(u32):      6(int) SpecConstant 4
               8:             TypeInt 64 0
               9:      8(int) SpecConstantOp 113 7(u32)
         4(main):           2 Function None 3
               5:             Label
                              Return
                              FunctionEnd
```
The problem occurs in the following translation. 113 represents OpUConvert. In SPIR-V spec, OpUConvert is disallowed for OpSpecConstantOp. Then, how should we translate `uint64_t(...)` for specialization constant. We have to do emulation, or change SPIR-V spec. It seems the emulation is not vert easy.
```
const uint64_t u64 = uint64_t(u32);
9:      8(int) SpecConstantOp 113 7(u32)
```

**Comment by johnkslang** [comment]
> In SPIR-V spec, OpUConvert is disallowed for OpSpecConstantOp.

I mean, I think that is a specification bug.  Original SPIR-V for Vulkan only had 32-bit ints, so no purpose for OpUConvert for OpSpecConstantOp.  Any specification that adds multiple bit widths for Vulkan should also add OpUConvert for OpSpecConstantOp.

**Comment by amdrexu** [comment]
I see. So this means we shoud have a new KHR extension to correct the behavior of OpSpecConstantOp. Thank you.

**Comment by johnkslang** [comment]
I created a Khronos-internal issue to track this.

**Comment by amdrexu** [comment]
Thank you. Since OpSConvert is suppored, it is more natural to support OpUConvert in OpSpecConstantOp unconditionally. I do not see any reason why we should differentiate such two OpCodes. Adding a extension to correct the behavior makes thing more complicated. This is just my opinion. Maybe I miss something.

**Comment by johnkslang** [comment]
I have not made any recommendation that additional extensions are needed, only that existing specifications and existing extensions get corrected.

**Comment by DominikWitczakAMD** [comment]
*cough*

**Comment by dneto0** [comment]
I've posted a SPIRV-Tools PR following @johnkslang's suggestion:   enable UConvert whenever extension SPV_AMD_gpu_shader_int16 is turned on.
https://github.com/KhronosGroup/SPIRV-Tools/pull/2264 

That should be accompanied by a change to the extension text.  cc: @sheredom @DominikWitczakAMD

However, it leaves open the possibility of what happens when Int64 is declared, without a companion extension.  Then 32 -> 64bit int conversion would be enabled, and I presume Glslang would generate UConvert similarly.

**Comment by DominikWitczakAMD** [comment]
@dneto0 : Sure, we'll be looking into this shortly.

**Comment by DominikWitczakAMD** [comment]
We do not believe any modifications are required because we have already stated in the the extension spec that:

```
Modifications to the SPIR-V Specification, Version 1.00, Revision 10
--------------------------------------------------------------------

Modify OpSpecConstantOp definition:

(Append OpUConvert to the list of permitted ..Convert Opcodes):

Opcode must be one of the following opcodes. This literal operand is limited to a single 'word'.

'OpSConvert', 'OpFConvert', 'OpUConvert',  (..)
```
