### ISSUE TITLE
HLSL: glslang emits a uniform struct with Texture2D + SamplerState

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/glslang#850]
NVIDIA's public FXAA implementation (which we use) uses a pattern similar to the following simplified shader:

```
struct CombinedTexture
{
	SamplerState smpl;
	Texture2D tex;
};

Texture2D g_myTex;
SamplerState g_mySampler;

float4 sampleTex(CombinedTexture combined, float2 coords)
{
	return combined.tex.Sample(combined.smpl, coords);
}

float4 main(float4 input : TEXCOORD0) : SV_Target0
{
	CombinedTexture combinedTex;
	combinedTex.tex = g_myTex;
	combinedTex.smpl = g_mySampler;
	
	float4 color = sampleTex(combinedTex, input.xy);
	return color;
}
```

The resulting SPIR-V creates a uniform struct with a texture + sampler, but the code isn't really declaring a uniform, just a temporary structure to be able to pass them into the function. This trips up SPIRV-Cross, but I've been told this isn't even legal SPIR-V so presumably would fail on Vulkan too?

```
10:             TypePointer UniformConstant 9(CombinedTexture)
...
39(combinedTex):     10(ptr) Variable UniformConstant
40(g_myTex):     26(ptr) Variable UniformConstant
43(g_mySampler):     30(ptr) Variable UniformConstant
```

EDIT: Hans Kristian of SPIRV-Cross reports that an equivalent vulkan glsl code also produces this error:

```
#version 450

layout(location = 0) out vec4 FragColor;

struct Combined
{
   sampler samp;
   texture2D tex;
};

layout(binding = 0) uniform sampler uSamp;
layout(binding = 1) uniform texture2D uTex;

vec4 samp(Combined combined)
{
   return texture(sampler2D(combined.tex, combined.samp), vec2(0.5));
}

void main()
{
   Combined c;
   c.samp = uSamp;
   c.tex = uTex;
   FragColor = samp(comb);
}
```

**Comment by Themaister** [comment]
For context: https://github.com/KhronosGroup/SPIRV-Cross/issues/164

There was also another shader:
```
struct CombinedTexture
{
	SamplerState smpl;
	Texture2D tex;
};

CombinedTexture g_combinedTex;

float4 sampleTex(CombinedTexture combined, float2 coords)
{
	return combined.tex.Sample(combined.smpl, coords);
}

float4 main(float4 input : TEXCOORD0) : SV_Target0
{	
	float4 color = sampleTex(g_combinedTex, input.xy);
	return color;
}
```
There are two things which probably shouldn't work:
- UniformConstant struct which isn't a Block type.
- Storing opaque data into a struct and passing it around. Structs containing opaque types probably can't be passed around in any sensible way? At least it cannot be expressed in Vulkan GLSL.

**Comment by chaoticbob** [comment]
Curious if there's been an updates on this? If passing around a struct doesn't work, is it feasible to decompose the fields to individual vars?

**Comment by johnkslang** [comment]
https://github.com/KhronosGroup/glslang/pull/905 addresses this. Interactions with other things are complex, so wanting more input about the extent of need.

**Comment by johnkslang** [comment]
So #905 addresses flattening, but not the source shader itself directly writing to opaque types (sampler/texture).

So, knowing more about direct shader writes to opaque types is a critical:
A) if supported by Vulkan, it means all the flattening work is pointless, yet
B) is illegal in Vulkan, so still needs another solution.

We need specific examples of what is not yet covered by 905, and if they include illegal writes to opaque types, we still need creative ideas how to solve that problem: extension to Vulkan, static analysis finding single write and extracting out for side-band driver information, others?

**Comment by chaoticbob** [comment]
Here's a different use case:

````C++
struct GenericTex2D {
  int which;
  Texture2D tex;
  Texture2DArray texArray;
};

struct MaterialResult {
  float3  baseColor;
  float3  sheen;
};

struct MaterialResources { 
  SamplerState  baseColorSampler;
  GenericTex2D  baseColorTex;
  SamplerState  sheenSampler;
  GenericTex2D  sheenTex;
};

struct MaterialParams {
  float  baseColor;
  float  sheen;
};

struct MaterialStyle {
  bool  sheenEnabled;
  int   baseColorState;
};

struct MaterialOptions {
  float3          uvw;
  MaterialParams  params;
  MaterialStyle   style;
};

MaterialResult GetExMaterialValues(MaterialResources resources, MaterialOptions options, out MaterialResult exResults)
{
  MaterialResult mr;
  mr.baseColor = resources.baseColorTex.tex.Sample(resources.baseColorSampler, options.uvw.xy).rgb;
  if (options.style.sheenEnabled) {
    mr.sheen = resources.sheenTex.tex.Sample(resources.sheenSampler, options.uvw.xy).rgb;
  }
  if (options.style.baseColorState == 1) {
    exResults.baseColor = mr.baseColor;
    exResults.sheen = mr.sheen;
  }
  return mr;
}

GenericTex2D SelectTex(Texture2D tex) 
{
  GenericTex2D gt;
  gt.which = 0;
  gt.tex = tex;
  return gt;
}

GenericTex2D SelectTex(Texture2DArray texArray) 
{
  GenericTex2D gt;
  gt.which = 1;
  gt.texArray = texArray;
  return gt;
}


Texture2D       BaseTexture : register(t0);
Texture2DArray  SheenTexture : register(t1);
SamplerState    MySampler : register(s2);

float4 PSMain() : SV_TARGET 
{
  MaterialResources res;
  res.baseColorSampler = MySampler;
  res.baseColorTex = SelectTex(BaseTexture);
  res.sheenSampler = MySampler;
  res.sheenTex = SelectTex(SheenTexture);
  
  MaterialOptions opt;
  opt.uvw = float3(0, 0, 0);
  opt.style.baseColorState = 1;

  MaterialResult outRef;
  MaterialResult ret = GetExMaterialValues(res, opt, outRef);
  return float4(ret.baseColor, 1) + float4(outRef.baseColor, 1);
}
````

**Comment by johnkslang** [comment]
These pseudo-dynamic texture assignments to things that actually have to be static are getting pretty extreme. Can they simply be statically set, instead of giving the appearance of being dynamically set?

It's almost like the shaders are trying to use C-like functions as macro processors to be executed at compile time.  (I assuming all these examples actually fall apart if any actual run-time execution of the setting was required.)

HLSL itself seems quite poorly defined here: It is basically requiring treating it like an interpreted language that the compiler has to execute at compile time. (Alternatively, HLSL requires illegal intermediate results that then go through an arbitrary optimizer, where if it eliminates the illegal results, then everything is okay again.)

**Comment by johnkslang** [comment]
Meant to include where it is no problem to support this:

It is actually feasible to establish aliases at compile time for examples where the apparent dynamic setting occurs earlier in the shader than the use. We already do successfully now, for example, in setting structure-member sampler/texture in the shader before consuming them.

**Comment by johnkslang** [comment]
Having thought through this quite a bit now, I think the best way of solving all these cases in one stroke is to generate SPIR-V with the dynamic assignments, followed by a SPIR-V transform that optimizes them away. It is getting more expensive than that to try to sort it out while parsing (especially where functions late in the compilation unit can conditionally set values needed earlier).

**Comment by arcady-lunarg** [comment]
I believe this is one of the cases that the legalization passes in `spirv-opt` were meant to address, so I am going to close this as completed. All the examples given here compile successfully with the latest version of glslang.
