### ISSUE TITLE
Separate image samplers with depth creates aliased image types

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#854]
```
#version 450
layout(binding = 0) uniform samplerShadow uSampler;
layout(binding = 1) uniform texture2D uTex;
layout(location = 0) in vec3 vUV;

layout(location = 0) out vec4 FragColor;

void main()
{
	FragColor = vec4(texture(sampler2DShadow(uTex, uSampler), vUV));
}
```
The code-gen here is
```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 28

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9 23
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "FragColor"
                              Name 12  "uTex"
                              Name 16  "uSampler"
                              Name 23  "vUV"
                              Decorate 9(FragColor) Location 0
                              Decorate 12(uTex) DescriptorSet 0
                              Decorate 12(uTex) Binding 1
                              Decorate 16(uSampler) DescriptorSet 0
                              Decorate 16(uSampler) Binding 0
                              Decorate 23(vUV) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
    9(FragColor):      8(ptr) Variable Output
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypePointer UniformConstant 10
        12(uTex):     11(ptr) Variable UniformConstant
              14:             TypeSampler
              15:             TypePointer UniformConstant 14
    16(uSampler):     15(ptr) Variable UniformConstant
              18:             TypeImage 6(float) 2D depth sampled format:Unknown
              19:             TypeSampledImage 18
              21:             TypeVector 6(float) 3
              22:             TypePointer Input 21(fvec3)
         23(vUV):     22(ptr) Variable Input
         4(main):           2 Function None 3
               5:             Label
              13:          10 Load 12(uTex)
              17:          14 Load 16(uSampler)
              20:          19 SampledImage 13 17
              24:   21(fvec3) Load 23(vUV)
              25:    6(float) CompositeExtract 24 2
              26:    6(float) ImageSampleDrefImplicitLod 20 24 25
              27:    7(fvec4) CompositeConstruct 26 26 26 26
                              Store 9(FragColor) 27
                              Return
                              FunctionEnd
```
The original image is created saying that there is no depth.
```
              10:             TypeImage 6(float) 2D sampled format:Unknown
```
the combined sampler adds the depth however.
```
              18:             TypeImage 6(float) 2D depth sampled format:Unknown
```
Is this kind of aliasing legal? Is the depth field for a plain OpTypeImage effectively ignored unless it's part of a SampledImage type?

**Comment by AWoloszyn** [comment]
Reading the spec, I think this is illegal.
Specifically: 
```
10:             TypeImage 6(float) 2D sampled format:Unknown
...
18:             TypeImage 6(float) 2D depth sampled format:Unknown
19:             TypeSampledImage 18
...
13:          10 Load 12(uTex)
17:          14 Load 16(uSampler)
20:          19 SampledImage 13 17
```


In the most recent SPIR-V spec OpSampledImage says:
```
OpSampledImage

Result Type must be the OpTypeSampledImage type whose Image Type operand is the type of Image.
```

`20: 19 SampledImage 13 17`  has an `ImageOperand` of `13` which has a type of `10`

`20: 19 SampledImage 13 17` has a type of `19` which is `19: TypeSampledImage 18` Which is a TypeImage of type `18`

It is worth noting that the SPIR-V 1.0 was less strict and only said
```
Result Type must be the OpTypeSampledImage type.
```
But that may have just been looser language, and the intention was always to be more strict.

**Comment by stevec611** [comment]
Can we get a decision on this issue?

GL_KHR_vulkan_glsl states the glsl source is valid:

> Textures can be combined with a
>         variable of type *sampler* or *samplerShadow* to create a sampler type
>         (e.g., sampler2D, or sampler2DShadow). This is done with a constructor,
>         e.g., sampler2D(texture2D, sampler) or
> sampler2DShadow(texture2D, samplerShadow)

but SPIR-V says it isn't?

**Comment by johnkslang** [comment]
> but SPIR-V says it isn't?

SPIR-V is not saying this is illegal. The code generated is not correct, according to the specifications, though making it correct is not trivial. But, aliasing is not required for the given GLSL example, and there is correct SPIR-V that implements the example and follows the specifications.

The issues are:
1. GLSL: GLSL is a bit mixed about tying depth the texture type versus the sampler type
2. Aliasing: can a single shader use the same texture for both shadow and not-shadow uses?
3.  SPIR-V: should depth really be part of the image type?
4. glslang: can correct code be generated?

Current answers I can offer:
1. GLSL: that's just how it is now, the specifications have been done that way for a long time.
2. Aliasing: See 3, but it could also depend on the consuming API if it has additional rules.
3. SPIR-V: Khronos is discussing internally changing this, which could remove the aliasing issue.
4. glslang: This is made harder by not knowing whether a GLSL texture is used with a depth sampler until after it has seen the types declared. But, I'll look at making it smarter.

**Comment by johnkslang** [comment]
#1451 fixes the problem for this example, but then will have problems regarding using a texture for both shadow and non-shadow sampling.  Depends on the result of 2 and 3.
