### ISSUE TITLE
glslang requires RWTexture2D's type to match bound texture

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#858]
Hi,

Seems like glslang is a bit stricter than the D3D12 shader compiler with the type parameter for ```RWTexture2D``` (and possibly ```Texture2D```). The ```#ifdef``` separates the D3D12 version of the shader from the glslsang/Vulkan version. Simple compute shader that just swizzle a pixel from RGBA to BRGA.  The major difference is that ```BufferIn``` for D3D12 can take a ```float4``` and has the expected behavior. The Vulkan version requires the type to be ```uint``` and subsequently requires some logic to go from int to float. ```BufferOut``` seems unaffected. The incoming texture for both ```BufferIn``` and ```BufferOut``` is RGBA8.

````c++
#if defined(D3D12)
RWTexture2D<float4>  BufferIn : register(u0);
RWTexture2D<float4>  BufferOut : register(u1);

[numthreads(16, 16, 1)]
void main(uint3 tid : SV_DispatchThreadID)
{
  float4 val = BufferIn[tid.xy];
  BufferOut[tid.xy] = val.brga;
}

#else // glslang/Vulkan
//
// glslang seems to want a type that matches the
// incoming image format, using uint for rgba8.
//
RWTexture2D<uint>    BufferIn : register(u0);
RWTexture2D<float4>  BufferOut : register(u1);

[numthreads(16, 16, 1)]
void main(uint3 tid : SV_DispatchThreadID)
{
  uint val = BufferIn[tid.xy];
  BufferOut[tid.xy] = float4(((val >> 16) & 0xFF) / 255.0,
                             ((val >>  0) & 0xFF) / 255.0,
                             ((val >>  8) & 0xFF) / 255.0,
                             1);
}
#endif
````

**Comment by chaoticbob** [comment]
I suspect this may also be true for incoming textures for types other than rgba8.

**Comment by LoopDawg** [comment]
Hi @chaoticbob,

Can you help me to understand this one?  I'm not following what the issue is yet.  Looking at the D3D12 side in your example, the RWTextures are templatized on float4, and are copied into the float4 "val", and then into the output:

     float4 val = BufferIn[tid.xy];
     BufferOut[tid.xy] = val.brga;

The two RWTextures are created with float format (image2D) in the linkage:

    0:?     'BufferIn' (layout( binding=0 rgba32f) uniform image2D)
    0:?     'BufferOut' (layout( binding=1 rgba32f) uniform image2D)

and there's no int/float conversions of the data in the SPIR-V, but there isn't in the shader either.

**Comment by chaoticbob** [comment]
Hi @LoopDawg,

Sorry, it's taken a while for respond to this. The example shader up there achieves the same thing in different ways, nothing special about it. The one detail that I failed to mention was that on both D3D12 and Vulkan the incoming image format is R8G8B8A8 which has the same storage format as uint32. In D3D12 I can use RWTexture2D<float4> (or Texture2D<float4> now that --hlsl-iomap is available). Whatever is happening in the background, the shader in D3D12 doesn't seem to care that the data backing the image is uint32. For Vulkan, this doesn't seem to be true, the type parameter for RWTexture2D has to match the type that backs the image. If I try to use RWTexture2D<float4> in Vulkan, I get garbage. 

This could very well be unrelated to how glslang operates, but I thought I'd give it an ask and see where it landed.

**Comment by LoopDawg** [comment]
Speculation: I am wondering if there may be a relation here to the ``Unknown`` format (StorageImageReadWithoutFormat & ...Write... capabilities).

Currently RWTexture* are given an image format in the SPIR-V OpTypeImage opcode derived from the template type in the HLSL.  For example, in ``RWTexture2D<float4>``, that will be ``rgba32f``, which of course does not match the underlying storage format in your case.  Suspicious.  Using the *WithoutFormat capabilities in these cases would impose requirements that are not currently being imposed, so some care is needed here.  

It may be worth a small experiment on the side to see if we can make the problem go away.

You say this also happens with Texture2D, which does use Unknown format.  On the surface the above theory is inconsistent with that data point, but there are a lot of factors involved (image fetch vs image sample, etc).  I'll dig into it some more.

**Comment by chaoticbob** [comment]
> You say this also happens with Texture2D, which does use Unknown format.
I meant ```Texture2D<float4>``` not the template-less ```Texture2D```. I didn't test the latter case. But I will now.

**Comment by LoopDawg** [comment]
Oh, don't worry about that; ``Texture2D`` should be a synonym for ``Texture2D<float4>``.

I'll make an experimental branch that uses the Unknown format for the RW* cases and we can see if that will alter the behavior.  It might be early next week.

**Comment by chaoticbob** [comment]
@LoopDawg Please accept my apologies for wasting time. Apparently between the time I reported this and yesterday when I tested last night, the issue seems to have been resolved. The following shader works exactly the same in D3D12 and Vulkan:
````C++
Texture2D<float4>  BufferIn : register(t0);
RWTexture2D<float4>  BufferOut : register(u1);

[numthreads(16, 16, 1)]
void main(uint3 tid : SV_DispatchThreadID)
{
  float4 val = BufferIn[tid.xy];
  BufferOut[tid.xy] = val.brga;
}
````

And with ```--hlsl--iomap``` Vulkan doesn't complain about ```Texture2D``` anymore.

**Comment by LoopDawg** [comment]
Ah ok - glad it is resolved!
