### ISSUE TITLE
Support for passing #defines as command-line parameters

### ISSUE THREAD

**Issue by nvining-work** [KhronosGroup/glslang#861]
We would like to be able to have an equivalent of fxc's -D parameter, which lets a #define be created via a command-line parameter. (Currently of course -D is being used to emit HLSL; so... I don't know what the parameter should be.) Unless I'm missing something, this does not seem to be implemented in glslangValidator.

**Comment by johnkslang** [comment]
Right, this is missing functionality.  It is also a duplicate of #87.  I will close this one, and list it in #362. Good to be aware of addition need here.
