### ISSUE TITLE
Pass -D preprocessor options in command line

### ISSUE THREAD

**Issue by yousry** [KhronosGroup/glslang#87]
A parameter to pass  preprocessor directives is necessary. For example:
`glslangValidator test.frag -D __LINUX__` or
`glslangValidator test.frag -D __ANDROID__`

**Comment by johnkslang** [comment]
Curious, how would these get set in an production environment?

(The idea being, that whatever makes the shader do the right thing when in an application should also work with glslang.)

**Comment by johnkslang** [comment]
This feature makes sense if something is generated that is consumed (SPIR-V, `-E` option, AST down stream, etc.)  It is also useful for HLSL.

**Comment by nvining-work** [comment]
@johnkslang : I am happy to put together a patch for this, but I wouldn't be happy writing it without knowing what the right thing to do is in a production environment. I believe Direct3D breaks the preprocessor into its own D3DPreprocess() command: https://msdn.microsoft.com/en-us/library/windows/desktop/dd607332(v=vs.85).aspx - but I think somebody other than me should decide how we implement this for paths other than through standalone. Would this be a change to TShader::preprocess? Are we okay with adding a new parameter here?

(It would also be nice to pass -I for include paths on the command line as well, for feature parity with fxc. This seems to already be done by TShader::preprocess and is relatively straightforward; I can get it on the same pass.)

**Comment by nvining-work** [comment]
(Started doing both of these.)

**Comment by johnkslang** [comment]
Yes, first the interfaces must support it, in a backward compatible way, and then Standalone would use the interfaces to expose something on the command line.

**Comment by ubc-nvining** [comment]
Any reason why this *shouldn't* be implemented by writing #defines into the preamble? That's how I've written it so far and it seems to be working, but if there's an issue with this strategy I'd like to know now.

**Comment by nvining-work** [comment]
(Wrong github account..)

**Comment by johnkslang** [comment]
It may be sufficient. Without some research as to what's expected from command-line tools, I'd question whether it works in the presence of complex #undef/#define etc.

Also, we might benefit from a "preprocessor category" of command-line option, to gather up all include, define, and other preprocessor oriented commands. Hopefully something standard if that works with glslang.

**Comment by johnkslang** [comment]
Looked into this a bit more.  Would like to see:

- yes, these should turn into #define and #undef in a preamble and get parsed that way (characters after a newline in the argument would be discarded)
- a new command-line option that means the rest of the command-line is in a "standard" mode, that could then accept -D and -U for this purpose

On the last point, would also like to generate a "glslang" executable as apposed to a "glslangValidator" executable, where the "glslang" executable was by default in the "standard" mode.

Do you have something already in this space, or is it still waiting?

**Comment by johnkslang** [comment]
Should've included an @nvining-work in last comment...

**Comment by johnkslang** [comment]
@nvining-work I also realize now that we can reuse `-D`, based on context (without a mode switch).  I'm willing to take this work on now, if you want.
