### ISSUE TITLE
compling glslang on Linux produces many warnings

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/glslang#875]
As of commit eb9a532b2a4ca076b23d20b09e3f9c08b0c962fe:

SPIRV/spvIR.h:68:27: warning: ‘spv::MemorySemanticsAllMemory’ defined but not used [-Wunused-variable]
glslang/MachineIndependent/iomapper.cpp:416:36: warning: unused parameter ‘stage’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:416:55: warning: unused parameter ‘name’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:416:74: warning: unused parameter ‘type’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:416:85: warning: unused parameter ‘is_live’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:417:34: warning: unused parameter ‘stage’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:417:53: warning: unused parameter ‘name’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:417:72: warning: unused parameter ‘type’ [-Wunused-parameter]
glslang/MachineIndependent/iomapper.cpp:417:83: warning: unused parameter ‘is_live’ [-Wunused-parameter]
StandAlone/../SPIRV/spvIR.h:68:27: warning: ‘spv::MemorySemanticsAllMemory’ defined but not used [-Wunused-variable]

Would it be possible to enable warnings-as-errors to catch these before commiting?
Thanks

**Comment by johnkslang** [comment]
Possibly, but different compilers are giving different warnings, and some may need to get turned off. (The ones you say Linux caught are also caught by Visual Studio, but at the same warning level that complains about constants in control-flow conditionals, which are validly used.)  I don't think it is realistic to treat all warnings as errors, just a certain level of warnings, so need some guidance for each compiler how to set the right level and turn off the warnings that are valid.

Did the recent PR from @steve-lunarg fix the ones above?

**Comment by EoD** [comment]
I can confirm that commit eb9a532b2a4ca076b23d20b09e3f9c08b0c962fe produces the above errors on GCC and Clang. Those warnings are fixed in de1cc06c1d1c1eeae31aa5cae686ccf24064730f with steve-lunarg's PR.
