### ISSUE TITLE
Catching link errors?

### ISSUE THREAD

**Issue by io7m** [KhronosGroup/glslang#89]
Hello.

Given `m.vert`:

```
#version 330 core

vec4 f();

void
main()
{
  gl_Position = f();
}
```

... and `m.frag`:

```
#version 330 core

layout(location = 0) out vec4 out_rgba;

void
main()
{
  out_rgba = vec4(1.0);
}
```

Validating with `glslangValidator -l m.vert m.frag` gives:

```
m.vert
m.frag

Linked vertex stage:


Linked fragment stage:


```

No error is indicated, despite the definition for `f` not having been given anywhere. Is there a way to get the validator to catch errors of this type? In C-like languages, that would obviously become a link-time error.

**Comment by johnkslang** [comment]
Correct, there is a large class of link-time errors not yet implemented.  First step was being complete for compile-time errors.  This is stated in the Khronos landing page: https://www.khronos.org/opengles/sdk/tools/Reference-Compiler

(I.e., being a reference compiler, but not yet a reference linker.)

**Comment by io7m** [comment]
I assume given the "not yet" that this is planned for the future?

**Comment by johnkslang** [comment]
Here is a list (not complete, and some partially done) of things to implement in the linker:

- generate static use of object even if the only use is to access the length of its array

Cross-stage linking

- type consistency check of uniform and ins <-> outs, both variables and blocks, stage-specific arrayness matching
- location/binding/index check
- mixed es/non-es profiles
- statically consumed input not produced by previous stage
- give error for sharing a packed block
- 1.2: matching initializers for uniforms
- 1.3: only statically used built-ins have to be redeclared as flat
- 1.5: matching between gl_PerVertex blocks and gl_PerFragment blocks
- 1.3: deprecated mixing fixed vertex/fragment stage with programmable fragment/vertex stage.
- 4.3: check compute shader not combined with any other stages

Intra-stage linking, single shader

- limits checking:
  - number of input/output compononents
- Even the potential for recursion through subroutine uniforms is an error.
- 4.4: An interface contains two different blocks, each with no instance name, where the blocks contain a member with the same name.
- 4.4: component aliasing (except desktop vertex shader inputs)
- 4.4: overlapping transform/feedback offsets, offset/stride overflow checks, and stride matching

Intra-stage linking, multiple shader (Non-ES)

- block matching
- binding overlap for atomic counters
- matching redeclarations of interface blocks
- 4.3: implicit array sizing is cross shader within a stage
- 4.4: If gl_FragCoord is redeclared in any fragment shader in a program, it must be redeclared in all the fragment shaders in that program that have a static use gl_FragCoord

**Comment by io7m** [comment]
I wonder if the behaviour of `struct`-typed uniform variables should be included here?

Given the following:

```
struct t {
  int x;
  int y;
};

uniform t data;

out int out_0;

void main()
{
   out_0 = data.x;
}
```

Implementations differ on whether or not both `data.x` and `data.y` will be treated as active uniforms after linking. Some only have `data.x` as active, where others have both, even though there are no static references to `data.y`.

**Comment by johnkslang** [comment]
From @weifengz in comment #296.

This simple pair of shaders should have failed to generate spv with linking option due to mismatched uniform blocks, but SPV was generated successfully.

FS:

```
#version 310 es
precision highp float;
layout(location = 0) out vec4 color;
layout(set = 0, binding = 0) uniform myUBO {
  vec4 base;
};
void main()
{
  color = base + 1.0;
}
```

VS:

```
#version 310 es
layout (set = 0, binding = 1) uniform myUBO {
  mat4 m;
};
void main()
{
  gl_Position = m[1];
}
```

**Comment by arcady-lunarg** [comment]
The original issue has since been fixed, and separate issues should be filed for any link errors that should be caught but are not.
