### ISSUE TITLE
[question] Why does program not provide access to the TObjectReflection?

### ISSUE THREAD

**Issue by sergeyreznik** [KhronosGroup/glslang#891]
Maybe I'm missing something, but now parsing program input seems to be very complicated. In my particular case I need to determine type of the uniform - either it is texture or sampler or image. Now I see the only one way to do this - switch/case **getUniformType** which actually is **glDefineType**. This seems to be redundant and not quite useful, because I'm not using OpenGL (I'm on Vulkan). 

Is there any reason for hiding full reflection info?

Thank you
Serhii

**Comment by johnkslang** [comment]
Can't you query for the actual TType*, and ask whatever you want of the TSampler information?

**Comment by sergeyreznik** [comment]
@johnkslang hmmm, this seems to be working. 
I think I just missed it.
Thank you
