### ISSUE TITLE
GLSL : shader storage buffer object qualifier specification.

### ISSUE THREAD

**Issue by absinthe99** [KhronosGroup/glslang#892]
I am an engineer and user of GLSLANG, and I am satisfied quality of this software.

by the way.
I have a question of ESSL specification. (is not OpenGL shader language)  about declaration of shader storage buffer object. 
I found a strange behavior  of nVidia compiler. and I worry my understanding of specification is correct or not. nVidia's compiler parser allowed expression like bellow.

layout(std430)  readonly buffer MySSBO{
 ///
};

but same compiler disallowed expression like below.

layout(std430)  buffer readonly MySSBO{
 ///
};

If my understanding is correct, buffer and readonly are both storage-qualifier, and according to specification any order may be OK. and then both expression must be allowed.

following is khronos GLES specification

**4.11 Order of Qualification
When multiple qualifiers are present in a declaration, they may appear in any order, but they must all
appear before the type.  The layout qualifier is the only qualifier that can appear more than once.
Further, a declaration can have at most one storage qualifier, at most one auxiliary storage qualifier, and at most one interpolation qualifier.  Multiple memory qualifiers can be used.  Any violation of these rules will cause a compile-time error.**

but if the *buffer* is a type,  other qualifier must appear before *buffer*. and then *buffer readonly* must be disallowed.
I tried to verificate glslang parser, and glslang parser allowed both expression.

It would be greatly appreciated if you could explain the details.

regards

**Comment by johnkslang** [comment]
`buffer` is not a type, it is a qualifier.  Key point is this from the grammar:

```
storage_qualifier:
    CONST
    IN
    OUT
    INOUT
    CENTROID
    PATCH
    SAMPLE
    UNIFORM
    BUFFER
    SHARED
    COHERENT
    VOLATILE
    RESTRICT
    READONLY
    WRITEONLY
```

**Comment by absinthe99** [comment]
johnkslang -san

Thank you very much for your comment.
This means nVidia compiler was wrong.

Definition below must be accepted.
layout(std430) buffer readonly MySSBO{
///
};

Regards
shusaku sawato.
