### ISSUE TITLE
HLSL parsing error when constructing half3x3 variable from 4 half3 arguments

### ISSUE THREAD

**Issue by SSPkrolik** [KhronosGroup/glslang#898]
Here is a place in my fragment shader where the error happens (lines 186-188):
```hlsl
  fFlipNormal*=IN.bIsFrontFace?1.0f:-1.0f;   // line 186
  half3x3 mTangentToWS=half3x3(half3(1,0,0),half3(0,1,0),half3(0,0,1));  // line 187
  mTangentToWS=half3x3(IN.vTangent.xyz,IN.vBinormal.xyz,IN.vNormalWS.xyz*fFlipNormal);  // line 188
```
Here is the output of `glslValidator` utitliy:
```sh
rostislavd@rostislavd-VirtualBox:~/Projects/glslang/build$ install/bin/glslangValidator -D -V ../../Shaders/illumZPassPS.frag 
../../Shaders/illumZPassPS.frag
ERROR: ../../Shaders/illumZPassPS.frag:187: 'half3x3' : unknown variable 
ERROR: ../../Shaders/illumZPassPS.frag:187: ';' : Expected 
../../Shaders/illumZPassPS.frag(187): error at column 22, HLSL parsing failed.
ERROR: 3 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
``` 
DirectX11 shader compiler compiles it just fine. Also I hadn't found that the feature is absent for HLSL parsing in issue #362

**Comment by johnkslang** [comment]
It is the fourth line of #362:

>  Map half to float. See issue #492.

Is mapping `half` -> `float` sufficient for you?  (Assuming that means mapping all `half*` types to corresponding `float*` types.)

**Comment by SSPkrolik** [comment]
@johnkslang thx a lot, missed it. Yeah, the mapping would be quite enough.

**Comment by johnkslang** [comment]
This should work now with 96f65521b42dd35e7869ee924633779f306036d3.  FXC also complains if you try to use 4 half3 arguments, so I assume the title is a typo.  The code example only has 3, and my testing shows this works now.
