### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/glslang#9]
revision.h is intended for auto-updated versioning on each change, but this is not working under GitHub; a mechanism needs to be put in place for it.

**Comment by fkaa** [comment]
The consensus around versioning with git seems to revolve around using `git tag` for versions and having multiple branches (eg. one for `stable` and one for `dev`). [This](http://programmers.stackexchange.com/a/255411) SO answer goes through it quite well, but is obviously not the only way to do it.

**Comment by johnkslang** [comment]
Commit 0da9eaabe8b0a858949e878319113ce1c9419f0d updated revision.h.  It is git tag based.  Intention is to bump the tag infrequently, but to frequently bump the master-commit-count part.  I don't think pull requests need to worry about it (yet); it will get bumped often enough anyway (I'm using a pre-commit hook to call the script that updates revision.h).

Version rationale is roughly 1.x => 10 year ago 3Dlabs.  2.x is previous/current year's Khronos revival.

Note also there are independent version strings for glslang itself, ESSL, GSSL, and SPIR-V.

**Comment by xorgy** [comment]
http://semver.org/

first number: Major revisions, when you remove or change existing API endpoints which haven't been labeled "experimental"
second number: Minor revisions, when you add functionality but don't break the existing API
third number: patch/bugfix revisions, when you fix bugs and the fixes don't require an API change.

**Comment by johnkslang** [comment]
Agreed, generally, with semantic versioning.  Just making up the first number.  Some subtleties may exist due to different behaviors for different uses (i.e., if it changes which version of SPIR-V is emitted, that is orthogonal to changing which version of GLSL is accepted, and it makes sense to have these versions tracked in their per-domain versions).  But, take your comments and this thread to be focused more on the glslang interface itself.
