### ISSUE TITLE
[SPIR-V] Image load/store does not emit readonly/writeonly qualifiers

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#90]
When outputting SPIRV with GLSL code like

```
uniform writeonly image2D foo;
```

the SPIRV code does not emit decorations for this.

**Comment by Qining** [comment]
Hi @johnkslang @Themaister . This is issue already fixed? I tried with writeonly/readonly image uniforms and I can see the 'nonreadable' and 'nonwritable' decoration of the image variable in the generated SPIR-V code.

**Comment by Qining** [comment]
Here is a list of glslang tests that use readonly/writeonly keywords:

```
./baseResults/spv.image.frag.out:
./baseResults/spv.double.comp.out:
./baseResults/spv.memoryQualifier.frag.out:
./baseResults/spv.memoryQualifier.frag.out:
./baseResults/spv.memoryQualifier.frag.out:
./baseResults/spv.memoryQualifier.frag.out:
```

**Comment by johnkslang** [comment]
A lot has happened since October! If your local tests show this is working right now, let's close it out.

**Comment by Qining** [comment]
Yes, my local tests show this is working. We can close it :)
