### ISSUE TITLE
GLSL/SPIRV: compiler rejects all redeclarations of builtin block

### ISSUE THREAD

**Issue by chrisforbes** [KhronosGroup/glslang#904]
Since 71facdf435fac7f688c7237b053be1bef8cd16d0, glslang rejects redeclarations of gl_PerVertex. Example vertex shader: 
```
#version 450 core

out gl_PerVertex {
	vec4 gl_Position;
};

void main() {
	gl_Position = vec4(0);
}
```

This produces:
```
ERROR: a.vert:3: 'location' : SPIR-V requires location for user input/output 
ERROR: 1 compilation errors.  No code generated.


ERROR: Linking vertex stage: Missing entry point: Each stage requires one entry point
```

This is nonsense -- the builtin block is not user input/output.

**Comment by johnkslang** [comment]
Sorry about that @chrisforbes.

Using `--aml` or `shader.setAutoMapLocations(true)` will help work around these, until we get them all fixed.  (This was definitely a big backward-incompatible hammer; rejecting many shaders that used to be accepted, so quite the opposite of normal forward progress.)

I will beef up testing and look at fixing this.

**Comment by johnkslang** [comment]
Code was protecting against built-ins, but for this built-in-block redeclaration, the block is not marked as built-in, only the members are.  Fix is coming.

**Comment by chrisforbes** [comment]
Thanks for sorting this out so quickly. I'll test tomorrow and hopefully we
can roll the version the layers use forward rather than reverting.
