### ISSUE TITLE
HLSL: Arrays between shader stages

### ISSUE THREAD

**Issue by chaoticbob** [KhronosGroup/glslang#906]
Just a simple question :)

How does glslang currently handle packing/offsets for fields of structs that get passed between shader stages, e.g. vertex to frag? Curious about fields that are arrays in particular. In the shader below, if the ```Unused``` field is removed, the results in Vulkan look incorrect. With the ```Unused``` field, the D3D12 and Vulkan outputs look identical.

````C++
struct VSOutput {
  float4 Position      : SV_POSITION;
  float2 TexCoord      : TEXCOORD;

  // Without this, Vulkan seems to get the wrong values in 
  // pixel shader for ColorScale.
  float2 Unused        : PADDING;

  float  ColorScale[4] : COLOR_SCALE;
};

VSOutput VSMain(float4 Position : POSITION, float2 TexCoord : TEXCOORD0)
{
  VSOutput result;
  result.Position = Position;
  result.TexCoord = TexCoord;
  result.ColorScale[0] = 1.0f;
  result.ColorScale[1] = 1.0f;
  result.ColorScale[2] = 1.5f;
  result.ColorScale[3] = 1.0f;
  return result;
}

Texture2D uTex0 : register(t0);
SamplerState uSampler0 : register(s1);

float4 PSMain(VSOutput input) : SV_TARGET
{
  float4 colorScale = float4(input.ColorScale[0], input.ColorScale[1], input.ColorScale[2], input.ColorScale[3]);
  return uTex0.Sample(uSampler0, input.TexCoord) * colorScale;
}
````

**Comment by johnkslang** [comment]
The documentation is quite lacking for subtleties in the packing rules.  Glslang currently uses the GLSL rules (quite explicit, for all cases) modified with the DX relaxation of allowing vec2 and vec3 in any location that does not cross a vec4 boundary. What that means for nested types (types inside arrays and structs) is not clear.

I'll look at using this as an example to refine the rules.

**Comment by johnkslang** [comment]
Update: You must be talking about locations in in/out?  (I accidentally misinterpreted from the talk of packing/offset that this was about uniform buffers.)

**Comment by chaoticbob** [comment]
Hi John - Yes. My apologies if my initial wording was unclear. I looked at the HLSL flags and I couldn't find one that matched with the issue. I tried what I thought would affect it, but it didn't seem to.

**Comment by johnkslang** [comment]
The location assignments to in/out is automatic and should work correctly by default.  We'll look into it.

**Comment by LoopDawg** [comment]
@chaoticbob,

Does it change the behavior you see if you move the Position element of the VSOutput struct to the last member, like so?
```

struct VSOutput {
    float2 TexCoord      : TEXCOORD;

    // Without this, Vulkan seems to get the wrong values in 
    // pixel shader for ColorScale.
    // float2 Unused        : PADDING;

    float  ColorScale[4] : COLOR_SCALE;

    float4 Position      : SV_POSITION;
};
```

I have no expectation either way, but knowing that would help to rule a slightly complex piece of code in, or out, as a potential culprit.

**Comment by chaoticbob** [comment]
This looks like it may be an AMD driver bug.  I didn't have a chance to test on an NVIDIA card until today. 

@LoopDawg the variation you suggested still produced the issue on AMD, however it did inspire me to try moving the fields around - and this variation does the right thing:
````c++
struct VSOutput {
  float4 Position      : SV_POSITION;
  float2 TexCoord      : TEXCOORD;
  float  ColorScale[4] : COLOR_SCALE;
  float2 Unused        : PADDING; // Without this, Vulkan result will look wrong
};

````

**Comment by chaoticbob** [comment]
After more testing, this is an AMD driver bug.
