### ISSUE TITLE
[SPIR-V] Remove shadowed "param" variables when possible

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#91]
For purposes of readability and potentially performance, it would be nice to avoid the shadowed "params" variable where appropriate.

Typical code-gen when passing simple in arguments to functions get first copyed to a separate variable (via OpStore).

```
#version 310 es

vec4 foo(float v)
{
    return vec4(v);
}

void main()
{
    float v = 10.0;
    gl_Position = foo(v);
}
```

Compiles into

```
         4(main):           2 Function None 3
               5:             Label
           16(v):      7(ptr) Variable Function
       23(param):      7(ptr) Variable Function
                              Store 16(v) 17
              24:    6(float) Load 16(v)
                              Store 23(param) 24
              25:    8(fvec4) FunctionCall 11(foo(f1;) 23(param)
              27:     26(ptr) AccessChain 20 22
                              Store 27 25
                              Return
                              FunctionEnd
```

There is no need for this param variable, and it only adds clutter when disassembling and reading the SPIR-V.

For out/inout arguments, param shadowing makes more sense though due to GLSL's weird semantics with out/inout arguments.

**Comment by johnkslang** [comment]
Agreed.  This is presenting a basic read/write through memory model for all accesses.  A broad improvement that eliminates this in a variety of places would be quite useful.  It would likely help that to not needlessly generate the accesses to begin with, but on the other hand if a simple generic algorithm catches them all, that might be okay too.

Generally, the strategy here is to complete the functionality, followed by improving the emitted code.  Discussion is welcome.

**Comment by Themaister** [comment]
Does SPIR-V support non-variable types being passed in as OpFunctionParameter? I cannot see any reference to where it must be backed by an OpVariable at least.

**Comment by johnkslang** [comment]
Yes, no problem passing an intermediate object to an OpFunctionParameter.

**Comment by johnkslang** [comment]
Couple notes here:

1. Even with a pure `in` argument, the argument can be written to, and that write does not change the variable that was passed in. So, there really are (semantically) two objects, hence a param allocation.

2. It is now pretty clear we want glslang to focus on correct semantic translation and https://github.com/KhronosGroup/SPIRV-Tools to focus on optimization. So, I expect elimination of an unwritten to shadow to occur there.
