### ISSUE TITLE
HLSL: multiple initializers in for loop fails to parse

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#919]
The for loop in the following HLSL demonstrates the issue (glslang master built to commit e00e8f45a60adb7fd2a84c6f6b608372a5398014)
```
struct VS_INPUT 
{ 
    float3 vPositionOs : POSITION;
}; 
struct PS_INPUT 
{ 
    float4 vOutputPositionPs : SV_Position;
    
}; 
PS_INPUT MainVs ( const VS_INPUT i ) 
{ 
    PS_INPUT o; 
    
	int foo = 3;
	for ( int i = 0, count = int( foo ); i < count; i++ )
	{
		o.vOutputPositionPs.xyzw = float4( i.vPositionOs.xyz, 1.0 );
	}
    
    return o;
} 
```
glslangValidator produces the following errors:

ERROR: test_vs.hlsl:17: 'count' : unknown variable
ERROR: test_vs.hlsl:17: 'assignment expression' : Expected
ERROR: test_vs.hlsl:17: 'assignment expression' : Expected
ERROR: test_vs.hlsl:17: 'initializer' : Expected
ERROR: test_vs.hlsl:17: ';' : Expected
ERROR: test_vs.hlsl:17: ';' : Expected
ERROR: test_vs.hlsl:17: ')' : Expected
ERROR: test_vs.hlsl:17: 'for sub-statement' : Expected
test_vs.hlsl(17): error at column 22, HLSL parsing failed.

**Comment by johnkslang** [comment]
Indeed, the current parser only accepts one declared variable in control flow productions, not an arbitrary list.  I'll look at adding the arbitrary list

**Comment by johnkslang** [comment]
Update: for-init-statements are arbitrary declarations, unlike the init-statements for `if`, `while` and `do-while`.  Should be fixed now.
