### ISSUE TITLE
Add additional #include support to StandAlone via command-line option

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#921]
It would be very useful if glslangValidator had an option like fxc /I <include> to include additional directories now that includes are supported.

**Comment by johnkslang** [comment]
This was on the tip of my fingers anyway.  To verify semantics:

For "local" search paths, the order of search will be:
1. the directory of the includer, generalizing to the active stack of directories leading up to that include
2. the command-line `-I` directories, in left-to-right order.

(For library form, there is an includer method: `DirStackFileIncluder::pushExternalLocalDirectory()`.)
