### ISSUE TITLE
HLSL: Assigning scalar to matrix allowed by fxc, but not glslangValidator

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#923]
fxc allows assignment of a matrix to a scalar, but this is not supported glslangValidator.  See shader for examples:

```
float4 main() : SV_TARGET
{
    /// Case 1
    float4x4 mat1 = 0.0;                                                 // Works in fxc. glslangValidator gives ERROR: mini_test_shader.cg:8: '=' :  cannot convert from ' const float' to ' temp 4X4 matrix of float'
    float4x4 mat2 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};    // Works in fxc and glslangValidator
    float4x4 mat3 = (float4x4)0.0;                                       // Works in fxc and glslangValidator

    /// Case 2
    float4x4 mat4;
    mat4 = 0.0;                                                         // Works in fxc and glslangValidator gives ERROR: mini_test_shader.cg:14: '' : could not create assignment
    mat4 = float4x4(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);    // Works in fxc and glslangValidator
    mat4 = (float4x4)0.0;                                               // Works in fxc and glslangValidator
   
    float4 f4 = 0.0;                                                    // Works in fxc and glslangValidator

    return f4;
}
```

**Comment by LoopDawg** [comment]
```mat4 = (float4x4)0.0;                                               // Works in fxc and glslangValidator```

It parses, but I'm not so sure the semantics are right.  In HLSL it should replicate the scalar to every component of the matrix, whereas glslang is setting the diagonal.  (E.g, if the constant were 0.5 instead of 0.0, say).

**Comment by johnkslang** [comment]
> it should replicate the scalar to every component of the matrix

Note that for non-zero, that's a pretty nonsensical matrix, unless it gets used in a non-matrix like way.

This should be fixed but, for priority setting, might want to know if there need for this for non-zero values?

Will certainly look at supporting the direct assignment case.
