### ISSUE TITLE
HLSL: Casting float vector arrays supported by fxc, but not glslangValidator

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#924]
fxc allows casting between float vector arrays as long as they have the same number of elements, but glslangValidator does not.  See shader for example:

```
float4 main() :  SV_TARGET 
{
    float4 float4_array[4]; // 16 floats

    // Casting same number of floats to a different vector/array size combo
    float2 float2_array_times2[8] = (float2[8])float4_array; // Fails in glslangValidator ERROR: 'expression' : Expected and ERROR: 'initializer' : Expected

    return (float4)0.0;
}
```

**Comment by johnkslang** [comment]
Glslang wasn't yet supporting array-type cast syntax. Adding that now.

HLSL actually allows this when the component types are different as well as when the converted type has more elements than the cast type.  I'll include conversions for that as well.
