### ISSUE TITLE
OpEntryPoint is missing references to uniforms

### ISSUE THREAD

**Issue by warp-10** [KhronosGroup/glslang#927]
Fragment shader:

    #version 450

    layout(input_attachment_index = 1, set = 0, binding = 0) uniform subpassInput blendInput;

    layout(location = 0) in vec4 color;
    layout(location = 0) out vec4 fragColor;

    void main()
    {
        fragColor = (subpassLoad(blendInput) + color)*0.5;
    }

Disassembly from spirv-dis.exe:

    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 1
    ; Bound: 25
    ; Schema: 0
                   OpCapability Shader
                   OpCapability InputAttachment
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Fragment %main "main" %fragColor %color
                   OpExecutionMode %main OriginUpperLeft
                   OpSource GLSL 450
                   OpName %main "main"
                   OpName %fragColor "fragColor"
                   OpName %blendInput "blendInput"
                   OpName %color "color"
                   OpDecorate %fragColor Location 0
                   OpDecorate %blendInput DescriptorSet 0
                   OpDecorate %blendInput Binding 0
                   OpDecorate %blendInput InputAttachmentIndex 1
                   OpDecorate %color Location 0
           %void = OpTypeVoid
              %3 = OpTypeFunction %void
          %float = OpTypeFloat 32
        %v4float = OpTypeVector %float 4
    %_ptr_Output_v4float = OpTypePointer Output %v4float
      %fragColor = OpVariable %_ptr_Output_v4float Output
             %10 = OpTypeImage %float SubpassData 0 0 0 2 Unknown
    %_ptr_UniformConstant_10 = OpTypePointer UniformConstant %10
     %blendInput = OpVariable %_ptr_UniformConstant_10 UniformConstant
            %int = OpTypeInt 32 1
          %int_0 = OpConstant %int 0
          %v2int = OpTypeVector %int 2
             %17 = OpConstantComposite %v2int %int_0 %int_0
    %_ptr_Input_v4float = OpTypePointer Input %v4float
          %color = OpVariable %_ptr_Input_v4float Input
      %float_0_5 = OpConstant %float 0.5
           %main = OpFunction %void None %3
              %5 = OpLabel
             %13 = OpLoad %10 %blendInput
             %18 = OpImageRead %v4float %13 %17
             %21 = OpLoad %v4float %color
             %22 = OpFAdd %v4float %18 %21
             %24 = OpVectorTimesScalar %v4float %22 %float_0_5
                   OpStore %fragColor %24
                   OpReturn
                   OpFunctionEnd

Note that only `OpEntryPoint`, which references `subpassInput blendInput`, does not list the corresponding ID.

From the spec (dated March 15 2017):

> Interface is a list of <id> of global OpVariable instructions with either Input or Output for its Storage Class operand. These declare the input/output interface of the entry point. They could be a subset of the input/output declarations of the module, and a superset of those referenced by the entry point’s static call tree. **It is invalid for the entry point’s static call tree to reference such an &lt;id&gt; if it was not listed with this instruction.**

Emphasis mine.

Though it does not appear to be explicitly required, without listing other _implied_ inputs, such as `subpassInput` and other uniforms, the application must still perform static analysis on the code, making `OpEntryPoint` nearly useless for the purposes of validating linkage between two modules.

However, I'm not entirely sure if this is an API issue, or really a problem with glslangValidator.

**Comment by johnkslang** [comment]
The intent of the specification is to list only the input and output storage class interface. Glslang is faithfully following what the specifications require.  It would be invalid to change it to include uniform storage class-like objects on OpEntryPoint.

I won't go into rationale here, but do note that the linkage between two modules is indeed defined by input/output storage, and not by uniform storage.  Uniform storage forms part of the linkage between the application and a module.

If you think the specifications are in error, can you file instead against the SPIR-V specification?  See issues in https://github.com/KhronosGroup/SPIRV-Headers. Thanks.
