### ISSUE TITLE
Incorrect SPIR-V code generation for gl_SubGroup*MaskARB

### ISSUE THREAD

**Issue by cwabbott0** [KhronosGroup/glslang#930]
When enabling GL_ARB_shader_ballot, glslang generates SPIR-V like this:

    OpDecorate %gl_SubGroupEqMaskARB BuiltIn SubgroupEqMaskKHR
    // ...
    %ulong = OpTypeInt 64 0
    // ...
    %_ptr_Input_ulong = OpTypePointer Input %ulong
    %gl_SubGroupEqMaskARB = OpVariable %_ptr_Input_ulong Input

So it declares the SubgroupEqMaskKHR builtin variable as a single-component 64-bit integer, even though the SPV_KHR_shader_ballot spec says that it's supposed to be a 4-component 32-bit integer. There's a similar issue for all the other Subgroup*MaskKHR builtins.

**Comment by alan-baker** [comment]
This came up in https://github.com/KhronosGroup/SPIRV-Tools/pull/2637 too.
