### ISSUE TITLE
Incorrect code generation for dynamic arrays

### ISSUE THREAD

**Issue by warp-10** [KhronosGroup/glslang#934]
# EDIT:

Pass the following with -V to glslangValidator (as a fragment shader):

    #version 450

    layout(set = 0, binding = 0) uniform ValueBlock
    {
        float value;
        float moreValues[];
    } valueBlock;

    layout(location = 0) out vec4 color;

    void main()
    {
        color = vec4(1,1,1,1) * valueBlock.moreValues[8];
    }

After disassembly, one can observe the following is present in the output:

    %_runtimearr_float = OpTypeRuntimeArray %float
    %ValueBlock = OpTypeStruct %float %_runtimearr_float
    %_ptr_Uniform_ValueBlock = OpTypePointer Uniform %ValueBlock
    %valueBlock = OpVariable %_ptr_Uniform_ValueBlock Uniform

It's now my understanding that uniform blocks can't have runtime arrays (why?), and that the size is determined by the compiler.

The above disassembly indicates the last member is a runtime array, so the size is not known where it could have been determined by the compiler.

# OLD VERSION

Code (fragment shader):

    #version 450

    layout(set = 1, binding = 0) uniform ValueBlock
    {
        float value;
        float moreValues[]; // dynamic!
    } valueBlock;

    layout(location = 0) in vec4 color;
    layout(location = 0) out vec4 fragColor;

    void main()
    {
        fragColor = color * valueBlock.value;
    }

Relevant disassembly snippet:

                 %uint = OpTypeInt 32 0
               %uint_1 = OpConstant %uint 1
    ; should be "%_runtimearr_float = OpTypeRuntimeArray %float"
    %_arr_float_uint_1 = OpTypeArray %float %uint_1
           %ValueBlock = OpTypeStruct %float %_arr_float_uint_1

Note: It works correctly for buffer blocks.

Maybe I'm wrong to assume this should work for uniform blocks? If not, an error would be nice.

**Comment by johnkslang** [comment]
Actually, that's not a dynamic array, it is implicitly sized.  It will have a static size assigned, base on how it is used.  Presumably, if you'd actually indexed it with a dynamic index, you would have gotten an error.  For that, I get:

> ERROR: '[' :  array must be redeclared with a size before being indexed with a variable

If you only index with compile-time constants, those will size the array to a compile-time size.  Note it would be unusual to want a dynamic array indexed with only constants.

**Comment by warp-10** [comment]
That is the same code passed to the most recent glslangValidator. It does not generate an error.

The other thing I'm wondering about, then, is: What do these correspond to?
- VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC
- VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC

I was assuming that, since "buffer" is just a decoration, it would just mean I'd choose between those descriptor types based on its presence (and whether or not the last member is a runtime array).

**Comment by johnkslang** [comment]
> That is the same code passed to the most recent glslangValidator. It does not generate an error.

There is nothing wrong with your example code. It just requests an array of size 1, because it has no use. It does not request a dynamic array.  (The dynamic bits are only in your comments.)  You cannot have a dynamic array in a `uniform` block.

Vulkan says

> `OpTypeRuntimeArray` must only be used for the last member of an `OpTypeStruct` that is in the `Uniform` storage class and is decorated as `BufferBlock`.

So, I agree it is odd that there are both storage and uniform `BUFFER_DYNAMIC` descriptor types.

**Comment by warp-10** [comment]
OK, so I tried this:

    layout(set = 1, binding = 0) uniform ValueBlock
    {
        float value;
        float moreValues[]; // dynamic!
    } valueBlock;

    layout(location = 0) in vec4 color;
    layout(location = 0) out vec4 fragColor;

    void main()
    {
        fragColor = color * valueBlock.moveValues[5];
    }

And it generates this:

    %_runtimearr_float = OpTypeRuntimeArray %float
    %ValueBlock = OpTypeStruct %float %_runtimearr_float
    %_ptr_Uniform_ValueBlock = OpTypePointer Uniform %ValueBlock
    %valueBlock = OpVariable %_ptr_Uniform_ValueBlock Uniform

**Comment by johnkslang** [comment]
That example doesn't compile, has a typo for `moreValues`. I can get a runtime array be fixing that typo and changing uniform -> buffer.

**Comment by warp-10** [comment]
After trying the example again, and also with several different combinations of other things, it still builds for me.

I'm using the debug build of glslangValidator (pulled @ 8am today), if that makes any difference.

I just left defaults in the config when generating a VS2015 solution.

**Comment by johnkslang** [comment]
Perhaps you can give the complete shader and command line options.  As it stands, it defaults to ES, which does not support implicitly-sized arrays (but does support dynamically sized).  It really needs a `#version`.

**Comment by warp-10** [comment]
I've been using #version, this is just a complaint about formatting on github (I don't feel like looking up ASCII codes for a trivial character).

I've been using version 450, with only the -V option.

**Comment by johnkslang** [comment]
I edited https://github.com/KhronosGroup/glslang/issues/934#issuecomment-307917020 to bracket the code; you can look and see how to do it from that.

**Comment by warp-10** [comment]
Great. Github issues aside. I've updated the code for the umpteenth time. The problem still remains.

From what I've gotten so far, it could be one of the following:

- Uniforms actually **can** have runtime arrays, and it is incorrectly generating a constant-1 sized array
- Uniforms **can't** have runtime arrays, and it is incorrectly generating a runtime array when a constant index is used (are we expected to transform `OpTypeRuntimeArray` into `OpTypeArray` in this case?)
- I'm accidentally using an ancient dialect of English that nobody can understand.

**Comment by johnkslang** [comment]
Very mysterious, I don't know how this is happening.  Could you post your full SPIR-V?

Notes:

1) This part of glslang has not changed recently. The path to get a SPIR-V **OpRunTimeArray** is quite linear in glslang, requiring an AST storage type of `EvqBuffer`, which only comes from a GLSL `buffer`.

2) If I compile the following, as a fragment shader `t.frag`:

```
#version 450

layout(set = 0, binding = 0) uniform ValueBlock
{
    float value;
    float moreValues[];
} valueBlock;

layout(location = 0) out vec4 color;

void main()
{
    color = vec4(1,1,1,1) * valueBlock.moreValues[8];
}
```

Using `glslangValidator -V t.frag &&  spirv-dis frag.spv`, I get this SPIR-V:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 1
; Bound: 25
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %main "main" %color
               OpExecutionMode %main OriginUpperLeft
               OpSource GLSL 450
               OpName %main "main"
               OpName %color "color"
               OpName %ValueBlock "ValueBlock"
               OpMemberName %ValueBlock 0 "value"
               OpMemberName %ValueBlock 1 "moreValues"
               OpMemberName %ValueBlock 2 "a"
               OpName %valueBlock "valueBlock"
               OpDecorate %color Location 0
               OpDecorate %_arr_float_uint_1 ArrayStride 16
               OpMemberDecorate %ValueBlock 0 Offset 0
               OpMemberDecorate %ValueBlock 1 Offset 16
               OpMemberDecorate %ValueBlock 2 Offset 32
               OpDecorate %ValueBlock Block
               OpDecorate %valueBlock DescriptorSet 0
               OpDecorate %valueBlock Binding 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Output_v4float = OpTypePointer Output %v4float
      %color = OpVariable %_ptr_Output_v4float Output
    %float_1 = OpConstant %float 1
         %11 = OpConstantComposite %v4float %float_1 %float_1 %float_1 %float_1
       %uint = OpTypeInt 32 0
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
 %ValueBlock = OpTypeStruct %float %_arr_float_uint_1 %float
%_ptr_Uniform_ValueBlock = OpTypePointer Uniform %ValueBlock
 %valueBlock = OpVariable %_ptr_Uniform_ValueBlock Uniform
        %int = OpTypeInt 32 1
      %int_1 = OpConstant %int 1
      %int_8 = OpConstant %int 8
%_ptr_Uniform_float = OpTypePointer Uniform %float
       %main = OpFunction %void None %3
          %5 = OpLabel
         %22 = OpAccessChain %_ptr_Uniform_float %valueBlock %int_1 %int_8
         %23 = OpLoad %float %22
         %24 = OpVectorTimesScalar %v4float %11 %23
               OpStore %color %24
               OpReturn
               OpFunctionEnd
```

**Comment by warp-10** [comment]
So, this is another occasion notepad++ has made me look like an ass. Despite asking to re-load the disassembly every time, nothing apparently changed until after a restart.

Sorry for the trouble.

The specific problem I highlighted isn't an issue, then. What remains is bounds-checking on the array, which now always has a size of 1.

**Comment by chrisforbes** [comment]
From a couple days ago-- the dynamic descriptor types don't really have anything to do with your dynamic array sizing case.

**Comment by johnkslang** [comment]
I opened #938 for the implicit array-size issue, fully closing out this one.
