### ISSUE TITLE
Support for 3 new Nvidia Vulkan beta driver extensions?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/glslang#935]
Hi,
recently NV posted 382.58 driver with 3 new extensions which seem to be exposing features already exposed on his OpenGL driver also via GL extensions:
VK_EXT_sampler_filter_minmax 
VK_NV_fill_rectangle 
VK_NV_fragment_coverage_to_color 
any support in GLSLang?

**Comment by TiemoJung** [comment]
Those extensions don't need any support by GLSlang. They add nothing to shaders.
VK_EXT_sampler_filter_minmax - adds new filter modes for samplers
VK_NV_fill_rectangle - new polygon mode that creates a rectangle out of a axis aligned bounding box of the rendered triangle
VK_NV_fragment_coverage_to_color - lets you reroute the coverage mask into a output color

**Comment by oscarbg** [comment]
Thanks..
was asking before even knowing if will affect shader code.. 
seems two new 
VK_EXT_blend_operation_advanced 
VK_NV_framebuffer_mixed_samples 
also don't need it ..
so thanks.. 👍

**Comment by oscarbg** [comment]
Thanks..
was asking before even knowing if will affect shader code..
seems two new
VK_EXT_blend_operation_advanced
VK_NV_framebuffer_mixed_samples
also don't need it ..
so thanks.. 👍
