### ISSUE TITLE
Generating invalid OpArrayLength instructions

### ISSUE THREAD

**Issue by aarongreig** [KhronosGroup/glslang#936]
I have found that this shader
```
#version 450

layout(set=0, binding=0) buffer block{
    int[] a;
    float b;
};

void main(){
    int result = a.length();
}
```
generates this SPIR-V, without raising any warnings or errors
```
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 1
; Bound: 15
; Schema: 0
               OpCapability Shader
     %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
               OpName %result "result"
               OpName %block "block"
               OpMemberName %block 0 "a"
               OpMemberName %block 1 "b"
               OpName %_ ""
               OpDecorate %_runtimearr_int ArrayStride 4
               OpMemberDecorate %block 0 Offset 0
               OpMemberDecorate %block 1 Offset 0
               OpDecorate %block BufferBlock
               OpDecorate %_ DescriptorSet 0
               OpDecorate %_ Binding 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
%_ptr_Function_int = OpTypePointer Function %int
%_runtimearr_int = OpTypeRuntimeArray %int
      %float = OpTypeFloat 32
      %block = OpTypeStruct %_runtimearr_int %float
%_ptr_Uniform_block = OpTypePointer Uniform %block
          %_ = OpVariable %_ptr_Uniform_block Uniform
       %main = OpFunction %void None %3
          %5 = OpLabel
     %result = OpVariable %_ptr_Function_int Function
         %14 = OpArrayLength %int %_ 0
               OpStore %result %14
               OpReturn
               OpFunctionEnd
```
more specifically it generates this instruction: 
`%14 = OpArrayLength %int %_ 0`
but [the spec](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpArrayLength) says:

> Structure must have a type of OpTypeStruct whose **last** member is a run-time array.
> 
> Array member is the **last member number** of Structure and must have a type from OpTypeRuntimeArray.

I haven't dug far enough into the glsl spec to see if the shader itself is valid, but either way attempting to compile it should do something other than silently generating invalid SPIR-V.

**Comment by johnkslang** [comment]
Glslang certainly has code to enforce that runtime arrays are only the last member, and that other unsized array syntax gets implicitly sized at (offline) shader link time. Will look to see why this is getting through.

Note #938 captures a problem with implicitly-sized (not run-time sized) arrays as block members.

**Comment by johnkslang** [comment]
A while back, unsized arrays were refactored, and the specification was also clarified (soon to be released) about using `.length()` on an unsized array that is neither runtime sized nor explicitly sized. Glslang now generates this error message:

```
ERROR: t.vert:9: 'length' :  array must be declared with a size before using this method
```
