### ISSUE TITLE
shaderc will not compile glslang master

### ISSUE THREAD

**Issue by janesma** [KhronosGroup/glslang#945]
54596ff99e93e6f4205af81c337da56cc95587f2
Author:     John Kessenich <cepheus@frii.com>
HLSL: Force flat (nointerp) onto integer fragment inputs.
Addresses #940.

glslang/Include/../Include/Types.h:1343:16: error: enumeration value ‘EbtVoid’ not handled in switch [-Werror=switch]
02:27:07          switch (basicType) {

**Comment by johnkslang** [comment]
Should be fixed by be1085cb883f9cfb332a5266cf407e608df783e4.
