### ISSUE TITLE
ClipDistance decoration applied to scalar from HLSL shader

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/glslang#946]
This short HLSL vertex shader

```hlsl
// glslangValidator -e main -S vert -D -V test.hlsl -o test.spv

void main(out float4 pos : SV_Position, out float clip : SV_ClipDistance)
{
	pos = 1.0f.xxxx;
	clip = 0.5f;
}
```

Produces SPIR-V that applies the ClipDistance to a scalar float output variable:

```asm
      %float = OpTypeFloat 32
%_ptr_Output_float = OpTypePointer Output %float
     %clip_1 = OpVariable %_ptr_Output_float Output
```

But the SPIR-V spec says:

> **ClipDistance**
> _Array_ of clip distances. See Vulkan or OpenGL API specifications for more detail.

And Vulkan's spec says even more explicitly:

> Any variable decorated with `ClipDistance` **must** be declared as an array of 32-bit floating-point values.

So I think any/all ClipDistance outputs from HLSL should this be turned into an implicit array output?

**Comment by LoopDawg** [comment]
There is some code doing a similar(ish) thing for tessellation level builtins (HlslParseContext::fixBuiltInIoType), with some TODO comments about handling clip distance and cull distance.

If I'm reading the HLSL documentation correctly, it seems multiple clip distances can be packed into components of registers, per: _"Multiple clip planes can be implemented simultaneously, by declaring multiple component(s) of one or more vertex elements as the SV_ClipDistance."_  I guess it means something like this?

```
void main(out float4 pos : SV_Position, out float2 clip[2] : SV_ClipDistance)
{
    pos = 1.0f.xxxx;
    clip[0].x = 0.5f;
    clip[0].y = 0.6f;

    clip[1].x = 0.7f;
    clip[1].y = 0.8f;
}
```

Does that match your understanding around multiple clip / cull distance values?  There is some plumbing missing to unpack that into the array of floats expected by SPIR-V.  I could try to add it, although I'm not entirely clear about the rules.  E.g, do the values 0.5 .. 0.8 above become sequential in the clip distance array?  Is the above code a synonym for an array of 4 float (not float2) set with the same values?

**Comment by baldurk** [comment]
I don't honestly know myself, I'd need to leave that for someone with an understanding of how multiple clip distances are declared in HLSL. This wasn't my shader where I encountered it - I was doing some SPIR-V patching/modification and ended up running into an issue where the source SPIR-V seemed to come from something like this.

**Comment by LoopDawg** [comment]
It seems there is yet another possible dimension: the semantic numeric suffix.  So maybe there are 3 (??) things, which is two more than I like :-).  There's a WIP PR to handle two of the dimensions, possibly correctly, and possibly incorrectly.  Hopefully someone might pop in and offer some insights.

The PR should handle the first case posted by @baldurk of a non-array scalar member.  This will be copied to the 0th element of a size one SPIR-V array.

If there are vectors in the shader declaration (ala float2 clip : SV_ClipDistance), or it is an array of scalars, or it is an array of vectors, then each component of each array element in turn will be copied to a sequential location in the SPIR-V output array, with vector being the inner dimension and array the outer dimension.  I do not know for certain that is correct.  We can tweak the behavior easily enough, and add handling of the semantic's ID, once I know how they should all relate.

There also needs to be testing that this plays nicely with splitting builtin members out of mixed user+builtin structures, which I will work on.  That may or may not happen correctly as it sits.  I've only exercised it with "loose" entry point parameters.

**Comment by danginsburg** [comment]
We are also hitting this problem which is causing a crash on a driver with a shader that outputs SV_ClipDistance0 only.  The IHV confirmed that the problem is ClipDistance being a scalar rather than an array.

**Comment by LoopDawg** [comment]
OK.  I have some pending code to handle mixed uservar+clipdistance interface structures (that is not pushed to the PR yet - will do so in a while), and then I'm inclined to remove the WIP.  The code does not yet handle the SV_ClipDistance**N** axis, but that can be added in its own PR so the current cases which don't need that axis can start working sooner.  I'll make a PR for the semantic axis after that.
