### ISSUE TITLE
How to define user-defined macro before parsing a shader

### ISSUE THREAD

**Issue by Joojooo** [KhronosGroup/glslang#949]
Hi,
Is there a way to set some user-defined macro in the TPpContext class **before** parsing a shader?

For example if a shader defines:
#ifndef USER_DEFINED_MACRO
//default value
#define USER_DEFINED_MACRO 1
#endif
I'd like to have the possibility to set the value of USER_DEFINED_MACRO before parsing the shader

The TppContext class defines a `addMacroDef(int atom, MacroSymbol& macroDef)` function, but we can't call this function without knowing the MACRO atom ID

Thanks

**Comment by johnkslang** [comment]
I don't imagine you'd want to mess with the actual preprocessor just to set a macro.

The command line has `-D` and `-U`, so you could say `-DUSER_DEFINED_MACRO` or, e.g., `-DUSER_DEFINED_MACRO=3`.

The library form takes a user preamble. You can pass in the string `#define USER_DEFINED_MACRO\n` or whatever you want.  See `TShader::setPreamble`.  (In the C-form, the `preamble` or `customPreamble` parameters to `ProcessDeferred` or `CompileDeferred`.

Even internally, the preferred way is to set up a system preamble in Versions.cpp `TParseVersions::getPreamble` which is how virtually all the built-in GL_ macros etc. get set.

**Comment by Joojooo** [comment]
Thanks for your reply.

I didn't know about preamble, will check more about this.

A few points I noticed;
- In the command line: usage defines -D as: "-D      input is HLSL\n", I cannot see an option about preamble, or perhaps we just add those macros as another input?
- In PpContext.h, setPreamble function has no definition, is it normal?
- in "TParseVersions::getPreamble(std::string& preamble)", the preamble is hardcoded, with apparently no possibility to add user-defined macro?

**Comment by johnkslang** [comment]
You should see all these for the command line:

```
  -D          input is HLSL
  -D<macro=def>
  -D<macro>   define a pre-processor macro
```

This functionality is actively working.  The `getPreamble()` you refer to is the system-provided preamble, not the one I described the user can pass in.

**Comment by Joojooo** [comment]
Got it, my version was a few weeks behind (-D for preprocessor macros has been pushed on June 15th)
Thanks for the support
