### ISSUE TITLE
HLSL: support SV_(Clip/Cull)DistanceN for N>0

### ISSUE THREAD

**Issue by LoopDawg** [KhronosGroup/glslang#951]
PR #947 has support for handling some varieties of HLSL clip and cull distance syntax.  HLSL allows values in: vectors, arrays, and semantic IDs, whereas SPIR-V requires a 1D array of scalar floats.

The following appears to be a valid construct which mixes the vector dimension and the semantic ID dimension:

```
struct PS_INPUT 
{ 
    float3 clip0 : SV_ClipDistance0;
    float3 clip1 : SV_ClipDistance1;
}; 
```

I think the separate clip0 and clip1 structure member values should be merged into the single SPIR-V clipdistance output array (because where else would they go?)  The intended semantics are a little unclear though.  Does anyone know this?  I guess that the above (once you write to all the components) should produce the 6 consecutive clip distance values in array elements [0..5], but I can imagine other possibilities such as 8 values with indexes 3 and 7 being implicitly 0, and indexes 0,1,2,4,5,6 are the values the shader wrote.

**Comment by johnkslang** [comment]
I think if you look at the `Index`, `Mask`, and `Register` columns, it answers this question.

Specifically, it packs, for example, a float and a float2 into one register (note the yz):

```
 Name                 Index   Mask Register SysValue  Format   Used
 -------------------- ----- ------ -------- -------- ------- ------
 SV_ClipDistance          0   x           0  CLIPDST   float   x
 SV_ClipDistance          1    yz         0  CLIPDST   float    yz
```

but it does not pack two float3:

```
Name                 Index   Mask Register SysValue  Format   Used
-------------------- ----- ------ -------- -------- ------- ------
SV_ClipDistance          0   xyz         0  CLIPDST   float   xyz
SV_ClipDistance          1   xyz         1  CLIPDST   float   xyz
```

However, I don't know how the DX API view compares to Vulkan.  But, I'd certainly think the straightforward way would be to have holes in the float3+float3 case and no holes in the float+float2 case.

Also of note, if you try going to `SV_ClipDistance2` it complains about it being out of range, implying that each SV_ClipDistance takes up 4 of the maximum 8 components.

**Comment by LoopDawg** [comment]
Alright; I'll add those packing rules and assume the API would see a hole.

**Comment by LoopDawg** [comment]
Pending as #997; it should be functional for basic cases, although there are known limitations yet.
