### ISSUE TITLE
HLSL: calling function with wrong argument type. (uniform qualifier?)

### ISSUE THREAD

**Issue by xxxbxxx** [KhronosGroup/glslang#952]
Hello,

as noticed by the validtion layer
[SC] Code 5 : SPIR-V module not valid: OpFunctionCall Argument <id> '407's type does not match Function <id> '19's parameter type.

The function call a argument type doesn't match the declaration. 
The function call b is fine.

```
struct S 
{
	float4 v;
};

float func(S s)
{
	return s.v.x;
}

cbuffer 
{
	S	uniform1;
};

float4 main(const float4 p : SV_Position) : SV_Target0
{
	S t = uniform1;
	float a = func(uniform1);
	float b = func(t);

	return float4(a,b,0,1);
}
```

**Comment by xxxbxxx** [comment]
(I guess it's the same as #944)

**Comment by johnkslang** [comment]
closing as duplicate
