### ISSUE TITLE
[SPIR-V] Increments to loop variable ignore signedness

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/glslang#96]
Tried a loop like this where the loop variable is unsigned. However, mismatched signedness is generated in the SPIR-V output.

```
    vec4 idat = in_data[ident];
    for (uint i = 0u; i < 16u; i++)
    {
        idat = mvp * idat;
    }
```

```
              25:             TypeInt 32 1
              26:     25(int) Constant 1
           31(i):      7(ptr) Variable Function
               6:             TypeInt 32 0
               7:             TypePointer Function 6(int)
...
             32:             Label
              35:      6(int) Load 31(i)
              38:    37(bool) ULessThan 35 36
                              LoopMerge 33 32 None
                              BranchConditional 38 34 33
              34:               Label
              41:     40(ptr)   AccessChain 24 39
              42:          20   Load 41
              43:   17(fvec4)   Load 19(idat)
              44:   17(fvec4)   MatrixTimesVector 42 43
                                Store 19(idat) 44
              45:      6(int)   Load 31(i)
              46:      6(int)   IAdd 45 26
                                Store 31(i) 46
                                Branch 32
              33:             Label
```

I am not sure if SPIR-V is lenient enough to support mismatched signedness in operations, but seems like a bug.

**Comment by johnkslang** [comment]
To answer the basic question: It is valid SPIR-V to mix signed and unsigned types for most operations.  Generally, the type of operation (signed vs. unsigned) is encoded in the opcode, not deduced from the type of the operands.  When it matters (e.g., a < b), there are two opcodes, when it doesn't matter (e.g. a + b), there is one opcode.

Leaving open to revisit if something should change anyway for this example.

**Comment by johnkslang** [comment]
Commit referred to wrong issue, reopening.

**Comment by arcady-lunarg** [comment]
@Themaister is this still a problem? If not, we would like to close this issue.

**Comment by ncesario-lunarg** [comment]
Closing due to offline confirmation from @Themaister that this is no longer an issue.
