### ISSUE TITLE
CMake scripts that try to set the POSITION_INDEPENDENT_CODE property are not doing it correctly

### ISSUE THREAD

**Issue by rohith10** [KhronosGroup/glslang#972]
The CMakeLists scripts in the project that try to set the POSITION_INDEPENDENT_CODE property do it like this : set_property(TARGET *target* PROPERTY FOLDER *folder* POSITION_INDEPENDENT_CODE ON)

CMake documentation states that set_property can only be used to set a single property, and everything following the property name will be treated as the value of that property (multiple values will be strung together as a semicolon separated list). As a result, the generated solution in Visual Studio have "folder" filters named *folder*;POSITION_INDEPENDENT_CODE;ON.

I have fixed this in pull request #970.

Also, I'm not sure which compile/link setting in VS (or other compilers) this property maps to. I diffed the project files in question before and after applying my fix, and nothing seems to have changed (apart from the fixed filters). Don't really know what the impact will be on non-VS toolchains.

**Comment by johnkslang** [comment]
I'd seen the symptom show up a while back, but had not tracked it down yet, thanks.  The PR is merged.
