### ISSUE TITLE
[Question] Does auto-map-locations not do anything for GLSL?

### ISSUE THREAD

**Issue by rohith10** [KhronosGroup/glslang#973]
I don't see any functional code associated with the auto-map-locations option for GLSL. The code and comment in TDefaultIoResolverBase::resolveInOutLocation suggest that it's non-functional, so is there a reason why this option is exposed to users?

The HLSL parser has the requisite functionality in HlslParseContext::assignToInterface already. Is it intended for this to be moved to TDefaultIoResolverBase::resolveInOutLocation and for auto-map-locations to be auto-defaulted to on for HLSL?

**Comment by johnkslang** [comment]
HLSL should be doing fine already for location mapping (based on declaration order and/or semantic declaration).

GLSL currently needs locations explicitly declared in the source, or have the current skeletal auto-map-locations fleshed out.  The current utility of auto-map-locations is preservation of a large set of tests that test things other than location, and were written without explicit locations in the shader source.

**Comment by rohith10** [comment]
Okay, so I hacked in the HLSL code from HlslParseContext::assignToInterface in TDefaultIoResolver::resolveInOutLocation to try it for GLSL, and it seems to work fine. So, is this the way to go to get --aml functional (moving that piece of code over to TDefaultIoResolverBase::resolveInOutLocation so that it can be used for both GLSL and HLSL and then auto-defaulting to --aml for HLSL, instead of handling it in HlslParseContext::transformEntryPoint/assignToInterface), or is there some pitfall that I'm not aware of?

**Comment by johnkslang** [comment]
Possible pitfall: How do you know you assigned the same location to the same symbol in two different stages?

Vertex output:

```
out vec4 foo;  // location 0?
out vec2 bar;  // location 1?
```

Fragment input:

```
in vec2 bar;  // location 0?
in vec4 foo;  // location 1?
```

**Comment by rohith10** [comment]
But that would be an issue with the option itself, wouldn't it? As long as the declaration order matches in all the stages, shouldn't this option should be fine for GLSL, as is currently the case for HLSL (glslang doesn't do semantics-based mapping as far as I can tell)?

**Comment by johnkslang** [comment]
Yes. Big assumption that declaration order matches, but if it does, it would work.

If declaration order subtly does not match, it will be hard to debug why the pipeline does not work, and better to tell the authors to explicitly put the locations in the source.  Or, wait until a tool can look at both stages and do per-name assignment of locations.

That is, it could be a disservice to implement such a feature based on declaration order rather than based on seeing both stages.

**Comment by rohith10** [comment]
Okay, got it. Thanks!
