### ISSUE TITLE
Missing TProgram::getUniformBinding()

### ISSUE THREAD

**Issue by RCalocaO** [KhronosGroup/glslang#977]
Dumping the reflection shows this but it's not exposed as a public method so apps can query it.

**Comment by johnkslang** [comment]
Do you have the type (from `getUniformTType` or `getUniformBlockTType`)? I think we're saying you just query the type itself: `type->getQualifier().layoutBinding`  If it's not `TQualifier::layoutBindingEnd`, then that's the binding.

**Comment by johnkslang** [comment]
BTW, the bindingEnd thing is encapsulated:

```
if (type->getQualifier().hasLayoutBinding())
    type->getQualifier().layoutBinding; // binding number
```

**Comment by RCalocaO** [comment]
I tried doing 
`			const auto* Type = Program->getAttributeTType(Index);
			int32 Binding = -1;
			if (Type && Type->getQualifier().hasBinding())
			{
				Binding = Type->getQualifier().layoutBinding;
			}
`

but that doesn't seem to work for samplers, so I had to use the private method.

**Comment by johnkslang** [comment]
Not sure why samplers would be different. But, at a higher level, is this problem solved? Thanks.

**Comment by RCalocaO** [comment]
It's solved by making `TObjectReflection::getBinding()` public and by adding 
```
int TProgram::getUniformBinding(int index) const
{
	return reflection->getUniform(index).getBinding();
}

```

**Comment by johnkslang** [comment]
It looks like the same code to me either way, though I'm not against exposing getUniformBinding(), so I will do that. (Both paths get the type from the TObjectReflection and look at it's TQualifier::layoutBinding, yes?)
