### ISSUE TITLE
HLSL: regression "flattened array with initializer list unsupported" error

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#980]
I just sync'd glslang to master at commit 652db16ff114747c216ec631767dfd27e3d3c838 and hit a regression testing our HLSL shaders.  Here is a stripped down example of a shader that used to parse but no longer works:

```
struct FxaaTex { SamplerState smpl; Texture2D tex; };
SamplerState g_tInputTexture_sampler; Texture2D g_tInputTexture;

float3 FxaaPixelShader( FxaaTex tex )
{
	// stripped
	return float3( 1.0, 1.0, 1.0 );
}

float4 MainPs() : SV_TARGET0
{
	float4 vColor;
	
	FxaaTex tex = { g_tInputTexture_sampler, g_tInputTexture };
	vColor.xyz = FxaaPixelShader( tex );
	vColor.a = 1.0;
	return vColor;
}
```

Produces the following error:
glslangValidator.exe -D -S frag -e MainPs -V test.hlsl
test.hlsl
ERROR: test.hlsl:14: 'tex' : flattened array with initializer list unsupported
test.hlsl(14): error at column 60, HLSL parsing failed.
ERROR: 2 compilation errors.  No code generated.

I don't have an exact commit ID when this regressed.  The last time I had updated in our tree was glslang to commit a1cdd13b

**Comment by rohith10** [comment]
This is the same as #933, introduced by the flatten code fix for #850.

**Comment by danginsburg** [comment]
Looking at the changes for #850 I realized there is a workaround.  If I change:

```
FxaaTex tex = { g_tInputTexture_sampler, g_tInputTexture };
```

to this:

```
FxaaTex tex;
tex.smpl = g_tInputTexture_sampler;
tex.tex = g_tInputTexture;
```

...then it parses fine.  It would seem to me the two statements are equivalent, so is it just a matter of supporting the {} initializer syntax in this case?

**Comment by johnkslang** [comment]
@danginsburg yes, it seems like it should be the case.  Just have to go through the mechanics of it.   The general case is rich hierarchies.  I'm planning this as the next non-trivial glslang I'll do.

**Comment by johnkslang** [comment]
The basic cases should be fixed now. It's all code to throw away once we do this with optimization passes instead of aliasing.

FYI, the initializer path is different than assignment; there are a number of ways these appear the same, but are not. So, I sorted that out, but not necessarily the deep nesting; lets have a new issue for any deep nesting of opaques that must be fixed before we get the optimization-transform solution in place.
