### ISSUE TITLE
HLSL: regressions with global CB

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/glslang#982]
There have been issues introduced with the global CB between commit a1cdd13 and 652db16.  The problems are:

1) The SPIR-V for the global CB now generates it with offsets that require D3D11-style packing.
2) The reflection information does not match the new offsets.

There are several options for fixing:
1) Revert the global CB to using std140 layouts
2) Make the layout it uses optional, generating D3D11-style packing only if requested.  Then also fix the reflection information.

My preference would be to resolve with option 1.  Option 2 (D3D11-style packing) at least can't be the default, because drivers are not required to support D3D11-style packing.

Here is a simple example:

```
float g_flGlobalFloat;
float3 g_vGlobalVec3;

float4 MainPs() : SV_Target0
{
	return float4( g_flGlobalFloat, g_vGlobalVec3 );
}
```

H:\dev\source2\main\src\thirdparty\glslang\build\install\bin>glslangValidator.exe -D -S frag -e MainPs -V -q test2.hlsl
test2.hlsl
Uniform reflection:
g_flGlobalFloat: offset 0, type 1406, size 1, index 0, binding -1
g_vGlobalVec3: offset 16, type 8b51, size 1, index 0, binding -1

Uniform block reflection:
$Global: offset -1, type ffffffff, size 28, index -1, binding -1

Note that g_vGlobalVec3 is reported at offset 16.  However, disassembling the SPIR-V it is actually at offset 4:

```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 1
; Bound: 33
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %MainPs "MainPs" %_entryPointOutput
               OpExecutionMode %MainPs OriginUpperLeft
               OpSource HLSL 500
               OpName %MainPs "MainPs"
               OpName %_MainPs_ "@MainPs("
               OpName %_Global "$Global"
               OpMemberName %_Global 0 "g_flGlobalFloat"
               OpMemberName %_Global 1 "g_vGlobalVec3"
               OpName %_ ""
               OpName %_entryPointOutput "@entryPointOutput"
               OpMemberDecorate %_Global 0 Offset 0
               OpMemberDecorate %_Global 1 Offset 4
               OpDecorate %_Global Block
               OpDecorate %_ DescriptorSet 0
               OpDecorate %_entryPointOutput Location 0
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
          %8 = OpTypeFunction %v4float
    %v3float = OpTypeVector %float 3
    %_Global = OpTypeStruct %float %v3float
%_ptr_Uniform__Global = OpTypePointer Uniform %_Global
          %_ = OpVariable %_ptr_Uniform__Global Uniform
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%_ptr_Uniform_float = OpTypePointer Uniform %float
      %int_1 = OpConstant %int 1
%_ptr_Uniform_v3float = OpTypePointer Uniform %v3float
%_ptr_Output_v4float = OpTypePointer Output %v4float
%_entryPointOutput = OpVariable %_ptr_Output_v4float Output
     %MainPs = OpFunction %void None %3
          %5 = OpLabel
         %32 = OpFunctionCall %v4float %_MainPs_
               OpStore %_entryPointOutput %32
               OpReturn
               OpFunctionEnd
   %_MainPs_ = OpFunction %v4float None %8
         %10 = OpLabel
         %18 = OpAccessChain %_ptr_Uniform_float %_ %int_0
         %19 = OpLoad %float %18
         %22 = OpAccessChain %_ptr_Uniform_v3float %_ %int_1
         %23 = OpLoad %v3float %22
         %24 = OpCompositeExtract %float %23 0
         %25 = OpCompositeExtract %float %23 1
         %26 = OpCompositeExtract %float %23 2
         %27 = OpCompositeConstruct %v4float %19 %24 %25 %26
               OpReturnValue %27
               OpFunctionEnd
```

**Comment by LoopDawg** [comment]
Behavior changed in 7cca140956c4feb02f33473bddf0bfbeb4e2e494.

**Comment by johnkslang** [comment]
Basically understood, but a couple subtleties to check.

1. Is $Global different than other buffers regarding glslang packing tighter? Or, should glslang never be packing tighter automatically (just tolerating it when members are specifically laid out).

1. What distinguished D3D11-style packing from general DX tighter packing over std140?

**Comment by danginsburg** [comment]
Yeah, there is some trickiness here, and some decisions to make as far as behavior.  I will explain our use case first.

1. The global CB is "special" in that we query it for reflection information in order to know the offsets of each active member.  Whereas all other CBs are represented by some C/C++ data structure, the global CB never is, and the code is roughly agnostic to where things are located.

2. For the non global CB, we automatically insert packoffset qualifiers into the CB definition in the HLSL so that the HLSL packing matches what std140 would produce.  There is also a script which generates the C/C++ data structures using std140 rules so they all match up.  This means we can have a single in-memory layout in the engine code that works on any API.

That being said, as far as I can tell, fxc does pack the global CB for D3D11 using the same kind of relaxed layout rules it does for other CBs.  So one possibility here is that if you fix the reflection information then the global CB layout that glslang produces would match fxc.

However, it is expected that any application using the global CB will need to use reflection to know the location of offsets, therefore unlike all other CBs it does not rely on it having a specific in-memory layout.  AND, since currently drivers do not accept DX11-style packing (or at least, are not guaranteed to), I don't think it makes sense to pack this way by default for the global CB.

On the other hand, packing regular CBs by regular DX11-style packing rules probably does make sense in some cases (once it can be relied upon that drivers will support this).  It seems to me the best path for now is to have a toggle for the global CB and all other CBs and glslang can optionally pack by std140 or DX rules.  Maybe?

**Comment by johnkslang** [comment]
My summary, @danginsburg, see if I got it right. There are two choices that make sense:

A. Fix reflection to match current SPIR-V layout. (The current problem is reflection is done before SPIR-V generation, and assumes std140, and then later the SPIR-V generator realizes it can pack better and does so.)

B. Change SPIR-V layout of $Global to be the old non-DX std140 way, which would match what is currently reflected.

Both these methods could work, because apps rely on reflection for $Global, not on implicit layout rules. And, the problem with A really should be fixed, but is not quite trivial because it is different components run at different times looking at things differently.

Choice B seems the more conservative (safer) approach.  Yes? So, the action plan would be to implement choice B, and later follow up with fixing the problem mentioned in A.

Yes?

**Comment by danginsburg** [comment]
> Choice B seems the more conservative (safer) approach. Yes? So, the action plan would be to implement choice B, and later follow up with fixing the problem mentioned in A.

Yes, that seems reasonable.

**Comment by johnkslang** [comment]
PR #987 address choice B. I'm worried if it breaks anything that relied on the other way, so is a PR for now.

**Comment by danginsburg** [comment]
I sync'd master containing PR #987 and confirm it fixes the issue I was seeing.

**Comment by johnkslang** [comment]
#933 captures the remaining issue here, closing this one.
