### ISSUE TITLE
GLSL: Missing MemberDecorate ops in SPV code

### ISSUE THREAD

**Issue by LKostyra** [KhronosGroup/glslang#984]
Consider following GLSL fragment shader code:

```
layout (location = 0) in VertexShaderOutput
{
    vec3 Norm;
    vec2 UV;
} Input;

layout (location = 0) out vec4 color;

layout (set = 1, binding = 0) uniform sampler2D tex;

void main()
{
    color = texture(tex, Input.UV);
}
```

Newest version of glslang (`652db16`, master as of 12th July, 2017) produces following SPV code:

```
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 26

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9 19
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              SourceExtension  "GL_ARB_separate_shader_objects"
                              SourceExtension  "GL_ARB_shading_language_420pack"
                              Name 4  "main"
                              Name 9  "color"
                              Name 13  "tex"
                              Name 17  "VertexShaderOutput"
                              MemberName 17(VertexShaderOutput) 0  "Norm"
                              MemberName 17(VertexShaderOutput) 1  "UV"
                              Name 19  "Input"
                              Decorate 9(color) Location 0
                              Decorate 13(tex) DescriptorSet 1
                              Decorate 13(tex) Binding 0
                              Decorate 17(VertexShaderOutput) Block
                              Decorate 19(Input) Location 0
// cut further code, not important
```

The code above (compared to older version of glslang) does not have two MemberDecorate ops, which point GPU to whatever Vertex Shader outputs (the contents of VertexShaderOutput block). Older versions of glslang added following:

```
                              MemberDecorate 17(VertexShaderOutput) 0 Location 0
                              MemberDecorate 17(VertexShaderOutput) 1 Location 1
```

Without it the UV coordinates received in Fragment Shader are random, as if their data was taken from a random place in memory. Compiling the code with glslangValidator attached to Vulkan SDK 1.0.42.1 does not have this issue.

Env: Windows 10 Creators Update, GTX 1070 (latest 384.76 drivers), Vulkan SDK 1.0.42.1

**Comment by johnkslang** [comment]
The locations were previously over specified (doubly specified) in the generated SPIR-V. This was logged as an issue to fix.

Subsetting the new SPIR-V you quoted:

```
                              Decorate 19(Input) Location 0
17(VertexShaderOutput):             TypeStruct 15(fvec3) 16(fvec2)
              18:             TypePointer Input 17(VertexShaderOutput)
```

There is still location information on the structure, as per what the specification says, which includes rules for how a whole structure consumes locations. It was considered incorrect by some vendors to also re-specify the member locations. This PR was pending for some time, and we did let driver vendors know about it and have time to provide input.

To implement the spec and to make all cases work, drivers had to implement `Location` at the struct level, so this sounds like a defect in a driver.

**Comment by LKostyra** [comment]
Indeed, it looks like a driver error. Sorry about that and thanks for the explanation. I'll stick with the old-fashioned input/output declarations without structures for now on, as they seem to work fine.

Thanks for the reply.

**Comment by johnkslang** [comment]
Well, I am also concerned with any driver issues. Can you also submit this to the drivers you see the issues with?
