### ISSUE TITLE
Uniform variables in unsized arrays of structs do not appear in shader reflection data

### ISSUE THREAD

**Issue by haddoncd** [KhronosGroup/glslang#985]
When compiling a vertex shader that uses shader storage buffer objects to access variable sized arrays of "uniform" data, the reflection data generated does not include the fields accessed through the variable sized array when it is an array of structs (see example 1, below).

This is in contrast to both the case where the array is statically sized and the case where the array is of a basic type, in which the expected fields do appear in the reflection data (see examples 2 & 3 respectively).

Looking at the code in `reflection.cpp` (specifically in `TReflectionTraverser::blowUpActiveAggregate()`), it appears that when processing a dereference chain containing a variable array subscript operator (`EOpIndexIndirect`) it will neither recurse into any indices of the array (since `getOuterArraySize()` returns zero for unsized arrays) nor proceed to add the entire array as a single uniform variable (since `isReflectionGranularity()` correctly determines that the array is an aggregate that needs further expansion).

In the case of example 3, however, the reflection data includes uniform variable `d` despite it being an unsized array. I think this is because the construction of the dereference chain in `addDereferencedUniform()` omits the final subscript operator, preventing `blowUpActiveAggregate()` from "dropping" the uniform variable.

### Examples

1. Unsized array of structs (problem case)
```glsl
#version 430 core

struct PerInstanceDataType
{
  vec4 a;
  vec4 b;
};

layout(std430, binding = 0) buffer BufferDataType
{
  vec4 c;
  PerInstanceDataType instances[];
} bufferData;

void main()
{
  gl_Position = bufferData.instances[gl_InstanceID].a +
                bufferData.instances[gl_InstanceID].b +
                bufferData.c;
}
```
```
Uniform reflection:
BufferDataType.c: offset 0, type 8b52, size 1, index 0, binding -1

Uniform block reflection:
BufferDataType: offset -1, type ffffffff, size 16, index -1, binding 0

Vertex attribute reflection:
gl_InstanceID: offset 0, type 1404, size 0, index 0, binding -1
```

2. Static sized array of structs (OK)
```glsl
#version 430 core

struct PerInstanceDataType
{
  vec4 a;
  vec4 b;
};

layout(std430) buffer BufferDataType
{
  vec4 c;
  PerInstanceDataType instances[2];
} bufferData;

void main()
{
  gl_Position = bufferData.instances[0].a +
                bufferData.instances[1].b +
                bufferData.c;
}
```
```
Uniform reflection:
BufferDataType.instances.a: offset 16, type 8b52, size 1, index 0, binding -1
BufferDataType.instances.b: offset 32, type 8b52, size 1, index 0, binding -1
BufferDataType.c: offset 0, type 8b52, size 1, index 0, binding -1

Uniform block reflection:
BufferDataType: offset -1, type ffffffff, size 80, index -1, binding -1

Vertex attribute reflection:
```
  * I note that the names of the uniforms as shown in the reflection data do not include the array subscript (i.e. `BufferDataType.instances[0].a`) - I did not expect this, but it appears to be intentional; the code in `blowUpActiveAggregate()` explicitly avoids adding any subscript to the name when the base type is a block.

3. Unsized array of basic type (OK)
```glsl
#version 430 core

layout(std430, binding = 0) buffer BufferDataType
{
  vec4 c;
  vec4 d[];
} bufferData;

void main()
{
  gl_Position = bufferData.c + bufferData.d[gl_InstanceID];
}
```
```
Uniform reflection:
BufferDataType.c: offset 0, type 8b52, size 1, index 0, binding -1
BufferDataType.d: offset 16, type 8b52, size 0, index 0, binding -1

Uniform block reflection:
BufferDataType: offset -1, type ffffffff, size 16, index -1, binding 0

Vertex attribute reflection:
gl_InstanceID: offset 0, type 1404, size 0, index 0, binding -1
```

**Comment by johnkslang** [comment]
The problem case starts working if you change `gl_InstanceID` to `2` because of the difference between having no constant indexes or having a constant index.

I'll map the no-known-size case to always visit at least the first element.
