### ISSUE TITLE
Constructor not using default precision qualifer

### ISSUE THREAD

**Issue by chaoc** [KhronosGroup/glslang#999]
In GLES, precision of an operation should depend on precision of all operands. as illustrated by following example in GLES 3,2 Section 4.7.3:
>m = 3.7 * h1 * h2; // all operations are highp precision

SPIR-V spec 1.0 Section 2.14 mentions the result id will be determining the precision of an operation:
>The Result <id> of an instruction that operates on numerical types, meaning the instruction is to operate at relaxed precision.

When given the following GLSL code, glslang seems to incorrectly generate the `ConvertSToF ` and `FDiv` operation in `RelaxedPrecision`.
``` 
#version 310 es
precision highp float;

in highp int a;

out mediump float d;

void main ()
{
	d = float(a) / 0.333f;
} 
```

```
                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 8 11
                              Source ESSL 310
                              Name 4  "main"
                              Name 8  "d"
                              Name 11  "a"
                              Decorate 8(d) RelaxedPrecision
                              Decorate 13 RelaxedPrecision
                              Decorate 15 RelaxedPrecision
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypePointer Output 6(float)
            8(d):      7(ptr) Variable Output
               9:             TypeInt 32 1
              10:             TypePointer Input 9(int)
           11(a):     10(ptr) Variable Input
              14:    6(float) Constant 1051361018
         4(main):           2 Function None 3
               5:             Label
              12:      9(int) Load 11(a)
              13:    6(float) ConvertSToF 12
              15:    6(float) FDiv 13 14
                              Store 8(d) 15
                              Return
                              FunctionEnd
```

I believe this is due to constructors currently lacks a logic to set the default (or global) precision and has a the default value of `EpqNone`, which will be propagate over by the result's `EbqMedium` in the example. (`EpqNone` < `EpqLow` < `EpqMedium` < `EpqHigh`)

To correct this issue, we could add something for builtin functions in glslang.y to set the default precision value for `EEsProfile`. Or perhaps we could eliminate the usage of `EbqNone` for non constant in `EEsProfile` since we should always have a default that is ordered correctly.

**Comment by johnkslang** [comment]
Before getting too deep into this complex space, I have a clarifying question.

The issue title is about built-in functions, but the example is about a constructor?  Is the problem about constructors specifically?

**Comment by chaoc** [comment]
Hi John

Sorry for the language, it should be the constructors and I have updated the title and description.

**Comment by johnkslang** [comment]
I'll have a go at fixing this, or seeing what's going on.

**Comment by johnkslang** [comment]
Glslang is doing what the specification says it should do.

From the spec:

> Literal constants do not have precision qualifiers. Neither do Boolean variables. Neither do constructors.

Followed by:

> In cases where operands do not have a precision qualifier, the precision qualification will come from the other operands. If no operands have a precision qualifier, then the precision qualifications of the operands of the next consuming operation in the expression will be used. ... If necessary, it will also include the precision qualification of lvalues for assignments.

So, not sure there is anything to do.  Glslang has also been used in the past to drive precision qualifications into a driver, and that was working.

So, it seems this example has an incorrect expectation. Is this workload derived from a compiler that did not implement the above rules from the specification?

**Comment by johnkslang** [comment]
I could see it being a reasonable spec change to say `float(a)` inherits the precision qualification of `a`, instead of the precision of the operations around it.  The existing rationale would be that

```
mediump int i = int(expr);  // after expr is evaluation it's internal precision, only
                            // need a mediump result
```

Is the real problem the precision of the divide, not the precision of the conversion?

**Comment by chaoc** [comment]
The real problem was the precision of the divide not happening at high precision. But according to the part of the spec that describe the constructor, I agree glslang is doing it correctly. So this should not be a glslang bug. Would you like me to close it?

**Comment by johnkslang** [comment]
Since we agree to close, I'll close now, thanks.
